### ISSUE TITLE
TypeCastError isn't raised when casting scalar value

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#10021]
https://play.crystal-lang.org/#/r/a1tf

```cr
1.as String
```

```
Showing last frame. Use --error-trace for full trace.

error in line 1
Error: can't cast Int32 to String
```

I would have expected this to work like the example in the API docs, where it actually raises a [TypeCastError](https://crystal-lang.org/api/master/TypeCastError.html).

**Comment by jhass** [comment]
`TypeCastError` is a runtime error, it happens when resolving a union to a type that doesn't match its actual value at runtime.

You're looking at a compile error here.

Also remember, casting is interpreting the same value (the same bytes) as a different type. Conversion is producing an equivalent or comparable value in a different type. `as` does casting only.

**Comment by Blacksmoke16** [comment]
Ahh rip, don't mind me 🙈.
