### ISSUE TITLE
Unable to set custom status message with custom headers in HTTP::Server::Response

### ISSUE THREAD

**Issue by LeXofLeviafan** [crystal-lang/crystal#10038]
`HTTP::Server::Response` has a field `@status_message` which defaults to `nil` (thus falling back to `@status.description`) and it can only be altered via `#respond_with_status()` method (unlike `@status` which is a writable property). However, since `#respond_with_status()` resets the response stream and then closes it, it's impossible to provide custom headers (e.g. for CORS) along with custom status message.

I would say it's a bug, since if you're allowing to provide a custom status message in the first place, it should be available for modification with the same rules as the status code (that is, I should be able to alter it at any time before the headers are written to the stream). I suggest changing it to either a regular property, or supply it with a regular setter along with a getter that falls back to `@status.description`.

**Comment by straight-shoota** [comment]
I think the idea behind `respond_with_status` resetting the headers was that the headers might already set up for a successful response and then an error response shouldn't use those headers. I'm not sure that's a good idea though, because it's really unexpected when I set a header before `respond_with_status` and then it doesn't show up.

```cr
response.headers["Foo"] = "Bar"
response.respond_with_status(418, "I'm a teapot")
```

Maybe we should  really change `respond_with_status` to *not* reset the response. If you want that behaviour, you could always reset the headers manually.

This method is also completely broken when headers have already been sent, because the reset causes that flag to disapear and `respond_with_status` just writes a second response. https://carc.in/#/r/a2ha

That aside, it also makes sense to make `status_message` writable because it should also be possible to set the status message while writing content to the response body. With `respond_with_status` this is not possible.

**Comment by LeXofLeviafan** [comment]
> I'm not sure that's a good idea though, because it's really unexpected when I set a header before `respond_with_status` and then it doesn't show up.

That's exactly how I found out about this particular behavioural detail, actually :-D

> Maybe we should really change `respond_with_status` to _not_ reset the response.

It can be made optional, I'd say. it can even default to reset (as that seems to be the intended usage), but the main problem of course is that this method is *the* only way that `status_message` can be specified (unlike `status` itself).

> This method is also completely broken when headers have already been sent, because the reset causes that flag to disapear and `respond_with_status` just writes a second response. https://carc.in/#/r/a2ha

Now this one looks like a separate bug (and should probably be posted as a separate issue)… Although it does add on to the problem of reset behaviour.

**Comment by potomak** [comment]
@straight-shoota I think you completed the things to do for this issue with the two PRs above. Is there anything else to do or can you close the issue?
