### ISSUE TITLE
The Trivial class `class U; end` Doesn't Compile

### ISSUE THREAD

**Issue by toddsundsted** [crystal-lang/crystal#10153]
The following code does not compile (https://play.crystal-lang.org/#/r/a6a0):
```crystal
class U
end
```
Diagnostics:
```
In /usr/lib/crystal/comparable.cr:83:16

 83 | abstract def <=>(other : T)
                   ^--
Error: abstract `def Comparable(T)#<=>(other : T)` must be implemented by Slice(T)
```

Trivial changes (using any other letter than `U`) work.

Interestingly, a trivial modification to `Slice(T)` makes the error go away: just replace the type restriction variable `U` in the definition of `<=>` with something else, however this just moves the problem to another trivial class (replacing `U` witih `Zee` breaks the trivial class named `Zee`).

I'm still exploring, but I think this may be related to https://github.com/crystal-lang/crystal/issues/9173.

I'm  using Crystal v.0.35.1.

**Comment by HertzDevil** [comment]
We have:

```crystal
module Comparable(T)
  abstract def <=>(other : T)
end

struct Slice(T)
  include Comparable(Slice)

  def <=>(other : Slice(U)) forall U
  end
end

class U
end
```

What happens here is the compiler tries to match `other : Slice(U)` against `other : T`, but that `T` is assigned the `Slice` type (which is distinct from `Slice(T)` by the way), due to the generic include. Currently, abstract def lookup doesn't consider free vars:

https://github.com/crystal-lang/crystal/blob/cb09b0e218768c759f261424f10a0abb48edff0f/src/compiler/crystal/semantic/abstract_def_checker.cr#L239-L260

#10155 considers them, but this still fails because the PR currently ignores types substituted through generic inheritance/includes. As type lookup now succeeds, `Slice(U)` is obviously not substitutable for `T` or `Slice`, because the former is an instantiated generic and the latter isn't.

Supposing free vars are checked, the compiler would then determine that `Slice(U) forall U` is substitutable for `T` or `Slice`. That's fine for this case but if there is more than one type var the results would be different (that doesn't affect this issue though).

**Comment by toddsundsted** [comment]
thanks @HertzDevil

why does this become a problem only for the class named `U`? upon failing to match `Slice(U)` does the compiler then see `U` as the class instead of a type variable?

**Comment by HertzDevil** [comment]
Turns out some of those generics aren't necessary:

```crystal
module Foo
  abstract def foo(x : Int32)
end

class Bar
  include Foo
  
  def foo(x : Quux) forall Quux # okay
  end
end
```

```crystal
module Foo
  abstract def foo(x : Int32)
end

class Bar # Error: abstract `def Foo#foo(x : Int32)` must be implemented by Bar
  include Foo
  
  def foo(x : Quux) forall Quux
  end
end

class Quux
end
```
