### ISSUE TITLE
Base64 doesn't need to be required anymore

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#10323]
I was very surprised by this.

It turns out, Random has two methods, `base64` and `urlsafe_base64`, and Random is required by default.

I really think those two methods should belong to `Base64`. Or, they should be available only if you require base64.

**Comment by straight-shoota** [comment]
This has actually been the case for a long time: https://github.com/crystal-lang/crystal/commit/27684db49083bfd95f27a90321cf7c0817929f8e#diff-e9984061c5b69d5e06e5f0599cbb11e9ed3277fac516f81c45cc832e8b7a9da3R1

Those methods are there for convenience. 

It's probably not a good idea to let individual methods of a type depend on requiring another library. That would be really awkward.

This is different from `require "json"` for example defines `#to_json` methods on types from other libraries in order to implement a generic interface.

I don't think there's a strong enough reason to break this. Whether `base64` belongs to core lib or not isn't such a big deal. I vote for practical usability.
