### ISSUE TITLE
@type is not instantiated in macro finished

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#10354]
The following code shows that `@type` in macros is not instantiated inside macro finished hook. The same macro method will expand to different code if it's declared outside the macro hook.

```crystal
class MyBox(T)
  def f
    {{@type.type_vars.first.stringify}}
  end

  macro finished
    def g
      {{@type.type_vars.first.stringify}}
    end
  end
end

box_int = MyBox(Int32).new
pp! box_int.f # => "Int32"
pp! box_int.g # => "T", expected "Int32"

box_str = MyBox(String).new
pp! box_str.f # => "String"
pp! box_str.g # => "T", expected "String"
```

Present at least since Crystal 0.30.1

Related to #6757

**Comment by asterite** [comment]
This works 😉 

```crystal
class MyBox(T)
  def f
    {{@type.type_vars.first.stringify}}
  end

  macro finished
    def g
      \{{@type.type_vars.first.stringify}}
    end
  end
end

box_int = MyBox(Int32).new
pp! box_int.f # => "Int32"
pp! box_int.g # => "T", expected "Int32"

box_str = MyBox(String).new
pp! box_str.f # => "String"
pp! box_str.g # => "T", expected "String"
```

Note the `\{{...}}`.

**Comment by asterite** [comment]
To expand on the above a bit more...

If you do this:

```crystal
  macro finished
    {{ puts @type }}
```

you will see that "MyBox(T)" gets printed. That's because `finished` is called once for the uninstantiated generic type. Now becuase there's `{{...}}` inside the method definition it's expanded right away. It's **not** expanded differently on every invocation.

If you use `\{{...}}` that will produce macro code to be expanded when the method is invoked. At that point `@type` will be the instantiated type and this will work as expected for this use case.

So to me this is not a bug, it's just that nesting macros is confusing... maybe intrinsically.
