### ISSUE TITLE
Top-level program exits while there are live fibers, doesn't complain, no good way to wait.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#10363]
The top-level program exits while there are live fibers, killing them. It doesn't complain. There isn't really a good means to wait for them.
```crystal
fiber = spawn do
  sleep 2
  STDOUT.puts "The fiber completed."
end
p fiber.dead?
```

The only thing I can think of to wait for live fibers to complete is to keep a container of all spawned fibers, and to scan through it every second or so checking for `Fiber#dead?`.

**Comment by asterite** [comment]
The usual pattern for doing this is:

```crystal
chan = Channel(Nil).new
fiber = spawn do
  sleep 2
  chan.send(nil)
end
chan.receive
STDOUT.puts "The fiber completed."
```

More specifically I think a [WaitGroup](https://golang.org/pkg/sync/#WaitGroup) like the one they have in Go would suit your needs. But that doesn't exist yet. Maybe there's a shard for that.

In any case this is by design. I also suggested that, if in doubt of if something is a bug or not, to open a discussion in the forums.

**Comment by straight-shoota** [comment]
For completeness: Fibers are very low level. After launching a new fiber, the runtime doesn't keep track. It doesn't care wether a fiber is supposed to keep running or should finish when the program exits.
You can do so explicitly with channels or higher level concurrency constructs like wait groups or nurseries (see #6468).
