### ISSUE TITLE
Multiple assignment is not allowed for constants

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#10433]
I was trying to have a method that returned an array of the subclasses for runtime use, but since the subclasses method is a macro level method, I had to dynamically generate my array. When I did this, I got the error

```
Called macro defined in eval:4:5

Which expanded to:

 > 1 | 
 > 2 |     One,
               ^
Error: Multiple assignment is not allowed for constants
```

```crystal
abstract class Base
  def self.subs
    [
    {% for s in Base.all_subclasses %}
    {{ s }},
    {% end %}
    ]
  end
end
 
class One < Base
end
 
# If you get rid of this line, it compiles... 🤔
pp Base.subs
```

Now, if I write it out manually, it all works fine

```crystal
abstract class Base
  def self.subs
    [
    One,
    ]
  end
end
 
class One < Base
end
 
pp Base.subs
```

**Comment by straight-shoota** [comment]
The reason is that the macro expansion is delimited by the `for` and `end` tags. The square brackets are not part of the macro-generated code because they are outside the macro tag.

The generated code is parsed and the resulting AST replaces the macro expression in the original AST. The macro generates `One,` which is not a valid expression. Hence the compiler errors.

The solution is to wrap the entire array literal in `{% begin %}...{% end %}`. 

```cr
abstract class Base
  def self.subs
    {% begin %}
    [
    {% for s in Base.all_subclasses %}
    {{ s }},
    {% end %}
    ]
    {% end %}
  end
end
 
class One < Base
end

pp Base.subs # => [One]
```

This is always necessary when a macro expansion produces a partial expression (except in bodies of macro methods).

There's a section in the language reference about this: https://crystal-lang.org/reference/syntax_and_semantics/macros/index.html#pitfalls

**Comment by straight-shoota** [comment]
Your use case might be more complex, but for this example you could also use something like this:
```cr
  def self.subs
    {{ Base.all_subclasses }}
  end
```

The values can also be transformed with `#map` in the macro expression.

**Comment by jwoertink** [comment]
Ah. ok. Awesome. Thanks for that explanation. I guess I just need to understand macros a bit better 😅  Since this is just a "me" issue, we can close this.
