### ISSUE TITLE
Invalid memory access on Linux

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#10466]
I ran in to an error (unrelated) and went digging for a related issue, and found https://github.com/crystal-lang/crystal/issues/8411 which @asterite  had [some code example](https://github.com/crystal-lang/crystal/issues/8411#issuecomment-548779754). 

I ran this code example.

```crystal
class Foo
end
 
class Baz(T) < Foo
  def baz
  end
end
 
f = uninitialized Foo
if f.is_a?(Baz)
  puts f.baz
end
 
Baz(Int32).new
```

It turns out, that on macOS, it's fine. 

```
Crystal 0.36.1 (2021-02-02)

LLVM: 11.0.1
Default target: x86_64-apple-macosx
```

It compiles, and runs with no output just fine. However, on Linux, that code sample throws `Invalid memory access`

```
Invalid memory access (signal 11) at address 0x0
[0x55effbfd6346] *Exception::CallStack::print_backtrace:(Int32 | Nil) +118
[0x55effbfc9bdc] __crystal_sigfault_handler +316
[0x7f42b16df0f0] ???
[0x55effbfbbc53] __crystal_main +1107
[0x55effc033396] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +6
[0x55effc03320c] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +44
[0x55effbfc70d6] main +6
[0x7f42b14a4152] __libc_start_main +242
[0x55effbfbb72e] _start +46
[0x0] ???
```

```
Crystal 0.36.1 [c3a3c1823] (2021-02-02)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by bcardiff** [comment]
I think you were just lucky. Accessing an uninitialized variable is unsafe. Even the is_a? Is accessing some part of the structure.

**Comment by jwoertink** [comment]
So does that mean that the error is on the mac and it should have exploded? 😅

**Comment by bcardiff** [comment]
Pretty much. You are accessing potentially random data and the behavior is undefined. In simple value types an undefined will not cause a crash. But on reference types a type_id is present at the beginning of the memory. The compiler assumes that that value will make sense. With uninitialize you are asking (or forcing) the compiler to trust you.

**Comment by jwoertink** [comment]
Everyone should just trust me 😈  😂

**Comment by BrucePerens** [comment]
Maybe a difference between platforms regarding page 0 or initialization of memory. Linux gives you all zeroed memory, the first time your process asks for it, so that you don't see data from other processes. Most modern OSs make page 0 inaccessible, so that the most common wild pointer will get a signal.

**Comment by straight-shoota** [comment]
I don't think this requires any action. `uninitialized` is unsafe and accessing an uninitialized variable is undefined behaviour. It can explode, especially with reference types. Because it's undefined, there is no guarantee it exploded the same way on all platforms.

The deal with `uninitialized` is that it can pretty much only be used to give a variable a default stand-in value. But the code should make sure that this value can never ever be accessed.
