### ISSUE TITLE
flake.nix

### ISSUE THREAD

**Issue by kimburgess** [crystal-lang/crystal#10509]
## Discussion

With the upcoming v1.0.0 release (yay!) is there interest in a transforming the existing `shell.nix` into a `flake.nix`?

For those not familiar, some [background on Flakes](https://nixos.wiki/wiki/Flakes).
<sub>TL;DR this provides a method for projects to reference specific compiler versions via commits / tags within this repo.</sub>

Reasons for this:
1. Functionality provided by the existing `shell.nix` will be preserved.
2. It will also provide a canonical reference for projects using crystal and nix together.
3. Remove duplication of effort in nixpkgs.

Reasons for doing this now:
1. It will provide this reference from 1.0.0.

Reasons not to do this:
1. There's an [existing set of packaging tools](https://github.com/crystal-lang/distribution-scripts), that live outside of this repo.
2. Flakes is still an experimental feature.
3. Nix packaging of Crystal is [actively maintained in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/crystal/default.nix) by some very awesome people.

_If_ this is of use, please let me know and I'll get to work on a PR.

**Comment by straight-shoota** [comment]
I'm really not very familiar with the nix ecosystem. And I don't think any other core developer is experienced either.

Currently, `shell.nix` is primarily used for running [Github Actions on macos](https://github.com/crystal-lang/crystal/blob/7aa9e98a195a2da63f703be36e5694074a1179a9/bin/ci#L203). Maybe some developers also use it for a local development environment. I guess migrating to flake shouldn't break any of that? It probably doesn't break anything at all, right? It's just a different way and allows doing the same things (plus more)?
Although it looks like flake support is not enabled by default, so in order to use it, you need to explicitly install/enable it. So maybe that would be a reason to wait until flakes are a stable feature.

I think it could be worth exploring to switch to Nix for several infrastructure tasks. This might give an opportunity to improve and simplify the CI and distribution workflows. So reason-not-to-do-this number 1 could even be a reason-to-do-this (assuming flake gives any benefit for that, if not it's just mute).

Could you elaborate on the reason-not-to-do-this number 3? As far as I understand it `flake.nix` works similar to `shard.yml` for defining dependencies and `shards`/`nix flake` installs dependencies from source repositories and also resolves transitive dependencies defined in dependencies' `flake.nix`/`shard.yml`.
But this likely wouldn't replace the crystal package on nixpkgs, would it? The toolchain for building the compiler needs different dependencies than just the compiler distribution package. As another analogy, I'd assume the `flake.nix` configuration would resemble (and possibly even replace) the `*-build` docker images including compiler build tools, whereas the nigpkgs package would resemble the `*` docker images with just the compiler itself and stdlib dependencies.

**Comment by kimburgess** [comment]
@straight-shoota right on with your `flake.nix` ~ `shard.yml` comparison. That structure of a file declaring immediate deps, with a lock file that pins resolved transitive deps is exactly the pattern. In addition to inputs though `flake.nix` also declares a [set of outputs](https://nixos.wiki/wiki/Flakes#Output_schema) and how these should be built. This includes a `devShell` (which replaces `shell.nix`), as well as the build outputs for various arch's. You may also be able to use the `nixosConfigurations` output to define deterministic docker builds, but haven't played with that personally.

@bcardiff the experimental status is definitely a good reason to wait. If time allows, I'll have a play in a fork with a Flakes setup that provides some of those build outputs for non NixOS systems and docker images. By time that's happened, it may be out of experimental phase and can hopefully submit a PR for consideration that covers those needs. If there's a desire to keep this seperate at that point, no stress either.
