### ISSUE TITLE
NilLiteral.nil? return false

### ISSUE THREAD

**Issue by erdnaxeli** [crystal-lang/crystal#10534]
Hi,

As the title says:
```Crystal
{% puts nil.nil? %}
```
> false

I am not sure this is a bug, `NilLiteral` is not `nil`, but it feels weird.

Tested with 0.36.1, as 1.0.0 is not yet available on playgrounds.

**Comment by straight-shoota** [comment]
The parser transforms `nil.nil?` to `nil.is_a?(Nil)`. In regular code that is correct and works as expected. But in the macro language the type of `nil` is `NilLiteral` and `.is_a?(Nil)` returns false.

I don't think `.nil?` was ever intended for the macro language. It just happens to be accepted by the compiler because of the implicit transform to IsA.

We could fix the behaviour or let `.nil?` be undefined in the macro language.

It's not really necessary there. The reason for `.nil?` in the regular language is to provide a reliably way for the compiler to identify nil types without the equality operator which can be overriden in user code.
But in the macro language that's not an issue anyways, so every `x.nil?` could just be written as `x == nil`.

It doesn't seem that `.nil?` is used that much in macro expressions anyways, otherwise it should have long been noticed that it's completely broken.
