### ISSUE TITLE
request: File cp/mv/rm

### ISSUE THREAD

**Issue by elia** [crystal-lang/crystal#1058]
Those are on FileUtils in Ruby

I don't have any particular opinion about where they should go (File, Dir, FileSystem, FileUtils, …)

**Comment by strcmp** [comment]
yeah it'd be nice to have those methods, and maybe mkdir/mkdir_p too. crystal has its own [FileUtils](https://github.com/manastech/crystal/blob/master/src/file_utils.cr) but there's not a lot there. I don't have a strong feeling either way though.

**Comment by asterite** [comment]
If somebody wants to tackle this, we'll be more than happy to merge pull requests for this. Ideally File/FileUtils should be in Crystal.

**Comment by daviswahl** [comment]
I'd be happy to take this on as long if no one else wants to claim it.

**Comment by daviswahl** [comment]
Accidentally deleted my comment -- I would be happy to take this on, but on second thought this is low level C stuff which I really shouldn't be getting involved in.

**Comment by kirbyfan64** [comment]
I would love trying this! I have pretty much memorized half the Posix filesystem functions from using them in C++. :O

**Comment by elia** [comment]
> I would be happy to take this on, but on second thought this is low level C stuff which I really shouldn't be getting involved in.

Same here

@kirbyfan64 <3

**Comment by kirbyfan64** [comment]
Are `rm` and `mv` really needed? Can't one already use `File.delete` and `File.rename`?

**Comment by ysbaddaden** [comment]
They're nice in FileUtils since Rake includes it, so we can go shell-like in tasks. I'm not sure they're so interesting in Crystal.

**Comment by EvanHahn** [comment]
I agree with @kirbyfan64 here:

> Can't one already use `File.delete` and `File.rename`?

**Comment by ysbaddaden** [comment]
That depends: if we want `FileUtils.rm_r` and `FileUtils.rm_rf` then not having `FileUtils.rm` might be weird. Same for `mv` since `File.rename` could feel odd:

```crystal
include FileUtils

cp src, dst
File.rename dst, dst2
rm_rf dst2
```

That being said, these methods would be aliases, and maybe we don't want shell-induced naming, so we could prefer better method names in File and Dir, like `Dir.delete(path, recursively: true)` or `Dir.copy(src, dst)` and have a shard provide FileUtils instead.

**Comment by asterite** [comment]
Yes, I'm still unsure about what's the best thing to do here: have separate methods in File, Dir, etc. Or have them all in FileUtils with unix-like names. Or have both.

Having both is really not a bad option, because if your code needs to do "bashy" stuff then it will look similar to bash, and if you need to rename a file here and there you can just use `File.rename` instead of `File.mv`. These are like aliases but probably don't bother much. Aliases are mostly a problem when all of them need to be in related types (like the case of length/size/count in String, Array, Hash, Deque and possibly other containers), because if I want to add a new container I have to remember to implement all these aliases.

**Comment by ysbaddaden** [comment]
Sounds good to me.

**Comment by sevk** [comment]
can we auto convert from  this file : https://github.com/ruby/ruby/blob/trunk/lib/fileutils.rb

**Comment by sdogruyol** [comment]
@spalladino since https://github.com/crystal-lang/crystal/pull/3420 is merged can we close this?

**Comment by spalladino** [comment]
Certainly! Thanks for spotting this @sdogruyol :-)

**Comment by sdogruyol** [comment]
@spalladino gracias 👍
