### ISSUE TITLE
[RFC] Add optional `default` argument to `try`

### ISSUE THREAD

**Issue by caspiano** [crystal-lang/crystal#10675]
I've noticed a common pattern around the place along the lines of 

```crystal
some_nillable_value.try { |v| foo(v) } || "a default"
```

This can lead to bugs in cases where the try block intentionally returns a falsey value, leading to the unexpected assignment of the default value. 

I'm proposing the addition of `Nil#try(default, &block)` and `Object#try(default, &block)` to provide an alternative

```crystal
# Old
some_nillable_value.nil? ? "a default" : foo(some_nillable_value)

# New
some_nillable_value.try("a default") { |v| foo(v) }
```

Alternative syntax, `try_or`

```crystal
some_nillable_value.try_or(default: "something") { |v| foo(v) }

collection.try_or(0, &.size)
```

**Comment by straight-shoota** [comment]
Looks like a nice idea. I can definitely see the use case.

Having a few doubts about readability, though. Not sure how easy it is to understand the purpose of the argument. It doesn't feel very natural.

**Comment by jhass** [comment]
Haha, I had the same idea the other day.

Maybe a little more verbose is okay?

```cr
some_nillable_value.try(or_else: "a default") { |v| do_thing(v) }
```

**Comment by caspiano** [comment]
@kimburgess suggested `value.try_or(default, &block)`

**Comment by straight-shoota** [comment]
I think it's worth mentioning that a default *argument* may not be as efficient as the alternative, a conditional expression.
The reason is that the expression providing the `default` argument is always executed, even if the target is not `nil`. When it's a literal or variable for example, this doesn't matter.
But a method call could really be avoided when `default` is not necessary at all.

Because of this, methods like `#fetch` which also receive a default argument have a yielding variant where the block provides the default value only when necessary. With `#try` this is not possible because the block arg is already taken.

Despite this, the `default` argument may still be useful for trivial cases (or when such efficiency optimization is not relevant). But taking this aspect into consideration, I'm not sure if it's a good idea to add this. The alternative is not as concise, but IMO easier to reason about and potentially more efficient.

**Comment by asterite** [comment]
Agreed, I don't see a huge advantage in terms of readability or the amount of code you have to type. Instead, it might add confusion (I initially thought the default value was used if the result of the `try` expression returned `nil`)

I would actually write it more verbosely, like this:

```crystal
if some_nillable_value.nil?
  "a default"
else
  foo(some_nillable_value)
end
```

In some cases `some_nillable_value` might even not include `Bool`, in which case in part of the code you can probably do:

```crystal
return "a default" unless some_nilable_value

foo(some_nilable_value)
```

I don't know, I don't feel this new `try` variant is needed.
