### ISSUE TITLE
Symbol autocasting flag enum

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#10680]
One of the main features of symbols is the ability to auto cast into an enum member.  However symbol auto casting does not currently support flag enums when more than 1 member is used.  E.g.

```crystal
@[Flags]
enum Foo
  One
  Two
end

pp Foo::One | Foo::Two # => One | Two
pp :two | :one         # => Error: undefined method '|' for Symbol
```

I propose to expand the autocasting functionality to also support multiple members.  This will ultimately need to be done if we want to move forward with removing manual symbols holistically, ref: #6736.

The main usecase for this is to just reduce the amount of typing when multiple members are needed.  Currently the expression can be quite long, especially if the enum is namespaced.

**Comment by asterite** [comment]
Can't be done, sorry. What's the type of `:two | :one` and how do you compute it?

**Comment by asterite** [comment]
To explain a bit more, the compiler will first type-check a call's arguments. Once all types are defined it can start searching matches. In the case of a Symbol type, if the argument is a SymbolLiteral it will try to do autocasting. But here it would be different because there's no way the compiler can type `:two | :one`.

**Comment by straight-shoota** [comment]
I suppose technically, the compiler could get similar special handling for calls to `|` with symbol literals. Or, expressed differently: `SymbolLiteral | SymbolLiteral` could just be a language feature, say a `CombinedSymbolLiteral`. It is only valid where the type can be inferred and autocasting would be similar to `SymbolLiteral`. The only exception is, it only works with flag enum types.

That sounds feasible to me. Yet, I don't think it's high priority. Although I fully relate to the motivation for this, and it would be really nice to have.

**Comment by Blacksmoke16** [comment]
As a workaround for now, I recently discovered the `.flags` macro which allows for `Some::Long::Namespace::Colors.flags RED, BLUE` instead of `Some::Long::Namespace::Colors::RED | Some::Long::Namespace::Colors::BLUE`, which is about half the length.

**Comment by straight-shoota** [comment]
As long as the first flag is properly typed as a flags enum member, all the following ones can be symbol literals because autocasting of [`Enum#|(other : self)`](https://crystal-lang.org/api/1.3.2/Enum.html#%7C%28other%3Aself%29%3Aself-instance-method) applies:

```cr
Foo::One | :two
```

This should work pretty well as a simplified workaround. You only need the full path once.
I think it reads better than [`Enum.flags?`](https://crystal-lang.org/api/1.3.2/Enum.html#flags%28%2Avalues%29-macro) which would be another alternative: `Foo.flags?(One, Two)`.

Perhaps this could also help to implement proper autocasting for flags enum combinations.

The expression `:a | :b` is a `Call` with receiver `SymbolLiteral` and argument `SymbolLiteral`. Calls can be chained when more than two flag members are combined: `(:a | :b) | :c` (parenthesis added for clarity, they can be omitted). Such a chain of calls should be relatively easy to detect. We would only need to autocast the first receiver to the flag enum type, everything else would be handled by the existing autocasting rules.

The trouble with that is the order of typing: When you have a call `foo(:a | :b)`, the inner expression `:a | :b` is typed first, before the outer `foo(result_of_inner)`. But the inner expression already errors because `Symbol` does not implement `#|`. So autocasting of such a call chain would need to happen earlier.

**Comment by Blacksmoke16** [comment]
With the introduction of https://github.com/crystal-lang/crystal/pull/12900, would this feature even be worth it? `Foo[:one, :two]` might be sufficient.

**Comment by oprypin** [comment]
I think yes, that is enough to close this off. The other approach is already there, is less hacky *and* indeed with this there would be too many ways to do this.
