### ISSUE TITLE
`IO::Hexdump#read` is returning `(Int32 | Int64)` instead of `Int32`

### ISSUE THREAD

**Issue by caspiano** [crystal-lang/crystal#10855]
[This stack trace](https://gist.github.com/caspiano/5a838eb272e2a8342e4fdac6aef6762c) is produced from some code tested against nightly.

Looks like the [annotation here](https://github.com/crystal-lang/crystal/blob/a03539c239c75eca2466b276567769c8a75d36f0/src/io/hexdump.cr#L29) is incorrect, or an `Int64` is slipping in somewhere.

**Comment by caspiano** [comment]
[Here's another failing CI run](https://github.com/PlaceOS/driver/pull/90/checks?check_run_id=2929557028) with the same error, but different stack trace.

**Comment by straight-shoota** [comment]
This is caused by #10575 (or #10580 more specifically) which adds lots of useful type restrictions. This seems to be one of the few cases where this causes an issue. For the time being, we should simply revert all restrictions that cause any trouble. The hard part is identifying them.
Theoretically, we could just revert *all* those PRs and make sure to review them more carefully. But I think that would be too drastic. The error rate is really low.

I think I'll go through all the PRs again and try to identify any methods that might be problematic as well. The most likely trouble makers are probably integer type restrictions.

**Comment by straight-shoota** [comment]
Actually, maybe we should just cast to `Int32` instead. I mean, we really want unified return types for any `IO#read` implementation.

This can probably wait until after 1.1 and reverting this is cheap for a quick fix.

**Comment by caspiano** [comment]
There’s no type restriction on `IO#read` (`@io` in the class is not a more specific subclass of `IO`), so I would wait for that instead of casting.
