### ISSUE TITLE
Add an OS-aware newline constant

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#10885]
Ruby has the poorly named `$/` global variable which returns `"\n"` on *nix OSes and `"\r\n"` on Windows. Crystal should have a similar constant to assist in formatting multi-line Strings in an OS-agnostic manner.

## Proposed Code

Top-level constant:

```crystal
{% if flag?(:win32) %}
  NL = "\r\n"
{% else %}
  NL = "\n"
{% end %}
```

String constant:

```crystal
class String

  {% if flag?(:win32) %}
    NL = "\r\n"
  {% else %}
    NL = "\n"
  {% end %}
  
end
```

Char vs. String (could cause issues):

```crystal
{% if flag?(:win32) %}
  NL = "\r\n"
{% else %}
  NL = '\n'
{% end %}
```

Additionally, it could be named `NEWLINE`, although `NL` is more succinct.

### Usage

```crystal
def to_s
  [
    "line one",
    "line two",
    "line three"
  ].join(NL)
end
```

**Comment by Blacksmoke16** [comment]
FWIW PHP calls it `PHP_EOL` so `EOL` would be another option.

**Comment by HertzDevil** [comment]
`$/` in Ruby is actually the input record separator, and is not even a constant.

**Comment by straight-shoota** [comment]
I think adding a constant for this is pretty much uncontested. The only open question is naming it.

Suggestions are:

* `EOL`
* `System::EOL`
* `String::EOL`
* `NEWLINE`

My preference is `EOL` over `NEWLINE` because it's succinct yet unambiguous.
It probably makes some sense in either of the namespaces top-level, `System`, or `String`. So I think either of them is fine. Top-level is most succinct and versatile. I see no cause for conflict or misinterpretation. So I'm happy to take that.
