### ISSUE TITLE
`Socket::Addrinfo::Error.new` No Longer Works in 1.1.0

### ISSUE THREAD

**Issue by toddsundsted** [crystal-lang/crystal#10958]
## Bug Report

The following works in 1.0.0:

```crystal
raise Socket::Addrinfo::Error.new(LibC::EAI_NONAME, "No address found", "foobar.com") # => raises "Hostname lookup for foobar.com failed: No address found (Socket::Addrinfo::Error)"
```

In 1.1.0 this fails to compile

```crystal
raise Socket::Addrinfo::Error.new(LibC::EAI_NONAME, "No address found", "foobar.com")
...
...
 66 | Socket::ConnectError.new(message, **opts)
                           ^--
Error: no argument named 'domain'
```

It looks like the change may have been introduced in https://github.com/crystal-lang/crystal/pull/10761.

I am using this in a networking mock in test code—definitely open to better approaches if that's the problem as long as they don't hit the networking stack.

I am currently testing Crystal 1.1.0 on MacOS 10.14.6.

**Comment by asterite** [comment]
Indeed, it seems one of the `initialize` was transformed to a `new` and then deprecated. I think it broke because changing `initialize` to `new` doesn't always work. So we should probably revert that for 1.1.1

**Comment by straight-shoota** [comment]
`new` vs `initialize` is not at fault here. The complex initialization logic of `SystemError` makes it a bit hard to pinpoint the exact issue. 
The issue is `Addrinfo::Error.new_from_os_error` expects *all* optional named args to be present. But the deprecated `.new` overload just uses `domain`. It should fill the others with default values to make sure the appropriate overloads match.

**Comment by toddsundsted** [comment]
thanks all!
