### ISSUE TITLE
A lot of `IO#write` calls should have been `IO#write_string`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#11009]
Whenever a `Bytes` consisting of UTF-8 byte sequences is written to an `IO`, the correct method to use is always `IO#write_string` (`#write_utf8` before #11051), never `IO#write`, unless the `IO` is guaranteed to come from some internal method and never use a custom encoding. A failing example is JSON:

```crystal
require "json"

io = IO::Memory.new
io.set_encoding("utf16")

JSON.build(io) do |json|
  json.object do
    json.field "name", "foo"
    json.field "values" do
      json.array do
        json.number 1
        json.number 2
        json.number 3
      end
    end
  end
end

byte_slice = io.to_slice
utf16_slice = Slice.new(byte_slice.to_unsafe.unsafe_as(Pointer(UInt16)), byte_slice.size // sizeof(UInt16))

byte_slice # => Bytes[
           #      255, 254, 123, 0, 34, 0, 110, 97, 109, 101, 34, 0, 58, 0, 34, 0,
           #      102, 111, 111, 34, 0, 44, 0, 34, 0, 118, 97, 108, 117, 101, 115, 34,
           #      0, 58, 0, 91, 0, 49, 0, 44, 0, 50, 0, 44, 0, 51, 0, 93,
           #      0, 125, 0,
           #    ]

utf16_slice # => Slice[
            #      65279, 123, 34, 24942, 25965, 34, 58, 34,
            #      28518, 8815, 11264, 8704, 30208, 27745, 25973, 8819,
            #      14848, 23296, 12544, 11264, 12800, 11264, 13056, 23808,
            #      32000,
            #    ]

String.from_utf16(utf16_slice) # => ﻿{"慮敭":"潦≯Ⰰ∀瘀污敵≳㨀嬀㄀Ⰰ㈀Ⰰ㌀崀紀
```

Replacing the calls to `IO#write` in `JSON::Builder#string` by `write_string` will fix it<strike>, but from a quick glance many other methods in the standard library are also suspectible to this issue</strike>. Most of this has been done in #11011, but `HTTP` and `MIME` types have been left out.

**Comment by straight-shoota** [comment]
The name of the method might be a factor that facilitates incorrect use. `#write_utf8` appears as if it should be used when writing UTF-8 characters. But in fact, it must be used for *any* string, even if it consists entirely of ASCII characters (they're technically also UTF-8 but we typically differentiate between (non-ASCII) UTF-8 and ASCII (UTF-8) characters for practical purposes).

I'd propose to rename that method to a more expressive name: `#write_string`

In a similar fashion, we could consider renaming `#write` to a more expressive name like `#write_data` or `#write_binary` in order to emphasize the different semantics.

**Comment by straight-shoota** [comment]
It's technically fine to skip instances where the IO is enclosed. But it could also easily slip out if a refactor would introduce `Path.join(io : IO, enumerable)` for example 🤷 . Not saying that's particularly realistic, but we can't eliminate the possibility of something like this. And at that point nobody might be looking at the specific IO calls.
Maybe a little sacrifice would be preferable to avoid potential later issues. It's really just an extra nil check on an ivar.

With `JSON::Lexer` for example, any change would be especially hard to track because an instance variable is not scoped locally. I'd suggest `write_utf8` for that to be on the safe side.

For locally scoped string builders it might not be that important and I'm fine with skipping the extra safety there.

**Comment by HertzDevil** [comment]
Applying the `assert_prints` helper to various specs has revealed a variant of this issue where raw ASCII bytes are written to a possibly unknown `IO`:

```crystal
struct Time::Format::Formatter
  def year : Nil
    pad4(time.year, '0')
  end

  def month_zero_padded : Nil
    pad2 time.month, '0'
  end

  def day_of_month_zero_padded : Nil
    pad2 time.day, '0'
  end

  def pad2(value, padding) : Nil
    io.write_byte padding.ord.to_u8 if value < 10
    io << value
  end

  def pad3(value, padding) : Nil
    io.write_byte padding.ord.to_u8 if value < 100
    pad2 value, padding
  end

  def pad4(value, padding) : Nil
    io.write_byte padding.ord.to_u8 if value < 1000
    pad3 value, padding
  end
end

t = Time.utc(1, 2, 3)

io = IO::Memory.new
io.set_encoding("UTF-16LE")
t.to_s(io, "%Y-%m-%d") # possibly unknown `IO` passed here

byte_slice = io.to_slice
utf16_slice = Slice.new(byte_slice.to_unsafe.as(UInt16*), byte_slice.size // sizeof(UInt16))

byte_slice                     # => Bytes[48, 48, 48, 49, 0, 45, 0, 48, 50, 0, 45, 0, 48, 51, 0]
utf16_slice                    # => Slice[12336, 12592, 11520, 12288, 50, 45, 13104]
String.from_utf16(utf16_slice) # => "〰㄰ⴀ　2-㌰"
t.to_s("%Y-%m-%d")             # => "0001-02-03"
```

When the original `Char` is available we can simply do `io << padding`. (In this particular example we could also use `printf`.)

**Comment by straight-shoota** [comment]
After #11011 and #11124 this should be mostly resolved, right?
According to the description of the latter, `MIME::MediaType.decode_rfc2231` ist still missing
 But yeah should be it.

**Comment by straight-shoota** [comment]
The behaviour in `MIME::MediaType.decode_rfc2231` seems actually correct. The method decodes a string from a given encoding. Escape sequences reference the byte representation in the respective encoding. They're not UTF-8.

So I believe we can consider this resolved.

**Comment by HertzDevil** [comment]
The remaining calls of `IO#write` in `HTTP` and `MIME` have not been reviewed.

**Comment by straight-shoota** [comment]
The remaining uses in `MIME` look fine. They're either specifically for non-text binary data or write to an internal and encapsulated `IO` which does not use an encoding.

`HTTP` is a text-based protocol. The control parts (request and status lines, header names) are encoded in ASCII, but the encoding of the actual contents is not specified (usually ASCII or UTF-8). I don't think there should be any transformation of content sent through the HTTP protocol. It should be the consumer's/producer's tasks to use the encoding intended for the application.

**Comment by straight-shoota** [comment]
I don't think there is anything left to do here. All reported instances of `IO#write` calls have either been fixed or are actually correct in writing binary data without encoding conversion.
