### ISSUE TITLE
`sprintf "%c"` does not check its argument

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#11022]
The whole method that writes characters from `sprintf` format strings is:

https://github.com/crystal-lang/crystal/blob/fc0617ff701d328cab868b390750d492bb1f0ab6/src/string/formatter.cr#L204-L210

It does not care if `arg` is a `Char` at all, and every type implements `#to_s(IO)`, so anything can be passed here:

```crystal
sprintf "%c", 123             # => "123"
sprintf "%c", "123"           # => "123"
sprintf "%c", Random::DEFAULT # => "#<Random::PCG32:0x7f13d08b9f80>"
```

The expected behaviour is to write any `Char` unmodified, write the `#chr` of any `Int`, and raise on anything else. Perhaps 1-character `String`s could be allowed too. (There is no such thing as `#to_char` for arbitrary types yet, so we don't need to consider that.)

**Comment by nanobowers** [comment]
@HertzDevil I was looking to find a simple issue so I could make a contribution and found this one.  After poking a little I have some questions:
1. I wasn't clear if a decision was made on the "Perhaps 1-character strings could be allowed" part and if so, if it was really conditional on #7830 
2. My initial implementation gave me this error `Error: undefined local variable or method 'unsafe_chr' for BigInt
` and apparently it's not okay to use `#chr` on an arbitrary `Int`, because `BigInt`  `.is_a(Int)`.  I changed my checking to allow for `Int::Primitive` instead of `Int`, but unsure if that meets the intent.  Or alternately - should `unsafe_chr` be defined for `BigInt`?
