### ISSUE TITLE
Unexpected simple #reduce behavior

### ISSUE THREAD

**Issue by jeremyjaybaker** [crystal-lang/crystal#11102]
Hello! Hope I'm not missing something obvious, but I'm trying to use a `reduce` call like I would in Ruby using the following code:

`[1,5,7].reduce(&.+) # => expected 13, but returns 1`

It seems like `.reduce(&.+)` is always returning the first el of an array. Is this intentional or a bug? It's reproducible in the playground v1.1.1.

**Comment by asterite** [comment]
Hi!

It's not an intentional bug. It's working as expected.

This:

```crystal
[1,5,7].reduce(&.+)
```

by the language rules, is the same as:

```crystal
[1,5,7].reduce { |x| x.+ }
```

that's calling the unary `+` method.

By the way, you can call `sum` instead of using `reduce`.

**Comment by jeremyjaybaker** [comment]
Thanks for the quick feedback! I'll use `sum` instead and close this out :)

**Comment by jeremyjaybaker** [comment]
I do find the fact that `1.+` compiles and the above `reduce` behavior very unintuitive, but I'm also pretty new to Crystal and probably lacking some design context around this issue. I'm also less concerned about it overall because I think most people coming from Ruby like myself will just use `sum` like @asterite suggested, I was just experimenting and thought I found a bug.

**Comment by asterite** [comment]
A few notes:
- Ruby also has the unary `+` method, but because Ruby doesn't have overloads, it's called `+@`, and you can even do `10.+@()` (it seems it doesn't work without parentheses, I don't know why). But then, you can write `[1, 2, 3].reduce(&:+@)` which parses fine but fails at runtime with "wrong number of arguments".
- In Crystal we chose to use `+` for unary plus because we have overloads, and `+@` looks pretty weird.
- We also have the unary `-` method
- If you can do `1.b`, why wouldn't you be able to do `1.+` if `b` and `+` are methods? `+` is a valid method name.

**Comment by asterite** [comment]
Finally, this is really not an issue in Crystal because nobody that knows about `sum` will need to write `.reduce(:+)`, and even Ruby added `sum` recently to the standard library, so uses of `reduce(:+)` will be reduced ( 😉 ) even in Ruby.

**Comment by jeremyjaybaker** [comment]
Ohh I see the distinction now, this makes sense. I didn't initially consider the _unary_ method versus other implementations of `+` even though you were pretty clear about it in the initial post. Thanks for the explanation!
