### ISSUE TITLE
__FILE__ and __DIR__ not working in macro inherited

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#1115]
As seen below when i can't get the file or directory path via macro inherited 

http://play.crystal-lang.org/#/r/a3l

Is this is a bug or intention?

**Comment by asterite** [comment]
`macro inherited` works in the context of a class, and only when you inherit it: http://play.crystal-lang.org/#/r/a44

But yes, that info isn't useful right now.

What file and line info do you need? The callers? Or the ones right there in the file? Because this isn't possible right now we need to discuss how we want to achieve each of these possibilities.

**Comment by Sdogruyol** [comment]
Hey @asterite 

Actually both can be useful. For my case i need to get the info of current file which inherited from super that implemented the macro.

**Comment by asterite** [comment]
@sdogruyol Could you provide a use case for this? (with code). I'm still not sure I understand what file/line you need.
