### ISSUE TITLE
`Bool` vs truthy in blocks in the stdlib

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#11210]
Currently the stdlib uses inconsistently the two options. For instance, it's possible to `Enumerable#select` elements using truthy values:

```crystal
[1, 2, 3].select do
  1
end # => [1, 2, 3]
```

Yet, the same doesn't work for `Indexable#bsearch`, as the domain of the block is restricted to `Bool`:

```crystal
[1, 2, 3].bsearch do
  1
end # Error: expected block to return Bool, not Int32
```

The differences are in the type annotations of the functions:

```crystal
def select(&block : T ->)

def bsearch(&block : T -> Bool)
```

Ideally there should be the same kind of annotation in all the library's relevant methods. The tradeoffs of each style are clear: `Bool` prevents potential bugs, while at the same time restricting potential valid uses (like deciding according to if a value is `nil` or not).

**Comment by asterite** [comment]
I think we did it that way for `bsearch` because in Ruby's bsearch you can return an int or a bool, and that changes what `bsearch` does: https://www.rubydoc.info/stdlib/core/Array:bsearch

I wouldn't restrict `select`, or any other method like that, to return `Bool`. Some values are nilable and it's very convenient to just use that nilable type as a filter.

**Comment by straight-shoota** [comment]
I think we should remove the type restriction from `bsearch`. I don't see why you shouldn't be able to use truthy/falsey values with that particular method.

If we want to implement a find-any method like Ruby's alternative mode, I'm pretty sure it should be a differnt method, not an overload based on the block's output type.

**Comment by asterite** [comment]
I agree.
