### ISSUE TITLE
Tuple literals precedence

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#11225]
It would be great to improve the parsing of tuples so it binds a bit tighter.  Concretely, I'd like to avoid needing to surround tuples with parens in the following examples:

```crystal
# without () it doesn't work :-(
p {1, 2}  # => Unexpected token: ,

def f
  yield {1, 2}   # => Unexpected token: {
end

# with () it works
p ({1, 2})  # OK

def f
  yield ({1, 2})   # OK
end
```

**Comment by straight-shoota** [comment]
The example with `yield` should probably be easy to do.

But with an arbitrary call like `p` it's different because there's ambiguity with a block. More specifically, `p {1}` would legitimately be the single-element version of the tuple. But it can't be, because it's a block. Even if the syntax might be unambiguous for multiple elements, it doesn't seem very smart to make the syntax depend on the size of the tuple (think about splats for example...).

**Comment by j8r** [comment]
However, if the method accepts no blocks, then we certainly want to pass a tuple. This information may not be available at this parsing stage however.

**Comment by straight-shoota** [comment]
If the intention is to call a method with a block, but the method does not accept a block, then it should be a clear error. Parsing of the method call must not depend on the method definition.

**Comment by beta-ziliani** [comment]
Ah yes, I didn't thought of 1-element tuples 🤦

**Comment by maxfierke** [comment]
Perhaps requiring a trailing comma for a one-element tuple would be a good disambiguator (Python does this, I believe) i.e. `p {1,}`. It looks a little funny, but AFAIK it's not valid syntax for any other context?

**Comment by asterite** [comment]
```crystal
foo { x, y = [1, 2] }
``

**Comment by j8r** [comment]
That's unfortunate that's Blocks and Tuples are close syntaxically 😕.
I'm curious where the Tuple syntax inspiration came from?

**Comment by asterite** [comment]
By the way:
- This is a duplicate: https://github.com/crystal-lang/crystal/issues/1051 https://github.com/crystal-lang/crystal/issues/2746 https://github.com/crystal-lang/crystal/issues/4826 https://github.com/crystal-lang/crystal/issues/6224
- This also happens with hashes, it's not only with tuples, so it doesn't matter what syntax we use for tuples
- This also happens in Ruby! They never "fixed" it because it's actually impossible to fix.
