### ISSUE TITLE
Bug with hash function default value

### ISSUE THREAD

**Issue by pjcoenen** [crystal-lang/crystal#11239]
## Bug Report

I think I discovered some strange behaviour with the hash function.

```
hash = Hash(String, Hash(Int32, Int32)).new(Hash(Int32, Int32).new(0))
hash["hello"] = Hash(Int32, Int32).new(0)
hash["hello"][1] += 3

puts(hash.size) # => 1
puts(hash) # => {"hello" => {1 => 3}}
puts(hash["hello"]) # => {1 => 3}
```

Works as expected, but the following behaviour is a little bit unexpected:

```
hash = Hash(String, Hash(Int32, Int32)).new(Hash(Int32, Int32).new(0))
hash["hello"][1] += 3

puts(hash.size) # => 0
puts(hash) # => {}
puts(hash["hello"]) # => {1 => 3}
```

**Comment by Blacksmoke16** [comment]
Pretty sure this isn't a bug, but is closely related to https://forum.crystal-lang.org/t/hash-help/2707/2.

**Comment by straight-shoota** [comment]
This is expected and documented behaviour.

The default value is returned when a key is missing and it's passed by reference. `hash["hello"]` returns the default value and when you mutate that, you mutate the reference. `hash` is empty because no value was actually assigned to the hash. A second call to `hash["hello"]` returns again the default value, but since the previous operation mutated that, you see the mutated state.

**Comment by pjcoenen** [comment]
Thanks a lot !
