### ISSUE TITLE
Formatter removes escape slash in HEREDOC

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#11247]
Code before format

```crystal
<<-REGEX
/\d/
REGEX
```

Code after `crystal tool format that_file.cr`

```crystal
<<-REGEX
/d/
REGEX
```

I noticed this when running the formatter on the ICR shard. The specs changed on these lines

https://github.com/crystal-community/icr/blob/0537fc21636fc1de467fa7108d80387eeba06893/spec/integration/icr_spec.cr#L300-L317

**Comment by straight-shoota** [comment]
This is expected behaviour, see #8619. The formatter transforms *any* string literal like that.

The reason is that `\d` is an invalid escape sequence. The parser accepts that and treats it as equivalent to `d`.
If you want an actual backslash, you need to escape it (`\\`).

Eventually, invalid escape sequences should probably become an error (even if just to avoid such surprises).

**Comment by vlazar** [comment]
Why `p!` prints 2 `\`?
Does `p!` print internal string representation or exact source code?

```
% crystal eval 'p! "/\\d/"'
"/\\d/" # => "/\\d/"

% crystal eval 'puts "/\\d/"'
/\d/
```

**Comment by straight-shoota** [comment]
`p!` calls [`String#inspect`](https://crystal-lang.org/api/latest/String.html#inspect(io:IO):Nil-instance-method) which escapes special characters (thus the result can be used as a string literal).
`puts` just prints the string without any escapes.
