### ISSUE TITLE
Support '\xXX' notation for Chars

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#11260]
## Discussion

String literals already support the `\xXX` hex byte notation, but Char literals do not. Instead you must type `\u{XX}`, which is kind of cumbersome. It would be more consistent to allow writing Char literals using the traditional `\xXX` notation.

**Comment by postmodern** [comment]
@straight-shoota I think it would be possible to technically express ASCII hex bytes using `\xXX` but have Crystal implicitly convert them to Unicode Chars underneath. This would allow easily expressing ASCII bytes such as `\x00` or `\xff`.

**Comment by straight-shoota** [comment]
ˋ0x00ˋ can already be expressed as ˋ\0ˋ. ˋ0xFFˋ is not a valid codepoint, neither in ASCII nor Unicode. All ASCII characters are also Unicode characters, so there is technically no conversion between the two.

**Comment by postmodern** [comment]
Ah I did not know that Crystal supported `'0xXX'` Char literal syntax. Most other languages adopted the C-style of Char literals, `'\xXX'`, which is why most people are familiar with that syntax and why I was confused by Crystal not supporting `'\xXX'` syntax.

**Comment by straight-shoota** [comment]
Yeah, C's ˋcharˋ type is fundamentally different from Crystal's ˋCharˋ. C's ˋcharˋ, it's just an unsigned 8-bit integer. In Crystal, ˋCharˋ represents a unicode codepoint.

**Comment by postmodern** [comment]
Still seems odd to support the `'0x00'` syntax, but not say `char : Char = 0x00` without the single quotes. It also still seems inconsistent to support `\xXX` in Strings, but not single Chars.

**Comment by asterite** [comment]
I think that idea is that, going forward, there will be an effort to make it impossible to create a `String` instance that's not valid UTF-8. That would mean you won't be able to use `\xXX` in strings after that (so instead of adding `\xXX` somewhere else, it will actually be removed from existing places.)

That said, I can't really imagine how would that work.

**Comment by straight-shoota** [comment]
> Still seems odd to support the `'0x00'` syntax

`'0x00'` is not valid syntax. The character with the codepoint `0` (i.e. `0x00`) can be represented as `\0`.

> but not say `char : Char = 0x00` without the single quotes

The syntax for that is `char : Char = 0x00.ord` (or `'\u{0}'`, or in this special case, `'\0'`).

> It also still seems inconsistent to support `\xXX` in Strings, but not single Chars.

`\xXX` in string literals is a workaround. But that workaround is unnecessary in char literals.

**Comment by postmodern** [comment]
@asterite wouldn't that effect the ability to explicitly define binary Strings, which are not valid UTF-8, in Crystal code?

**Comment by HertzDevil** [comment]
`U+00FF` is a valid UTF-8 codepoint, so `\u{FF}` is correct (`ÿ`). However 0xFF is never part of any valid UTF-8 byte sequences, and `\x` represents the latter. If `Char` literals follow `String` ones in this aspect, then:

* The compiler needs to detect and reject char literals that encode multiple UTF-8 codepoints, e.g. `'\x41\x42'`.
* Any invalid UTF-8 byte sequence is mapped to U+FFFD.
* It follows that if a `Char` literal containing multiple `\x`'s is not valid UTF-8, it is also invalid as a whole because it maps to U+FFFD plus something.

None of these properties are really useful at all.

**Comment by straight-shoota** [comment]
Closing this discussion. Multiple arguments have shown that we should not implement this proposed change. It's not considered beneficial.

There are simple and practical alternatives to `\x` escape sequences in char literals: `\u` escape sequences and hex number literals char conversion. Instead of `'\xXX'` you can write `'\u00XX'`, `0xXX.chr` or `0xXX.unsafe_chr`.

**Comment by postmodern** [comment]
`\u00XX` is still unusual/unfamiliar syntax and `0x00.chr` isn't literal as it involves a method call.
