### ISSUE TITLE
`inject_primitives: false` should be the default for semantic specs

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11290]
I think `inject_primitives: false` should be the default value for compiler spec helpers like `semantic`,  `assert_type`, etc. instead of the current `inject_primitives: true`.

Ideally, code examples should be self-contained and not depend on an external prelude in order to be fully comprehensible. Injecting primitives should be an exception, not the norm. 

In fact, only a minority of use cases actually requires injected primitives: In `spec/compiler/semantic` there are 2793 calls to `semantic` in total. That's a little more than one call per example (2755 examples). Most examples succeed even with `inject_primitives: false`, only 297 examples fail (that's about 10%).

Those that fail, typically just use one ore two simple methods from the prelude. Most popular is `Int32#==(Int32)` which is used for expressions such as `1 == 1` that evaluate to true but can't be inferred by the compiler. Other frequently missing primitive methods are `Int32#+`, `Int32#to_f`, `Proc#call`, `Object#class` and `Pointer.malloc`.
I suppose many of them can be refactored to work without primitives or to define the necessary primitive method themselves. But that would not be a necessary consequence of changing the default. Those that fail can just pass `inject_primitives: true`.

As demonstrated in #11269, ommiting the primitives prelude provides a rather significant performance improvement when executing the specs.

So far, I have only focused on semantic specs and did not investigate the `codegen` and `run` helpers.

**Comment by HertzDevil** [comment]
To my knowledge the main bottleneck of the CI suite is codegen specs that need the entire prelude, e.g. #11233 and the exception specs, rather than the primitives.

That said, primitives.cr can indeed get very large even if the methods have no bodies; running the compiler with `AFTER=1` shows that the fully macro-expanded primitives.cr has over 11k lines, mostly due to the integer-with-integer methods. If a semantic or codegen spec does need a certain primitive then it should be permissible to simply declare those used methods in the code literal itself:

```crystal
assert_type(<<-CR) { bool }
  struct Int32
    @[Primitive(:binary)]
    def ==(other : Int32) : Bool; end
  end

  1 == 1
  CR
```

Semantic specs that use any of the container literals are another source of time-consuming specs.
