### ISSUE TITLE
Upgrade `Regex` engine

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#11331]
## Discussion

- What aspect of the language would you like to see improved?

An updated `Regex` engine.

- What are the reasons?

Crystal currently uses `PCRE1` as its engine. This library is now EOL and released its final release a few months ago. See https://www.pcre.org/original/changelog.txt. Because of this, we are no longer getting new bug fixes and/or features.

- Optionally add one (or more) proposals to improve the current situation.

1. Upgrade to `PCRE2`, which is [mostly](https://wiki.php.net/rfc/pcre2-migration#backward_incompatible_changes) backwards compatible.
2. Migrate to some other engine, such as `RE2` or `Oniguruma`
3. Support multiple and allow picking which one to use via a compile time flag.

Some discussion related to this happened in https://github.com/crystal-lang/crystal/issues/8199. However, having a higher level discussion on which route we want to go would be better taking _all_ things into consideration, outside of that one particular issue.

**Comment by straight-shoota** [comment]
It is important to keep the semantics of `Regex` consistent. Regular exception literals are part of Crystal code, and like any other part of the standard library, we should try not to break them.

Thus we probably have to go with PCRE2. Switching to a completely different engine would create more dissonance. I don't think any potential functional or performance benefits could make up for that. 

Even with PCRE2 there are a couple minor breaking changes compared to PCRE1. But that's probably acceptable or rather unavoidable unless someone keeps up maintenance of the legacy version.

Bindings for alternative engines can be provided as third party libraries.

**Comment by Fryguy** [comment]
While I agree with @straight-shoota , for the future, when we can accept more breaking changes in a major release, another option is to look at [`Onigmo`](https://github.com/k-takata/Onigmo), which is a fork of `Oniguruma`, and is the engine used by Ruby 2+.  Having the same engine as Ruby would keep some more of that consistency between the 2 languages that makes the transition from one to other so nice.

**Comment by asterite** [comment]
As far as I know, the major benefit of Onigmo is supporting some encodings other than UTF-8, like Shift_JIS/EUC-JP, which, in Crystal's case, is not important at all. For instance, I'm not sure if Onigmo is faster than PCRE.

So I think there's not a lot of incentive (as far as I see it) to move to another Regex engine...

**Comment by straight-shoota** [comment]
Even if some alternative is more performant or has some nice additional features, it would be hard to overcome the consistency factor. We're talking about the default implementation of the standard library. If we change that, it will undoubtedly break something.

If you need a faster engine ore some nice additional feature, you're always free to use a custom Regex implementation. It just won't work with regex literals (unless fooling around with stdlib).

**Comment by Blacksmoke16** [comment]
>  when we can accept more breaking changes in a major release, another option is to look at [`Onigmo`](https://github.com/k-takata/Onigmo), which is a fork of `Oniguruma`, and is the engine used by Ruby 2+. 

@Fryguy What would the benefit be of switching beyond just making using Ruby code easier? If that's the only different I don't think it would be worth it since Crystal is its own language and isn't trying to be compatible with Ruby. Would be a large breaking change for seemingly no benefit.

> Even with PCRE2 there are a couple minor breaking changes compared to PCRE1. But that's probably acceptable or rather unavoidable unless someone keeps up maintenance of the legacy version.

Yea, PHP released it as part of a minor release so I suppose we could do the same if we wanted. 🤷.

> Thus we probably have to go with PCRE2.

I guess another question in this regard is should we use the standard implementation of it? They also have https://www.pcre.org/original/doc/html/pcrejit.html#SEC11, which would be more performant, but would require all of the supported platforms support it. https://www.pcre.org/original/doc/html/pcrejit.html#TOC1. Possibly could have it be behind a flag or something one way or the other.

**Comment by Sija** [comment]
PCRE is known for shitty performance (for a majority of cases), and Oniguruma (+ Onigmo as its fork) beats it to the ground, so I guess it would be worth looking into a potential change.

See for reference:
- https://stackoverflow.com/questions/11996988/how-good-is-oniguruma-compared-to-other-cross-platform-regexp-libraries
- http://lh3lh3.users.sourceforge.net/reb.shtml

**Comment by Blacksmoke16** [comment]
@Sija I'd be curious to see some more modern benchmarks as both of those are almost a decade old. Plus with #3852, It's likely it'll perform much better than it was before.

**Comment by straight-shoota** [comment]
Performance optimization is a *subordinate goal.* If I want something really fast, I write a dedicate algorithm in Crystal instead of employing a regex engine. If I need to use regex for whatever reasons, I can alwasy use a custom implementation that fits my needs best.

I think the *primary metric* for taking any alternative implementation into serious consideration is how much it deviates from PCRE.

PCRE2 is mostly backwards compatible, except for a couple minor changes. That's most likely the best we can get anyways.

Not sure about Onigmo/Onigurama. But I can't recall big issues with Ruby's switch, so maybe it's not a huge deal.

**Comment by deiv** [comment]
Any move forward here ? In Debian, PCRE will be droped in the next release, so crystal package will have to be removed from debian archives.

**Comment by straight-shoota** [comment]
I've successfully ported the bindings to libpcre2 🚀
It was pretty straightforward and the new library API is pretty similar, as expected. So I don't expect many issues when migrating the regex backend (except for some rare behaviour and syntax changes between pcre and pcre2).

Now it's about integrating the bindings into the codebase. It should be sufficient to select the regex engine backend at compile time. While technically possible to include bindings for both libraries and being able to load either at runtime would be possible, but I also introduce a lot of complexity for little benefit.
So my proposal is to extract the engine-specific bindings out of `Regex` and `MatchData`. They should be placed into the `Crystal` namespace and used as backend for the public API. At compile time we can detect which library version is available and chose to build bindings for that one (preferring `pcre2` if both would work?). A compile time flag should be able to override the automatic detection. 

While implementing the bindings I noticed the specs for `Regex` are very thin in some areas when the full spec suite passed despite a couple of stubs in the new bindings 😆 
So I've set out to fill out some missing specs and in the process, overhaul the entire thing in #12788 and #12789. It's very useful to have decent spec coverage in order to verify both backends are good in the end.
