### ISSUE TITLE
Abstractions

### ISSUE THREAD

**Issue by dillonfagan** [crystal-lang/crystal#11386]
## Discussion

**What aspect of the language would you like to see improved?**
I would like there to be an `abstraction` keyword, which would work just like `protocol` or `interface` in other languages.

**What are the reasons?**
Writing an interface can be very verbose, since `abstract` needs to be written in front of `class` and every method. As a result of making it convenient, I think this might help encourage the use of abstractions, which makes for cleaner code. Right now, it's too easy to depend on concretes.

**Include practical examples to illustrate your points.**

```cr
abstract class Store
  abstract def name : String
  abstract def get(id : ID) : EntrySummary
  abstract def put(value : String) : EntrySummary
  abstract def patch(id : ID, value : String) : EntrySummary
  abstract def delete(id : ID) : EntrySummary
end
```

```cr
abstraction Store
  def name : String
  def get(id : ID) : EntrySummary
  def put(value : String) : EntrySummary
  def patch(id : ID, value : String) : EntrySummary
  def delete(id : ID) : EntrySummary
end
```

_**Somewhat related:** It would be nice if the VS Code extension distinguished between concrete and abstract types._

**Comment by j8r** [comment]
The `class` keyword will be in any case still needed, since it can be also a `struct` or a `module`.
It is also common to have an standard methods along with abstract ones, this won't be possible with this proposition.

In a way, it is close - but not - to having `private` and `protected` standalone keywords as Ruby.
AFAIK one suggested it in the past but I can't find the issue.

An example will be:
```cr
abstract class MyClass
  def a_public_method
  end

  abstract
  def an_abstract_def
  def another_abstract_def

  private
  def a_private_method
  end
  def another_private_method
  end
end
```

Personally I don't this feature adds much benefits. There are cons, and is writing `abstract` and method visibility really an issue? IDEs can solve this with multi-line edition.

**Comment by Blacksmoke16** [comment]
Depending on the exact use case, the compiler already handles most of this for you. The main benefit of explicit interfaces is for better documentation. I.e. you could just _not_ type things and compiler would error if whatever obj doesn't implement any method called on it.

However, I do like using abstractions, but I'm not sold on needing a whole new keyword for it. It's not really _that_ much extra overhead to just add `abstract` to everything. It also wouldn't be clear what the `Store` abstraction _is_. I.e. can i do like `struct MemoryStore < Store` or `class MemoryStore < Store` or `class MemoryStore; include Store; end`. Related, you'd be better off using a module for your "interface" since it could be included into _both_ structs and classes.

**Comment by j8r** [comment]
The `class` keyword will be in any case still needed, since the object can be also a `struct` or a `module`.
It is also common to have standard methods along with abstract ones, this won't be possible with this proposition.

In a way, it is close - but not exactly - to having `private` and `protected` standalone keywords as in Ruby.
AFAIK one suggested it in the past but I can't find the issue.

An example will be:
```cr
abstract class MyClass
  def a_public_method
  end

  abstract
  def an_abstract_def
  def another_abstract_def

  private
  def a_private_method
  end
  def another_private_method
  end
end
```

Personally I don't this feature adds much benefits. There are cons, and is writing `abstract` and method visibility really an issue? IDEs can solve this with multi-line edition.

**Comment by asterite** [comment]
You can omit all abstract method declarations, if what you want is to write as less code as possible.

**Comment by oprypin** [comment]
I think this is just not constructive. Well, if the main constructive argument is that you type less, then we can literally consider it solved by the above comment. Otherwise, the `module` construct serves the "abstraction" concept quite well.
Because I don't see this issue ever coming to a real conclusion, I would like to close it.
Further comments are welcome, in case I'm wrong.

**Comment by asterite** [comment]
Yes, also sorry if my comment sounded rude. What I wanted to make clear is that having to type less code is nice, but we don't generally design the language around typing less. Having to type a few more things here and there is fine. You'll just have to type the abstract keyword a few more times, once, and that's it.

But do note that you can, actually, omit abstract methods. Then it works almost exactly the same, except the compiler won't tell you which methods you actually need to implement.
