### ISSUE TITLE
--mcpu native broken

### ISSUE THREAD

**Issue by BlobCodes** [crystal-lang/crystal#11415]
## Bug Report

This bug basically exists since #10276, but I haven't filed a bug report because I just assumed my version of crystal was compiled with an ancient version of LLVM.

Using `--mcpu native` to optimize the executable for the host cpu always throws an exception, even if the LLVM version is far newer than 7.0.

Running `crystal run --mcpu native` results in:
```
LibLLVM.host_cpu_name requires LLVM 7.0 or newer (Exception)
  from /crystal/src/llvm.cr:87:5 in 'host_cpu_name'
  from /crystal/src/pointer.cr:286:59 in '->'
  from /crystal/src/primitives.cr:266:3 in 'parse'
  from /crystal/src/option_parser.cr:114:5 in 'create_compiler'
  from /crystal/src/compiler/crystal/command.cr:304:11 in 'run_command'
  from /crystal/src/compiler/crystal/command.cr:62:5 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

BTW even if the local LLVM version is older than 7.0, I think it should not raise an error like that.

## Crystal
Version: 1.2.1
OS: Fedora Silverblue Toolbox 35 (Also got the same error on Manjaro and OpenSuse previously)

**Comment by straight-shoota** [comment]
This would be fixed by #8725 (removing support for older LLVM releases).

**Comment by HertzDevil** [comment]
`||` in constant initializers are not evaluated, and `Or` nodes are always truthy. Reduced:

```crystal
A = false
B = false
C = A || B

def c
  {% p C %}  # => A || B
  {% if C %}
    true
  {% else %}
    false
  {% end %}
end

c # => true
```

So this will eventually affect other places that do a similar version check. Instead `IS_LT_70` must be evaluated during macro expansion too.

**Comment by HertzDevil** [comment]
This is quite worrying. The compiler does this:

https://github.com/crystal-lang/crystal/blob/6654ca7aad9a7ad4d304b213b014c978376fa575/src/llvm/module.cr#L59-L75

https://github.com/crystal-lang/crystal/blob/6654ca7aad9a7ad4d304b213b014c978376fa575/src/llvm/lib_llvm.cr#L399-L401

The wrong number of arguments are passed to `metadata_as_value`, but since `IS_LT_70` is truthy, we are using the deprecated code path even on the latest LLVM versions, and the compiler would actually fail to compile if we remove the version check altogether.
