### ISSUE TITLE
Autocompletion provider inside the compiler

### ISSUE THREAD

**Issue by Peekmo** [crystal-lang/crystal#1156]
Hello,

I'm a really big fan of this project, and I would like to share ideas around something that would be amazing to develop tools around crystal (even if it's only an alpha version..) : an autocomplete provider inside the compiler (like Haxe provides). I know that it's not your priority, and that's normal, but I'm interested in, so I share and I think that the compiler is the most appropriate tool to give this kind of services : no need to register runtime metadata, or to manually parse all files.

@bcardiff started some works in tool-impl branch to find some contexts in the file, that works very well, and I think that it's not far from what is needed to allow some autocomplete : A context, and a list of available methods/attributes

The problem for the context is the following : 

``` crystal
x = Animal.new
x.     # {fail to compile}
```

Two things could be done to allow invalid strings to be parsed : 
- To have a parser less strict when there's no build
- Or to have a special token like `x.CONTEXT_TOKEN` that will not fail when trying to complete. The tool maker will have the responsability to add this CONTEXT_TOKEN to the file when an autocomplete will be needed.

The other thing needed, is the list of methods available. Is it available simply in the compiler src today ? I don't really know where to start to search, so, if you could help me... ;)

Thank you very much,
Regards,
Peekmo

**Comment by asterite** [comment]
Yes, the compiler should come with this built-in, I think it's the best thing to do. But it's definitely not a simple task.

**Comment by mrkaspa** [comment]
Is there wip on this?, I want to make an atom plugin for this

**Comment by mverzilli** [comment]
It's still as Ary said a couple of years ago (time flies btw :P). It's something we'd like to eventually see in the compiler, it's not a simple task, and it's not one of the midterm priorities for the project. If I had to guess, I think this would only come after we introduced a number of optimizations to the compiler (like incremental compilation).

**Comment by mrkaspa** [comment]
ok this tool would be pretty useful, good editor support are necessary to increase the devs using crystal

**Comment by cocodrino** [comment]
+1 I really want a good editor support for crystal, please let me know if the crystal team develop this feature soon ;D

**Comment by howesteve** [comment]
Lack of good autocomplete support is keeping me away from using Crystal seriously...

**Comment by kirbyfan64** [comment]
@howesteve Any decent text editor should also have a more primitive, text-based completion, which works pretty well most of the time too.

**Comment by howesteve** [comment]
@kirbyfan64 actually, I disagree. Autocomplete is very useful when you don't remember a class methods, propertyes, members etc. It saves a large amount of time checking documentation as well. It's not just "typing saving".

**Comment by luislavena** [comment]
IMO the best approach for this is via LSP (Language Server Protocol) designed by Microsoft and currently being implemented by several languages and editors (see [here](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations))

But as pointed out before, is not an easy task plus, with current compiler implementation, might result in slow since everything will need to be parsed constantly (there is no incremental parsing or analysis).

This is something could be done as separate project (shard) and later on perhaps integrated in the compiler. After all, Crystal is written in Crystal and the compiler source code is shipped with every Crystal installation, so any tooling that uses compiler internals can be used that way :smile: 

Cheers.

**Comment by asterite** [comment]
Autocomplete can't be implemented in a timely fashion in Crystal because the program needs to be compiled all over again each time. I suggest using a text editor with word autocomplete for open files (Sublime has such plugin). 

I've been programming in Ruby for about 10 years and never used an IDE and I'm pretty fast in it. Ruby has a pretty intuitive API, plus code tend to be very short and concise. I would recommend not depending on an IDE for programming. If you can't program in Crystal because of luck of a decent IDE, maybe use another programming language (I think Nim has a good IDE, probably Rust too, and Go has many)

**Comment by straight-shoota** [comment]
While I'm perfectly fine with the functionality that Sublime Text provides, autocomplete is nevertheless much liked by many developers and could be a great selling point ;)

I am not that familiar with the compiler process, but a simple lookup for autocomplete should probably be possible at a relatively early stage.

**Comment by straight-shoota** [comment]
Closing stale discussion.

Autocompletion doesn't need to be provided by the compiler itself. That's outside its scope.
It should be implemented by external tools. There is https://github.com/crystal-lang-tools/lsp for this. I'm not sure how far advanced the progress on autocompletion is, but it's definitely the right way to go. Not in the compiler.

**Comment by bew** [comment]
FWIW the most up to date lsp server for Crystal is https://github.com/elbywan/crystalline
