### ISSUE TITLE
sending an IO::Memory to itself can cause corruption

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#11642]
```
$ cat corrupt.cr
   io = IO::Memory.new
   io << "something"
   io << "........................."
   io.to_s(io)
   puts io
$ crystal corrupt.cr
something..........................g.........................
```

the weird "...g" thing in the middle seems to be some kind of corruption and changes with each run.  Not sure if this is something to care about but it was a bit confusing...

```
Crystal 1.2.1 [4e6c0f26e] (2021-10-21)
LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by straight-shoota** [comment]
The issue seems to be caused by memory reallocation during `io.to_s`. If the `IO::Memory` has sufficient capacity, the example works correctly.

`IO::Memory#to_s` appends the current buffer (`to_slice`) to its argument. When the capacity is not big enough to hold the entire content (i.e. twice the current size), the buffer needs to be increased. That causes a `realloc` which invalidates the previously returned buffer pointer (`to_slice`) and it can be garbage.

This patch should fix it. It adds a special condition for writing to itself which ensures sufficient capacity before taking the buffer pointer.

```diff
--- i/src/io/memory.cr
+++ w/src/io/memory.cr
@@ -409,6 +409,9 @@ class IO::Memory < IO

   # Appends this internal buffer to the given `IO`.
   def to_s(io : IO) : Nil
+    if io == self && @capacity < 2 * bytesize
+      resize_to_capacity(bytesize * 2)
+    end
     io.write(to_slice)
   end
```

**Comment by rdp** [comment]
Thanks!
