### ISSUE TITLE
Weird regex behavior

### ISSUE THREAD

**Issue by webhive** [crystal-lang/crystal#12055]
## Bug Report

I got weird regex behavior 

This code should match single digit only

```crystal
puts "1" =~ /^[0-9]$/   
0 # <= correct
```

```crystal
puts "11" =~ /^[0-9]$/   
nil # <= correct
```

But if source number followed by new line, we got false match, no matter if multiline modifier used or not. It really looks like regex engine has multiline always on.

```crystal
puts "1\n" =~ /^[0-9]$/ 
0 # <= incorrect
```

```
$ crystal -v
Crystal 1.4.1 [b7377c041] (2022-04-22)

LLVM: 10.0.0
Default target: x86_64-apple-macosx
```

**Comment by Blacksmoke16** [comment]
Based on https://www.pcre.org/original/doc/html/pcresyntax.html#SEC10, I'm pretty sure this is by design. Specifally:

```
  $   end of subject
         also before newline at end of subject
         also before internal newline in multiline mode
```
I.e. given it matches the end of the _subject_, before a newline (since we're not in multiline mode) it allows the trailing newline and matches. However, if in multiline mode, it still matches because the newline becomes part of the subject.

I think you may want to use `\z`, which is a lesser known anchor that works like `$`, but disallows a trailing newline. There is also `\Z` which also works like `$` by matching the end of the subject, and allows trailing newlines, but its behavior does not change when in multiline mode.

**Comment by webhive** [comment]
> I think you may want to use \z, which is a lesser known 

Yes it work. Thank you a lot. But anyway seems a workaround, but not a correct behavior.

> Based on https://www.pcre.org/original/doc/html/pcresyntax.html#SEC10, I'm pretty sure this is by design. Specifically:

```
$   end of subject
         also before newline at end of subject
         also before internal newline **in multiline** mode
```

Explicitly noticed it should work this way **in multiline mode**. In my examples multiline switch changed nothing. So definitely something wrong with crystal regex

>  https://www.rexegg.com/regex-anchors.html has some good examples/explanations.

Cite from this link _Of course the $ anchor also matches that position. But since $ changes its meaning **when multiline is on**, \z gives us an ..._

**Comment by Blacksmoke16** [comment]
> But anyway seems a workaround, but not a correct behavior.

It's totally the correct behavior. The main issue you're having is that `$` allows a trailing newline whether you're in multiline mode or not. `\z` disallows the trailing newline, so you get the behavior you want.

> In my examples multiline switch changed nothing. So definitely something wrong with crystal regex

This is also expected because in your example of `1\n` there no internal newlines anyway, so the behavior is the same both when its on or off. An example of this would be `\n1\n` matches _only_ in multiline mode, but the first newline becomes an internal newline, and because it still matches the trailing newline.

You can try this in any other language that uses PCRE and I'm certain you'll get the same behavior.

**Comment by Fryguy** [comment]
Ruby is the same:

```ruby
"1\n" =~ /^[0-9]$/  # => 0
```

**Comment by webhive** [comment]
> You can try this in any other language that uses PCRE (C, PHP, R) and I'm certain you'll get the same behavior.

As long as PCRE mean Perl Compatible, tested perl
It is really the same

So closing it
