### ISSUE TITLE
Method's type restrictions do not account for assignability of `Proc(NoReturn)`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12126]
`Proc(*T, NoReturn)` can be assigned to any `Proc(*T, R)` (#3032, #9971).
This code compiles:

```cr
foo : Proc(Int32) = -> { raise "" }
```

But this is not reflected in type restrictions of method arguments.
This code should compile:

```cr
def foo(p : Proc(Int32))
end

foo -> { raise "" } # Error: no overload matches 'foo' with type Proc(NoReturn)
```

**Comment by asterite** [comment]
Because it goes through a different path: https://github.com/crystal-lang/crystal/blob/8a7f09a7f99b38bb7ee953cee6ad7801b504d9dc/src/compiler/crystal/semantic/restrictions.cr#L1209

You can see it's handled here: https://github.com/crystal-lang/crystal/blob/8a7f09a7f99b38bb7ee953cee6ad7801b504d9dc/src/compiler/crystal/semantic/restrictions.cr#L1250-L1251
