### ISSUE TITLE
Why compile time type (typepof) is different in following case?

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12199]
More details, please check discuss on https://forum.crystal-lang.org/t/why-compile-time-type-typepof-is-different-in-following-case/4756/8?u=zw963
Thank you.

```crystal
num2 : Int32 | Nil = 1
p! typeof(num2) # =>  (Int32 | Nil)
num2 = nil
```

```crystal
num2 : Int32 | Nil
num2 = 1
p! typeof(num2) # =>  Int32
num2 = nil

```

**Comment by jgaskins** [comment]
Variable declarations in Crystal aren't quite the same as you might be used to in some other statically typed languages. TL;DR: it's the same reason this works

```crystal
value = [1, nil].first
pp typeof(value) # => Int32 | Nil
if value
  pp typeof(value) # => Int32
end
```

Note that the second `typeof` check doesn't have `Nil`. The compiler knows that, at that specific point in the code, that variable can only ever be an `Int32`. In your example, it's because you assigned an `Int32` to the variable right before the `typeof` check. It's not about the type of the variable binding, it's the type of the value it contains. The type of the binding is typically a lot less useful than the type of the value.

**Comment by zw963** [comment]
Ha, The person who create this issue (Yes, it's me!) is naive, not a issue anyway, closing.
