### ISSUE TITLE
[Compiler] Could the compiler show a bit more helpful information? In particular when it comes to ruby users who expect $stdin.gets.chomp to work

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal#12292]
Oddities in Crystal: String versus nil

I am struggling a bit with crystal.

Some examples:

 3 | @user_input : String
     ^----------

Error: instance variable '@user_input' of Shell was not initialized
directly in all of the 'initialize' methods, rendering it nilable.
Indirect initialization is not supported.

Ok ... weird, but ... whatever.

So another try:

 10 | @user_input = ''
                    ^
Error: invalid empty char literal (did you mean '\''?)

Ok so ... "" rather than ''.

Next try:

In shell.cr:28:5

 28 | @user_input = STDIN.gets
      ^----------
Error: instance variable '@user_input' of Shell must be String, not (String | Nil)

./shell

Hmmmmm. At that point I gave up for today. I found out that $stdin
is not valid in crystal. But ... if I do .gets, why is a nil possible?
Isn't .gets short for "get string"? So I'd get a String?

Crystal right now is quite confusing. This may be due to my ruby
background, but it feels like quite a different language compared
to ruby at this point. That's ok if it is advertised as a separate
language but it confuses me a lot so far.

Letting the compiler show information to the user is useful, though,
so I don't recommend to show LESS information. But I recommend that
the information could be more useful. For instance, what is the
alternative then for $stdin.gets.chomp? Perhaps the compiler could
check for this and ask the question "the user wants to fetch user
input, so show some more information here". I would not mind 
URLs to the wiki or elsewhere to read up on that; right now I
gather information from many different websites. That works but
it is quite tedious; and when I end up being frustrated, I make
a break and resume again at a later time.

**Comment by Blacksmoke16** [comment]
> but it feels like quite a different language compared
> to ruby at this point

It is a different language. It does share a lot of the same syntax and methods and such, but compatibility with Ruby is not a goal. I don't think the compiler should or needs to also show the Ruby equivalent to every possible error. But of providing clearer error messages could be helpful.

I think it would be helpful to stop trying to relate Crystal to Ruby and treat it as learning another language entirely. 

But to add some explanation to some of the errors:

> 3 | @user_input : String

You have an instance variable typed as `String`, but since you did not give it a default value or set its value within an `initialize` method, the compiler saves you from undefined behavior since it otherwise would have an undefined value.

> Error: instance variable '@user_input' of Shell must be String, not (String | Nil)

It's possible for `IO#gets` to return `nil` if called at the end of an IO. See https://crystal-lang.org/api/IO.html#gets%28chomp%3Dtrue%29%3AString%3F-instance-method. Maybe the answer is a dedicated method or something that does `gets.not_nil!` for you if you know the IO won't be empty, like `STDIN`. Otherwise you'd just need to handle `nil` like you would any other time by either using `.not_nil!` if you know 100% it won't be `nil`, or do like `.gets || ""` or use `#try`, an `if` statement etc.

**Comment by straight-shoota** [comment]
> if I do .gets, why is a nil possible? Isn't .gets short for "get string"? So I'd get a String?

The behaviour of `gets` in Crystal is identical to Ruby. In both languages, it returns `nil` when the stream is closed.
The only difference is that Crystal's type checker compels to regard the nil case with a compile time error, whereas in Ruby you would only get a runtime exception in the event of a closed stream. So while writing the Ruby code is easier, it can easily contain hidden bugs (or undefined behaviour).

**Comment by HertzDevil** [comment]
In case you are wondering, `$stdin.gets.chomp` _does_ error in Ruby Typeprof:

```
$ cat rbstest.rb
$stdin.gets.chomp
$ rbs method IO gets
::IO#gets
  defined_in: ::IO
  implementation: ::IO
  accessibility: public
  types:
      (?::String sep, ?::Integer limit) -> ::String?
$ typeprof rbstest.rb -v
# TypeProf 0.21.2

# Errors
rbstest.rb:1: [error] undefined method: nil#chomp

# Classes
```

So Crystal has really been doing what Ruby does for a long time, except we also show the compile-time type of the failing receiver.

**Comment by HertzDevil** [comment]
Closing. Having the compiler instruct the user on every occasion where Crystal's stdlib differs from Ruby's is not a viable option.
