### ISSUE TITLE
std/dir_spec.cr fails when the current working directory path contains symlinks

### ISSUE THREAD

**Issue by dmgk** [crystal-lang/crystal#12325]
To reproduce:
```
$ ls
crystal/
$ ln -s crystal cr; cd cr
$ bin/crystal spec spec/std/dir_spec.cr
Using compiled compiler at /home/user/crystal/.build/crystal
......................................................F.................

Failures:

  1) Dir .current
     Failure/Error: Dir.current.should eq(`#{{{ flag?(:win32) ? "cmd /c cd" : "pwd" }}}`.chomp)

       Expected: "/home/user/cr"
            got: "/home/user/crystal"

     # spec/std/dir_spec.cr:511

```
getcwd(3) always returns path with all symlinks resolved but the `pwd` shell builtin may return a "logical" path with symlinks. I think the  fix here would be to call `env pwd -P` instead to make sure the spec compares two physical paths.

**Comment by straight-shoota** [comment]
Hm, this might actually an error (or perhaps a shortcoming?) in the implementation. IMO the spec is correct.
I would expect `Dir.current` to return the same value as `pwd` in the shell, i.e. the literal path including symbolic links. That would be the least surprising result and match typical user expectations.
And you can easily resolve the symlink path with `File.real_path` in case you want the other, while the opposite direction is not as simple.

Thus the implementation should rather use the GNU extension function `get_current_dir_name` instead of `getcwd`. We'd probably have to implement it ourselves though, because `get_current_dir_name` is not available on all platforms (including FreeBSD).

The difference is simply to check whether the environment variable `PWD` is set and - with symbolic links resolved - points to the same directory as `getcwd` .

This is a bit overhead when you actually need the path with symbolic links resolved, so we could consider adding a variant which efficiently returns the value from `getcwd` without taking `PWD` into account.

**Comment by Blacksmoke16** [comment]
If you're on FreeBSD this was brought up in the past via https://github.com/crystal-lang/crystal/pull/12117, but it was closed by the author. I added some context in one of the comments for what we discovered was going on.

**Comment by straight-shoota** [comment]
Btw. on windows this seems to be the actual behaviour (provided by `GetCurrentDirectoryW`)

```console
$ cmd.exe /c dir
27.07.2022  01:10    <SYMLINKD>     bar [foo]
27.07.2022  01:07    <DIR>          foo
$ crystal.exe eval 'Dir.cd("bar"); puts Dir.current'
C:\tmp\bar
```

For comparison, on Linux. I'm running exactly the same program in exactly the same directory (Windows file system mounted in WSL2).
```console
$ ls -l
total 0
lrwxrwxrwx 1 johannes johannes   3 Jul 27 01:10 bar -> foo
drwxrwxrwx 1 johannes johannes 512 Jul 27 01:07 foo
$ crystal eval 'Dir.cd("bar"); puts Dir.current'
/mnt/c/tmp/foo
```

**Comment by dmgk** [comment]
@Blacksmoke16 yes, this is easily reproducible on FreeBSD due to the `/home` being a symlink. But the `pwd -P` (the binary, not the shell builtin) should behave [the same way everywhere](https://pubs.opengroup.org/onlinepubs/007904875/utilities/pwd.html), do you have an example of a platform where this is not the case? Using the builtin might work too (bash's pwd supports -P, as does FreeBSD's sh), but I'm not sure about other shells.
