### ISSUE TITLE
Add "unsafe"

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#124]
The idea is to have methods marked as `@[Unsafe]` and to call them you either have to mark a method as unsafe or use an unsafe block. Some primitives will be unsafe by default, like `Pointer#value` and all C functions.

For example:

``` ruby
def foo
  data = Pointer(Uint8).malloc(10)
  data.value # error: must use unsafe or mark foo as unsafe
end

def bar
  data = Pointer(Uint8).malloc(10)
  unsafe { data.value } # ok, inside unsafe block
end

@:Unsafe
def baz
  data = Pointer(Uint8).malloc(10)
  data.value # ok, baz is unsafe
end
```

`unsafe` is not a method, it's a keyword and must be used with `{ ... }` or `do ... end`.

This will be useful to clearly detect which code is unsafe and also to try to reduce unsafe code as much as possible.

This is just the basis of the idea, some things might change.

**Comment by ysbaddaden** [comment]
I'm resurecting this back, because this would an awesome feature to add, and apparently not hard to implement I'm told.

Yes, it puts a burden to the developer, and as one that wrote C bindings (e.g. sockets, SDL2, JNI) I know I won't have any fun to mark methods and wrap all C calls into unsafe blocks... but the benefits to the language and safety shall trump the initial burden.

All methods from `Pointer` should be marked unsafe, some constructors like `String.new(pointer)`, C functions that involves pointers, casting a pointer... well, anything that involves pointers, which we don't normally use in normal code, so the burden is limited.

Strong :+1: from me!

**Comment by shelvacu** [comment]
I also had this same idea, I'm glad to see such a feature is planned.

However, I forsee this making writing crystal versions of C libraries annoying. For example, in the sqlite3 library, I would argue that most of the `sqlite3_*` functions should be marked unsafe because they take in a pointer, and if it does not point to a sqlite3 struct the result is undefined.

With the proposal as-is, a library to safely interact with the sqlite3 lib would have to use an `unsafe{}` block in every function. I think it would be better to have the module/class marked as `@[UnsafeToSafeAdapter]` or something (need a better name) to indicate that all of that module's functions deal with unsafe code but should be safe.

**Comment by straight-shoota** [comment]
*All* C functions would automatically be marked as unsafe. See @asterite's original post. That's is because they run in C land and are not protected by Crystal's awesomeness.

> a library to safely interact with the sqlite3 lib would have to use an unsafe{} block in every function

I think that's the point of this feature. What would be the benefit if you didn't have use it for C library wrappers? Their purpose is to make a safe adapter to an unsafe library and therefore must wrap unsafe calls with `unsafe` and expose `safe` methods as a Crystal API.

**Comment by shelvacu** [comment]
As is proposed, a library might look like

```crystal
lib LibFoo
  fun foo(data : UInt8*, data_size : LibC::SizeT)
  fun bar(data : UInt8*, data_size : LibC::SizeT)
  fun baz(some_int : Int32)
end

module DoLibThingsSafely
  def foo(arg : String)
    unsafe{
      LibFoo.foo(arg, arg.size)
    }
  end

  def bar(arg : String)
    unsafe{
      LibFoo.bar(arg, arg.size)
    }
  end

  def baz(arg : Int32)
    unsafe{
      LibFoo.baz(arg)
    }
  end
end
```

Instead, I would propose something like:

```crystal
lib LibFoo
  #...
end

@[UnsafeToSafeAdapter] #Needs a better name
module DoLibThingsSafely
  def foo(arg : String)
    LibFoo.foo(arg, arg.size)
  end

  def bar(arg : String)
    LibFoo.bar(arg, arg.size)
  end

  def baz(arg : Int32)
    LibFoo.baz(arg)
  end
end
```

Does that make sense? Hopefully makes the code a little DRY-er.

**Comment by ysbaddaden** [comment]
The whole point of this proposal is for unsafe code sections to be specifically marked as such: unsafe. Marking a whole type as unsafe would be counterproductive.

**Comment by shelvacu** [comment]
If all the code within the type is unsafe, why is it counterproductive to mark it as such?

**Comment by RX14** [comment]
@shelvacu Firstly, because it's rare for truly *all* code in a type to be unsafe. Secondly, because it moves the "unsafe" declaration too far away from the code which is unsafe. Using unsafe should be *annoying* and it should be *obvious*.

**Comment by shelvacu** [comment]
>Using unsafe *should* be annoying and it *should* be obvious.

Yeah, that makes sense. Nevermind about that whole-class-marking.

**Comment by ysbaddaden** [comment]
Oh, really? No unsafe wrapper?
