### ISSUE TITLE
macOS/arm64 lib binding incorrect

### ISSUE THREAD

**Issue by threez** [crystal-lang/crystal#12407]
## Bug Report

Can't read/write structs with floats under macOS/arm64.

### rect.c

```c
typedef struct _Rect {
  float x;
  float y;
  float w;
  float h;
} Rect;

Rect sample() {
  Rect r = {
    .x = 150,
    .y = 250,
    .w = 1.53,
    .h = 3.12,
  };
  
  return r;
}
```

### rect.cr

```crystal
@[Link(ldflags: "#{__DIR__}/rect.o")]
lib LibRect
  struct Rect
    x : LibC::Float
    y : LibC::Float
    w : LibC::Float
    h : LibC::Float
  end

  fun sample : Rect
end

p LibRect.sample
```

### Environment

MacOS MacBook Pro (14-inch, 2021) Apple M1 Pro

```
$ crystal -v
Crystal 1.5.0 (2022-07-06)

LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0
```

### Reproduce

```
$ gcc -c rect.c
$ crystal rect.cr
LibRect::Rect(@x=2.7306424e-37, @y=1.0e-45, @w=0.0, @h=0.0)
```

**The same code works under linux!**

**Comment by mattrberry** [comment]
I'm seeing a very similar bug in one of my own projects that I suspect is due to the same cause. I took a look at the generated IR and compared it to what Rust emits. They're nearly identical. Distilling the IR from both yields something like the following:

Rust:
```llvm
source_filename = "rect_rs.bc30dfcd-cgu.0"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx11.0.0"

%Rect = type { float, float, float, float }
...
  %0 = alloca [4 x float], align 4
  %_1 = alloca %Rect, align 4
  %1 = call [4 x float] @sample()
  store [4 x float] %1, [4 x float]* %0, align 4
  %2 = bitcast %Rect* %_1 to i8*
  %3 = bitcast [4 x float]* %0 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 %2, i8* align 4 %3, i64 16, i1 false)
...
declare [4 x float] @sample() unnamed_addr #1
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #3
```

Crystal:
```llvm
source_filename = "main_module"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-apple-darwin21.6.0"

%"struct.LibRect::Rect" = type { float, float, float, float }
...
  %0 = alloca [2 x i64], align 8
  %1 = alloca %"struct.LibRect::Rect", align 8
  %2 = call [2 x i64] @sample()
  store [2 x i64] %2, [2 x i64]* %0, align 8
  %3 = bitcast [2 x i64]* %0 to i8*
  %4 = bitcast %"struct.LibRect::Rect"* %1 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 %4, i8* align 4 %3, i64 16, i1 false)
...
declare [2 x i64] @sample()
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #1
```

It seems that the practical differences here are that Rust chooses to use `[4 x float]` and 4-byte alignment while Crystal [chooses](https://github.com/crystal-lang/crystal/blob/cd3081f3b87ef6c777255197d35e140b8249c534/src/llvm/abi/aarch64.cr#L133) to use `[2 x i64]` and 8-byte alignment. That said, I don't really see what those would impact. However, at this point I'm out of my depth on my project and I imagine somebody more familiar with the codebase and LLVM could have greater impact.

I'd _love_ to see aarch64-darwin become a first-class platform for Crystal. My emulator projects compile 5x faster on the current generation of Apple silicon than on my x86_64 linux devices, which fundamentally changes the dev cycle

**Comment by beta-ziliani** [comment]
@mattrberry can you (or @threez or anyone with an M1) post the entire .ll file from the following, with `crystal build --emit llvm-ir --prelude=empty rect.cr` so it's minimal. Thanks!

```crystal
lib LibC
  alias Float = Float32
end

@[Link(ldflags: "#{__DIR__}/rect.o")]
lib LibRect
  struct Rect
    x : LibC::Float
    y : LibC::Float
    w : LibC::Float
    h : LibC::Float
  end

  fun sample : Rect
end

x = LibRect.sample
```

**Comment by mattrberry** [comment]
https://gist.github.com/mattrberry/ebdd8547213a6b80baf287b964eeb058

This is on MacOS 12.5 on M2 with
```
$ crystal --version
Crystal 1.5.0 (2022-07-06)

LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0
```
