### ISSUE TITLE
Double negative sign when rounding to negative 0.0

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#12411]
```crystal
puts -0.01.format(decimal_places: 1) # => --0.0
```

A good question is if the output should be `0.0` or `-0.0`.

**Comment by Sija** [comment]
`-0.0` doesn't have much sense IMO, as zero is neither positive nor negative.

**Comment by mattrberry** [comment]
> `-0.0` doesn't have much sense IMO, as zero is neither positive nor negative.

IEEE 754 requires signed 0. It's a fair question whether Crystal exposes that to the user, but it "makes sense." Java exposes it, for example

**Comment by beta-ziliani** [comment]
Same as Ruby, BTW

**Comment by straight-shoota** [comment]
This is actually not a bug in `Number#format`.

The underlying problem is that `-0.0.abs == -0.0` because this implementation assumes that 0 is unsigned:
https://github.com/crystal-lang/crystal/blob/3c4969ff002b6417cfda5599a25106e893b3ee0e/src/number.cr#L154-L156

We should fix this to use the actual sign and return a positive value for `Float#abs`.
