### ISSUE TITLE
Allow using U/Int128  somehow broke Lucky

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#12516]
We started having an issue with Crystal nightly that was tanking Lucky with an undefined constant error.

```
lucky on  main is 📦 v0.30.1 via 🔮 v1.5.0 
❯ /home/jeremy/Development/crystal/lang/bin/crystal spec --error-trace
Using compiled compiler at /home/jeremy/Development/crystal/lang/.build/crystal
error in line 1
Error: while requiring "./spec/charms/hash_spec.cr"

In spec/charms/hash_spec.cr:1:1

 1 | require "../spec_helper"
     ^
Error: while requiring "../spec_helper"


In spec/spec_helper.cr:2:1

 2 | require "../src/lucky"
     ^
Error: while requiring "../src/lucky"


In src/lucky.cr:20:1

 20 | require "./lucky/*"
      ^
Error: while requiring "./lucky/*"


In src/lucky/action.cr:1:1

 1 | require "./*"
     ^
Error: while requiring "./*"


In src/lucky/base_component.cr:1:1

 1 | require "./html_builder"
     ^
Error: while requiring "./html_builder"


In src/lucky/html_builder.cr:3:1

 3 | require "./mount_component"
     ^
Error: while requiring "./mount_component"


In src/lucky/mount_component.cr:39:26

 39 | def mount(_component : Lucky::BaseComponent, *args, **named_args) : Nil
                             ^-------------------
Error: undefined constant Lucky::BaseComponent
```

I ran a bisect from the last time we had green specs, then I did a `make clean crystal` each time:

```
lang on  master 
❯ git bisect start

lang on  master (BISECTING) 
❯ git bisect good f276d706a92d5593558ae2f45b2a5671a619114a

lang on  master (BISECTING) 
❯ git bisect bad abe4d344cc1807223982a7f629563487a0faabb5
Bisecting: 16 revisions left to test after this (roughly 4 steps)
[c7d90c562c700bd9d9d8e12cacfd5d5348cb43a9] Fix docs error for File.match? `**` globbing pattern. (#12343)
```

This is the commit that breaks it https://github.com/crystal-lang/crystal/commit/b5a03cf and this is the last good commit https://github.com/crystal-lang/crystal/commit/bd6dca1

**Comment by asterite** [comment]
I wonder if it's not that "declare local vars blah blah blah" PR that we weren't sure would break things. Now I'm almost sure that's the cause.

Can you try reverting https://github.com/crystal-lang/crystal/commit/bd6dca1de1dc90edc97a77c7969ff6104007394c on master and see if that fixes things?

**Comment by jwoertink** [comment]
It's still broken with that commit reverted.

**Comment by wontruefree** [comment]
This looked like a load order problem to me.  I added to abstract class deceleration above the require and it worked for me. not a great solution but it might help prove the problem.


```
abstract class Lucky::BaseComponent
end

require "./html_builder"

abstract class Lucky::BaseComponent
  include Lucky::HTMLBuilder
...
```

I am suspicious this [PR](https://github.com/crystal-lang/crystal/pull/10711) might have something to do with this because of the areas of the compiler it is changing.

**Comment by HertzDevil** [comment]
Reduced:

```crystal
# `Foo` is not defined, `foo` is not called
def foo(x : Int32.class); end
def foo(x : Foo); end # Error: undefined constant Foo
```

Normally, when a new method is added, the compiler checks whether the new method is more specific than the old one, and then, that check failing, whether the opposite holds. After #10711 the compiler always checks in both directions, which causes the above error to show up. This is to say the following errors even without that PR:

```crystal
# `Foo` is not defined, `foo` is not called
def foo(x : Foo); end # Error: undefined constant Foo
def foo(x : Int32.class); end
```

The usual convention is to leave them unordered if the types are undefined, because calling the method would produce the same error anyway.
