### ISSUE TITLE
Unable to use `crystal play` on localhost

### ISSUE THREAD

**Issue by Vici37** [crystal-lang/crystal#12587]
A quick search through existing issues for `playground` didn't yield anything recent, apologies if I missed a previous version of this bug.

As of crystal 1.6, I'm running into the issue where `crystal play` sets up and listens to `http://127.0.0.1:8080`, but navigating to `http://localhost:8080` yields a `Connection lost. Refresh` error in the web UI, and a log line `crystal.playground: Invalid Request Origin: http://localhost:8080` being displayed in the terminal. 

Going to the IP address directly works just fine.

Thanks for the continued development of the crystal language!

**Comment by straight-shoota** [comment]
This is a regression introduced by #12356.

A simple workaround is to configure the server to listen on any address: `crystal play -b 0.0.0.0`.

The cause is in this piece of code:

https://github.com/crystal-lang/crystal/blob/41573fadba11fecc43c03b838c27bdb816e1b928/src/compiler/crystal/tools/playground/server.cr#L538-L548

Before https://github.com/crystal-lang/crystal/pull/12356 `@host` was apparently always `nil`. That's no longer the case.

But that `accept_request?` has multiple other issues. It doesn't work when bound to port 80 (because the default port is omitted in the `Origin` header). And it generally does not work when the server is accessed through a host name (instead of an IP address). So this does not just affect `localhost`. It's by far the most common use case, certainly.

I do not entirely understand the reasoning for this origin validation in the first place. What's the reason for that? The playground is primarily an internal development tool, I wouldn't worry too much about security issues and prioritize convenience for users. (I'm not sure what exactly this check is supposed to prevent/protect from). After all, you can get requests with arbitrary header values, so it would be trivial to circumvent this validation.
It was apparently introduced in https://github.com/crystal-lang/crystal/commit/7e37c244c2f05984677141858cbf8e733ea413b but without any explanation for the reason. @bcardiff can you shed some light on this?

**Comment by bcardiff** [comment]
There was a security issue raised by @tprynn at that time that would allow IIRC crystal code to be submitted and executed from other location. I don't have access to that report anymore, it was in the `@manas.tech` account. Maybe @matiasgarciaisaia has access that security report where there were some repro steps.

I'm not sure if bind/listen http refactors happened before 0.20 when that code was released. Maybe the check is no longer needed. Definitely a lot changed since then. I agree that the using it with implicit port 80 will not pass that validation. But most important checking a header value is not enough to mitigate unwanted connections. Maybe we need some token to mitigate things properly.

**Comment by straight-shoota** [comment]
Thanks.

I don't think this provides any meaningful security because you can just send arbitrary `Origin` headers.

So it's probably best to remove this validation entirely.

**Comment by tprynn** [comment]
It's been a long time since I reported this issue, but I believe the context of requiring a valid Origin header was to prevent attacks originating from the browser. Because browsers guarantee a valid Origin (can't be controlled by a malicious site targeting the Crystal playground), it would prevent some random site like example.com to send a request (i.e. CSRF) which executes code on your machine through the playground. Other machines on the network or processes on the local machine can still control the Origin header so this protection does not relate to them.

You could consider changing the check to either check for 127.0.0.1 or localhost.

**Comment by straight-shoota** [comment]
Thanks, @tprynn for the recollection.

I don't think this offers any protection about a relevant attack vector. It only prevents direct API requests from a browser on a different origin site. But a malicious site could just direct such requests through their own server which allows it to forge the `Origin` header. Or a malicious user could just access the playground directly through its own web interface (which has no access restrictions in any way).

The playground is exclusively intended as an internal tool and definitely not prepared for public use. So you should never expose it to a public network, whatsover. This pretty much eliminates any consideration about attach vectors and mitigations. It should never be reachable for anyone you cannot trust.

**Comment by tprynn** [comment]
The interesting point of this type of CSRF attack is that it uses *your own browser* as a point inside your own network / on your own computer. So it's not meaningful to consider whether you expose the playground externally (i.e. bind it on a local network or public IP address) - rather, this attack still works as long as I can get you to visit any random site in your browser, if the playground is running on your computer.

**Comment by tprynn** [comment]
Here's a relevant bug which demonstrates a similar problem: https://bugs.chromium.org/p/project-zero/issues/detail?id=1524

**Comment by straight-shoota** [comment]
Yes, the immediate issue would be fixed by being more lenient on `localhost` and `127.0.0.1`.

But the usability problem affects any hostname, not just `localhost`. If I connect to the playground with a host name (for example because its running on a device in my network), the origin header won't validate because the browser sends the hostname, but the playground only knows the IP address it listens to.

**Comment by tprynn** [comment]
In the case where a web app needs a hostname, I believe typical practice is for the app to know its own hostname (i.e. passed in configuration / command line flag). Then it can check against that hostname in the Origin field.

**Comment by straight-shoota** [comment]
I'm not talking about a case where the app *needs* a hostname. Just that the server runs on a network device and I use a hostname to access that device. Neither the device nor the app need to be aware of that hostname.

**Comment by tprynn** [comment]
I'm not sure we're communicating very well at this point, and I don't really have any skin in the game (I haven't used crystal since messing around with it many years ago). Basically to me, it looks like the change you're suggesting opens a significant security hole. Without investigating the low level details of the app and your suggested change, I can only suggest general patterns of how to approach the issue. It seems to me that requiring a small config change by the user in order to more safely run this app which is like "code execution as a service" on the network is a relatively small burden, and worth the effort when the alternative is to allow remote attackers to exploit RCE.

**Comment by straight-shoota** [comment]
I'm very thankful for your input! 👍 It's a great example for participation in the general open source community, even with no/minimal direct ties to the particular project.  🙇 

#12599 is a more minimal fix for the main problem with `localhost`. It's probably best to merge that into 1.6.1 as a bug fix and delay further changes to a later point.

**Comment by straight-shoota** [comment]
Closing. The immediate issue was fixed in https://github.com/crystal-lang/crystal/pull/12599
We could consider further enhancements in the future to allow more flexibility. But that would be a separate feature discussion.
