### ISSUE TITLE
Line numbers in exception

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#1270]
When an exception is raised, it would be very helpful if the resultant stack trace contained line numbers. As things stand, I pretty much have to _guess_ where the error is.

**Comment by technorama** [comment]
+1

**Comment by sardaukar** [comment]
not sure how easy this is to do, but +1

**Comment by lakshgupta** [comment]
+1

**Comment by Nakilon** [comment]
Does :+1: comment influe anything? )

**Comment by stugol** [comment]
Any movement on this issue?

**Comment by stugol** [comment]
Bump. This is really important.

**Comment by kirbyfan64** [comment]
...and it's also surprisingly complicated...

**Comment by miketheman** [comment]
#triage 
Having some method to trace the error back to source is useful.
Is there something we can do to help push this forward?

**Comment by ysbaddaden** [comment]
I believe (I can be wrong) that it needs a better LLVM debug integration, which in turn would mean upgrading to LLVM 3.8, since the debug API changed since LLVM 3.6.

Alternatively, maybe look at debug tools like `gdb` or `lldb` to understand how they are capable to access the file:line when the program is built with `--debug` and replicate this in Crystal. Still, it won't be capable to show the complete trace, since non-captured blocks are inlined (see #2785).

**Comment by sdogruyol** [comment]
Since https://github.com/crystal-lang/crystal/pull/3303 is merged, can we close this @ysbaddaden @asterite ?

**Comment by ysbaddaden** [comment]
Yes.

**Comment by sdogruyol** [comment]
@ysbaddaden thank you ❤️
