### ISSUE TITLE
Propose for short circuit version's #try.

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12710]
## Discussion

Mo discussion check https://forum.crystal-lang.org/t/ask-some-questions-thanks-again/5058/1

In short, i want introduce the short circuit version of #try, as describe on the official document

https://dart.dev/null-safety/understanding-null-safety#smarter-null-aware-methods

Check following the not so good example. (but hope can describe my key point clearly)

```crystal
y = if rand > 0.5
      if rand > 0.5
        [[1, 2, 3]]
      else
        [nil]
      end
    else
      nil
    end


y.try &.first.try &.each do |e|
  p e
end
```

Above code work, but a little tedious, any others case use ``if condition + &&`` is not good too.

So, i propose as describe in above dart document:

```crystal
y = if rand > 0.5
      if rand > 0.5
        [[1, 2, 3]]

      else

        [nil]
      end
    else
      nil
    end


y.try &.first.each do |e|
  p e
end

# Error: undefined method 'each' for Nil (compile-time type is (Array(Int32) | Nil))

```

I guess this should need some compiler support anyway.

**Comment by oprypin** [comment]
The document about Dart that you're referring to says it was bad that people had to write
```dart
[123, 45] .firstOrNull ?.toString ?.length
```
so they redesigned the meaning of the `?.` operator in a way that enables writing this:
```dart
[123, 45] .firstOrNull ?.toString .length
```
Specifically the grouping of operations changed from
```dart
(([123, 45] .firstOrNull) ?.toString) ?.length
```
to
```dart
[123, 45] .firstOrNull ?(.toString ?(.length) )  //not a real syntax
//or after dropping the unnecessary check:
[123, 45] .firstOrNull ?(.toString .length )  //not a real syntax
```
---
Your description is difficult to follow but I'm guessing that you're saying that it's bad in Crystal that people have to write
```crystal
[123, 45] .first? .try &.to_s .try &.size
```
but in fact, that's not true! People can and should just write
```crystal
[123, 45] .first? .try &.to_s .size
```
That is because the grouping of operations already works in your favor, this is what's implied:
```crystal
[123, 45] .first? .try( &.to_s .size )
```
Or you could intentionally group it in a bad way:
```crystal
([123, 45] .first? .try &.to_s) .try &.size
```

You are proposing to replace a bad situation with a good situation "like Dart" but there is no bad situation in the first place, so I think the proposal is not valid.

**Comment by oprypin** [comment]
There may be something specific about the precedence of the `do` syntax that interferes with the grouping of operations, but I'm on mobile so I can't reasonably check that.

But basically could you try to change from `do` `end` to `{` `}` and see if your problem still persists?

**Comment by zw963** [comment]
> The document about Dart that you're referring to says it was bad that people had to write

Sorry, I may have misremembered.

---

> But basically could you try to change from `do` `end` to `{` `}` and see if your problem still persists?

My example change to `y.try &.first.each { |e| p e }`, right?  still same error.

```
Showing last frame. Use --error-trace for full trace.

In 1.cr:11:15

 11 | y.try &.first.each { |e| p e }
                    ^---
Error: undefined method 'each' for Nil (compile-time type is (Array(Int32) | Nil))

```

-----------

I'm starting to get confused ... why following code not work but your's example both of them work?

```
x = [nil]
x.try &.first.to_i32.to_s.size
```

```
Showing last frame. Use --error-trace for full trace.

In 1.cr:2:15

 2 | x.try &.first.to_i32.to_s.size
                   ^-----
Error: undefined method 'to_i32' for Nil
```

**Comment by oprypin** [comment]
OK so we can agree that the link to the Dart document describes a different situation than the code example that you're unsatisfied with. I'd say that Dart would require `?.` in all the same places as Crystal requiring `.try`


If you have a concrete proposal, please try to rephrase it on its own. Right now I think you just have some questions on why `.try` is necessary in some cases and not others.

**Comment by lbguilherme** [comment]
It's because `first` itself can return nil in case the array is empty. It has nothing to do with the fact that there is a `try` before that.

**Comment by zw963** [comment]
> It's because `first` itself can return nil in case the array is empty. It has nothing to do with the fact that there is a `try` before that.

Yes, you are right, but, i consider we can add #try to all latter?

```crystal
x = [nil]
x.try &.first.to_i32.to_s.size
```

What I want to express is, if the first invoke is nilable, a good assume is all latter invoke is nilable, right?

It has no side effects.

if this is not the expected case, user can rewrite above code more easily with:

```crystal
x = [nil]
y = x.first
y && y.to_i32.to_s.size
```
So, i consider above '#try' should apply to all latter invoke, this may be what I want to express.

```crystal
x.try &.first.to_i32.to_s.size
```

compiler should translate to:

```crystal
x.try &.first.try &.to_i32.try &.to_s.try &.size
```

Now, when run code like this, will give us confidence never raise exception.

```crystal
if rand > 0.5
  x = [nil]
else
  x = [123]
end

x.try &.first.try &.to_i32.try &.to_s.try &.size

# => will simpler to x.try &.first.to_i32.to_s.size
```

**Comment by asterite** [comment]
> i consider above '#try' should apply to all latter invoke

It's a good suggestion, but if we do that then if you have a `nil` somewhere but you want to handle it, the compiler won't be able to tell you "Hey, you have a `nil` value here that you might want to handle differently in this case". That's why we force you to handle `nil` on every place that it can show up: because it might need to be handled differently in each case.

I honestly don't think we'll have change this.

**Comment by beta-ziliani** [comment]
I understand the motivation, and I wouldn't oppose a _different_ method or notation to do an implicit chain of `#try`.

**Comment by asterite** [comment]
It can probably be done with a macro. Hard, but doable.

**Comment by straight-shoota** [comment]
`#try` is a very simple concept. It invokes the block on any type except `Nil`, so it trivially excludes `Nil` from type unions.

This issue is about something more complex: A mechanism that would transform a regular call chain into nil-protected `#try` semantics. Basically an implicit safe-navigation operator. This might be doable with macros. Definitely with compiler support. But it's a complex thing to implement and to understand.

Having a couple of `#try` in a call chain might not be entirely pleasing, but it's okay. It does the job, it's easy to understand and doesn't add too much noise.
And I actually don't see that many use cases. Usually you want explicit handling for `Nil` values. And deeply nested nilable structures are probably not that common. IMO it's not worth having a special tool for a relatively rare case when there is already a decent acceptable alternative.

An (explicit) safe navigation operator might make it a bit more concise, but we don't have that in Crystal (ref #2177).

For reference, this goes in a similar direction to enhanced `responds_to?` and a generic `compiles?` as discussed in https://github.com/crystal-lang/crystal/issues/2549#issuecomment-778893432 ff.
