### ISSUE TITLE
Fiber nesting highly limited on 32bit

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#1275]
With the following program

``` cr
def fiber_stack(n=1)
  spawn do
    fiber_stack(n+1)
    puts n
    sleep 3600
  end
end

fiber_stack
sleep 3600
```

It eats up my memory on 64bit (I killed it around n = 500 000), however on 32bit I merely get to 500, on some systems not even. Then it crashes with:

```
Process terminating with default action of signal 11 (SIGSEGV)
==379==  Access not within mapped region at address 0x15B
==379==    at 0x4094BB9: co_create (in /usr/lib/libpcl.so.1.0.11)
```

Maybe more interestingly, https://github.com/manastech/crystal/blob/master/src/fiber/fiber.cr#L22 turns into garbage:

```
377
@stack = Pointer(Void)@0xbef33000
378
@stack = Pointer(Void)@0xffffffff
```

**Comment by jhass** [comment]
Alright, `0xffffffff` is `MAP_FAILED`, raising `Errno` in that case: `Unhandled exception: Couldn't allocate fiber stack:: Cannot allocate memory`, guess there's not much to do about it? But 500 is really low :/

**Comment by waj** [comment]
I just tried on my Mac and stopped around 148000 fibers. The virtual mem was more than 1TB but the real resident memory was 1.18GB. That is around 8Kb per fiber. It could be better but definitely not bad :-)

Regarding the limitation in 32bit, the fiber stacks is currently fixed to 8MB and that's what the runtime allocates. It is lazily assigned by the OS as used (that's why each fiber only uses 8Kb in your example) but in 32bit the virtual address space is quickly exhausted: 2**32 / (8*1024*1024) = 512

Solving this issue requires making the fiber stack to grow dynamically. This could be either achieved using segmented stacks or moving the stack to a new place every time it needs to grow.

Rust used segmented stacks in the past but they decided to [abandon](https://mail.mozilla.org/pipermail/rust-dev/2013-November/006314.html) that idea. Go also used segmented stacks but now they reallocate the stack when needed: https://blog.cloudflare.com/how-stacks-are-handled-in-go/

In the future we might also move to a dynamically allocated stack. But I wonder if we do this just to be able to run thousands of fibers in 32bit? Is the extra complexity worth the effort? Isn't the virtual memory allocation enough for this purpose in 64bit?

**Comment by jhass** [comment]
Well, the main issue I see is a huge discrepancy between 32bit and 64bit environments, it's 300 times less, so a program that has no issue at all running in 64bit will suddenly stop working when run in a 32bit environment. Since Crystal is appealing for CLI tools, you do want a diverse as possible platform support out of the box, you don't always control your deployment scenario/target platform.

**Comment by waj** [comment]
But that could be always true. The limitations in 32bit and 64bit could be always different, so it's impossible to guarantee that any software working fine in 64bit can be happily moved to a 32bit  system.

Where that 300 comes from? In 32 bit the theoretical maximum is 512 fibers, while in 64bit is... well, practically unlimited, or limited by the available memory.

I naturally associate the number of fibers with the number of concurrent connections that a server is attending or any other parallel actions that a process is doing. A 32bit server could definitely handle more than 512 simultaneous connections, but how many more? We could tune the stack size so the limit could raise to 1024 or 2048. But again... being 32bit something that is slowly converting in something from the past, do we really want to take this limitation into account? I'm not saying we should not, but I'd like to have a more strong reason to move to a more complex memory allocation system that gives advantages to 64bit as well. Otherwise I feel we would be punishing the performance in 64bit just to be backward compatible with old 32bit systems.

**Comment by ozra** [comment]
64 bit is a much more powerful arch regarding memory addressing. I don't see much reason to complicate the matter to support thousands of fibers on 32 bit. I started coding on the C-64, it's 8 bit, I don't expect to run that there ;-)
This is one of the things that could potentially be implemented as an "alternative allocation mode" for 32bit, using a flag when compiling perhaps, and then knowing that the standard version is the reference (which would still be the default on 32 bit too). Or something. In my opinion it shouldn't get first class priority.
Just my 2 mBTC of course.

**Comment by straight-shoota** [comment]
I'm closing this . There hasn't been any activity in 5 years, so it doesn't seem there have been actual issues with this limitation. Can be revisited when issues arise.
