### ISSUE TITLE
Using instance vars in Reference and other top-level classes

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#1279]
Moved from #809

```crystal
class Reference
  def foo
    @foo
  end
end
```

(crash)

Maybe this shouldn't be allowed, because right now we are moving instance variables up in the hierarchy to know who "owns" them, for the case of virtual types. I'm also not sure adding instance variables to every type is a good idea.

**Comment by miketheman** [comment]
#triage Original report against Crystal 0.7.6. Still affected in 0.15.0: https://play.crystal-lang.org/#/r/yfk
0.16.0 does not exhibit the crash: https://play.crystal-lang.org/#/r/yfg

Not entirely certain which commit fixed it - tried bisecting my way back in time to find the commit, but trying to do a `checkout, clean, build <revision at the time` doesn't really work, probably due to some symlinking magic on compiler selection and backwards-incompatible fixes.

**Comment by jhass** [comment]
Everything between Crystal 0.15 and 0.16 should build with 0.15, so install 0.15 system wide and run `make clean; make` to built the intermediate revisions.

**Comment by miketheman** [comment]
@jhass Thanks for the pointer - I realized I had an issue in my bisecter - wasn't using the freshly-compiled `bin/crystal` to test. 

It appears this issue has Gone Away in https://github.com/crystal-lang/crystal/commit/29382ae4ccffd9be09b82eaca6fe152b26d1b100.

If that was intentional, recommend issue to be closed.
