### ISSUE TITLE
Name starting with non-ascii uppercase letter is not treated as constant

### ISSUE THREAD

**Issue by kolesar-andras** [crystal-lang/crystal#12791]
The following code does not compile:

```crystal
class ÁrvíztűrőTükörfúrógép
end
```

> Error: expecting token 'CONST', not 'ÁrvíztűrőTükörfúrógép'

Some corner cases to narrow the problem:

* `Á` fails
* `A` works
* `Aőű` works
* `AőűŐű` also works

When a name starts with non-ascii uppercase letter (for example `Á`) it is currently not treated as constant.

This bevaviour also causes a bug:

```crystal
Á = 1
Á = 2 # no error (Á is treated as a variable, not constant)

A = 1
A = 2 # Error: already initialized constant A
```

Running on Ubuntu 21.10:

```
$ crystal -v
Crystal 1.6.2 [879691b2e] (2022-11-03)

LLVM: 13.0.1
Default target: x86_64-unknown-linux-gnu
```

**Comment by HertzDevil** [comment]
The same can also be said about titlecase characters, i.e. `Char`s that belong to the Unicode `Lt` (letter titlecase) general category: `ǅ ǈ ǋ ǲ ᾈ ᾉ ᾊ ᾋ ᾌ ᾍ ᾎ ᾏ ᾘ ᾙ ᾚ ᾛ ᾜ ᾝ ᾞ ᾟ ᾨ ᾩ ᾪ ᾫ ᾬ ᾭ ᾮ ᾯ ᾼ ῌ ῼ`

Ruby also treats identifiers starting with titlecase characters as constants rather than variables.
