### ISSUE TITLE
Recursive splat expansion with `preview_overload_order`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#12854]
The following code currently works fine as of Crystal `1.6.2`:
```cr
class DataHash
  def self.new(*args : _) : self
    new args
  end

  def self.new(**args : _) : self
    new args.to_h
  end

  def initialize(args : ::Hash = ::Hash(NoReturn, NoReturn).new)
    pp args
  end

  def initialize(args : Enumerable)
    pp args
  end
end

DataHash.new(1, 2, 3)             # => {1, 2, 3}
DataHash.new(foo: "bar", bar: 10) # => {:foo => "bar", :bar => 10}
DataHash.new({"foo" => "bar"})    # => {"foo" => "bar"}
DataHash.new([false, 12])         # => [false, 12]
```

However when running it with the `-Dpreview_overload_order` flag, it now produces:
```cr
In test.cr:2:12

 2 | def self.new(*args : _) : self
              ^--
Error: recursive splat expansion: Int32, Tuple(Int32, Int32, Int32), Tuple(Tuple(Int32, Int32, Int32)), Tuple(Tuple(Tuple(Int32, Int32, Int32))), Tuple(Tuple(Tuple(Tuple(Int32, Int32, Int32)))), ...
```

**Comment by HertzDevil** [comment]
Definition order:

* `(*args : _)`
* `(**args : _)`
* `(args : Hash = ...)`
* `(args : Enumerable)`

Overload order of `DataHash.new` before `-Dpreview_overload_order`:

* `(args : Hash = ...)`
* `(args : Enumerable)`
* `(*args : _)`
* `(**args : _)`

After:

* `(*args : _)`
* `(args : Enumerable)`
* `(**args : _)`
* `(args : Hash = ...)`

This can probably be fixed by ensuring every restriction subsumes `_`, effectively making `_` behave like a top type (it can also be interpreted as an unnamed free variable).

Related, the following two defs are unordered, with or without the flag:

```crystal
class Foo
  def foo(x : _)
    1
  end

  def foo(x : Int32)
    2
  end
end

Foo.new.foo(1) # => 1
```
