### ISSUE TITLE
Missing `llvm_ext.o` in Linux release

### ISSUE THREAD

**Issue by mamantoha** [crystal-lang/crystal#12896]
When I try to compile `crystalline` I get this error:

```
Error target crystalline failed to compile:           
/home/linuxbrew/.linuxbrew/bin/ld: cannot find /var/lib/snapd/snap/crystal/1441/share/crystal/src/llvm/ext/llvm_ext.o: No such file or directory
```

__Issue 1__. Snap package missing `llvm_ext.o`.
__Issue 2__: The [latest](https://github.com/crystal-lang/crystal/releases/tag/1.6.2) release package for Linux (`crystal-1.6.2-1-linux-x86_64.tar.gz`) is also missing `llvm_ext.o`. But `crystal-1.6.2-1-darwin-universal.tar.gz` includes it.

For example, the Arch Linux [crystal](https://archlinux.org/packages/community/x86_64/crystal/) package includes `llvm_ext.o`. 

At the same time, the Ubuntu package (which is maintained by Crystal team) is missing it too:

```
dpkg -S crystal | grep llvm_ext
crystal: /usr/share/crystal/src/llvm/lib_llvm_ext.cr
crystal: /usr/share/crystal/src/llvm/ext/llvm_ext.cc
```

---

Is it a bug at all? Should the release packages include  `llvm_ext.o`? Or did I miss something?
Thanks!

**Comment by straight-shoota** [comment]
`llvm_ext.o` depends on the installed LLVM version. Hence it's not supposed to be packaged (unless the package would also install a specific LLVM version). There's a good chance it won't work with the version you have installed anyways.

The darwin package including it is probably just an omission. In the linux package we're explicitly excluding it: https://github.com/crystal-lang/distribution-scripts/blob/d8c44c0a2c977bfb90363923047f2c64cef3bf8e/docker/alpine.Dockerfile#L36 (related: #10880).

**Comment by kostya** [comment]
I have, the similar issue, just compile it by myself. and all works.
```
cd ~/Downloads/crystal-1.6.2-1/share/crystal/src/llvm/ext
gcc -c llvm_ext.cc `llvm-config --cppflags` -O3
```

**Comment by mamantoha** [comment]
Thanks, @kostya ! All works.

---

My case with Arch Linux and llvm13:

1. Compile `llvm_ext.o` from Crystal sources

   ```sh
   cd ~/src/crystal/src/llvm/ext
   gcc -c llvm_ext.cc `/usr/lib/llvm13/bin/llvm-config --cppflags` -O3
   ```

2. Build crystalline

   ```sh
   git clone https://github.com/elbywan/crystalline
   cd crystalline
   CRYSTAL_PATH=~/src/crystal/src:lib LLVM_CONFIG=/usr/lib/llvm13/bin/llvm-config shards build
```

**Comment by straight-shoota** [comment]
I suppose we could at least provide a makefile to build `llvm_ext.o` easier.

However, I'm also wondering if we can get rid of `llvm_ext` entirely at some point. I think by now many of the functions have an equivalent in `libllvm`.

**Comment by asterite** [comment]
Isn't that `make deps`?

**Comment by asterite** [comment]
```
$ make deps
c++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/opt/homebrew/Cellar/llvm@14/14.0.6/include -std=c++14 -stdlib=libc++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```

**Comment by straight-shoota** [comment]
Yes, when you have the source repository checked out. But the makefile is not distributed with the stdlib source.

**Comment by MyrddinE** [comment]
I'm encountering a similar error on Ubunto 22.04 LTS:

Building: crystalline
Error target crystalline failed to compile:     
/usr/bin/ld: cannot find /usr/share/crystal/src/llvm/ext/llvm_ext.o: No such file or directory
/usr/bin/ld: cannot find -lstdc (this usually means you need to install the development package for libstdc)++: No such file or directory
collect2: error: ld returned 1 exit status

I have to admit, I'm new to Ubuntu; I've only used Gentoo prior to this, so the idea of not having source code or debugging symbols installed for everything is a bit confusing to me. 😀 How would I resolve this? Do I need to install something extra for Crystal (since the file it's looking for is under the Crystal folder) or for LLVM?

**Comment by straight-shoota** [comment]
Haha, so far I've only seen people coming from Ubuntu and other binary package distributions being overwhelmed from building everything themselves in Gentoo 😆 

Actually, this fits perfectly because you just have to build the file. The sources should all be there in that `ext` directory. Only the Makefile is (probably) missing. It should be at `/usr/share/crystal/Makefile`.

It's this recipe though: https://github.com/crystal-lang/crystal/blob/bb96c5398e001f41b31431eea283a1a28198a84b/Makefile#L225C2-L225C2

So you can either copy the Makefile from the source repository and run `make llvm_ext` or run the command directly.
```shell
g++ -c -o llvm_ext.o llvm_ext.cc $(llvm-config --cxxflags)
```

**Comment by straight-shoota** [comment]
I think that's a question for the crystalline project.

**Comment by MyrddinE** [comment]
True, apologies, I wasn't paying attention and thought this issue was on the Crystalline git.
