### ISSUE TITLE
Add OAuth2::Client#make_token_request that returns http response

### ISSUE THREAD

**Issue by cyangle** [crystal-lang/crystal#12924]
OAuth2 has new features that are not supported in the std lib.

For example, in OAuth 2.1, PKCE is required for all OAuth clients using the authorization code flow.

Support for sender constraining as in DPoP requires a new HTTP request header and it also needs to handle Authorization Server-Provided Nonce. DPoP is not a standard yet but some IDP implementations already provide support for it.

These new features enhance the security of OAuth2 tokens.

Adding support for these new features to the std lib is a lengthy process and sometimes are not backward compatible.

Users of OAuth2::Client can workaround this by reopening it and adding new methods to support these new OAuth2 features which is not ideal.

#12921 solves this problem by making OAuth2::Client#get_access_token a public method with a flexible interface that supports custom headers, so that one can use new OAuth2 features by wrapping this method instead.

We can make it more future proof by exposing response headers and response body in this method.
For example, to support [Authorization Server-Provided Nonce](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop#name-authorization-server-provid), one needs access to the response body and response header to grab the server provided nonce.

This method is private so making changes to it and exposing it as public method are backward compatible.

Ref:
https://oauth.net/2.1/
https://oauth.net/2/dpop/
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop

@straight-shoota

**Comment by straight-shoota** [comment]
Sounds good 👍 But I think we can make it better than just make `#get_access_token` public.

`#get_access_token` is tailored specifically to the needs of the existing implementations of `#get_access_token_using_*` methods. It doesn't have a decisively generic interface, it just represents what's shared between the four methods currently implemented.
For making it broadly usable for custom applications, we should polish the API so that it works for advanced use cases as well.

From the above I gather that it needs to be able to customize request headers as input, and as output access to the response header as well as the entire body?

For the input headers, I'm wondering if they should be passed in as parameters, or maybe the header object could be yielded like the form builder. This might be a bit more consistent because both form parameters and request header are similar configuration, just on different levels of communication layers.

The output part sounds like we might want to extract `OAuth2::AccessToken.from_json` from the shared method and return instead the entire `response` instead. I suppose the status check should be good, though? I.e. only return the response when it's `ok` or `create` and raise otherwise.
`OAuth2::AccessToken.from_json` could be put in a separate method, but I suppose it should be easy enough to place it at the call site.

**Comment by cyangle** [comment]
@straight-shoota I have refactored my PR as suggested. Please review.
