### ISSUE TITLE
Change to TypeNode#has_constant? breaks Lucky

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#13095]
This PR https://github.com/crystal-lang/crystal/pull/12966 causes a break in Lucky. The code is a bit complicated, but this was as short as I was able to make it:

```crystal
module Assignable
  macro needs(*type_declarations)
    {% for declaration in type_declarations %}
      {% previous_declaration = ASSIGNS.find { |d| d.var == declaration.var } %}
      {% if previous_declaration %}
        {% raise "Duplicate Declaraction" %}
      {% end %}

      {% ASSIGNS << declaration %}
    {% end %}
  end

  macro inherit_assigns
    macro included
      inherit_assigns
    end

    macro inherited
      inherit_assigns
    end

    {% if !@type.has_constant?(:ASSIGNS) %}
      ASSIGNS = [] of Nil
      {% verbatim do %}
        {% if @type.ancestors.first %}
          {% for declaration in @type.ancestors.first.constant(:ASSIGNS) %}
            {% ASSIGNS << declaration %}
          {% end %}
        {% end %}
      {% end %}
    {% end %}
  end

  inherit_assigns
end

abstract class BaseComponent
  include Assignable
end

class Paginator::One < BaseComponent
  needs pages : Array(String)
end

class Paginator::Two < BaseComponent
  needs pages : Array(String)
end
```

Before that PR, this code compiles, but after, it will raise the `Duplicate Declaraction` error.

**Comment by Blacksmoke16** [comment]
The core difference seems to be `!@type.has_constant?(:ASSIGNS)` before was `true` 4 times, while after its `true` once, then `false` 3 times.

Looking into it more it's because before that PR `has_constant?` was not taking constants defined in the parent type into consideration. For example, given this code:

```cr
abstract class Base
  ASSIGNS = [1, 2, 3]
end

class Child < Base
end

{{pp Child.has_constant? :ASSIGNS}}
pp Child::ASSIGNS
```

Before that PR, it would print:
```sh
false
[1, 2, 3]
```
whereas after it prints:
```sh
true
[1, 2, 3]
```

Both are technically correct depending on how you look at it. But previously `has_constant?` seemed to behave more like `#defines_constant`, which maybe should be its own method?
