### ISSUE TITLE
Unable to use extra PCRE(2) options

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#13152]
## Bug Report

I've been playing around more with PCRE2 and have a use case where I want to prevent trailing newlines from being matched when using an ending `$` E.g. such that the regex `/^\/foo$/` would _not_ match `"/foo\n"` which is what the `PCRE2_DOLLAR_ENDONLY` option does. However this is not a valid option for a [Regex::Options](https://crystal-lang.org/api/Regex/Options.html) so I used the [Enums from Integer](https://crystal-lang.org/reference/1.7/syntax_and_semantics/enum.html#enums-from-integers) feature to create one based on the value from https://github.com/crystal-lang/crystal/blob/856fbe076c3f4e64d667770ad82ba57225e94183/src/regex/lib_pcre2.cr#L15 and gave that a try:

```cr
{{pp Regex::Engine}} # => PCRE2

pp Regex.new("^\\/foo$").matches? "/foo\n"                                 # => true
pp Regex.new("^\\/foo$", Regex::Options.new(0x00000010)).matches? "/foo\n" # => true
```
However it still didn't seem to work :thinking:. Looking into it more, I found that the PCRE2 code only seems to support the `Regex::Options` values: https://github.com/crystal-lang/crystal/blob/856fbe076c3f4e64d667770ad82ba57225e94183/src/regex/pcre2.cr#L47-L58 

Where as the PCRE code suggests it'll pass thru unamed values: https://github.com/crystal-lang/crystal/blob/856fbe076c3f4e64d667770ad82ba57225e94183/src/regex/pcre.cr#L25-L37

So I then tried the same thing using PCRE, grabbing the value from some other bindings I found online since it's not in ours:

```cr
{{pp Regex::Engine}} # => PCRE

pp Regex.new("^\\/foo$").matches? "/foo\n"                                 # => true
pp Regex.new("^\\/foo$", Regex::Options.new(0x00000020)).matches? "/foo\n" # => true
```

But it _still_ didn't seem to work. Ultimately I determined that using `#each` with flag enums just don't support unamed members while the actual underlying enum value _does_ have the unnamed member:

```cr
{{pp Regex::Engine}} # => PCRE

options = Regex::Options::IGNORE_CASE | Regex::Options.new(0x00000020)

options.each do |o|
  pp "Option: #{o}"
end

# => "Option: IGNORE_CASE"

pp options.value & 0x00000020        # => 32
pp options.value & LibPCRE::CASELESS # => 1
pp options.value & LibPCRE::DOTALL   # => 0 since its not set
```

I wasn't sure the best way to report this as it's a culmination of a few issues so decided to just create one describing all of them and can spin our other issues from here.

**Comment by straight-shoota** [comment]
Prior to #12802, `Regex::Options` was directly passed to `libpcre` so you could use custom values there.

Option values in PCRE and PCRE2 are different, so an abstraction is necessary.
Unfortunately, that makes it practically impossible to use unnamed values because it would be ambiguous.

So the plan was to essentially maintain the PCRE behaviour of `Regex::Options` to not break existing code that uses custom option values. The options for PCRE2 are mapped to the respective values in `libpcre2`. Obviously, this only works for named values. So unnamed values would be unavailable when using PCRE2 (at least for now).

Due to how `Enum#each` works, this logic doesn't seem to be working out as intended.

I think this is unexpected behaviour of `Enum#each`, but that's a different topic. For the regex options this is just an implementation detail. We can fix `Regex::Options` to implement the intended behaviour.

I'm afraid that won't satisfy your use case, though.

I reckon we can find some solution to make custom options possible. The main concern to maintain code compatibility with PCRE *and* PCRE2 at the same time. But maybe we can introduce some option to explicitly opt in for the PCRE2 behaviour or disambiguate in some way. A simple solution would be to just add additional option members to `Regex::Options`. That should make them immediately usable, but the code won't work for older Crystal releases.

**Comment by Blacksmoke16** [comment]
> A simple solution would be to just add additional option members to `Regex::Options`. That should make them immediately usable, but the code won't work for older Crystal releases.

If we're okay with introducing PCRE specifics into the public implementation. I know in the past we kind wanted to avoid that. E.g. #11320. However if we did go this way, couldn't we just base the value of the enum members on the current engine? E.g. something like `DOLLAR_ENDONLY = Regex::EngineLib::DOLLAR_ENDONLY`. Would have to add some additional modifiers to represent them tho...

Another solution that keeps things separated is just manually checking for additional options within the `pcre(2)_options` methods within each implementation. E.g.

```cr
if options.value & LibPCRE2::DOLLAR_ENDONLY > 0
  options |= LibPCRE2::DOLLAR_ENDONLY
end

if options.value & LibPCRE2::DOTALL > 0
  options |= LibPCRE2::DOTALL
end

# ...
```

I don't think we have to support _every_ possible option, but for my use case I just need these two so wouldn't be the end of the world. Both versions support them too so would be backwards compatible.

**Comment by Blacksmoke16** [comment]
Maybe I'm missing something, but why does using the unnamed `DOLLAR_ENDONLY` option also enable anchored mode, but not also show the unnamed member?

```cr
{{pp Regex::Engine}} # => PCRE2

regex = Regex.new "/(foo)/bar", Regex::Options.new(LibPCRE2::DOLLAR_ENDONLY)

options = regex.options

pp options                                  # => Regex::Options::ANCHORED
pp options.anchored?                        # => true
pp options.value & LibPCRE2::ANCHORED       # => 0
pp options.value & LibPCRE2::DOLLAR_ENDONLY # => 16
```

**Comment by straight-shoota** [comment]
> Maybe I'm missing something, but why does using the unnamed DOLLAR_ENDONLY option also enable anchored mode, but not also show the unnamed member?

You're comparing apples and oranges here. `Regex::Options::ANCHORED` just happens to be represented by the same integer value that equals `LibPCRE2::DOLLAR_ENDONLY`:

```cr
Regex::Options::ANCHORED.value # => 16
LibPCRE2::DOLLAR_ENDONLY       # => 16
```

**Comment by straight-shoota** [comment]
> Another solution that keeps things separated is just manually checking for additional options outside of the `#each` within the `pcre(2)_options` method within each implementation. Such that we can support a subset of the unnamed members without changing anything publicly.
>
> ```cr
>  if options.value & LibPCRE2::DOLLAR_ENDONLY > 0
>    flag |= LibPCRE2::DOLLAR_ENDONLY
>  end
>   
>  if options.value & LibPCRE2::DOTALL > 0
>    flag |= LibPCRE2::DOTALL
>  end
>  
>  # ...
>  ```

Sure we could do that. But this showcases exactly the problem that I described earlier: The values are ambiguous.

Continuing with the example that `LibPCRE2::DOLLAR_ENDONLY` and `LibPCRE::ANCHORED` are represented by the same integer value. Thus the same value of `Regex::Options` would mean different things, depending on whether the regex engine is PCRE or PCRE2.
If code uses these constants directly, it's not a big problem because typically only one of them should be defined (unless you require the lib bindings explicitly, which would technically be possible).
But when using the integer value directly, i.e. `Regex::Options.new(16)` the behaviour would be inconsistent and depends on the version of the regex engine.

**Comment by straight-shoota** [comment]
Unnamed regex options have been broken since https://github.com/crystal-lang/crystal/pull/12802, which was released in 1.7. Apparently nobody has noticed since then. So maybe that could be an indicator that unnamed regex options are not used a lot and we shouldn't bother too much about it.
It could also just mean that people haven't updated to 1.7 yet or simply not noticed anything breaking because it's a silent error.

**Comment by Blacksmoke16** [comment]
> `Regex::Options::ANCHORED` just happens to be represented by the same integer value that equals `LibPCRE2::DOLLAR_ENDONLY`

Ahh thanks, figured I was just missing something :see_no_evil:.

> If code uses these constants directly, it's not a big problem because typically only one of them should be defined (unless you require the lib bindings explicitly, which would technically be possible).

Wouldn't it be possible to still set the values of the enum to the lib consts based on the currently active engine given there can be only 1, either by default or one you explicitly opt into. Even if you require the bindings themselves, that wouldn't change the current engine. I also noticed some of the `:nodoc:` members value points to the PCRE1 values which could also be a point of conflict.

> Hence I would prefer to make additional options only available when the regex engine is explicitly chosen (or have some other means to opt-in).

> Crystal's `Regex` implementation never made any claims to support any options beyond the defined members of `Regex::Options`.

I'm assuming until we fully remove support for PCRE1? Because it would kinda suck to require every user of Athena/Athena Routing to use some flag just to use these options.

Is there any harm in actually just adding these to the enum and calling it a day then? That would probably solve a lot of the issues here given then there wouldn't be _any_ reason to use unnamed members at all.

**Comment by Sija** [comment]
> Is there any harm in actually just adding these to the enum and calling it a day then? That would probably solve a lot of the issues here given then there wouldn't be _any_ reason to use unnamed members at all.

Compatibility with other Regex backends might be an issue that comes to my mind.

**Comment by Blacksmoke16** [comment]
Sure, but I don't see that happening anytime soon. And even when/if it does it's going to be breaking anyway, so also removing two extra options isn't that big of a deal IMO.

It just feels kinda meh to me that we say we use PCRE but make it quite hard to use some of its features just because they may not be often used, or kinda niche. Granted there are deff some features that could use their own shard, e.g. https://www.pcre.org/current/doc/html/pcre2callout.html#TOC1, but otherwise I don't see a harm in having the simpler stuff just be available as a feature since the underlying engine supports it. Nothing a couple additional specs won't handle, versus requiring to monkeypatch the stdlib or keep a duplicate implementation with a handful of extra code :shrug:.

**Comment by straight-shoota** [comment]
Yeah, I suppose there's not too much benefit in restricting features just for the sake of being open to switch engines in the future. I think one outcome of the PCRE2 transition is that regexes in Crystal *are* deeply connected to the engine used to execute them. Even if we would keep the stdlib APIs simple and be able to port them, differences in regex syntax are to be expected. Changing to any engine that has more differences than PCRE and PCRE2 would most likely be a major breaking change.

Another concern is simplicity for the sake of maintaining the stdlib implementation. The goal of stdlib is to provide good tools that suffice for the majority of common use cases. But more complex features for nice use cases are better addressed outside of stdlib (#11320 could be one such instance).

**Comment by Blacksmoke16** [comment]
> Another concern is simplicity for the sake of maintaining the stdlib implementation.

IMO I'm still of the opinion that adding these 2 options, and even #11320, would add a negligible amount of maintenance overhead given the two options are consts and won't change, and the latter is already available, but just needs exposed via 1 additional bound method. Both of which can easily have robust test coverage. So beyond the initial implementation effort, which I'm happy to take point on, what would actually _be_ the maintenance overhead?

> But more complex features for niche use cases could be better addressed in a more dedicated manner outside of stdlib

As I mentioned in that other issue, it just feels like such a code smell in the ways you have to handle implementing these extra features outside of the stdlib via:

1. Monkeypatch the stdlib
2. Create a custom regex type by subclassing the stdlib type
3. Totally duplicate of the stdlib implementation, with a custom regex type

No matter which way you go, you then have to be aware of upstream changes and if they will break your implementation either via changes to the internal API in the first two cases, or remember to upstream fixes to your own in the latter case. Also, not all of these would be usable with `Regex` type restrictions, nor would you be able to make use of regex literals outside of the first option.

I get the rationale not wanting to add too many features to the stdlib for maintenance reasons, but I just think based on how regex are used, it will just be easier to have them in the stdlib. At least compared to say https://github.com/crystal-lang/crystal/issues/9048, which has support for a stdlib implementation, but could also be a shard given its more a more independent feature.

**Comment by asterite** [comment]
Whenever these proposals happen, it would be nice to check which other languages support that specific feature. If none of very few, it might mean that this isn't super needed.

**Comment by Blacksmoke16** [comment]
Based on https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines#Libraries, the three main languages that use PCRE are PHP, Julia, and R. Tho AFAIK the latter two are more math/statistic base langs versus a more general purpose language like PHP 🤷.

* PHP definitely does support both options and the MARK feature
  * https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php
    * `DOTALL` - `s` modifier
    * `DOLLAR_ENDONLY` - `D` modifier
  * https://www.php.net/manual/en/function.preg-match exposes the matched mark in a `MARK` key in the `$matches` assoc array
* Julia seems to support the `DOTALL` modifier by default, but not MARK or DOLLAR_ENDONLY, but does allow passing in custom options
   * https://github.com/JuliaLang/julia/blob/master/base/regex.jl#L61
 * Can't really find any mentions of it regarding R so prob also a no.

**Comment by asterite** [comment]
I think only php suuports it because it plainly exposes the engine. Given the recent upgrade here, I would avoid introducing features that are only available in a particular engine.

**Comment by asterite** [comment]
I guess you can match and also check if it doesn't end in a newline?

**Comment by Sija** [comment]
IMO I'd go with monkey patching and by smart redesigning the API (I think) you wouldn't need to overwrite much of the code.

**Comment by Blacksmoke16** [comment]
A comprise I'd be okay with is forgoing the MARK feature in the stdlib as I can easily enough patch that in, but IMO we should add the modifiers since you cannot reopen an enum, nor add custom values anyway due to #13155. They could either be public or, `:nodoc:` like those other values within the enum.

**Comment by straight-shoota** [comment]
This is a summary of the current situation with regex options:

* Originally `Regex::Options` mapped directly to the option values from `libpcre`. Exposed values were only `IGNORE_CASE`, `MULTILINE` (= `PCRE_MULTILINE | PCRE_DOTALL`), `EXTENDED` and `ANCHORED`. The first three are also available as modifiers on regex literals. You could use custom values such as `PCRE_DOLLAR_ENDONLY` which were directly passed on.
* https://github.com/crystal-lang/crystal/pull/12802 refactored the regex implementation to make the engine pluggable. `Regex::Options` keeps the same values. This refactor broke the ability to use custom values. They were simply ignored. With https://github.com/crystal-lang/crystal/pull/13155 the behaviour for PCRE should be identical to the original, i.e. unknown option values are passed through to `libpcre` unchanged.
* The PCRE2 engine implementation added in #12856 translates `Regex::Options` to `libpcre2` values. Only named members are supported. Custom values were originally ignored just as with PCRE, since #13155 an unknown option raises at runtime

I compiled a list of all option values used by PCRE and PCRE2: https://docs.google.com/spreadsheets/d/1t_qZGRaPCSBkRCxa07e5igdMpMQHp8HhRfPkCgVPeDo/edit?usp=sharing

Out of those, I think only a handful could be useful additions to the currently available options.

For example:
* DOLLAR_ENDONLY
* ENDANCHORED (PCRE2 only)
* FIRSTLINE
* NO_JIT (PCRE2 only)

Maybe we could just add them as named options and we're good.

However, I'm also thinking about changing `Regex::Option` to use the values from PCRE2 and map them to the PCRE equivalents. That's the new default and it doesn't make much sense to keep the old option values from PCRE2 around. This would allow using additional unnamed options with PCRE2 in the future. Also PCRE2 has some additional values that are not available in PCRE but might be useful (for example `ENDANCHORED`, ref https://github.com/crystal-lang/crystal/pull/9312#issuecomment-1477685614).

**Comment by straight-shoota** [comment]
@beta-ziliani proposed an alternative solution to have the values for `Regex::Options` depend on the engine. That would mean simplify things a bit as there's no need to map any values and you can just use the native values of the regex engine.
However, there may be some pitfalls with this approach because code that initializes `Regex::Options` with a fixed integer value becomes ambiguous (the meaning depends on the regex engine used). I guess this would be acceptable, though. To make sure, you'll have to check what `Regex::Engine` points to.

I know I had considered this approach when I implemented #12802, but I don't recall why I didn't choose it. I have a feeling that there may have been some blocking issue that I can't put my finger on.

**Comment by straight-shoota** [comment]
Actually, there is a major problem with changing: The compiler passes the integer value of the compiler's version of `Regex::Options` when expanding a `RegexLiteral`.

For example `/cat/i` expands to `Regex.new("cat", Regex::Options.new(1))` (with `PCRE_CASELESS = 0x00000001`).
With PCRE2 semantics for `Regex::Options`, this value would represent `PCRE2_ALLOW_EMPTY_CLASS`.

This obviously causes chaos if the library version of the compiler and the one used in stdlib have different semantics.

So we have three options (I think?):

* Avoid changing the semantics of `Regex::Options.new`. This essentially means keeping the values of `Regex::Options` fixed to PCRE semantics because everything else would be confusing.
* Make the compiler aware of the library version used in the program. This is a related problem to #12857 where it was also briefly considered to add compiler awareness. I think it should not be too difficult considering this only affects the three modifiers `i`, `m` and `x`. Still, it feels kind of weird to integrate this into the compiler.
* Change the compiler to represent the modifiers using names instead of values. This would be the preferred solution because it decouples the compiler from the stdlib implementation. I think this could be done in a backwards-compatible way so that the compiler would also be able to build an older stdlib. It would break forward compatibility though, as an old compiler would not be able to build a new stdlib unless they use the same regex library version (i.e. only with `-Duse_pcre`).

**Comment by bcardiff** [comment]
Yes it would require a delay. The only alternative that would not require a delay IMO is to offer a `Regex#initialize` that would translate PCRE1 options to PCRE2. 

I would avoid making the compiler aware of the linked PCRE version (your proposed option 2), I would rather decouple them for good by a std-lib convention. This makes future changes/customization easier, no changes in the compiler needed.

**Comment by straight-shoota** [comment]
I've been thinking a bit more about option 1. If we can find a good mechanism, going with that would probably be the least hassle. It wouldn't exclude changing the compiler as well, but that would not be a precondition for changes to `Regex::Options`.

For the compiler we technically only need `Regex::Options.new` to keep the semantics for the three modifiers expressed as PCRE options: the flag values 1, 2, 4, and 8 (and 0 of course). The compiler never emits anything else.

All other flag members can technically have arbitrary values. So far, we've chosen to use the same values as in PCRE1 for simplicity and backwards compatibility. But that doesn't need to be the case, or rather we don't need to be limited by that.

Perhaps it makes sense to consider the angle of decoupling the values of `Regex::Options` from any particular engine semantics entirely. That means we need to map the options in the bindings for both PCRE1 and PCRE2 to the values used in the respective engine versions.

It probably makes sense to keep the general semantics of the PCRE1 values, for backwards compatibility.
But we can also add additional enum members, even ones that are only supported in PCRE2. The values for those don't matter, but the PCRE2 would map them to the equivalents as with all the others, and the PCRE1 bindings would raise.

This would make it impossible to use unnamed members because arbitrary option values would not be supported (which essentially means reverting https://github.com/crystal-lang/crystal/pull/13155). All option values need to be explicitly supported by `Regex::Options`.
Thus, we need to add more members to `Regex::Options` in order to enable more use cases for regex options.

**Comment by straight-shoota** [comment]
I made a prototype implementation in #13223. Actually, it doesn't change much from the current implementation. The most significant change is defining more explicit option values (it's only a few so far, the ones proposed in https://github.com/crystal-lang/crystal/issues/13152#issuecomment-1477686472).

**Comment by straight-shoota** [comment]
I think with #13223 and #13248 we can consider this closed?
@Blacksmoke16 Am I missing something?

**Comment by Blacksmoke16** [comment]
@straight-shoota I'll try things out against master tonight and close this if everything looks good.

**Comment by Blacksmoke16** [comment]
Perfect yea. Was able to remove my custom regex type in favor of the stdlib implementation, passing in my required options. Future iterations can improve on things like #13150 can come in  a later release.
