### ISSUE TITLE
Undefined constant with record and improper properties

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#13343]
This is more of a bad error message than a bug.

```crystal
record Item, amount: Int32
Item.new(1)
```

In this code, the `record` is setup wrong by missing a space after the `amount`, but the error message is:

```
In foo.cr:1:8

 1 | record Item, amount: Int32
            ^---
Error: undefined constant Item
```

Where the correct code would be

```crystal
record Item, amount : Int32
Item.new(1)
```

**Comment by a-alhusaini** [comment]
I'm looking into this issue. Hopefully I'll have a PR for this in a few hours or tomorrow. Depending on how many obstacles I run into (My crystal is rusty)

**Comment by a-alhusaini** [comment]
Update: After looking into this more closely and discussing it on the community discord it seems that the error is caused by Crystal thinking that this is a named argument.

I initially expected that the error could somehow be detected and handled within the record macro itself. That would have been easy to fix.

But with this new information we now know that we'll need to get a hold of the compiler code that parses named arguments and add a conditional block to it that verifies that a named argument is actually a named argument. And if it isn't then it should print a more helpful error.

I've digged around in the compiler code but I haven't been able to find the chunk of code that needs to be changed. This should be relatively easy to fix if you know where to look. I don't.

I'll loook into this further tomorrow and see if I can locate the code that needs changing.

**Comment by straight-shoota** [comment]
Perhaps a trivial solution would be to just add a `**kwargs` parameter to the `record` macro to capture such a call signature and raise explicitly in the macro.

Basic implementation:
```cr
macro record(name, *properties, **kwargs)
  {% raise "unknown argument to macro `record`: #{kwargs}" unless kwargs.empty? %}

  # here follows the existing macro body
end

record Bar, foo: String # Error: unknown argument to macro `record`: {foo: String}
```

**Comment by a-alhusaini** [comment]
This current solution does not work with Strings. I am not sure why.
I tried
`record Cat, name: String`
This shows undefined constant
`record Cat, name: Int64`
This shows the error we want.

Any ideas?
