### ISSUE TITLE
Unclear semantics in macro yield

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#1338]
Let's have a yielding macro that defines a method that takes a parameter

```cr
macro foo
  def bar(baz)
    {{yield}}
  end
end

# ...

bar("Hi")
```

We try to call it and access the parameter, but nope:

```cr
foo do
  puts baz
end
```
```
Error in line 11: instantiating 'bar(String)'

in line 8: undefined method 'baz' (if you declared 'baz' in a suffix if, declare it in a regular if for this to work)
```
http://carc.in/#/r/dea

Let's have another macro, yielding one of its parameters
```cr
macro a(b)
  {{yield b}}  # Read before definition of b ?!
end

macro a(b)
  {{yield {{b}}}}  # Undefined macro variable b ?!
end

a("foo") do |c|
  puts {{c}}
end
```

Okay that doesn't work. But hey `do |c|` is not a syntax error! Okay, let's go back to our first macro
```cr
foo do |baz|
  puts baz
end
```
```
"foo"
```
http://carc.in/#/r/dee

Uhm, ...

**Comment by asterite** [comment]
The first snippet doesn't work because `baz` is parsed as a call. That is, when the parser sees:

```crystal
foo do
  puts baz
end
```

it says "OK, I can't see `baz` assigned to here, so `baz` is definitely a call". This, coupled with the fact that macros can't define variables in the scope that they are called, lead to an error.

We *could* make the semantic part "smarter" by first checking if it's true that `baz` is a call, checking if there's a variable. But if in my original code I had:

```crystal
def baz
  10
end

foo do
  puts baz
end
```

then when I thought `baz` would resolve to `10` now it resolves to the invisible variable declared by the macro.

This is the main reason why I believe it's dangerous or bug-prone if a macro defines inivisible variables.

Your last snippet works because the parser knows that `baz` is a variable (it's a block argument), but then that block is gone (because it was just used for the macro) and it resolves (maybe incorrectly) to the variable declared by the macro.

All of this should definitely be explained in the docs.

**Comment by jhass** [comment]
I think that it does resolve to the variable is inconsistent, it should either fully isolate or not. Also maybe checking if the block has arguments and error in that case when encountering `{{yield}}` would be good and lead to less surprises.

**Comment by miketheman** [comment]
#triage 
This seems to have stalled around discussion on which way a macro yield should work - has this been decided elsewhere?

**Comment by asterite** [comment]
@miketheman Thanks for the triage.

I'll mark this as a bug. This should work:

```cr
macro foo
  def bar(baz)
    {{yield}}
  end
end

foo do
  puts baz
end

bar("Hi")
```

It doesn't right now because for `yield` we do something special: we generate a temporary var for it, and then when parsing back the code we replace that temporary var with the yielded code. That way we preserve the original location of the expression (`puts baz` in this case), for better error messages. However, it can be done in a different way, simply using location pragmas when pasting code.

As a workaround, this works:

```cr
macro foo(&block)
  def bar(baz)
    {{block.body}}
  end
end

foo do
  puts baz
end

bar("Hi")
```

but location information for `puts baz` is lost (maybe not very important). I'll fix this (eventually).

**Comment by jhass** [comment]
I still think we should make `{{yield whatever}}` a syntax error for the time being, and perhaps even `foo do |whatever` if `foo` is a macro call.

**Comment by asterite** [comment]
@jhass I think there are two issues here, then. One is `yield` not retaining the original expression. The second one is the semantics of `yield ...`, which currently doesn't evaluate its expressions. The only place where we are using it is [here](https://github.com/crystal-lang/crystal/blob/152a1d7ffaff072ee528756a6d57da46aa30db85/src/main.cr#L12).

I'll close this and open two separate issues.

**Comment by asterite** [comment]
Split into https://github.com/crystal-lang/crystal/issues/2923 and https://github.com/crystal-lang/crystal/issues/2924

**Comment by asterite** [comment]
Both seem kind of easy to fix, I think :-)

**Comment by jhass** [comment]
Awesome, I think having these fixed will make the language a lot more powerful and consistent.
