### ISSUE TITLE
Listing all spec tags

### ISSUE THREAD

**Issue by baseballlover723** [crystal-lang/crystal#13615]
## Feature Request

I don't see an easy way to list out all of the tags that are listed in the specs besides just looking through all of the spec files themselves. It seems like it would be easy to have a `crystal spec #{path} --tags` command that would not execute the specs, but instead would tell you what tags existed there. I imagine it would be nice to know how many of each tag type there are. Getting more information like say where each instance of a tag are located seems like it could be something hidden behind a `--verbose` flag, but would require more work.

I think a good starting point would be something like
```
$ crystal spec spec/ --tags
untagged: 1000
slow: 30
flakey: 5
```

perhaps a verbose version could be like
```
$ crystal spec spec/ --tags --verbose
spec/
    test1_spec.cr
        untagged: 15
        slow: 3
    test2_spec.cr
        untagged: 30
        slow: 27
        flakey: 5
```

I think this feature would be really good for large codebases (like crystal itself), where it's really not feasible to see what tags exist and potentially you might want to exclude.

> Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.

You just look through the spec source files and notate / remember which tags are specified for each test. This isn't really feasible for large codebases.

> Does it break backward compatibility, if yes then what's the migration path?

No

**Comment by straight-shoota** [comment]
I'm taking the feedback asked on the PR (https://github.com/crystal-lang/crystal/pull/13616#issue-1783342239) here:

This belongs as a part of `crystal spec`. It's a feature of the runtime spec library. Not a compiler tool or in any way related to the compiler.

@beta-ziliani 
> Ideally, it should compile but no codegen and no run (in any form) the specs.

It's necessary to run this because tag information is only available at runtime. I suppose tags will *usually* be defined as literals which you could technically explore statically (heck you could even do that literally with some regex, not even a compiler needed).
But that's not necessarily the case. Examples and groups are explicitly runtime information.

So I think a runtime flag is the only reasonable entry point for this. I would call it `--list-tags` to avoid confusion bewteen `--tag` and `--tags`.

**Comment by Blacksmoke16** [comment]
Would this be a good use case for #13509 given specs run in an `at_exit` handler, so could use `exit!` to collect them, but never actually run them?

**Comment by beta-ziliani** [comment]
> It's necessary to run this because tag information is only available at runtime.

That's also in my comment, so we're good here. I just mentioned what should be the ideal situation.

**Comment by baseballlover723** [comment]
updated my PR to be ready for review. I'm not gonna do any of the `--verbose` stuff right now, since it seems like a bit too much work then I want at the current moment.

**Comment by straight-shoota** [comment]
I'm wondering about separate tallies for pending vs. non-pending examples. Not sure if there are good use cases for that. IMO the separate tables produce bigger output which makes it harder to process and IMO it doesn't provide much extra information typically.

With respect to https://github.com/crystal-lang/crystal/issues/13747#issuecomment-1721579334 I'm wondering if separating pending examples makes sense at all because you cannot really determine which ones are pending without actually running the examples.

I doubt many pending specs are actually tagged in practice, so maybe this discussion is a bit mute. But if we could agree on that, I'd prefer to keep the code simpler and not count pending examples separately...

**Comment by baseballlover723** [comment]
I agree that there isn't any significant tagging for pending examples. If we can't easily and reliably detect pending examples without actually running the examples, then I'm all for simplifying the code and not distincting between them. I've updated the PR to reflect this change.
