### ISSUE TITLE
not nil is inconsistent?

### ISSUE THREAD

**Issue by Silentdoer** [crystal-lang/crystal#13677]
## Bug Report

```crystal
if a = @a
  # here `a` can't be nil
end

should be:(like dart)
if a  =  @a!

because it not consistent with:
a  = @a
In this case a can still be nil
```

- Make sure a similar issue does not exist yet: use the search box, search engine and look at [Stack Overflow](https://stackoverflow.com/questions/tagged/crystal-lang).
- **Include reproducible code**: we should be able to paste it into an editor, compile and run it and get the same error as you. Otherwise it's impossible for us to reproduce the bug.
- Don't **only** use `play.crystal-lang.org` or `carc.in`: code might be lost and the issue will remain incomplete. Write code in the issue itself.
- Reduce code, if possible, to the minimum size that reproduces the bug.
- If all of the above is impossible due to a large project, create a branch that reproduces the bug and point us to it.
- Include Crystal compiler version (`crystal -v`) and OS. If possible, try to see if the bug still reproduces on master.

**Comment by devnote-dev** [comment]
So your proposal is the addition of `!` in the if condition? If so, this wouldn't be compatible with the language or at the very least would produce some very confusing syntax, such as the following:

```crystal
def something! : Int32?
end

if a = random!!
  # less readable here, why are there two exclamations?
end
```

Your argument for not being consistent with `a = @a` also doesn't make much sense because that is just passing a reference of `@a` to `a`, there is no `nil` checking being performed here unlike in the if statement.

**Comment by straight-shoota** [comment]
I can see no inconsistency. The type restriction inside the `if` branch comes from the `if` condition.
A singleton assignment without a conditional has no such circumstances, thus it's not comparable.
Adding a trailing exclamation mark would be semantically unnecessary clutter.
