### ISSUE TITLE
case when if expression use ==  not  ===

### ISSUE THREAD

**Issue by Silentdoer** [crystal-lang/crystal#13679]
## Bug Report

why case when use ===, it is redundant?

- Make sure a similar issue does not exist yet: use the search box, search engine and look at [Stack Overflow](https://stackoverflow.com/questions/tagged/crystal-lang).
- **Include reproducible code**: we should be able to paste it into an editor, compile and run it and get the same error as you. Otherwise it's impossible for us to reproduce the bug.
- Don't **only** use `play.crystal-lang.org` or `carc.in`: code might be lost and the issue will remain incomplete. Write code in the issue itself.
- Reduce code, if possible, to the minimum size that reproduces the bug.
- If all of the above is impossible due to a large project, create a branch that reproduces the bug and point us to it.
- Include Crystal compiler version (`crystal -v`) and OS. If possible, try to see if the bug still reproduces on master.

**Comment by beta-ziliani** [comment]
Hi @Silentdoer , I understand that a new language has different ways of expressing different patterns. Instead of consider such new finding "a bug", I encourage you to ask in the [forum](forum.crystal-lang.org) and, of course, to [read the documentation](https://crystal-lang.org/reference/1.9/syntax_and_semantics/case.html) (a search of `===` would have solved your question).

I will close this one, since there's nothing to be done.
