### ISSUE TITLE
Signals delivery fails constantly

### ISSUE THREAD

**Issue by MistressRemilia** [crystal-lang/crystal#13698]
This only seems to happen with `-Dpreview_mt`.  Assume `CRYSTAL_WORKERS` is set to 20 like it is on my machine (I have 20 logical cores).  This program will cause a "Signals delivery fails constantly" error message and the program will just exit.

```crystal
doneChan = Channel(Int32).new(5)

21.times do |_|
  spawn do
    prog = Process.new("ls", ["-l"], output: Process::Redirect::Pipe)
    doneChan.send(prog.output.gets_to_end.size)
    prog.wait
  end
end

21.times do |_|
  puts doneChan.receive
end
```

Output when doing `crystal run -Dpreview_mt test.cr`:

```
Signals delivery fails constantly at GC #2
Signals delivery fails constantly
Program received and didn't handle signal ABRT (6)
```

This behavior seems to change depending on the value of `CRYSTAL_WORKERS` and the number of fibers that get spawned as well.  If I reduce `CRYSTAL_WORKERS` to 4, it works with 21 fibers.  But if I then increase the fibers to something like 225, it starts happening again.  Adding some `Fiber.yield` calls doesn't seem to do anything.

I discovered this when launching some `bzip2` calls that would write to stdout, then capturing the bytes from stdout.

Tested with Crystal 1.9.2 and 1.8.2 on Slackware Linux 15.0

```
Crystal 1.8.2 [7aa5cdd86] (2023-05-09)

LLVM: 13.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by straight-shoota** [comment]
I can reproduce this error. Not with 21/20 or 225/4, but with 225/20 on my machine with 16 logical cores.

**Comment by ysbaddaden** [comment]
The failure to send the stop signal is actually a failure to receive the signal because we disable the reception of signals on the current thread before forking, so that signals sent to the forked process won't be inadvertently received by the parent process (through the signal pipe). Both the parent and child processes should quickly reset the sigmask after `fork`.

What seems to happen is that the parallel `fork` calls enter into a deadlock (threads are waiting on a mutex).

I tried disabling the `pthread_sigmask` and that fixes the issue. Now, how to fix both issues :thinking:

Maybe we should never block the GC suspend and restore signals (accessible through `GC_sig_suspend` and `GC_sig_thr_restart`).

**Comment by ysbaddaden** [comment]
I wonder what's causing the `fork` deadlock in the first place. None of the backtraces from all the threads, especially the suspended ones, seem to hold anything related to `fork`. Maybe this is something related. The blocked `fork` calls are waiting on a futex related to allocations... maybe a suspended is doing something related to malloc or something?
