### ISSUE TITLE
UTF-8 letters replaced with null bytes if provided via Windows Terminal

### ISSUE THREAD

**Issue by KamilZielinski** [crystal-lang/crystal#13731]
I have an issue where running such code on Windows results in letters replaced with null bytes. Then it keeps failing in places like `Path.windows()` where are checks for null bytes - that's how I noticed it.
The issue appears only when running the script/.exe file from the terminal, both cmd and PowerShell.

## Crystal
Code `main.cr`:
```crystal
puts "Give me your name"
input = gets
value = input.not_nil!
puts value.inspect
puts value
```

While on Linux it worked perfectly
**Linux (WSL):**
```bash
$ crystal run main.cr
# => Give me your name
zażółć gęślą jaźń
# => "zażółć gęślą jaźń"
# => zażółć gęślą jaźń
```

Reading the value from terminal on Windows replaces some letters with null bytes
**Windows 11**
```bash
$ crystal run main.cr
# => Give me your name
zażółć gęślą jaźń
# => "za\u0000\u0000\u0000\u0000 g\u0000\u0000l\u0000 ja\u0000\u0000"
# => za gl ja
```

**Windows Crystal Version:**
```bash
$ crystal -v
# =>  Crystal 1.9.2 [1908c81] (2023-07-19)
# =>  
# =>  LLVM: 16.0.3
# =>  Default target: x86_64-pc-windows-msvc
```
---
Based on the [documentation](https://crystal-lang.org/api/master/IO.html#encoding), the default encoding should be set to UTF-8 and all the mentioned letters are valid UTF-8 letters.
```
If an encoding is not set, the default one is UTF-8.
```

When value is placed direcltly in the code like so:
```crystal
value = "zażółć gęślą jaźń"
puts value.inspect
puts value
```

**Windows 11:**
Then there are no issues with printing values:
```bash
$ crystal run main.cr
# => "zażółć gęślą jaźń"
# => zażółć gęślą jaźń
```

---
## Ruby
```ruby
puts "Give me your name"
input = gets
value = input.chomp
puts value.inspect
puts value
```

**Windows 11:**
```bash
$ ruby main.rb
# => Give me your name
zażółć gęślą jaźń
# => "zażółć gęślą jaźń"
# => zażółć gęślą jaźń
```

**Comment by erdian718** [comment]
We may refer to the solution in golang:
#https://github.com/golang/go/issues/4760
#https://github.com/golang/go/commit/26498684cb71de328b28974b87df3d5ab9486e4c

**Comment by doongjohn** [comment]
`read_line` is not that complicated:
```crystal
require "winerror.cr"

lib LibC
  fun ReadConsoleW(hConsoleInput : HANDLE, lpBuffer : Void*, nNumberOfCharsToRead : DWORD, lpNumberOfCharsRead : DWORD*, pInputControl : Void*) : BOOL
end

def windows_console_read_line()
  buffer = uninitialized UInt16[32768]
  read_size : UInt32 = 0
  if LibC.ReadConsoleW(Crystal::System::FileDescriptor.windows_handle!(0), buffer, buffer.size, pointerof(read_size), nil)
    return String.from_utf16(buffer.to_slice[0, read_size]).strip # strip "\r\n"
  end
  raise WinError.value.formatted_message
end

p! windows_console_read_line() # it can handle unicode input
```
but for the custom delimiter it may be more complicated: https://stackoverflow.com/a/70124526

**Comment by straight-shoota** [comment]
We're explicitly setting the console code page to UTF-8:

https://github.com/crystal-lang/crystal/blob/9390ee503b290e79c0dd886642cd1ea033d52b2e/src/crystal/system/win32/file_descriptor.cr#L279-L290

Apparently, that does not seem to work as one would expect?

**Comment by erdian718** [comment]
> #13750 should fix this.
> 
> I'm still unsure about the console codepage setting ([#13731 (comment)](https://github.com/crystal-lang/crystal/issues/13731#issuecomment-1680409376)). Is it really useful/necessary?

Hi, core team!

I'm a Windows user, and non-English user.
I've been following this issue, and I also found that there are already some solutions here( #11527). @HertzDevil 
ReadConsoleW / WriteConsoleW is a better solution, and I see @straight-shoota  have created a PR. But there are some problems with this PR:

1. Incomplete characters in the buffer are not taken into account.
2. EOF is not taken into account.
3. Each time unbuffered_read is called, memory is allocated to the u16buffer.

This issue is a little more complicated than it seems. I think I can solve it better, but I need a few days to get used to Crystal.
If there is no hurry to fix this issue，can you give me a chance to contribute?

**Comment by straight-shoota** [comment]
Sure, please give it a go 👍 Let me know if you need any help!

**Comment by erdian718** [comment]
> Sure, please give it a go 👍 Let me know if you need any help!
> 
> My implementation is only minimal to solve the primary problem. Of course it can be improved.
> 
> I suppose a potential optimization could be to use a `StaticArray` as u16 buffer and iterate multiple times if it does not fill the u8 slice at once.

Thank you, I need a few days (possibly more) to implement it because I am new to Crystal.

**Comment by erdian718** [comment]
I've created a PR #13758

**Comment by straight-shoota** [comment]
Thanks for the PR! I understand it's a lot of work doing that while still getting aquainted with the language. But I'm sure it also helps moving that forward =)

I would like to discuss some general design issues.

1. This is very complex code that needs to deal with a lot of edge cases. We need a way to write extensive tests. I'm not sure if we can sufficiently setup a console handle for testing, but I suppose we might use `AllocConsole` and then test read/write operations on that.
2. Can the value of `GetConsoleMode` change for a given file descriptor? If not, we should probably store the result instead of querying it on every operation.
3. I'd like to avoid buffering data in the file descriptor object. Typically, there's already a buffer in `IO::Buffered` and layering buffers doesn't do any good here. It's important to note that the slice that's being read into does not need to be filled to the brim. We can read from the console with sufficient margin to not overfill the slice. I believe UTF-8 encoding needs at most 50% more bytes than UTF-16 in case all codepoints are between U+0800 and U+FFFF (UTF-8 requires 8 bytes and UTF-16 only 2). In all other code ranges, UTF-8 is either smaller or equal in size.
We might not be able to avoid storing residual bytes, though. But that would be just 3 bytes max.
4. The documentation mentions that setting the console's code page may still be necessary to prevent other system config to produce garbage. But I'm not sure I understand it correctly.
5. A potential performance enhancement in the future (should not be part of the base PR!) could be to optimize for the common use case of `IO#gets` which looks for a delimiter (usually `\n`). I suppose we could provide a special implementation for that method using `ReadConsoleW` with `pInputControl` parameter which serves exactly the same purpose.

**Comment by erdian718** [comment]
Thank you for your reply.
Yes, the code is complex, and I tried to explain the design idea:

1. I agree with you that this code is not easy to test. I only tested some cases by hand.
2. The value of `GetConsoleMode` may change, as mentioned in the documentation: [windows/console/readconsole](https://learn.microsoft.com/en-us/windows/console/readconsole).
3. I know that the maximum number of UTF-16 code units that need to be read is no more than the number of bytes that need to be read, and I use this feature in my code. I used two buffers: 'console_bytes_buffer' and 'console_units_buffer'. Buffers are used for two reasons, one is to properly handle the residual UTF-16 code units and the residual UTF-8 bytes (For example, the character to be read has 4 bytes, but we only read 1 byte with 3 bytes remaining), and the other is to avoid allocating memory again and again.
4. I tested on the non UTF-8 code page, both Windows terminal and conhost, and it worked fine.
5. This code is already very complex, and I think it's best not to optimize it too early unless we really hit a performance bottleneck.

**Comment by straight-shoota** [comment]
1. It seems impossible to get *actual* consoles for testing purposes from the Win32 API as there is ever maximal one console per process.
  However, I figure we could mock the behaviour by subtyping `IO::FileDescriptor` with a stubbed implementation of the API methods. I've implemented a demonstration for `read_console` in this branch: https://github.com/straight-shoota/crystal/tree/test/windows-console-utf8-spec Do you think that's adequate for testing?
2. Right. If a descriptor gets redirected, it might not be a console anymore.
3. I don't think a persistent buffer for wide chars (UTF-16) should be necessary. `IO::Buffered` takes care of generic read buffering. We just need to read UTF-16 data from the console and put it into the buffer transcoded to UTF-8. If we never request more characters than can be put in the UTF-8 buffer, there's no need for persistence. So the only use case would be avoiding local allocations for performance reasons. I think it's best to disregard this for now and just focus on a simple implementation that is minimally invasive (i.e. does not add a bunch of instance variables to `IO::FileDescriptor`) and correct. We can optimize late and there are several options to explore.

**Comment by erdian718** [comment]
It's a pleasure to communicate with you @straight-shoota 

> The only limitation is that it does not work well with miniscule buffer sizes, but that's not required because IO::Buffered always allocates a sufficiently siced buffer.

That's exactly what I care about. I'm not good at using English, so let's get straight to the code:

Example 1: Miniscule small buffer sizes are possible, and we cannot ignore this situation, and there will be residual UTF-8 bytes!
```
STDIN.read_buffering = false
slice = Bytes.new(1)
STDIN.read(slice)
```

Example 2: We cannot guarantee that the last code unit of the UTF-16 sequence read by `ReadConsoleW` is a complete character:
```
STDIN.read_buffering = false
slice = Bytes.new(3)
STDIN.read(slice)

# Then type "𐩯" in the console. NOTE: character '𐩯' has 4 UTF-8 bytes and 2 UTF-16 code units.
```

Example 3: This situation is not particularly important and can be achieved in other ways:
```
gets
gets

# Then type "A^ZB", `^Z` is `Ctrl-Z`, which stands for EOF.
```

My code is complicated because it takes into account several of the above scenarios.

Your idea of "re-using the buffer for reading UTF-16" is fantastic! We really don't need to `console_units` this way.
But I think it's indispensable to deal with the residual UTF-8 bytes and the residual UTF-16 code unit.

**Comment by straight-shoota** [comment]
> Example 1: Miniscule small buffer sizes are possible, and we cannot ignore this situation, and there will be residual UTF-8 bytes!

I'd argue that this use case might not be relevant enough that we should care about it. IMO `IO::Buffered` is intended to provide large buffer sizes and deviating from that can have defective effects.
Of course, this is up for debate. I'm happy to consider practical applications for that.


> Example 2: We cannot guarantee that the last code unit of the UTF-16 sequence read by ReadConsoleW is a complete character:

I suppose this would happen when the buffer is filled fully and the end of the buffer is exactly inside a surrogate pair.
My solution for dealing with that would be to request one less UTF-16 unit from `ReadConsoleW` and do a second read of one unit in case the last unit is a surrogate.

> `String.each_utf16_char` is currently private, and making it public requires careful consideration

I'm not making it part of the public API, see the `:nodoc:` addition. It only becomes callable from outside its scope. That's completely legitimate and applied in many similar situations. Don't worry about this.

**Comment by erdian718** [comment]
I agree with you that we should not over-engineer for the sake of situations that theoretically exist but do not actually exist.
I reimplemented a version based on your suggestion. @straight-shoota

**Comment by HertzDevil** [comment]
Regressions are regressions, the examples with read buffering disabled should not break. It should suffice to use a local `StaticArray` for very small output slices without introducing a lot of code changes

**Comment by straight-shoota** [comment]
I suppose we could introduce a special case handling for `buffer.size < 6` (I think that's the lower limit of the current implementation). It should be as simple as using a small static array for the units buffer if the buffer size is too small.

> Moreover I am not sure if `IO::Buffered#read` is allowed to touch the parts of the output slice that do not correspond to the bytes successfully read. If `STDIN` can assume those bytes aren't used by the caller, the caller can also assume stdlib doesn't use those bytes on equal grounds.

I would not worry about that. IMO a buffer supplied to a method can be used to the full extend of its capacity for whatever utility purpose. Regardless of how much filled space is reported as a result. This is very pracitcal and can be clearly documented.

Furthermore, I don't see much practical use for assuming that buffer space beyond the number of read bytes is untouched. What kind of purpose would that enable?
I wouldn't even be sure if the invariant isn't broken in existing implementations already.

**Comment by erdian718** [comment]
> It should suffice to use a local `StaticArray` for very small output slices without introducing a lot of code changes.

I'm not sure I didn't understand some information.

PR #13758 has been trying to properly handle the 2 problems:
1. There is no guarantee that the data read by the `ReadConsole` is full Unicode characters.
2. There is no guarantee that the data fill into the `slice` is full UTF-8 bytes.

What is now certain is that the first problem can be solved with two reads. And there has been no perfect solution to the second problem:

* The initial approach handled both problems correctly, but increased the size of the file descriptor.
* In the ensuing discussion, I proposed a way to improve, but it was rejected.
* The current code is relatively simple and can handle the general case, but it cannot handle the case where the `slice` is too small.

I haven't figured out how to solve the second problem with just a local `StaticArray`.

**Comment by erdian718** [comment]
> Moreover I am not sure if `IO::Buffered#read` is allowed to touch the parts of the output slice that do not correspond to the bytes successfully read. If `STDIN` can assume those bytes aren't used by the caller, the caller can also assume stdlib doesn't use those bytes on equal grounds.

In other programming languages, similar approaches are also used (such as golang).

Usually, this is not a problem. One problem that comes to my mind is that the caller assumes that the remaining part of the `slice` are the initial values (such as zero values), but this approach breaks this assumption.

We need to make a reminder in the document, for example, the following reminder comes from golang standard library document:

> Even if Read returns n < len(p), it may use all of p as scratch space during the call.

**Comment by straight-shoota** [comment]
> > It should suffice to use a local `StaticArray` for very small output slices without introducing a lot of code changes.
> 
> I'm not sure I didn't understand some information.

It's not about edge cases in the data, but the size of the provided buffer. My comment refers to the first paragraph of https://github.com/crystal-lang/crystal/issues/13731#issuecomment-1745613302, which goes along with the example in https://github.com/crystal-lang/crystal/pull/13758#discussion_r1344633947.
A buffer size of 4 is enough to hold any single UTF-8 codepoint, so it should technically work. But the current implementation raises on `third < 2`, which implies `buffer.size < 6`.
It should be totally fine to handle this tiny buffer as an edge case.
The proposed solution is to use a `StaticArray(UInt16, 2)` as units buffer if `buffer.size < 6`.

**Comment by erdian718** [comment]
There are still two points that we have not reached an agreement on:

1. For `units_Buffer`, whether to use the remaining of `slice` or a local `StaticArray`. I tend to use one of the methods instead of mixing the two. If using `StaticArray`, what is the appropriate size? 64 or 128?
2. How to handle the second problem? We have already attempted to solve it (the initial solution) and have also attempted to ignore it (the current solution). How can we balance simplicity and completeness?

**Comment by straight-shoota** [comment]
> 1. For `units_buffer`, whether to use the remaining of `slice` or a local `StaticArray`. I tend to use one of the methods instead of mixing the two. If using `StaticArray`, what is the appropriate size? 64 or 128?

If we agree that mutating the buffer beyond the returned data is acceptable (@HertzDevil WDYT?), we should use `slice` as `units_buffer`. Only if `slice` is very small, we must use a static array. There is no problem with mixing both approaches.

> 2. There is no guarantee that the data fill into the slice is full UTF-8 bytes.

I don't think there needs to be a strong guarantee for that. With a couple of constraints in place, this edge case should be pretty negligible. For example, the slice should always be large enough to hold a full UTF-8 codepoint. If `slice.size < 4`, undefined behaviour should be acceptable.

**Comment by HertzDevil** [comment]
```crystal
STDIN.read_buffering = false
STDIN.read_byte
```

relies on reading into a 1-byte `Slice`, so it must not be undefined behavior.

**Comment by straight-shoota** [comment]
Are we talking about an actual use case or just a theoretical scenario? What's the point in disabling read buffering and reading individual bytes? I don't see a practical use case for that.
We should be careful about complicating the implementation for hypothetical edge cases.

**Comment by HertzDevil** [comment]
We are talking about never introducing any regressions, however minor. So if the internal decoder cannot be implemented without buffering, then maybe the original idea of having a separate read buffer isn't that bad after all.

**Comment by straight-shoota** [comment]
> maybe the original idea of having a separate read buffer isn't that bad after all.

The most minimal step for implementing the edge case of reading slices that are smaller than a UTF-8 codepoint is a small buffer for holding at most 3 residual bytes.

**Comment by erdian718** [comment]
I have implemented two versions, one that completely handles edge case correctly, and the other that ignores edge case. But we have never reached a consensus on how to handle edge case.

I am personally a pragmatist who values simplicity over completeness. So I agree with the current implementation.
Of course, I don't object to correctly handling edge case either. I just need to revert to the original code of this PR and make some small improvements to avoid increasing the size of the file descriptor.

> The most minimal step for implementing the edge case of reading slices that are smaller than a UTF-8 codepoint is a small buffer for holding at most 3 residual bytes.

It is too early to discuss this detail now, as we have not yet reached an agreement on edge case handling. Ultimately, whether to use a 3 bytes buffer or an appropriately sized buffer depends on simplicity and performance.

**Comment by erdian718** [comment]
> maybe the original idea of having a separate read buffer isn't that bad after all.

Do you agree to use a separate read buffer while keeping the code simple? @straight-shoota 
The initial code was indeed a bit complex, but we can use the discussion results of this period to simplify it.

**Comment by straight-shoota** [comment]
Yeah, I suppose we can do that. Let's get it working in a state that we all agree is sane. We can always optimize the implementation later on.

I think we only need an ivar holding a utf-8 buffer in `IO::FileDescriptor`. By default, this would be empty. It allocates when `read_console` is called.

**Comment by erdian718** [comment]
I have refactored the code, and the current code can handle edge case correctly without adding much complexity. @straight-shoota @HertzDevil 

1. By using the class variables, the problem of increasing the size of file descriptors is avoided.
2. Not using the remaining portion of `slice`, because there are still different opinions on this approach.
3. Did not use `StaticArray` or 3-bytes buffer, but instead used a regular sized buffer because it was simpler.
4. No lazy allocating memory because the buffer is very small and only allocated once during program startup.
