### ISSUE TITLE
[RFC] unassignable value for return statements

### ISSUE THREAD

**Issue by technorama** [crystal-lang/crystal#1393]
Many methods perform an action without returning a useful value.  There is no standard for what to return.  Some methods return nil, true, false, 0, or implicitly return the value(s) of other methods.  Sometimes this leads to leaking internal state (Scheduler.enqueue).

The behavior can lead to bugs depending on what the method returns.
```
if no_useful_return()
  # runs if true or 0 is returned
  # also runs if accidental objects are returned (like Scheduler.enqueue and many other methods)
else
  # runs if false or nil is returned
end
```

I propose making a guard return value possibly named Void that can reduce program errors.

Requirements:
* Void may not be assigned as a variable
* Void may not be stored in a collection
* Void may not be used in a union type
* Void may not be compared
* Void may not be used in if/case statements

Test cases follow:
```
def foo : Void
  # implicit return is now Void
end

def bar
  Void
end

# no union's with Void
def baz 
  if condition
    true
  else
    Void
 end
end

a = foo # compile time error
b = bar # compile time error
c = baz # compile time error
```

Void is a suggested name.  If Void is in use or has other semantics another name can be chosen (undefined?).

**Comment by jhass** [comment]
Every expression should have a value, I should be able to assign it, call methods on it and pass it to other methods and use it in contexts where truthiness is evaluated.

We should rather make an effort to return nil instead if of leaking internals.

**Comment by technorama** [comment]
Not every methods returns a **useful** value.  If a method returns something not useful the compiler should show an error if used.  

Currently any conditional statement used with an unspecified [nil, true, false, 0] or possibly leaked value leads to undefined behavior.

Also, the internals of libraries may change between versions leaking new values that change conditional branches.  (New bugs with upgrades)

What use case is there for unspecified values being stored, passed to other methods, or used in branching?

**Comment by jhass** [comment]
I'm not saying we should leak internals, rather make sure to return nil in these cases. However that every expression does have a value is a useful language semantic that makes working with it easier IMO.

**Comment by technorama** [comment]
I feel like this is another case of cargo cult programming.  We're doing it this way because ruby (and others) did it.

Process.fork returns a pid or nil.  That's useful.
Process.kill return 0.  Always.  What can you do with that?   How is it useful?
File#close returns an empty array.  You could change that to return nil but what are you going to do with it?

You would never use nil returns in conditionals or store them in variables.  The language may let you but doing so is almost certainly an error.  Why does the compiler allow something that is not useful and probably an error?  What's the point?

**Comment by jhass** [comment]
Why shouldn't I return something I can inspect? "Oh I wonder what this expression returns, `pp whatever`". Why is something you can't inspect (`void`) better than something you can inspect (`nil`)? You have to make sure to declare/return it in either case, the overhead in stdlib is the same.

Besides maybe we should seek to return more useful values, having to return something could spawn incentive to return something useful.

**Comment by technorama** [comment]
I am suggesting that something is returned with specific semantics which is *Void*.  0, false, nil, true, don't have the desired semantics.

Storing a useless result in a collection or variable is still a bug.  That's what I want to catch when compiling rather than during runtime or after upgrading a library or crystal version.

Inspection is the only valid point I see.  Perhaps `pp foo()` should work.  

You have to return something useful before it can be used.  Many methods return useless values (nil) currently.

**Comment by technorama** [comment]
Let's take an example where one's assumptions lead to bugs when upgrading.

```
  if Scheduler.enqueue(fiber)
   # If the Scheduler let's me queue a fiber I should be able to do something, right? 
    do_something
  end
```

The scheduler is currently leaking internal state and always returns a truthy value.  If the return is changed to nil the program won't run the method(s) inside the if block.  That may mean incorrect results silent failure, missing data structures that cause failures later, or worse of all silent failures.

Changing a return from (random object) to nil is not currently safe.  Changing it to Void would flag all incorrect uses of the method at compile time.

**Comment by asterite** [comment]
I also had the idea of marking methods as returning `Void` and disallowing using their value.

The main issue is that it's a different beast compared to every other type in the language. Imagine this method:

```crystal
def log_result(operation)
  result = operation.run
  Logger.log "Result of #{operation} is: #{result}"
  result
end
```

If one of my operations returns void, that code won't compile anymore, because `Void` can't be used for anything (it doesn't have any methods). So I'd probably have to go and change the `log_result` method to consider the case of void. But maybe returning `nil` wasn't so bad in this case, and `nil` already means "lacks a value".

The example of `Schedule.enqueue`, i'm not sure. Methods usually say what they return. If they don't say it, you shouldn't use the return value. Even if we had this `Void` return type, people will forget or just not care to use it, and you'll still be able to use it in conditions.

**Comment by technorama** [comment]
Maybe we can reduce the scope of Void errors while still catching common errors.  

Requirements:
* Void may not be used in if/case statements
* Void may not be stored in a collection
* Void may not be compared???

The above requirements would allow mixed return logging and inspection while catching bugs involving conditionals.

Re other libraries.  We can never control what external sources return or how they are designed.  We can only set examples and policy within the crystal project itself.  Methods like Process.kill and most other wrapped system calls can return Void instead of their current random assortment of return values.

Some libraries will start to use Void if available.  Especially the well maintained ones.

**Comment by technorama** [comment]
Perhaps we can relax the requirements of Void to allow logging and inspection while still catching common errors (especially when libraries change API's).

Requirements:
* Void may not be used in if/case statements
* Void may not be stored in a collection
* Void may not be compared???
* Void methods error with explicit return of objects
* Void methods change all implicit returns to Void.

Process.kill and most wrapped system calls can safely return Void instead of the current random assortment of return values.  This would ensure type safety within crystal itself.  Others using the language would see the documentation or examples provided and start using Void returns when appropriate.  It's a common concept familiar to anyone from a C family language.

We can't control the design of external libraries, only set examples within the documentation and crystal itself.

Many projects would use Void if available, especially the well maintained ones.

**Comment by waj** [comment]
I also think we should be more careful with the values returned from methods in the standard library. Specially when they return internal implementation stuff, because even when not documented someone might start relying on the return value.

We discussed this topic many times internally. I'm also concerned about unnecessary code generated when calling methods with useless return values. Specially if they are called from different branches of an "if" statement, it will generate temporary union types. These, as not used, will be probably discarded by LLVM optimization passes, but it's more work for the codegen phase that just takes time.

The `Void` type already exists, although it doesn't have the restriction of being assigned. @technorama, your requirement list might be mapped to a more abstract design, if we disallow assignments, and passing void values as arguments to other methods.

Doig so would of course raise the issues that @asterite just explained, but given that the problem seems to materialize in metaprogramming scenarios, maybe it wouldn't hurt to take that special case into account, and have the benefit of compile errors anywhere else.

BTW, I also agree with @jhass, that every expression must have a value. So to make a method Void I'd just mark the return type as such, no need to introduce new kewords or special values, but the return value won't be able to be used anywhere.

**Comment by jhass** [comment]
Well, if I can't use the value of an expression that amounts to the same as not having a value as far as I'm concerned.

**Comment by waj** [comment]
That it's true, but I was more like thinking that we don't need to explicitly note `Void` in the body of a method, but just mark the method as `Void` and the compiler wouldn't even use the type of the body expression.

I'm still not convinced about this whole idea, but let me think out loud about the semantics that it would have.

Formally speaking, the `Void` type has a value: the void value. One can think that makes it very similar to the `Nil` type (a unit type), but the difference is that the compiler doesn't allow that type in some contexts with the only goal of helping with potential bugs, when a value from a method is used and it shouldn't. (`NoReturn` should also follow the same semantics?)

Analyzing the problem more deeply, we'd need to define what's the union type of `Void` with other types (T). If the `Void` type cannot be used, `Void | T` type is pointless. It can't be `T` because we still need to define a value for when it's not `T`. So it has to be either a compiler error or `Void`. A compile error doesn't sound just right to me, because it would force to introduce some artifacts in the code just to make the compiler happy. Finally, making `Void | T = T` actually doesn't sound that bad.

**Comment by strcmp** [comment]
I'm sure functional programmers would just **love** this one :stuck_out_tongue: If I understood this correctly, this is for methods are exist purely for side effects. I don't know how this is useful, to be honest.

**Comment by asterite** [comment]
I'm starting to like the idea of Void, if it will disallow leaking information, clearly documenting that the return value is useless, and speeding up the codegen.

However, what's the type of the following `if`?

```crystal
if some_condition
  method_that_returns_void
else
  1
end
```

It **has** to have a type. Imagine this is the only expression in a `def`.

I thought about this, and maybe `Void` should consume every other type it's joined with. Just like `NoReturn | Anything` gives `Anything`, I think `Void | Anything` should give `Void`, because there will be some case where you can't use that value.

Going back to my example:

```crystal
def log_result(operation)
  result = operation.run
  if result.is_a?(Void)
    Logger.log "Result of #{operation} is void"
  else
    Logger.log "Result of #{operation} is: #{result}"
  result
end
```

If we disallow assigning void, then the above won't compile (`can't assign void to result`). In fact, I can't see a way of writing the above method.

So... maybe void should be allowed to be assigned, but not passed to methods? This needs more thought.

**Comment by waj** [comment]
Errata: in my last sentence I meant `Void | T = Void`

**Comment by bcardiff** [comment]
I like the idea of declaring the void return type to swallow a default return value.

I agree that `Void | T = Void`. As `NoReturn | T = T` seems neat to have that behavior with a type. Even `Void | NoReturn = Void` works so it has to make sense :-)

But, I don't see there is much gain adding more things. Like preventing them to be used in assignments, arguments, etc. 

For sure the compiler could use that the only Void is void and avoid storing some intermediates results as pointed bye @waj at https://github.com/manastech/crystal/issues/1393#issuecomment-138301559

So Void might be similar to Nil, but the behavior in the union make a whole deal and the compiler may optimize things a bit further. I would vote for adding just that, at least initially.

**Comment by asterite** [comment]
@waj @bcardiff Note that intermediate results are already optimized away in the codegen if their value is not used.

For example, for this code:

```crystal
def union_method
  1 || 'a'
end

def foo
  a = 1
  union_method
  2
end

foo
```

We get:

```llvm
define internal i32 @"*foo:Int32"() {
alloca:
  %a = alloca i32
  br label %entry

entry:                                            ; preds = %alloca
  store i32 1, i32* %a
  %0 = call %"(Int32 | Char)" @"*union_method:(Int32 | Char)"()
  ret i32 2
}
```

However, if the last expression in foo is the call that returns the union, we get:

```llvm 
define internal %"(Int32 | Char)" @"*foo:(Int32 | Char)"() {
alloca:
  %a = alloca i32
  %0 = alloca %"(Int32 | Char)"
  br label %entry

entry:                                            ; preds = %alloca
  store i32 1, i32* %a
  %1 = call %"(Int32 | Char)" @"*union_method:(Int32 | Char)"()
  store %"(Int32 | Char)" %1, %"(Int32 | Char)"* %0
  %2 = load %"(Int32 | Char)"* %0
  ret %"(Int32 | Char)" %2
}
```

**Comment by technorama** [comment]
@asterite One class of error I'm trying to prevent is the use in if statements.  Not all if statements but specifically `if obj` statements.

```
if log_result # compiler error
  ...
end

def log_result(operation)
  result = operation.run # Void | Any
  ...
  result
end
```

Testing for is_a?(Void) should be ok.  The programmer has chosen to test for it.  `if obj` allows implicitly accepting values like [nil, false, 0, true, internally leaked objects] and making decisions on them which should be considered a bug/error.

This example is fine if we allow store, printing & inspection.
```
def log_result(operation)
  result = operation.run
  if result.is_a?(Void)
    Logger.log "Result of #{operation} is void"
  else
    Logger.log "Result of #{operation} is: #{result}"
  result
end
```

**Comment by ysbaddaden** [comment]
I dont see any difference with `if result.is_a?(Nil)` then.

Either Void creates a real concept, breaking the everything is an expression concept (not cool), or it's a void concept (pun intended) for the developer that somehow duplicates nil (ie. no data).

I'm more in favor of returning actual data (avoiding nilables and union types) or to always return nil to avoid leakages.

**Comment by asterite** [comment]
I'm hesitating between adding this `Void` feature, or removing `Void` altogether (even from lib functions, and having to use `Pointer(UInt8)` instead of `Pointer(Void)`). Right now `nil` has no representation so it's pretty similar to void. And for what @technorama wants you can simply put a last `nil` expression in your method and that's it, maybe together with a ` : Nil` return type annotation. You can't possibly use `nil` for something meaningful.

In fact, removing `Void` might simplify the language and the compiler, because right now void arguments can be passed, but they are codegened as `i8` because llvm doesn't allow `void` arguments. So that's one more check the compiler has to do. And people have to learn about this special `Void` type and its special rules.

**Comment by bcardiff** [comment]
But then you will have a special case that `def foo : Nil` will swallow return statements values, but any other `def foo : T` will perform a type checking you are returning the expected type. I would prefer more drastic separation of types.

But, if we end up using only Nil, on the LibC you can have a Void alias ;-)

(As a side note, since the compiler already do some optimization, can't we just use a macro to ensure no value is returned?  `void def; S;end` ~> wrap S and return nil.)

**Comment by technorama** [comment]
@asterite nil and Void are not the same.  I'm not asking for that.  Returning nil does NOT solve the problem.  See below.
@ysbaddaden There is a difference between an explicit type check and checking truthiness in normal if/unless statements.

```
a = nil;
if a # ok
if a == "something" # ok

a = Void
if a # ERROR
if a == "something" # ERROR
```

I gave examples previously (please see BOTH of my posts containing Scheduler.enqueue) where erroneous returns that are relied upon will **silently** change behavior and possibly break in a variety of hard to debug ways if the return is changed to nil.  Just use nil is not a solution to the problem of incorrectly using returns statements that have no valid return value useful in a conditional or otherwise (except possibly inspection of union results or debugging usage).

**Comment by asterite** [comment]
@bcardiff's: if you mark a method as `: Nil`, you have to return an explicit `nil`. The compiler won't automagically do that for you.

@technorama I have to disagree. `Scheduler.enqueue` is not documented. And if it were documented, it would say "Enqueues a fiber..." or something like that. It wouldn't say anything about what the method returns (in fact, I don't think it will be documented at all, it's an internal implementation detail). So, relying on the return of the method is a mistake.

Your examples:

- Process.fork returns a pid or nil. That's useful. -> because you looked at the source code. The docs won't say anything about the return type.
- Process.kill return 0. Always. What can you do with that? How is it useful? -> it's not, Process.kill won't say anything about the return type.
- File#close returns an empty array. You could change that to return nil but what are you going to do with it? -> nothing, but `File#cluse` won't say anything about the return type

In all the examples you mention, you are relying on a return value just because you are peaking in the source code. You can peak at it, but if the docs don't say what the method returns, don't rely on that value. It's a very simple rule.

You can also turn private methods into public by redefining them. Later I decide to remove the private method and your code will break, but you shouldn't have done that in the first place.

Note that this is my point of view on this subject, but this doesn't mean I dislike the idea of `Void` :-)

**Comment by jhass** [comment]
I feel like we're hitting a discrepancy in language design philosophy here. Mainly the colliding world views of

* A language should enforce as much as possible and give you no way around those enforcements. A library author knows better than you what you need and should be able to do with a library.
* A language should be open, giving you hints where the recommended and approved way of doing things is, but not block the paths besides it. It should make best practices easy and pleasure to follow, but allow you to shoot yourself into the foot. Repeatedly. For the rare occasions where getting the job done is just more important than following the ideal or supported way.

Ruby, and its community, is strong on the second philosophy. More traditional languages like Java and C++ are stronger on the first point. So far I think Crystal is heading where Ruby is heading, with some more emphasis on the best practices part by taking practices from the first philosophy or hiding the sideways better.

What can make out of this for this discussion? If we can take a clear stance on either philosophy, this becomes a fairly trivial question to answer. If we go with the first philosophy, then the answer is yes, let's try to protect the user where we can, because we know better. However if we go with the second philosophy, what @asterite said comes into play: we should make clear that you're relying on undefined behaviour or internals by not documenting those parts. If you discover these things and ways in how they can be useful to you to achieve something quick, we won't forbid you to do it, just discourage it. But we won't protect you, you're on your own there for all the positive and negative implications that has.

**Comment by technorama** [comment]
@asterite / @jhass Should the compiler not allow dangerous operations/undefined behavior or should we follow the path of C with LOTS of undefined behavior and yelling at the programmer if it happens to break.

@asterite developers don't read documentation reliably.  Even if they do read it they may be copying an example from someone else that appears to work but is subtly incorrect.

@asterite there is no use case provided here where `if` with Void is valid, or as you suggest `if` with a `nil` return serves a purpose.

Void with if statements stops certain classes of bugs completely AND serves as a way to document the return value.

If dangerous operations should be allowed and the programmer "needs" it then we should drop all `nil` checking enforced by the compiler.  To me this is the same type of issue.  I desire that an `if` statement on a possibly `Void` return results in a compiler error just like method calls on possibly `nil`'s result in compiler errors.  That's it.  That's the main type of error I want to avoid.  The other requirements are flexible and @jhass has outlined a use case in inspection/printing that require variable storage of `Void`'s so I have dropped my request for all other requirements previously mentioned.

One more time:  I don't want a method returning `Void` to work with `if`.  That's an invalid operation.  Returning `nil` doesn't work.

**Comment by jhass** [comment]
Given we partly moved into the opposite direction with #2701 and that it also made a return type restriction of `Nil` always return `nil`, let's close this.
