### ISSUE TITLE
Adding Marshal support

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14179]
## Discussion
Adding Marshal support as ruby is. (I can't find Marshal module)

#some thoughts:
when Marshal.load involves a class then
it may needs
1.dynamic require
it makes no sense to require all possible classes beforehand just for supporting loading some unknown class.
2.dynamic load a class
after the const is defined, I need to Object.const_find(cls_name).new(...) to instantiate it.

**Comment by Blacksmoke16** [comment]
Related: https://forum.crystal-lang.org/t/possible-to-serializer-deserialize-and-object-like-ruby-marshaling/564.

**Comment by yxhuvud** [comment]
The problem with Marshal (and with including the bad parts of the yaml standard that allows arbitrary serialization for that matter) is that it tends to break on version changes, and it tends to add security vulnerabilities, because at some point people will try to unmarshal untrusted input.

Just a couple of weeks ago I tried to make an old project to work which depended on serialized data that was serialized using something akin to Marshal (though in python), and in the end had to give it up because the serialized data was tied down to versions of dependencies that only work on python 2.7. Had it instead used custom serialization then it should have been no issue at all to upgrade it. 

I sincerely hope nothing like this becomes reality in crystal.

What problem are you trying to solve? There may be some less problematic way to solve it?

**Comment by kostya** [comment]
Full ruby Marshal not possible to implement in Crystal, because it can serialize dynamic things. But crystal is a static language. You can use `JSON::Serializable` or others serializable. And It actually quite close to Marshal, if you know your data structure.

**Comment by femto** [comment]
1. for performance reasons. binary is more performance than clear text protocol.
2.For needs like crystal itself, like say compiling bytecode and then Marshal.dump it,
in order to support incremental compile.

**Comment by kostya** [comment]
1. for performance you can use msgpack, which also have serializable.
2. no idea, sounds like something strange.

**Comment by straight-shoota** [comment]
This is an issue tracker for *actionable* items. An open discussion about a possible new language feature is *not* an actionable item. It only becomes an actionable item once there is a clear plan about how to implement it and at least some reasonable consensus about that plan.

This kind of discussion belongs in the forum, not the issue tracker. Closing.
