### ISSUE TITLE
Drop with .. yield

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14205]
## Discussion

this comes from here,
https://forum.crystal-lang.org/t/questions-about-with-yield/6283/7

I think HertzDevil says `scoped yields` == `with .. yield`, right?

yeah, I agree with that to drop this confusing syntax,

but then instance_eval/instance_exec is needed, the reason being [here](https://www.saturnflyer.com/blog/the-difference-between-instanceeval-and-instanceexec)

**Comment by jwoertink** [comment]
Personally, I'd rather see the scoping issues fixed with `with ... yield`, but I know @asterite has mentioned wanting to remove it before too. After having mentioned that, I started removing it from any of my projects that use it just in case, but I know there's a lot of popular shards like [Jennifer](https://github.com/imdrasil/jennifer.cr) that use it. 

I don't think adding `instance_eval/instance_exec` would be a good idea though. Crystal isn't Ruby, nor a dynamic language, and adding dynamic metaprogramming concepts like this would lead to a lot more issues than what `with .. yield` has.

For example:

```crystal
abstract class Foo
end

class Bar < Foo
end

module Baz(T)
  T.instance_eval do
    abstract def run : String
  end
end

class Qux < Foo
  include Baz(Foo)
end
```

In this case, it really shouldn't compile since (in the Ruby sense), it would make a class method `run`, but you can't define an abstract method on the metaclass. While each of these edge could be accounted for, I don't see how that's not any different than accounting for edge cases on `with .. yield`.

**Comment by straight-shoota** [comment]
There already exist several discussions about this topic, here and in the forum. If you want to start a fresh discourse, please refer to the numerous arguments that have already been made with a summary and optional opinions. It does not make any sense to start a new issue with zero reference to what has already been talked.

Also, this is an issue tracker for *actionable* items. An open discussion about the possibility to change a language feature is *not* an actionable item. It only becomes an actionable item once there is a clear plan about how to implement it and at least some reasonable consensus about that plan.

This kind of discussion belongs in the forum, not the issue tracker. Closing.
