### ISSUE TITLE
Another undefined const regression on master

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14495]
Follow up to #14489.

```cr
module MyApp::Component
  module MyApp::Component::Model; end
end

class Foo
  include MyApp::Component::Model
end

pp Foo.new.is_a?(MyApp::Component::Model)
```

Current master branch results in:
```sh
$ ccrystal test.cr
Using compiled compiler at /home/george/dev/git/crystal/.build/crystal
Showing last frame. Use --error-trace for full trace.

In test.cr:6:11

 6 | include MyApp::Component::Model
             ^----------------------
Error: undefined constant MyApp::Component::Model
```
Whereas it prints `true` on latest release.

Personally I don't think this one is a bug and actually more correct than the previous behavior. But I at least wanted to report it for posterity.

**Comment by straight-shoota** [comment]
Yeah this is pretty much the same issue as #11181.

Since https://github.com/crystal-lang/crystal/pull/11208, `MyApp::Component::Model` inside the namespace `MyApp::Component` resolves to `MyApp::Component::MyApp::Component::Model`, not `MyApp::Component::Model`. And that's correct.

If you want the previous behaviour, you'll either need the module definition to use a global path (`module ::MyApp::Component::Model`) or (better) strip the path prefix that's equivalent to the namespace (`module Model`).

**Comment by Blacksmoke16** [comment]
Duplicate of #11181
