### ISSUE TITLE
Parser considers empty argument list with trailing comma as invalid

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14629]
The following code fails to parse with `Error: unterminated call`

```cr
bar(,)
```

I think this should be valid code because it's just a list of arguments with a trailing comma. It just happens that the list of arguments is empty.

Currently, the parser expects a comma to appear only *after* an argument. I think it should be accepted without an argument.

But this should probably be treated *exclusively* as a trailing comma, i.e. there may not be any more arguments afterwards and the next expected token is rparens. `bar(,1)` would not be valid.

**Comment by devnote-dev** [comment]
Commas historically represent a break or pause in a statement or expression in programming and linguistics, the only exception is cases where a comma represents something conceptually different (like in array and esoteric languages). There is no such case in Crystal so there's no reason why it should follow this pattern.

This syntax also isn't supported in Ruby, Python, JavaScript, PHP or Go (yes, I tested all of them) so I don't understand why Crystal would allow this. Even from a parser perspective it doesn't make sense, because with all the aforementioned, a comma signifies the end of the expression that precedes it. Allowing no expression before a comma would also likely permit `method(,,)`, and having additional parsing logic to prevent this is a waste of time.

**Comment by zw963** [comment]
> bar(,)

Not seeing any benefits to support this?

**Comment by oprypin** [comment]
The reason to allow a trailing comma is that all tooling can cleanly treat it as:

```python
"def" name "(" ( argument "," )* ")"
```

So indeed I don't think that this logic generalizes to just a comma in the case of 0 arguments, instead it definitively generalizes to "nothing".

**Comment by HertzDevil** [comment]
A "leading" comma would indicate a `Nop` argument, but then it becomes ambiguous whether the position after the `,` and before the `)` also counts as a `Nop`. The only thing I'm aware of that supports this is the C preprocessor:

```c
#define foo(a, b) 1
#define bar(a, b, c, d) c

int main(void) {
    return foo(,) + bar(,,5,); /* => 6 */
}
```

**Comment by straight-shoota** [comment]
I agree this syntax doesn't really make sense. It's certainly not well formed, and there's no *need* to support it.
My motivation is solely that the parser needs to support this in order for the formatter to be able to fix it.

However, I think I got confused about the origin of this issue and wrongly understood it as being produced by the formatter (as part of #14609). However, I actually only sumbled across this while researching on that issue. So it's not something that happend in a real use case.

I suppose there could still be an argument that it's *possible* to end up in an editing process where all arguments of a call are removed and only a comma is left over. Or multiple commas in a row because the argument in between was removed. The intention of the code would still be clear and the formatter could fix it to be well-formatted. Having the parser accept the syntax would be quite quirky, though.
Judging from the responses on this issue, there doesn't seem to be much support for that. So I'm closing this.
