### ISSUE TITLE
[RFC] Separating pass by value from memory allocation location

### ISSUE THREAD

**Issue by technorama** [crystal-lang/crystal#1517]
Currently objects are reference (heap) allocated with pass by reference semantics.  Structs are inline allocated on the stack or as part of another object with pass by value semantics.  The behavior of pass by X or allocate in location Y are not inherently tied together.

Passing by x defines the semantics by which the program is structured.
Allocating on the stack or heap is an optimization and shouldn't effect how the program is structured.

Mixing these 2 concepts forces users to restructure their programs when optimizing or forgo optimizing to gain the desired passing behavior.

A better model would allow specific Objects to be optionally allocated locally through annotation, keyword or some other method.  

. | Pass by Ref | Allocate Heap | Pass by Val | Allocate Local
--- | --- | --- | --- | ---
Object(heap) | :white_check_mark: | :white_check_mark: | |
Object(local) | :white_check_mark: | | | :white_check_mark: 
Struct |  | | :white_check_mark:  | :white_check_mark:

The current state of crystal

. | Pass by Ref | Allocate Heap | Pass by Val | Allocate Local
--- | --- | --- | --- | ---
Object | :white_check_mark: | :white_check_mark: | |
Struct |  | | :white_check_mark:  | :white_check_mark:

Some use cases
* No need to change from class to struct just to change the memory location and risk breaking existing code.
*  Video game programming with object pooling.  Pass by reference is desired but iteration over the entire collection is common (memory locality).
* Memory locality for inline objects that retain pass by reference semantics when the inner objects are passed to other functions.

**Comment by asterite** [comment]
So you can allocate an object locally and pass it by reference? For example you can return a pointer to locally allocated data and crash everything? This definitely needs more thought :-)

I think with a smarter compiler (escape analysis) this can be done automatically. I wouldn't like to infect the language with all sorts of annotations.

In any case, we have lots of other things going on, we can always introduce this at a later stage.

**Comment by technorama** [comment]
Escape analysis is useful for temporary variables but not necessarily for embedded objects.

My main goal is not saving GC cycles but improving memory locality.  The code below would run much slower if each object is in a random memory region.
```
class Foo
  #
  @bar = (allocate inline) Bar.new 
end

array = StaticArray(Foo, n).new { Foo.new }
load_data(array)

event_loop do
  update_values(array)
  sequentially_analyze(array)
end
```

**Comment by pgkos** [comment]
Let's say we have this struct and this array:
```crystal
struct Point
  property x
  property y

  def initialize(@x, @y)
  end
end

ary = [] of Point
ary << Point.new(2, 3)
ary << Point.new(4, 5)
```

I give a +1 to the possibility of doing this:
```crystal
ary[0].y = 6  # now it does nothing
puts ary[0].y  # 3
```
Now, `ary[0]` creates a copy of the Point, so the first line of code does nothing - it operates on the copy! This is, in my opinion, quite unintuitive and inelegant. Also, it is inconsistent - if Point was a class instead, then the second line of code would work as expected.

Moreover, if we strive for maximum efficiency, we should (in case of structs) allow operating directly on the array's members.

Now, in order to modify the struct in place, we have to do this:
```crystal
ary.to_unsafe as Pointer(Int32))[1] = 20
```
which modifies the `y` property of the first Point in the array.

As expected, using pointers here is faster than reassigning the whole Point. On my computer - at least by 21% (`build --release`) and at most 3 times faster (without building).

I have no idea how to implement this without some changes to the stdlib. Maybe, by default, we should pass **composite** (with at least 2 member variables) **and `malloc`'ed** (as in arrays) structs by reference?

Another alternative would be to allow allocation of contiguous arrays of classes (not pointers to them).

**Comment by ozra** [comment]
At risk of repeating something I've already written somewhere else in the issues mountain:

I agree for some change regarding this, I hope the following is understandable, a bit tired atm:

Declarings structure (class) and allocation mode should be separated.

- If I create an array of objects, I probably don't want it to be an array of references.
- If I create a class containing members of other classes, I may want them to be references, or, just as likely "inlined" (memory locality), as structs are.
- If I pass an object to a function (method) I might very well want it to be by reference, (but might want it immutable - other issue), even though it might be allocated "in" another object (composed class), or in an array.
- If I create an object in a method, locally assigned, it might very well be better off on the stack (escape analysis for this case).

`Objects` should be `classes`, and that's it, for the allocation behaviour, it seems to me, some hinting keyword like `val` and `ref` could be of use, both for data-members in class-defs and method param-defs.

This of course means that code like `@some–val–member = SomeType.new()` must fail (returns ref), the initializer should be used on the already 'part-of-this-allocated' object.

**Comment by asterite** [comment]
I'm closing this. The compiler will eventually know that an inline object is never changed (only assigned in the constructor) and can be embedded inside it, avoiding an extra memory allocation.

Otherwise, please reopen and add how the language needs to change, both in terms of syntax and semantics, with as much formalism as possible.
