### ISSUE TITLE
`Log.error(exception: exception) {}` is a no-op

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#15221]
In my codebase a long time ago I had a line **`Log.error(exception: exception) {}`** in order to print an exception.
But now this line simply does nothing.

To work around this, I had to change this to **`Log.error(exception: exception) { "" }`**

* This seems related: https://github.com/crystal-lang/crystal/pull/12000
  Thanks to @Blacksmoke16 for pointing me in this direction.

This behavior should be specced / documented / fixed. To me this behavior doesn't make sense. Why would I pass the `exception` arg, other than if I expect it to be printed

**Comment by straight-shoota** [comment]
I believe this is simply an error by omission. Nobody noticed the case that an exception may be given but the block returns nil.

Perhaps we could also consider adding an overload which accepts a required `exception` parameter and no block?

Then you could write just `Log.error(exception: exception)` instead of `Log.error(exception: exception) { }`.
