### ISSUE TITLE
Proper way to store bytes array

### ISSUE THREAD

**Issue by Xanders** [crystal-lang/crystal#1681]
Hello all. Sorry if there already was issue about this - I didn't found it.

Crystal String is designed for UTF-8 strings. There are a lot of bytes methods that works at any byte sequence (String#bytesize, String#byte_slice etc) but a lot of other methods expect a valid UTF-8 sequence.
Let's think about MessagePack or any other raw-bytes-strings (like blobs on databases, image files etc). How to store it properly? Now https://github.com/benoist/msgpack-crystal return Array(UInt8). It is a good way by design but bad way in real world. All Ruby (and lot other langs) programmists expect a String as result of MessagePack.pack or, for example, getting string from Redis or MySQL's blob. And they build libraries that expect Strings on IO operations like in https://github.com/stefanwille/crystal-redis - there is no easy way to store Array(UInt8) in Redis. And now this lib expect String while getting data from Redis and it's broken if I try to write MessagePack string and then read it:

```crystal
redis = Redis.new
redis.set "some", MessagePack::Packer.new.write("some").to_s # I can't use MessagePack.pack("some"), see above
some = redis.get "some"
p MessagePack.unpack some if some # Broken string "some\u{0}"!
```

I just mage pull request to Redis that fix it: https://github.com/Xanders/crystal-redis/commit/bf52d6fbc010881a61838acb9e47180d3e45c2c0
But I don't think it is a proper way. I must always hold in mind to use #bytesize instead of #size, #byte_slice(int, int) instead of #[int, int] etc. And if I made a mistake compiler will not save me.
Please read this discussion: https://github.com/Xanders/msgpack-crystal/commit/c03a8ef35d20d18a947d7af6ea94476da280af96

I think something like ByteString < String or String::Raw < String will solve both problems. We can add String#raw method witch returns ByteString/String::Raw instance, and then all methods will work with bytes instead of UTF-8 endpoints (#size will work like #bytesize, #[int, int] like #byte_slize(int, int) etc). And all libs in real world that expects String will work well because this instance's class will be subclassed from String, and even if other lib use #size instead of #bytesize all will be good, because I already marked my string as raw.

Another way to solve the problem is using Ruby's encoding system, witch works very well. I can just encode any string to ASCII-8bit and it will work at any foreign lib as I expect.
Also, for me, luck of encoding system and Windows support are two major factors against using Crystal at my projects (many of old services my customers operate use non-UTF-8 encodings, so I can use only Ruby, not Crystal, and I must start my services on Windows environment often).

Hope we will find some great way to solve those problems!

Sorry for my bad English and hello from cold Russia (all that you hear about us from TV is bullshit).

**Comment by jhass** [comment]
I think we should aim for `Slice(UInt8)` to be the primary container for byte sequences, not `String`. In fact using `String` for storing arbitrary byte sequences causes many headaches in Ruby (please take my word for it, as someone actively watching the #ruby IRC channel for years now). So it's rather a question of having that as the primary interface for libraries. It already is the primary interface for stdlib IO, see http://crystal-lang.org/api/IO.html. Any methods that take strings should be merely convenience wrappers around the overloads for `Slice(UInt8)` that handle data that properly encodes to UTF-8 (and other encodings in the future). Ruby's `ASCII-8bit` is a gigantic misnomer, since it in fact is no encoding at all and simply turns off any encoding handling for `String`.

**Comment by ysbaddaden** [comment]
Ruby uses String to store and represent binary data because it lacks a proper container. Other languages like Erlang/Elixir or Rust, and Crystal of course do have binary types.

As outlined by @jhass you are looking for slices. They're the proper containers for binary data in Crystal (think of them as a Tuple of bytes), and they can be read and written from and to any IO object. By using String you'll quickly end up with encoding problems and invalid UTF-8 byte sequences, which can be avoided altogether by using a simple `Slice(UInt8)` sequence.

**Comment by jhass** [comment]
Thinking about it, this is related to #1601

**Comment by ysbaddaden** [comment]
I understand the complexity in the examples provided. We can legitimately expect for `redis.get(key)` to return a String, but that won't work if the key is actually a msgpack binary, hence it should be a Slice(UInt8), but a redis client has no way to make the difference by itself.

We can use overloads like `set(key, value : Slice)` and `set(key, value)` to differentiate the set operation, but we can't do that for the get operation... So, maybe a `get_binary(key)` or `get_raw(key)`? and `get(key)` would be a convenience for`String.new { get_raw(key) }`

**Comment by Xanders** [comment]
Thank you for replies. I'm absolutely new to slices, and now I read docs and have some questions:

1. Slice is subclass of Struct and Struct is subclass of Value and in Value docs I read: "when you pass it to methods, return it from methods or assign it to variables, a copy of the value is actually passed". Does that mean when I read some 1Gb movie file into memory with Slice(UInt8), and after that I passed this file to 10 methods will be there 10 copies of movie, and will 10GB of memory be used?

2. Why String#bytes and Char#bytes return Array(UInt8), not Slice(UInt8)?

3. What's the benefits of Slice(UInt8) against Array(UInt8)?

I still think that having one unified container like in Ruby is simpler in many cases. For example I want create a web-server which can answer with JSON or MessagePack, depending on the request headers. So in Ruby I will write one interface that operating with encoding-less strings, and in Crystal I must implement two interfaces - String for JSON and Slice(UInt8) for MessagePack. But now MessagePack returns Array(UInt8) instead of Slice(UInt8), and some lib (BSON etc) developers can do either, so it will be better to support third interface for Array(UInt8).
MessagePack.unpack should recieve strings, Slice(UInt8) and Array(UInt8) as argument too. Redis would support marshalizing all of them too. All web libs should support passing String/Slice/Array as argument for POST-params, WebRTC, WebSocket (which all has binary mode support) etc.
Working with slices looks like a bit more complex (especially without reallocing from https://github.com/manastech/crystal/pull/1601), but benefits are not clear for me. Maybe it's because I don't know some details. In my practice (about 6 years of Ruby) there wasn't any problems with bytes in strings. Ruby strings in ASCII-8bit (which is encodings-less, I know) are just byte arrays in fact, aren't they? :)

But, OK, I see your point and don't want to press of course!

Thought about redis.get too. Looks like get_raw is only way, but also there will be a tons of other _raw-methods for other Redis types. For example Redis List of strings/slices.

**Comment by jhass** [comment]
It's true that the full design around this is not finished, mainly because there hasn't been a clear commitment to the issue from the language designers, yet.

Regarding `Slice`, being a struct, it contains a `Pointer` and a size, so not the actual data is copied on pass, only the pointer and the size. If you change the data the pointer points to, it's reflected everywhere.

Perhaps `String#bytes` should indeed return a `Slice(UInt8)`, though that would make it kind of redundant to `String#to_slice`. This plays into the above point, we need a clear goal we can design APIs towards to. So some clear commitment from @asterite and @waj what the primary storage type for arbitrary byte sequences should be is very needed.

When we got that, we can look into allowing things like serializing JSON into a `Slice(UInt8)` or whatever, however I don't quote follow your example, you can already turn a `String` into `Slice(UInt8)`, but more importantly you would have to differentiate between MessagePack and JSON data in your Ruby API too, since you not only need to set the Content-Type accordingly, but also encode the response body, since returning arbitrary byte sequences is invalid there too.

**Comment by ozra** [comment]
Small side note here, but, I find the name `Slice` slightly confusing. I get the hinting, a "slice of memory", but to me it sounds more like a "temporary work slice of a buffer or something". So if slices can be allocated, I'd find it much more natural to have a `Buffer` type or something. Slices could be derived, but their name really suggest a temporary, view like, use to me..

**Comment by jhass** [comment]
I turned this into an RFC, since we need a clear guideline from the language designers here.

**Comment by asterite** [comment]
Slice(UInt8) is for binary data, String is for UTF-8 data. But note that String can hold non-UTF8 data, just like in Java Strings can hold non-utf16 data and in Go strings can hold non-UTF8 data.

For Redis, maybe you can define two methods, one that returns a String and another that returns a Slice. Or just return a String and then call `to_slice` on it. Then you have `String#bytes` that returns an Array, and it returns an Array because arrays are more higher level than slices, and `to_slice` is more low-level. You can append to an Array, shrink it, etc., so it's more useful for an end-user. But for IO use Slice.

**Comment by Xanders** [comment]
Thank you all for replies! I see your point, so OK, I'll not discuss much. :) I also understand the way Crystal's moving (I'm about issue https://github.com/manastech/crystal/issues/1824 and so on), and it is good, but just not "Ruby way" I prefer.

I still don't understand, why I should prefer Slice(UInt8) instead of Array(UInt8) if Array is better in all directions and more hi-level. I am end-user in this case, and why I should prefer more useless interface over more usefull (your words)? Is there any performance reasons?

It's not only about slices. Creators of the language says "we prefer one way to do same things over many ways" and kill many beautiful method's aliases, breautiful "and"/"or" and very usefull in some cases tralling while, but also they introduces a huge mess of things, which allows me to do things that I already can do with other things. I'm about enums (we already had symbols *exactly* to avoid ugly enums), structs (we already had classes), abstract classes and virtual methods (we already had modules), chars (we already had strings), slices and turples (we already had arrays) and so on.

I don't think that Ruby "lacks" a proper container. I think, it is a deliberate choise in the direction of unified language stdlib with hi-level containers, way of simplify for a end-user (programmer), but complex inside.

Maybe sometime I'll release my dreams about beautiful and simple static-compiled lang with myself. :) Because I see, Crystal is not it, it's just another Nim/Rust/Go nowdays.

Buuut... I still like it. ^_^ Not as Ruby, but much more then Nim/Rust/Go company.

I'm agree that Slice is confusing name. Honesty, UInt8 too. Maybe aliases Byte = UInt8 and Bytes = Slice(UInt8) may be usefull. MemoryIO is good name too. :)

Before the war was String vs. Array(UInt8) vs. Slice(UInt8), and now "vs. MemoryIO" part was added. Oh... I'll try to dig it. :)

@jhass "but more importantly you would have to differentiate between MessagePack and JSON data in your Ruby API too, since you not only need to set the Content-Type accordingly, but also encode the response body, since returning arbitrary byte sequences is invalid there too."
Hmm... Why? HTTP response body can consist of raw byte sequences, like in at image answers. I don't need to encode JSON and MessagePack in different ways in Ruby. Just copy Content-Type header from request at push bytes from controller into body. I'm already tried this, and it works. :)

**Comment by gamebox** [comment]
@ysbaddaden You say that Crystal has a binary type, could you provide a reference to its definition or usage?  I'm in need of this, thanks.

**Comment by asterite** [comment]
@gamebox [Slice(UInt8)](http://crystal-lang.org/api/Slice.html)

**Comment by asterite** [comment]
I'm closing this. We have these types in Crystal:

* `String`: immutable bytes that denote an UTF-8 text. This should be the type to return when asking for text content.
* `Slice(UInt8)`: mutable bytes that denote binary date (they could also denote a string). This should be the type to return when asking for binary content.

If both binary and text content must be returned by an API, the best thing to do is to provide two different methods for this. To do this, one could implement the method that returns a string by invoking the method that returns the slice and then do `String.new(slice)`, though that allocates extra memory. The best thing to do here is use a helper method that fills a buffer (the size of the slice is probably known by the protocol).

If the underlying data is now known by the API, `Slice(UInt8)` should be returned. Users can then turn it into a string by doing `String.new(slice)`.

One example of this is [Base64](http://crystal-lang.org/api/Base64.html), where we have [decode](http://crystal-lang.org/api/Base64.html#decode%28data%29-instance-method) returning `Slice(UInt8)` and [decode_string](http://crystal-lang.org/api/Base64.html#decode_string%28data%29-instance-method) returning a `String`.
