### ISSUE TITLE
Manually integrate or pull OpenSSL.cr to crystal repo

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#1710]
So, it seems that https://github.com/datanoise/openssl.cr hasn't been updated in around 3 months now.
I think we should manually copy the changes or ask @datanoise to create a pull request with the changes.
It would help other who wants to add to the Crystal OpenSSL implementation to know where to do it (not everyone knows that the more advanced code is there).

What do you think ?

**Comment by asterite** [comment]
I think it will be fine with @datanoise if you send us a pull request with the changes.

**Comment by datanoise** [comment]
I apologize but I've been quite busy lately and didn't have time to follow all those wonderful changes in the crystal-lang land. I'd appreciate if someone helps me to prepare the pull request. I'd love to see this code in the official repository.

**Comment by technorama** [comment]
Has anyone considered the spec failures that are likely to result from various versions of OpenSSL that may or may not have all necessary methods to complete the specs?

AC_CHECK_FUNCS or similar functionality would resolve the problems in this library and many more.

**Comment by asterite** [comment]
We are working on something to generate automatic lib bindings using libclang. But it's not finished. So don't worry about that. But until then we'll have to use what we.

Check our crystal_lib project

**Comment by technorama** [comment]
@asterite What about the spec failures due to different versions?  Change them to pending and live without them?

**Comment by benoist** [comment]
I've got a compiling version with the latest crystal build, but I've got three failing specs that I don't know how to resolve due to lack in OpenSSL library knowledge.

**Comment by benoist** [comment]
I've managed to fix the issue I had and updated the pull request with a working spec in the openssl.cr repo

**Comment by technorama** [comment]
Ruby is in the process of gemifying OpenSSL so it can be kept up to date.  Is there a strong reason for including it in crystal rather than using shards?

https://bugs.ruby-lang.org/issues/9612

**Comment by benoist** [comment]
I think it has pros and cons. Separately fixing security issues is a pro, but requires people to monitor all shards. So having one place to store the Stdlib shards is a must IMO.
Because shards are not stored in a central location on the development machine, it also requires updating all the projects individually as opposed to just installing the latest version of Crystal.

OpenSSL is also one of those shards that a lot of people will require by default for doing anything with the HTTP libraries or using securerandom as Aaron also indicates here:
http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/60075
Therefore it should also be possible to have certain shards be added by default, but I don't know if that's possible given the fact that shards are stored in the project and not a central location.

**Comment by bararchy** [comment]
+1 for having OpenSSL in STDlib, because of how Crystal works in oppose to Ruby, you can't just ```gem install openssl``` and remember to ```gem update``` one in a while, you will need to do that for each project, and if there is a security vulnerability in the implementation, upgrading to latest Crystal version wont help you.  I really do believe libs like this one should live in the heart of the project.

**Comment by technorama** [comment]
Hold on, you think people are going to upgrade crystal (when it is stable) more often that they update shards?  I don't know where you've worked but gems are updated WAY more often than ruby releases on every project I've worked on.  Upgrading ruby generally requires upgrading many gems because of language changes.  Crystal will probably be similar.  Wait, crystal is already similar.  Shards break all the time from language changes.

Individual shards can release way faster than crystal once it is out of beta.  Especially when any person can create a fork with a bugfix.

I made couple of long comments in #1794 that I probably should have made here.  One of them deals with the security and upgrade problems that exist in ruby and how those will probably be identical in crystal.

So really this is +1 for having some overridable shards provided with crystal to get the best of both worlds.

**Comment by technorama** [comment]
The security problem is not unique to OpenSSL.  Any external libraries or shards will eventually require a security notification infrastructure.  Or we could just ignore security problems *shrug*.

**Comment by jhass** [comment]
A shard that provides the same filenames as a stdlib already takes precedence, I guess one should make sure to provide all filenames of a stdlib for such a usage scenario though.

**Comment by benoist** [comment]
Could I politely ask to watch the tone a bit. I'm merely expressing my thoughts. I've seen your Pr's and I respect the work you've done for crystal.

**Comment by technorama** [comment]
@benoist I apologize.  OpenSSL is a sore spot for me especially with ruby.  I had to fight to get bugs and memory leaks removed.  I had to fight to get string instantiation in ruby and not just fixed classes.  I had to fight to get keys and iv's that you could set rather than this:
https://github.com/ruby/ruby/blob/trunk/ext/openssl/ossl_cipher.c#L218
https://www.reddit.com/r/ruby/comments/ndl1p/be_careful_rubys_openssl_rulez/
and many more.

Eventually I got too upset to continue contributing.  Some of the issues I was never able to fix were automatic key wiping which required changes to the string class or fixing `Bignum / Bignum #=> Array`.  Major wtf.  It's especially galling because it's my class that was butchered.  The original had `/ #=> Bignum` and `divmod #=> Array` just like ruby.

Here I am doing some of it again >10 years later.  Repeating the same mistakes that ruby made all over again brings back many bad memories.

**Comment by technorama** [comment]
And the redundant naming.  I couldn't get them to drop OpenSSL::Cipher::Cipher
OpenSSL::SSL::SSLShit before the project was imported into ruby.  I think it's important to get these sorts of syntax/naming/upgrading/updating things correct from the get go.  It's harder to change when others rely on your language design, API's, and methods of operation.  

One continuing worry is that my OpenSSL fixes/additions (if I can stomach them) won't get merged in a timely manner or won't get merged at all.  At least as an external shard I can create my own fork.  I already have PR problems with crystal.  This is just like going back to 2003/2004 where I had to email files + diffs to get my changes in, only this time I lose the ability to fork unless I want to fork all of crystal.

**Comment by benoist** [comment]
@technorama tnx for the apology. I hear you and your points are valid. It's always good to have people with passion for their code and opinion. I hope you continue contributing and with giving your opinion. It really helps the decision makers in making a decision that is based on weighing every pro and con that gets presented. I really like contributing to a shard or the stdlib as long as it's clear where to do it so that my work and the work of others is not useless. 

In the case of OpenSSL, I think if it's only available via shards there should be a preferred shard to contribute to. Also because other libraries in the stdlib depend on it.

**Comment by bararchy** [comment]
Valid points, but, if it's going to be in an external shard, I would suggest creating a new repo under /manastech/crystal-ssl or something like that, so we could have a one place to contribute and one place to push new code into.

**Comment by ysbaddaden** [comment]
A problem is that the stdlib has parts that relies on OpenSSL (eg: to start a HTTPS server) and thus require OpenSSL to be available in the stdlib

That doesn't mean that development can't happen in a always up-to-date shard, with regular merges into Crystal. As long as both are compatible (same filenames) installing the shard will always take precedence over the stdlib.

I won't recommend this, thought, as it will require to regularly pull the shard into crystal, which can become a hassle if other parts of the stdlib start doing the same. But maybe we can make an exception for OpenSSL, since it's likely to involve security related issues we want to quickly patch our applications against.

Another solution, once we hit stable, could be to have patch releases for Crystal that would only fix the security issue and drag no other changes.

**Comment by waj** [comment]
We think is better if we keep essential libraries within the same repository, at least until the language is more stable. We still make changes in the syntax or semantics sometimes and that requires changes everywhere. That doesn't mean we couldn't split the stdlib in the future, but I think it's just convenient to keep these things in the same repository. Also, note that splitting the stdlib in different projects doesn't mean that we can't still distribute essential libraries within the stdlib with each Crystal release.

@technorama please, stop fighting and start enjoying. You already did a couple of great contributions to the language. There is no reason to get upset if some of your ideas doesn't get through. There might be others with different points of view which are still valid. There is no one unique truth for everything.

**Comment by technorama** [comment]
@waj You've already expressed that not only my ideas but my code are not welcome regardless of what they are, even if it's your design (that you don't have or won't share).  You're unwilling to collaborate on the design online or if I fly to Argentina (your excuse was a lie).  You left me waiting for any communication whatsoever for over a week when you had already told another member you wouldn't accept my offer.  Later you claim threading is fun, not a priority, don't have the time, your contributions aren't welcome no matter what lengths you go to (even temporarily moving to Argentina and learning Spanish).

Now you're going to import an external project to one that doesn't want what I can do?  Especially when I have extensive OpenSSL experience?

@datanoise accepted my PR's quickly.  The same has not been true of crystal.

Your idea of "enjoy" is very different from mine.

**Comment by mverzilli** [comment]
@technorama well if you did come to Argentina and met @waj and @asterite you'd realise they're two of the nicest guys working on software out there :). 

I think you're taking things way too personal: "not only *my ideas* but *my code* are not welcome", "*you left me* waiting for a week", "import an external project to one that doesn't want what *I can do*", etc.

Please realise that everyone here is contributing to the extent each one can, and @waj and @asterite are no exception. If you didn't receive a reply for a week it's because there's a lot going on: work commitments, personal lives and lots of other aspects of Crystal itself. 

Everyone here is giving you credit for some important contributions you already made, but some people is asking you for a little bit more kindness on your interactions. 

I'm sure your OpenSSL experience and the rest of your ideas are being taken into account just as anyone else's, so don't let your manners cast a shadow over that.

**Comment by technorama** [comment]
@mverzilli My issues are not with the time delays but with the way it was handled.  Another project member was told about rejecting my offer within a day or 2 and the reasons why.  It took over a week to tell me directly.   It's obviously not a time issue if they have time to speak to others but not tell me directly, ask me questions or answer any of mine. Many attempts were made to contact asterite and waj through irc, email, issues, and wiki entries.  No comments were ever made on my proposals except "don't work on that".  Every collaboration effort was made on my part and none on theirs except silence and a belated "no".

Maybe they are nice guys in person but their communication sucks.

**Comment by technorama** [comment]
I've bent over backwards to collaborate on threading, get a spec approved, or get anything at all.  What will be accepted?  Who can tell me that?  Why should I create PR's when I don't know if they will be approved?  Why create issues and email proposed designs if they are met with silence?  What other options do I have other than complaining publicly or forking?

This isn't just about threading.  It's the smallest of issues sitting around for months without a response: #1284.

**Comment by bararchy** [comment]
I fell we are getting away from the flame original discussion and this is turning into a thread , let's gets back on the subject please.

1) do we want a external repo that will hold OpenSSL and would be merged into main crystal once every release ? 

2) do we want OpenSSL to be only inside main STDlib ? 

3) do we want OpenSSL as a fully external shard ? 

I think we should answer those questions in order to continue.

**Comment by kirbyfan64** [comment]
@technorama BUT you're missing the point. This is a project managed by *people*. Which means, there inevitably will be delays, accidental non-replies (you know, when you read a GitHub issue, say you'll reply later, and don't), and stuff like that. @datanoise's project is small and has WAY fewer issues open than Crystal.

Also, about the PR approval: normally, it's best to open an issue related to whatever and mention that you'll implement it...but don't implement it yet. That way, if it gets closed, there's no lost work, and you can avoid constantly tweaking PR commits over and over again.

**Comment by waj** [comment]
@bararchy thanks for bringing sense to the conversation again

As I expressed before, I'd prefer to keep OpenSSL within the stdlib, and within the same repository. At least until we feel the need to do something else. I can't stop anyone to create alternative libraries to those that are included with the language but it is my wish that the stuff included in the stdlib is good enough to anybody trying to do common stuff with the language.

**Comment by technorama** [comment]
@kirbyfan64 You're missing the point.  I've tried all of those things.  First I created PR's which sat idle.  Then I tried issues describing the proposed interfaces which also sat idle.  Sometimes if I create the issue (which is ignored) and then submit a PR the code gets merged.  Other times neither get any feedback.  Either way I'm wasting my time.

It's requires me reading their minds to know what will or won't be approved.

Let me say this again.  As *people* their communication about PR's and issues suck.

**Comment by technorama** [comment]
@kirbyfan64 You're point about @datanoise's project only supports my position.  Crystal moves too slow with issues and PR's.   The bottlenecks are @asterite and @waj.  They're busy people and that's ok but funneling everything through them is only going to make the problem worse.  I thought distributed development was a solution for this problem but apparently I'm mistaken.

**Comment by bararchy** [comment]
@benoist , as @waj prefers to pull the changes into the STDlib, could you create a PR to crystal ?

**Comment by bararchy** [comment]
@benoist Sorry, I just saw you already did it.

1) https://github.com/manastech/crystal/pull/1794
2) https://github.com/manastech/crystal/pull/1787

@asterite @waj I think we can close this issue, as the PRs been taken care of by @benoist

**Comment by benoist** [comment]
@technorama I really understand your complains. You spend time working on something and if it turns out that it's not gonna be used it really sucks. The reason I started looking for OpenSSL stuff came from a requirement for the Cipher and Digest methods. The project I'm working on requires this, but unfortunately it was not in the stdlib yet. Looking for alternatives I came across the openssl.cr shard. This did not compile so I decided to see how to make it compile again so I could use it. Then this thread started and I thought, well if I succeed with upgrading openssl.cr to 0.9+ then I might as well see if the work is good enough for the stdlib, as @waj and @asterite indicated that they like to keep in the stdlib. Because my original requirement is only for Cipher and Digest and I don't need the X509, RSA and PKEY yet, I choose my own priority. 
This way I was able to create small PR's to be reviewed. If they get accepted that would be great. If they need some changes, tell me and I'll change it. If it's not what you want, well though luck for me, but I'll keep using the code in my own project until a better alternative is provided. This way I didn't waste my time while still contributing. I will not move the X509 and other stuff until I'm asked for it and I get a feeling that if I put the effort in it, the effort will be rewarded with an eventual merge (after review off course and giving the credit to @datanoise and you for the code in openssl.cr).
So far this has worked for me with a requirement for SliceIO (StringIO got changed to MemoryIO, my problem solved). My local HTTP stuff was buggy due to lack in timeout support, as soon as it could be added, I added it to the HTTP libraries, used it in my project and created a PR. It whas nice that this was accepted. 
The requirement for IP address being set on the HTTP request is still pending. But it doesn't stop me from using my PR on my machine. I'll patiently wait till a better alternative is provided. 
Sometimes this can be frustrating, but that's really more my problem and something I just have to accept when dealing with a project thats not in my lead.
I really hope you can find maybe a similar way to go about your suggestions as your suggestions have helped me and the crystal lang well.

**Comment by asterite** [comment]
@jhass @ysbaddaden maybe this can be closed now?

**Comment by jhass** [comment]
We worked on the TLS side of things, the X509 side of things has its own issue with #2771, but OpenSSL is still a lot more than this. Especially the cipher stuff is still lacking, we also lack support for engines and the various PKCS versions. And probably some stuff I don't even know about or forgot right now.

**Comment by bararchy** [comment]
@asterite @jhass 

Hi Guys, so , What is the status on this, is there more work to be done ? can we maybe point up points regarding what is needed for this to be closed ?

**Comment by bararchy** [comment]
@asterite @jhass 

This issue is specificlly for the OpenSSL.cr merge which is kinda irrelevant now.
Closing this issue and we can continue discussion on improving OpenSSL in Crystal at another thread
