### ISSUE TITLE
Integers do not undergo implicit casting in function calls

### ISSUE THREAD

**Issue by Philpax** [crystal-lang/crystal#1778]
Unsure if this is by design or not, but:
```crystal
def test(value : UInt64)
    pp value
end
test 0_u8
```
results in
```
no overload matches 'test' with types UInt8
Overloads are:
 - test(value : UInt64)
```
As this is a strict up-cast possible with any possible `value`, I argue that this should be implicit.

Similarly, the inverse should be true if using an integer literal that fits in the new type:
```crystal
def test(value : UInt8)
    pp value
end
test 0_u64
```
Most of my problems with this arise from the use of an untyped constant (i.e. `test 42`); these constants default to `Int32`, which means I have to specify the type each time I want to call a function that takes a different type.

**Comment by kumpelblase2** [comment]
I think automatically upcasting is "fine" as it doesn't really change anything, but how would you deal with something like this?

```crystal
# Somewhere above your code you get a number that is > UInt8::MAX
some_var = UInt16::MAX

def test(val : UInt8)
  pp val
  # for the current example (given it would just cast to UInt8) it would print 255
  # but you've put in a larger number, so you'd most likely wonder what happened to it.
end

test some_var
```

What would the desired behavior be? Simply casting to down? I think the user should be aware that he might be doing an invalid operation and should decide what to do, so either noticing "Hey I got a larger number than my function can deal with" or "I don't care if it's higher".

**Comment by Philpax** [comment]
I agree - that shouldn't be valid behaviour. However, when the compiler can prove that the value fits within the range (i.e. an integer literal between 0 and 255), it should be implicitly casted.

**Comment by jhass** [comment]
Having this special case for just numbers would seem weird to me. Generalizing it would mean automatic conversions (this already is a conversion conceptually, that it can be achieved through casting is an implementation detail) and thus weak typing. And I hope we all can agree that weak typing isn't to prefer.

**Comment by ozra** [comment]
I've proposed earlier, and will again, that _literals_ should be weakly typed.

**Comment by jhass** [comment]
@ozra so `"1" + 2 == '3'` should be `true`?

**Comment by asterite** [comment]
The compiler looks up method matches by first inferring the type of call arguments. Having an exception for number literals is bad, as with almost any exception. Also new errors start to appear:

```crystal
def foo(x : Int64)
end

def foo(x : Int8)
end

foo 0 # Matches both, a new error message now appears
```

How often do you need to use `UInt64` and invoke methods with literals? Also, you could do this:

```crystal
def test(value : Int)
   value = value.to_u64
end

test 0 # now works
```

If you want to make sure that no negative values are passed, maybe add a check and raise. That makes it a runtime error instead of a compile-time one, but the only reason we have unsigned types is for C interoperability, unsigned types are discouraged from regular code. They are bug-prone and unintuitive.

**Comment by Philpax** [comment]
My current project requires a fair amount of C interop. I believe your first example (two functions accepting ints) should be an error anyway - it's clearly ambiguous, and the behaviour will change depending on which platform you're compiling for. Your suggested workaround doesn't work for calling C methods unless they're wrapped, and it pokes holes in the type system (by throwing away all information about sizes).

This isn't a blocker by any means, but it is counter-intuitive behaviour (you'd expect `0` to be accepted by any method taking any variant of `[U]IntX`).

**Comment by asterite** [comment]
What is the C library you are interfacing with? Ruby also interfaces with C and it doesn't have unsigned  numbers. They probably use similar checks to the ones I propose, and in practice it works well.

**Comment by ysbaddaden** [comment]
Types are casted automatically when calling C functions, to avoid manually having to cast to the many LibC types (eg: LibC::Char, LibC::SizeT, etc.), and the following works:

```crystal
lib LibX
  fun foo(x : LibC::UInt) : LibC::Int
end

LibX.foo(0_i8)   # ok
LibX.foo(0_u16)  # ok
```

This way you don't have to worry about (un)signed integers in Crystal code.

**Comment by ozra** [comment]
@jhass, I was thinking of within "SomeInt" fitting in target data-type only... Since it's a literal fitness test is compile time...

**Comment by asterite** [comment]
This is something that for simpler integer literals can seems to be very easy to implement with a few special cases in the compiler, but can quickly get out of hands.

For example, implicit conversion from Int8 to Int16 should probably happen. But what about Int32 to BigInt? One would probably want that too. Then we'd need to improve the language with custom conversion rules. [Julia does this](http://docs.julialang.org/en/release-0.4/manual/conversion-and-promotion/), and we *could* maybe do this in the future. On the other hand being explicit is simpler and always understandable, with implicit casts one could transform any object to any other objects, not necessarily numeric types. And with anything "implicit", it makes things harder to follow and understand.

There's also the case where maybe I want to have an array of Int32 and Int8, for some reason. Would the compiler not let me do this because Int8 is implicitly castable to Int32? What happens when a type is implicitly castable to two types inside a union? The language will quickly get out of control.

So I'll close this for now.
