### ISSUE TITLE
question, dsl with method_missing and self yield

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#1808]
i am trying to build dsl: http://play.crystal-lang.org/#/r/jzg
is it possible to make `with self yield` understand method_missing?

something like ruby instance_eval(block)

**Comment by asterite** [comment]
I think we could make this work. At least it makes sense to work that way, if methods are first looked up in the `with` scope. However, the `ends_with?('=')` condition in your example will never be true because doing `a = 1` is a local variable assignment, and then if you do `self.a = 1`, `self` is not bound to the `with` scope. That is, `with ... yield` is not like Ruby's instance_eval.

**Comment by kostya** [comment]
in ruby the save `a = 1`, would local variable, but `a 1` is method call

**Comment by asterite** [comment]
Yes, what I meant is that there's no way to invoke a method that `ends_with?('=')` if you use `with ... yield`.
