### ISSUE TITLE
[RFC] URI usabilty

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#1821]
Currently usage is ugly like:

``` cr
uri = URI.new("http://example.org/foo")
client = HTTP::Client.new(uri.host.not_nil!, uri.port || 80)
client.get(uri.path || "/")

HTTP::Server.new(8080) do |request|
  if request.path.not_nil!.starts_with? "/hello"
    # ...
  else
    # ...
  end
end
```
#### path

Currently `URI#path` returns `nil` to indicate the absence of a path. [RFC 3986 Section 3.3](https://tools.ietf.org/html/rfc3986#section-3.3) states:

> A path consists of a sequence of path segments separated by a slash
>    ("/") character.  A path is always defined for a URI, though the
>    defined path may be empty (zero length).  Use of the slash character
>    to indicate hierarchy is only required when a URI will be used as the
>    context for relative references.  For example, the URI
>    mailto:fred@example.com has a path of "fred@example.com", whereas
>    the URI foo://info.example.com?fred has an empty path.

Following this by returning the empty string for path would make usage in contexts where there's a path guaranteed easier. For the client example above however, with `uri = URI.new("http://example.org")` it would break (`GET HTTP/1.1` is invalid). However `HTTP::Client` could rewrite `""` to `"/"`, curl does this too.
#### port

We could hardcode common ports matching the `protocol`. However there might be unknown protocols and thus it would remain nilable, on top of the inconsistency of sometimes returning the implicit port value. The latter inconsistency could be reduced to a minimum by parsing `/etc/services` though, perhaps even at compile time so the runtime cost is kept low.
#### `foo`, `foo?` accessors

Most usages will probably remove the nilables with runtime raising `not_nil!` calls, in particular for cases where there's no sensible default value, like `host`. Should we make this more convenient by turning all of these into `getter!`s?

**Comment by asterite** [comment]
For the client part here are two less uglier options:

```crystal
# 1.
client = HTTP::Client.new "example.org"
client.get "/foo"

# 2.
HTTP::Client.get "http://example.org/foo"
```

The thing is, if the URI is hardcoded then for the reader it's obvious that some things aren't nil, and so the `not_nil!` checks become redundant. Remove that hardcoded string and then it's worth stopping and thinking a few seconds the case where some properties might be nil.

For `request.path` I'd make `Request#path` be `"/"` when the underlying uri's path is nil. I wouldn't change `URI#path` to an empty string for the nil case. For example [OAuth::Signature](https://github.com/manastech/crystal/blob/master/src/oauth/signature.cr#L55) has to use "/" for the nil case. Maybe we can use "/" then, but I don't know if that brings another problem.

For the port, I don't know. We could make `port` raise on nil and provide `port?`, and have a hardcoded list of scheme -> default port (or even better: register that at runtime or compile time). I wouldn't use /etc/services because then a program's behaviour changes depending on the contents of that file, so programs become non-portable between different machines (the same is true for any run macro, but run macros usually use files located in the same project).

**Comment by luislavena** [comment]
@asterite 

> Maybe we can use "/" then, but I don't know if that brings another problem.

Pretty much every scenario and framework where `path` is return as empty string, it is immediately changed to `"/`" to properly workout routing and format the response.

However, URI is also used for non-hierarchical URI's (like `mailto`) where `path` being returned as `"/"` might be a problem.

**Comment by asterite** [comment]
@jhass Should we make `Request#path` return "/" if it's nil or empty then? We can do bits of this issue and relate the commits.

**Comment by jhass** [comment]
I guess that would be fine with me. I'd still also make `HTTP::Client` handle `""` as `"/"` though.

**Comment by ozra** [comment]
Perhaps it's better to opt for the "correct way" and handle it specifically when needed (OAuth etc.)?
When working with urls, when using 3rd party mods, I've grown used to use "ensure_slash" and "de_slash" depending on the case because of inconsistencies. Well.

**Comment by asterite** [comment]
Closing in favor of #4954
