### ISSUE TITLE
Force formatter output to stdout

### ISSUE THREAD

**Issue by keplersj** [crystal-lang/crystal#1863]
Being able to pass a command line parameter to spit out the formatted code to STDOUT, much like [`clang-format`](http://clang.llvm.org/docs/ClangFormat.html), would be very helpful for [`formatter`](https://github.com/atom-community/formatter) and [`formatter-crystal`](https://github.com/atom-crystal/formatter-crystal).

**Comment by asterite** [comment]
I don't know if it's of any help, but if you do `crystal tool format -` then the input is STDIN and the output is STDOUT. We use this in the sublime-crystal plugin. I guess we should also have a way to force output on STDOUT...

**Comment by kepler0** [comment]
Oh that's perfect actually. Beautiful. Thanks!

**Comment by jhass** [comment]
Let's keep this open, an option to force stdout would indeed be quite useful.

**Comment by straight-shoota** [comment]
#1874 was an implementation and got closed because there was no practical use case. Here, the code formatter for Atom is mentioned (new link: [atom-crystal/atom-crystal](https://github.com/atom-crystal/atom-crystal)). Though I am not sure if the use case is still justified.
If so, #1874 (or a new PR) should be reopened. Otherwise, this can be closed.

**Comment by straight-shoota** [comment]
The current options are either run the formatter on a bunch of files/directories or pipe from STDIN to STDOUT. That should be sufficient. If you want to get the formatter output of a file on STDOUT, you just pipe the content of the file to STDIN.
A possible improvement to that would be to make `--stdin-filename` work with the formatter.
