### ISSUE TITLE
UInt32 literals are typed as Int32 when used as enum values

### ISSUE THREAD

**Issue by mverzilli** [crystal-lang/crystal#194]
```crystal
lib LibFoo("AnyLib")
  enum Foo
    A = 0x00000001_u32
  end
end

puts LibFoo::Foo::A.class #=> Int32
```

I expected Foo::A.class to yield UInt32 instead

**Comment by fernandes** [comment]
hi, I'm trying to solve this issue, I did the test and implementation, they are ok (at least I think so), but need to define some things like, on [src/time/time.cr](https://github.com/crystal-lang/crystal/blob/master/src/time/time.cr) we have an enum like:

```crystal
enum Kind : Int64
  Unspecified = 0
  Utc         = 1
  Local       = 2
end
```

According to this issue, should break unless defined like:

```crystal
enum Kind : Int64
  Unspecified = 0_i64
  Utc         = 1_i64
  Local       = 2_i64
end
```

another possible solution is to raise the exception only when `enum_base_type` is the default `i32` and was specified another type for enum values.

Please give your thoughts then I can open the PR :)

**Comment by asterite** [comment]
@fernandes No, it should not break, it should work. The idea of writing `enum Kind : UInt64` is to say "I want the values to be UInt64", so there's really no point in repeating that information in all of the constants.

The case you fixed is important, though, because it's unexpected that `0x00000001_u32` silently changes to `Int32`. But I wouldn't worry about other combinations right now. I suspect the original error came from not knowing that you can specify the underlying type of an enum, and that all enum members have the same type.

**Comment by fernandes** [comment]
that's perfect, good to know! 👍
