### ISSUE TITLE
Weird error when subclassing Array...

### ISSUE THREAD

**Issue by Fusion** [crystal-lang/crystal#2017]
There is a non zero chance that I am not understanding some Crystal concept here so thanks in advance for your patience :/

Basically, it looks like not invoking `super` in a subclass may cause the compiler to fail the parent's initialization, even when not using the subclass.

src/i_array.cr:

    class I_Array(T) < Array(T)
      def initialize(value : Array(T))
      end
    end

ext.cr:

    require "./ext/*"
    
    module Ext
      class Test
        def do
          @myarray = [] of String
        end
      end
      Test.new.do
    end

The compiler has this to say:

    Error in ./src/ext.cr:9: instantiating 'Ext::Test#do()'
    
      Test.new.do
               ^~
    
    in ./src/ext.cr:6: instantiating 'Array(String):Class#new()'
    
          @myarray = [] of String
                     ^
    
    instantiating 'Array(String)#initialize()'
    
    type must be Int32, not (Nil | Int32)
    
    ================================================================================
    
    Error:

If I insert a call to `super` in initialize, then everything is copacetic.

I do not understand how a subclass ends up having an effect on its parent?

**Comment by asterite** [comment]
Since you are not invoking super, for example, the `@size` instance variable is not initialized and thus it becomes nilable. But [Array states that `@size` must be an Int32](https://github.com/manastech/crystal/blob/7c6dde972714cbc2a4fc744de2243298f046226e/src/array.cr#L57), so that's why you get an error.

As an aside, I wouldn't advise extending Array/Hash. I always prefer to compose these types instead of subclassing them.

**Comment by Fusion** [comment]
First, kudos for the extremely prompt reply!

Now, I understand your explanation. But as far as I am concerned, "[] of String" will return an Array, not an I_Array. I am *not* using I_Array in my code.

So, why does simply subclassing Array, then *not* using that subclass have an impact on Array?

**Comment by asterite** [comment]
Good question.

The compiler will make classes "share" instance variables in a class hierarchy. For example:

```crystal
class Foo
  getter x

  def initialize
    @x = 1
  end
end

class Bar < Foo
  def initialize
    @x = "hello"
  end
end

puts typeof(Foo.new.x)
puts typeof(Bar.new.x)
```

This will print `(String | Int32)` both times, which hints that there's only one `@x` between `Foo` and `Bar`. The compiler does this to optimize a class representation: there's only one `@x` and it has the type of everything that's assigned to it in the class hierarchy. Later if you have a `Foo+` (something that is `Foo` or one of its subclasses), accessing `@x` is just loading memory from a pointer offset. If for each type there's an `@x` in a different offset and with a different type, that would be a bit slower.

In your example in particular, `Array` states that `@size :: Int32`, and since that instance variable is shared with subclasses and you are not initializing it, you are breaking this contract.

The other reason for the above is [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle) that states that whenever you are dealing with a type T, you should be able to deal with a type `S < T` just fine. If an instance variable in a subclass changes of type, you are breaking this. Basically, if somebody was expecting an Array and you pass it an I_Array, the code will definitely not compile. We could have make it work in a different way, but this way is simpler and *makes sense*.

**Comment by Fusion** [comment]
Thank you for this detailed explanation. I have to say, this is not the first time that Crystal's compiler returns an error message that requires a bit of head scratching.

You may think I am complaining but in fact, I am happy with this behavior: Crystal performing type inference at compile time means that I get to write ruby-like code without the pitfalls :)

**Comment by asterite** [comment]
Error messages can definitely be improved. I just realized that the error message doesn't mention the `@size` variable. I'll try to fix it.

**Comment by javajax** [comment]
I am just poking around in the backlog.
Is there a followup to this or can it be closed?

**Comment by Fusion** [comment]
A good reference to Liskov's substitution principle. You can close this issue, I believe.

**Comment by asterite** [comment]
Now the compiler gives this error message:

```
Error in ./foo.cr:2: this 'initialize' doesn't initialize instance variable '@size', rendering it nilable

  def initialize(value : Array(T))
      ^~~~~~~~~~
```

So I believe the error message is now much clearer than before :-)
