### ISSUE TITLE
Spawning too many Fibers chokes the system

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#2045]
While experimenting with `spawn` and `Fiber` I wondered if it's cheap or not.

First i tried spawning 100K which actually does nothing.

```crystal
1_000_00.times do
  spawn do
      
  end
end
```
This was pretty cheap.

```
time ./spawn
./spawn  0.24s user 0.57s system 99% cpu 0.816 total
```

Seeing that i thought spawning 1MM would be a piece of cake but i was wrong.

```
time ./spawn
./spawn  4.00s user 30.66s system 48% cpu 1:11.87 total
```
P.S: This consumes around 3.5G of memory.

I really wonder why is it like this? Is spawning too much `Fiber`s actually choking the OS threads or so?

**Comment by waj** [comment]
I tried the same on my machine but it didn't take that much time. What are your hardware and OS specs? Is this with the latest release? Can you try on master?

Each fiber consumes at least 4K, so to get 1MM fibers running at the same time, at least 4GB are required.

**Comment by sdogruyol** [comment]
Crystal Version: 0.10.2
Os: OS X El Capitan
Hardware: 2013 Macbook pro 2ghz i7 8gb ram

When i ran the script i had like 5gb of ram free. I'll try with Crystal master and let you know the results

**Comment by sdogruyol** [comment]
Trying with Crystal 0.10.2 [aa043bb] (Fri Jan 22 05:33:25 UTC 2016)

```
time ./spawn_master
./spawn_master  2.58s user 54.06s system 62% cpu 1:30.27 total
```

I watched the process from start to end (with Activity monitor) and after 4G it goes to swap memory and later the OS kills the process before completing.

**Comment by sdogruyol** [comment]
Update

I also tried this on a 2015 Macbook Pro with 16G of ram. The same happened when the process hits 4G of memory it got killed by the OS before finishing. (meanwhile i still had like 2G of free ram)

Maybe this is OS specific?

**Comment by waj** [comment]
I also have a MBP with 16GB and with 1 million fibers it worked just fine (ending in 8 seconds). I had to raise the number and mine got stuck around 2 million fibers. The memory allocation get slower and slower as the number of fibers increased. Aproaching to 2 MM it was impossibly slow. I need to research in that area to improve the situation.

How do you know the OS killed the process? Do you get any error message? (you can check in Console.app)

**Comment by sdogruyol** [comment]
Actually this has to do with yielding nothing in `spawn` fiber.

To prove this i've done 

```crystal
channel = Channel(String).new
1_000_000.times do |i|
  spawn {
    channel.send "Hello #{i}"
  }
  puts channel.receive
end
```

And this completes without any problems.

`./spawn  2.90s user 2.85s system 98% cpu 5.843 total`

WDYT @waj?

**Comment by waj** [comment]
Well, the difference is that in the first example, all the fibers are initialized without giving them a chance to execute, so all of them exist in memory at the same time.
In your last example, because you use the channel, the main fiber is interrupted and the new fibers are executed. When they finish, the memory is reclaimed or reused for other fibers. In other words, at any time only a few fibers are alive in memory.

I'm pretty sure all this has to do with the big memory allocation that a large number of fibers require. As soon as the OS starts swaping fibers stacks to disk, the performance will drop dramatically. Of course there might be many optimizations opportunities, that could increase the number of fibers that a certain system is capable to handle, but there is going to be always a limit.

**Comment by jhass** [comment]
I see no clear proposal  or bug report here, closing.
