### ISSUE TITLE
Make Fibers more portable?

### ISSUE THREAD

**Issue by Fusion** [crystal-lang/crystal#2072]
Hi,

Excited about Crystal 0.11.0. However, the new stack switch function saddens me as it has been my hope that Crystal would be moving in a more architecture-agnostic direction, allowing use in embedded development, more specifically on ARM architectures.

A quick proposal: how about using contexts instead, thus leaving assembly code to the underlying libraries? I wrote a blog post on this topic a couple years ago:

http://nexus.zteo.com/blog/c-coroutines-no-assembly-bad-pun-required/

It has the advantage of saving not just the stack but the registers as well.

If you feel that it's not a direction you would like to go, how about, then, adding it in a "else" guard matching your "ifdef x86_64" sections? (Obviously some more changes would be necessary to reconcile stack v. context elsewhere in that file)

Thanks

**Comment by waj** [comment]
Hi @Fusion! 

Before me moved to use custom inline assembly, Crystal was using [libpcl](http://www.xmailserver.org/libpcl.html). Underneath, it uses contexts or setjmp/longjmp depending on the platform. It happens to be much more portable (well... is in the name of the library, isn't it? :) ) but it's also much slower that our current implementation.

At first I though it wanted to still use libpcl for other architectures besides x86 and x86-64, but the truth is, in order to support other platforms or architectures, much more work is required than just that small function with just a few assembly lines. In other words, to make Crystal work on ARM, writing the switch function for these CPUs would be a very small percentage of the required effort.

Also, I think is particularly important for embedded platforms to be as efficient as possible. So is for these architectures where a more custom and tuned context switch would be desirable.

**Comment by asterite** [comment]
I don't think we'll make Fibers more portable. Fibers are something that must be really fast, and the fastest way is to use inline assembly. It does mean we'll have to write a few assembly when porting to other platforms, but this is better than having a slow runtime.
