### ISSUE TITLE
`run(filename, args)` macro does not work with shard paths

### ISSUE THREAD

**Issue by jeromegn** [crystal-lang/crystal#2127]
**Note:** I'm encountering this in my `Slang` shard, at this line: https://github.com/jeromegn/slang/blob/master/src/slang/macros.cr#L2

It appears that the run macro can't find paths from shards, only relative paths.

When I'm working on it locally, I use a different path, a path relative to where the file I'm running resides.

For instance if I'm running it from my examples folder, I need to change the path to `../src/slang/process` or else it bombs with:

```
expanding macro
in macro 'embed_slang' /Users/jgn/projects/jeromegn/slang/src/slang/macros.cr:1, line 1:

  1.   {{ run("slang/process", "basic.slang", "__slang__") }}

  {{ run("slang/process", "basic.slang", "__slang__") }}
     ^~~

error executing macro run: can't find file 'slang/process' relative to '/Users/jgn/projects/jeromegn/slang/examples'
```

I tried adding a symlink (`examples/libs/slang` as I was suggested to) but that didn't help.

I thought my code would work since this works: https://github.com/manastech/crystal/blob/938a083906057fb21c3ac0e64249527e5621746d/src/ecr/macros.cr#L2

But I think this might just work because of how Crystal resolves paths.

Any idea?

**Comment by asterite** [comment]
Hm, it seems to work if I change it to "slang/slang/process". It works with "ecr/process" because we have "src/ecr/process.cr". In your case it's more like "libs/slang/slang/process.cr" and it can't deduce that from just "slang/process".

I also tried changing it to this:

```crystal
macro embed_slang(filename, io_name)
  {% process = "#{__DIR__}/process.cr" %}
  \{{ run({{process}}, {{filename}}, {{io_name}}) }}
end
```

but it doesn't work: run doesn't let you use absolute paths. Maybe it should. In that case `__DIR__` is processed when the macro is invoked and has the directory where that macro is defined, so we can go from there to `process.cr`. That's the way it will always work, since it's a relative path, and we could do the same with ecr, but I'll need to fix that in the compiler.

That is, unless we find another way to do this...

**Comment by jeromegn** [comment]
Thanks, I updated my shard. Looks like this works! Great start.

Yes, if run could just check for a leading `/`, it would know not to try to resolve the path relatively.

**Comment by asterite** [comment]
@jeromegn This will be fixed in the next release. You'll be able to solve it with:

```crystal
macro embed_slang(filename, io_name)
  \{{ run("{{__DIR__.id}}/process", {{filename}}, {{io_name}}) }}
end
```

`__DIR__` will be expanded to the directory where that macro is defined, and if a `process.cr` file is in that directory, it will work. So it will work if used from a shard, or used via `require "./src/slang"`.

**Comment by ysbaddaden** [comment]
BTW the Ruby like way of having library files under `lib/slang` isn't working great with Crystal and Shards. Files should be directly in `src` so when installed they'll be available as `slang/process` instead of `slang/slang/process` which is kind of repetitive.

**Comment by asterite** [comment]
@ysbaddaden How can we fix that? One idea we had was putting the `src` directory inside `lib`, so you'd end up with:

- lib
  - slang
    - src
      - slang
        - process.cr

Then we also change how `require` works. If you do `require "slang/process"` it will also check `slang/src/slang/process` in CRYSTAL_PATH. If you do `require "slang"` then it will also check `slang/src/slang`, etc. A bit of this is described [here](https://github.com/crystal-lang/crystal/wiki/Roadmap#package-manager), though I'm not sure I like that solution, but I'd use it if we don't come up with a better one.

**Comment by ysbaddaden** [comment]
I like that we don't have to mimic the rubygems convention of puting library files under a `lib/name` folder to "namespace" the files. I really prefer having files righ under `src`, the shard itself acts as the "namespace" (hey, cool).

The one thing that could change is for `require "name/foo"` to also look for `libs/name/src/foo` so Shards could link the shard root folder as `libs/name` instead of just its `src` directory. That could simplify a few things, and allow shards to have data outside the `src` folder.

**Comment by asterite** [comment]
@ysbaddaden If you want and have time, since you are the shards master, you can toy with how `require` is resolved. The logic is [here](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/crystal_path.cr#L11). That way you can check different layouts for how shards are put inside the `libs` directory and check that `require` works for different uses cases. The current code is a bit messy, and it predates the powerful Dir.glob, so if you also find something to improve it's readability, it'll be very welcome :-)
