### ISSUE TITLE
Reliable Nightly builds

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#2204]
Hello folks,

In the light of pre-1.0 changes coming to Crystal, I personally use nightly builds when testing locally and against Travis and Drone CIs.

At this time the last nightly build for Debian/Ubuntu was based against commit c4d47ea.

While I know is possible to produce manual builds, I'm interested in understand the build infrastructure being used for the nightly builds and perhaps contribute either with time or resources to ensure they remain up-to-date.

Opening this issue so we can coordinate an discuss.

Thank you in advance for your responses.
:heart: :heart: :heart:

**Comment by jhass** [comment]
The nightlies are built using omnibus inside some docker containers, using this fork of the omnibus project: https://github.com/jhass/omnibus-crystal/tree/nightly_build

Since I don't actually use them myself, I don't really notice when they break, something that could help would be a munin plugin or something else that monitors them and can send a notification in case they fall behind. Note they're built only once a day.

One issue is that upstream never merged [my changes](https://github.com/manastech/omnibus-crystal/pull/4), so it's hard to keep necessary changes to the omnibus project in sync.

**Comment by asterite** [comment]
@jhass I just moved the omnibus-crystal project to the crystal-lang organization. Then I'll give you access and you can rebase and merge the changes.

**Comment by jhass** [comment]
No real discussion happening, closing for now.
