### ISSUE TITLE
Initialize StaticArray (or Slice) *with* static contents

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#2229]
With current Crystal, we can easily initialize an Array with `a = UInt8[1, 2, 3]` which initializes an Array(UInt8) with 3 elements (already casted from Int32 to UInt8, sweet).

I found myself from times to times to want to initialize an StaticArray(UInt8) because I need/want capacity to change and prefer a static pointer to memory. Yet, it's quite difficult to achieve.

Example uses cases:
- blowfish tables for BCrypt;
- quickly initialize a Slice (StaticArray#to_slice exists, but Array#to_slice doesn't, because an array can be resized, thus realloc'd and moved into the memory space).

Proposed syntaxes:

- `UInt8[1, 2, 3]` could instead initialize a StaticArray(UInt8) instead of an Array(UInt8), which would allow to have both the `.to_a` and `.to_slice` methods (con: may break a bunch of code that expect an Array);
- we could extend the syntax with `Slice(UInt8)[1, 2, 3]` or `StaticArray(UInt8)[1, 2, 3]` (pro: won't break anything, don't need to transform the static array).

**Comment by bcardiff** [comment]
A while I ago I wanted to have the ability to define readonly blobs in a data section.
If you are only interested in UInt8 data, the scenario might be the same.

I think @waj suggested back then something similar to `0x...some variable length hex dump...`, which I dream to use it as a way to embed file content with a macro for example in data section.

**Comment by ysbaddaden** [comment]
Indeed, having hexstring blobs parsed at compile time would be lovely.

**Comment by asterite** [comment]
For readonly data we probably need a new language construct. One idea that we had, some time ago, was something like:

```crystal
const [1, 2, 3]
```

That would create a `StaticArray(Int32, 3)` (or maybe `ConstStaticArray(Int32, 3)`, since it can't be modified?) in the data section of the program.

However, it's sometimes also useful to create static arrays or slices with runtime data, and it would be nice to have a syntax or method for this.

I think I'd like to keep `UInt8[1, 2, 3]` returning an Array, because Array is the recommended container to use in most cases: Slice and StaticArray are more low-level and are usually used when interfacing with C or when writing protocols, so they are used less.

For Slice we can have `Slice(UInt8).[1, 2, 3]`, the implementation is easy: https://play.crystal-lang.org/#/r/t7c . This casts the values using `T.new`, similar to `Number.[]`.

If we want T to be inferred from the values, we probably need another method name. Right now there's no way to know if the method is being invoked on the uninstantiated generic type, or the instantiated one.

For StaticArray it's a bit more tricky, because `StaticArray(UInt8)[1, 2, 3]` won't work: StaticArray has two type arguments, so you'd need to do something like `StaticArray(UInt8, 3)[1, 2, 3]`, which is a bit tedious. If we try to implement it with a method it becomes tricky because there's no way to get the size of a tuple at compile time (try to implement it and you'll see). However, we can use a macro for this... the problem is, `[]` isn't accept as a macro name right now, but we can add that, so doing `StaticArray[1, 2, 3]` works as expected. Then we could have another macro like `StaticArray.of UInt8, 1, 2, 3` which would do the cast: https://play.crystal-lang.org/#/r/t7m

**Comment by bcardiff** [comment]
@asterite I like making `[]` a valid macro name. Since it's a method name, it should be also a macro.
I would wait for that and using the same syntax for StaticArray and Slice. So we get the element type inference.

As for the const, it is nice, but can be pushed a bit further for sure. "Phoenix" data sections, will come again.

**Comment by ozra** [comment]
+1 on data section happiness.

@bcardiff - what's "Phoenix" data sections?

**Comment by bcardiff** [comment]
I was expressing desire for them to come back, as the [phoenix bird](https://en.wikipedia.org/wiki/Phoenix_(mythology)).

**Comment by ozra** [comment]
Ah, silly me!
