### ISSUE TITLE
Continous integration against musl-libc

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2275]
With #2124 merged, we should ensure we don't break it, especially since it's an uncommon target to test against locally.

This should be as easy as creating and maintaining a docker image and adding a build on Travis using it.

**Comment by luislavena** [comment]
If I'm not mistaken, we will need a static version of the compiler be available in order to bootstrap the compilation itself.

That compiler might need to be updated from time to time to keep up with breaking changes and such.

@ysbaddaden perhaps you can provide here the instructions necessary to produce the static compiler on a glibc-based distro? That way we can produce from an Ubuntu/Debian docker the bootstrap compiler that will be used to build the base image?

**Comment by jhass** [comment]
Yes, that's right. I guess ideally we would add it one to the omnibus builds.

**Comment by ysbaddaden** [comment]
No need to bootstrap the compiler anymore, an Alpine Linux package is available (temporary location): https://dl.dropboxusercontent.com/u/53345358/alpine/setup.txt which I intend to use to build new releases of Crystal.

**Comment by asterite** [comment]
@ysbaddaden Can we maybe put it as a download in the [releases](https://github.com/crystal-lang/crystal/releases/tag/0.12.0) section of 0.12.0? Then yes, I guess we would need to modify omnibus to support this, and from this release on we'll provide Alpine Linux packages.

**Comment by luislavena** [comment]
@ysbaddaden thank you. Can you share the `APKBUILD` script you're using also? Are you building boehm gc also as part of the package (as static lib)?

**Comment by ysbaddaden** [comment]
I'm still working on the APKBUILD. I'm trying to follow Alpine Linux guidelines: have smallest possible packages. So I now have a patched `gc` package (7.4.2 + patch to make `GC_push_all_eager` public), a `crystal` package (crystal shared binary + `src`) and a `shards` packages (only the shared binary). I'll eventually try to send the patch for libgc as well as the crystal/shards APKBUILD to Alpine Linux maintainers, see if they accept it or not.

I'm not sure how the omnibus works. It must be run on a musl-based system to produce Alpine packages. It may be great to reduce requirements and overall size. For instance my current crystal binary only weights 7MB, but requires to pull in llvm-libs, libncurses, and all other libraries, which is quite a lot in the end.

Things to consider:
- Alpine Linux doesn't provide static `.a` libraries for some libraries (eg: libevent, libgc, llvm).
- I believe we can't `apk add crystal.apk`. AFAIK it requires signed packages to be intalled from a repository. For example abuild always creates/updates `APKINDEX.tar.gz` with the list of signed packages, and will refuse considering the repository, and thus its packages, until the signature can be verified and is valid.
- We can't have `/usr/local` or `/opt` in packages, `abuild` merely refuses it. I'm working around this by pushing `crystal` (shell) and `crystal-binary` into `/usr/bin` and the `src` as `/usr/lib/crystal/src`.

**Comment by jhass** [comment]
[Here's](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/crystal#n57) the layout we use for the Arch packages for reference.

**Comment by Lukc** [comment]
Any news on this?

Does anyone have access to a crystal binary for Alpine?

**Comment by ysbaddaden** [comment]
@Lucz https://dl.dropboxusercontent.com/u/53345358/alpine/setup.txt

**Comment by asterite** [comment]
@ysbaddaden I think @waj followed those steps without success, not sure what was the reason or where he got stuck. Any reason why we can't put some kind of released version (.tar.gz) in the releases page for Alpine?

**Comment by ysbaddaden** [comment]
In order to distribute a tarball, we'll need the omnibus, to build (with specific flags) and distribute all dependencies. One bonus is that we could build a truly static version of Crystal for Linux. We can't now because Alpine doesn't distribute many static libraries, and is shared libraries oriented.

The quickest route was to provide official packages and a repository to distribute. Actually, building a package always generates a repository, and I didn't find a way to install an APK directly.

I'll need more info about where it failed when following instructions. I'm using Alpine 3.3. Under edge, one must pin the LLVM package versions. Maybe this is it?

**Comment by ozra** [comment]
The only static libs for LLVM I found for Alpine was 3.8, it sure would be nice to get that working for Crystal. Hmm...

**Comment by straight-shoota** [comment]
Fixed by #7420
