### ISSUE TITLE
Lacks a lead byte when write(2) by syscall intstruction

### ISSUE THREAD

**Issue by kubo39** [crystal-lang/crystal#2277]
I encountered this behavior. (Yes, I know it's very unsafe code..

```crystal
class String
  def to_unsafe
    pointerof(@a)
  end
end

def syswrite
  dst = 0_u64
  write = 1_u64
  b = "Hello!\n".to_unsafe
  asm("syscall" : "={rax}"(dst)
      : "{rax}"(write), "{rdi}"(1), "{rsi}"(b), "{rdx}"(7)
      : "rcx", "r11", "memory"
      : "volatile")
end

def sysexit
  dst = 0_u64
  exit = 60_u64
  asm("syscall" : "={rax}"(dst)
      : "{rax}"(exit), "{rdi}"(0)
      : "rcx", "r11", "memory"
      : "volatile")
end

def __main
  syswrite; sysexit
end

# crystal build hello.cr --emit obj --prelude=empty
# ld hello.o -o hello -e main
# ./hello

__main #=> ello!
```

I'm not sure it is expected behavior or a bug, can anyone advise me?

my crystal version && environment.

```
$ crystal --version
Crystal 0.12.0 [90eaec1] (Tue Feb 16 14:31:00 UTC 2016)
$ uname -mrv
3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64
$ cat /etc/issue
Ubuntu 14.04.4 LTS \n \l
```

**Comment by jhass** [comment]
It works with `pointerof(@c)`, as in the original [String implementation](https://github.com/crystal-lang/crystal/blob/master/src/string.cr#L2932). Looks like `@a` just happened to point somewhere below that.

**Comment by asterite** [comment]
This actually makes total sense :-)

String's instance variables are:

```
+- class String (16 bytes)
       @bytesize : Int32 (4 bytes)
       @length   : Int32 (4 bytes)
       @c        : UInt8 (1 bytes)
```

The `@c` is actually the first character of the string, because its data is "inlined" in memory. We don't want `@c` to be `Pointer(UInt8)` because that would be an extra indirection. It's a little trick.

So, in your code you are defining a new variable, `@a`. The compiler will assign the `Nil` type to it because you never assign it a value. Its position will be one byte after `@c`, so it will point to the second byte in the string.

**Comment by kubo39** [comment]
@jhass @asterite 
Thank you for answering my question.

> The `@c` is actually the first character of the string, because its data is "inlined" in memory.

It's interesting! For less memory access?

Anyway, it's not bug. I close this.
