### ISSUE TITLE
Expected STDERR be flushed at program termination

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#2290]
The following program never outputs contents sent to `STDERR` unless `#flush` is called:

```crystal
STDOUT.puts "out" # at exit, this shows
STDERR.puts "err" # does not show unless `STDERR.flush`
```

Looking at the code, seems only when `exit` is called, STDERR is flushed.

And `redefine_main` macro only flushes `STDOUT` for regular termination.

Was this done for a particular reason? If not, I can send a pull request! :smile: 

Thank you :heart: :heart: :heart:

**Comment by asterite** [comment]
@luislavena Hi! Yes, it makes total sense. I made the change because it's just one line :-)

A second question that we were discussing with @waj is: should we set `STDERR.sync = true` at startup? At least in Ruby it's true. The same goes for STDOUT in Ruby, though in Crystal we don't do that. Instead, we make the top-level `puts` and `print` always flush, so console apps see the texts immediately. Still, the question remains about what to do with STDERR. Thoughts?

**Comment by luislavena** [comment]
@asterite a good set of questions, basically I found this issue when working on adding some deprecation warnings for a upcoming release of Radix and want to show that so on next release I can remove the code and throw an error.

On Ruby I got used to `warn` and the immediate flush.

It makes sense that `STDERR` is flushed right away, so when used to show errors is closer to the output that originated the error and not when the program exits.

Cheers.
