### ISSUE TITLE
undefined method 'key' for Array(JSON::Type)

### ISSUE THREAD

**Issue by kuraga** [crystal-lang/crystal#2300]
```crystal
# error doesn't occur on using Hash
require "simple_hash"
require "json"

# error doesn't occur on removing "?"'
alias Answer = (String | Array(String))?

class Storage

  @sample : SimpleHash(String, SimpleHash(String, Answer))

  def initialize
    @sample = SimpleHash(String, SimpleHash(String, Answer)).new
  end

  getter sample

  def load(file_name : String) : Nil
    json = File.read file_name
    # error doesn't occur on replacing Answer
    @sample[file_name] = SimpleHash(String, Answer).new JSON.parse(json).as_h.values
    nil
  end

end

storage = Storage.new
# error doesn't occur on removing next line
storage.load "input"

s = SimpleHash(String, Array(String) | String | Nil).new
p s
```
```
Error in ./t.cr:32: instantiating 'p(SimpleHash(String, Array(String) | String | Nil))'

p s
^

in /opt/crystal/src/kernel.cr:75: instantiating 'SimpleHash(String, Array(String) | String | Nil)#inspect(IO::FileDescriptor)'

  object.inspect(STDOUT)
         ^~~~~~~

in /opt/crystal/src/simple_hash.cr:142: instantiating 'to_s(IO::FileDescriptor)'

    to_s(io)
    ^~~~

in /opt/crystal/src/simple_hash.cr:147: instantiating '(Array(JSON::Type) | Array(SimpleHash::Entry(String, Array(String) | String | Nil)))#each_with_index()'

    @values.each_with_index do |entry, index|
            ^~~~~~~~~~~~~~~

in /opt/crystal/src/enumerable.cr:191: instantiating 'each()'

    each do |elem|
    ^~~~

in /opt/crystal/src/array.cr:776: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /opt/crystal/src/array.cr:776: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /opt/crystal/src/enumerable.cr:191: instantiating 'each()'

    each do |elem|
    ^~~~

in /opt/crystal/src/simple_hash.cr:147: instantiating '(Array(JSON::Type) | Array(SimpleHash::Entry(String, Array(String) | String | Nil)))#each_with_index()'

    @values.each_with_index do |entry, index|
            ^~~~~~~~~~~~~~~

in /opt/crystal/src/simple_hash.cr:148: undefined method 'key' for Array(JSON::Type) (compile-time type is (Array(JSON::Type) | Bool | Float64 | Hash(String, JSON::Type) | Int64 | String | Nil))

      entry.key.inspect(io)
            ^~~

================================================================================

Array(JSON::Type) trace:

  /opt/crystal/src/simple_hash.cr:147

        @values.each_with_index do |entry, index|
                                    ^~~~~

  /opt/crystal/src/enumerable.cr:192

          yield elem, i
                ^~~~

  /opt/crystal/src/enumerable.cr:191

        each do |elem|
                 ^~~~

  /opt/crystal/src/array.cr:777

          yield @buffer[i]
                       ^

  /opt/crystal/src/pointer.cr:116

      def [](offset)
          ^~

  /opt/crystal/src/pointer.cr:117

        (self + offset).value
                        ^~~~~
```

**Comment by asterite** [comment]
`JSON.parse(json).as_h.values` has type `Array(JSON::Type)`, and SimpleHash.new expects an `Array(Entry(K, V))`. It works with `Hash` because the constructor expects a default value and right now I think it's not restricted to any type. So, the constructors are different.

What's your problem to solve?

**Comment by kuraga** [comment]
Why problem occurs in p (not before)?

**Comment by asterite** [comment]
@kuraga Because when you create a SimpleHash with those values nothing "bad" happens. It's only when you use it (invoke a method on it) that the compiler figures there's something wrong.

For example:

```crystal
def foo
  1 + "hello"
end

# foo
```

The above compiles just fine, but if you uncomment the last line you'll get an error. That's the way Crystal works (in a way, similar to Ruby)

**Comment by kuraga** [comment]
Ok, thanks very much!

**Comment by kuraga** [comment]
@asterite, so isn't a way to catch every *possible* type error (such as in your code above) at *compile time*, is it?

**Comment by jhass** [comment]
It would be a bit inconsistent, take
```cr
def foo(bar)
  bar + 1
end
```

here the compiler needs to have at least one call to `foo` in order to know the type of `bar`, so it's impossible to check unless it's called. "Only typecheck when called" is just the much simpler rule opposed to "typecheck when there are no arguments without a type restriction", for both, the compiler and the human.

**Comment by kuraga** [comment]
@jhass big thanks! But is the below code else, no?.. Types of `1` and `"hello"` are restricted, aren't they?
```crystal
def foo
  1 + "hello"
end
```

**Comment by jhass** [comment]
I think you entirely missed my point and I'm unsure how to put it more clearly :)  You're still wishing for the rule I made up, while I was trying to explain why the former rule is in place.

**Comment by kuraga** [comment]
Ok, but why there is *one* rule only for *two different* (imho) situations?

**Comment by asterite** [comment]
There's only one rule: methods are typed when they are invoked

**Comment by kuraga** [comment]
1) So isn't a way to catch every *possible* type error (such as in your code above) at *compile time*?
2) (ritorical) Isn't it bad to catch errors on in invokations only? When is it helpful?

**Comment by asterite** [comment]
1) Yes, invoke the function. If you have an error in a function you don't use then there's no error. Of course that function might be part of a library. In that case, you are probably missing a test for that function. So, in a way, the language kind of asks you to test stuff to see it works. (you can always do a "typeof" test, that only checks that a method compiles.
2) We could type methods that don't have arguments, but that's it. In the general case there's no way to do it because we don't know the type of arguments (and even if they have a type restriction, it's just a restriction, not the final type)

**Comment by jhass** [comment]
2) continued... and as I said doing so as it's inconsistent, leads to slower compiler and has a more complex implementation.

**Comment by kuraga** [comment]
Thanks very much!

**Comment by kuraga** [comment]
Now I see: I confused static typing and strong typing :smile:
