### ISSUE TITLE
Check for format in specs.

### ISSUE THREAD

**Issue by MaloJaffre** [crystal-lang/crystal#2328]
We can add a check in specs for ```crystal tool format``` output. We can so:
- spot bugs in formatter (e. g. #2325, #2326, #2327).
- have a repository in a clean state while coding (it's annoying to revert  unrelated formatter fixes).
- check PRs format easily.

**Comment by asterite** [comment]
It's a really good idea. Maybe we can add `crystal tool format --check`, which basically formats everything and returns `0` if no changes were made, and `1` otherwise (and prints an error). We can then be sure that our commits are always formatted, otherwise the build will break. And PR will also fail if they are not properly formatted.

What do you think?

**Comment by MaloJaffre** [comment]
I think we can implement this, but returns 2 when there is a internal formatter bug.
