### ISSUE TITLE
Formatter should keep all trailing newlines (Was: Formatter removes end of file newlines.)

### ISSUE THREAD

**Issue by vjdhama** [crystal-lang/crystal#2360]
I tend to leave a newline at the end of files. I ran `crystal tool format` on my project and it removed the newline at the end, for all the files. I that desired behavior? 

I personally think it shouldn't. WDYT?

**Comment by waj** [comment]
The formatter ensures there is a newline at the end, but only one newline. Do you leave an extra empty line? is that what you mean?

**Comment by vjdhama** [comment]
Yes I left an empty line.
If this is the content of file, 

```
class Foo
end

```

it changes to

```
class Foo
end
```

**Comment by luislavena** [comment]
Hello,

I can confirm this:

```
$ cat foo.cr 
class Foo
end




$ wc -l foo.cr 
6 foo.cr
$ crystal tool format foo.cr
$ wc -l foo.cr 
2 foo.cr
$ cat foo.cr 
class Foo
end
$
```

**Comment by luislavena** [comment]
It seems that formatting within Sublime Text and combined with new line option in the editor it always includes a new line, but only in that context, not from the terminal.

Cheers.

**Comment by waj** [comment]
@luislavena Your example shows the formatter leaves a newline at the end (but only one). Otherwise the prompt would be in the same line as the `end`.
Personally I think this is the expected behaviour.

**Comment by luislavena** [comment]
@waj you're correct. I think the problem is the interpretation of what is considered *a new line*

Just for the sake of clarification:

```
class Foo\n
end\n
```

That, according to Git, is a proper terminated file (there is a new line indicator at the end of the file, as expected).

Now, editors like Sublime will show a new line (3rd) when there isn't actually one, just because the presence of `\n` in the last line

![screenshot from 2016-03-24 15-53-06](https://cloud.githubusercontent.com/assets/4182/14027883/96265a96-f1d8-11e5-8c50-2b915491e815.png)

So that could be the root of the confusion. I personally have Sublime Text setting to add new line at the end (to avoid GCC and Git to complain about it) and when used the formatter, never got a complain from Git about missing the new line.

@vjdhama can you tell us which editor are you using that is presenting this issue? or perhaps is that you prefer to end the file with 2 new lines?

```
class Foo\n
end\n
\n
```

Cheers.

**Comment by waj** [comment]
It depends on the interpretation of the newline character. Some editors (Vi) assume the `\n` is the end of the line. For others (Sublime) is the beginning of a new one.

Most editors have the option to add a missing newline at the end of the file while saving. In Vi you wouldn't notice the difference, besides the `[noeol]` in the status bar. In Sublime, if you have two newlines that means there will be lines 3 and 4 empty. That's why I think having only one newline at the end is the right way to format the files.

**Comment by vjdhama** [comment]
@luislavena I am using vim and I think issue is actually non-existent as @waj described. I checked now, that it renders fine in sublime and also git didn't complain, that means there actually no issues. It's just the vim thingy, that got me confused. Thanks guys.
