### ISSUE TITLE
How do you insert into string?

### ISSUE THREAD

**Issue by TyanNN** [crystal-lang/crystal#2409]
Something like String.insert(where to insert, string to insert)?

**Comment by jhass** [comment]
Strings are immutable by design in Crystal.

To create a new string you can for example do something like `"#{string[0..where_to_insert]}#{string_to_insert}#{string[where_to_insert..-1]}"` for now. Though I agree we miss a method to create a new string with another string inserted at a certain place.

**Comment by TyanNN** [comment]
@jhass thanks, i'll use that for now.

**Comment by asterite** [comment]
Indeed, it's a useful method, I remember doing that interpolation a couple of times now so it would be good to have it in the standard library (it can also be done in a bit more efficient way then using an interpolation).

I think `insert` might be a good name. Strings are known to be immutable in Crystal and we already have methods like `chomp`, `chop` and `delete` that would suggest that the string is modified but of course a copy is returned.

@jhass @TyanNN what do you think?

**Comment by TyanNN** [comment]
@asterite nice, thanks!

**Comment by sdogruyol** [comment]
@asterite nice one :+1:

**Comment by handicraftsman** [comment]
As always - string are immutable :smile:
