### ISSUE TITLE
Comparable(T) and Ints becoming references? 

### ISSUE THREAD

**Issue by will** [crystal-lang/crystal#2461]
``` crystal
class Foo
  include Comparable(Int)

  def <=>(other : Int)
    0
  end
end

struct Int
  include Comparable(Foo)

  def <=>(other : Foo)
    -(other <=> self)
  end
end

# p Foo.new == 3
p 3 == Foo.new
```

if you uncomment that you get 
```
Error in ./a.cr:17: instantiating 'Foo#==(Int32)'

p Foo.new == 3
          ^

in /usr/local/Cellar/crystal-lang/0.15.0/src/comparable.cr:23: no overload matches 'Foo#same?' with type Int32
Overloads are:
 - Reference#same?(other : Reference)
 - Reference#same?(other : Nil)

      return true if self.same?(other)
                          ^~~~~
```

I'm sure I'm missing something, but in comparable, `#==` is 
``` crystal
  # Compares this object to *other* based on the receiver’s `<=>` method, returning `true` if it returns `0`.
  # Also returns `true` if this and `other` are the same object.
  def ==(other : T)
    if self.is_a?(Reference) && (other.is_a?(Reference) || other.is_a?(Nil))
      return true if self.same?(other)
    end

    (self <=> other) == 0
  end
```

and somehow `(other.is_a?(Reference) || other.is_a?(Nil))` must be `true` with `0`, but ints are structs so I'm super confused.

**Comment by kumpelblase2** [comment]
https://carc.in/#/r/wqj
Using the spaceship operator you can define order between objects (as in, is this one bigger or smaller than the other), but not equality. Even if it returns 0 (so they are, from an order perspective, the same), they do not have to be equal. So you'd have to specifically overwrite the `#==` method, too, to get your desired behavior.

**Comment by asterite** [comment]
I was able to reduce it to this:

```crystal
a = "foo"
other = 3
if a.is_a?(Reference) && (other.is_a?(Reference) || other.is_a?(Nil))
  a.same?(other)
end
```

The main problem is that right now the compiler doesn't do type filtering in the `||` operator. The check `other.is_a?(Reference) || other.is_a?(Nil)` won't restrict `other`'s type inside the `if`. Also doing `other.is_a?(Reference | Nil)` doesn't work because you can't use `Reference` in a union type right now.

So, this is something to improve in the language :-)

For now, as a workaround, I'll change Comparable to make two comparisons, one against `Reference` and another against `Nil`.

**Comment by will** [comment]
Cool, thanks
