### ISSUE TITLE
Chained assigns confuses ivar inference (latest master)

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2467]
Neither of these two works (exact same cause, but...), although it reasonably should:

```crystal
class Foo
   def initialize()
      @foo = 47
      @bar = bar = 47
   end
end

foo = Foo.new
```

```crystal
class Bar
   def initialize()
      foo = @foo = 47
      @bar = foo
   end
end

bar = Bar.new
```

**Comment by asterite** [comment]
I'll make it work for the first snippet because one can easily guess the type of `@bar` from an assignment to a local variable by using the right hand side.

The second case is harder, it requires the guesser to keep track of what was assigned to local variables, so it requires flow logic. This makes the algorithm much complex (for a computer as well as for a human), so a type annotation will be required there (I won't improve this).

You can write the second case like this:

```crystal
class Bar
  def initialize
    foo = @bar = @foo = 47
    # use foo
  end
end
```
