### ISSUE TITLE
Add BigFloat

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2474]
Similar to [BigInt](https://github.com/crystal-lang/crystal/blob/master/src/big_int/big_int.cr) and [BigRational](https://github.com/crystal-lang/crystal/blob/master/src/big_rational.cr), it would be nice to have `BigFloat` based on [GMP's float](https://gmplib.org/manual/Floating_002dpoint-Functions.html).

With that type, "big" types in the standard library will be complete.

If anyone has GMP knowledge and knows how to do it, go ahead :-)

**Comment by Exilor** [comment]
The gist I linked at #574 might save some work to whomever attempts to implement it.

**Comment by ozra** [comment]
Decimal (fixedpoint with base-10 scaled fraction) and BigDecimal and it would be complete :-)

**Comment by asterite** [comment]
`BigFloat` is `BigDecimal`. C# has `decimal` type, I don't know how it's implemented. Maybe just having `BigFloat` will be enough?

**Comment by ozra** [comment]
Ah, I suspected so. Decimal is of course a lot faster, trade off being having to select what range and precision it can handle, simply being fixedpoint (all though 10-muls, and not old-school shifted, which would defeat the purpose), but anyone of us will add it when time comes for need, who ever gets there first :-). Whether it lands in stdlib or shard - but I do think it should be in stdlib for completeness.

**Comment by will** [comment]
![toot](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/27879/toot-1365641558.gif)

**Comment by asterite** [comment]
I included the code of @Exilor because it was very good. I guess some interactions between the "big" types are missing, and maybe some BigFloat operations, but we can add them later.

**Comment by Nephos** [comment]
hello @asterite 

```text
Couldn't find overloads for these types:
 - Float32#/(other : BigFloat)
```

Float32 / BigFloat => BigFloat isn't it ?

**Comment by ozra** [comment]
Back on the eternal subject ;-) Short answer: no - unfortunately not.
```
a = 1.2
b = BigFloat 1.2
1.upto 5 do
  a /= b   # <= `a` becomes a terribly hideously slow union of Float and BigFloat
end
```

**Comment by vegai** [comment]
Commenting on an old issue, because I'm thinking of BigDecimal. Asterite's comment that BigFloat is enough is not quite correct. Here's a example code using BigFloat:

`
require "big_float"

x=BigFloat.new(1.0)/BigFloat.new(10.0)
sum=BigFloat.new(0.0)
(1..1000).each {
  sum += x
}

puts "sum: #{sum}"
`

This outputs something else than 100.0 -- something like 99.9999999999999999678. With (a well implemented) BigDecimal, it would be 100.0. 

I'll experiment on this a bit myself and perhaps later submit an issue and a pull request. The simplest way (and usually the way others do it, afaik) is to just extend BigInt with a "scale" value that signifies where the decimal point is at.

For motivation, this is an extremely useful type for financial applications, since no other type really gives the precision required to model money.

**Comment by RX14** [comment]
@vegai You want to use `BigRational` which is exact and already in the stdlib.

**Comment by vegai** [comment]
BigRational almost fits the bill, but I think it would need to be augmented with a few methods to make it usable in this case. For instance, at least one of these should work:

```
BigRational.new 1.5
BigRational.new "1.5"
```

And I suppose outputting these to strings should have some support for formatting, rounding etc.

But since none of these things make really much sense for BigRational, I kinda think that a new class would be a better idea... so as not to mess BigRational with non-rational (hah) things.

For prior art, see 

- Java https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html
- Python https://docs.python.org/2/library/decimal.html
- Rust https://github.com/akubera/bigdecimal-rs

**Comment by RX14** [comment]
@akzhan's PR covers a lot of what you require: https://github.com/crystal-lang/crystal/pull/4653

**Comment by akzhan** [comment]
@vegai feel free to propose other additions to big arithmetics. Anyway it should be correlated with LibGMP capabilities.

**Comment by vegai** [comment]
I will :) It seems to me that BigDecimal can be implemented on top of either BigRational or BigInt without needing to touch gmp directly. I'll investigate it hopefully in a few days and will submit a PR -- we can continue discussion there.
