### ISSUE TITLE
(Class === other) not equivalent to other.is_a?(Class)

### ISSUE THREAD

**Issue by will** [crystal-lang/crystal#2505]
Given

``` crystal
class A
  def a
    1
  end
end

class B
end

def foo(i)
  i > 5 ? A.new : B.new
end
```

`foo(2).a if x.is_a?(A)` compiles,
but `foo(2).a if A === x` fails with `undefined method 'a' for B (compile-time type is (A | B))`

https://play.crystal-lang.org/#/r/xf5

**Comment by asterite** [comment]
This is expected behavior, the only thing that does type filtering is `is_a?` because you can't redefine it (in the next release I'll give an error if you do `def is_a?`, right now that's not the case). Since `===` can be redefined, the compiler can't filter the type.

We *could* special case it, but we'd like to avoid special cases.

**Comment by will** [comment]
Oh, the redefining. Got it, thanks
