### ISSUE TITLE
alias_method

### ISSUE THREAD

**Issue by JacobUb** [crystal-lang/crystal#252]
Crystal lacks a macro to alias methods:

``` ruby
macro alias_method(old_method, new_method)
  def {{new_method.id}}(*args)
    {{old_method.id}}(*args)
  end
end
```

We could also have a version for class methods (which Ruby lacks):

``` ruby
macro alias_class_method(old_method, new_method)
  def self.{{new_method.id}}(*args)
    self.{{old_method.id}}(*args)
  end
end
```

The following also works and perhaps makes `alias_class_method` unnecessary:

``` ruby
alias_method self.bar, self.foo
# or 
alias_method bar, self.foo
```

I didn't want to make a commit before hearing your thoughts on this.

**Comment by rubyFeedback** [comment]
Hmm. Old discussion but I wanted to add something.

Crystal uses aliases too but the intent is a bit different.

Take the official documentation here:

https://crystal-lang.org/reference/syntax_and_semantics/alias.html

    alias RecArray = Array(Int32) | Array(RecArray)

In my own ruby code I tend to do this:

    alias e puts

"e" could be anything else; I use it as "echo" abbreviation hence "e". Ruby also has p and pp;
pp for pretty_print.

Anyway. I sort of would expect that:

    alias e puts

would or should work on crystal. It does not seem to work.

I can get around it by e. g. defining a method "e" anyway and just using that as output
method. In classes I tend to do so because the output I use often gets modified, e. g.
colours and Unicode symbols for the commandline.

If you crystal folks don't want this as a default, then perhaps there could be a "compat-module" where these things could be enabled, a bit like an add-on gem or the did-you-mean gem for ruby. That way we could collect "ruby idioms" to make it simpler for people to transition into crystal.

It all may appear as a trivial thing, but the initial hurdle to overcome when entering a new language is very, very hard, and many things are different anyway. The easier that step is the better for people to want to transition.

Then we could have a require line, just to showcase:

    require 'ruby_compat_mode' # bad name but you get the gist of the idea

**Comment by Blacksmoke16** [comment]
> would or should work on crystal. It does not seem to work.

It is expected to not work, see https://github.com/crystal-lang/crystal/wiki/FAQ#why-are-aliases-discouraged.

> I can get around it by e. g. defining a method "e" anyway and just using that as output
> method.

Yes, just do that if that's what you want.

> It all may appear as a trivial thing, but the initial hurdle to overcome when entering a new language is very, very hard, and many things are different anyway. The easier that step is the better for people to want to transition.

I think people need to realize that this is in the README as a goal of the language:

> Have a syntax similar to Ruby **(but compatibility with it is not a goal)**

I.e. just because Crystal has similar syntax to Ruby, there is no desire to make things 100% compatible, nor introduce every Ruby concept/feature. Crystal is its own language. No one is going to Rust or Go suggesting they add the ability to alias a method just because that feature existed in Ruby.

In the end they're/you're just going to need to accept that and restructure your code to conform to Crystal semantics.

Related: https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists

**Comment by straight-shoota** [comment]
As an addition: Feel free to create a shard that provides such features. It does not have to be an optional part of stdlib or an official shard.

**Comment by wyhaines** [comment]
Huh.  Timely.

Somewhat as fallout of work that I did to build a library to inject method tracing (https://github.com/wyhaines/tracer.cr), I just finished the MVP of an `alias_method` implementation that tries really hard to _just work_. It works for class methods or instance methods.

I am sure that the internals can be made less ugly, but it seamlessly works for many (most?) cases.

Spec coverage currently includes:

```crystal
  def self.bare_class_method
  def [](val)
  def bare
  def bare_with_return_type : UInt8
  def with_args(one, two)
  def with_args_and_return_type(one, two) : Array(Int32)
  def with_typed_args(one : String, two : String)
  def with_typed_args_and_return_type(one : String, two : String) : Hash(String, String)
  def with_capture(&block : -> Int32)
  def with_arg_and_capture(arg, &block : Int32 -> Int32)
  def with_arg_and_capture_and_return_type(arg, &block : Int32 -> Int32) : Int32
  def with_yield(arg)
```

I am working on adding all of the things to the specs, so that the coverage is well defined, and then I will probably do some more internals cleanup.

https://github.com/wyhaines/alias_method.cr

**Comment by asterite** [comment]
Isn't it possible to use splats and double splats for this? I think the only thing that wont work is captured blocks, but other than that it seems it would be simpler than the macro you have right now. Plus it would cover all arities.

**Comment by asterite** [comment]
Actually, alias_method could internally rely on the delegate macro available in the standard library, and just delegate to self.

**Comment by wyhaines** [comment]
Block forwarding, in general, makes the implementation more complex, but an implementation that can't handle captured blocks feels pretty crippled.

In general, the internals can get a lot of cleanup, though, and leveraging splat/double splat in all of the places where they can work should be part of that.
