### ISSUE TITLE
method overloading by return type

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2552]
is it possible to implement in crystal this?

```crystal
def bla : String
  "bla"
end

def bla : Int32
  1
end

a = Array(String).new
a << bla

b = Array(Int32).new
b << bla
```

**Comment by asterite** [comment]
No. I think it could be done, though, but since the language doesn't require return type annotations and neither method arguments annotations it'll also be useful in very few cases. So it maybe goes better with a fully typed language. I believe both Rust and Swift allow this.

**Comment by kirbyfan64** [comment]
And I think that, if the compiler tried to infer return types *and* try to have them overloaded at the same time, you'd probably end up with exponential compile times.

**Comment by waterlink** [comment]
That is true. Sane way to do such overloading is to require return type annotation for such overloads. This will make language more confusing, though..

**Comment by kumpelblase2** [comment]
This only works well if you directly pass the result to another method which only works on a specific return type. Consider for example this:
```crystal
# From your example above
def bla : String
    "bla"
end

def bla : Int
    1
end

def foo(a: String)
   puts "Is a String"
end

def foo(a: Int)
   puts "is an Int"
end

foo(bla) #=> ????
# or
a = bla #=> what value would a have?
```
What would get run? I really think this is a bad idea. Not only would this make code less readable because now methods can have different effects depending on what is expected, but also is it ambiguous what will get run until somewhere down in the code a decision has been made. This doesn't make any sense in such a dynamic language, only if you'd always had to declare a type (which would be counterproductive in crystal).

**Comment by kostya** [comment]
in cases where compiler can't resolve it, it would be just error
i think about this cases:

```crystal
j = JSON.parse("{\"bla\":1.5}")
j["bla"] * 2.5
```

and compiler cast it as float from expression, instead of:

```crystal
j = JSON.parse("{\"bla\":1.5}")
(j["bla"] as Float64) * 2.5
```

**Comment by kumpelblase2** [comment]
I don't think that example serves as a good support for having return types added to the signature of a method. I'd rather have something like implicit conversions (e.g. like in scala) for what you just described instead of return type defining behavior of a method.

**Comment by asterite** [comment]
But `j["bla"]` can be an Array, and it also has the `*` method.

**Comment by kostya** [comment]
in case where multiple cases comply, compiler give error:

how funny it can be:

```crystal
j = JSON.parse("{\"x\":1, \"y\":2}")

def calc(x : Int32, y : Int32)
  x * y
end

puts some j["x"], j["y"]
```

**Comment by asterite** [comment]
But `j["x"]` can be of other types, so the compiler will give an error saying "no overload matches calc(String, Int), calc(String, String), etc.". You'd have to do:

```crystal
j = JSON.parse("{\"x\":1, \"y\":2}")

def calc(x : Int32, y : Int32)
  x * y
end

def calc(x, y)
  raise "Oops"
end

puts some j["x"], j["y"]
```

which is basically what you have to do right now.

What's wrong with:

```crystal
j = JSON.parse("{\"x\":1, \"y\":2}")
puts j["x"].as_i + j["y"].as_i
```

The `as_i` have a use: they are a runtime check and will fail if that's not the type. It's similar to Ruby, but the check has to be explicit (like `not_nil!`).

**Comment by asterite** [comment]
I'm closing this. It's **very** hard to implement, hard to understand, and I even remember @waj complaining about the Swift compiler because it gives some errors that are really hard to understand and they usually arise when the compiler tries to type things in both directions. And because variables don't have an explicit (written) type, it's very hard to fit this into the language.
