### ISSUE TITLE
Can't infer the type of instance variable initialized with to_s (0.16)

### ISSUE THREAD

**Issue by olegantonyan** [crystal-lang/crystal#2598]
```crystal
class A
  property :some_prop

  def initialize
    self.some_prop = nil.to_s
  end
end

A.new
```
Gives a compilation error:
`Can't infer the type of instance variable '@some_prop' of A`
But `to_s` method returns `String`, so I think the compiler should be able to infer type from it.

**Comment by bcardiff** [comment]
Hi @olegantonyan, 

There are two issues in the above example.

1. The statement that `#to_s` method returns `String` is necessary not true. It depends on the receiver of the call. You are using a constant, so actually the value is determined to be string empty `""`. The `""` expression is known to be a String since it is a literal.

2. The type of the instance variables need to be inferred from the class code, despite its usage. For this either `property :some_prop` is changed to `property some_prop : String` or you use the literal `""` instead of `nil.to_s`, and in both cases assign the value directly to the instance variable `@some_prop`.

https://play.crystal-lang.org/#/r/ylp
https://play.crystal-lang.org/#/r/ylr
  

Although you example seems tiny and should work right away, right now [the rules](http://crystal-lang.org/docs/syntax_and_semantics/type_inference.html) avoid resolving instance methods.

**Comment by olegantonyan** [comment]
Thanks a lot @bcardiff ! I think I get it now
