### ISSUE TITLE
Float string edge case

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2656]
I noticed you truncate based on a certain run of 0s.  Here's a number that doesn't quite fit.

```ruby
      num = 1464132168.65_f64
      num.to_s.should eq("1464132168.65")
 ```

**Comment by asterite** [comment]
@mperham Thanks. I found many other edge cases too, but it's hard to satisfy all inputs with this simple algorithm. I'll try to fix them as you and others report them, if I can (if others specs don't break). For now I prefer to err with more digits than with less, specially because if you then parse the output you continue getting the same value, even though the output shows more digits.
