### ISSUE TITLE
Support unions in YAML mappings

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal#2714]
When defining a YAML or JSON mapping for an object that does not have a very strict schema, it would be useful to be able to define unions. For instance:

```crystal
class Foo
  YAML.mapping({
    field: Int32 | String
  })
end
```

In order to support both `field: foo` and `field: 10`. This can be implemented for basic types by checking the `kind` property of the pull parser (see [here](https://github.com/crystal-lang/crystal/blob/fb22a8978eecde0f986513b0b0cbbc6e15066598/src/json/pull_parser.cr#L3) for JSON).

This becomes more complicated when dealing with complex types, as each type should be able to answer whether it accepts that fragment of JSON or YAML or not (perhaps by raising a pre-agreed exception); and if it doesn't, then **rewind** the pull parser to its former state so the next type in the union can be tested. I'm not familiar with the underlying implementations for either pull parser, but is this feasible?

Do you think something like this would be useful?

**Comment by bcardiff** [comment]
I agree that  `Int32 | String` is useful. For example when dealing with query request/responses to elasticsearch.

I don't think more complex scenarios will appear. So 👍  for the `Int32 | String`

**Comment by kostya** [comment]
is there a way to iterate for `Int32 | String` inside macro? then i think it should be easy to implement

**Comment by bcardiff** [comment]
@kostya Yes! check out [macro_specs.cr:542](https://github.com/crystal-lang/crystal/blob/master/spec/compiler/codegen/macro_spec.cr#L542)

**Comment by asterite** [comment]
Some things to consider:

1. You can currently read JSON/YAML from an IO, so rewinding is not an option. However, one can read the raw string and later reparse it. Check for example [String::RawConverter](http://crystal-lang.org/api/String/RawConverter.html) and [JSON::PullParser#read_raw](http://crystal-lang.org/api/JSON/PullParser.html#read_raw-instance-method).
2. How would reading a union work? One way I can think, but it's probably very slow, is to try to `T.from_json(string)` for every type and return the one that succeeds first. If the union consists of simple types maybe something custom can be done.
3. `Int32 | String`, in that place, is a method call, as @bcardiff says. And we don't have a syntax to refer to unions, [but we could have one](#2659). Alternatively, we could change the language so that `Foo | Bar` creates a union instead of being a method call. We could also add `Foo?` for completeness, because it's common. So... right now the only way would be to decompose the Call ASTNode, which is very tedious.

@spalladino What's your specific use case?

**Comment by spalladino** [comment]
The use case is parsing data returned from an API, where I have a "bag" of entities, that can be either strings or numeric, so I just have to deal with primitive types now; but I don't see it that odd having to handle complex types as well.

I was thinking something along the lines of what you mention in (2), where the mapping tries every type in the union in order, and returns the first one that did not raise a "I don't know how to parse this stuff"-exception.

As for reading the raw string and later reparsing, the mapping should be smart enough to save the string only if there is a union involved, to avoid a performance penalty.

**Comment by kostya** [comment]
i playing with implement it to msgpack, but got error, instance_vars is empty in macro:

```crystal
module M
  macro bla
    @a : Int32 | String

    def initialize
      p "{{@type.instance_vars}}"
      @a = 1
    end
  end
end

class A
  include M
  bla
end

p A.new
```

```
"[]"
```

**Comment by jhass** [comment]
@kostya yes, quite expected so in this case, since in the same macro, the "@a : Int32|String" wasn't even parsed yet when you invoke `@type.instance_vars`.

**Comment by asterite** [comment]
Actually, the issue is macro-inception. This works:

```crystal
module M
  macro bla
    @a : Int32 | String

    def initialize
      p \{{@type.instance_vars.stringify}}
      @a = 1
    end
  end
end

class A
  include M
  bla
end

p A.new
```

Otherwise `{{@type}}` gets expanded as soon as you invoke `bla`, but you want it expanded when you then invoke `initialize`.

**Comment by kostya** [comment]
with msgpack diff is not so big to implement it: https://github.com/benoist/msgpack-crystal/commit/d5666accf23ba4cb61880dc603bfbdac23d525eb

this is not full implementation, just example

works:
```crystal
require "./src/message_pack"

class Bla
  MessagePack.mapping({
    a: (String | UInt32),
    b: (String | UInt32),
    c: Int32,
  })
end

bla = Bla.from_msgpack({"a" => "bla", "b" => 11, "c" => 12}.to_msgpack)
p bla
```

**Comment by asterite** [comment]
@kostya Nice trick, splitting by "|" ;-)

Should this work too?

```crystal
class Foo
  JSON.mapping({
    field: Array(Int32 | String),
  })
end
```

It gets trickier, and this implies modifying `Array.new(pull : JSON::PullParser)` to check if `T` is a union.

**Comment by kostya** [comment]
or problem with aliases:

```crystal
alias Bla = Int32 | String
alias Bla2 = Char | Bool

class Foo
  JSON.mapping({
    field: Bla | Bla2,
  })
end

```

**Comment by asterite** [comment]
So... I thought about this a bit more.

First, I thought we could have a type `JSON::Deserializer(T)`, so one can do: `JSON::Deserializer(Int32 | String).new(pull_parser)` and make it work. The compiler of course resolves the union inside the generic type, so aliases are solved, and inside `JSON::Deserializer` we can ask things about `T` with macro methods (is it a union? give me the union types, etc.).

However, that meant we'd had to use `JSON::Deserializer` everywhere, for example in `Array.new(pull_parser)`, doing `JSON::Deserailzer(T).new(...)` instead of `T.new`. Kind of ugly and long.

Then I remembered about having `Union` as a first-class type to which one can add class methods. Then, problem solved: instead of `JSON::Deserializer` we just define a `def self.new(pull_parser)` method in `Union`, and that's it. No need to change Array, because `T` is already a union type. And for `JSON.mapping` one can pass `Union(Int32 | String)` to make it work. But, we can also use `Union({{type}})` in JSON.mapping, so users can do `value: Int32 | String`. The macro generates `Union(Int32 | String).new(pull_parser)`, which works, because it's a union of a union type, and the compiler flattens all types. It also works with `Union(Int32)`, because that produces a `Int32` type (not a union).

I think this is the "mathematically correct" solution to the problem :-)

**Comment by asterite** [comment]
In fact, it also makes more sense because one can also do:

```crystal
require "json"

p Union(Int32, String).from_json(%(1)) # => 1
p Union(Int32, String).from_json(%("hello")) # => "hello"
```

which is more uniform and consistent with how you parse every other type into JSON.

**Comment by asterite** [comment]
So, union types in JSON mappings, and in general for parsing, are now supported.

Support still needs to be added for YAML, but we need to implement `read_raw` for `YAML::PullParser` first.
