### ISSUE TITLE
Better error suggestion for `and`, `or`, `not` and `xor`

### ISSUE THREAD

**Issue by mirek** [crystal-lang/crystal#2715]
```
in ./src/uuid.cr:5: undefined method 'and' (did you mean 'rand'?)

  unless value[i].hex? and value[i + 1].hex?
```

It should probably suggest `(did you mean '&&'?)`

**Comment by bcardiff** [comment]
It seems like a nice idea. If someone wants to give it a try, the relevant code is:
https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/suggestions.cr#L25

There is something a bit odd about the resulting AST in that line, the rand is suggested because it is a top level method and there is no information that the expression has a boolean in the lhs. But I think there is no harm to add a case for boolean operators.

**Comment by asterite** [comment]
The actual logic to give an error message for an "undefined method" is here: https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/call_error.cr#L45

If someone wants to do this, go ahead. I marked it with an "easy" label, should be relatively simple to enhance/fix. The case is when the Call (self) has no `obj` (receiver), the name is "and" and there's just one argument. And consider other names ("or", "xor"). And maybe also "not".

**Comment by fernandes** [comment]
@asterite this is a 238-lines method, is interesting to extract on a class with smaller methods or something like this? or you believe keeping this is the right approach?

**Comment by asterite** [comment]
If you can find a way, go ahead. That part of the compiler (producing good error messages for "undefined method") is a bit messy, so a cleanup is always welcome :-)

**Comment by fernandes** [comment]
as I've seen (maybe I missed something, I just searched on `spec` folder for `raise_matches_not_found` and found nothing)

you can assign me to this one, perhaps it's going to take a little bit of time to understand how it works, but as soon as I make any progress I open a PR to get some direction

**Comment by asterite** [comment]
@fernandes We usually avoid unit tests in the compiler that exercise specific parts. That's why there are no specs for the internal implementation (except a few cases). We test the language's behaviour, to check that types are correct and generated code is correct. This is very good because when we decide to change the internal implementation we don't need to re-write or remove internal tests, but we still can be sure the changes kept the language's semantics in place.

You can search "undefined method" or "no overload matches" to find where to put new specs :-)

**Comment by asterite** [comment]
@fernandes There's no hurry at all on this, so take as much time as you need. Thank you! :-)

**Comment by fernandes** [comment]
Hi @asterite,

Trying to solve this problem I added a test on [did_you_mean_spec.rb](https://github.com/crystal-lang/crystal/blob/ab0cade885cd368f4f2c30ba4c65a2e6b69935fc/spec/compiler/type_inference/did_you_mean_spec.cr)

```crystal
it "suggests a better alternative to logical operators (#2715)" do
  if "a".bytes and 1
    1
  end
  ), "undefined method 'and' (did you mean 'rand'?)"
end
```

But I got undefined method `bytes` for a String (on carc this snippet perfectly works https://carc.in/#/r/10nk)

Then I opened `String` class and added `bytes` returning `self` once I need to call a method before `and`, called bytes perfectly.

Then, didn't suggest `rand`, I thought that was because the method did not exist on String and added, but still don't get the suggestion.

Going deeper on [src/compiler/crystal/semantic/suggestions.cr](https://github.com/crystal-lang/crystal/blob/86a90e159a8b28f1b2a3c26b1dfeba05930d6177/src/compiler/crystal/semantic/suggestions.cr) I found [lookup_similar_name](https://github.com/crystal-lang/crystal/blob/86a90e159a8b28f1b2a3c26b1dfeba05930d6177/src/compiler/crystal/semantic/suggestions.cr#L25), when looking for `and` method, self is `Crystal::Program`, should not be `String`?

Sorry if it's a dumb question, probably is, but now I got into some areas of the compiler I have never touched.

Thank you

**Comment by asterite** [comment]
@fernandes I think you missed something in your copy-paste, it's missing the `assert_error` bit:

```crystal
it "suggests a better alternative to logical operators (#2715)" do
  assert_error %(
  if "a".bytes and 1
    1
  end
  ), "undefined method 'and' (did you mean 'rand'?)"
end
```

The error you are getting is because you have `if "a".bytes and 1`, which is parsed as `if "a".bytes(and(1))`, and so you get an undefined method error for "and".

**Comment by fernandes** [comment]
perhaps explained me wrong

after using `if "a".bytes and 1` and being parsed as `"a".bytes(and(1))`, the compiler do not find the `rand` method to be suggested.

my current test

```crystal
  it "suggests a better alternative to logical operators (#2715)" do
    assert_error %(
      class String
        def rand
          self
        end

        def bytes
          self
        end
      end

      if ("a".bytes) && 1
        1
      end
      ), "undefined method 'and'"# (did you mean 'rand'?)"
  end
```

On the test I'm getting the exception and `undefined method 'and'` and not `undefined method 'and' (did you mean 'rand'?)`.

Going deeper on [src/compiler/crystal/semantic/suggestions.cr](https://github.com/crystal-lang/crystal/blob/86a90e159a8b28f1b2a3c26b1dfeba05930d6177/src/compiler/crystal/semantic/suggestions.cr) I found [lookup_similar_name](https://github.com/crystal-lang/crystal/blob/86a90e159a8b28f1b2a3c26b1dfeba05930d6177/src/compiler/crystal/semantic/suggestions.cr#L25), when looking for `and` method, self is `Crystal::Program`, should not be `String`?

**Comment by jhass** [comment]
I think you still didn't paste the correct spec, this one has `("a".bytes) && 1`. Assuming `"a".bytes and 1` it's `"a".bytes(and(1))`, not `"a".bytes.and(1)`, so `and` would be a toplevel method there, not an instance method of string.

**Comment by fernandes** [comment]
you're right, I changed to test some stuff and forgot to change back to original spec when pasting

```crystal
  it "suggests a better alternative to logical operators (#2715)" do
    assert_error %(
      class String
        def rand
          self
        end

        def bytes
          self
        end
      end

      if "a".bytes and 1
        1
      end
      ), "undefined method 'and' (did you mean 'rand'?)"
  end
```

this is the right one

**Comment by jhass** [comment]
So I guessed right, see my previous comment. I don't understand why you think it would search in `String` for it.

**Comment by fernandes** [comment]
got it...

maybe is my ruby mind, I was thinking in a method chain, and didn't realize the top level method... thank you! 🙇

**Comment by jhass** [comment]
This is no different on Ruby.

**Comment by fernandes** [comment]
sorry, I misunderstood, you're right 🙇

**Comment by fernandes** [comment]
reproduced the error, now I'm going to work on a solution... thank you @asterite and @jhass
