### ISSUE TITLE
Array#pack and String#unpack

### ISSUE THREAD

**Issue by chendo** [crystal-lang/crystal#276]
Are these going to be implemented as part of the stdlib? If so, would we like it to work the same way as the Ruby one? I'm willing into look into porting this over.

**Comment by jwoertink** [comment]
Now that's it's been a few years, is there any chance of this being a thing, or maybe a way to handle this?

**Comment by straight-shoota** [comment]
This question has just recently come up again on chat. So it seems to be a constant topic for Ruby developers. Although I've personally never used it in Ruby and I can really never tell what that cryptic format string means. And honestly, I don't care.

In Crystal, we have a way better tool for solving the problems that pack/unpack solves: [`IO`](https://crystal-lang.org/api/latest/IO.html). You can do the same things as with pack/unpack and it even offers better readable code, type safety, and more performance and flexibility.

```cr
n = [65, 66, 67]

# Ruby
n.pack("ccc") #=> "ABC"

# Crystal
String.build do |io|
  n.each do |number|
    io.write_byte number.to_u8
  end
end #=> "ABC"
```

Sure, the Crystal implementation is a bit more verbose, but that only makes it that you can actually understand what the code is doing instead of having to decipher the meaning of a cryptic format string.

**Comment by jhass** [comment]
Have a look at `IO::ByteFormat`, `IO#read_byte`, `IO#read_bytes`, `IO#write_byte`, `IO#write_bytes`.

**Comment by jwoertink** [comment]
Yeah, I don't mind a little verbosity especially when it makes it clearer on what's going on. The one specifically I'm looking to do is `[5].pack('e*').bytes` which returns an array of ints. I found [this](https://crystal-lang.org/api/0.32.1/IO/ByteFormat/LittleEndian.html) but I still haven't managed to figure out how to get what I'm looking for.

**Comment by straight-shoota** [comment]
```cr
# Equivalent to `numbers.pack('e*')`:
numbers.each do |n|
  io.write_bytes n.to_f32, IO::ByteFormat::LittleEndian
end
```

**Comment by jwoertink** [comment]
Boom! Thanks 😄 I was stuck on that one for a while there.

**Comment by bcardiff** [comment]
My take is that there could be a shard that provides a macro via run program that could translate de pack syntax and even generate typed results.

**Comment by straight-shoota** [comment]
@bcardiff Please, no that would still have cryptic format strings end up in Crystal code bases 😆 Then I'd rather prefer a webservice at https://transform-crazy-pack-format-to-beautiful-crystal.com

**Comment by jhass** [comment]
More importantly I still think that it would be a mistake to treat  and promote `String` as generic byte sequence container,  that's what we have `Slice(UInt8)` aka  `Bytes` and `IO` (including `IO::Memory`) for.

**Comment by straight-shoota** [comment]
Since this has been coming up very frequently in the last weeks, I've added an entry to the FAQ: https://github.com/crystal-lang/crystal/wiki/FAQ#user-content-is-there-an-equivalent-to-rubys-arraypackstringunpack

**Comment by Blacksmoke16** [comment]
@straight-shoota wouldn't it fit better under the crystal for rubyists section?

**Comment by rubyFeedback** [comment]
> Although I've personally never used it in Ruby and I can really never tell what that cryptic format string means.

I have not used it myself either, largely because I never understood it. There have, however had, other people using it. I am not sure how popular it is in Ruby, but it was used. I guess the underlying question is what the use case actually is, and then figure out if that use case applies to crystal as well or not. 

Note that I found the issue tracker via this blog:

https://therubyist.org/2020/05/07/rewriting-rubys-pack-and-unpack-methods-in-crystal/

And I still don't understand #pack in ruby ...
