### ISSUE TITLE
Name convention for acryonims

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#279]
Right now we have:
- `Xml::Node`, `Xml::Document`, ...
- `Json::Parser`, `Json::Lexer`, ...
- `HTTP::Client`, `HTTP::Request`, ...
- `Yaml::Parser`, ...

Our original idea was to use upcase for things that you normally say letter by letter, like XML and HTTP, and use downcase for things that are pronounced like a name (json is pronounced "jason", yaml is pronounced "yaml", etc.).

We are currently following this rule, except for Xml, probably because we thought about that rule later in time. Now I'm not sure about this. I think `Http::Client` feels more lightweight than `HTTP::Client`. Maybe using downcase everywhere is better: you spend less time holding shift, and you can better distinguish where the next "word" starts when not using colons.

As a separate issue, I find it easier to type `HttpClient` than `Http::Client`, or `JsonParser` than `Json::Parser`. In .Net for example they have a type `DateTime` and another `DateTimeKind` that are related. They also have an `HttpClient` class. Right now we have `Time` and `Time::Kind`. I find it a bit annoying to type those two colons. So maybe we should drop them in these cases. Who else is going to define a `JsonParser` or an `HttpClient` type at the top level? The std should be as pleasant to use as possible.

We should decide on this now that the language is still in version 0.x, where we can make breaking changes.

**Comment by ozra** [comment]
Oh, I got really late to this party, and I guess a breaking rename again will be hard to argue for?

I definitely think PascalCased acronyms are _much more readable_, thus more easily understandable and readable code. I would beg on my knees for `Http`, `AstNode`, etc. instead of `ASTNode` etc.

**Comment by mirek** [comment]
More arguments for PascalCase

* FooBar it's convertible to / symmetric with fooBar, foo_bar, foo-bar etc. FOOBar is not and makes automatic conversion impossible
* it requires 0 brain effort to name things, there are no arguments between alternatives because there aren't any; FOOBar on the other hand is left for interpretation. We are going to end up with people using FOOBar in one library and FooBar in other (we'll see FooBAR as well).
* difference between abbreviations and acronyms is blurred / they are mixed into one word; you end up not knowing if this postgres type decoder class should be called IPAddr or IPADDR; RegProc REGProc or REGPROC; MacAddr, MACAddr or MACADDR - with PascalCase this problem doesn't exist
* PascalCase is readable when joined TcpIpHttp, TCPIPHTTP is not. 
* abbreviations and acronyms have their own capitalization rules it's hard to say which one should be used PNPDiscovery or PnPDiscovery, LOCCounter or LoCCounter, UUIDV4 or UUIDv4 - with PascalCase it's more straight forward
* FooBar can be plural FoosBars - looks good, but FOOsBars FOOsBARs FOOBARs not so much
* similarly FooOrBar looks good, FOOOrBar FOOAndBar doesn't and it's hard to read because there is no clear boundary
* acronyms with time become words so on the long enough timeline FOOBar will die or will change to FooBar anyway

**Comment by asterite** [comment]
I'm starting to agree with @ozra and @mirek . I believe pascal case for acronyms is easier to read and write and makes names more consistent and easier to figure out in case you need to use them. I always liked how this is handled in C#, basically use pascal case, and the standard library is very consistent about this. While searching this I even found a [code convention guide for acronyms](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.100).aspx#Anchor_2) right in the docs.

I was about to say that we should start using this convention, using aliases for the current names to make upgrade easier and slower, but... looking at the standard library, modules as namespaces are used very well. We have `JSON.parse`, `JSON::Parser`, `XML.parse`, `XML::Document`, `HTTP::Client`, `URI::Parser`, etc. I think `OpenSSL` is the only case an acronym is used combined with another word, and in this case I don't think it's a bad way to name it because nothing else comes after the `SSL` part. Well, we also have `IniFile`, but that's an old class that never received much love, and I think it should be named `INI`.

This way is maybe better because it preserves the original name of the acronym, so it's more familiar (`Json.parse`, `Http::Client`, `Uri`, etc., look kind of odd)

So, what we can do and encourage is pascal case when names are combined into a single name, but otherwise use acronyms as module names and use them as namespaces.

**Comment by mirek** [comment]
I agree that there is something strangely nice about capitals in ruby'ish syntax, this lean chubbiness that goes well with begin? end blocks and just feels right.

Should we just change `IniFile` to `INIFile` to be consistent and close this discussion forever leaving naming convention as something along the lines "capitals preferred for acronyms, for abbreviations that are getting longer, especially ones following acronyms use pascal case". So for example `IPAddr` follows this convention and feels right.

**Comment by ioquatix** [comment]
Yes changing `IniFile` to `INIFile` is the right choice IMHO. Also, I'd prefer no abbreviations, e.g. `IPAddress`. It's less ambiguous in general, easier for people for who English is not their native language.
