### ISSUE TITLE
SecureRandom.random_bytes should use `/dev/urandom` by default

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#2792]
Following the advice of professional cryptographers, we shouldn't use OpenSSL `RAND_bytes` by default, but instead use `/dev/urandom` or a secure syscall when available.

See for reference:
- The long pending [Ruby issue](https://bugs.ruby-lang.org/issues/9569)
- The secure SecureRandom gem for Ruby: [sysrandom](https://github.com/cryptosphere/sysrandom)
- The `getrandom` syscall introduced in Linux 3.17 (not widely deployed in LTS releases)

**Comment by jhass** [comment]
See http://www.2uo.de/myths-about-urandom/

**Comment by RX14** [comment]
Also see https://download.libsodium.org/doc/generating_random_data/ for how a (decently) popular crypto library generates randomness on several platforms. It might be worth using such an ordering, depending on platform, instead of blindly using urandom. `getrandom(2)` is likely faster than urandom, in crystal, but I havent benchmarked it.
