### ISSUE TITLE
typeof is not allowed in the type grammar

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#2849]
> ### [typeof](http://crystal-lang.org/docs/syntax_and_semantics/type_grammar.html#typeof)
> 
> `typeof` is allowed in the type grammar. It returns a union type of the type of the passed expressions:
> 
> ``` crystal
> alias SameAsInt32 = typeof(1 + 2)
> alias Int32OrString = typeof(1, "a")
> ```

... But these examples don't seem to work on any version of Crystal

https://carc.in/#/r/11sv
https://carc.in/#/r/11sw

**Comment by asterite** [comment]
Moved it as a docs bug, it should be documented somewhere that that's not possible.

The reason is:

```crystal
alias Foo = typeof(...)

class Bar < Foo
end
```

Oops, now we need to potentially do method resolution to determine what type is `Foo`, and then what's the superclass of `Bar`. Basically `typeof` is not allowed in the first pass of the compiler when we determine all the types and their relationships.

One can use `typeof` inside methods:

```cr
def foo
  a = typeof(1)
end
```
