### ISSUE TITLE
Instance variable types not inferred from method calls.

### ISSUE THREAD

**Issue by jpittis** [crystal-lang/crystal#2860]
#### Issue
Instance methods cannot have their types inferred from method calls.

``` Crystal
# Types are inferred in this case.
my_string = "foobar"
puts my_string[0..my_string.size]

# Types are not inferred in this case.
class MyClass
  getter my_string
  def initialize(str : String)
    @my_string = my_string[0..my_string.size]
  end
end

puts MyClass.new(my_string).my_string
```

The latter part of the code causes:
```
Can't infer the type of instance variable '@my_string' of MyClass
```

The current workaround is to specify the type of the instance variable:
``` Crystal
@my_string : String
```

#### Discussion from IRC:
```
<jhass> for the moment it's intentional
<jpittis> jhass: for what reason?
<jhass> to keep the algorithm simple and thus fast
```

**Comment by asterite** [comment]
The reason is that in the general case (and also in this specific case) we have to do method resolution and that can involve needing the types of some instance variables. The compiler works by doing a first pass to quickly determine the types of instance vars for all types. This will allow us to improve compile times in the future and possibly do incremental compilation.

In your specific case, `str[0..str.size]` means resolving [str.size](https://github.com/crystal-lang/crystal/blob/07dbb0507381f561ce914cbb62c69df4f8bec841/src/string.cr#L2932-L2938), which depends on instance vars like `@length` and `@bytesize`. Then we'd need to solve the [`String#[]`](https://github.com/crystal-lang/crystal/blob/07dbb0507381f561ce914cbb62c69df4f8bec841/src/string.cr#L635-L646) method which is pretty complex, and so on.

We could probably improve this if return types are available on those instance methods... but that might lead everyone to put return types everywhere, just because someone might want to use them for initializing an instance variable, so the language we'll become more verbose and tedious to use. Well, basically, instead of having to add type annotations from time to time in an instance variable, one would have to put return types to every method.

So I don't think this will ever change (but I can be wrong).

**Comment by asterite** [comment]
Also check http://crystal-lang.org/docs/syntax_and_semantics/type_inference.html

**Comment by asterite** [comment]
I'm closing this as it's not something we'll change soon (we might never change this)
