### ISSUE TITLE
empty YAML and .from_yaml

### ISSUE THREAD

**Issue by mose** [crystal-lang/crystal#2873]
Hi

Here is some piece of code

```crystal
require "yaml"

class Something
  YAML.mapping(
    x: {
      type:    String,
      default: "bbb",
    }
  )
end

puts YAML.parse ""                # returns an empty YAML::Any
puts Something.from_yaml "o: oo"  # returns a Something
puts Something.from_yaml ""       # raises an error
```

which results in 

```
$ crystal yaml.cr

#<Something:0x1db1f20>
expected DOCUMENT_START but was STREAM_END at 0:0 (YAML::ParseException)
[4379207] *CallStack::unwind:Array(Pointer(Void)) +87
[4379098] *CallStack#initialize:Array(Pointer(Void)) +10
[4379050] *CallStack::new:CallStack +42
[4373400] *raise<YAML::ParseException>:NoReturn +24
[4447594] ???
[4448248] *YAML::PullParser#expect_kind<LibYAML::EventType>:Nil +136
[4448090] *YAML::PullParser#read<LibYAML::EventType>:LibYAML::EventType +10
[4448267] *YAML::PullParser#read_document_start:LibYAML::EventType +11
[4470237] *Something +61
[4361522] ???
[4373081] main +41
[139780543627077] __libc_start_main +245
[4360153] ???
[0] ???
```

While parsing an empty string with YAML parser is all ok, it's not tolerated by the `.from_yaml`, even while the mapping don't declare any mandatory key. 

I checked the mapping code a bit and I see why, but I'm not sure there would be an easy way to fix it. Or is there?

**Comment by jhass** [comment]
Perhaps the easier solution to consistent behaviour is to raise in all cases?

**Comment by david50407** [comment]
@jhass I think the empty content still a legal YAML. How about just return `nil` in `YAML.parse`, and skip the empty document in the `Object.from_yaml`?

**Comment by mose** [comment]
Just as a side note, in ruby `YAML.parse ""` returns a `FalseClass` object.

**Comment by david50407** [comment]
@mose they discussed about returning `false` here, and maybe `nil` is better for "nothing here": https://github.com/tenderlove/psych/issues/149

**Comment by asterite** [comment]
Not sure what to do with this, an empty YAML is not like an empty object/hash. 

@mose What's your use case?

**Comment by mose** [comment]
My case is that I have a config Class with default values for all items in YAML.mapping, and the config file is optional. So when there is a config file to be found, I load the file content to create my config object. Otherwise, I want to create that config object with default values only. 

Then to do so I cannot load an empty string I have to load `"nothing: here"` which feels like crap.

ref https://github.com/mose/anyquestion/blob/master/src/anyquestion/configuration.cr

**Comment by asterite** [comment]
Why not create an empty Config instance if the file doesn't exist instead of always creating it via YAML parsing? It will also be a bit faster like that.

**Comment by david50407** [comment]
@asterite your solution is good, but I still considered that empty content should be a valid YAML document.
Because in [YAML document](http://www.yaml.org/spec/1.2/spec.html#id2801681), it said:

> A YAML stream consists of zero or more documents. 

And the rule of stream is pasted below and it seems that empty content is still a valid yaml stream:

```
[211]	l-yaml-stream	::=	l-document-prefix* l-any-document?
                            ( l-document-suffix+ l-document-prefix* l-any-document?
                            | l-document-prefix* l-explicit-document? )*
```

**Comment by asterite** [comment]
@david50407 How can we implement YAML.mapping for this case?

**Comment by david50407** [comment]
I know if we move `parser.read_document` from [Object.from_yaml](https://github.com/crystal-lang/crystal/blob/9bb0ada8cf0d77d6b3dd17c99ff92bea32083325/src/yaml/from_yaml.cr#L4) into `Foo#initialize(YAML::PullParser)` and check if the stream is ended before [here](https://github.com/crystal-lang/crystal/blob/9bb0ada8cf0d77d6b3dd17c99ff92bea32083325/src/yaml/mapping.cr#L92) will be complicated.

IMO, accept STREAM_END appears in `read_document` with a optional flag that if we accept to read a STREAM_END for `read_document`, it will still yield the block. like this:

```crystal
class YAML::PullParser
  def read_document(allow_stream_end = false)
    read_document_start if allow_end && kind == EventKind::STREAM_END
    value = yield
    read_document_end if allow_end && kind == EventKind::STREAM_END
    value
  end
end
```

I know that will use more time to compare the flag and the kind of current token, maybe it can be a separated function named like `read_document_or_end`

And we can raise in the built-in types (like `Int32`, `Float64` ...) that don't have default values while we passed a empty document (because a empty document only can performed as a empty hash/array or null)

I think the empty content is the same to the content `---` which means a stream and a empty document in it, so the action of "" and "---" should be the same at least.

**Comment by david50407** [comment]
@mose btw, you can pass `"---"` for a empty YAML document.

**Comment by mose** [comment]
@david50407 yeah that's what I thought, but using `---` works with `YAML.parse` and raises an error with `Something.from_yaml`
