### ISSUE TITLE
GC_get_push_other_roots in a testing server different than development environment

### ISSUE THREAD

**Issue by raydf** [crystal-lang/crystal#2896]
I'm compiling a program with latest version of crystal released today:

```bash
crystal compile src/test.cr --release --verbose

cc -o "/home/test/test" "${@}"  -rdynamic  -lyaml -lz `pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib _main.o
```
Everything compiles correctly, but when i try to run in another testing environment with ubuntu server i receive this error:

```
./test: symbol lookup error: ./test: undefined symbol: GC_get_push_other_roots
```

**Comment by kirbyfan64** [comment]
You need to install the latest Boehm GC in the other system.

**Comment by raydf** [comment]
Thanks @kirbyfan64 for the info. Why the lib is not statically linked inside the executable file?

**Comment by ysbaddaden** [comment]
It should be statically linked, since the compiler comes with the static libraries only. Since it dynamically linked against the shared library, I suppose you installed boehm-gc manually and got the shared libraries installed on your development machine. This is because linkers will always link to shared libraries by default.

You may uninstall boehm-gc, then either don't reinstall it if you don't need to build crystal itself, or reinstall it with only the static libraries.

Or you may tell the linker to always use the static library: `crystal compile --link-flags="/usr/local/lib/libgc.a" foo.cr`

**Comment by raydf** [comment]
Thanks @ysbaddaden, that solved the issue.

**Comment by rdp** [comment]
I even got this error running on the *same* machine once. I could not figure it out, ended up just renaming /usr/local/lib/libgc.so to /usr/local/lib/libgc.so.disabled
FWIW (configuring bdwgc with --disable-shared might be another option...maybe...shouldn't the pre-req docs have that specified do you think?).
