### ISSUE TITLE
Unhandled exception in spawn at exit

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2961]
Code:

``` cr
100_000.times do |i|
  STDOUT.print i, "-"
end
```

At some point we get:

```
Unhandled exception in spawn:
end of file reached (IO::EOFError)
[4537507506] *CallStack::unwind:Array(Pointer(Void)) +82
[4537507409] *CallStack#initialize:Array(Pointer(Void)) +17
[4537507368] *CallStack::new:CallStack +40
[4537498073] *raise<IO::EOFError>:NoReturn +25
[4537550533] *IO::FileDescriptor+@IO#read_fully<Slice(UInt8)>:Int32 +117
[4537555412] *IO::ByteFormat::LittleEndian::decode<Int32:Class, IO::FileDescriptor+>:Int32 +68
[4537520786] *Int32@Int::from_io<IO::FileDescriptor+, IO::ByteFormat::LittleEndian:Module>:Int32 +34
[4537550402] *IO::FileDescriptor+@IO#read_bytes<Int32:Class>:Int32 +34
[4537546309] *Event::SignalHandler#run:NoReturn +53
[4537497916] ~procProc(Nil)@./src/event/signal_handler.cr:93 +12
[4537502586] *Fiber#run:(IO::FileDescriptor | Nil) +170
[4537497897] ~proc2Proc(Fiber, (IO::FileDescriptor | Nil))@./src/fiber.cr:29 +9
```

The culprit seems to be [Event::SignalHandler](https://github.com/crystal-lang/crystal/blob/d30f29c439a4044a8d4e0302ed4881f9d4d80b3a/src/event/signal_handler.cr) together with this [at_exit](https://github.com/crystal-lang/crystal/blob/d30f29c439a4044a8d4e0302ed4881f9d4d80b3a/src/kernel.cr#L169) call. This was done by @technorama so I don't know why it was like that, but surely it's a bug. 

@waj any idea? I removed that `at_exit` and it seems to solve the problem, I don't know why we need to shut down a pipe at the end of a process if the process is going to die anyway...

**Comment by sdogruyol** [comment]
This works in master but fails from time to time after printing the result like

```
698-99699-99700-99701-99702-99703-99704-99705-99706-99707-99708-99709-99710-99711-99712-99713-99714-99715-99716-99717-99718-99719-99720-99721-99722-99723-99724-99725-99726-99727-99728-99729-99730-99731-99732-99733-99734-99735-99736-99737-99738-99739-99740-99741-99742-99743-99744-99745-99746-99747-99748-99749-99750-99751-99752-99753-99754-99755-99756-99757-99758-99759-99760-99761-99762-99763-99764-99765-99766-99767-99768-99769-99770-99771-99772-99773-99774-99775-99776-99777-99778-99779-99780-99781-99782-99783-99784-99785-99786-99787-99788-99789-99790-99791-99792-99793-99794-99795-99796-99797-99798-99799-99800-99801-99802-99803-99804-99805-99806-99807-99808-99809-99810-99811-99812-99813-99814-99815-99816-99817-99818-99819-99820-99821-99822-99823-99824-99825-99826-99827-99828-99829-99830-99831-99832-99833-99834-99835-99836-99837-99838-99839-99840-99841-99842-99843-99844-99845-99846-99847-99848-99849-99850-99851-99852-99853-99854-99855-99856-99857-99858-99859-99860-99861-99862-99863-99864-99865-99866-99867-99868-99869-99870-99871-99872-99873-99874-99875-99876-99877-99878-99879-99880-99881-99882-99883-99884-99885-99886-99887-99888-99889-99890-99891-99892-99893-99894-99895-99896-99897-99898-99899-99900-99901-99902-99903-99904-99905-99906-99907-99908-99909-99910-99911-99912-99913-99914-99915-99916-99917-99918-99919-99920-99921-99922-99923-99924-99925-99926-99927-99928-99929-99930-99931-99932-99933-99934-99935-99936-99937-99938-99939-99940-99941-99942-99943-99944-99945-99946-99947-99948-99949-99950-99951-99952-99953-99954-99955-99956-99957-99958-99959-99960-99961-99962-99963-99964-99965-99966-99967-99968-99969-99970-99971-99972-99973-99974-99975-99976-99977-99978-99979-99980-99981-99982-99983-99984-99985-99986-99987-99988-99989-99990-99991-99992-99993-99994-99995-99996-99997-99998-99999-Unhandled exception in spawn:
```

**Comment by ysbaddaden** [comment]
I got this issue countless times while working on the backtrace line numbers, especially when I used `addr2line` because I used to run an external process, which sent a SIGCHLD signal, but the program had started running the `at_exit` blocks, thus closed the IO pipe in SignalHandler, so :boom:

I believe closing the pipe is meant to stop processing signals while we are existing (or make sure it processed them all?), which is a good idea, we don't want signal handling to block the process from exiting, or raising more exceptions because some resources were closed. Yet, the current solution is buggy, because it does raise an exception. Oops.

Maybe we should set a `@closed` variable, and avoid writing signals to the pipe if `@closed` is set? or somewhat verify that the pipe is closed before writing?

**Comment by sdogruyol** [comment]
`@closed` solution really makes sense

**Comment by asterite** [comment]
@ysbaddaden The signal handling code wasn't written by us, and we merged it without reviewing it well ( :-( ) so yeah, it's buggy. I'd either fix it or rewrite it from scratch if there is a better way to do it. Ideally I'd like @waj to participate in this.

**Comment by ysbaddaden** [comment]
The whole idea, if I understand correctly, is to defer signal processing, so they won't block the process longer, which would block the event loop. We thus attach minimal listeners that pass the signal to the handler,  but through the event loop.

The current implementation uses an IO pipe to transfer the signal. This should be changed to a Channel, which would fit better in Crystal, be more portable, avoid file descriptors, and achieve the same —i.e. go through the event loop.

That won't change the issue here, thought.

Do we have to close the channel in a `at_exit` block? Shall we stop or continue handling signals while the process is exiting? I honestly don't know. I'd love some literature about this topic, if someone has any.

**Comment by vlazar** [comment]
Maybe it's already fixed or wasn't an issue on OS X in first place?

I'm running this code continuously for ~10 minutes in dev and release mode with and without `-Dpreviewmt` in Crystal 0.31.1 on MacOS and can't make it fail. Also tried .

```
$ crystal --version
Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```

**Comment by ysbaddaden** [comment]
This was refsctored st some ooint, and shoukdnt happen anymore. Closing.
