### ISSUE TITLE
Why the crystal binary is bigger that others?

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#2975]
## The biggest in my /usr/bin
![big list](http://i.imgur.com/bxS99Me.png)

## Compared with other kanguages
![compared] (http://i.imgur.com/Oosda4B.png)

**Comment by asterite** [comment]
Hi,

1. The compiler statically links LLVM: those are 10MB. You can see this by creating a file:

    ```cr
    require "llvm"

    LLVM.init_x86
    ```

    Then compiling it and checking its size:

    ```
    $ crystal build foo.cr 
    du -h foo
    10M	foo
    ```

2. Crystal isn't optimized to generate small binaries, and in fact, because of how it works, will specialize methods to their specific types, leading to some almost duplicated code in the final executable.

**Comment by faustinoaq** [comment]
@asterite Ok, I understand.
Atom editor is also a heavy program (200mb) but I like it's features

I like Crystal and [DevDocs](http://devdocs.io/) then I do a request:
👉 https://trello.com/c/4NSQDrPF/322-crystal

Saludos

**Comment by kirbyfan64** [comment]
Many of those are either likely symlinks (GCC) or load all their code via separate libraries at runtime (Python). If you add in the cost of the external libraries, then I believe you'll find it to be larger.

**Comment by jhass** [comment]
Looks like the question is answered :)
