### ISSUE TITLE
Provide Enumerable#zip as convenience accessor to Iterator#zip

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#2977]
Maybe i'm missing something, but why .zip is a method of Array? Exactly same code works (if moved to Enumerable) for Tuples and other Enumerable objects, and zip is a part of Enumerable in Ruby library.

**Comment by bcardiff** [comment]
I would agree it is missing in enumerable. 

But I wouldn't use the same code, because it access the [other array elements by index](https://github.com/crystal-lang/crystal/blob/master/src/array.cr#L2006) so the cost would be quadratic instead of lineal.

Copying the second enumerable in an array isn't a nice solution.

So you are left to use [Iterator#zip](https://crystal-lang.org/api/0.18.7/Iterator.html#zip%28other%3AIterator%28U%29%29-instance-method) method that can be used in a lazy fashion.

Maybe we are just needing a `Enumerable#zip` that will use the `Iterator#zip` for convenience.

**Comment by asterite** [comment]
It's what @bcardiff says. To implement zip you need to iterate two enumerables at once, so you need external iteration, but Enumerable only provides internal iteration. This is why there's `Iterator#zip`.

You moved it to Enumerable and it worked with Tuple, but try to see if it works by zipping two `Range`s and you'll notice it doesn't work because you can't index a range with `#[]`. So as for the original issue ("move zip to Enuerable"), I don't think there's much that can be done.

**Comment by konovod** [comment]
Well, now i see the problem. Perhaps it is possible to introduce module that represents objects with indexed acess and move methods like `Array#zip` or `Array#sample` there, but this looks like unnecessary complication, `Iterator#zip` is enough for most cases.

**Comment by jhass** [comment]
I think having a convenience method there is a great idea and in spirit of the original request, I too the liberty to change the proposal accordingly.

**Comment by asterite** [comment]
Since #3725 we have `zip` in `Indexable`, which is the most generic way to define it. So I'm closing this.
