### ISSUE TITLE
what am I doing wrong here?

### ISSUE THREAD

**Issue by sardaukar** [crystal-lang/crystal#3064]
```crystal
module A
  record LegalOpcodeInfoEntry,
    branch : Bool,
    store : Bool,
    types : Array(String),
    desc : String,
    name : String

  record IllegalOpcodeInfoEntry,
    illegal : Bool = true

  alias OpcodeInfoHash = Hash(Int32, LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry)

  record OpcountHash, zero_op : OpcodeInfoHash

  alias VersionsHash = Hash(Int32, OpcountHash)

  ILLEGAL = IllegalOpcodeInfoEntry.new

  Versions = VersionsHash.new

  Versions[1] = OpcountHash.new({
    zero_op: OpcodeInfoHash.new({
      0 => LegalOpcodeInfoEntry.new(
        branch: false,
        store: false,
        types: [] of String,
        desc: "rtrue",
        name: "rtrue",
      ),
      1 => ILLEGAL,
    }),
  })
end
```

The error I get is:
```
no overload matches 'Hash(Int32, A::IllegalOpcodeInfoEntry | A::LegalOpcodeInfoEntry).new' with type Hash(Int32, A::IllegalOpcodeInfoEntry | A::LegalOpcodeInfoEntry)
```

which baffles me a bit :|

**Comment by sardaukar** [comment]
This is an upgrade to a codebase that used to work on 0.12, so I converted the hashes first to NamedTuples then to records as seen here, but stuck at this error.

**Comment by mverzilli** [comment]
This compiles:

```
module A
  record LegalOpcodeInfoEntry,
    branch : Bool,
    store : Bool,
    types : Array(String),
    desc : String,
    name : String

  record IllegalOpcodeInfoEntry,
    illegal : Bool = true

  alias OpcodeInfoHash = Hash(Int32, LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry)

  record OpcountHash, zero_op : OpcodeInfoHash

  alias VersionsHash = Hash(Int32, OpcountHash)

  ILLEGAL = IllegalOpcodeInfoEntry.new

  Versions = VersionsHash.new

  Versions[1] = OpcountHash.new(
    zero_op: ({
      0 => LegalOpcodeInfoEntry.new(
        branch: false,
        store: false,
        types: [] of String,
        desc: "rtrue",
        name: "rtrue",
      ),
      1 => ILLEGAL,
    } of Int32 => LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry),
  )
end
```

**Comment by mverzilli** [comment]
1. Opcount hash is a record, so its initializer receives attributes as named args (noticed you had `{ zero_op: ... }` instead of `zero_op: ...`

2. { 0 => ..., 1 => ... } already creates a `Hash(Int32, LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry)`, which is to say it creates an `OpcodeInfoHash`. So no need to `OpcodeInfoHash.new({...`.

**Comment by mverzilli** [comment]
That said... the error message is baffling, that's undeniable :P

**Comment by sardaukar** [comment]
Thanks, that works - but only if the hash has both a Legal **and** an Illegal entry. Isn't the "|" supposed to denote that it can be one OR the other?

**Comment by sardaukar** [comment]
A bit of background on the choice of structure: this is for an emulator. The target system has had several revisions, so opcodes for Version 1 might have different behavior on Version 3 - when booting up a version X emulator instance, what I do is load all version info (so, for V5 I load versions 1 to 4) and if in version 3 the opcodes map replaces an opcode map key from version 1, that's the desired behavior. The "illegal" entries are for the rare case when an opcode has become illegal from one version to the other. 

If there's a better data structure to use, I'm all ears!

**Comment by RX14** [comment]
This works:
```
module A
  record LegalOpcodeInfoEntry,
    branch : Bool,
    store : Bool,
    types : Array(String),
    desc : String,
    name : String

  record IllegalOpcodeInfoEntry,
    illegal : Bool = true

  alias OpcodeInfoHash = Hash(Int32, LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry)

  record OpcountHash, zero_op : OpcodeInfoHash

  alias VersionsHash = Hash(Int32, OpcountHash)

  ILLEGAL = IllegalOpcodeInfoEntry.new

  Versions = VersionsHash.new

  Versions[1] = OpcountHash.new(
    zero_op: OpcodeInfoHash{
      0 => LegalOpcodeInfoEntry.new(
        branch: false,
        store: false,
        types: [] of String,
        desc: "rtrue",
        name: "rtrue",
      )
    },
  )
end
```

The problem is crystal doesn't type the hash as `Hash(Int32, LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry)`, because there is only `LegalOpcodeEntry` in it.

**Comment by sardaukar** [comment]
Cool - but in my mind, `LegalOpcodeEntry` satisfies `LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry` ... right?

**Comment by asterite** [comment]
Yes, Crystal deduces types from values and upwards, it never considers what the values will be used for to deduce the type. So if you write:

```cr
{1 => :a}
```

Crystal will say: OK, I have one integer key, one symbol value, so the type is `Hash(Int32, Symbol)`. Now, if you want to pass that to a class that expects that to be `Hash(Int32, Symbol | String)`, it won't match. Crystal won't figure this out "from both ends of the equation".

The way to do it right is to either use an alias, like @RX14 said, or write:

```cr
{1 => :a} of Int32, Symbol | String
```

However, in your particular case I think a Hash might not be needed at all. For example, you could have a method that parsed the emulator info and there check the opcode, using a simple `case` or `if/elseif`. The code will be simpler, memory won't be needed for the `Hash` and you won't have trouble with types. As a reference, you can compare these two solutions to a problem: https://github.com/exercism/xcrystal/issues/32#issue-167615333

I just saw your other comment, but no, a `Hash(Int32, LegalOpcodeEntry)` might not be compatible with `Hash(Int32, LegalOpcodeInfoEntry | IllegalOpcodeInfoEntry)`. Imagine the two types are structs, which is actually the case. The binary representation of a union includes an extra member for the type id, so you can't simply assign one hash to the other without doing some binary conversion, and that's why the compiler gives an error.

Yet another way to model this is with hierarchy, like in traditional OOP. You have a base `InfoEntry` struct/class, or even module, and then you have subclasses for each entry type. Then the Hash becomes simpler, `Hash(Int32, InfoEntry)`, although here you'll also have to specify the type in a hash literal.

**Comment by sardaukar** [comment]
Yeah, as I said this "just worked" on Crystal 0.12 - updating it now. Going to revamp it with traditional OOP. Felt at the time that basic hashes were easier and quicker to hash out (pun intended). Still conflicted on having to OOP it instead of just using basic hash merges, but OK. And thanks for the binary representation note, did not know that!

**Comment by asterite** [comment]
I think union types bring a lot of power to the language, but also a lot of confusion. It would probably be good if we eventually improve the error message, even trying to explain why some types are incompatible. Elm error messages will of course be an inspiration :-)

**Comment by sardaukar** [comment]
Yeah, the error message in this really threw me off. Elm is of course the gold standard, but Crystal's are usually good. I'd suggest some better way of outputting types, or using color to highlight the expected and actual, because right now it's a Monkey Island level of pixel hunt around the output for "with" :D

**Comment by sardaukar** [comment]
And finally, logically seeing `A | B` and getting an error because `A` doesn't fit is just... wrong. But I understand the reason now.
