### ISSUE TITLE
Add Illumos/Solaris support

### ISSUE THREAD

**Issue by alhazred** [crystal-lang/crystal#3173]
Would be nice to have illumos/Solaris support (you can use clang-3.8 from the OpenIndiana repository) or at least provide some instructions how to build crystal from sources there.

**Comment by snltd** [comment]
Seconded. I'd be very happy to help with this, but I need something to start me off. As alhazred, some build docs, or even a rough porting guide.

**Comment by RX14** [comment]
@snltd The best place to get a feel of what's required is to look at https://github.com/crystal-lang/crystal/pull/3369.

You can attempt to cross-compile using `bin/crystal build --cross-compile --target <target triple> spec/all_spec.cr` or similar. The main thing you'll have to do is to create a `src/lib_c` directory in the style of the other unixes with correct libc bindings. Then install a bunch of shared libraries and try to link!

Make sure to ask us if you hit any problems.

**Comment by snltd** [comment]
I'm making some progress here. I have a branch of Crystal which can successfully cross-compile. For instance, this command on OS X  produces `test.o`.

`bin/crystal build --cross-compile --target x86_64-pc-solaris2.11 test.cr`

But I can't link that object file on a SmartOS box:

```
$ gcc -o test test.o -L/usr/local/gc/lib -lgc -leven>
Undefined                       first referenced
 symbol                             in file
setup_sigfault_handler              test.o
ld: fatal: symbol referencing errors. No output written to test
collect2: error: ld returned 1 exit status
```

I'm not sure if this is caused by a mistake in the porting I've done, or by my general ignorance of cross-compiling, so I thought I'd ask advice before I start making more changes.

**Comment by snltd** [comment]
I'm making some progress with this. I can cross-compile from OSX to a new `x86_64-pc-solaris2.11` target. For instance, I can make a simple test file `test.cr` into `test.o` with

```
$ bin/crystal build --cross-compile --target x86_64-pc-solaris2.11 test.cr
```

But linking that object file on SmartOS fails:

```
$ cc -o test test.o -lpcre -levent -L/usr/local/gc/lib -lgc
Undefined                       first referenced
 symbol                             in file
setup_sigfault_handler              test.o
ld: fatal: symbol referencing errors. No output written to test
collect2: error: ld returned 1 exit status
```

I'm not sure if this is a problem with my porting work, or my ignorance around cross-compiling in general.  I can obviously see `setup_sigfault_handler` in the source, but no other platforms seem to have to anything special to deal with it. Best to ask for advice at this point, I think, rather than pursue the wrong path.

**Comment by RX14** [comment]
@snltd `setup_sigfault_handler` is defined in [this C file](https://github.com/crystal-lang/crystal/blob/1f3e8b0e742b55c1feb5584dc932e87034365f48/src/ext/sigfault.c#L12) which you can compile with `make libcrystal`. You then need to add it to the linker command as just `src/ext/libcrystal.a`(or an absolute path to the same file).

**Comment by snltd** [comment]
I picked this up again after a long break. Got a (very) simple program cross-compiled, linked, and run, but I can't get crystal itself to build properly. It links, and simple commands like `crystal version` work, but trying to do anything with `build`, `run` etc dumps core.

Here's the stack trace from the core file. I'm kind of out of my depth now.

```
$ pstack core
core 'core' of 16197:   ./crystal eval puts 123
------------  lwp# 1 / thread# 1  ---------------
 00007fffbfffd590 ???????? ()
 00007fffbda406b1 call_user_handler () + 2f1
------------  lwp# 2 / thread# 2  ---------------
 00007fffbda4eb07 __lwp_park () + 17
 00007fffbda47713 cond_wait_queue () + 63
 00007fffbda47cef __cond_wait () + 7f
 00007fffbda47d3d cond_wait () + 1d
 00007fffbda47d79 pthread_cond_wait () + 9
 00000000020cd993 GC_wait_marker () + 13 (pthread_support.c:2214)
 00000000020c5ed2 GC_help_marker () + 22 (mark.c:1229)
 00000000020cd96f GC_mark_thread () + 5f (pthread_support.c:363)
 00007fffbda4e7e4 _thrp_setup () + a4
 00007fffbda4eac0 _lwp_start ()
------------  lwp# 3 / thread# 3  ---------------
 00007fffbda4eb07 __lwp_park () + 17
 00007fffbda47713 cond_wait_queue () + 63
 00007fffbda47cef __cond_wait () + 7f
 00007fffbda47d3d cond_wait () + 1d
 00007fffbda47d79 pthread_cond_wait () + 9
 00000000020cd993 GC_wait_marker () + 13 (pthread_support.c:2214)
 00000000020c5ed2 GC_help_marker () + 22 (mark.c:1229)
 00000000020cd96f GC_mark_thread () + 5f (pthread_support.c:363)
 00007fffbda4e7e4 _thrp_setup () + a4
 00007fffbda4eac0 _lwp_start ()
------------  lwp# 4 / thread# 4  ---------------
 00007fffbda4eb07 __lwp_park () + 17
 00007fffbda47713 cond_wait_queue () + 63
 00007fffbda47cef __cond_wait () + 7f
 00007fffbda47d3d cond_wait () + 1d
 00007fffbda47d79 pthread_cond_wait () + 9
 00000000020cd993 GC_wait_marker () + 13 (pthread_support.c:2214)
 00000000020c5ed2 GC_help_marker () + 22 (mark.c:1229)
 00000000020cd96f GC_mark_thread () + 5f (pthread_support.c:363)
 00007fffbda4e7e4 _thrp_setup () + a4
 00007fffbda4eac0 _lwp_start ()
```

**Comment by ysbaddaden** [comment]
Looks like an issue in fiber context switch asm.

**Comment by snltd** [comment]
Any guesses where I might start looking? I think it's probably beyond the limits of my knowledge, but I don't give up easily.

**Comment by snltd** [comment]
Totally out of my depth now. For the record, what I have done is in a branch at https://github.com/snltd/crystal/tree/feature/solaris-smartos_support

**Comment by HertzDevil** [comment]
From what I could recall, stack traces inside signal handlers are broken because frame pointers were omitted, and also catching `SIGCHLD` with `LibC.signal` isn't actually portable, hence the above core dump. There are no ABI changes since illumos is derived from the very same UNIX System V after which the SysV ABI is called
