### ISSUE TITLE
[Question]: When will v0.19 become official ?

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal#3177]
All in the title !
I'm waiting for 0.19 in the arch repository, and I don't really want to compile master myself (maybe one day).

Is there a known release date ?

Thanks

**Comment by asterite** [comment]
I don't know.

The upgrade to LLVM 3.8 made it difficult to create new releases, because compiling LLVM 3.8 is different than 3.5, which requires newer build tools that are not available in older systems. We could use 3.5 for the next release, and we'll probably do that, but we want to try with LLVM 3.8 a bit more.

Next, compiling the current compiler in release mode never finished. It hangs in the codegen phase where we ask LLVM to optimize modules (so the fault doesn't seem to be on our side). I didn't have time to investigate it, maybe it has something to do with LLVM 3.8...

Finally, I'll be taking two weeks off, so chance of a release if some other core developer does it instead of me, but I don't know if that'll happen.

So the answer is: at least two weeks from now.

**Comment by Bew78LesellB** [comment]
Thanks for your answer, indeed I tried to compile it finally through AUR (yaourt), but it failed to complete.. 

I hope your days off will be resourceful ! 

Keep me updated if there are some news, or just ship it if you can :)

**Comment by asterite** [comment]
We'll probably release 0.19.0 during the next week.
