### ISSUE TITLE
is_a? accepts CONST only ?

### ISSUE THREAD

**Issue by marceloboeira** [crystal-lang/crystal#3185]
Assigning a type to a variable breaks `.is_a?`:

```crystal
"foo".is_a?(String)
# => true
"foo".is_a?(String || Array(String))
# => true
klass = String | Array(String)
"foo".is_a?(klass)
# expecting token 'CONST', not 'klass'
```

**Comment by Exilor** [comment]
That's because is_a? is actually a pseudo method whose argument follows the [type grammar](https://crystal-lang.org/docs/syntax_and_semantics/type_grammar.html) and the type grammar simply works like that.
It's the same reason why ```Int8[4]``` in conventional Crystal code is an instance of ```Array(Int8)``` containing a ```4_i8```, while in the type grammar ```Int8[4]``` is another way of saying ```StaticArray(Int8, 4)```. 

AFAIK the closest you can get to what you want to do is create an alias:
```crystal
alias Klass = String | Array(String)
p "foo".is_a?(Klass) # => true
```

**Comment by marceloboeira** [comment]
@Exilor thanks!
