### ISSUE TITLE
question about instance variable type

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3192]
imagine we have user classes A, B, C, and more as extensions, all classes return different named_tuples. i need to execute class and store result, how to do this? i need to define @result type, but i don't know what type is it.

```crystal
class A
  def exec
    {result: 1}
  end
end

class B < A
  def exec
    {error: true}
  end
end

class C < A
  def exec
    {something: 2.5}
  end
end

class Exec
  def initialize(@instance : A)
  end

  def exec
    @result = @instance.exec
  end
end

p Exec.new(C.new).exec
```

is there any way to declare like this?
`@result : typeof(@instance.exec)`

**Comment by lbguilherme** [comment]
One possible solution to represent this type:

```cr
class DummyA < A
end

p typeof(DummyA.new.as(A).exec)
# (NamedTuple(error: Bool) | NamedTuple(result: Int32) | NamedTuple(something: Float64))
```

The trick it that casting from a child to the more generic type `A` will lead to "A and any subclass of it", known as `A+` internally. Note that doing `typeof(A.new.as(A).exec)` does not work as it will mean "exactly A".

# But...

`typeof` cannot be used in the context of declaring the type of a instance variable. That's why `typeof` will require resolving the return value of methods, which requires a full run of the type inference process. And, as per a few releases ago, this requires the type of all class and instance variable to be known ahead of time. Quite cyclic.

As you can't depend on the return value of methods to specify the type of a instance variable, I believe there is no solution to this.

**Comment by kostya** [comment]
ok, i find that JSON::Type is enough for me, so this works, thanks:

```crystal
require "json"

class A
  def exec
    {result: 1}
  end
end

class B < A
  def exec
    {error: true}
  end
end

class C < A
  def exec
    {something: 2.5}
  end
end

class Exec
  @result : Hash(String, JSON::Type)?

  def initialize(@instance : A)
  end

  def exec
    result = @instance.exec
    h = {} of String => JSON::Type
    result.each { |k, v| h[k.to_s] = v.as(JSON::Type) }
    @result = h
  end
end

e = Exec.new(C.new)
e.exec
p e
```
