### ISSUE TITLE
command line help for available cross-compile targets

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3200]
I'm trying to compile from linux to osx ... but with little success ... a bit of extra docs would be nice

```
crystal build hello.cr --cross-compile --target "x86_64-apple-macosx10.7.0"
```

```
current:
Error: File x86_64-apple-macosx10.7.0 does not exist
```

```
better:
Error: File x86_64-apple-macosx10.7.0 does not exist
available targets are x,y,z from folder xyz
install xyz to get more targets
```

**Comment by keplersj** [comment]
Try this `crystal build --cross-compile --target "x86_64-apple-macosx10.7.0" hello.cr` instead

**Comment by grosser** [comment]
same: Error: File x86_64-apple-macosx10.7.0 does not exist

... must be missing some basic packages ... running this in
manastech/crystal docker container ... ideally a "complete" crystal docker
container would be great, that has latest crystal + cross-compile tools for
all platforms ...

**Comment by luislavena** [comment]
Hello @grosser 

The target specified in `--target` needs to be a target supported by LLVM and Crystal

I believe the target is `x86_64-macosx-darwin`:

```
$ crystal build test.cr --cross-compile --target "x86_64-macosx-darwin"
```

If I'm not mistaken that will only produce an object file, which you will need to use the proper linker for that platform.

Hope that helps somehow.

**Comment by grosser** [comment]
Same :)
Error: File x86_64-macosx-darwin does not exist

... a docker image that can build everything would be handy :D
... not a big issue atm since I'm just playing around, but kind of a sad
showstopper ... having to figure out these dependencies is not fun ...

**Comment by ysbaddaden** [comment]
There is no way to get the list of targets from LLVM —see this [stackoverflow answer](http://stackoverflow.com/a/35061913/199791) for details.

Cross compilation in Crystal won't build an executable but only compile an object file (`.o`) that must be linked into an executable on the target platform itself. In order to build an OSX executable from the object file, you need an OSX host (because we need the OSX linker).

Cross compilation is thus only meant to cross compile the compiler itself (to be eventually linked on the target arch), or to achieve some hacks (eg: compile a static/shared library). This may change in the future, when we'll support ARM or Android that come cross compilation toolchains, but for now cross compilation won't achieve much, except allow to port the compiler to new archs.

**Comment by grosser** [comment]
Thanks for the details ... was hoping to generate a binary for each system and then make these downloadable ... not a common issue I guess ... but useful if you want to write tools in crystal ... generating the object file is not really helping much there ...

`crystal build test.cr --cross-compile --target "x86_64-macosx-darwin"` worked find on the crystallang/crystal docker image, so I think not easy fixes to be had here ... I'll close ...

Just as a crazy idea: have a compile as a service thing that pulls a repo from github and creates the binary ad-hoc ... crystaliz.me/ysbaddaden/foobar -> detects what OS you are on, downloads the repo and responds with a compiled binary :)

**Comment by ysbaddaden** [comment]
The issue is the presence of a tool capable to produce to link an executable for a target. Some targets always provide a toolchain so we can cross compile (eg. mobiles), but most OS don't, so it's hard.

A possibility is using Travis or another CI to build a binary automatically when a tag is created, then uploading it as a GitHub release file, for example.

**Comment by grosser** [comment]
travis has some mac build service I think, so that might work ...

On Mon, Aug 29, 2016 at 12:08 PM, Julien Portalier <notifications@github.com

**Comment by rdp** [comment]
for followers, you can see the list of "triple options" crystal actually supports (and you practically have to use those exact names) here: https://github.com/crystal-lang/crystal/tree/master/src/lib_c

**Comment by ysbaddaden** [comment]
Not exactly. One should always refer to LLVM for the correct triple to use. The targets defined in `src/lib_c` may be tweaked and not exactly reflect the correct LLVM target machine triple.

For example, we have C bindings under `src/lib_c/x86_64-portbld-freebsd`, but the LLVM triple must reflect the ABI version; for example `x86_64-portbld-freebsd10.1` is correct. Same for OpenBSD, we have bindings under `amd64-unknown-openbsd`, but we must specify the ABI, so `amd64-unknown-openbsd6.0` is correct.

A solution to know the correct triple is to ask LLVM itself. For example on the the target machine:
```sh
$ llvm-config --host-target
```

It's harder from the local machine to determine the correct triple for the destination. `llc` can be used to determine a few parameters, but you should refer to documentation to build the correct triple.

**Comment by rdp** [comment]
OK that's good.  Initially on OS X I tried that:

$ llvm-config --host-target
x86_64-apple-darwin16.0.0

which failed as a target, but then when I specify --target "x86_64-macosx-darwin" it worked, I guess that's just a bug and *should* work.  I might look into it sometime, thanks!
