### ISSUE TITLE
strange error with channel initialization

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3206]
```crystal
class A
  @channel : Channel(Nil)?

  def channel
    @channel ||= Channel(Nil).new
  end
end

A.new.channel
```

```
in ./1.cr:5: instance variable '@channel' of A must be (Channel(Nil) | Nil), not Channel::Unbuffered(Nil)

    @channel ||= Channel(Nil).new
    ^~~~~~~~
```

but this works:
```crystal
class A
  @channel : Channel::Unbuffered(Nil)?

  def channel
    @channel ||= Channel(Nil).new
  end
end

A.new.channel
```

**Comment by RX14** [comment]
This is because `Channel(T)` is abstract, and [`Channel(T).new` actually calls `Channel::Unbuffered(T).new`](https://github.com/crystal-lang/crystal/blob/07964d05b999fdfc3ce68fb13fed36c9732f407b/src/concurrent/channel.cr#L23). If you provide a capacity to `Channel.new` it actually creates a buffered channel.

You should be able to implicitly cast child to superclass, but here an explicit cast may fix it.

**Comment by kostya** [comment]
another example:
```crystal
class A
  alias MyChannel = Channel(Nil)

  @ch : MyChannel?

  def ch
    @ch ||= MyChannel.new
  end
end

A.new.ch
```

**Comment by asterite** [comment]
This now works on master
