### ISSUE TITLE
Cannot read big files using File.read (Int32 overflow)

### ISSUE THREAD

**Issue by olbat** [crystal-lang/crystal#3209]
Hello,
I'm trying to load the content of a big file in memory and I used the [`File.read`](https://crystal-lang.org/api/0.18.7/File.html#read%28filename%2Cencoding%3D%3Cspanclass%3D%22n%22%3Enil%3C%2Fspan%3E%2Cinvalid%3D%3Cspanclass%3D%22n%22%3Enil%3C%2Fspan%3E%29%3AString-class-method) method to do so (bad habit from ruby).

Here is the error I got:

```
$ crystal eval 'p File.read("BIGFILE_2GB").size'
negative capacity (ArgumentError)
[4367495] *CallStack::unwind:Array(Pointer(Void)) +87
[4367386] *CallStack#initialize:Array(Pointer(Void)) +10
[4367338] *CallStack::new:CallStack +42
[4345512] *raise<ArgumentError>:NoReturn +24
[4377351] *String::check_capacity_in_bounds<Int32>:Nil +39
[4427979] *File::read<String, Nil, Nil>:String +171
[4427793] *File::read<String>:String +17
[4343431] ???
[4356537] main +41
[139793359363909] __libc_start_main +245
[4341993] ???
[0] ???
```

And even worst:

```
$ crystal eval 'p File.read("BIGFILE_4GB").size'
0
```

I'm working with crystal 0.18.7:

```
crystal --version
Crystal 0.18.7 [68783f1] (2016-07-03)
```

I took a look [at the code](https://github.com/crystal-lang/crystal/blob/68783f1ebdd5b9bbefc8892ddbc200fe1f13bbea/src/file.cr#L387) and it does not seems possible to handle files that are bigger than `Int32::MAX` using [`File.read`](https://crystal-lang.org/api/0.18.7/File.html#read%28filename%2Cencoding%3D%3Cspanclass%3D%22n%22%3Enil%3C%2Fspan%3E%2Cinvalid%3D%3Cspanclass%3D%22n%22%3Enil%3C%2Fspan%3E%29%3AString-class-method) since it's using [`String.new(Int32,&block)`](https://crystal-lang.org/api/0.18.7/String.html#new%28capacity%3AInt%2C%26block%29-class-method) and [`Slice.new(Pointer(T),Int32)`](https://crystal-lang.org/api/0.18.7/Slice.html#new%28pointer%3APointer%28T%29%2Csize%3AInt%29-class-method) that both relies on the usage of `Int32`.

Since I suppose it would be tricky to modify the `String` and `Slice` classes, I was thinking that an exception should be raised if the size of the file that's being read is greater than `Int32::MAX`.

What do you think about it ?

**Comment by jhass** [comment]
Yes, raising an exception sounds good, there shouldn't be a reason to read a 4GB file as a `String` into memory. For things like CSV files line-wsie consumption seems much more efficient.

However `Slice` should probably be able to handle chunks of data larger than that.

**Comment by RX14** [comment]
I agree, Strings should never be larger than `UInt32::MAX`, but slices should probably go up to `UInt64::MAX`.

**Comment by olbat** [comment]
Yes, would be nice to have UInt64 slices to handle big chunks of data.

I was thinking, if an exception is added to `File.read`, a note may be added in the documentation too.

**Comment by ozra** [comment]
Feels rather stupid though to "artificially limit" the coder. Int64 should be the "default int" imo. And even though it's bad practise with such _strings_, I think it still should work.

**Comment by olbat** [comment]
IMO I prefer the way it's done in ISO C with the `size_t` typedef (that's used every time you're using an integer to represent the size of something and defined to be `unsigned int` or `unsigned long int` depending on the arch.). Unfortunately it implies tons of modifications ...

**Comment by olbat** [comment]
I patched using `ArgumentError` since I was not sure about using `IO::Error`.

**Comment by olbat** [comment]
I took a look at the code and was thinking that instead of trying to read the file in one shot the method may use `IO#gets_to_end` / `String.build`+buffer as it's done when an encoding is specified ? (it will be another way to fix the issue)

**Comment by asterite** [comment]
@olbat Why do you need to read the whole file into memory? What do you want to do with that file?

**Comment by olbat** [comment]
@asterite I'm porting a small Ruby script that analyzes and filters large bunch of strings. It's a really small PoC: the algorithm itself is really simple/dump and I wanted to keep the code as close as possible to the Ruby version.

I had no problem to find another way to do it. I understand that's the `File.read` method has not been designed to handle big files into memory and that there is more optimized way to do so. I was just thinking that if there is a known limitation an error should be raised or it should at least be written somewhere.

However I think that loading big text files into memory can be appropriate for applications such as loading models/resources for machine learning algorithms, etc ... .

**Comment by ozra** [comment]
It's also good for when using "really simple/dumb" algos. Which is perfectly alright when doing some one off task and quickly "just want it done" - like batch-processing some docs in an ad hoc way - where optimized or idiomatic code isn't a concern.

It would be really nice if Crystal still kept these scriptish scenarios in consideration (thereby replacing bash, python, ruby and nodejs for those tasks) as long as the changes doesn't penalize "regular use".

**Comment by asterite** [comment]
We can consider these two languages: Java and C#. These are super popular and useful languages, yet their array and string sizes are of type Int32, so they are limited to 2GB (I think in .Net >= 4.5 they lifted that restriction, but you must compile your program with a special flag).

In fact, try reading a file bigger than 2GB in Ruby with `File.read`: I'm getting Errno::EINVAL. I expected Ruby to be able to deal with that, since integers are unbounded. I also get a similar error in Python.

Both Java and C# provide memory mapped files. Maybe we could later implement something like that to map big files to memory. Alternatively, nothing prevents a program from allocating more than 2GB of memory. One could, for example, use several arrays and read several chunks of a file to them, holding more than 2GB total (for example, [check this](https://blogs.msdn.microsoft.com/joshwil/2005/08/10/bigarrayt-getting-around-the-2gb-array-size-limit/)).

My point is that I think it's very uncommon to read so much memory into an array or a string (that is, I guess 90% of the programs out there, and probably more, don't need this). Then, using integer types that depend on the platform is a real pain: you could get different behaviour for the same program on different machines, and this is hard to debug. Using unsigned integers is also troublesome. And there will always be a limit regarding how much one can read into memory. I think 2GB is a pretty good limit, but then you could implement a `BigArray` class if you need it.

I do agree that an error should be raised on overflow. I think the places to do that are in `String::Builder`, `MemoryIO`, and I guess `Slice.new`, `Array.new`, `Deque.new`, etc.

**Comment by olbat** [comment]
@asterite Which version of Ruby or OS did you use ? I just tried to read an 8GB file with Ruby 2.1.5 on a Debian GNU/Linux (x86_64) and did not have any issue ...

Sorry, I'm not really sure to understand how to fix the issue, can you give me extra explanations about it ?

I think that `String::Builder`, `Slice`, ... are not subject to the overflow issue since this classes are working with `Int32`.
The problem with `File.read` is that `File#size` returns an `UInt64` [that's converted](https://github.com/crystal-lang/crystal/blob/68783f1ebdd5b9bbefc8892ddbc200fe1f13bbea/src/file.cr#L387) to an `Int32` to be able to build a string (using `String.new(Int32)`), so it's the only method subject to the overflow.

Did I miss something ?

**Comment by olbat** [comment]
Should I rename the issue "Int32 overflow when reading a big file using File.read" and create a new issue to discuss about loading big files into memory and managing big (Int64) slices/buffers/... of data ?

**Comment by asterite** [comment]
@olbat Don't worry, I will eventually fix this, but right now I don't consider this a high priority

**Comment by olbat** [comment]
@asterite Thank you. As you said, I don't think it's an hight priority issue, especially since it's easy to find an alternative to `File.read` 

A few thoughts ... Just stop me if I'm wrong, but aren't every libc/syscall bindings subject to this kind of problem ?

I mean, since size-related value's standard type is `UInt64` (`size_t`) in most systems and `Int32` in Crystal, there may be other overflows like this one in the standard lib ? (at least if there is other bindings like this one ...)

**Comment by ozra** [comment]
Just because the developers of Java and C# has chosen a bad way of overly conservative carefulness doesn't mean Crystal should. Crystal is better than that. The pointer size obviously changes from 32 bit arch to 64 bit architecture. I think it's only natural and expected that the indexing and sizing capability to be the same width as the pointer of the platform. That they are _not_, is what I rather find peculiar. There's not _anything_ to loose (disclaimer: except in a few rare cases), and then it's not like the computer explodes or anything.

We have these machines to solve problems for us, if we can solve it with five lines of code in 60 seconds and it just works - than we're aiming right. If it doesn't, because it "isn't the right way, and so shouldn't be needed" ("640kB ought to be enough for anyone", anyone? ;-) ) - then I think we're moving our computing technology in the wrong direction.

Well, I'm not sleepless over it - just the two old cents

@olbat - in _some_ systems there are specific stdlib-calls for 64 bit sizing. But it's unfortunately not so in all OS'es.

**Comment by olbat** [comment]
@ozra Oops, sorry, you're right. BTW there is the same problem with `UInt32` (`size_t`) and `Int32` (Crystal)...

**Comment by oltmannsdaniel** [comment]
@asterite So I ran today into the same issue. Is there any way how I can fix that?

**Comment by RX14** [comment]
@oltmannsdaniel Simply cast `size_per_read` to an `Int32`.

```cr
size = File.new("./3GB_of_text.txt").size

# Get parts of files
size_per_read = (size / 4).to_i32

4.times do |i|
    File.new("./data/3GB_of_text.txt").read_at(size_per_read * i, size_per_read) do |data|
        puts data
    end
end
```

**Comment by oltmannsdaniel** [comment]
@RX14 Well, then I ran into the next error:
```
#<File::PReader:0x1a7ff80>
#<File::PReader:0x1a7ff00>
Bytesize out of bounds (ArgumentError)
0x450bf7: *CallStack::unwind:Array(Pointer(Void)) at ??
0x43ebb3: __crystal_main at /opt/crystal/src/file.cr 644:7
0x44ee29: main at /opt/crystal/src/main.cr 12:15
0x7fa2e00eb830: __libc_start_main at ??
0x43e319: _start at ??
0x0: ??? at ??

```

**Comment by oltmannsdaniel** [comment]
@RX14 SSSOOOOLLLLVVVEEDDD 💯 🥇 

Code:
```crystal
file = File.new("./data/3GB_data.txt")
size = file.size

# Get parts of files
size_per_read = (size / 20).to_u

20.times do |i|
  puts file.pos

  file.pos = (size_per_read * i).to_u

  part = Bytes.new(size_per_read.to_u)

  file.read(part)

  output = String.new(part) # Works
end
```

I get the warning, but it wwooorrrkksss!!! The warning is:
```
GC Warning: Repeated allocation of very large block (appr. size 161460224):
        May lead to memory leak and poor performance.
```

**Comment by GregPK** [comment]
@olbat Looks like this is fixed (kind of) and can be closed, right?

**Comment by lribeiro** [comment]
Is there a place where we can define the String `@bytesize` property as UInt64 instead of Int32?

I was experimenting with "UInt64" Strings instead of "Int32", trying to learn the compiler internals,
and I couldn't find `@bytesize` definition inside string.cr or string/*.cr,
grepping it yields

```
src/compiler/crystal/program.cr
196:      string.declare_instance_var("@bytesize", int32)

src/compiler/crystal/codegen/llvm_typer.cr
78:        @llvm_context.int32,                    # @bytesize
```
src/compiler/crystal/program.cr:195
```crystal
      types["String"] = string = @string = NonGenericClassType.new self, self, "String", reference
      string.declare_instance_var("@bytesize", int32)
      string.declare_instance_var("@length", int32)
      string.declare_instance_var("@c", uint8)
```

src/compiler/crystal/codegen/llvm_type.cr:75
```crystal
    def llvm_string_type(bytesize)
      @llvm_context.struct [
        @llvm_context.int32,                    # type_id
        @llvm_context.int32,                    # @bytesize
        @llvm_context.int32,                    # @length
        @llvm_context.int8.array(bytesize + 1), # @c
      ]
    end
```
NOTE: inconsistency between the two places one `@c`is int8 the other uint8, since both types are the same size this is possibly inconsequential.

Changing those places I still can't make it build the compiler.

```
➜  crystal git:(master) ✗ CRYSTAL_CONFIG_PATH="/Users/lribeiro/Work/crystal/src" CRYSTAL_CONFIG_LIBRARY_PATH="/usr/local/Cellar/crystal/0.31.1/embedded/lib" CRYSTAL_CONFIG_BUILD_COMMIT="c86eefef5" ./bin/crystal build --link-flags="-L/usr/local/opt/ruby/lib -L/usr/local/opt/openssl/lib"  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib --error-trace
In src/compiler/crystal/compiler.cr:99:38

 99 | property codegen_target = Config.default_target
                                       ^-------------
Error: instantiating 'Crystal::Config:Module#default_target()'


In src/compiler/crystal/config.cr:43:88

 43 | target = Crystal::Codegen::Target.new({{env("CRYSTAL_CONFIG_TARGET")}} || LLVM.default_target_triple)
                                                                                     ^--------------------
Error: instantiating 'LLVM:Module#default_target_triple()'


In src/llvm.cr:79:18

 79 | if triple =~ /x86_64-apple-macosx|x86_64-apple-darwin/
                   ^--
Error: instantiating 'Regex.class#new(String, Regex::Options)'


In src/regex.cr:253:21

 253 | source = source.gsub('\u{0}', "\\0")
                       ^---
Error: instantiating 'String#gsub(Char, String)'


In src/string.cr:2061:14

 2061 | return gsub(char, replacement.unsafe_byte_at(0).unsafe_chr)
               ^---
Error: instantiating 'gsub(Char, Char)'


In src/string.cr:2066:16

 2066 | return gsub_ascii_char(char, replacement)
               ^--------------
Error: instantiating 'gsub_ascii_char(Char, Char)'


In src/string.cr:2076:12

 2076 | String.new(bytesize) do |buffer|
               ^--
Error: no overload matches 'String.new' with type Int32

Overloads are:
 - String.new(bytes : Bytes, encoding : String, invalid : Symbol | ::Nil = nil)
 - String.new(chars : ::Pointer(UInt8), bytesize : UInt64, size : UInt64 = 0)
 - String.new(chars : ::Pointer(UInt8))
 - String.new(slice : Bytes)
 - String.new(capacity : UInt64, &block)
 - String.new(pull : JSON::PullParser)

```

**Comment by asterite** [comment]
The places you found in the compiler are the ones you are looking for.

There's no inconsistency because i8 is the only type in llvm for representing 8 bits integers. How Int8 and UInt8 work depend on their operations.

To make it work you need to first make the change in the compiler, then compile it to create a new compiler. Then you need to change how string is constructed and used in the std using the new compiler. It can't be done in a single step and that's why it's so hard to change.

But the error you are seeing seems to be because you already changed a constructor from Int32 to UInt64 and there's a type mismatch. Maybe check the error trace? I think it will point you to the right location. Or it should.

**Comment by asterite** [comment]
The error you are getting, it seems bytesize is still returning Int32 but you are passing it to something that expects UInt64. Probably because you are trying to do the change in a single step, which is impossible.

**Comment by lribeiro** [comment]
Thank you for the pointers @asterite. I'm trying now to build the compiler with only the type changes, and afterwards proceed with the changes to the stdlib.

**Comment by wontruefree** [comment]
With https://github.com/crystal-lang/crystal/pull/9569 can the default for slice be `Int64`?

**Comment by asterite** [comment]
@wontruefree I don't think so, Int64 doesn't autocast to anything because it's already one of the largest types. And this is also a return type, autocasting is about input types.

**Comment by Darimac1** [comment]
Test to verify

**Comment by dscottboggs** [comment]
I'm really confused as to why the size type is signed. I understand not wanting to introduce platform dependence (although I personally think it's worth it), but the size of a container being negative makes no sense. Is there some sort of reason it needs to be an int? Doesn't this also slow down C interop because the int32s would need cast as size_t/UInt32?

**Comment by kalinon** [comment]
This is also problematic if you want to get a MD5/SHA for a large file. I cant seem to find a way to do ti.

**Comment by asterite** [comment]
@kalinon Not a problem at all. Read the file by chunks using an IO, pass the IO to the MD5 decoder.

**Comment by kalinon** [comment]
@asterite i tried to do it via:
```
require "digest/sha1"
require "digest/md5"

large_file = "3gb.file"
file = File.open(large_file)

slice = Bytes.new(256000000)

digest = Digest::SHA1.base64digest do |ctx|
  file.read(slice)
  while (slice)
    ctx.update slice
    file.read(slice)
  end
end

puts digest.to_slice.hexstring
```

But it throws the same Arithmetic error i get when doing `File.read` of the 3gb

**Comment by Blacksmoke16** [comment]
Can be closed now I think based on https://github.com/crystal-lang/crystal/pull/10015 being released.
