### ISSUE TITLE
bug HTML.escape

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3233]
``` ruby
irb(main):001:0> require 'cgi'
=> true
irb(main):002:0> CGI.escapeHTML("?a=1&b=2")
=> "?a=1&amp;b=2"
```

``` crystal
require "html"
p HTML.escape("?a=1&b=2")
```

`"?a&#61;1&amp;b&#61;2"`

i don't may be this is correct, i just rewrite some specs for my project from ruby and find it failed

**Comment by kostya** [comment]
ruby uses this
  TABLE_FOR_ESCAPE_HTML__ = {
    "&" => "&amp;",
    "\"" => "&quot;",
    "<" => "&lt;",
    ">" => "&gt;"
  }

**Comment by asterite** [comment]
They were originally those, until this happened: https://github.com/crystal-lang/crystal/pull/2175

As with anything web-related, I don't know what's the correct answer, or which of the RFCs that apply to this case, if any, we should follow.

**Comment by rdp** [comment]
It definitely feels as if something is amiss, because I believe I should be able to do the following:

something.ecr

<a href="<%= HTML.escape my_url %>">...</a>

However with today's HTML.escape, if there are "=" in my_url, I'll end up with a URL like

<a href="http://host/path?id&#61;my_id">...</a>

which is "not the right url" and not received correctly by the host.

Django seems to differentiate "javascript escape" from HTML escapes FWIW. https://docs.djangoproject.com/en/1.10/_modules/django/utils/html/#escape

"rule #1" from the link 

https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet#XSS_Prevention_Rules

from #2175 says for HTML content to escape

```
 & --> &amp;
 < --> &lt;
 > --> &gt;
 " --> &quot;
 ' --> &#x27;     &apos; not recommended because its not in the HTML spec (See: section 24.4.1) &apos; is in the XML and XHTML specs.
 / --> &#x2F;     forward slash is included as it helps end an HTML entity
```

which is quite a similar list, and it also then differentiaites between that, attribute, and javascript escaping.

So sounds like there are a lot of different types of escapes actually used.

I'd be happy to hack up something to have three different escape methods if that would be useful.  What this does mean though, however, is that the current escape mechanism "doesn't work" for (at least) escaping links today and requires local workarounds like this:
 https://github.com/ysbaddaden/frost/commit/896a74b3a4ac9dda162f6a20d757c86bf3b523dd

Thanks all.

**Comment by ysbaddaden** [comment]
Maybe a parameter, or a few methods to selectively encode few or many characters?

**Comment by jazzonmymind** [comment]
there's also [Rack::Utils.escape_html](http://www.rubydoc.info/github/rack/rack/Rack%2FUtils.escape_html). it uses a small hash table, similar to CGI.escape_html.
```ruby
ESCAPE_HTML =
{
  "&" => "&amp;",
  "<" => "&lt;",
  ">" => "&gt;",
  "'" => "&#x27;",
  '"' => "&quot;",
  "/" => "&#x2F;"
}
```

**Comment by rdp** [comment]
Yes, it seems that "normal" escape is those chars.  If I knew what is the
"normal" way to do this in the std lib (multiple method names? params?) I'd
be happy to proceed :)

**Comment by codenoid** [comment]
still open ? :/

**Comment by rdp** [comment]
yes
