### ISSUE TITLE
casting callback to c

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3253]
this is expected to work, but not.
```crystal
cb = ->(x : Int32) { x + 1 }

cbc = cb.as(Void*)

unless cbc.null?
  cb2 = cbc.as(Int32 -> Int32)

  p cb2.call(1)
end
```

```
Error in ./1.cr:4: can't cast Proc(Int32, Int32) to Pointer(Void)

cbc = cb.as(Void*)
```

**Comment by asterite** [comment]
Hmmm, you can't cast a `Proc` to `Void*` because a proc is a 2-element tuple that has the function pointer and the closure data. If you are absolutely sure the proc is not a closure, you can invoke `pointer` on it. Otherwise you'll have to use [Box](https://crystal-lang.org/api/0.18.7/Box.html) (there's a link from there to Proc that explains how to do what you probably want to do, but you'll have to keep the box, not the proc, somewhere for the GC not to collect it)

**Comment by kostya** [comment]
box is ok
