### ISSUE TITLE
RFC String#matches?

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3256]
Wanted to use String#maches? in https://github.com/crystal-lang/crystal/pull/3246 to avoid unnecessary capture overhead ($1 ... maybe others like $`) ... is that needed or somehow made obsolete by compiler smarts ?

**Comment by luislavena** [comment]
Hello @grosser, the only captures done by Crystal is `$~` which is a *global-like* variable (looks like global but is bound and exists only in the method's context that produced it).

Either way, I've done a simple implementation of that, but found that the performance gain wasn't as much to justify it, except for the GC savings (creation of `MatchData` and later destroying).

Also found that you still need to allocate memory for `LibPCRE.exec`'s `ovector` for the captures, if not, the result will be always false. Took a look to PCRE docs but didn't understand it :disappointed: 

Once I get my backup computer running will update with the script.

**Comment by ozra** [comment]
Getting rid of heap allocs should speed an app up. In a micro-benchmark you might not get to the point of a  garbage collection, and so it won't show the potential speed difference?

_Iff_ there is a gain, I would see it as a welcome addition, since it's rather common to use regexps for just testing for match without using the results. (obviously in the case of options parsing it's a drop in the sea, but for tight loops etc.)

As asterite has pointed out `$~` shouldn't be referred to as "global-like" (since it's not global at all), but rather simply "magic var" or something. Nitpicking though...

**Comment by asterite** [comment]
I think we can make `MatchData` be a struct and problem solved.
