### ISSUE TITLE
Type inference: strange behavior with the || operator

### ISSUE THREAD

**Issue by olbat** [crystal-lang/crystal#3266]
The type inference algorithm does not infer the same type when using two equivalent `||` and `&&` expressions:
```crystal
a = b = nil
if rand() >= 0
  a = b = 1
end

pp typeof(a), typeof(b)
# typeof(a) # => (Int32 | Nil)
# typeof(b) # => (Int32 | Nil)

if a && b
  pp typeof(a), typeof(b)
  # typeof(a) # => Int32
  # typeof(b) # => Int32
end

unless !a || !b
  pp typeof(a), typeof(b)
  # typeof(a) # => (Int32 | Nil)
  # typeof(b) # => (Int32 | Nil)
end
```
I think that in this case `a` and `b` should have the type `Int32` in the `unless` block or at least the type inference for equivalent `||` and `&&` expressions should behave the same way ...

```bash
$ crystal --version
Crystal 0.18.7 [68783f1] (2016-07-03)
```

**Comment by olbat** [comment]
I understand that it's not really natural to write the condition using the `||` operator this way.

Here is some code that where it may seems more natural to do such a thing:
```crystal
a = b = nil
# some code
return|raise|abort "some error" if a.nil? || b.nil?
# here "a" and "b" still have the type "(Int32 | Nil)"
```

**Comment by asterite** [comment]
True, though it seems a bit hard to implement. The problem is that in this:

```cr
if a.nil? || b.nil?
  # We can't conclude anything about a or b
else
end
```

The compiler works by first trying to conclude something about the `if` condition, and then negating that conclusion for the `else` branch. But in the case of an `||` over distinct variables there's nothing to conclude about `a` and `b` at the same time, so there's nothing to negate.

I'll leave it as an enhancement, maybe we can find a way to make it work.

**Comment by asterite** [comment]
@olbat For your use case you do do:

```cr
return unless a && b
```

Not quite the same because it won't work if `a` or `b` are booleans, but this is almost never the case.

**Comment by olbat** [comment]
@asterite Yup, that's what I've done to get it working :)

I understand that the fix will be tricky to implement, thanks for the explanation !
