### ISSUE TITLE
Inheritance appears to not work correctly

### ISSUE THREAD

**Issue by jaitaiwan** [crystal-lang/crystal#3272]
Consider the following code

```crystal
class Parent
  @foo = true
end

class Child < Parent
  @foo = false
  
  def initialize
    pp @foo
  end
end

# @foo # => true
Child.new 


class Parent2
  @foo = false
end

class Child2 < Parent2
  @foo = true
  
  def initialize
    pp @foo
  end
end

# @foo # => true
Child2.new
```

You would expect the first return to be `false` and the second to be `true` but they are both somehow `true`. You can see this running [here](https://play.crystal-lang.org/#/r/18u5)

Crystal v0.18.7 macOS sierra + Crystal Playground

This is a pretty interesting bug and I cannot for the life of my determine why this is happening...

**Comment by jaitaiwan** [comment]
In fact, one can see the same example with integers:

```crystal
class Parent
  @foo = 1
end

class Child < Parent
  @foo = 0
  
  def initialize
    pp @foo
  end
end

# @foo # => 1
Child.new


class Parent2
  @foo = 0
end

class Child2 < Parent2
  @foo = 1
  
  def initialize
    pp @foo
  end
end

# @foo # => 1
Child2.new
```

**Comment by jaitaiwan** [comment]
I traced back the issue to see how long its been like this... seems like this has been broken since 0.9.0. 0.8.0 shows the expected output for integers.

**Comment by asterite** [comment]
@jaitaiwan Good catch.

It's working like that because when an instance variable initializer is that type's "zero" (`nil` for nilable types, 0 for numbers, `false` for booleans) then the initializer is skipped. So `false` initializers are skipped and only the `true` ones are executed.

There's also an issue here because all instance var initializers are executed from subclasses to parent classes, but only the deepest initializer should be run for each instance var.

**Comment by asterite** [comment]
Ah, forgot to say that "zero" initializers are skipped because all instances start with the memory set to zero, so setting it to zero again would be redundant... 

Doing this:

```cr
class Parent
  @foo = 1
end

class Child < Parent
  @foo = 2

  def initialize
    pp @foo
  end
end

# @foo # => 2
Child.new

class Parent2
  @foo = 2
end

class Child2 < Parent2
  @foo = 1

  def initialize
    pp @foo
  end
end

# @foo # => 1
Child2.new
```

works as expected, so what I said was wrong: initializers are executed from parent to children, but they shouldn't be skipped if they are zero (in any case I think LLVM will optimize that, or it should be negligible, so I'll remove that "optimization")

**Comment by jaitaiwan** [comment]
Awesome. Yeah it was just the weirdest thing! What is the release timeline on a bug like this? Just wondering if its worth changing our implementation of this to workaround the bug or wait for a release...

**Comment by asterite** [comment]
I plan to release 0.19.1 this Friday with bugfixes and regression fixes.

**Comment by asterite** [comment]
(and I'll probably fix this today in some hours)

**Comment by jaitaiwan** [comment]
Oh fantastic. Thank you!

**Comment by jaitaiwan** [comment]
If I knew how I'd do it myself and submit a PR
