### ISSUE TITLE
`puts` output is interleaved between different fibers

### ISSUE THREAD

**Issue by jefurry** [crystal-lang/crystal#3277]
![1]

why output these? sometime is right.

`MacOS`

[1]: http://www.image-share.com/upload/3316/212.jpg

**Comment by asterite** [comment]
Hi,

Please next time provide code that we can copy and paste. Now I have to type all of that to try it... It would also help if you explained what was your expected output, though in this case I guess you don't want the output interleaved.

`puts(obj)` first prints object, then prints a newline. It might happen that these calls interleave between fibers.

There are several solutions to this:
1. Do nothing: use mutex or something similar, don't assume IOs are fiber-safe (they are not)
2. We could make the top-level `puts` and `print` methods fiber-safe
3. We could have a flag set on IOs to make them fiber-safe. STDOUT would be marked as fiber-safe by default.

I'd start with option 2 for now, as I'm not sure 3 is generally applicable.

**Comment by ysbaddaden** [comment]
There are 2 writes to STDOUT but there is no guarantee that each write will write everything it's supposed to. Well, in this example this is a single byte write.

1. this is how we fixed Logger.

2. Having special care for `::puts` but not for `IO#puts` could be inconsistent.

3. Interesting. IO#write could check whether a lock is set and use it?

**Comment by asterite** [comment]
@ysbaddaden 3. Yes, we could make `IO::FileDescriptor` have a flag `fiber_safe` or similar. Then all writes (and reads?) would synchronize using a mutex. I don't know if this could be generally applied to all IOs because IO is almost abstract, but at least having it in `IO::FileDescriptor` and maybe other IOs provided in the standard library could be useful.

In a way I'd like to think of that as how IO in Ruby is super practical: buffered by default, but you can control that `sync`; it supports encoding and you can set it, etc.

**Comment by jefurry** [comment]
1000.times do |i|
        spawn do
            puts i
        end
    end

    sleep

@asterite thanks, can you provide that right example with sync?

**Comment by asterite** [comment]
@jefurry 

```cr
mutex = Mutex.new

1000.times do |i|
  spawn do
    mutex.synchronize do
      puts i
    end
  end
end

sleep
```

**Comment by jefurry** [comment]
@asterite thanks.
