### ISSUE TITLE
Incorrect error when calling protected method

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#3290]
Update: edited original code because the example was incorrect.

```cr
class Thing
  protected def hi
    puts "hi from Thing"
  end
end

class SomeThing < Thing
  def initialize(@friend : Thing)
  end

  def hi_friend
    @friend.hi
  end
end

class GoodThing < Thing
  protected def hi
    puts "hi from Good Thing"
  end
end

SomeThing.new(Thing.new).hi_friend # => protected method 'hi' called for GoodThing
```

This should work, because `@friend.hi` is invoked from `SomeThing` and `@friend` has the general type `Thing`, so it's OK if `GoodThing` overrides this.

**Comment by asterite** [comment]
Hmm... No, this needs more thought. In Ruby we get the same error.

We could maybe use the rule "inherit from the same type, unless that type turns out to be Reference", but I'm not sure.

**Comment by petertseng** [comment]
Indeed, in Ruby you get the similar error - there is a slight nuance to it - you can call `SomeThing.new(Thing.new).hi_friend` and get "hi from Thing", but you will get the error if you call `SomeThing.new(GoodThing.new).hi_friend`.

So in my view, Crystal is protecting us at compile-time from this mistake because we can't prove that the `Thing` is not a `GoodThing`, on which it would not be legal for `SomeThing` to call `hi`. In the same way, you are not allowed in many languages to override a method and then make it **less** visible. (as the `protected GoodThing#hi` does). So I don't think the behaviour needs to be changed! This can continue to be a compile-time error.

If there **is** anything to be done about this, I would say this:

In the original code, it was slightly confusing to see `protected method 'hi' called for GoodThing` when a `GoodThing` is not involved at all in the line the error occurs. It only made sense when I reduced the example to the minimum.

Would it be better if the compiler told you that `GoodThing` is overriding `hi` and reducing its visibility?
