### ISSUE TITLE
Hash type signature limitation or bug on instance variable types

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#3329]
Hello folks,

Thank you for the newer releases! :sparkles: :sparkling_heart: 

Encountered the following problem when trying to use a Hash as a mapping structure. It was possible for me to use as method signature on the `main` object yet failed to be used as part of `initialize` to set a instance variable.

Version of Crystal: `0.19.2 [d81c32c] (2016-09-16)` (also checked against `master`, `0.19.2+6 [1274a2e]`)
OS: Ubuntu Linux (Willy, 15.10)

The following code:

```crystal
class Foo
end

class Bar < Foo
end

def check(x : Hash(Int32, Foo))
  p typeof(x), typeof(x.values)
end

a = {0 => Foo.new}
b = {1 => Bar.new}
check a # Hash(Int32, Foo), Array(Foo)
check b # Hash(Int32, Bar), Array(Bar)
```

However when attempt to associate it to an instance variable of a class:

```crystal
class CheckFoo
  def initialize(@x : Hash(Int32, Foo))
  end
end

CheckFoo.new b
```

Failed:

```
Error in ./1.cr:22: instantiating 'CheckFoo:Class#new(Hash(Int32, Bar))'

CheckFoo.new b
         ^~~

instantiating 'CheckFoo#initialize(Hash(Int32, Bar))'

in ./1.cr:8: instance variable '@x' of CheckFoo must be Hash(Int32, Foo), not Hash(Int32, Bar)

  def initialize(@x : Hash(Int32, Foo))
                 ^~
```

Now, found that limitation only applies when the hash is passed on the initialize, as I'm able to associate a child instance without issues:

```crystal
class Foo
end

class Bar < Foo
end

class EmptyBar
  @x = Hash(Int32, Foo).new

  def initialize
    @x[0] = Bar.new
  end
end

eb = EmptyBar.new
p typeof(eb.@x), typeof(eb.@x.values), eb.@x.values.first.class
# Hash(Int32, Foo), Array(Foo), Bar
```

Can you confirm if this is a limitation or a bug?

Thank you.

:heart: :heart: :heart:

**Comment by asterite** [comment]
Hi!

What is the method `check`?

In any case, this is how the compiler works: it sees `{1 => Bar.new}` so it says "the key is an integer, the value is a Bar, so the type is `Hash(Int32, Bar)`"... it's not, by default, `Hash(Int32, Foo)`).

The way to solve this is simply to write:

```cr
{1 => Bar.new} of Int32 => Foo
```

**Comment by asterite** [comment]
There have been other discussions about this same subject, it basically boils down to covariance and contravariance. See #1297

But basically, check your code:

```cr
class CheckFoo
  def initialize(@x : Hash(Int32, Foo))
  end
end

CheckFoo.new b
```

What happens if `CheckFoo` now inserts a `Foo` as a value of `@x`? We will be inserting a `Foo` in `b`, which can only have `Bar`, not `Foo`, so it breaks the type system.

**Comment by luislavena** [comment]
> What is the method check?

Apologies, copy&paste failure (updated the first message with it)

```crystal
def check(x : Hash(Int32, Foo))
  p typeof(x), typeof(x.values)
end
```

**Comment by luislavena** [comment]
Thank you @asterite for the promptly follow up.

In my particular case `Foo` and `Bar` are actually `Channel` and `Channel::Buffered`, my service object doesn't need to know if the channel is a unbuffered or a buffered one, but instead that is a channel.

Found it a bit unexpected as `Hash(Int32, Foo)` worked on method signature (matching it) yet it failed as instance variable type.

Following your last comments:

```crystal
class Foo
end

class Bar < Foo
end

class CheckFoo
  def initialize(@x : Hash(Int32, Foo))
    p typeof(@x)
    p @x.values.map &.class
  end
end

b = {1 => Bar.new, 2 => Foo.new}

CheckFoo.new b
# Hash(Int32, Foo)
# [Bar, Foo]
```

And `b = {1 => Bar.new} of Int32 => Foo` also works.

> What happens if CheckFoo now inserts a Foo as a value of @x? We will be inserting a Foo in b, which can only have Bar, not Foo, so it breaks the type system.

Apologies again, but not sure I follow above statement.

Thank you.

**Comment by luislavena** [comment]
Hello, me again :smile: 

Re-reading above, I think will be better if rephrased.

The issue I found interesting (to be either a bug or a limitation) is that method signature is matched and used accordingly, yet initialization is not:

```crystal
class Foo
end

class Bar < Foo
end

def check(x : Hash(Int32, Foo))
  puts "Checking as Foo"
end

def check(x : Hash(Int32, Bar))
  puts "Checking as Bar"
end

check({0 => Foo.new})               # => Checking as Foo
check({0 => Bar.new})               # => Checking as Bar
check({0 => Bar.new, 1 => Foo.new}) # => Checking as Foo
```

Now if `check(x : Hash(Int32, Bar))` is removed, check against `Foo` will be used:

```
Checking as Foo
Checking as Foo
Checking as Foo
```

But the same doesn't happen with `initialize`, which is why raised by question here.

I do understand that if I limited the hash to be just `Bar`, there will be issues when attempting to insert `Foo` in it. That is clear and happens with other samples (as expected):

```crystal
class Foo
end

class Bar < Foo
end

# works
a = [] of Foo
a << Foo.new
a << Bar.new

# compile error on << Foo.new (expected)
b = [] of Bar
b << Foo.new
b << Bar.new
```

Hope that made more sense than my initial question.

Once again, thank you for your time.

**Comment by asterite** [comment]
Yes, there current is a difference between type restrictions (the ones used in method arguments) and the type of instance variables. In your example there are both things: the type restriction in the `initialize` method, but also the compiler uses that type to set the type of the instance variable.

The issue basically boils down to what is described in #1297 . Right now type restrictions are variant (can't remember which one was it, covariant or contravariant), meaning that this works:

```cr
def foo(array : Array(Foo))
end

foo([] of Bar)
```

but it doesn't work when `array` is assigned to an instance variable with that type. This is because the snippet above is harmless, we aren't doing anything with `array`. However, if we do this:

```cr
def foo(array : Array(Foo))
  array << Foo.new
end

foo([] of Bar)
```

we get an error, because `foo`, even though it has a restriction of `Array(Foo)`, is instantiated with `array` being `Array(Bar)`, and we can't put a Foo there.

We could make the above be an error. But what about this?

```cr
def begin_plus_end(range : Range(Int, Int))
  range.begin + range.end
end
```

Should that compile? Seems safe, we aren't putting anything inside Range, just reading it, so it wouldn't seem right to disallow the above.

You can read more about this problem and how they solve it in Java (wildcards) and C# (`in` and `out` type modifiers), we might do something like what C# does in the future, or just leave things like they are now (if you use things well it compiles, if not you get a compile error, so it's always safe).

**Comment by luislavena** [comment]
Thank you for the detailed explanation @asterite, it makes sense now.

More and more thinking some compiler errors should have a verbose description that recommends changes (similar to Rust) so we avoid this type of questions on the issue tracker :sweat_smile: 

Closing now.
