### ISSUE TITLE
IO.read without arguments should return everything ?

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3346]
Was hoping IO.read would work as it does in ruby ... had to settle for the a bit ugly gets_to_end ... would you accept a PR to make 'no argument' mean 'everything' ?

**Comment by RX14** [comment]
Crystal doesn't aim for ruby compatibility, and as such we decide on the best route to take for crystal. In crystal, `String` types can only contain UTF-8 data, and the `Slice(UInt8)` type is the correct type for handing binary data. As such the `IO#read` method is for reading data in to slices, which is efficient because the slice can be reused. `IO#gets_to_end` is a more descriptive method name, and the length doesn't really matter, because it's actually quite a rare method call outside of debugging. Besides, having a method do two unrelated different things, depending on whether it has an argument or not is a bit weird, don't you think?

**Comment by grosser** [comment]
hmm yeah ... returning string or slice would be kind of confusing ... I find using slices/partial reads to be the uncommon thing ... most of the time I need to read whole files and want a string back ... so it's a bit sad that it's not `read -> string` / `slice -> slice` ... but I guess changing that over would break a lot of stuff :(

I find `gets_to_end` a bad name since it is too low level ... I want to "read" this file, not play with an IO object / worry about gets/getc etc details.

**Comment by RX14** [comment]
@grosser Maybe you want [`File.read`](https://crystal-lang.org/api/0.19.2/File.html#read%28filename%2Cencoding%3Dnil%2Cinvalid%3Dnil%29%3AString-class-method).

**Comment by grosser** [comment]
I have an IO from http get .body_io ... so I need to `read` that (returning he io to do streaming/full reads in different situations) ... but yes File.read solves the 99% case of wanting to read a file ... so I guess not worth the trouble of making the 1% case nicer ...

**Comment by trans** [comment]
I have to agree with grosser that this is not very intuitive. `#each_slice` and `#read_slice` would be much clearer. Having `#read` do different things in different but similar classes/modules is confusing. Hence why I ended up here -- b/c there's no way to figure this out without an Internet search.

**Comment by RX14** [comment]
@trans the docs have the correct information on `File.read` and `IO#read`.

The different meanings of `IO#read` and `File.read` comes from `IO` being a stream, and `File` treating files (in general) as strings. For a stream, the most basic read operation you can do is read a sequence of bytes, and for "files are strings", the most basic read operation is to read the file to a string. The root cause of this is that `IO` is largely a crystal thing, while `File`'s interface comes from ruby. I still don't think it's too big of a deal. 

And honestly, if we decided that one name had exactly the same semantics throughout the whole stdlib, we would have some rediculously long names.

**Comment by trans** [comment]
I understand it. It's just not intuitive. If you know one, you don't know the other. When I tried to "read" the IO it didn't work and I had to go to the docs to learn about `gets_to_end`. File is a subclass of IO (through two other classes), so one would intuit the convenience class method `File.read` would likely utilize `File#read`. But it's not, so one has to wonder why it isn't `File.gets_to_end`. Do you see what I mean? I'm just talking about ways to reduce "cognitive load" by using similar names for methods that do similar things. Obviously, that's not always possible, but it is definitely something worth striving for, IMO.

**Comment by asterite** [comment]
Actually, we inherited `File.read` from Ruby, and we *could* change it do `File.gets_to_end`. Maybe we should, I don't know. It's just that the use cases for reading a file's content as raw isn't very useful. But this is a perfectly valid thing to change.

**Comment by trans** [comment]
@asterite If there is an `IO#read(Slice)` why is there no corresponding `IO#each(Slice)`? Every other `read_foo` seems to have an `each_foo`. 

Also, is `write(string.to_slice)` the same as `print(string)`?

**Comment by asterite** [comment]
What would `IO#each(Slice)` do? "Yes" to the second question.

**Comment by trans** [comment]
Along the lines of

```ruby
def each_slice(slice : Slice(UInt8))
    while s = read(slice)
      yield s
    end
end
```

Btw, I noticed there are two definitions of `#each_byte` in IO.

```ruby
def each_byte
    while byte = read_byte
      yield byte
    end
  end
```

```ruby
  def each_byte
    ByteIterator.new(self)
end
```

Wouldn't the second override the first? Or does Crystal "automagically" realize the difference b/c of `yield`?

**Comment by luislavena** [comment]
@asterite 

> It's just that the use cases for reading a file's content as raw bytes isn't very useful.

Actually that is the reason why Ruby added `File.binread` and `File.binwrite`, to be able to write binary data (well, still using Strings for that, but that is a Ruby limitation).

@trans 

> Btw, I noticed there are two definitions of #each_byte in IO.

That is due overloading. The first one will be used when `each_byte` is called with a block while the second one is just the iterator that you move manually to the `next` byte.

**Comment by rdp** [comment]
Somehow the "gets" part of the name is a bit confusing...it's kind of like it's leaking the implementation details somehow.  The "behavior" desired is "read everything" and the implementation underneath is it does a gets to the end.  Maybe it could be named "read_all"?  Oh well there's always monkey patching... :)

**Comment by RX14** [comment]
Its gets because it's a string. A read_to_end method would return a slice.
