### ISSUE TITLE
Binary representation: 0b10000000_i8

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#3381]
Hello,

I've a question on the language design about binary's representation of numbers.

```text
icr(0.19.3) > -0b10000000_i8
 => -128
icr(0.19.3) > 0b10000000_i8
128 doesn't fit in an Int8
```

Maybe should crystal recognize 0b10000000_i8 as -128 right ?

**Comment by ozra** [comment]
It shouldn't consider anything - it should just put the bits in to the chosen bit-width type - provided the bit count suffice.

**Comment by lbguilherme** [comment]
Literals should be treated like big integers with unlimited precision, parsed from the source base (hex, oct, dec, bin), and only then converted to the expected final type. 

`0b10000000_i8` and `128_i8` and `0x80_i8` should all be exactly equivalent, all invalid. Otherwise we would get very odd behaviors such as `0b11111111_i8` being equal to `-1i8`

**Comment by Nephos** [comment]
Ok right, design purposes, thanks for your time !

**Comment by ozra** [comment]
> get very odd behaviors such as 0b11111111_i8 being equal to -1i8

That's the expected behaviour as far as I'm concerned.
