### ISSUE TITLE
sort_by don't unpack tuples

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#3419]
https://carc.in#/r/1c5u

```
a = [ {"a",1},{"b",2} ]
a.map{|x,y| x } #works
a.sort_by{|x,y| x } #fails
```

fails with `Error in line 3: wrong number of block arguments (given 2, expected 1)`

**Comment by luislavena** [comment]
I believe the difference is that `map` uses `yield` and `sort_by` calls the block instead.

Since 0.18, yield tuples will auto-unpack them when the block has more arguments, but that works for `yield` only.

You can workaround that by unpacking manually:

```crystal
a = [{"b", 2}, {"a", 1}]
a.sort_by { |(x, y)| x } # => [{"a", 1}, {"b", 2}]
```

**Comment by asterite** [comment]
@konovod The reason is exactly what @luislavena said. The problem with a captured block is that it becomes a regular function that is passed around, and that function receives exactly two parameters in this case, so auto-unpacking only works for non-captured blocks. Maybe there is a way to make it work, like doing a wrapping function, so I'll mark this as an enhancement.

An alternative you can use here is:

```cr
a.sort_by &.[0]
```

**Comment by konovod** [comment]
Thanks for answers, i unpacked it by hand and it looked like `sources.sort_by! { |tuple| {tuple[0].card.power - tuple[1], tuple[0].card.power} }`, much less readable than with unpacking. But with (x,y) it looks much better.
But why sort_by uses function instead of yield? I've tried to replace call with yield and it looks working: https://carc.in#/r/1c6f . So I'm definitely missing something - the problem is in performance? Or in type checking?

**Comment by luislavena** [comment]
@asterite would this benchmark has some value?

```crystal
require "benchmark"

class Array(T)
  def alt_sort_by!(&block : T -> _)
    sorted = map { |e| {e, yield(e)} }.sort! { |x, y| x[1] <=> y[1] }
    @size.times do |i|
      @buffer[i] = sorted.to_unsafe[i][0]
    end
    self
  end

  def alt_sort_by
    dup.alt_sort_by! { |e| yield(e) }
  end
end

items = [{"d", 4}, {"a", 1}, {"c", 3}, {"e", 5}, {"b", 2}]
one = items.sort_by { |(x, y)| x }
two = items.alt_sort_by { |x, y| x }
pp items, one, two

Benchmark.ips do |results|
  results.report("sort_by:") { items.sort_by { |(x, y)| x } }
  results.report("alt_sort_by:") { items.alt_sort_by { |x, y| x } }
end
```

```
items # => [{"d", 4}, {"a", 1}, {"c", 3}, {"e", 5}, {"b", 2}]
one   # => [{"a", 1}, {"b", 2}, {"c", 3}, {"d", 4}, {"e", 5}]
two   # => [{"a", 1}, {"b", 2}, {"c", 3}, {"d", 4}, {"e", 5}]
    sort_by:   2.22M (± 3.31%)  1.12× slower
alt_sort_by:   2.49M (± 1.95%)       fastest
```

OS: Ubuntu Linux 15.04 (4.2.0-42-generic)
Crystal: Crystal 0.19.4+29 [9119c33] (2016-10-17)

**Comment by asterite** [comment]
@luislavena Definitely! I think we used `&block` there because in other methods it's captured anyway and passed to `quicksort!`, but here the block passed to quicksort is the one passed to `sort!` on the right.

Eventually I'd like the compiler to be smarter and don't produce closures when using `&block`.
