### ISSUE TITLE
Support for "proto-types"

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3436]
Mnemonic devices can be very helpful in making code more clear. So I'd like to propose _prototypes_ as an addition to Crystal. These are simply type definitions for container types that are represented by the very type they are (or will be). Their contents are thus the type(s) they will contain. So for example, a method could be defining having an argument that takes an Array of String like so

``` ruby
    def f( a : [String] )
```

in contrast to

``` ruby
    def f( a : Array(String) )
```

The same pattern applies for all the container types: Hash, Tuple and NamedTuple.

``` ruby
    def f( h : {String=>String} )
    def f( t : {String} )
    def f( n : {String: String} )
```

These prototypes act just like regular types, so they can also be used in all the places regular types are used. In instance variable declarations, for example.

``` ruby
    class Page
      @tags : [String]
```

Initialization is another.

``` ruby
    [Int64].new
```

Container types written in this or similar manner are common in compiled languages. All the major one's have something like it: C (`int[]`), Go (`[]int`), Rust (`[int]`).

Obviously, this isn't a vital must-have feature, but the mnemonics of it are nice, and it would mean a little less typing -- that's always a good thing. Another advantage, one that I think could be easily overlooked, is that it would feel a little more familiar to programmers coming from other compiled languages. 

(Acknowledgement to @RX14 for pointing out to me that it could be used for with `new` too.)

**Comment by bcardiff** [comment]
I like the simplicity of `[T]` instead of `Array(T)`, but I think there are some stones in that path. 

What would be the proposal regarding *an array* with a `String:Class` as element?

Since the title is prototypes I guess you want to use a value for describing the type. So,

The prototyping you envision is just for literals? 
Or would you expect the following to work?

```
p = [Int64]
a = p.new
```

Should it compile if p has other than a sole elements? (not easy to detect in compile time for non literals)

Even though I found a bit too much magical the conversion from a value to type. The value will need to be compile time deterministic due to the nature of crystal.

And we will probably need to deal with unions if we go all that path

```
p1 = rand > 0.5 ? [Int64] : [String]
p1.new # => Array(Int64) | Array(String)
p2 = [ rand > 0.5 ? Int64 : String ]
p2.new # => Array(Int64 | String)
```

if we are only interested in using literals as types, some of this questions go away. Until we need to resolve how/when a literal will need to be turned into a type due to the their usage in a method. Without this the support will be incomplete IMO. But performing analysis that depends on the callee method definition is something to avoid usually.

```crystal
def create(t)
   t.new
end

create [Int64]
```

The only language I know use this kind of syntax is Haskell. But there the literals do not clash with types and that simplify the whole thing a lot.

**Comment by asterite** [comment]
I don't know what "proto-types" are, but we already have this in the language for other types. For example:

```cr
# Pointer
@x : Pointer(Int32)
@x : Int32*

# StaticArray
@x : StaticArray(Int32, 8)
@x : Int32[8]

# Tuple
@x : Tuple(Int32, Char)
@x : {Int32, Char}

# NamedTuple
@x : NamedTuple(x: Int32, y: Char)
@x: {x: Int32, y: Char}
```

We are just missing these for Array and Hash. But... I think the shortcut syntax above already bring a bit of confusion, so I don't know if I'd like to add more. We originally added the `T*` and `T[N]` notation for pointers and static arrays to make writing C bindings easier. Maybe Array and Hash are OK, but we can't generally have this for any types (well, use the name in that case).

**Comment by asterite** [comment]
And a note: this only applies for the type grammar (type declarations, method restrictions, etc.), not regular code.

**Comment by lbguilherme** [comment]
I can't think on anything usable for Hash, but for Array it could be: `String[]`, which is consistent with `String[8]` being a `StaticArray(String, 8)`. But as it can only be used in the type grammar (you can't call `.new` in it) I don't really see much gain.

**Comment by trans** [comment]
Rust uses the notation, `[String;8]`. It can be multi-dimensional too, `[[String;8];10]`. I'm not so keen on the `;`, but maybe something like that would be better for Crystal too.

Thing about `String[8]` is, it clobbers the class method name space for `#[]`. That might not matter in the context of type declarations, but for us programmers it's less than optimal for the same notation to have two different meanings.

**Comment by jazzonmymind** [comment]
i prefer the verbose syntax, it is clearer, the shorthand syntax is a little ambiguous in some cases - i imagine it only gets worse if you start supporting Hash and Array as well. as well as that, i think providing multiple options leads to confusion, it requires you to learn not just one syntax, but at least two. it reminds me a bit of aliased methods in Ruby (map/collect, inject/reduce, etc). i always found that confusing, and then someone might prefer collect over map, or vice versa, which can lead to pointless arguments about which is "better". most projects will decide on one or the other, so there's some consistency throughout the codebase.

just my 2 cents :smile:

**Comment by asterite** [comment]
Closing because of https://github.com/crystal-lang/crystal/issues/3436#issuecomment-254553469
