### ISSUE TITLE
alias SizeT is already defined in /src/lib_c/amd64-unknown-openbsd/c/stddef.cr

### ISSUE THREAD

**Issue by iDev0urer** [crystal-lang/crystal#3443]
After forking and compiling the crystal source code I decided to try and build the docs. As soon as I did I was presented with the error

```
Error in line 1: while requiring "./src/**"

in ./src/lib_c/amd64-unknown-openbsd/c/dirent.cr:1: while requiring "./sys/types"

require "./sys/types"
^

in ./src/lib_c/amd64-unknown-openbsd/c/sys/types.cr:1: while requiring "../stddef"

require "../stddef"
^

in ./src/lib_c/amd64-unknown-openbsd/c/stddef.cr:2: alias SizeT is already defined

  alias SizeT = ULong
  ^
```

**Comment by luislavena** [comment]
Can you provide the command you executed when building the docs?

**Comment by iDev0urer** [comment]
@luislavena `./.build/crystal docs`. Also `./.build/crystal --version` returns `Crystal 0.19.4+35 [2754433] (2016-10-19)`

**Comment by RX14** [comment]
@iDev0urer you need to use `bin/crystal` when working on the crystal compiler.

**Comment by asterite** [comment]
@iDev0urer Use `bin/crystal` or better, just run `make doc`

**Comment by luislavena** [comment]
The case of running `crystal doc` on Crystal's own source code is caused by the multiple platform definitions present in `src/lib_c` directories.

`crystal doc` will attempt to require and load **all** `.cr` files within `src` directory, which is why `make doc` instead points to a single source file: `src/docs_main.cr`

You can use `crystal doc src/docs_main.cr` or `make doc` as shortcut.

Cheers.

**Comment by iDev0urer** [comment]
@luislavena ok! I didn't realize that was included in the `Makefile`.
