### ISSUE TITLE
Allow HTTP::Client.new to accept a URL or URI

### ISSUE THREAD

**Issue by iDev0urer** [crystal-lang/crystal#3455]
Instantiating a new HTTP::Client was confusing for me at first until I realized it wanted a URL instead of a URI. I think it would be nice if it could accept either.

Here is an example of what I tried at first.
```crystal
require "http/client"

client = HTTP::Client.new "http://www.google.com"
response = client.get "/" # => getaddrinfo: Name or service not known
response.status_code
response.body.lines.first
client.close
```

And then when I got rid of the `http://` it worked.
```crystal
require "http/client"

client = HTTP::Client.new "www.google.com"
response = client.get "/"
response.status_code      # => 200
response.body.lines.first # => "<!doctype html>"
client.close
```

At the very least this should be better documented, but I think that if methods such as `get` and `post` accept a url, then `initialize` should as well. Thoughts?

**Comment by RX14** [comment]
The documentation of `HTTP::Client#initialize` [explicitly says](https://github.com/crystal-lang/crystal/blob/master/src/http/client.cr#L102-L106) host, so it doesn't take a `URL` or `URI`. `URL` is a subset of `URI` anyway. Maybe it's a little confusing, but most people shouldn't be using `HTTP::Client.new` anyway, and since the client reuses a TCP connection it seems to be a sensible interface.

**Comment by iDev0urer** [comment]
@RX14 You're right. I was just a little confused in the beginning I guess
