### ISSUE TITLE
Inconsistencies on type variables and extending a generic module

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#3487]
Originally mentioned on Gitter:

https://gitter.im/crystal-lang/crystal?at=581536de0e25dbfa1176ecce

The following code fails to compile:

``` crystal
module Foo(T)
  macro extended
    @@foo : Array(T)
  end

  def foo
    @@foo
  end
end

class Bar
  extend Foo(Int32)
end

pp typeof(Bar.foo)
```

```
>  1.     @@foo : Array(T)
   2.   

undefined constant T
```

However, generic `T` is available to `included` and `inherited` macros without issues:

``` crystal
module Foo(T)
  macro included
    puts T
  end
end

class Bar
  include Foo(Int32) # => Int32
end
```

``` crystal
class Foo(T)
  macro inherited
    puts T
  end
end

class Bar < Foo(Int32) # => Int32
end
```

Unsure if this inconsistency is a bug or intended, so opening this issue to confirm. In case is intended, we might need to update the documentation for `extended` macro.

Thank you. :heart: :heart: :heart:

**Comment by asterite** [comment]
I've analyzed this and I don't think it's an inconsistency. You should use `included` to declare the class variable.

The types are looked up in the ancestors chain. Given `Bar < Foo` the type will be first looked up in Bar, then in Foo, etc. When you include a module into a type it is inserted in the ancestors chain. When you extend a module it is inserted in the **type's class** chain. That means that if you extend Bar with Foo you get `Bar:Class < Foo`. When looking up a type in Bar you don't look up a type in `Bar:Class` and then in its ancestors. It will be a bit confusing, because what do you look first, the included modules or the class?

So I think this is working as expected.

**Comment by luislavena** [comment]
Thank you @asterite for the detailed response, first wasn't sure but after thinking a bit more the context of `extend` made total sense.

Closing this out.

Cheers.
