### ISSUE TITLE
Literal arguments

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3508]
I got kind of excited when I discovered the following code compiled without errror.

```ruby
def foo(tag : String, value : String)
  p value + "!"
end

def foo("string", value : String)
  p value
end

foo("string", "foo")
```

Unfortunately, it did not work as I had hoped -- the output is:

```
"foo!"
```

It would be awesome if we could use literals in arguments. 

Classic example of the functional definition of factorial:

```ruby
def fact(0)
  1
end

def fact(n : UInt)
  fact(n - 1)
end
```

**Comment by asterite** [comment]
Hm, that should probably be a compile error.

The reason it works is because you can do something like this:

```cr
def foo("some parameter" param)
  param + 1
end

puts(foo "some parameter": 10)
```

Probably a hidden feature for many :-)

(it's using external names, which can be any string, even with spaces)

Now, external names are optional, and just specifying an external names without an internal one will use that name for both things... but it doesn't make sense to do that with a string literal, so it should be a compile error.

Regarding overloading by value, this is something that many want (I think even @waj wants it, or wanted it some time ago), but even though it might be useful or "cute" for numbers and string, it's not much different than using an `if`. In several functional languages you can use numbers and strings, but also lists, tuples and recrods/structs (Erlang/Elixir) to pattern match data, but I can't see how would that translate to Crystal... would you only be able to pattern match numbers and strings? Would we need to define new syntax to pattern match arbitrary types? That seems like the language will change a lot, and I personally never needed this in an imperative/OOP language. I did need it in a functional language because, well, the language doesn't provide another way of doing this, you only have pattern matching in your toolbox.

There's also the thing that each overload can have a different type, and the compiler knows the type of the arguments so it can know the overload beforehand. This is not the case with values: the compiler doesn't track the flow of values. So multiple overloads will collapse into a common return type (a union).
