### ISSUE TITLE
#as call with implicit receiver when being a method argument fails

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3547]
This code fails to compile:
```crystal
class Foo
  def bar
    print as Foo
  end
end
Foo.new.bar # => unexpected token: as
```
Replacing ```as```with ```as?``` or other pseudo methods does not incur the error, which I guess is a leftover from when ```print as Foo``` meaning ```print().as(Foo)``` instead of ```print(self.as(Foo))``` was deprecated.

**Comment by dylandrop** [comment]
To clarify, you'd expect the output to be

```crystal
print(self.as(Foo))
```

Yes?

**Comment by Exilor** [comment]
@dylandrop Exactly. It's the behavior of ```as?``` and ```is_a?``` which are also hardcoded methods that take one argument.
Right now you can do:
```crystal
class Foo
  def bar
    print as? Foo
  end
end
Foo.new.bar # prints #<Foo:0x176dfc0>
```
and
```crystal
class Foo
  def bar
    print is_a? Foo
  end
end
Foo.new.bar # prints true
```

**Comment by dylandrop** [comment]
Yup, makes sense to me.

**Comment by dylandrop** [comment]
I found [the perpetrator](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/syntax/parser.cr#L3887):

```crystal

    def parse_call_args_space_consumed(check_plus_and_minus = true, allow_curly = false, control = false)
      if (@token.keyword?(:as) || @token.keyword?(:end)) && !next_comes_colon_space?
        return nil
      end
```

Commit: https://github.com/crystal-lang/crystal/commit/09207b42b680c92276c6c8992b23030c342ca22f (It's actually quite old)

When I removed that, everything works. However, it's probably easier said than done, so I'll set up a PR and see what the @asterite thinks since after all, @asterite wrote it.

**Comment by dylandrop** [comment]
@Exilor see PR ^.

**Comment by Exilor** [comment]
Thanks man, I get completely lost when I browse the compiler's source 😁

**Comment by dylandrop** [comment]
@Exilor As a first-timer, I gotta say it was quite an experience 😁
