### ISSUE TITLE
Improve polymorphism for #each

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3665]
I have been thinking about polymorphism with regards to static typing and it has become clear to me that methods of the same name of essentially the same usage should have the same signatures wherever possible. Doing so makes the language more flexible as it allows union types to use common behaviors.

It that light, I'd like to propose that `Array#each` also be able to handle two parameters.

    ["A", "B", "C"].each { |i, v| ... }

Where `i` would be the index `(0, 1, 2, ...)`. This would make it polymorphic with `Hash#each` -- an array's index and a hash's key are analogous, serving the same basic purpose. In addition `Hash#each`, when only taking a single block argument, should iterate over the value, not the tuple pair. 

    {"A" => "X"}.each do |v|
       v  #=> "X"
    end

To iterate over the tuple pair another method would be needed (e.g. `each_pair`). This would be defined for both Array and Hash.

This would then allow `(Array | Hash)#each` to work without unnecessary compile errors.

**Comment by dylandrop** [comment]
If I originally had a loop such as 

```crystal
["A", "B", "C"].each { |v| ... }
```

upon adding a second argument, that first parameter suddenly referring to an entirely different value, which is a bit counterintuitive to me. Also considering most people coming from Ruby would just expect to use `each_with_index`, it might cause more confusion than good. I don't know how strong of an argument that is for the Crystal community though, considering I'm brand new to it.

**Comment by ysbaddaden** [comment]
The proposed changes would seem highly unnatural to me. I'm always pesting against jquery's `$.each(index, value)` for example. I'd pest against a `Hash#each(value, key)` too.

I used to mix Hash and Array types before, but since I started using Crystal, I started to understood how fundamentally different they are: Array is aligning a collection of values, when Hash is mapping values for keys. I never mix them anymore.

**Comment by RX14** [comment]
Is there any reason why you can't just treat them differently?

**Comment by trans** [comment]
> Is there any reason why you can't just treat them differently?

That can be true for everything. Why even bother with OOP?

Polymorphism is a basic advantage of OOP. Take advantage of it wherever possible.

**Comment by asterite** [comment]
But this is already possible:

```cr
a = [1, 2, 3]
h = {"x" => "y", "z" => "w"}

[a, h].each do |v|
  v.each_with_index do |x, i|
    p x, i
  end
end
```

Here `x` will either be an `Int32` (comes from the Array) or `Tuple(String, String)` (comes from the Hash). And `i` will be the index. Then inside the block you can switch based on `x`'s type.

But, as @ysbaddaden , you shouldn't normally have to mix arrays and hashes.

I'm closing this because there isn't much chance that we'll change any of this.
