### ISSUE TITLE
Error when overloading `initialize` in classes with an Abstract superclass.

### ISSUE THREAD

**Issue by ruivieira** [crystal-lang/crystal#3670]
This code fails to compile

```crystal
abstract class Foo
  def initialize(a : Array(Float64), b : Array(Float64))
	@x = a
  	@y = b
  end
end

class Bar < Foo
def initialize(a : Array(Float64))
    @x = a
    @y = a
  end
end

bar = Bar.new(a: [1.0, 2.0], b: [3.0, 4.0])
```

with the following error:

```crystal
Error in line 15: no overload matches 'Bar.new', a: Array(Float64), b: Array(Float64)
Overloads are:
 - Bar.new(a : Array(Float64))
```

@cjgajard suggested this workaround:

```crystal
class Foo
  def initialize(a @x : Array(Float64), b @y : Array(Float64))
  end
end

class Bar < Foo
  def initialize(a : Array(Float64))
    super a, a
  end
end

class Baz < Foo
end

p Bar.new([1.0])
p Baz.new([1.0], [2.0, 3.0])
```

Code compiled with Crystal 0.20.1 on macOS Sierra (10.12.1)

**Comment by asterite** [comment]
Ths second snippet is **correct**, and it's not a workaround. Defining `initialize` in a subclass hides any initialize in the parent class. This is because if you were able to directly invoke an `initialize` in a superclass then some variables might be left uninitialized. For example:

```cr
class Foo
  def initialize
    @a = 1
  end
end

class Bar
  def initialize(@b : Int32)
    super
  end
end

b = Bar.new(1) # OK
b = Bar.new    # Oops, @b wasn't initialized
```

In any language with constructors there's no way to invoke a superclass constructor. You have to invoke the bottom-most one.
