### ISSUE TITLE
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded: ignored.

### ISSUE THREAD

**Issue by zhuangbiaowei** [crystal-lang/crystal#3676]
I just download 0.20.1, my OS is ubuntu 12.04

I type the command: 

~/crystal-0.20.1-1# crystal
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded: ignored.
/root/crystal-0.20.1-1/embedded/bin/crystal: error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory

**Comment by Sija** [comment]
Have you installed [all required libraries](https://github.com/crystal-lang/crystal/wiki/All-required-libraries)?

**Comment by ysbaddaden** [comment]
You don't have to install all required libraries unless you want to hack or compile Crystal itself.

Linux Crystal binaries require libpthead which can't be found, or maybe it has another local name. What happens if you use the Ubuntu repository (see instructions in crystal docs) instead of the tarballs?

**Comment by asterite** [comment]
Hi @zhuangbiaowei , did you have any progress on this by following the suggestion above?

**Comment by sdogruyol** [comment]
Can we close this?

**Comment by asterite** [comment]
Too old and needs more info. Reopen if it's still an issue.

**Comment by summershrimp** [comment]
Hi, this is not a issue from your project. I think @zhuangbiaowei and I are colleagure, and libachk.so is a monitor library in our company's cloud vm.
