### ISSUE TITLE
Union inconsistency

### ISSUE THREAD

**Issue by TechMagister** [crystal-lang/crystal#3687]
**Crystal 0.20.1 [18e7617] (2016-12-05)**
**OS : Linux**

Union are working half as expected in this case : 
```crystal 
alias MyType = Int32 | String | Array(MyType)

my_hash = Hash(String, MyType).new

# this is ok, giving [1, 2, 3] is recognized as a MyType
def do_something(t : MyType)
  t.is_a? Array(Int32)			# => true
end

arr = [1,2,3]
do_something arr             # Working
my_hash["a"] = arr           # Compilation error here ??
```

The Array(Int32) is well recognized as a MyType ( Array(MyType) ) when given as function argument but not when giving it to the hash.
```
instance variable '@value' of Hash::Entry(String, MyType) must be MyType, not Array(Int32)
```

**Comment by RX14** [comment]
I think we need a well written up answer in a section of the crystal docs about this.

**Comment by asterite** [comment]
Hi,

Maybe it's an inconsistency, but it's the way it works. Type restrictions are different than proper types. For example:

```cr
def foo(x : Range(Int, Int))
end

foo 1..10 # Works
p typeof(1..10) # => Range(Int32, Int32)
```

We are passing `Range(Int32, Int32)`. The restriction says "I accept a Range where both components are ints", and since Int32 < Int, it works.

In the case of the alias, `Array(Int32)` can be matched against `Array(MyType)` because `MyType` can also be `Int32`... however, it's incorrect to put an `Array(Int32)` inside an `Array(MyType)`.

Check https://github.com/crystal-lang/crystal/issues/1297

I'm closing this. We'll eventually solve this. I think this is one of the points that bring people most confusion... but then again, you should really try to avoid using unions and recursive types if possible.
