### ISSUE TITLE
HTTP::Handler as a module

### ISSUE THREAD

**Issue by andrewhamon** [crystal-lang/crystal#3690]
Because modules can also have abstract methods, I see little reason to use abstract classes unless there is a reason to impose a particular class hierarchy. To that end, I think it would be generally more useful if `HTTP::Handler` was a module that could be included in to any class.

Given that `HTTP::Handler` is probably a very often inherited from class, I realize that a change would probably break a lot of existing code. Perhaps instead there could be a differently named module that is identical to the class. Maybe `HTTP::Handleable`?

**Comment by asterite** [comment]
I think we could change it to be a module, after all it's almost like an interface. Do you have a specific use case in mind? HTTP handlers are usually handlers, not something else that you inherit from a base class.

**Comment by luislavena** [comment]
In my case, I have an scenario for a similar requirement. I have `Router` which currently inherits from `HTTP::Handler`.

The router is also used by the router in order to build the mount points or related constraints to other router instances.

This router is also capable of mount `HTTP::Handler` instances, so using the module signature/type instead of the inheritance might freed us to have different handlers without the inheritance constraint.

Of course, right now we are fine with current approach, but sometimes composability is more encouraged than inheritance.

Cheers.

**Comment by andrewhamon** [comment]
Routers are what made me bump into this issue specifically.

Suppose I have a `Route`, which is similar to but not quite a `Handler`. They shouldn't really be used as a `Handler`, since the matchers on the `Route` don't get called during `call`, so it would just be really weird.

Now, suppose I have a `Router`, which is a container of `Routes`. But! Routes can be nested. So `Router < Route`. Obviously a `Router` should be `Handler` as well, but now theres trouble since it already inherited in `Route`.

Another thought I had is that a Proc can already be a handler as a special case. If there were a Handler module that could just be included in Proc.

**Comment by andrewhamon** [comment]
I got up and running with the std lib finally, so I decided to make a quick and dirty pull request.

**Comment by petehuang** [comment]
Seems like everything's slick here and we can close this issue? 😃
