### ISSUE TITLE
expect_raises message does an inclusion check instead of absolute check

### ISSUE THREAD

**Issue by samueleaton** [crystal-lang/crystal#3707]
In a spec, when doing `expect_raises MyError, "my message" do...` it does an inclusion check (e.g. string.includes? "") instead of actually checking if the messages are equal.

The code in question is [here](https://github.com/crystal-lang/crystal/blob/master/src/spec/expectations.cr#L272).

When looking at a comparable library (rspec) they do an [absolute check](https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/fuzzy_matcher.rb#L15): `return true if expected == actual`

The problem is that if my spec is like this:
```ruby
expect_raises MyError, "invalid value 12" do
  MyClass::do_something
end
```

...with the following class...

```ruby
class MyClass
  def self.do_something
    raise MyError.new("invalid value 1201")
  end
end
```

It will pass the spec (but it shouldn't!). In my class the message is `"invalid value 1201"` but in my spec its `"invalid value 12"`, but because the actual message includes the entire spec message, it passes. **This doesn't seem safe.**

If there is a good reason for it to work this way, let me know, otherwise I'd be happy to make a PR.

**Comment by asterite** [comment]
In exception specs I usually don't care about the full message, only part of it. For example I often check that the compiler says "undefined method" instead of "undefined method blah blah blah". I wouldn't mind changing it to an equality comparison for string, one can use regex for inclusion... but I personally never want equality (error messages change/improve over time and it's tedious to change all of the tests just because you did a minor change)

**Comment by straight-shoota** [comment]
Since #3709 is closed, I think this could be closed, too.
