### ISSUE TITLE
allow JSON.mapping load from JSON::Any

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3743]
this is useful for such apis:
```crystal
data1 = %q<{"job": "some1", "args": {"a":1, "b": "2"}}>
data2 = %q<{"job":"some2", "args": {"c":[1,2,3]}}>

class Data
  JSON.mapping({job:  String, args: JSON::Any, some_other_params: ...})

  def worker
    case job
    when "some1" then Some1.from_json(args)
    when "some2" then Some2.from_json(args)
    end
  end
end

class Some1
  JSON.mapping({a: Int32, b: String})
end

class Some2
  JSON.mapping({c: Array(Int32)})
end

Data.from_json(data1).worker.do_something
Data.from_json(data2).worker.do_something
```

or maybe introduce type JSON::RawString, which just save part of json as string.

**Comment by asterite** [comment]
You can use `String::RawConverter`, which should also be a bit more efficient as the object is not parsed twice:

```cr
require "json"

data1 = %q<{"job": "some1", "args": {"a":1, "b": "2"}}>
data2 = %q<{"job": "some2", "args": {"c":[1,2,3]}}>

class Data
  JSON.mapping(
    job: String,
    args: {type: String, converter: String::RawConverter},
  )

  def worker
    case job
    when "some1" then Some1.from_json(args)
    when "some2" then Some2.from_json(args)
    end
  end
end

class Some1
  JSON.mapping({a: Int32, b: String})
end

class Some2
  JSON.mapping({c: Array(Int32)})
end

p Data.from_json(data1).worker
p Data.from_json(data2).worker
```

[In play](https://play.crystal-lang.org/#/r/1hh5) :-)

**Comment by asterite** [comment]
This should probably be documented in `JSON.mapping`'s docs, or be provided as a shortcut via `raw: true` because I think it's pretty useful.

**Comment by kostya** [comment]
is it parsed twice? how it can be fixed?

**Comment by asterite** [comment]
`String::RawConverter` will parse into a raw string. So if you have `{"args": [1, 2 ,3]}` no array will be created for `[1, 2, 3]`, just a String containing "[1, 2, 3]" (it is "lexed" to check that the contents are valid, though). Using JSON::Any is slower and consumes more memory, because it will be parsed to an `Array(JSON::Type)`, and from there we'd need to create different instances.

I don't know what is the best solution to this. Maybe it can be done "on the fly" if you can assume that "job" will come before "args", but I wouldn't make that assumption.

**Comment by kostya** [comment]
so there is no something like this?
"[1,2,3]" => [1,2,3] => to_json => "[1,2,3]"

if no, there is ok.

**Comment by DougEverly** [comment]
`String::RawConverter` works _if_ the raw, unparsed JSON is a value of a known key.

It does not work in the following case, where the I need to inspect a key (`type`) to determine how to process the peer keys. Here is a _real_ example from Slack RTM API:

```javascript
{
	"type": "presence_change",
	"presence": "active",
	"user": "U1B6P071B"
}
```

```javascript
{
	"type": "reaction_removed",
	"user": "U1B602ZD1",
	"item": {
		"type": "message",
		"channel": "C1B6MMY7M",
		"ts": "1483578604.000003"
	},
	"reaction": "blush",
	"item_user": "U1B602ZD1",
	"event_ts": "1483578783.674957"
}
```

To inspect the `type`, I'd have already parsed this level into `JSON::Any`. Since this would already be a `JSON::Any` object, it would be nice to subsequently pass it on to `from_json()` to instantiate `PresenceChange` or `ReactionRemoved` objects for example.

**Comment by kostya** [comment]
https://play.crystal-lang.org/#/r/1j70

seems there little extra cost of parsing, but when key is first, it should be very small.

**Comment by RX14** [comment]
For reference, this is how discordcr handles a similar problem, although it's quite a bit easier due to the changeable data being inside it's own key: https://github.com/meew0/discordcr/blob/master/src/discordcr/client.cr#L193

**Comment by DougEverly** [comment]
JSON `String` and `JSON::Any` are two ways representations of the same data, therefore, for API completeness, I'd think anything that takes a `String` that is JSON parseable, should also be able to also accept `JSON::Any`.

That said, the PullParser solution will work. Thanks.

**Comment by DougEverly** [comment]
I implemented PullParser inspection here. Works like a charm!

https://github.com/DougEverly/slack.cr/blob/PullParser/src/slack/event.cr#L66
