### ISSUE TITLE
Can't create Socket::IPAddress for localhost

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#3780]
```cr
require "socket"

Socket::IPAddress.new("localhost", 1234) # => Invalid IP address: localhost (Socket::Error)
```

@ysbaddaden Any idea how to fix this? Someone mentioned this issue [here](https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/PYURCY11quE)

**Comment by ysbaddaden** [comment]
IPAdress has always been about representing an IP address (`::1` or `127.0.0.1`) whereas `localhost` requires a DNS lookup —i.e. looking into `/etc/hosts`.

For the moment we must use `Addrinfo.resolve(localhost, 1234)` instead, which also accepts an IP btw. Then you may call `.ip_address` on it, or simply pass the addrinfo to the Socket methods, they accept it directly, which avoids an intermediary Object.

**Comment by miketheman** [comment]
@ysbaddaden I'll agree that IPAddress was always mean to represent an IP only, but there's no other apparent way to resolve a name to an IP before this change.

With the new Addrinfo, I tried:
```crystal
require "socket"

host = "localhost"
port = 1234

address = Socket::Addrinfo.resolve(host, port)
```

This gets me:
```
wrong number of arguments for 'Socket::Addrinfo.resolve' (given 2, expected 4..6)
Overloads are:
 - Socket::Addrinfo.resolve(host, service, family : Family, type : Type, protocol : Protocol = Protocol::IP, timeout = nil, &block)

address = Socket::Addrinfo.resolve(host, port)
                           ^~~~~~~
```

So I modify:
```crystal
address = Socket::Addrinfo.resolve(host, port, Socket::Family::INET, "SOMETHING")
```

And I receive:
```
'Socket::Addrinfo.resolve' is expected to be invoked with a block, but no block was given

address = Socket::Addrinfo.resolve(host, port, Socket::Family::INET, "SOMETHING")
                           ^~~~~~~
```

When adding a block, I then get into deeper confusing behaviors:
```crystal
address = Socket::Addrinfo.resolve(host, port, Socket::Family::INET, Socket::Type::DGRAM) do |addrinfo|
  p addrinfo
end

Error in resolve.cr:8: instantiating 'Socket::Addrinfo:Class#resolve(String, Int32, Socket::Family, Socket::Type)'

address = Socket::Addrinfo.resolve(host, port, Socket::Family::INET, Socket::Type::DGRAM) do |addrinfo|
                           ^~~~~~~

in /usr/local/Cellar/crystal-lang/0.20.3/src/socket/addrinfo.cr:35: instantiating 'loop()'

        loop do
        ^~~~

in /usr/local/Cellar/crystal-lang/0.20.3/src/socket/addrinfo.cr:35: instantiating 'loop()'

        loop do
        ^~~~

in /usr/local/Cellar/crystal-lang/0.20.3/src/socket/addrinfo.cr:43: no overload matches 'raise' with type Socket::Addrinfo
Overloads are:
 - raise(ex : Exception)
 - raise(message : String)

              raise error if error
              ^~~~~
```

So I return to the question raised in the mailing list thread - should we have a Resolv-like library that provides convenience methods around resolving addresses, or should we continue to make it part of the Socket module?

Since 0.20.3 is there any straightforward way to resolve IPs from names?

**Comment by miketheman** [comment]
Conversely, the `.bind` method still accepts a dns name:

```crystal
require "socket"

host = "localhost"
port = 1234

server = UDPSocket.new
server.bind(host, port)
```

That server will work correctly, but only if the `client` sets their host to 127.0.0.1 and not `localhost`.

**Comment by ysbaddaden** [comment]
`Socket#bind(host, port)` uses `Socket#Addrinfo.resolve` internally, which can be quite confusing to use, I admit. I'd love a better design, but there are a bunch of constraints; mostly: avoid intermediary structs (or worse, HEAP), avoid raising if we can't connect (raising is expensive) until we tried all the possible `Addrinfo`, ...

DNS is made in such a way that we can't resolve a domain to an unique IP but to many, which will differ depending on the service (http, domain, mail, ...), but still possibly returning many IP for a single service... Even `localhost` may return `127.0.0.1` as well as `::1` or even `127.0.1.1` and maybe even more addresses.

I added documentation and a non block form of `Addrinfo.resolve` that returns an `Array(Addrinfo)` in #3781, so it's nicer to use and less confusing than the block form. What do you think?

**Comment by ysbaddaden** [comment]
@miketheman I don't understand how [your example](https://gist.github.com/miketheman/e024f69879fa4ef52653f90492ca1c79) ever worked. Passing `localhost` to `IPAddress.new` was accepted, because it wasn't validated, but trying to pass it to C functions would have failed just the same, because of the call to `LibC.inet_pton` (and not `getaddrinfo`), as per the [old implementation](https://github.com/crystal-lang/crystal/blob/0.20.1/src/socket.cr#L64-L83). 

A "breaking change" is that we now validate the address immediately in the constructor, not delayed for when we pass it to C. Thought, it sounds more like a fix to me.

Possible solutions to your example if #3781 is merged:

```crystal
destination = Socket::Addrinfo.udp("localhost", 1234).first
socket.send(message, to: destination)
```

And one for Crystal 0.21.3+:

```crystal
Socket::Addrinfo.udp("localhost", 1234) do |addrinfo|
  socket.send(message, to: addresses.first)
  nil # not needed if #3781 is merged
end

**Comment by miketheman** [comment]
@ysbaddaden Believe me, I don't know how it worked either, other than it did. I've tried digging into deeper, but get a bit lost.
From an strace on crystallang/crystal:0.20.1 docker image, I can see that the `localhost` String does indeed get translated to non-localhost address:
```
sendto(8, "This is only a test.", 20, 0, {sa_family=AF_INET, sin_port=htons(8125), sin_addr=inet_addr("0.0.0.0")}, 16) = 20
```

My approach for the statsd client library is that a user may specify the destination and it never actually has to be evaluated for correctness, since the underlying behaviors appeared to do that for me, and there was never a need to establish any kind of connectivity prior to sending, since UDP clients may send to servers that do not exist.

I can't help but wonder if the address validation is something that needs to be extracted to allow for dns-client behavior - in your proposed solution, if the DNS server doesn't speak udp, there's no current mechanism to retry in tcp, which is common amongst clients.

The changes in #3781 do indeed look to improve upon the interface, and I still cannot account for why it worked before.

I'll add that Socket::IPAddress also requires a port, so it's not precisely an ip address. ;)

**Comment by straight-shoota** [comment]
I don't think there is anything left to do here.
