### ISSUE TITLE
Slice via IO::Memory fails with []=

### ISSUE THREAD

**Issue by maiha** [crystal-lang/crystal#3807]
Just a report.
I don't know whether this is a problem or invalid usage.

https://github.com/crystal-lang/crystal/blob/0.20.3/src/io/memory.cr#L351-L354
```crystal
io = IO::Memory.new "hello"
slice = io.to_slice
slice[0] = 97_u8
```

fails

```text
Invalid memory access (signal 11) at address 0x44fabc
[4369301] *CallStack::print_backtrace:Int32 +117
```

#### env
- `Crystal 0.20.3 [b1416e2] (2016-12-23)`
- `Linux ubuntu 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Thanks.

**Comment by asterite** [comment]
`IO::Memory.new` uses the string's slice, and `to_slice` returns a view to that slice, so modifying it, in the case of a string constant, is trying to write to the data section of the program. I don't know if there's an easy way to prevent this (of course the hard way is to introduce immutability annotations all over the place), but it's incorrect usage of `IO::Memory`. It's the same as:

```cr
"hello".to_slice[0] = 97_u8
```

**Comment by maiha** [comment]
I completely understood!
I'll fix the example code in other pr.
Thank you!

**Comment by asterite** [comment]
Some others way to "fix" this would be to either mark `IO::Memory#to_slice` and `String#to_slice` as [unsafe](https://github.com/crystal-lang/crystal/issues/124). Maybe `String#to_slice` should return a read-only slice, somehow. The problem is that `IO::Memory` returns a view to its internal data, so that's super unsafe and there's no easy way to know if the slice is writeable or not... Maybe `IO::Memory#to_slice` shouldn't even exist.

**Comment by asterite** [comment]
@maiha Oooooh... Now I understand! The example code is wrong because in the past when you did `IO::Memory.new(string)` bytes were copied from the string... this was a bit slow so now a reference to the string's slice is kept by the `IO::Memory`, but you can't modify it (writing to `IO::Memory`, for example doing `<<`, will raise an exception). Yes, the example should be fixed, probably... but I'm thinking maybe the method `to_slice` should be removed, I can't think of a good use case for it.

**Comment by asterite** [comment]
(Well, it seems to be used in a few places, just to save a few allocations, so for now I think it'll have to stay)

**Comment by maiha** [comment]
@asterite Yup, *removing* is best I think.
Otherwise, it needs something like this as you said.

```
IO::Memory#to_slice # => Slice.new(..., writeable: false)
```
But this would lead heavy changes.
