### ISSUE TITLE
Better compiler feedback for incorrect elsif syntax

### ISSUE THREAD

**Issue by andyfleming** [crystal-lang/crystal#3846]
I'm not suggesting we support `elseif`, but there could be better feedback when it is used instead of `elsif`.

## Case 1 with `elseif`

```crystal
a = 12

if a > 15
	puts "a is greater than 15"
elseif a > 3
	puts "a is greater than 3"
else
	puts "a is less than or equal to 3"
end
```

```
Error in if-example.cr:15: undefined method 'elseif'

elseif a > 3
^~~~~~
```

## Case 2 with `else if`

```crystal
a = 12

if a > 15
	puts "a is greater than 15"
else if a > 3
	puts "a is greater than 3"
else
	puts "a is less than or equal to 3"
end
```

Compiler output

```
Syntax error in if-example.cr:19: expecting identifier 'end', not 'EOF'

end
   ^
```

## Proposed solution

A better message would be helpful. Specifically I would suggest:

```
Error in if-example.cr:15: incorrect syntax 'elseif', use `elsif` instead

elseif a > 3
^~~~~~

```

This would be similar to the feedback given when a `postfix increment` is attempted.

```
Syntax error in if-example.cr:13: postfix increment is not supported, use `exp += 1`

a++
  ^
```

**Comment by andyfleming** [comment]
@jhass Why the thumbs down with no explanation?

**Comment by lbguilherme** [comment]
# Case 1

This is a perfectly valid code, and it should stay working:

```cr
def elseif(value)
  p value
end

a = 20

if a > 15
	puts "a is greater than 15"
elseif a > 3
	puts "a is greater than 3"
else
	puts "a is less than or equal to 3"
end
```

Your proposal would make `elsif` a keyword, would change the parser to understand new syntax and would break perfectly valid code. Not good.

# Case 2:

```cr
a = 12
​
if a > 15
  puts "a is greater than 15"
else if a > 3
  puts "a is greater than 3"
else
  puts "a is less than or equal to 3"
end
end
```

Again, the code is perfectly valid, the actual error is the missing `end` at the end, as the error states. This is read as if `else` and `if` were in different lines, one inside the other. Would separating `else` and `if` with a space become illegal too?

---

I don't think the parser should try to parse syntax that doesn't exist just for the sake of better error messages. There are a few places where this is made, but it is because the syntax _was_ supported before and have changed since.

**Comment by ysbaddaden** [comment]
Closing, we shouldn't have to introduce specific error handlers to detect invalid syntaxes inherited from other languages. I believe the syntax is sufficiently documented to understand and fix the issue.

**Comment by andyfleming** [comment]
Thanks for the explanation, @lbguilherme.

In Case 2, I understand why that would be a bigger change.

For Case 1, I think it would be better to catch it as an invalid keyword than allow someone to name a function `elseif`.

The problem is you are only thinking about people coming from ruby. They are used to the `elsif` syntax. What about people coming from other languages?

While already documented, it would still be helpful to have the compiler feedback, and I doubt it would have a significant performance impact.

All in all, this isn't a huge deal, but I'm just trying to bring attention to things that I think would help with adoption (especially from users not coming from ruby), however small the issue might be.
