### ISSUE TITLE
Feature request: add non-substitutable type aliases

### ISSUE THREAD

**Issue by cjfuller** [crystal-lang/crystal#3888]
(Following up on the discussion in #3864.)

It would be useful to have a version of `alias` that creates type aliases that cannot be substituted for one another.  For example (calling this new feature `typedef` for the sake of discussion), with this feature we'd get a compiler error for a type mismatch for the following:

```crystal
typedef meters = Int32
typedef feet = Int32

def do_something_assuming_meters(measurement : meters)
  # code that does something that would go badly in the wrong units
end

x : feet = 10

do_something_assuming_meters(x)
```
since while x is an Int32, it's considered to be of type `feet` here, which would be incompatible with `meters`.

This is useful for having the type checker help you avoid errors in a lot of different applications, like attaching units to numbers as shown here, or my original usecase in #3864, which was distinguishing between protein and DNA sequences represented as strings.

**Comment by RX14** [comment]
I don't think @asterite is particularly keen on this feature, but I quite like it. I think it provides some extra type safety essentially for free. I think that `type` is a good name for it, as it's defining a new type.

**Comment by david50407** [comment]
I don't know if this is a good idea... so how this works?

```crystal
typedef Feet = Int32
x : Feet = 10 # here should raise an error that 10 is not a Feet, it's Int32
```

We have this in lib because we can ensure these value can only be use between the library's functions, right? (like HANDLE in Windows API, we should not modify or try to understand what the real value is, but it is meaningful in Window API world)

**Comment by firejox** [comment]
I think it can be done by macro.
```Crystal
macro type_new(new_type, from old_type)
  struct {{new_type}}
    def initialize(@%x : {{old_type}})
    end

    macro method_missing(call)
      (@%x.\{{call}}).try do |%y|
        if %y.is_a? {{old_type}}
          {{new_type}}.new %y
        else
          %y
        end
      end
    end
  end
end

type_new Foo, from: Int32
type_new Bar, from: Int32
foo = Foo.new 0
bar = Bar.new 0

def only_accept_foo(x : Foo)
end

only_accept_foo foo
only_accept_foo bar # => no overload matches 'only_accept_foo' with type Bar
```

**Comment by asterite** [comment]
I'd actually like to remove `type` from the language :-)

Before explaining why, I want to say that this is already possible by using structs, or simply `record`. For example:

```cr
record Feet, value : Int32
record Meters, value : Int32

feet = Feet.new(10)
meters = Meters.new(20)

def do_something_assuming_meters(measurements : Meters)
end

do_something_assuming_meters(meters) # OK
do_something_assuming_meters(feet)   # Error
```

LLVM will optimize this to simply use `Int32`, so it's as efficient as using `Int32`, but more type-safe.

The problem with `type` is this. Let's assume this:

```cr
type Feet = Int32
```

First, how do you construct such type? Doing:

```cr
feet : Feet = 10
```

is not a valid option, because the language right now doesn't have implicit type casting, and using type declarations like the above is not common at all.

Maybe we can use this syntax:

```cr
feet = Feet.new(10)
```

which is already closer to my `record` solution above.

Next, what's the type of this:

```cr
feet + 1
```

Or this:

```cr
feet + feet
```

if we have `type Feet = Int32`, where there's `Int32+#(Int32) : Int32`, how does the compiler know that the `+` method now suddenly needs to return `Int32`?` Maybe we can do the rule "if a method on a `type` returns the underlying type, automatically cast it to the wrapping type". But for example `Int32` has a `sign` method that returns -1, 0 or 1 according to the number's sign. So `feet.sign` would not return `Feet`, which is definitely something you don't want to happen.

The part `feet + feet` is trickier: is it always valid to pass a `Feet` value where an argument expects `Int32`? For example there's `Number#significant(digits, base = 10)` method, can I pass `Feet` as arguments? (that method doesn't even have type restrictions)

What's the solution to the above? Explicitly defining methods on the `Feet` type. We can define the `+` method like this:

```cr
record Feet, value : Int32 do
  # Maybe we'd like to just add other feet, never integers
  def +(other : Feet)
    Feet.new(value + other.value)
  end
end
```

Note that I wouldn't even consider using `method_missing` because it has the same problem I described above.

So 👎 from me on adding a `type` concept outside libs (I'd actually like to remove `type` from libs too and just use `alias`, chances of passing a wrong Void* pointer type are very low, and if you do that you'll immediately gets an error, so `type` adds very little type safety and has already the problems I described above)

**Comment by ysbaddaden** [comment]
Great explanation. No `type` outside of `lib`, then. I think I still like `type` over a simple `alias`, but I agree it's more a comfort feeling than actual safety.

**Comment by cjfuller** [comment]
Good points!  For your examples like `feet + feet`, or `feet = 10` I was envisioning you would have to explicitly cast with something like `feet.as(Int32) + feet.as(Int32)`, or `feet = 10.as(Feet)` (which I apparently left out of my example's initialization).

But as you say, that's just the same as the record solution; I'm completely satisfied with using records for this and happy to have the feature request closed!

**Comment by spalladino** [comment]
Great! Closing this issue then.

**Comment by stellarpower** [comment]
> It would be useful to have a version of alias that creates type aliases that cannot be substituted for one another. For example (calling this new feature typedef for the sake of discussion), with this feature we'd get a compiler error for a type mismatch for the following:

IK this issue is ancient, but just whilst I am here and it hasn't been mentioned already, this is called _strong typing_ in other languages and is an extremely useful tool to have in the pocket. The Mars Climate Orbiter story is usually brought up, and whilst a cliché it does go to show how important this concept is in the real world. In C++ there is a library for it (mentioned in second video) that has to introduce another type in order to get it to work (much like the above example for Feet, essentially disabling assignment form the underlying "normal" type), but given we have macros and the ability to throw exceptions in the compiler context in Crystal, I think there is room for a much broader sense of checking constraints on code are met at compile-time. IDK if there's already a way to do this, but if not then I think it's definitely worth considering. I always use things like this to ensure that matrices are of the right dimensions for example. If I am trying to multiply a 3\*3 by a 4\*4 and this is known before runtime by tagging the type of the operands, then I wanna be stopped in my tracks before my code builds and not waste time. The first video below uses a motivating example of working with co-ordinate geometry, which I have also found to be a really useful application of techniques like this.

- https://yewtu.be/watch?v=fWcnp7Bulc8
- https://yewtu.be/watch?v=WVleZqzTw2k
