### ISSUE TITLE
yield introduced through macro is not respected in method signature

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#391]
```ruby
macro a
  yield
end

def b(&block)
  a
end

b { puts "hi" } # works

def c
  a
end

c { puts "hi" } # claims c doesn't take a block
```

**Comment by ysbaddaden** [comment]
Maybe it goes further than macros, and applies when a `&block` is passed around. In #382 I had a bug like the following:

```crystal
def popen2(&block)
  popen_run(1, 2, &block)
end

def popen_run(a, b)
  yield a, b
end

popen2 { |a, b| } # => wrong number of block arguments (2 for 0)
```

**Comment by asterite** [comment]
There's a big, undocumented thing about Crystal regarding blocks: if you use the name of a `&block` argument, that **always** means the method will create a function/closure out of the block. Because of this, the compiler requires you to say the types of the function/closure (similar to how you need to say the type of a generic type).

The avoid this capture, you can invoke a method and yield again from inside the block:

```crystal
def popen2
  popen_run(1, 2) do |a, b|
    yield a, b
  end
end

def popen_run(a, b)
  yield a, b
end

popen2 { |a, b| } # works
```

You might wonder why this is like this. Well, the problem is that when the compiler sees "popen2 { |a, b| }", how can it know if it needs to create a closure for the block or not? Right now the rule is simple: if the block name is used inside the method, it's a closure. Otherwise it's a regular block, and the compiler will always inline it, without creating a closure.

Now, if you have:

```crystal
def popen2(&block)
  popen_run(1, 2, &block)
end
```

Does that method capture the block? Well, it depends on whether `popen_run` captures the block, but we only know that once we instantiate `popen2` and type it (do semantic checks), so it's kind of hard...

We still have a pending refactor related to how blocks work, which might happen or not. This will allow forwarding a non-captured block. But the syntax for block args will be a bit different (I don't remember the details right now).

However, I think I like the current way. In Ruby you really don't care about this little detail, "I just pass the block along and Ruby will understand". Well, it seems Ruby works more or less the same way as we think about blocks: if you name them and use them (even if you just pass them along), Ruby probably creates a closure. Otherwise it just "kind of inlines" the call (the VM goes back to the calling method and continues there, probably). Here's the [proof](https://gist.github.com/asterite/7267571938a96989f3b1). (it's very curious that if you name the block but don't use it, it's even slower... maybe ruby has to translate that yield to invoking the block, so that makes it slower)

So in Crystal if you don't want to capture the block you must always use yield, and use it to "pass along" a non-captured block, and the compiler forces you to do that. And in that way you save yourself some runtime time.

**Comment by ysbaddaden** [comment]
> you can invoke a method and yield again from inside the block

This is what I ended up doing, but that's an extra step and code, when a simple `&block` arg is simpler. That being said, having a `popen_run` macro instead, would also solve the problem —for that specific case.

**Comment by asterite** [comment]
@jhass I don't think I'll be able to "solve" this. Method b (as in `def b(&block)`) is the way to go. The compiler expands macros when it instantiates methods (think of this as "ruby would interpret this"), so it has no way of knowing that a macro inside the method will produce a yield. The only way you can tell the compiler this is is with a block arg.

I think this also makes the code more clear to the reader, because otherwise you might think the method doesn't yield, but that's hidden behind a macro.

**Comment by jhass** [comment]
Sure, your (design) choice after all ;) Feel free to close the issue.

**Comment by asterite** [comment]
I'll leave it open as an enhancement. There is a way of doing this, by expanding macros first, then doing semantic analysis, but it's a big change to do right now.

**Comment by asterite** [comment]
After a second though, I don't think this is doable. Macros inside methods need to be expanded when a method is typed (on invocation), because the macro might solve to a macro defined in a subclass. The solution to this is to mark the method as `&block`.
