### ISSUE TITLE
[RFC] Splats in yield

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#392]
We can splat a tuple when calling a method ,yet not when yielding, the tuple is passed as the only argument instead:

```crystal
def splat_it(a)
  yield(*a)
end

splat_it({1, 2}) do |a, b|
  p a # => {1, 2}
  p b # => nil
end
```

That played against me in #382 (look for commented out lines)

**Comment by asterite** [comment]
Cool, this seems doable :-)

**Comment by stugol** [comment]
Almost a year later....is this going to be fixed?

**Comment by waj** [comment]
Yay! We should start celebrating birthdays of old issues 🎂

**Comment by stugol** [comment]
I have a better idea. How about we fix them?

**Comment by asterite** [comment]
@stugol Sure, pull requests are welcome.

**Comment by stugol** [comment]
Har har. I wouldn't have the _faintest idea_ how to fix bugs in code that isn't even mine. I barely understand your source at the best of times.

For example, I don't understand AST nodes at all. Whatsoever.

**Comment by stugol** [comment]
I could maybe fix something in the libraries - that is, written in Crystal. But the C++ compiler code? Not a chance. C++ is a bastard at the best of times, let alone when writing a compiler - a subject about which I am lamentably ignorant.

**Comment by asterite** [comment]
@stugol The compiler is written in Crystal :wink:

In any case, the code is not trivial to modify, and lacks some comments and explanations for anyone to jump into it and add features or fix something. We definitely need to improve that.

But this is a low priority right now compared to other things. Just asking for something to be done, or writing ":+1:" or "Me too" won't make it happen. And much less complaining for lacking things, given that this is an open source project.

**Comment by stugol** [comment]
Doesn't '+1'ing something increase its relative priority, though? If lots of people want a fix, then it's more important, right?

**Comment by asterite** [comment]
Not necessarily. I don't think that if we open an issue in the Go language asking for generics, and 1_000_000 people vote :+1:, it will happen.

**Comment by stugol** [comment]
You're probably right. But that is because Go is stupid, and the developers of Go are also stupid, and they don't listen to their users. Go's concurrency model is nice (maybe you could implement their `select` in Crystal?) but everything else about the language totally blows. No generics. Cannot extend core types. No overloading. Totally violates DRY. Go is broken and unusable.

**Comment by aemadrid** [comment]
+1

**Comment by marceloboeira** [comment]
@aemadrid are you joking? kkk

**Comment by omninonsense** [comment]
@marceloboeira, no. :+1: :+2:!

**Comment by marceloboeira** [comment]
@omninonsense ahahaha

**Comment by lucaong** [comment]
I think it's totally understandable that implementing this takes time, and there are priorities. It would be cool to see contributions from the community.

I would happily give a try to help implementing this feature, but I need a bit of a code walkthrough. I suspect the part of the code that needs a change is here:

https://github.com/crystal-lang/crystal/blob/3a19f4187ff73fdf8dde316f05dcda3171394b4a/src/compiler/crystal/codegen/codegen.cr#L1150

In particular:

```crystal
# First accept all yield expressions and assign them to block vars
request_value do
  node.exps.each_with_index do |exp, i|
    accept exp

    if arg = block.args[i]?
      block_var = block_context.vars[arg.name]
      assign block_var.pointer, block_var.type, exp.type, @last
    end
  end
end
```

I assume it could be possible to say that if `exp` is a splat and `@last` is a tuple, then it should be expanded into the block vars. Or am I completely off-track?

I could not locate the code that expands the splats on method calls, I wanted to take inspiration from it as I am not familiar with the Crystal compiler code yet.

Otherwise, a temporary solution could be to make the parser raise when `yield` is passed a splat (possibly raising a compiler error telling that splats as yield arguments are not implemented yet). It could save people some headache while this feature gets implemented in a future release. The strange thing is that at the moment splats are parsed without errors but not expanded.

Maybe the check could be implemented here?

https://github.com/crystal-lang/crystal/blob/ab1705bda367c468e4ae108b62deb6192508c613/src/compiler/crystal/syntax/parser.cr#L4020

**Comment by asterite** [comment]
@lucaong Thanks for wanting to help. I actually tried to implement this a few times but thought it was very complex to do. The main issue I had was that the algorithm was simple: just bind yield expressions to block arguments in order. With a splat we now can't just bind like that and we need an intermediate object to bind things in a more complex way. But it took me a while to figure that out, that's why I couldn't help you try to implement it either.

Next on my list: https://github.com/crystal-lang/crystal/issues/1171
