### ISSUE TITLE
Subclass Array - Generics/Type errors

### ISSUE THREAD

**Issue by chyzwar** [crystal-lang/crystal#3938]
Hi, 

I am just starting  with Crystal. I had some issues with subclassing Array.
Somehow when I subclass on Array when I use my custom class (MyArray) as instance variable type information seems to be invalid in compile.

I tried to sprinkle my code with type declaration but problem persist. I did not tried with diffrent classes than Array, I am not sure if this is issue with Array only or in general.

Below code to reproduce my issue. 

```crystal
class MySomething

end

class MyArray < Array(MySomething)
	def self.from_something
		MyArray.new
	end
end

class Another
	@array = MyArray.new

	def array
		@array
	end

	def array=(array)
		@array = array
	end
end

test = MyArray.new

# Instance variable @array should be of type MyArray?
# Error: instance variable '@array' of Another must be MyArray, not Array(MySomething)
Another.new.array += test

# I shoudl be able to use << of Array on subclass with same generic type?
# Error: no overload matches 'MyArray#<<' with type MyArray
Another.new.array << test```

**Comment by RX14** [comment]
The problem is that `Array#+` returns an array, even when subclassed to `MyArray`. Therefore `Another.new.array + test` is an `Array`, not a `MyArray`, and assigning fails. For the << example, you're trying to add a `MyArray` as an element of the array, not append them.

The solution here is not to use inheritance. `Array` is not meant to be inherited ([even in ruby](http://words.steveklabnik.com/beware-subclassing-ruby-core-classes)). In your case, you seem to want to add a `from` style method to create an array from another type. This *could* be monkey patched onto `Array`, but I would recommend just putting this method somewhere else and returning an `Array(MySomething)`. If you *need* to extend `Array`, then use composition.

**Comment by chyzwar** [comment]
Ok I will try as suggest. 

But why + cast to array?.  If two Arrays are of the same type they should concatenate without casting or wrapping in we array.

In SmallTalk or Java there is no issues with extending native Classes.

**Comment by asterite** [comment]
`Array#+` returns a **new** array, it doesn't not append to an existing array (use `concat` for that).

That said, if I have `ArrayOne < Array(Int32)` and `ArrayTwo < Array(Int32)` if I do `ArrayOne.new + ArrayTwo.new`, what should be the return type?

(I think using `concat` basically solves the main problem you had in this issue)

**Comment by chyzwar** [comment]
Thanks for help. 

I create issue because i could not figure out why my instance variable is of different type I created.
I did not know that  Array+ have signature forall U 
```
# Error: instance variable '@array' of Another must be MyArray, not Array(MySomething)
```
