### ISSUE TITLE
Constant propagation and type inference

### ISSUE THREAD

**Issue by chocolateboy** [crystal-lang/crystal#3954]
**Crystal**: 0.20.5 (2017-01-25)
**OS**: Linux (Arch)
**Keywords**: constant folding, union type, union types

#### test1.cr

```ruby
def test
  if true
    42
  else
    "42"
  end
end

p typeof(test)
```

I would expect this to print `Int32`, but instead it prints `(Int32 | String)`.

As a result, the following is an error even though the return value is always `Int32`:

#### test2.cr

```ruby
def test
  true ? 42 : "42"
end

puts test.abs
```

#### output

    $ crystal run test2.cr
    Error in test2.cr:5: undefined method 'abs' for String (compile-time type is (Int32 | String))

A macro can be used to work around this, but IMO the lack of constant propagation here — or, more precisely, [sparse conditional constant propagation](https://en.wikipedia.org/wiki/Sparse_conditional_constant_propagation) — is surprising.

Note: I'm specifically talking about the type-narrowing opportunity here rather than any other advantages arising from dead-code removal, since I assume LLVM will aggressively perform the latter.

**Comment by asterite** [comment]
This used to work the way you want, but we eventually changed that to work the way it works now. The reason is that the type inference algorithm has an invariant that must hold: types can only "grow", never "shrink". A type "grows" if it becomes a union, or the union becomes bigger (for example it goes from `Int32` to `Int32 | String`, or from `Int32 | String` to `Int32 | String | Nil`). It "shrinks" if the opposite happens. The explanation as to why this invariant must hold is a bit long, but if not then in some border cases regarding `while` and blocks the type inferred is wrong.

Question: why do you need it to work like that? If a code has two branches returning different types there must be a reason for that, and the caller should consider both types. Why is there an `if true` in the first place? Why not simply return 42?

We *could* do this only for `if true`, if that's the only thing you need, though. But if it depends on runtime information, or on compile information that couldn't be known until a method is finished analyzing (like `x.is_a?(Int32)` where `x` turns out to only be an `Int32`) then for now it's kind of hard for that to happen.

Note that for the codegen phase we do simplify those branches and then let LLVM optimize them out. And of course LLVM will optimize things like `if 2 == 2`, or, though inlining of methods, optimize things like `x == 2` if `x` turns out to always be 2, and so on.

**Comment by chocolateboy** [comment]
> Question: why do you need it to work like that?

I don't necessarily need it, but I sometimes use this idiom to comment out a bunch of code for debugging &c.

```
if false && foo == bar
  # skip this long block
else
  # always execute this
end
```

If I end up working away in the `else` branch I don't expect its return type to be influenced by the "disabled" branch.

> Why not simply return 42?

Because I expect the compiler to do that for me :-)

Another common example is toggling assertions/debugging/logging e.g.:

```ruby
DEBUG = true

# ...

if DEBUG
  # ...
end
```

**Comment by RX14** [comment]
@chocolateboy In the first example, you can just comment out the code, in the second example, you would want the types to remain the same so that when you set `DEBUG=false`, types wouldn't change, and your program would still compile.

**Comment by chocolateboy** [comment]
> We could do this only for if true

With a [peephole optimization](https://en.wikipedia.org/wiki/Peephole_optimization) pass, simple cases like this can be handled without having to commit to the (heavyweight) rewrite to SSA form suggested by the [sparse conditional constant propagation](https://en.wikipedia.org/wiki/Sparse_conditional_constant_propagation) article.

**Comment by chocolateboy** [comment]
> In the first example, you can just comment out the code

Sure, but I'd expect the behaviour to be the same if I disable it with a compile-time constant rather than a comment.

**Comment by asterite** [comment]
Optimizations like this won't affect the type inference pass.
