### ISSUE TITLE
Heap size question

### ISSUE THREAD

**Issue by benoist** [crystal-lang/crystal#3992]
```crystal
10.times do
  Array(String).new(100_000_000) { |i| "a" }
end

loop do
  GC.collect
  puts GC.stats
  sleep(0.5)
end
```

After the 10 times loop the program prints the following GC stats:
```
GC::Stats(@heap_size=3233890304, @free_bytes=3233832960, @unmapped_bytes=0, @bytes_since_gc=0, @total_bytes=8000019728)
```

The heap size will always stay at 3GB but this is never returned to the OS. Is this expected behaviour with the current garbage collector?

**Comment by RX14** [comment]
Crystal uses libgc, which is a ready-made conservative GC library, so I doubt anybody on this issue tracker would be able to give you a definite answer on why the GC behaves as it does. However my guess is that because the GC cannot move objects around the heap, allocating a large amount of memory will fragment the heap, which means the memory cannot be reclaimed. You're much more likely to get a correct answer from the libgc developers, this question is out of scope for this issue tracker.

**Comment by rdp** [comment]
if it "stabilizes" and doesn't grow monotonically over time I'd consider that more like a "what is going on with that GC? it's not broken but not awesome somehow" so you could dive into the GC I suppose...FWIW :)

**Comment by benoist** [comment]
Well it only stabilises in this example because the code stops creating more arrays. If I keep on creating arrays memory grows far larger than the memory required to create one array. I am really interested in how the GC works so I've already started searching through the Bdw documentation but it's a slow process as it's really far out of my comfort zone ;-)

**Comment by rdp** [comment]
Yes you're right in a loop it does appear to just monotonically increase 

I get this warning as well:

```
GC::Stats(@heap_size=8134565888, @free_bytes=4134498304, @unmapped_bytes=0, @bytes_since_gc=0, @total_bytes=32000021280)
GC Warning: Repeated allocation of very large block (appr. size 800002048):
	May lead to memory leak and poor performance
```

Hard to know exactly what the problem is but something seems awry...maybe some old pointers to those arrays are left behind somehow [possibly in fiber stacks, does it re-mark all 8KB stacks always as gc_push_all_eager pointers?]

Interestingly, if I turn the 100_000_000 down to 10_000_000 then on linux it seems to stabilize at around 1GB of RAM (and on OS X about 500MB), FWIW. https://gist.github.com/rdp/fcbe228df7d295df89396171513ac7b1

Even if I remove the GC.collect it seems to behave that way FWIW...on both OS's.  Which is actually good news relative to other issues where it seems to just use up more and more...

**Comment by RX14** [comment]
The current GC doesn't handle large, frequent, allocations well. The solution is just don't do it.

**Comment by benoist** [comment]
we will continue in #3997
