### ISSUE TITLE
Improve error message for "undefined local variable or method" when variable is previosuly defined because of "var : Type"

### ISSUE THREAD

**Issue by sh01ch1** [crystal-lang/crystal#4106]
```crystal
module Mod
  class Klass
    getter name : String

    def initialize(@name)
    end
  end

  puts name
end
```

raises:

```
Error in test.cr:9: read before assignment to local variable 'name'

  puts name
       ^~~~
```

Crystal 0.21.0, mac os x yosemite

**Comment by MakeNowJust** [comment]
What's a problem? You just did **read before assignment to local variable 'name'**, so you got the error of course.

Crystal needs a assignment against the local variable before using this, not like Ruby.

**Comment by sh01ch1** [comment]
Hi @MakeNowJust, Module has the `.name` method. The following code works:

```crystal
module Mod
  class Klass
    getter name : String

    def initialize(@name)
    end
  end

  puts self.name # prints "Mod"
end
```

**Comment by MakeNowJust** [comment]
Small version:

```crystal
module A
  module B
    name : String
  end
  p name
end
```

**Comment by MakeNowJust** [comment]
Another version:

```crystal
def foo
  42
end

module Foo
  foo : Int32
end

puts foo
```

The problem is caused when same name variable is defined in class/module because `foo` is parsed as `Var` instaed of `Call` in this case.

**Comment by asterite** [comment]
Maybe the error message should be improved, but it will still be an error. I think this is minor.

**Comment by sh01ch1** [comment]
Hi @asterite, I'm a little confusing.

```crystal
def foo
  "foo"
end

class Klass
  @foo : String

  def foo : String
    @foo
  end

  def initialize(@foo)
  end
end

puts foo
```

is OK. 

```crystal
def foo
  "foo"
end

class Klass
  getter foo : String

  def initialize(@foo)
  end
end

puts foo
```
Why does this code raise "read before assignment to local variable 'foo'"?

**Comment by MakeNowJust** [comment]
@sh01ch1 Crystal's scope rule looks like LISP-2, in short it decides whether a name is a variable or a method on parsing (It is same as Ruby).

Then, how does it decide this? -- It is simple: the parser memorizes declared or assigned variable names on parsing, and it decides a name is variable if this name is memorized.

On your example, `foo : String` is a variable declaration of `foo`, so the parser memorizes `foo` is variable. The compiler treats `foo` of `p foo` as variable, but `foo` assignment is not found, so you got such an error.

(NOTE: the expressions inside a class and outside a class have same scope, for example this is valid program:

```crystal
class Foo
  foo = 1
end
p foo
```

)

But this case is fixed by me in #4114. Thanks.

**Comment by MakeNowJust** [comment]
@sh01ch1 By the way, I seem you are Japanese. I want you to join [crystal-jp Slack](http://crystal.pine.moe/) if you are interested in Crystal. Have fun!

**Comment by sh01ch1** [comment]
@MakeNowJust Thank you!!! Actually, I've already joined to the Slack team with another name. This is my business account.

So, for the Crystal parser, `getter name : String` means:

* declaring an instance variable (@name : String)
* declaring a getter method (def name : String)
* also declaring a local variable (name)

Right?
