### ISSUE TITLE
Access HTTP::Response.body_io without block

### ISSUE THREAD

**Issue by cschlack** [crystal-lang/crystal#4189]
I would like to do streaming IO through HTTP::Response.body_io without using a block.

**Reason:** Creation and consumption of the http stream happens in callbacks from a C library.

Is there any way to change HTTP::Response so body_io can be accessed without calling get with a block?

**Pseudo-Code:**
```crystal
def init_stream
  @client = HTTP::Client.new "www.example.com"
  @io = @client.get("/api/v1/data").body_io
end

def read_stream
  @io.read
end

def stream_close
  @client.close
end

**Comment by asterite** [comment]
The reason why the body is given as an `IO` only in the block form is that the block ensures that the response will be closed when the block finishes.

We could maybe add overloads to `get`, `post`, etc., that would directly return the response as an IO instead of a String.

In the meantime you could maybe use a Channel to synchronize between the methods, using a block.

**Comment by cschlack** [comment]
Here is a similar example https://crystal-lang.org/api/0.21.1/HTTP/Client.html:

### Reusing a connection

```crystal
require "http/client"

client = HTTP::Client.new "www.example.com"
response = client.get "/"
response.status_code      # => 200
response.body.lines.first # => "<!doctype html>"
client.close
```

I would like to write my code like in this example - except: I need to access body_io instead of body. How does the response get closed in this example?

Is it possible to change `HTTP::Client::Response` to call `consume_body_io` lazily in case `body` is being read?

**Comment by asterite** [comment]
Oh, sorry, I said it wrong. 

In the last example `body` is a String because the response was already read in this form (no block). With a block the benefit is that after the block exit the HTTP::Client makes sure to read whatever wasn't read from the socket for that particular request, so next time you issue a request you don't have to manually do it, or forget to do it.

But not being able to get the `body_io` outside of a block is problematic. I guess the client needs to maintain the last request and raise if someone tries to perform another request before closing the last one.

In any case, this problem can already happen when nesting blocks:

```crystal
# This will fail because the requests will mix
client.get "/" do |body|
  client.get "/" do |body|
  end
end
```

So the API will definitely need a change before 1.0, we just need a bit more time to think about a better solution.

**Comment by mjago** [comment]
I ended up doing the following to stream audio:
```
def get_next_chunk(redir)
  channel = Channel(Slice(UInt8)).new
  spawn do
    HTTP::Client.get(redir, range_header) do |response|
      Fiber.yield
      # ...
      if s = response.body_io.peek
        # ...
        channel.send s
      end
    end
  end
  channel.receive
end
```

**Comment by ysbaddaden** [comment]
I'm fairly sure you can use a single, pending request, and feed the next chunk to the channel.

I mean smth like:
```crystal
channel = Channel(Bytes | Nil).new

spawn do
  HTTP::Client.get(...) do |io|
    chunk = Bytes[4096]

    # IO, so triggers fiber switch
    count = io.read(chunk)

    # triggers a fiber switch
    channel.send(chunk.to_slice(0, count))
  end

  # done
  channel.send(nil)
end

while chunk = channel.receive
 # play audio chunk
end
```

**Comment by mjago** [comment]
@ysbaddaden your solution works nicely thanks!

**Comment by RX14** [comment]
Is there anything to do here? It seems that everyone has agreed that using the block form is acceptable when you need to stream a response body.
