### ISSUE TITLE
Change Range to be an Abstract Struct with Concrete Implementations

### ISSUE THREAD

**Issue by rjkaes** [crystal-lang/crystal#4218]
I tried to change `Range` into an abstract struct with two concrete implementations (for exclusive and inclusive.)   Simplified:

```
abstract struct Range(B, E)
  ...
  private struct Exclusive(B, E) < Range(B, E)
  end

  private struct Inclusive(B, E) < Range(B, E)
  end
end
```

but compiling (with `make crystal`) I receive the following error:

```
% make clean crystal                                                                                                                                               ~/src/crystal
Using /usr/local/opt/llvm/bin/llvm-config [version=4.0.0]
rm -rf .build
rm -rf ./doc
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
rm -rf src/llvm/ext/llvm_ext.o
rm -rf src/ext/sigfault.o src/ext/libcrystal.a
Error in src/compiler/crystal.cr:1: while requiring "prelude"

# This is the file that is compiled to generate the
^

in src/prelude.cr:61: while requiring "range"

require "range"
^

in src/range.cr:264: can't extend non-abstract struct Range(B, E)

  private struct Exclusive(B, E) < Range(B, E)
                 ^

make: *** [.build/crystal] Error 1
```

Is there a specific way to compile the compiler when making changes to the types of a core type?

**Comment by asterite** [comment]
You need to change the compiler. Probably make it in two steps. However, I see no point in making this change.

**Comment by rjkaes** [comment]
While I appreciate that this particular change isn't useful in-and-of itself, it was an easy test case to see how core types could be modified.  As such, I'd appreciate any insight into how to change the compiler to allow similar kinds of modifications to core types.

Thank you.

**Comment by asterite** [comment]
@rjkaes Sure! Range is defined [here](https://github.com/crystal-lang/crystal/blob/d6a2269fd8c6243d3fa99b3ccfe76583c74e10f6/src/compiler/crystal/program.cr#L191). It's defined internally by the compiler as a generic type.

To change it, you'll need to change that line to something else, compile the compiler, and then change the standard library code to match that definition. You won't be able to do both at the same time because the current compiler uses the current definition (Range is not abstract).

**Comment by rjkaes** [comment]
Awesome!  Thank you for the pointer!
