### ISSUE TITLE
Bug: can infer STDIN, but cannot infer STDOUT

### ISSUE THREAD

**Issue by ciofeca** [crystal-lang/crystal#4322]
Consider the following snippet:
```
class Test
  property input
  property output
  property count

  def initialize(inp = STDIN, out = STDOUT)
    @input = inp
    @output = out
    @count = 0
  end

  def shout
    @output.puts(@count)
    @count += 1
  end
end

x = Test.new
x.shout
```
Crystal 0.22 complains with _Can't infer the type of instance variable '@output' of Test._

Workaround: assign an easy to infer value to _@output_ before reassigning it. This ugly version works:
```
  def initialize(inp = STDIN, out = STDOUT)
    @output = STDIN
    @input = inp
    @output = out
    @count = 0
  end
```
Yes, it's weird, because the following version (less ugly) gets again the _Cannot infer_ error:
```
  def initialize(inp = STDIN, out = STDOUT)
    @output = STDOUT
    @input = inp
    @output = out
    @count = 0
  end
```
It seems that _STDIN_ is inferred, while _STDOUT_ not.

Platform: stock Ubuntu 17.04.
Version: Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0

**Comment by asterite** [comment]
This is not a bug. Check [these lines](https://github.com/crystal-lang/crystal/blob/6b1067aa483d03c9b2d4b6f9f9c4525a1983fecb/src/kernel.cr#L3-L4):

```
STDIN  = IO::FileDescriptor.new(0, blocking: LibC.isatty(0) == 0)
STDOUT = (IO::FileDescriptor.new(1, blocking: LibC.isatty(1) == 0)).tap { |f| f.flush_on_newline = true }
```

`STDIN` is just a `T.new`, while `STDOUT` has a `tap` in it, so the compiler can't infer the type from that. Read [this](https://crystal-lang.org/docs/syntax_and_semantics/type_inference.html). I suggest adding a type like `: IO` to your instance vars, otherwise it won't work with any IO you want.
