### ISSUE TITLE
Make @host publicly accessible such as @port is in HTTP::Server

### ISSUE THREAD

**Issue by joaodiogocosta** [crystal-lang/crystal#4325]
I would like to be able to access an http server's @host the same way I can access @port.
As of this moment, @host is a private variable of `HTTP::Server` and does not have accessor methods.

I would be happy to submit a PR if you find it suitable.

**Comment by bcardiff** [comment]
There is a draft for splitting http server and listeners in order to support binding to unix socket directly #2735. That could impact on the solution for this.

Note that the ip used to bind the server to is not the same as the ip of the server itself. `0.0.0.0` matching everything but not telling you the ip of the server.

**Comment by joaodiogocosta** [comment]
@bcardiff I'll follow on #2735 and see what happens then. Thanks
