### ISSUE TITLE
Sockets wont raise when trying to read from closed socket

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4348]
```crystal
require "socket"
  
server = TCPServer.new(9999)

spawn do
  loop do
    client = server.accept
    client.close
  end
end


spawn do
  sock = TCPSocket.new("127.0.0.1", 9999)
  loop do
    allocate_mem = Slice(UInt8).new(10)
    size = sock.read(allocate_mem)
    puts "#{allocate_mem[0, size]}"
  end
end

sleep

```
This example will return `Bytes[]` endlessly instead of raising an connection reset or EOF etc..

**Comment by oprypin** [comment]
I think this is expected behavior, at least it matches what C and Python do in this case - return 0 to indicate that there is no more data to receive.

In IRC you brought up the concern of how to differentiate between "no data to receive just yet" and "socket closed, no more data ever".

The first of these will have the .read call block until there is data, the 2nd of these will return 0.

Here is how the communication would happen:

```crystal
require "socket"

server = TCPServer.new(9999)

spawn do
  sock = TCPSocket.new("127.0.0.1", 9999)
  loop do
    allocate_mem = Slice(UInt8).new(10)
    size = sock.read(allocate_mem)
    break if size == 0
    p allocate_mem[0, size]
  end
  p "closed"
end

client = server.accept
client.write("blah".to_slice)
sleep 2
client.close
sleep 2
```

You can check that this example does indeed block but still knows exactly when the socket is closed.

**Comment by bararchy** [comment]
@oprypin 

Makes sense, thanks
