### ISSUE TITLE
Macro does not get expanded with symbol

### ISSUE THREAD

**Issue by shulhi** [crystal-lang/crystal#4479]
```crystal
class Controller
  def index
    puts "hello"
  end
end

macro handler(controller, action)
  c = {{controller}}.new
  c.{{action.id}}
end

# this doesn't work
temp = :index
handler Controller, temp

# this works
handler Controller, :index
```
Somehow on the first case, the macro gets expanded to `c.temp` instead of `c.index`

**Comment by bew** [comment]
Hi @shulhi, 

This is an issue tracker, not a forum, 
If you are a beginner and have questions, you can ask them on IRC/Gitter or Stackoverflow.com with the tag `crystal-lang`, the community will be happy to help you! 

Aussi, make sure you read the docs, multiple times :) 
- All docs: https://crystal-lang.org/docs/
- Docs on macros: https://crystal-lang.org/docs/syntax_and_semantics/macros.html

For your error, macros are expanded at compile time, and the value of `temp` is only known at runtime, so it cannot be accessed in the macro. 
Also, a macro call takes your arguments as is, it does not try to resolve the variable. 

There is an exception with constants, because there value (not their actual value, but their value as AST node) is known at compile time, and cannot be redefined. 

For example, 
```cr
macro example(argument) 
  print "{{ argument }} = "
  puts {{ argument }} 
end

example 1 + 3
```
Is literally expanded to:
```cr
print "1 + 2 = "
puts 1 + 2
```
You get in the macro exactly what you passed to the macro. 
https://carc.in/#/r/23gm

**Comment by shulhi** [comment]
@bew sorry! I've gone through the docs but I can't find the correct information. Feel free to close this, I will ask in SO.

**Comment by Sija** [comment]
@shulhi Feel free to do it yourself ;)
