### ISSUE TITLE
String.compare doesn't take into account case folding

### ISSUE THREAD

**Issue by akzhan** [crystal-lang/crystal#4513]
## Case folding

Unicode proposed case folding to correctly compare strings.

So case folded comparison of "ß" and "ss" returns true.

## String.compare

It doesn't take into account case folding at all, while downcase do (with #4512).

This is because it assumes that down cased character always represented by single character too.

Reimplementation of String.compare will be followed by performance penalty.

 ## Possible solutions

* String.locale_compare that known about multi character Char.downcase.
 * Use slow multi character implementation in String.compare with  Unicode::CaseOptions::Fold only.

Any suggestions?

/cc @RX14, @asterite

**Comment by asterite** [comment]
This is a tough one. The problem is for example that for the Turkish "I", the downcase is "ı" while in other languages it's "i". So downcase case insensitive comparison does need some locale info. So probably we need an extra argument to `compare` that's the `Unicode::CaseOptions`.

For now we could probably implement it by doing `s1.downcase(case_options) == s2.downcase(case_options)` when case_options is specified (or if it's not ASCII).

I also wonder whether we'd need unicode normalization for this to be totally right all the time...

**Comment by akzhan** [comment]
My proposal:

 * Implement `Char::FoldedReader < Char::Reader` to iterate fold cased characters.
* Add `case_fold` option to `String.compare` to replace char reader with folded reader.

**Comment by asterite** [comment]
@akzhan Do you think this can be implemented now?

**Comment by asterite** [comment]
@akzhan Ah, nevermind, we still probably need unicode normalization

**Comment by akzhan** [comment]
Yes, Unicode normalization still should be implemented.
вс, 10 сент. 2017 г. в 19:30, Ary Borenszweig <notifications@github.com>:

**Comment by straight-shoota** [comment]
Doing Unicode string comparison right is a hard problem. The ordering of characters does not just depend on script, but also on locale. Some languages have different sort orders for the same character.

Relevant standard: https://unicode.org/reports/tr10/
This standard defines a default order. Implementing that would probably be a good first step.

This definitely needs normalization which is tracked in #11223.

**Comment by HertzDevil** [comment]
Collation depends on a locale, e.g. `ä` may be ordered right after `a` or `z`. I think that is out of the standard library's scope.

For this issue we only need to ensure `s1.compare(s2, case_insensitive: true, options: :fold).sign == (s1.downcase(:fold) <=> s2.downcase(:fold)).sign`.
