### ISSUE TITLE
Add remote ip field to Http::Request

### ISSUE THREAD

**Issue by anatol** [crystal-lang/crystal#453]
It is useful to get access from `HTTP::Handler` to underlying socket properties. I am interested in the client ip address (aka 'remote_ip'). Currently `Http::Request` has fields that are parsed out of the request body but no client ip.

**Comment by jhass** [comment]
Should probably differentiate between the IP the TCP connection came from and things like the `X-Forwarded-For`.

**Comment by anatol** [comment]
http server implementation is surprisingly simple and it was easy to write own TCP socket loop

```
server = TCPServer.new("0.0.0.0", my_port)
begin
  sock = server.accept
  io = BufferedIO.new(sock)
  request = HTTP::Request.from_io(io)
  response = my_process_function(sock, request)
  response.to_io io
  io.flush
  sock.close
end while true
```

It works great.

**Comment by jhass** [comment]
I'm currently using the following method: https://github.com/jhass/carc.in/blob/master/src/web.cr#L68-L74

A proper solution should fallback to the sockets peer ip afterwards.

**Comment by anatol** [comment]
It was easy to implement my own version of the server as in the comment above. This issue might be closed now if devs think `repome_ip` is not needed.

**Comment by asterite** [comment]
We'll soon take a look at this with @waj, as it seems this is very needed :-)

**Comment by ozra** [comment]
To be picky, the remote_ip should be associated with the connection and the request. Though, use-wise it would be both more convenient and logical on the request object.

**Comment by crisward** [comment]
`request.remote_ip` would be very useful. Any news on this recently?

**Comment by crisward** [comment]
If you're using crystals behind nginx, you should be able to get the remote ip with

`remove_ip = context.request.headers["X-Forwarded-For"]?`

I'm using dokku with the heroku buildpack and this seems to work fine.

**Comment by RomanHargrave** [comment]
Luckily since I run everything behind a load balancer, I am able to, by way of headers, obtain a remote IP. That being said, it would be nice to have fields, perhaps a `client_ip` and a `remote_ip`.

The distinction between the two being that `remote_ip = client_ip` _unless_ `X-Forwarded-For` (or `X-Real-IP`) are present.

**Comment by rdp** [comment]
See also #1722

**Comment by straight-shoota** [comment]
Given that this is requested quite often (it has come up a few times on Gitter in the past weeks) and there is a working implementation in #1722, I wonder how this could be pushed forward?
The existing PR is outdated, but it should not be too difficult to rebase and move the implementation over to `HTTP::Context` (which was introduced in between) as suggested by @asterite and @ozra.

**Comment by samueleaton** [comment]
I'm trying to build a proxy server in crystal and need to add my own `x-forwarded-for` header before forwarding the request but need this to be available to the server context. Since this PR is super old, should I open another? Its a simple addition.

**Comment by straight-shoota** [comment]
@asterite in [#1772](https://github.com/crystal-lang/crystal/pull/1722#issuecomment-333109188)
> We still need this functionality, though, but it will probably come from the core team. Maybe we can copy [what Go does](https://stackoverflow.com/questions/27234861/correct-way-of-getting-clients-ip-addresses-from-http-request-golang/27235620#27235620), but I don't know (I don't know much about HTTP and proxies).

I'd really like to see this move on and I don't know why this couldn't be implemented by a non-core member. It's actually not that big of a deal I think.

One hold-up was the question *where* the remote IP should be stored but it seems that `HTTP::Context` is accepted as appropriate.
The actual implementation is not really difficult and there are many examples to look at, including Go. Some details might need some discussion but I wouldn't expect serious problems.

**Comment by straight-shoota** [comment]
@ysbaddaden in https://github.com/crystal-lang/crystal/pull/7302#pullrequestreview-202518264
> asking for the remote address should be on demand, not called on each and every connection.

I've been thinking about this. While I generally agree, there seems a flaw in this approach: It makes `Request` dependent on a `Socket` instance. The method can't provide any value if the socket has already been closed. Obviously, a closed socket usually means handling the request should be aborted because you can't send a response anyway. But it might still be relevant to collect metadata about the connection (like the remote address) for logging and debugging purposes. This won't be possible if the connection is closed premature, before any server handler could query the request for its remote address.

This makes me wonder if it wouldn't be better to retrieve the address at initialization and store it in an ivar. It adds a little performance penalty, but is more fault tolerant and reduces overall complexity.
