### ISSUE TITLE
Updating the roadmap page on the wiki.

### ISSUE THREAD

**Issue by abhi18av** [crystal-lang/crystal#4552]
Hey, crystal team :)

This is a not a feature request or an issue, just a reminder to update the roadmap as laid out on the wiki section. Feel free to close this.

I see that much work has been done since then, perhaps some of the enlisted tasks have been completed?

**Comment by RX14** [comment]
The roadmap looks pretty up-to-date to me.

**Comment by ysbaddaden** [comment]
Most of the roadmap is still valid. Goals are large and can't be reached in only a few months. For example

I ticked Random and SecureRandom, since most of the work has been done recently (and #4536 is only missing a merge).

I started working on adding nanoseconds precision to Time and Time::Span, but it ain't an easy task (instead of a single Int64 ticks, we have an Int64 + Int32).

**Comment by RX14** [comment]
@ysbaddaden I like go's idea of adding a monotonic clock value to `Time` as well but I don't think there's any way to fit that in 128 bits (with TZ offset). Maybe if we reduced tick precision for `Time` but added a monotonic nanosecond precision clock as well that would be enough.

**Comment by akzhan** [comment]
Go time is (sec Int64, nsec Int32, loc Location(ref) struct).

And I think that trying to fit it into 128 bit is not the target.

**Comment by asterite** [comment]
I wouldn't worry at all about the size of the `Time` struct. I'd focus on having the features we'd like, and correctness before performance.

**Comment by RX14** [comment]
@akzhan Not in master: https://github.com/golang/go/blob/b0d592c3c9a356b661c2d6bb958528f2761d821e/src/time/time.go#L116.

**Comment by mverzilli** [comment]
Closing, @ysbaddaden and @RX14 properly answered the question.
