### ISSUE TITLE
JSON.parse generates illegal JSON

### ISSUE THREAD

**Issue by TPei** [crystal-lang/crystal#4583]
The generated JSON includes `=>` characters instead of the expected `:` characters. So something like `key => value` instead of `key: value`

What I'm doing is parsing a json compatible String like so
```
le_string = %({ "key": { "embedded": "some levels" }, "key2": "value" })
le_json = JSON.parse(le_string)

puts le_json # => { "key" => { "embedded" => "some levels" }, "key2" => "value" }
puts typeof(le_json) # => JSON::Any
```

Crystal 0.22.0 (2017-04-20) LLVM 4.0.0 on macOS Sierra 10.12.5

**Comment by TPei** [comment]
Hmm, ok, apparently calling `.to_json` on the JSON did the trick... Is that expected behaviour?

**Comment by straight-shoota** [comment]
`JSON.parse` *parses* a string into an object that represents the JSON content. In this case it is a `Hash`, because the string contains an JSON object.
The string representation of a Hash in Crystal looks somewhat similar to JSON with `=>` instead of `:`, but it is something entirely different.
Only the `.to_json` method converts an object into a valid JSON string.
This is all explained in the docs: https://crystal-lang.org/api/0.22.0/JSON.html
