### ISSUE TITLE
Cannot inspect a lib's `type SpecificType = Int32`

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4682]
```cr
lib LibA
  type SpecificType = Int32
end

var = 1.as(LibA::SpecificType)
puts var.inspect
```
Gives error: `undefined constant LibA::SpecificType::MIN`
https://carc.in/#/r/2b7h

I know that types declared as `type XXXX = YYYY` are more restricted than others, but I would expect this usecase not to fail.

_Note: using `alias` instead of `type` works as expected. But I like the strictness of `type`, as I want to enforce the use of `SpecificType` instead of `Int32`._

---
A minimal failing code:
```cr
lib LibA
  type SpecificType = Int32
end

puts Int32::MIN
puts LibA::SpecificType::MIN
```
https://carc.in/#/r/2b7i

**Comment by bew** [comment]
Should this be fixed (will you accept PRs for this)? Or is this intended behavior?

**Comment by ysbaddaden** [comment]
Not a bug: you create a new type. Any constant defined on the previous type simply don't exist in the new namespace.

You really should use an alias in this example. There is no benefit to specify a new type: there is no ambiguity, passing any Int32 will work. Unlike opaque structs represented as Void pointers: passing any Void* is wrong and will likely segfault.

**Comment by RX14** [comment]
Is there any usecase for `type` outside of `Void*`? If not, maybe we should restrict it to `Void*`?

**Comment by bew** [comment]
I'm trying to bind to XCB, where in the API every manipulated object is represented by an ID (Int32) in the lib: a WindowId, a VisualId, a GraphicContextId, and everything.. So when using the bindings, I want to ensure that I have a WindowId and not something else.

**Comment by mverzilli** [comment]
I think the use case makes sense, it would make it easier to "sanitize" bound C APIs. If I understand the issue correctly, what we're missing here is a way to create values for types defined with `type` inside a `lib`. `as` is for casting, which should be a last resort. Note however that in general we suggest to encapsulate bindings in an idiomatic Crystal module. So "naked" C types shouldn't ever be accessible from outside their idiomatic Crystal wrapper.

**Comment by bew** [comment]
> Note however that in general we suggest to encapsulate bindings in an idiomatic Crystal module. So "naked" C types shouldn't ever be accessible from outside their idiomatic Crystal wrapper.

True, and this would solve my problem, but I'd like to _sanitized_ the bindings themselves, and I think it would be a great feature to be able to do just that. 

From my understanding, the only functional  difference between `alias` and `type` is that:
- By using `alias SpecificType = Int32` we can interchangeably use a `SpecificType` or an `Int32`.
- Using `type SpecificType = Int32` ensure that when we restrict e.g. a method to the new type, an `Int32` won't match but a `SpecificType` will. 

In the end the 2 types should be the same, only the type inference and restrictions system should be concerned here. 
And by the 2 types beeing the same, they should have access to the same constants too.

**Comment by mverzilli** [comment]
I understand you needed to #inspect, so the title here is good :).

But you're looking for higher type safety, that's why you want to use `type` and not `alias`. To get that kind of type safety you need explicit constructors on the side of Crystal, if values are just shareable then you get nothing as @ysbaddaden said. So the minimal failing code you provided shouldn't compile (the last line should end up looking like `puts LibA::SpecificType.new(Int32::MIN)` or you'd have to explicitly create a `MIN` constant for `LibA::SpecificType`.

**Comment by bew** [comment]
> From my understanding, the only functional difference between alias and type is that:
>
> - By using `alias SpecificType = Int32` we can interchangeably use a `SpecificType` or an `Int32`.
> - Using `type SpecificType = Int32` ensure that when we restrict e.g. a method to the new type, an `Int32` won't match but a `SpecificType` will.
>
> In the end the 2 types should be the same, **only the type inference and restrictions system** should be concerned here.
> And by the 2 types beeing the same, they should have access to the same constants too.

Is this correct? From what @ysbaddaden said it's not ("you create a new type. Any constant defined on the previous type simply don't exist in the new namespace").

Is there something wrong with my vision? (why is it not working like that?)

**Comment by asterite** [comment]
I actually want to remove `type` for a long time now. It's a broken concept. For example if you have `x` of type `SpecificType`, you can't compare it, or add an integer to it, because the method is only defined for integers, not typedefs.

I think the type safety it provides is minimal. Plus when you write a binding you will write very little "C" code with it, so chances of getting a type wrong are minimal too. In fact, I can't remember a time where I passed an incorrect `type` to a function or struct expecting one.

We should first make `type` be the same as `alias` (in fact, you'll be surprised to know that this is already the case when the type is a `Proc`, because of the reasons I mentioned above), then make the formatter rewrite `type` to `alias`, then remove `type`.

**Comment by RX14** [comment]
@asterite How about this alternative idea: `type` only works for `Void*`. Would that simplify things and solve this issue?

**Comment by asterite** [comment]
I don't know. The compiler has some hacks to make `type` work. I'd remove it.

**Comment by RX14** [comment]
@asterite my thought was that making it only work with `Void*` would simpify the compiler, if it doesn't then we might as well remove it.

**Comment by straight-shoota** [comment]
Superseeded by #10031
