### ISSUE TITLE
Empty interpolation is not allowed

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-lang/crystal#4725]
This program cannot be compiled:

`foo.cr`:

```crystal
"#{}"
```

```console
$ crystal --version
Crystal 0.23.1 (2017-07-13) LLVM 4.0.1
$ crystal run foo.cr
Syntax error in foo.cr:1: unexpected token: }

"#{}"
   ^

```

Is this an intended behavior?

Related issues: #4592 and #4607 (empty expression's semantics are discussed there)

**Comment by straight-shoota** [comment]
In Ruby it evaluates to the empty string.
Though I don't know if it should, because it looks very much like there is something wrong if you have an empty interpolation. But it might be useful when used with macros, where you can assign a variable name to be interpolated and if it is empty it would print nothing. But then you could just use `nil`.

**Comment by Sija** [comment]
I believe there's nothing wrong with such construct. It can occur for instance because of empty macro result.

```cr
{% begin %}
pp "#{{{ false ? 1.id : "".id }}}"
{% end %}
```

**Comment by RX14** [comment]
An empty expression is nil, `Nil#to_s` returns `""` so the result being `""` makes sense.

I wouldn't be opposed to supporting an empty interpolation, as we've decided to support empty expressions with `()`.

**Comment by MakeNowJust** [comment]
Hmm... Crystal accept only one expression inside string interpolation.

```crystal
puts "#{
  a = 1
  a
}"
# Syntax error in foo.cr:3: Unterminated string interpolation
#
#   a
# ^
```

It works on Ruby.

And however this works:

```
puts "#{(
  a = 1
  a
)}"
```

**Comment by oprypin** [comment]
I don't think this should be supported. There is no valid use case for it and it can hide errors.

Ruby supports any number of expressions in interpolation, Crystal supports exactly 1.
If you really want any number, add ()

**Comment by MakeNowJust** [comment]
@oprypin Yes. But I have a question. You said:

> There is no valid use case for it and it can hide errors.

When and how can it hide errors?

**Comment by oprypin** [comment]
Well, when you write `#{}`, in 99.9% of cases you want the compiler to tell you you made a mistake.

**Comment by MakeNowJust** [comment]
Ok. But current error is confusing to me, it should be improved.

**Comment by straight-shoota** [comment]
A valid use case was pointed out by @Sija
Maybe this is better understandable:
```crystal
macro foo(optional_name = "")
  "macro foo #{ {{optional_name}} }"
end
```
If you have to ensure that no empty string is inserted, this code becomes much more complicated. And this would be a measure that is easy to forget.

**Comment by RX14** [comment]
We either remove `()` and `"#{}"` or support both. I misremembered that we had decided to support `()` (we hadn't).

**Comment by straight-shoota** [comment]
@RX14 I understand [#4607 (comment)](#issuecomment-310673085) that it was decided to support `()`.

**Comment by RX14** [comment]
Man, it's really hard to discover decisions and discussion when they're spread over multiple issues. Perhaps we should be more active in encouraging only discussions of the implementation when in a PR which originated from the issue.

**Comment by oprypin** [comment]
`()` supports any number of expressions, including 0.
`"#{}"` supports one expression. Adding a special case for 0 expressions is bad. Adding support for multiple expressions in string interpolations... just ugh.

It's more often useful to see that you're doing something bad when you allowed the interpolation to be empty, than silently ignore it.
All supporting examples so far were very contrived. I am not convinced that there is a single use case.
If you're doing something crazy in macros, you'd better not be putting all of that inside interpolation, just like in normal code.
If you really really want to apply a workaround, use `#{()}`.

> We either remove () and "#{}" or support both.

I very strongly disagree with this, especially because it's used as a justification while these things are entirely different.

**Comment by straight-shoota** [comment]
Parenthesis and interpolation are very different, that's true.
But the case for allowing an empty expression is valid for both. Essentially, the interpolation means, take what's between `#{` and `}` and insert it's value into the string. If there is only empty space in between, this evaluates to `nil` and `nil` is inserted into the string - which equals to inserting an empty string.

**Comment by kirbyfan64** [comment]
IMO this isn't really necessary. If someone wants a potentially empty interpolation, they can just use parens:

```crystal
pp "#{({{ false ? 1.id : "".id }})}"
```

**Comment by MakeNowJust** [comment]
@oprypin's opinion gets many :+1: and I agree with @oprypin, so I close this. Thank you!
