### ISSUE TITLE
Consider extracting typechecker

### ISSUE THREAD

**Issue by stereobooster** [crystal-lang/crystal#4731]
Basically Crystal is based on Ruby Syntax (with some extension). I was wondering if I can reuse Crystal type checker as gradual type checker for Ruby files. Something like Facebook Flow for JavaScript. Matz considering to add gradual types to Ruby3, but that long time to wait. There was some research in this area, but nothing promising. Still looking for solution

**Comment by zatherz** [comment]
Crystal is not Ruby

**Comment by bcardiff** [comment]
The typechecker depends not only on the syntax but also with the semantics of the language. And there are some subtle differences and rules that differs from ruby.

If there is something to be extracted in the future is some sort of abstraction that could allow hosted languages (despite it's syntax nature) to describe dependencies and data flow between variables, describe method resolution and query the type inference for types of variables/expressions if the program is valid. 

Although is something I would like to see in order to avoid efforts in different languages to add type inference, it is not currently one of crystal's goals. Yet, the implicit union and other semantics of the languages could serve as inspiration.
