### ISSUE TITLE
Segfault, when method is called on a function name

### ISSUE THREAD

**Issue by akoskovacs** [crystal-lang/crystal#4756]
# Test code
```crystal
def something
    fname = something.to_s
end

something
```
As far as I understand this code shouldn't compile or at least it should give a warning. But when I tried to run the code, I got:

```
akos@pole:/tmp $ crystal something.cr
Invalid memory access (signal 11) at address 0x7fff7fed7ff8
[0x459975] *CallStack::print_backtrace:Int32 +117
[0x44ecfd] __crystal_sigfault_handler +61
[0x7f266e7ca390] ???
[0x44ed11] *valami:NoReturn +1
[0x44ed16] ??? (523805 times)
[0x43f7cb] ???
[0x44ebf9] main +41
[0x7f266dded830] __libc_start_main +240
[0x43f0f9] _start +41
[0x0] ???
```
I got the same `SIGFAULT` when I started the compiled binary. The compilation itself did't give any error message.
# Environment
```
akos@pole:/tmp $ uname -a
Linux pole 4.8.14-akos #2 SMP Wed Dec 14 19:30:21 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
akos@pole:/tmp $ crystal -v
Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1
```

**Comment by straight-shoota** [comment]
I don't think this is a compiler error. You are creating an infinite recursion. The compiler can't possibly prevent that. That's the programmer's job.

**Comment by RX14** [comment]
This is a stack overflow, you can tell by the "(523805 times)" in the stacktrace. You're simply calling your own function with no base condition.

That being said i'm not sure why `something.to_s` compiles when  `something` is typed `NoReturn`.

**Comment by MakeNowJust** [comment]
@RX14 I implemented such a feature: the compiler detects using `NoReturn` as method caller or argument, then it raises an error. See [wip/noreturn-detection branch](https://github.com/MakeNowJust/crystal/tree/wip/noreturn-detection).

Using this compiler, you can see it:

```console
$ ./bin/crystal run something.cr
Using compiled compiler at `.build/crystal'
Error in something.cr:2: NoReturn cannot call any methods (infinity recursion?)

    fname = something.to_s
            ^~~~~~~~~

```

But the compiler source code uses very complex recursion. There are many `NoReturn` calls (it seems intentional to me), so this compiler cannot compile the compiler itself.

**Comment by RX14** [comment]
@MakeNowJust `NoReturn` on it's own should error, however `NoReturn` in a union should disappear. Shouldn't that resolve the problem?

**Comment by lbguilherme** [comment]
@RX14, `exit` and `abort` are of type `NoReturn`, which is correct.

**Comment by MakeNowJust** [comment]
@RX14 I consider about implementing this feature, and then I think it is impossible now. We have to treat `NoReturn` as value sometimes in fact.

For instance, when we want write-only `IO` object, we define such a class:

```crystal
class WriteOnlyIO
  include IO

  def read(buf : Bytes)
    raise "Can't read from WriteOnlyIO"
  end
end
```

`WriteOnlyIO#read(buf : Bytes)`'s result type is `NoReturn`, and the compiler compiles included methods against each included classes, so we could see using `NoReturn` as value on the method using this `read`. `IO#read_byte` for example is such a method:

```crystal
# From src/io.cr:299
# ...
  def read_byte : UInt8?
    byte = uninitialized UInt8
    if read(Slice.new(pointerof(byte), 1)) == 1
      byte
    else
      nil
    end
  end
# ...
```

`read(Slice.new(pointerof(byte), 1)) == 1` is `NoReturn` expression because this `read` is `NoReturn`. If the compiler disallow using `NoReturn` as value, we loss the flexibility of including and inheritance.

**Comment by RX14** [comment]
@MakeNowJust Surely `IO#read(buf : Bytes)` would return `Int32 | NoReturn`, and we can safely ignore the noreturn. Unless you explicitly type the variable as `WriteOnlyIO`, in which case the error would be correct.

**Comment by MakeNowJust** [comment]
@RX14 

> Unless you explicitly type the variable as WriteOnlyIO, in which case the error would be correct.

I think it is impossible at least on the current Crystal.

Please look this code:

```crystal
abstract class Base
  abstract def override : Int32

  def base
    {{ puts(@type) }}
    p typeof(override)
  end
end

class Foo < Base
  def override
    1 # correct
  end
end

class Bar < Base
  def override
    raise "bar"
  end
end

Foo.new.as(Base).base
Bar.new.as(Base).base
```

And its output is:

```
$ crystal run --stats foo.cr
... (skip)

Semantic (main):
Bar
Foo
Base

... (skip)

Int32
NoReturn
Execute:                           00:00:00.0154300 (  58.41MB)
```

Repeatedly I say: *the compiler compiles (instantiates) inherited methods against each inherited classes*. In addition, `Base#base` method is expanded to it like this internally:

```crystal
  def base
    return self.as(Foo).base if self.is_a?(Foo)
    return self.as(Bar).base if self.is_a?(Bar)
    raise "error..."
  end
```

In other words `self` is typed as `Foo` or `Bar` explicitly but internally. And to detect such a internal typing is very difficult for now.

**Comment by asterite** [comment]
Duplicate of #271
