### ISSUE TITLE
I <3 Crystal

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#4757]
It's my tribute to all Crystal contributors: **Thank you!**

Crystal is the most awesome language in my life. It takes the best from Ruby, it includes all the useful libraries and makes it a part of the language. It's super fast and has the sweetest syntax ever crafted by a human! Crystal itself is the best thing ever happened in my small programmers life!

However, maintainers need to continue posting stuff about Crystal; from the side it looks like it's dead from April'17. More users come - the better shards will be. It's an actual issue for me right now - community shards often lack in the quality of code - because they think they are still on Ruby. The truth is Crystal is lot of steps beyond Ruby and the coding possibilities are much bigger!

Please, continue developing Crystal. It will be (or it already is) the next **Language** (from capital L), I promise! :heart: 

P.S: My skills are too bad for contributing into Crystal itself, but I wish I could. Also I try to contribute into community projects as much as I can.

**Comment by sdogruyol** [comment]
Thank you for your great words and thanks again for sharing @vladfaust 🙏 

The community is with you, you can be sure that there're lots of Crystal developers out there who share the same feelings with you. (I'm also one them 😄 ) Recently the core developers weren't contributing that much because they're actually developing Crystal on their free time. 

Actually there's not a full time Crystal core developer. How about we step up and increase the support on [BountySource Campaign](https://salt.bountysource.com/teams/crystal-lang) to get a Crystal core developer working full time. Everything helps.

Other than financial support please share your experience with Crystal. Blog posts, tutorials, videos, screencasts e.g anything is welcome and will help Crystal development ❤️

**Comment by bararchy** [comment]
I think that the issue is less how much Core-devs are actually contributing and more how much the communicate to the community about the state of things.
A language without a community is just a bunch of people saying look at my cool project, with a community however it's a paradigm shifting project ! 

As part of the community and someone who share those feeling of lack of information I too feel less comfortable in my choice of using Crystal for production project and time spent learning and helping.
It's not that I want something in return, I just want information, who is currently working on Crystal ? a budget of 2.5K USD is at least enough for someone to spend 2 days a week working on the project.


Anyway, point being is that I want something to show new users and co-workers to allow me to say "See , this language is advancing and ongoing, there are people who support and work on it, we should use that for new projects"

**Comment by oprypin** [comment]
I don't understand how faking progress for show would help.

**Comment by bararchy** [comment]
@oprypin I don't think he meant "faking" it was more about higher advisability for things that actually happen which right now are kinda behind the scene.

**Comment by bararchy** [comment]
Just pinging @matiasgarciaisaia as he is the de-facto community manager :)

**Comment by konovod** [comment]
perhaps offtopic, but exactly my feeling - it's the best thing happened in my programmer life. I'm so sad i haven't enough skills to contribute (to an important parts, not just dropping Mersenne :smile: ).

About progress - i'm slightly scared by the amount of work that Crystal still need. Looks like Windows support is much closer now (and it's the only thing that stops me from using it at work), but there is also multithreading, generics review, incremental compilation - they all could require plenty of workdays even for as highly-professional specialists as core team (and contibutors) are.
Blog posts about small progress are good, but these big things are IMHO even more important, reaching even one of them (say, Windows support :smile: ) will justify several months of silence.

**Comment by akzhan** [comment]
Windows support is something strange for me (there is great .NET ecosystem with F#/C#).

Multithreading is MUST HAVE.

But both features are less wanted for me than type system. It is not solid yet.

**Comment by faustinoaq** [comment]
@akzhan @matiasgarciaisaia  I think Windows support is very important.

All new languages [Rust](https://www.rust-lang.org/en-US/install.html), [Elixir](https://elixir-lang.org/install.html#windows), [Nim](https://nim-lang.org/install_windows.html), [Go](https://golang.org/doc/install), [Kotlin](https://github.com/JetBrains/kotlin-native/issues/461#issuecomment-310683001) and even [Swift](https://swiftforwindows.codeplex.com/) supports Windows.

Currently, Crystal is the only new language without Windows support.

**Comment by watzon** [comment]
I’m definitely on board for getting more hype for Crystal and building a community. Has anyone thought about doing a weekly or semi-monthly podcast about Crystal? Just had the idea myself, but I’d like to get everyone else’s take on it

**Comment by sdogruyol** [comment]
I've been itching to start a podcast but unfortunately haven't had the time to do so. I'll totally support it 👍  @watzon

**Comment by watzon** [comment]
@sdogruyol I’d definitely love to, I’d just need to know that I have support from the current community 😁 of course it would be nice to do it as a collaboration rather than just having me talking. Things are a lot more fun that way

**Comment by jwoertink** [comment]
I love Crystal, and really wanted to move over to it. My issue is there's a lot of things the core language is missing that prevent some of my apps from working. The bounty source goals says at $2,500 we get 2 developers working 8 hours per week on the language. Looking back through the month of July, you can see the only core member from that list to make any commits was [waj](https://github.com/crystal-lang/crystal/commit/158a818ed431f5bb44a7f479f19ff716d03c2a6a). Then mverzilli helped merge a few commits. Maybe we can get @MakeNowJust, @ysbaddaden, or a few others on to that list of those core devs? They seems to be crushing it lately, and I would feel much better about contributing to the bounty source if I knew they were getting that support.

It would also be nice to see [this blog](https://crystal-lang.org/blog/) updated more. Maybe an article on the direction or why development has slowed down? Keeping lines of communication open are definitely key in keeping a community thriving. 

I would love to see this progress further. I have even [submitted a PR](https://github.com/crystal-lang/crystal/pull/4190) that seemed to have been buried. I would just like to know what's priority, what direction this project is going, and if the 1.0 milestone is still on track, etc...

**Comment by bararchy** [comment]
@jwoertink I too would love to see who is getting paid via the source bounty I and many others contribute too , and would prefer active community members to begetting that instead of inactive core devs.

Not calling for a rebellion here , just want a little bit more clarity on what's going on.

**Comment by RX14** [comment]
@jwoertink ysbaddaden is already a core dev.

I do think that the level of work on crystal itself is unsustainable. At this rate of work we simply won't reach 1.0 before the end of 2018 let alone 2017. I'm mainly waiting for a response from the manastech guys, like everyone else I guess.

**Comment by faustinoaq** [comment]
@RX14 What Do you think are the minimal goals before reach 1.0?

**Comment by RX14** [comment]
@faustinoaq I agree pretty much entirely with this: https://crystal-lang.org/2016/12/29/crystal-new-year-resolutions-for-2017-1-0.html

**Comment by faustinoaq** [comment]
What are the knowledge needed to contribute to this compiler itself? ( I already read [CONTRIBUTE.md]

I already know about EBNF, Lexer and Parser like Flex and Bison.

@ysbaddaden @RX14 Which books or courses do you recommend to read before contribute to the compiler itself?

**Comment by RX14** [comment]
@faustinoaq We have a hand written lexer and parser, we don't use any formal BNF.

The only resource on compiler internals is in [here](https://codecamp.crystal-lang.org/Crystal-CodeCamp-SF2017.zip). There's a slide deck on the high-level structure of the compiler. The best way to learn the details is simply to get stuck in.

**Comment by MakeNowJust** [comment]
@faustinoaq I wrote the tutorial text to implement a new feature (a complex number literal) in the compiler, however, which was written in Japanese. If you and others want to read this, I'll try to translate to English.

**Comment by sdogruyol** [comment]
@MakeNowJust if you want I can help you with Japanese to English translation 😸

**Comment by faustinoaq** [comment]
@MakeNowJust where can I find your tutorial? Maybe I can use Google translate :stuck_out_tongue_winking_eye:

**Comment by matiasgarciaisaia** [comment]
Hi everyone!

I (we?) _really_ love both the love & the feedback. We **are** continuing Crystal's development, we **are** going to be around here in one, two, five years.

I think the support for any community effort is always there - we didn't hesitate in adding the awesome-crystal, crystal-weekly or things like that to [Crystal's community page](https://crystal-lang.org/community). So anyone interested in running a podcast, blogpost series, live twitch series coding the compiler, you-name-it - just drop us a line/tweet/pidgeon, and we'll try to share it via our channels.

Don't take this message as "The Response From Manas.Tech" that you were expecting - this is just a starter quickly written by me on a bus :)

I think we're sharing kind of nice news soon-ish - we're certainly addressing this issue's concerns soon.

Thanks for all the fish :)
Mati

**Comment by MakeNowJust** [comment]
@faustinoaq here <https://github.com/crystal-jp/techbookfest2/tree/master/makenowjust>.

**Comment by faustinoaq** [comment]
Thanks +1

On Sat, Aug 5, 2017 at 12:53 PM, TSUYUSATO Kitsune <notifications@github.com

**Comment by asterite** [comment]
Thank you!

**Comment by vladfaust** [comment]
Just wanted to share my single sticker view... And it's Crystal! Got a pack of them, thought they were bigger.

![image](https://user-images.githubusercontent.com/7955682/32133743-d5f67780-bbe6-11e7-8690-c055380ce3ca.png)

**Comment by GloverDonovan** [comment]
Adding my opinion here. The [Crystal documentation](https://crystal-lang.org/docs/) is one of the best I've ever read. Simple, straight-forward, and to the point. It is one of the main reasons why I'd recommend Crystal to new and experienced programmers alike.

But what good is documentation without the language behind it? Part of the reason why the documentation is so great is because of the language design behind Crystal. Reading (and writing!) Crystal is certainly a pleasurable experience.
