### ISSUE TITLE
Support YAML core schema

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4771]
Crystals YAML API currently only supports the [Failsafe Schema](http://yaml.org/spec/1.2/spec.html#id2802346) which has the datatypes mapping, sequence and string. It should be enhanced to support the [JSON Schema](http://yaml.org/spec/1.2/spec.html#id2803231) and [Core Schema](http://yaml.org/spec/1.2/spec.html#id2804923) which also recognize the datatypes null, boolean, integer and floating point as well as some improvements to readability for humans.
According to the YAML specification, *Core Schema* is the *recommended default schema that YAML processors should use*.

LibYAML does not directly support datatype mapping, so this needs to be implemented on top of that.

Related issues: #4384 #2235 #3101 #4175

**Comment by ysbaddaden** [comment]
Duplicate of #3101. Please add additional information to existing issues, thanks.

BTW: the JSON Schema shouldn't be supported: parsing JSON using a YAML parser was the source of many critical security bugs in Ruby and Rails, for example.

**Comment by straight-shoota** [comment]
This is actually intended as a meta issue to combine the different aspects of supporting [Core Schema](http://yaml.org/spec/1.2/spec.html#id2804923), which is certainly not the same as[language independent types](http://yaml.org/type/).  Therefore I don't see how this could possibly be a duplicate. 

If #3101 is about supporting types from JSON schema, it should be titled accordingly but would still only be a subsection of this issue. 
Language independent types already have some basic support from libyaml, the tag information can be accessed through `PullParser.tag`. We won't need to to parse all of them natively.

The Core Schema requires the parser to implement parsing the datatypes defined in JSON Schema. Core Schema is a subset of JSON Schema - which just means to support the same datatypes as JSON, not to parse actual JSON data with YAML parser.

**Comment by straight-shoota** [comment]
@ysbaddaden would you consider reopening this?#3101 has a different focus which is only partly overlapping with supporting Core Schema.

**Comment by perlpunk** [comment]
Hi, I stumbled upon this issue while searching for something else. Because I'm doing a lot of work for YAML currently I wanted to leave my comments about this topic here.

I recently wrote this article about YAML Schemas: http://blogs.perl.org/users/tinita/2018/01/introduction-to-yaml-schemas-and-tags.html

I'm currently writing a YAML processor for Perl which is supposed to offer all three YAML 1.2 Schemas and additionally the 1.1 Types.
One should be able to specify which Schema(s) one wants to use, and which additional types, for example `JSON+timestamp+binary+(userdefined tags)`. I'm still thinking about a good API for that.

The current YAML team thinks that the JSON Schema (with minor fixes) should be default for future versions, and all additional types should be optional.
