### ISSUE TITLE
[RFC] Create crystal-lang/crystal-rfcs

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#4944]
The main crystal repository is full with issues that suggest features or functionality. This clutters the repository with issues that are not issues at all.

I suggest we create another repository, `crystal-rfcs`, for submitting RFCs and discussing them there. RFCs should probably also follow some guideline, specially if they are about language features, but for now we can simply not require anything special.

This would be similar to how [Rust](https://github.com/rust-lang/rfcs) handles this.

Thoughts?

**Comment by asterite** [comment]
One example: https://github.com/crystal-lang/crystal/issues/4754

**Comment by Sija** [comment]
`crystal-lang/rfcs` seems 'nuff

**Comment by sdogruyol** [comment]
I say, let's go for it :+1: It's easier and simpler to handle discussions / suggestions in a separate repository.

**Comment by Fryguy** [comment]
Alternate idea: What about a label on the issue?  Then with GitHub search just tack on a `label:rfc` if you want to see labels and a `-label:rfc` if you don't want to see labels.

One reason I don't like a separate repo is that casual contributors won't be aware of it (even if it's in an ISSUE_TEMPLATE.md, they don't read it), and they will make the issue here anyway, meaning a core contributor has to transfer it.  Not really a huge deal, but it does add some overhead.

**Comment by Sija** [comment]
@Fryguy we already have too many of those, IMO introducing a new one would only make things worse.

**Comment by ensoxyz** [comment]
why not just do the reverse `crystal-issues` and let this be the report for request. This would allow a clean slate and clear up all the clutter and confusion instantly.

**Comment by lbguilherme** [comment]
@ensoxyz then commits won't be able to close issues so easily. And it is better to have issues about the code near the code itself.

Something like a hosted discourse could also be considered. Either way, seems good to move proposals apart from actual actionable and specific issues. +1

**Comment by monouser7dig** [comment]
can the scope of this expanded to not only `code/ implementation` but also `usage/ best practice` because I think the documentation could still benefit by `keeping such issues closer to the language/ incorporating them` than outsourcing to stack overflow?

Searching for crystal questions is a bit of a pain although I think many have already been asked.
A central place may be the best until crystal gains further adoption/ spread.

**Comment by akzhan** [comment]
Core team should be extended to handle more infrastructure as I suppose.

**Comment by asterite** [comment]
Nevermind, compared to other repos of other languages we still have very low traffic, so this is not an issue.

**Comment by luislavena** [comment]
On a personal note, I would love people submit issues to discuss possible
API addition or changes instead of direct work on a PR that might generate
lot of back and forth and consuming more time and effort.

Sorry for top posting. Sent from mobile.
