### ISSUE TITLE
Overload operators not working when using with `with..yield` syntax

### ISSUE THREAD

**Issue by AlexanderChen1989** [crystal-lang/crystal#5006]
Crystal: 0.23.1 (2017-09-08) LLVM 4.0.1
OS: MacOS X El Capitan 

```crystal
struct Vector2
  def initialize(@x : Int32, @y : Int32)
  end

  def +(other)
    Vector2.new(@x + other.x, @y + other.y)
  end
end

def build(x, y)
  v = Vector2.new(x, y)
  with v yield v
end

build(1, 2) {
  +Vector2.new(3, 4)
}

```

**Comment by asterite** [comment]
I think considering `+x` to invoke `+` on the hidden object yielded by `with ... yield` is super cryptic. That said, I consider `with ... yield` already cryptic and magical enough, that I've been wanting to remove it from the language from some time now. So operator overloading in this case is something that's much less likely to ever happen.

**Comment by AlexanderChen1989** [comment]
`with ... yield` syntax enables neat DSL syntax like Kotlin, but Kotlin implement this with Extension Functions

**Comment by asterite** [comment]
Actually, in your example, this happens:

```crystal
+exp
```

The above parses to `exp.+()`. That's why it's not found.

Comparing with how `with ... yield` works, you have this:

```crystal
some_method(argument)
```

then `some_method` would be looked up in the implicit object, like `implicit_object.some_method(argument)`. But in the case of `+exp` it's not the same as `implicit_object.+(exp)`, it's always `exp.+()`.

There simply is no way to disambiguate that.
