### ISSUE TITLE
Feature Request: Mutable NamedTuple

### ISSUE THREAD

**Issue by ansarizafar** [crystal-lang/crystal#5015]
Mutable NamedTuple are easy to understand, define (user = {count: Int32, name: String}) and use, especially for Developers coming from Nodjes/Javascript.

In my opinion, many Nodejs developers would like to switch after V1 release as less memory/CPU usage and performance gains will be huge.

**Comment by faustinoaq** [comment]
Hi, I'm developer coming from Python world.

I think currently we have inmutable and mutable sequences:

**Inmutable sequences:** just like Python Tuples, is a bit difficult to understand by Ruby a JS developers because those languages don't have inmutable sequences by default.

- [Tuple](https://crystal-lang.org/api/latest/Tuple.html)
- [NameTuples](https://crystal-lang.org/api/latest/NamedTuple.html)

**Mutable sequences:** just like any other dynamic sequence in almost all imperative programming languages.

- [Array](https://crystal-lang.org/api/latest/Array.html)
- [Hash](https://crystal-lang.org/api/latest/Hash.html)

I think we just need a better documentation :wink:

**Comment by faustinoaq** [comment]
@ansarizafar also see: https://crystal-lang.org/2016/05/17/crystal-0.17.0-released.html

**Comment by crisward** [comment]
I am also from a JS background. I think the confusion comes from the braces `{ }`, us JS devs love our braces :wink:

Hashes just don't look like js objects, and the use of fat arrows, look either like an ES2015 function definition or a PHP array. 

As @faustinoaq says, this is more a docs issue.

**Comment by mverzilli** [comment]
Thanks @faustinoaq and @crisward for addressing this. Closing.
