### ISSUE TITLE
Provide `compile` as a replacement/alias for the `build` command

### ISSUE THREAD

**Issue by chocolateboy** [crystal-lang/crystal#502]
The help message uses "compile" ("compile program file") and most compilers typically have a `c` suffix or use `-c` or `--compile`.

**Comment by asterite** [comment]
I think this is a reasonable change

**Comment by keplersj** [comment]
Just for clarification, because I'm thinking about taking this issue on, should `crystal compile file.cr` have the same behavior as `crystal build file.cr` or should it do something different?

**Comment by jhass** [comment]
it should be an alias really, for now. We can later think about phasing out/removing build.

**Comment by asterite** [comment]
Let's do the alias for now and recommend it as the way to compile.

**Comment by jhass** [comment]
So it would be great if you could update all docs to use it at the same time.

**Comment by keplersj** [comment]
Can do!

**Comment by asterite** [comment]
We had some internal discussions recently with @waj and @bcardiff and we are now not sure this was a good idea.

In compiled languages `compile` just means to compile, while `build` is more compile, link, generate an executable, etc. So `build` was probably more correct. And it's also shorter.

Since we are not 1.0 yet, we'd maybe like to revert this change. I think I rushed when I decided to accept this.

**Comment by lbguilherme** [comment]
I agree with reverting this. "Building" means producing the final result, where "compiling" is just one step of it. IDE's commonly have a "Build" button, for example.

As a reference: http://stackoverflow.com/questions/2310261/what-is-the-difference-between-compile-code-and-executable-code

gcc for instance by defaults builds an executable, and have an explicit `-c` (compile) option to only output the object code and skip linking.

So, +1 from me

**Comment by asterite** [comment]
I reverted the name change back to `build`. It was a mistake...
