### ISSUE TITLE
Comparing union of sub-structs affects comparison of other structs

### ISSUE THREAD

**Issue by bolshakov** [crystal-lang/crystal#5044]
```cr
abstract struct A; end
struct B < A; end
struct C < A; end

(B.new || C.new) == B.new

p C.new == C.new #=> false
```

```cr
abstract struct A; end
struct B < A; end
struct C < A; end

B.new

p C.new == C.new #=> true
```

Crystal 0.23.1 (2017-09-08) LLVM 4.0.1
OS X 10.11.6 (15G1611)

**Comment by oprypin** [comment]
Suggested title:

### Comparing union of sub-structs affects comparison of other structs

Reduced:

<table><tr><td>

```crystal
abstract struct A; end
struct B < A; end
struct C < A; end

(B.new || C.new) == B.new

p C.new == C.new
```
[`false`](https://carc.in/#/r/2t3t)

</td><td>

```crystal
abstract struct A; end
struct B < A; end
struct C < A; end

B.new

p C.new == C.new
```
[`true`](https://carc.in/#/r/2t3u)

</td></tr></table>

**Comment by bolshakov** [comment]
@oprypin thanks!

**Comment by asterite** [comment]
"Reduced" a bit more:

```crystal
struct Value
  def foo(other)
    "BAD"
  end
end

struct Struct
  def foo(other : self)
    {{@type}}
    "GOOD"
  end
end

abstract struct A
end

struct B < A
end

struct C < A
end

p (B.new || C.new).foo(C.new) # => "BAD"
```

It seems a macro def with `self` restriction isn't matched here for some reason.

**Comment by bolshakov** [comment]
Not sure if this is the same problem. I tried to implement singleton and encounter the following error

```cr
abstract class A(T); end
class C < A(Int32); end

class B < A(Nil)
  @@instance = uninitialized B

  def self.new
    @@instance ||= B.allocate.tap(&.initialize)
  end
end
```

```cr
(B.new || C.new) == B.new
puts B.new == B.new
```

Fails with error

```
>crystal spec/test.cr
Invalid memory access (signal 11) at address 0x0
[0x10773ddeb] *CallStack::print_backtrace:Int32 +107
[0x1077297cc] __crystal_sigfault_handler +60
[0x7fff8d3c152a] _sigtramp +26
[0x10771956f] __crystal_main +1279
[0x1077296c8] main +40
```

but this works as expected:

```cr
C.new
puts B.new == B.new #=> true
```

**Comment by bolshakov** [comment]
by the way I managed to implement singleton this way:

```cr
class B < A(String)
  @@instance : Nil | B
  @@instance = nil

  def self.new
    @@instance ||= B.allocate.tap(&.initialize)
    @@instance.as(B)
  end
end

(B.new || C.new) == B.new
puts B.new == B.new #=> true
```

**Comment by HertzDevil** [comment]
The original example works, but https://github.com/crystal-lang/crystal/issues/5044#issuecomment-332540066 still fails.

Seems to be related to #6760.

**Comment by HertzDevil** [comment]
In:

```crystal
class Foo
  def foo(x)
    1
  end
end

class Bar < Foo
  def foo(x : self)
    {{ @type }}
    "x"
  end
end

class Baz1 < Bar
end

class Baz2 < Bar
end

typeof(begin
  x = uninitialized Bar # or Baz1.new || Baz2.new
  x.foo(Baz1.new)
end) # => (Int32 | String)
```

The initial match with `Bar#foo` succeeds because `Baz1` matches the `self` restriction in `Bar`'s context. After that, when the compiler instantiates the macro def in each subtype, it performs lookup in that subtype's context using the same defs to recompute the whole `foo` call. Thus:

* Lookup in `Baz1` succeeds because `self` represents `Baz1`.
* Lookup in `Baz2` fails because `self` here represents `Baz2`, but the argument is a `Baz1`. Therefore, this matches `Foo#foo` instead, and `Int32` is returned.

This explains why the `foo` call might dispatch to `Foo`'s implementation even when it shouldn't happen for non-macro defs. One way to fix it is making `self` nodes always refer to `Bar` instead of the subtype during this lookup.
