### ISSUE TITLE
extend self + include module

### ISSUE THREAD

**Issue by monouser7dig** [crystal-lang/crystal#5082]
from gitter conversation, if this is not a bug but intended please close 

```crystal
module Foobar
  extend self
  def res?
  end
end

class Foo
  include Foobar
end

Foo.res?
#does not work

Foobar.res?
#works obviously 
```

although one could expect it to work because `Foobar.res?` works
extend instead of include works, but extend even works with `extend self` still in Foobar (if this is a feature or a bug depends IMO)

**Comment by bew** [comment]
`Foo.new.res?` works!
I'll let you think about it 😄

ok, I'll tell you, `include Foobar` will only add the methods in `Foobar` to `Foo` (as methods), not the class methods from `Foobar`.

**Comment by monouser7dig** [comment]
yes but that is not the point.

`extend self` makes res? work on the self.  level of the module (kind of like a class method instead of instance method although modules of course do not have instances)
**thus:**
the code in my first post defines res? as a method that can be called without (and only without) and instance

now if we look at include vs extend, include just pulls in methods as they are whereas extend takes method x and imports it as self.x.  #=> extend just makes them "not instance methods"

but since extend self in Fooable already made res? a "non instance method", include in Foo should work and let res? be called als Foo.res? because it is a `not instance method`

contrary 
extend Fooable takes res? and makes it self.res?
but res? is already a "non instance method" in Fooable as can be seen because Fooable.res? works so now if we additionally extend this module into Foo, the method has a state of Foo.self.res? (as far as that makes sense)


**an easy way to put it is:
extend and include ignore if the Module defined the methods as `extend self` or not**

**Comment by monouser7dig** [comment]
'll let you think about it 😄

but, I'll tell you I think it is confusing behavior cause `extend self` is just ignored once the module gets included or extended

**Comment by monouser7dig** [comment]
interestingly if you use `self.method` instead of `extend self` the result differs 

```crystal
module Fooable
  def self.res?
    p "fooable"
  end
end

class Foo
  extend Fooable
end

Foo.res? #=> does not work
Fooable.res? #=> works 
```

whereas if you use `extend self` both works

**Comment by asterite** [comment]
It's because `include` and `extend` don't pull off methods. They change the class hierarchy.

`include` inserts a type in the type hierarchy. `extend` inserts a type in the meta-type hierarchy. The docs are probably overly simplified. If someone wants to update them, please go ahead.

Let's say we have:

```crystal
class Foo
end

class Bar < Foo
end
```

The `<` thing makes a type and its meta-type inherit something. In the example above, the ancestors of the regular type (where instance methods are looked up) Bar are Foo, Reference and Object. The ancestors of the meta-type (where class methods are looked up) of Bar, Bar:Class, are Foo:Class, Reference:Class, Object:Class, Class, Object (I think right now there's also Value somewhere, this is not very well implemented).

When you do `include`, you insert something in the first chain. When you do `extend` you insert something in the second chain. Instance methods are always looked up in the first chain. Class methods are always looked up in the second chain.

So in your example, you have:

```crystal
module Foobar
  extend self
  def res?
  end
end

class Foo
  include Foobar
end
```

So the instance ancestors of Foo are Foo, Foobar, Reference, Object.
The class (meta-type) ancestors of Foo, Foo:Class, are not modified with that include: Reference:Class, Object:Class, etc.

By the way, the snippet you show also gives an error in Ruby, which probably means that we are faithful to Ruby's semantic here. But I'd really like to remove `extend` from the language, it's a bit useless.

**Comment by asterite** [comment]
To be clear: it's not a bug. It works as expected. You get exactly the same behaviour in Ruby. I know it's confusing, but that doesn't mean it's a bug.

**Comment by monouser7dig** [comment]
yes alright, it is confusing but I can already say I will not be able to put in a fix or give the proper algorithm (joking)

**Comment by RX14** [comment]
I don't think this is going to be changed.
