### ISSUE TITLE
[CI] Test shards on master

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5083]
https://github.com/crystal-lang/crystal/issues/5068#issuecomment-334126325 highlights an issue of incompatibility between Crystal `master` and _shards_ `master`.

Among other things it breaks `brew install crystal --HEAD`, which is not nice :(

I propose adding new section in `allow_failures`, run only on `master`, with _shards_ installation and spec. In this way there will be visible status on whether _shards_ needs to be updated without failing whole build.

---

I hope it's understandable since I'm bit of 💤

**Comment by straight-shoota** [comment]
It would be even better to have nightly build of `shards` with nightly builds of `crystal` ;)

**Comment by ysbaddaden** [comment]
Closing. Shards is an independent project, with its own set of dependencies that may break (minitest), and `crystal deps` should be removed. Adding yet another target to Crystal to test out-of-tree dependencies is too much.

Shards is built as part of the Crystal process, therefore fixed & released before.

If we eveventually have a CI infrastructure with nightly builds, it would be nice to build shards (if bundled) with automatic build failure reports, but... later.

**Comment by monouser7dig** [comment]
> Closing. Shards is an independent project, with its own set of dependencies that may break (minitest)

shards is the official dependency manager of crystal (almost part of the std, just different repo)

well shards is **so close to the main language (shipped by default, thus much like std)**

according to rx14 it is also the **recommended way to build** basic crystal stuff

thus a **"we are not related to crystal"** response is confusing

**Comment by straight-shoota** [comment]
@monouser7dig `shards` is an important tool of the Crystal infrastructure but not an integral part of Crystal core (compiler & standard library).

`shards` should be responsible for running `shards` tests, not Crystal core.

**Comment by monouser7dig** [comment]
As long as it is supposed to run well in combination in > 80% of all cases I think it is reasonable to test it and enforce it in combination?

**Comment by straight-shoota** [comment]
No. Errors in `shards` should pop up in `shards` repository, not here.

**Comment by monouser7dig** [comment]
sure but nothing pops on their side cause they do not use CI thus requiring [human-CI](https://github.com/crystal-lang/shards/issues/175)

(technically they have travis.yml but does it do anything?)

**Comment by straight-shoota** [comment]
[yes travis is working](https://travis-ci.org/crystal-lang/shards). The current error did not pop up because the compiler used is the current stable release (0.23.1) and it's only broken on master.

Now, this is obviously not great because `shards` is bundled with Crystal. There are no automatic tests against the release candidate and issues will only be noticed by manual tests, maybe late in the release process and therefore introduce a delay.

This could be improved by running`shards` specs regularly against current Crystal master (needs to be built by travis until there are nightlies available).

**Comment by monouser7dig** [comment]
to be fair `brew install crystal-lang --HEAD` is more of an enthusiast thing rather than pure necessity but it is convenient and **running a CI job is actually low hanging fruit and reduces human need for intervention?**

if all issues are fixed immediately or delayed until a revamp in master (like the YAML one) is done is another question

I'd say shards and crystal master do not always have to be in sync 100% but **after the smoke in master settles, shards should catch up**

**Comment by straight-shoota** [comment]
Sure. Please, you're welcome to bring this to attention in the `shards` repo.

**Comment by monouser7dig** [comment]
though @ysbaddaden was somewhat involved in shards? but if they do not want to fix issues along the road but only for a release maybe that Is it

**Comment by ysbaddaden** [comment]
Locking, please follow up at https://github.com/crystal-lang/shards/issues/177

Thanks.
