### ISSUE TITLE
What The Version?

### ISSUE THREAD

**Issue by ensoxyz** [crystal-lang/crystal#5130]
It might be useful to include the current release version # in the readme!

I'm thinking something like ( crystal-0.23.1 ) should do the trick.

**Comment by petoem** [comment]
I often use a release badge from https://shields.io/ to display the latest release number. 
[![GitHub release](https://img.shields.io/github/release/crystal-lang/crystal.svg)](https://github.com/crystal-lang/crystal)

**Comment by asterite** [comment]
You can check the changelog.

What other language has its last version in the Readme?

**Comment by shevegen** [comment]
I checked!

Ruby, Python, Elixir do not. I have no idea why, perhaps because it is cumbersome to update.

I am also a badge lover! Ruby has a badge already, crystal probably does not so one could get it here perhaps: https://github.com/BraveUX/for-the-badge

To the topic itself, I have no real opinion either way; I am just lurking here from the ruby world. :)

To readmes in general though, in particular README.md ... I've lately considering changing my larger README.md into README.gen, and on a new gem update move, generate a README.me that has actual information and also includes some hooks that can be called (from ruby) upon such autogeneration.

I have no idea if this is feasible or useful to crystal; hardcoded README.md have one thing going for them at the least (simplicity), but I liked being able to autogenerate README with some up to date information - which could fit to what the threadstarter wanted perhaps. But again, I am absolutely neutral either way - I only wanted to give an example, which makes me understand the threadstarter a bit. It's also, oddly enough, true, that many other programming languages do not have the last version in the readme - perhaps someone can find out why and share here.

**Comment by petoem** [comment]
> Ruby, Python, Elixir do not. I have no idea why, perhaps because it is cumbersome to update.

That is why i suggested a shields.io badge, they are automatically generated based on the latest GitHub release.

**Comment by ensoxyz** [comment]
It makes sense but it's probably not worth the effort for the readme. At best you save about 1 click. However this should most def be on the landing page.
