### ISSUE TITLE
Support nil checks in ||

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang/crystal#5186]
## Code:

```crystal
class Foo
  property :bar
  @bar : Int32?
  
  def initialize
    @bar = 0
  end
end

class Baz
  property :quux
  @quux : Foo?
  
  def initialize
    @quux = Foo.new
  end
  
  def test
    puts "This doesn't work!" unless @quux.nil? || @quux.bar.nil?
  end
end

test = Baz.new
test.test
```

## Result:

```
Error in line 24: instantiating 'Baz#test()'

in line 19: undefined method 'bar' for Nil (compile-time type is (Foo | Nil))

Rerun with --error-trace to show a complete error trace.
```

Would it be better if the `@quux.nil?` was evaluated and resulted in the `@quux.bar.nil?` not erroring, since with `||` the result short-circuits?

**Comment by asterite** [comment]
I don't know with what code you are getting that error, the snippet you sent works fine: https://carc.in/#/r/2yqp

**Comment by Qwerp-Derp** [comment]
Hmmm, I tried to reduce down my code but I guess that didn't work... [here](https://github.com/Qwerp-Derp/Mirrors) is my repository, the error is here:

```
Error in src/mirrors.cr:17: instantiating 'Mirrors::Window#show()'

test.show
     ^~~~

in src/mirrors/window.cr:26: undefined method 'listener' for Nil (compile-time type is (Mirrors::Display | Nil))

              @display.listener.listen(mouse_pos) unless @display.nil? || @display.listener.nil?
```

**Comment by straight-shoota** [comment]
You can't rely on `@quux.nil?` to short-circuit the right hand expression of `||` to prevent nil values because there might be a context switch in between which could set the ivar to nil. Therefore you need to assign it to a local variable. Saves an unnecessary lookup, too. See the [docs](https://crystal-lang.org/docs/syntax_and_semantics/if_varis_a.html) (this page is about `#is_a?` but essentially the same goes for `#nil?`).

You can do it with `unless (quux == @quux).nil? || quux.bar.nil?` though it's probably easier readable if you write `if (quux = @quux) && quux.bar`.
