### ISSUE TITLE
Inconsistent behavior of autocasting of signed and unsigned int

### ISSUE THREAD

**Issue by kimyu92** [crystal-lang/crystal#5260]
I found it inconsistent behavior of unsigned and signed operation during overflow case

My questions:
First, why would we even want to allow math operations between unsigned and signed without explicit type casting. Why not the compiler complain without explicit type casting? Imo, I believe this makes it hard to deal with libraries out there later which may exploit such behavior.

Secondly, why would it be different for left and right hand side class? Why picking the left hand side one is always the right choice?
```
(UInt8.new(255) + Int8.new(0)).class == (Int8.new(0) + UInt8.new(255))
# false
```

**Comment by ysbaddaden** [comment]
> why (...) allow math operations between unsigned and signed without explicit type casting

Convenience? So `7_u8 + 10` is working?

> Why picking the left hand side one is always the right choice?

That has nothing to do with right or wrong. This is a rule, which applies to operations between different types, whatever signed, unsigned or different sizes (u8 + i32).

IMHO this is because you add RHS to LHS, not the other way around, so LHS is always significant over RHS. The only exception is when RHS is a float, but LHS isn't, in this case RHS is always significant.

**Comment by asterite** [comment]
This is so you can do:

```crystal
a = 1_u8
a += 2
```

and it works, and `a` preserves its type.

**Comment by asterite** [comment]
Closing as duplicate of #6584 (it came later but there's more discussion there).
