### ISSUE TITLE
Macros won't work when used by proxy

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5267]
```cr
module Foo
  macro foo!
    puts "Foo::foo!"
  end
end

module Bar
  def self.foo
    Foo
  end
end

# WORKS
Foo.foo!

# Error in line 17: undefined method 'foo!' for Foo:Module
Bar.foo.foo!
```

**Comment by bcardiff** [comment]
I doubt it would ever work. The method could take arguments and knowing the returned module might depend on runtime information.

In smaller scenarios where the compile could deduce the receiver module it doesn't work either

```crystal
module Foo
  macro foo!
    puts "Foo::foo!"
  end
end

f = Foo
f.foo! # Compile time Error: undefined method 'foo!' for Foo:Module
```

But the intention for macros inside modules is to be namespaced mainly. What is the what you are trying to accomplish with that proxy?

Note that some kind of proxy can by done if type aliases are used:

```crystal
module Bar
  alias Baz = ::Foo
end

Bar::Baz.foo! # It works
```

**Comment by Sija** [comment]
My use-case is coherence in using such proxy.

```cr
module Crystal
  module Environment
    macro setup(keys)
      # ...
    end

    # ...
  end

  def self.env
    Environment
  end
end

Crystal.env.development? # => true

# I'd like to use below macro call in the same manner
Crystal.env.setup %i(foo bar)
```

**Comment by bew** [comment]
Please don't mix run-time & compile-time stuff, using the return of `Crystal.env` is run-time land, you are able to only use run-time land stuff on it. 

As @bcardiff pointed out, you can simply use a type alias if you don't want to type `Crystal::Environment`:
```cr
module Crystal
  module Environment
    macro setup(keys)
      # ...
    end

    # ...
  end

  alias Env = Environment
end

Crystal::Env.setup %i(foo bar)
```

**Comment by asterite** [comment]
If we go forward with `CRYSTAL_ENV` or similar, there's absolutely no need to use macros. At all.

Look, Elixir has these default environments: https://hexdocs.pm/mix/Mix.html#module-environments

There's no need to make that configurable. In fact, making it configurable is worse, because it means there's less convention.

And there's also no need to create `def development?` from a macro. They are just three methods, you can write it once and it's faster and easier to read than using macros.

As a side note, macros will probably never work the way you want, as @bcardiff explained.

**Comment by jhass** [comment]
#codetriage 

Let's close this, there hasn't been active discussion around this for 18 months, so it doesn't seem to be any major pain, and it's unlikely something like this ever will or should work.
