### ISSUE TITLE
Combining "included" `initialize` methods with new `initialize` method definition on a class fails.

### ISSUE THREAD

**Issue by da99** [crystal-lang/crystal#5285]
I'm able to add `initialize` methods using modules. But, when I combine modules with a `initialize` definition on the same Class, it fails to compile:

```crystal
module A
  def initialize(a : String)
    puts a
  end # === def initialize
end # === module A

module B
  def initialize(a, b)
    puts a, b
  end # === def initialize
end # === module B

class C
  include A
  include B

  def initialize(a, b) # This needs to be removed in order to compile
    puts a, b
  end # === def initialize
end # === class B

C.new("a")
C.new("a", "b")
```
Error: 
```
wrong number of arguments for 'C.new' (given 1, expected 2)
Overloads are:
 - C.new(a, b)
```

**Comment by jhass** [comment]
The last ancestor defining an `initialize` wins and shadows any other, no matter how overloads there were previously: https://carc.in/#/r/7r08

So this is by design for now. I guess at some point we might enforce defining that all overloads defined in parent ancestors are somehow called by the initializes in the concrete class or something like that, similar to Java.
