### ISSUE TITLE
crystal spec throws compile-time error when required if my library is also required

### ISSUE THREAD

**Issue by sam0x17** [crystal-lang/crystal#5312]
Any idea what could be causing this?

No error:
```crystal
require "spec" # no compile-time error
```

Causes compile-time error:
```crystal
require "spec" # throws the below compile-time error
require "../src/my_project"
```
Resulting error:
```
$ crystal spec
Error in line 1: while requiring "./spec/mongo_orm_spec.cr"

in spec/mongo_orm_spec.cr:1: while requiring "spec"

require "spec"
^

in /opt/crystal/src/spec.cr:119: instantiating 'Spec:Module#run()'

Spec.run
     ^~~

in /opt/crystal/src/spec/dsl.cr:172: instantiating 'Spec::RootContext:Class#print_results(Time::Span)'

      Spec::RootContext.print_results(elapsed_time)
                        ^~~~~~~~~~~~~

in /opt/crystal/src/spec/context.cr:46: instantiating 'Spec::RootContext#print_results(Time::Span)'

      @@instance.print_results(elapsed_time)
                 ^~~~~~~~~~~~~

in /opt/crystal/src/spec/context.cr:72: instantiating 'Array(Spec::Result)#each_with_index()'

        failures_and_errors.each_with_index do |fail, i|
                            ^~~~~~~~~~~~~~~

in /opt/crystal/src/enumerable.cr:377: instantiating 'each()'

    each do |elem|
    ^~~~

in /opt/crystal/src/indexable.cr:148: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /opt/crystal/src/indexable.cr:148: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /opt/crystal/src/enumerable.cr:377: instantiating 'each()'

    each do |elem|
    ^~~~

in /opt/crystal/src/spec/context.cr:72: instantiating 'Array(Spec::Result)#each_with_index()'

        failures_and_errors.each_with_index do |fail, i|
                            ^~~~~~~~~~~~~~~

in /opt/crystal/src/spec/context.cr:85: undefined method 'split' for Nil (compile-time type is (String | Nil))

            ex.to_s.split("\n").each do |line|
                    ^~~~~

Rerun with --error-trace to show a complete error trace.
```

**Comment by bew** [comment]
Can you give us a full reproducible example? (with source code and commands if necessary)
I tried creating a new project, which contains by default a `spec_helper.cr` file containing what you described, an it works well.

Also, what Crystal version did you tried?

**Comment by sam0x17** [comment]
I figured out what is doing it. 

If this class inherits from `Exception`, the compile time error happens:
```crystal
class Mongo::ORM::Error < Exception
  property field, message

  def initialize(@field : Symbol, @message : String)
  end

  def to_s
    if @field == :base
      @message
    else
      "#{@field.to_s.capitalize} #{message}"
    end
  end
end
```

If I take out the `< Exception` bit, there are no errors and everything is fine. I'm probably not implementing something required by `Exception` would be my guess.

**Comment by straight-shoota** [comment]
Reduced example:

```crystal
class FooError < Exception  
  @message = "foo"

  def to_s
    @message
  end
end

FooError.new.to_s.split("\n")

# => Error in line 9: undefined method 'split' for Nil (compile-time type is (String | Nil))
```

This is caused up by messed up types with inheritance of the instance variable. In `Exception`, it's type is `String?`, in the descendant class it should be expected to be `String`. But it inherits the (wider) type of the parent class and can't be redeclared.  AFAIK this is because that would break memory compatibility with parent class.

A naive workaround would be to let `to_s` return `@message.not_nil!`, as you're certain that the instance variable of *this* class will never be nil. This would fix the immediate problem, but there are still other issues:
First, you shouldn't implement `to_s` directly but rather `to_s(io : IO)`. That would make this line `io << @message` which would prevent the nil issue.
Second, `@message` is already defined in `Exception` class for a specific error message and the instance variable is used accordingly. So you shouldn't ever try to redeclare it in a descendent class. Either you want the same behaviour like in the parent, then you should use the parent's methods for this (for example delegate the message argument to the parent's constructor). Or you wan't a different behaviour and should use a different instance variable instead of hijacking one from a parent.

**Comment by RX14** [comment]
This isn't typically how we extend exceptions.

```cr
class Mongo::ORM::Error < Exception
  property field : Symbol
  property raw_message : String

  def initialize(@field, @raw_message)
    if @field == :base
      super(@raw_message)
    else
      super("#{@field.to_s.capitalize} #{@raw_message}")
    end
  end
end

**Comment by RX14** [comment]
https://github.com/crystal-lang/crystal/issues/3546 would help to avoid such mistakes by ensuring type contracts on overridden methods. Other than that, not much to do.

**Comment by sam0x17** [comment]
cool -- just wanted to make sure you guys were aware
