### ISSUE TITLE
`Read before assignment to local variable` using blocks

### ISSUE THREAD

**Issue by jfcalvo** [crystal-lang/crystal#5315]
I'm trying to do something like the following:

```crystal
def load(&block)
  block.call
end

def show(&block)
  block.call
end

number : Int32

load do
  number = 42
end

show do
  puts number
end
```

I receive the following:

```sh
test.cr:16: read before assignment to local variable 'number'
```
I'm not really sure but should the compiler know that before trying to access the variable `number` I'm defining it's value in a previous executed block so the `read before assignment..` error should not be raised?

Is that something that could be implemented or I'm saying something imposible for the compiler to know?

I'm trying to create a DSL similar to the previous one and I don't really know how to solve this problem.

Thanks.

**Comment by straight-shoota** [comment]
The compiler can't know if (and when) the block passed to `load` gets executed. That's why it has to assume that `number` might not be assigned. There is no way to know this at compilation time (that's when the possible types are resolved) because the execution of blocks can depend on runtime decisions.

To get this resolved, you can do one of the following:
* initialize `number` with a default value (might or might not be a good idea, depending on the usecase)
* mark `number` as uninitialized: `number = uninitialized Int32` if your code can *really* assure that it will be assigned a value before it is read (this is unsafe code, handle with care)
* Use a macro instead of a method:
```crystal
macro load
  {{ yield }}
end
# ...
```
* Think about a different design

**Comment by jfcalvo** [comment]
I think that defining `load` as macro will do the trick by now. Thank you @straight-shoota
