### ISSUE TITLE
Accessor macros don't work with names ending in "?"

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5344]
This works:
```cr
class Foo
  getter? bar = false
end
```

This doesn't:
```cr
class Foo
  getter bar? = false
end
```

IMO both forms should result in the same definitions.

**Comment by RX14** [comment]
No they shouldn't, because you cannot define a `bar?=` method.

**Comment by Sija** [comment]
Well, it would be nice if you'd wait with closing issues a bit more, since it's your opinion only and I'd like to point out that `JSON.mapping` uses these macros which makes defining question methods impossible.

**Comment by RX14** [comment]
Yeah my bad, I shouldn't have closed it.

**Comment by Sija** [comment]
Below IMO **should** work without any fiddling around (like defining another alias methods for "not working" properties):

```cr
require "json"

class Foo
  JSON.mapping({
    bar?: Bool
  })
end
```

**Comment by bew** [comment]
if you want json `method?` it may be related to #4129.

About `getter bar?` I don't think that's a good idea, and the root cause is that ivars cannot have punctuations like `@bar? = true`. IMO `getter` should stay simple, without edge cases like this, but JSON mapping can have an upgrade like https://github.com/crystal-lang/crystal/issues/4129#issuecomment-285875957.

**Comment by Sija** [comment]
@bew I missed that one, thanks! consider this as duplicate, closing.
