### ISSUE TITLE
Wishlist: Bring back Time#ticks or equivalent

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#5374]
It would be good to bring back Time#ticks that existed in 0.23.

It doesn't need to be exactly #ticks, it can be any equivalent which reduces Time or Span to a single number that can then be used for comparisons and in initializers.

to_time.ticks <=> other.to_time.ticks

Time.new( Time.now.ticks +- Int)

Time::Span.new( ticks)

etc.

**Comment by ysbaddaden** [comment]
Well: `to_time <=> other.to_time`, `Time.now - 1.second`. You don't need ticks.

If you really insist, there is `.epoch` and `.epoch_ms` as well as `to_f`.

**Comment by docelic** [comment]
In 0.24.0 the Time class has nanosecond precision, so it is not acceptable to use #epoch or #epoch_ms. (There is also epoch_f, but that loses precision.)

And one needs both seconds and nanoseconds value to re-create an identical (or at least equally precise) Time object.

**Comment by ysbaddaden** [comment]
Sorry, `ticks` was a private implementation detail, and we won't bring it back, since we don't use it anymore.

I believe Time has solutions for the exposed use cases, such as comparing Time instances themselves (which compares seconds and nanoseconds precisely), or casting to desired precisions. These solutions should be more future prone, for example to the addition of locations and offsets.

**Comment by straight-shoota** [comment]
> It doesn't need to be exactly #ticks, it can be any equivalent which reduces Time or Span to a single number that can then be used for comparisons and in initializers.

It is currently not even possible to express the full range of a time instance with nanosecond precision in a single primitive number because that would require more than 64 bits. Hence ´Time`uses `Int64` for `seconds` and `Int32` for `nanoseconds`.

However, it is possible to use `epoch` and `nanoseconds` together to read two numbers representing that time instance. However, it is not straightforward to recreate a `Time` instance from that, because `Time.epoch` does not have a nanosecond argument and for `Time.new` you'd have to manually add `UNIX_SECONDS`.
It might be worth thinking about exposing `total_seconds` publicly which allows to read the `seconds` ivar directly. It is not so much an implementation detail as `ticks` and will always be needed for `epoch` which is basically just an alias wich subtracts `UNIX_SECONDS`.

**Comment by straight-shoota** [comment]
To clarify: I'm with @ysbaddaden in arguing that you shouldn't *need* to convert a `Time` instance to primitive and back.
