### ISSUE TITLE
Roadmap Concurrency Item Accuracy - better link and more activity?

### ISSUE THREAD

**Issue by ylluminate** [crystal-lang/crystal#5381]
Regarding the [Concurrency item on the Roadmap](https://github.com/crystal-lang/crystal/wiki/Roadmap#toc1), it seems to link to perhaps [a stale branch](https://github.com/crystal-lang/crystal/tree/thread-support)... 

Would it be better to link it to an Issue so that more discussion, planning and action can be organized?

Would [this issue ([RFC] Fiber preemption, blocking calls and other concurrency issues #1454)](https://github.com/crystal-lang/crystal/issues/1454) be the primary point for discussion?  Or is there someplace better?

Since concurrency is right up there with Windows (and dare I say, WASM) support, I think it could be important to have a better call to action for would-be participants.

**Comment by ylluminarious** [comment]
I agree, parallelism is pretty important to have and I'm sure everyone's aware of that. It would be consolidate discussion and efforts on it to direct those who are interested in working on it.

**Comment by bararchy** [comment]
Not to spoil the party, but for 1y~ there wasn't even one user who said "hey guys you got multithreading? Ho.. No? I'll add it for you" , this is because this change is big, elaborate, and needs to be done by an expert in Crystal and someone who fully grasp the compiler , hoping someone will come along and add this , is just fools hope.

The only ones who can actually work on that are the core devs, and none has time for it right now, they all know where to find the relevant discussion .

**Comment by ylluminarious** [comment]
@bararchy 

> The only ones who can actually work on that are the core devs

Is that a fact? A more consolidated and accessible hub for this issue would foster more people working on it. Anyone could come along and study the compiler to figure out how to add parallelism.

> [...] this change is big, elaborate, and needs to be done by an expert in Crystal and someone who fully grasp the compiler , hoping someone will come along and add this , is just fools hope.

I guess all I can say to that is:

> When there's a will to fail, obstacles can be found.

\- John McCarthy

**Comment by jhass** [comment]
I think we don't need to keep this issue open :)
