### ISSUE TITLE
Roadmap should have WebAssembly (WASM) - could significantly enhance language adoption

### ISSUE THREAD

**Issue by ylluminate** [crystal-lang/crystal#5392]
Apparently my adding WebAssembly (WASM) support to the Roadmap a few days ago was frowned upon since @larubujo removed my addition and stopped editing (maybe - seems I can still edit the doc; or perhaps he was issuing an imperative at me to not ever attempt to edit the document again? 🤷🏼‍♂️) of the Roadmap doc.

Please see [my attempted original addition](https://github.com/crystal-lang/crystal/wiki/Roadmap/88f64e1e85225eb7d2283e2b0fc682f40e92c543) and advise as to why such an entry should not be found on the Roadmap since it's frankly higher priority to the community than a good number of the other items.  I've talked to a number of folks and it's most certainly desirable and could be arguably a higher priority than perhaps one or two of the highest as far as marketing reach, language adoption and  positive perception go.

Copy of my original addition for convenience:
## WebAssembly (WASM) support
Implement support for running Crystal on the web via WebAssembly (WASM). Some discussion has been started [here](https://github.com/WebAssembly/binaryen/issues/1312) in order to start feeling through what will be needed for this. This will be particularly useful for web frameworks such as [Amber](https://github.com/amberframework/amber), [Lucky](https://github.com/luckyframework/lucky) and others who could present an isomorphic platform built entirely around Crystal or those simply wanting to build games or other things for the browser in pure Crystal like [Opal](https://github.com/opal/opal) does for Ruby.

**Comment by faustinoaq** [comment]
I agree, compiling Crystal to Web Assembly could be a very nice feature, some issues like some dependencies and standard library,though

BTW LLVM already compile to WASM and we have a PR about it 👉 #3634

I know Windows support and parallelism are very important but currently these are common features. Almost every programming languages have Windows support, and at least popular languages like Julia, Rust and Go support parallelism. So, I think Crystal is a bit late on implementing some features, but maybe we can bring Web Assembly and sell it like a fresh feature for our exiting new language. 😉

There are many use cases like @ylluminate said, creating `.wasm` binaries using crystal will bring us a new world of possibilities 😄

**Comment by RX14** [comment]
We already have an issue for wasm support... This should either be in the mailing list or in there.

**Comment by ylluminate** [comment]
@RX14 - Sorry, this is more about adding it to the Roadmap document since I'm not allowed.

**Comment by jhass** [comment]
Let me quote the roadmap document:

> This roadmap defines the things that **we** want to have in the language **and plan to do**.

Are you confident in being able to contribute WASM support and if so could you give a rough ETA on when we can see your pull request?

**Comment by larubujo** [comment]
i closed because the way i see it, roadmap is defined by crystal core team, mostly manas. they decide what they want for 1.0, not community. community can contribute and say "i want these". but roadmap is what core team know they want to have, not what everyone want to have. otherwise the roadmap is just a wishlist (theres a repo, cant remember name).

imagine matz has a roadmap for ruby 3.0. you come and add items. matz will implement this? don't think so. fake roadmap then. community thinks this will happen, but will not.

also issue about concurrency or gc. only core team understands this, i guess. very hard to implement, i guess. is super hard for go, and they have lots of money and people. even if you send pr, probably hard to understand and not be accepted. or not the way they planned.

at least this is my opinion. might be wrong.

also why want wasm? crystal not even popular or finished for original purpose, why add more scope and reduce effort in main goal? step by step, first things first.

**Comment by ylluminarious** [comment]
@jhass Actually I believe that @ylluminate is working on adding wasm support, which can be seen [here.](https://github.com/WebAssembly/binaryen/issues/1312) AFAIK, he is planning on getting `bdwgc` to work on wasm. Even one of the members of the wasm project [is willing to help accomplish this.](https://github.com/WebAssembly/binaryen/issues/1312#issuecomment-348409211)

---

@larubujo I think that @ylluminate added the item to the roadmap because he did not believe that there would be this sort of resistance to such an item. Sure, I guess he could have added it to some sort of community wishlist but a roadmap offers better visibility and thus potentially more people working on the item. That way, manas doesn't have to worry about it since other people will do the work for him.

> also why want wasm?

Because it offers a huge marketing advantage for Crystal. It is on the way to being supported by all major browsers and given the JS buzz floating around in the IT world, Crystal would certainly be wise to consider the marketing potential of wasm. Crystal on wasm would offer people a great alternative to C/++, Rust, etc.

> crystal not even popular or finished for original purpose

Again, Crystal's popularity would be greatly augmented by getting on the wasm bandwagon. Also consider [Linus's law](https://en.wikipedia.org/wiki/Linus%27s_Law) in this context. Breaking into the wasm market means a lot more visibility for Crystal and thus many more potential contributors. These contributors would probably help with all kinds of Crystal's current issues.

**Comment by ylluminate** [comment]
Also, yes, Crystal is much more popular than you may realize. Have you seen the TIOBE levels?  Whether you believe 'em or not, it's impressive and gives one pause.  Granted it's gone back down this month, but it's going to (no doubt about it) break into the top 20 this next year (maybe I'm wrong, but "a fast Ruby" (pardon this analogy, but it's the main uptake driver for Crystal) is extremely desirable right now).  With the web frameworks steaming ahead, they all could use and want WASM Crystal (ask them if you want, but I'm hearing it from them and from my own perspective from our work in Opal and on Opal wrappers, we need it).

So yes, [we're going to get this done](https://github.com/WebAssembly/binaryen/issues/1312#issuecomment-352569877), even if we can't give you an actual ETA.  I would guess we'll get WASM support implemented WAY before native Concurrency and native Windows are in place.

**Comment by straight-shoota** [comment]
TIOBE index is just crab as the ranking of Crystal shows. They just count expected search results for `crystal programing`. Crystal might get some increased visibility because of that, but it is definitely not organic.

**Comment by ylluminate** [comment]
That is a highly arguable point in both directions. I tend to lend more credence to it after following it for so many years @straight-shoota.  It's definitely a good sign for Crystal either way you read it.

**Comment by straight-shoota** [comment]
It's nice for Crystal to get some visibility. Even if it's mostly from programmers who blindly trust a shiny naive ranking index.
There is nothing to argue. TIOBE describes the [method they use to calculate the ranking in detail](https://www.tiobe.com/tiobe-index/programming-languages-definition/).

Now take a look at the result pages for `+"crystal programming"` at a few of the listed search engines, start at page 10 or somthing. Most of these later results have nothing to do with the language.

**Comment by ylluminate** [comment]
Right and I like their methodology. Again, whether your like it or not is up to subjective argumentation as I tend to think there is a high degree of objectivity in what they do compared to the other options that I feel fall way short in their own paradigms.  Sure, it can be refined, but... At any rate, not a big deal, we can agree to disagree and that's a good thing. 😺

**Comment by vladfaust** [comment]
LLVM 6 supports WebAssembly as a linking target ([link](https://www.infoworld.com/article/3262128/development-tools/whats-new-in-llvm.html))
