### ISSUE TITLE
Travis builds with older Crystal versions

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#5449]
Suddenly my builds began to fail on Travis. Why? Because it got suddenly updated to 0.24 version.

According to [Crystal page on Travis](https://docs.travis-ci.com/user/languages/crystal/) only `latest` and `nightly` versions are supported, so I'm unable to test my previous changes on Travis unless I update to the latest Crystal version.

I suggest to allow defining custom Crystal versions in `travis.yml` like this:

```yml
crystal:
  - "0.23.1"
```

**Comment by oprypin** [comment]
Crystal is unstable. Old Crystal versions become obsolete the moment that another one appears. I think that supporting them is just unnecessary work at this stage.

**Comment by veelenga** [comment]
I faced the same issue today and actually tried exactly the same approach to fix travis build and failed. The idea is not to support old crystal version but give the opportunity to support shards' code before the upgrade. Because for now work on the shard is blocked unless you upgrade your codebase to the latest release. And sometimes it is not that easy to upgrade...

**Comment by ysbaddaden** [comment]
Crystal doesn't aim for stable development until 1.0 is around the corner. You must either support the latest release proactively (basic, default), or install a specific crystal manually in your CI builds.

I'm closing since this is distribution issue (here the Travis helpers), not a language/library issue.

**Comment by RX14** [comment]
I disagree that we should be be able to anchor the crystal version. However, it's difficult to implement and an issue for travis-ci not crystal.
