### ISSUE TITLE
[RFC] Add docs support for class variables

### ISSUE THREAD

**Issue by GloverDonovan** [crystal-lang/crystal#5634]
Sometimes you want to document class variables. You could document all the variables in the module description, but this isn't ideal if you want to document a lot of variables.

What works now:

```crystal
# Description of module
#
# Description of class variable 1
#
# Description of class variable 2
#
# ...
module Hello
  @@class_var = ...
  @@another_var = ...
end
```

Proposal:

```crystal
# Description of module
module Hello
  # Description of class variable 1
  @@class_var = ...

  # Description of class variable 2
  @@another_var = ...

  # ...
end
```

**Comment by straight-shoota** [comment]
You can already document class variables like this, but it will obviously not be in the generated API docs because class variables are generally not part of the public API.
You'll need to define class getter and setter methods if there should be an access to the class variables from outside that class itself. Those methods can then be documented.

Otherwise, you don't need the class vars included in the documentation if they're only an implementation detail.

**Comment by GloverDonovan** [comment]
Makes sense, but this makes me feel like I'm using class variables in the wrong way.

An unrelated question: I'm [using](https://github.com/GloverDonovan/mica/blob/master/src/mica/modules/config.cr) a hash to store runtime settings (verbose output, file locations, etc.). The user can change these defaults with `--options` or a `config` file.

It's just tedious to document these variables since I may change them in one spot and forget to change them in the other. I would use a constant since they're included in the docs, but constants are constants and cannot be changed at runtime. Is there a better way to do this?

**Comment by asterite** [comment]
Those (`--options` and a `config` file) seem like the docs for the **user** of your app, not for the **programmer** of your code... This has nothing to do with documenting class variables or constants.

**Comment by ysbaddaden** [comment]
Instance and class variables are private. Document them in code for other programmers (or future self) but if they're meant to be public, add public accessors and document them, so that will appear in the generated documentation.

For runtime provided arguments, use a command tool that allows you to parse & document each argument; OptionParser or something more complex that could generate man pages for example.

Let's close?

**Comment by GloverDonovan** [comment]
Thanks for the reply. And yes, I believe this can be closed now.
