### ISSUE TITLE
Multiple output values in asm

### ISSUE THREAD

**Issue by S-YOU** [crystal-lang/crystal#5660]
rdtsc instruction output eax, and edx, but seems like current asm.cr only support one output value.
Is there any way to fix that or workaround to output multiple values in asm?

**Comment by asterite** [comment]
It seems LLVM and Rust now support multiple operands, so this is a valid feature request.

This affects:
- The parser (it will need to parse more than one output operand)
- The semantic phase (in `MainVisitor`)
- The codegen
- The formatter
- `Asm#to_s` in `ToSVisitor`

I don't think it's hard to implement, one just has to see how that part is currently done and allow for multiple outputs instead of just one.

If someone wants to tackle this, let us know and I can assign them.
