### ISSUE TITLE
Regression in Spec::BeAExpectation(T)

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5729]
Merging #5646 caused a regression:

```crystal
require "spec"

describe "Spec::BeAExpectation(T)" do
  it { Int32.should be_a Int32.class }
end
```

v0.24.1 ([carc.in](https://carc.in/#/r/3lu6)):
```
.

Finished in 83 microseconds
1 examples, 0 failures, 0 errors, 0 pending
```

`master`:
```
Error in line 1: instantiating 'be_a(Class)'

in /.../crystal/src/spec/expectations.cr:271: can't use Object as generic type argument yet, use a more specific type

      Spec::BeAExpectation(T).new
```

**Comment by luislavena** [comment]
I always assumed `be_a` refers to _instances of_ instead of _kind of_ classes.

If not mistaken, RSpec does the same distinction between `be_kind_of` and `be_instance_of`:

* https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/type-matchers
* http://www.rubydoc.info/gems/rspec-expectations/RSpec/Matchers/BuiltIn/BeAKindOf
* http://www.rubydoc.info/gems/rspec-expectations/RSpec/Matchers/BuiltIn/BeAnInstanceOf

Perhaps the same approach needs to be made here in order to properly differentiate kind from instances.

Cheers.

**Comment by Sija** [comment]
IIRC that's what `be` should do, `be_a` is/was meant to check for given type, see previous definition:

https://github.com/crystal-lang/crystal/blob/844cc6e608fe74237d3deda6092a0becd3854033/src/spec/expectations.cr#L270-L272

Now, it reads:

https://github.com/crystal-lang/crystal/blob/ed0aad89ed476b58fc444e975881b2356b37541e/src/spec/expectations.cr#L270-L272

`type` argument is still there, yet in actual version it seems to work differently.

**Comment by luislavena** [comment]
@asterite any comment on this?

**Comment by Sija** [comment]
@asterite ping!

**Comment by asterite** [comment]
My commit should be reverted

**Comment by RX14** [comment]
(just the `be_a` bit)
