### ISSUE TITLE
Use a global tmpdir for specs

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#5811]
#5810 adds a few ensure after specs that creates tempfiles but don't delete them.

To remove all of this we could also create a temp directory in `spec_helper.cr` using:
```cr
dirname = Tempfile.tempname "compiler_spec"
Dir.mkdir dirname
ENV["TMPDIR"] = dirname
```
So all subsequent Tempfile calls will create a file in our `dirname`, and we could just delete it after all specs passes (or not?).

Maybe if the specs doesn't passes we can leave the directory and tell the user that it's there if he wants to checkout some leftover file?

WDYT?

**Comment by straight-shoota** [comment]
I'm against leaving tempfiles in place to avoid compromising subsequent spec runs. If you need to investigate a failing spec, you should adjust the spec to temporarily include diagnostics or not delete the file.

About the centralized temp directory I'm not so sure... by itself it sounds like a nice idea, but I wouldn't want individual specs to rely on some global cleanup magic instead of doing their own housekeeping.

As an alternative, I'd suggest a spec helper `with_tempfile` which yields a block receiving a temp path and ensures that path is cleaned up at the end. So it would actually be like `Tempfile.open` for `Tempfile.tempname`. The path could actually be in a central spec directory according to your proposal. But every spec needs to do it's cleanup itself.

```crystal
def with_tempfile(extension = nil)
  # naive implementation
  path = Tempfile.tempname(extension)
  begin
    yield path
  ensure
    File.delete(path)
  end
end
```

This might even be implemented as `Tempfile.tempname` receiving a block... it could surely prove useful outside of specs if you want to ensure a temporary file is cleaned up, but need to handle file creation yourself.

**Comment by RX14** [comment]
The current problem is that it's almost impossible to cross-compile the specs because there's no centralised temporary directory (lots of tests just dump their tempfiles in the repo and then "clean up"), AND all sorts of tests use `__FILE__` and `__DIR__`. These two constants break cross-compilation.

**Comment by straight-shoota** [comment]
Data file helper sounds good, but why don't `__FILE__` and `__DIR__` cross-compile?

**Comment by RX14** [comment]
@straight-shoota they do, they just point to paths on the host not the target so are useless.

**Comment by straight-shoota** [comment]
So the goal should be to get rid of most `__FILE__` and `__DIR__` usages in specs and replace them with tempfile and datafile helpers. These are actually two different issues but it makes sense to do the replacements in one go. It could still be separated commits/PRs with selective committing (`git add -p`). We should probably have separate PRs to implement the helpers first.

Temporary files should generally just go where `TMPFILE` says (default `/tmp`). All temporary files should be put in that path, but could be scoped to a sub directory `$TMPFILE/crystal`.

In specs, you typically don't really need temporary files using `Tempfile` (which adds name randomization) because most file names are unique and not reused. Random characters in the file names make them harder to read and compare. A spec helper should avoid unnecessary randomization and probably just use the plain names (scoped to a sub directory `$TMPFILE/crystal`).

* It probably still makes sense to add `Tempfile.tempfile(&block)` as a general purpose utility to create and automatically delete a Tempfile after the block scope exits. But that's a separate issue.
* A spec helper `with_tempfile` (or perhaps a different name to avoid confusion with `Tempfile`?). This could either go in a spec helper or even in `src/spec/dsl.cr` to make it generally usable in specs. 
* A `datafile` helper would just receive a path name relative to the file it is called from and turn it into a path relative to the data folder in the project's root directory.

**Comment by RX14** [comment]
@straight-shoota tempfiles should be in a directory with a random name, so you can run multiple specsuites at once without clashing names.

**Comment by straight-shoota** [comment]
True. So `with_tempfile` should scope to `$TMPDIR/crystal-XXXX`.

**Comment by RX14** [comment]
@straight-shoota `$TMPDIR/crystal-spec-#{Random.hex(8)}/#{filename}`.

**Comment by RX14** [comment]
@straight-shoota the benefit would be that the spec suite would be `$PWD` agnostic, which helps a lot for cross-compiling the spec suite. Since the data path will vary between the compile host and the compile target.

**Comment by RX14** [comment]
@straight-shoota Hmm, actually yeah I should just change my auto cross-compile script to run from a checkout of the crystal repo. So relative paths should actually be fine.

**Comment by RX14** [comment]
@straight-shoota :+1:
