### ISSUE TITLE
Publish nightly API docs for master

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5934]
With the new CI setup, we're getting nightly builds including API docs. But https://crystal-lang.org/api/master/ still lags behind and has not been updated since the release of 0.24.2 a month ago. I'm not sure if that's a bug or simply not implemented yet, but it would be great to have access to the latest API docs.

**Comment by bcardiff** [comment]
It’s intended actually. From the build in master in circleci you can grab the docs artifacts there. Every released version will be online, but branches and nightly are downloadable from circleci artifacts.

**Comment by straight-shoota** [comment]
I'm not sure what you meab... What's the purpose of https://crystal-lang.org/api/master/ if it doesn't follow master?

**Comment by bcardiff** [comment]
The nightly builds currently have artifacts where the docs are available to download and view locally.
For example: https://circleci.com/gh/crystal-lang/crystal/4839#artifacts/containers/0 

They are not built in every commit as before. But know you can compare docs of any dates.

The  https://crystal-lang.org/api/master/ will go away eventually on a cleanup of the S3 bucket that store them.

If docs for every commit in master is desired we could grab those in artifacts on builds on master when the build of linux 64 bits finish. What would be even better is that if commit message has a "[doc]" for example a build over a PR could generate those artifacts also in order to be able to review them before merge.

So, nightly docs are enough or do you really need per commit docs artifacts in master?

**Comment by straight-shoota** [comment]
Docs for every commit are not necessary, a nightly build totally suffices.

But they should not just be available as a pretty difficult to discover download link, but actually directly accessible to browse at https://crystal-lang.org/api/master/.

That would greatly help to see and improve the current state of the API docs. And a lot of people are working with more recent compilers/stdlib than the latest release, having current API docs publicly available would benefit for those usages as well.

I mean it shouldn't be too difficult, right? You just need to push the docs generated in the nightly build to S3, either directly from circleci or through an external webhook or something.

**Comment by Sija** [comment]
>The https://crystal-lang.org/api/master/ will go away eventually on a cleanup of the S3 bucket that store them.

That would be a serious mistake, I've been using it many times in the past and I bet many other people did too. It's especially important when new versions are released months between each other.

**Comment by RX14** [comment]
That's unacceptable, changing a single "visit this URL" to "download this tarball and extract". We must keep around and maintain a `/master/`, or at least `/nightly/` docs URL.
