### ISSUE TITLE
"UT8" encoding error

### ISSUE THREAD

**Issue by Proximyst** [crystal-lang/crystal#5961]
As I was improving my spec code to actually use `spec` in the stdlib, I came across quite a weird bug, which happened in all of my specs on the same lines. This is one of the specs:

```crystal
require "./helper"

module OwO
  describe WhatsThis do # error: Invalid encoding: ut8
    it "Upload test image (image.png in root of the repo)" do
      image_id = inst.upload UploadData.new File.new "image.png"
      image_id.nil?.should eq false
      next if !check_file_data
      response = HTTP::Client.get "https://owo.whats-th.is/#{image_id}"
      response.status_code.should eq 200
      response.body.should eq File.read "image.png"
    end
  end
end
```
I got suspicious, and tried this instead:
```crystal
module OwO
  class Test
  end
  describe Test do
    it "lol" do
      true.should eq true
    end
  end
end
```
This worked splendidly, but nowhere in my code is `ut8` ever mentioned, nor is it in Cossack (at least using `grep` recursively with `ut8`, `Ut8`, `uT8` and `UT8`) which I use for my library. The full stack trace is as follows:
```
  1) OwO::WhatsThis Upload test image (image.png in root of the repo)

       Invalid encoding: ut8
       /usr/lib/crystal/iconv.cr:27:35 in 'initialize'
       /usr/lib/crystal/iconv.cr:7:3 in 'new'
       /usr/lib/crystal/io/encoding.cr:59:16 in 'initialize'
       /usr/lib/crystal/io/encoding.cr:58:5 in 'new'
       /usr/lib/crystal/io.cr:502:7 in 'decoder'
       /usr/lib/crystal/io.cr:551:10 in 'gets_to_end'
       /usr/lib/crystal/http/client/response.cr:73:15 in 'consume_body_io'
       /usr/lib/crystal/http/client/response.cr:97:9 in 'from_io?'
       /usr/lib/crystal/http/client.cr:502:5 in 'exec_internal_single'
       /usr/lib/crystal/http/client.cr:486:5 in 'exec_internal'
       /usr/lib/crystal/http/client.cr:482:5 in 'exec'
       /usr/lib/crystal/http/client.cr:585:5 in 'exec'
       /usr/lib/crystal/http/client.cr:612:7 in 'exec'
       /usr/lib/crystal/http/client.cr:329:3 in 'get'
       /usr/lib/crystal/spec/methods.cr:16:5 in '~procProc(Nil)'
       /usr/lib/crystal/spec/methods.cr:255:3 in 'it'
       /usr/lib/crystal/spec/methods.cr:16:5 in '~procProc(Nil)'
       /usr/lib/crystal/spec/context.cr:255:3 in 'describe'
       /usr/lib/crystal/spec/methods.cr:16:5 in 'describe'
       spec/image_spec.cr:4:3 in '__crystal_main'
       /usr/lib/crystal/crystal/main.cr:11:3 in '_crystal_main'
       /usr/lib/crystal/crystal/main.cr:112:5 in 'main_user_code'
       /usr/lib/crystal/crystal/main.cr:101:7 in 'main'
       /usr/lib/crystal/crystal/main.cr:135:3 in 'main'
       __libc_start_main
       _start
       ???
```
I quite simply am unable to find out what this comes of, and I suspect it's in the Crystal source somewhere..

**Comment by straight-shoota** [comment]
This issue has nothing to do with running as spec. You could easily reduce this to a minimal example which would be `HTTP::Client.get "https://owo.whats-th.is/#{image_id}"` (where `image_id` is a valid ID). As I can't access your service and I don't know what it does, I can only assume.

`HTTP::Client.get` consumes the body of the HTTP request and reads it into a `String` as `response.body`. I suspect that the body is actually binary data or at least not UTF-8 encoded. That's why iconv errors out when it finds a byte sequence that is not a valid UTF-8 codepoint.

If this is a bug I don't know. Can't tell without knowing the actual HTTP response.

But you should probably use `HTTP::Client.get` with a block, which yields the response and shouldn't consume the body. But you can use `response.body_io` to access it as an IO.

**Comment by asterite** [comment]
Closing, @straight-shoota gave the answer.
