### ISSUE TITLE
Can't format `NamedTuple(foo: Int32 bar: Bool)`

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#5979]
The formatter can't format the following code: (@MakeNowJust :smiley:)
```cr
p NamedTuple(foo: Int32 bar: Bool).types
```
(there is no comma and it compiles! https://carc.in/#/r/3wvz)

---
NOTE: This syntax only works for the generic type, not in actual named tuples.
I think the syntax can be confusing, I'd suggest to remove it (by making the comma mandatory).

**Comment by MakeNowJust** [comment]
I think it should not be compiled and this is a simple parser bug.
-- 土曜日, 21 4月 2018, 00:29午後 +09:00 from Benoit de Chezelles  notifications@github.com :

**Comment by bew** [comment]
I don't think that's a parser bug, just a feature that's never used and that looks weird to me with the rest of the language.

**Comment by girng** [comment]
Just to add, this bug actually goes a bit deeper. Because when you compile you will not see any error, but when you are using Sublime for Crystal (or a console that runs `crystal tool format` *on save*), the formatter will echo out an `Error: expecting ,, not IDENT`,  and ask the user to run a stack-trace. This will cause a small delay when saving files on WSL. Once the `,`   was added,  the delay went away, and the console flash is now instant.

**Comment by MakeNowJust** [comment]
"parser bug" means and I guess the author of NamedTuple parser does not intend to accept such a syntax. Is there a spec for this?
--
土曜日, 21 4月 2018, 00:40午後 +09:00 from Benoit de Chezelles  notifications@github.com :

**Comment by bew** [comment]
Good point, I can't find a spec for that
