### ISSUE TITLE
Instance vars + finished: chicken and egg problem

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#6028]
Imagine I'd like to implement an `AutoConstructor` module that defines an `initialize` method from all the instance variables. One solution could be this:

```crystal
class Object
  module AutoConstructor
    macro included
      macro finished
        def initialize(*,
          \{% for ivar in @type.instance_vars %}
            @\{{ivar}} = \{{ivar.default_value}},
          \{% end %}
          )
        end
      end
    end
  end
end

class Foo
  property x = 1
  property y = "foo"

  include AutoConstructor
end

Foo.new(x: 10, y: "hello")
```

The code is a bit convulted because it involves an `included` macro and a `finished` macro, which needs to be escaped to avoid it being expanded as the result of the inclusion (and not because of `finished`).

But, aside from those indirections (which are sometimes needed)... it doesn't work.

The problem is that `finished` runs directly after the first compiler pass, and at that point the type of instance variables (or even which instance variables) are computed.

This is both bad and good: the above doesn't work, but we can introduce more instance variables in a `finished` hook, and in fact this how it's implemented here: https://github.com/kostya/auto_constructor . But, instead of using instance vars, the `field` macro will store this info in some array, and later process that array. It works because it doesn't use instance vars in the `finished` macro.

We can change the compiler to have instance vars be processed/defined **before** `finished` macros are executed. I have that change working on my machine (though I didn't thoroughly tested it), and with that the above snippet runs fine. The downside of this approach is that the `finished` macro now obviously **can't** define new instance variables (and if it does, they will probably be ignored).

So, which approach should we chose?

I think I'd like to stick with the latter behaviour, because I'd like macros to work on instance variables and their metadata. Right now they only have just a few (their type, whether or not they have a default value, and what's the default value), but eventually, with `@[Attribute]` (https://github.com/crystal-lang/crystal/issues/3620) we could store arbitrary data in them to be able to more easily implement `JSON::Mapping` and such (and maybe more use cases that right now I can't imagine).

Just note that `JSON::Mapping` could still be implemented on top of instance var attributes **without** this change, because macros inside methods are only expanded when methods are instantiated, and at that point instance vars are already defined. A partial implementation is here: https://github.com/crystal-lang/crystal/issues/5643#issuecomment-360817842

If we go with the latter approach, the `AutoConstructor` project above can still work: the `field` macro can declare the type of an instance variable right away, but still store the associated info in some compile-time array (though it might be convenient to use an attribute at that point).

The question is: how do you use `finished`? And do you think your projects could still work if we change the compiler to work in the latter form?

(One more thing: I don't want to change the compiler to just be able to implement the above `AutoConstructor` module, which I think it might not be very useful. Instead, I'm thinking about a way of having access to instance variables in `finished` macros, which is something that isn't currently possible, to open up the way for more flexibility, such as defining various things based on instance vars (not just a constructor)).

**Comment by RX14** [comment]
The ugly compromise is to implement a hook before ivars are typed which acts as current, and implement a new hook after the ivar pass to implement this behaviour. I don't particularly want that, just mentioning it as an option if we suddenly realise that both behaviours are essential.

**Comment by straight-shoota** [comment]
I think it's fine to change. You shouldn't need `finished` hook to declare instance variables, they can be defined in an `included` hook or through a direct macro call. `finished` should have access to the "finished" type information (as far as possible at that point) and use the available data (including ivars) to add something on top.

**Comment by rumenzu** [comment]
I actually use the `included` + `finished` macro hooks for a similar use-case.

My implementation [https://github.com/rumenzu/quartz/blob/master/src/quartz/state.cr](https://github.com/rumenzu/quartz/blob/master/src/quartz/state.cr) is actually based on kostya's `AutoConstructor` project.

As you mentioned I'll have to declare instance variables right away, though I'll need to store some extra info in an array until the meta attributes feature lands.
I think it will help to reduce code complexity and it will be simpler to read/understand.

**Comment by vladfaust** [comment]
I have neutral position on it and also have a question - where to read about how exactly Crystal compiler works - its passes etc?

**Comment by asterite** [comment]
@vladfaust it's in the source code :-)

There are also a couple of talks I gave at Manas, just search crystal compiler internals on Google, or ask someone at gitter

**Comment by asterite** [comment]
If we do this, this bug will "reopen" with "will never fix": https://github.com/crystal-lang/crystal/issues/3964 (I found it because there's a spec about that issue in the compiler)

**Comment by asterite** [comment]
Hm, I'm not sure we'll go with this (can't find a good way to implement it), plus the only use case I can come up is the auto-constructor, which can be done without this change.

**Comment by bew** [comment]
Why not have 2 hooks? Or have the `finished` one configurable in some way?

**Comment by asterite** [comment]
Well, I managed to make it work (oh, wait, no, it doesn't work well with default values... 😢)

That said, now I'm not sure why we need the `finished` hook. I'm seeing [the original PR](https://github.com/crystal-lang/crystal/pull/3612), it was about being able to extend `JSON.mapping` in some way, or to gather info at compile-time to later process it. I'm not sure why we would still need to do that.

So... unless someone comes here and tells us how they are using `finished` for, and why it can't be done without it, I'd say we can remove it from the language.

The main issue with `finished` is that... what can you do there? Can you declare a new type? If so, how can you use it? Can you declare new instance vars? What for?

I'll give this two weeks. If no good use cases appear, it will be gone. Otherwise, we'll leave it just like it is now, because that's the most consistent thing to do code-wise (by looking and seeing how the compiler works).

**Comment by bew** [comment]
_Note: maybe the users of this feature don't follow this issue_

Maybe you can find some valid examples in [this github search: "macro finished" language:crystal fork:false](https://github.com/search?utf8=✓&q="macro+finished"+language%3Acrystal+fork%3Afalse&type=Code)

Some examples from this github search (the ones I think worth looking):
- https://github.com/MakeNowJust/noir/blob/01065d1d5775464b7fa273dcbc85999269931d39/src/noir/token.cr#L5
- https://github.com/splattael/bigbrother/blob/1290adf050de8c99c2a5ef1d25fc478cde22785e/src/bigbrother/check.cr#L50
- https://github.com/luckyframework/habitat/blob/25c1e4475f6e825cc2c073ecfb4e3c8965874a40/src/habitat.cr#L68
- https://github.com/gurapomu/attendance_mng/blob/db108a8aa833dfaf7932c02cca8e4ebe9e9ff292/lib/kemal/src/kemal/ext/context.cr#L11 (using a constant filled by https://github.com/gurapomu/attendance_mng/blob/db108a8aa833dfaf7932c02cca8e4ebe9e9ff292/lib/kemal/src/kemal/helpers/macros.cr#L96)
- https://github.com/imdrasil/jennifer.cr/blob/0847244712a8a88031f2edb183e556c7d8c3e43c/src/jennifer/view/base.cr#L128
- https://github.com/calebuharrison/spatch/blob/33bfaa3040f925d6fbc2fc5ef34003d31d3fc788/src/spatch/task.cr#L50
- https://github.com/vladfaust/core.cr/blob/66ac708ca6d870efabb00c0f3496358f95ef36f9/src/core/schema/mapping.cr#L10
- https://github.com/kostya/auto_msgpack/blob/64cc2020b405ff4113fe509bdf66eaf02c07e49f/src/auto_msgpack.cr#L21
- https://github.com/javanut13/slang/blob/d05f0e0fc9eb9865a985e3bfe09f8f110eaca910/src/slang/objects/types.cr#L9
- https://github.com/aca-labs/hyperloop/blob/87e9062bfcacac2490e1b2145443452888551630/active-model/src/active-model/model.cr#L15
- https://github.com/imdrasil/jennifer.cr/blob/0847244712a8a88031f2edb183e556c7d8c3e43c/src/jennifer/model/validation.cr#L33 (called by a `finished` hook)
- https://github.com/imdrasil/factory/blob/824f705528430711117b29b83cd9182c9a44db3a/src/factory/base.cr#L113

**Comment by asterite** [comment]
I guess we can leave it just like now then, because it works.

**Comment by bew** [comment]
But the chicken & egg problem is still there, and we don't have any way to have a `finished` that can declare ivars & method, and another `finished` that can use `@type.instance_vars` to declare other methods based on that.

Please re-open this issue

**Comment by faultyserver** [comment]
> The main issue with `finished` is that... what can you do there? Can you declare a new type? If so, how can you use it? Can you declare new instance vars? What for?

I have a situation where I'd like this behavior to define a new type that essentially clones the instance variables from the including class/struct. From bew's links above, this seems to be a pretty common situation that currently necessitates a work around.

In short, I want to be able to do this:

```crystal
module Change
  macro included
    {% verbatim do %}
      macro finished
        struct Changeset
          {% for prop in @type.instance_vars %}
            property! {{prop.name}} : {{prop.type}}?
            property {{prop.name}}_changed? : Bool = false
          {% end %}

          # initializers, other methods, etc.
        end
      end
    {% end %}
  end
end

class Post
  include Change

  property title : String
  property author : String
end

pp Post::Changeset.new
# Post::Changeset(
#   @title=nil,
#   @title_changed=false,
#   @author=nil,
#   @author_changed=false
# )
```

<sub>Yes, this may seem like a lot more "magic" than some people would like to see in Crystal code, but given the proclivity of this pattern, I think it's worth considering regardless. Especially because it could help the code that powers this pattern to be more pragmatic, less magical, and easier to comprehend, playing into the macro's features instead of working around them.</sub>

I have two ideals in my head: not modifying the including type in any way<sup>1</sup>, namely constants in this case (other than defining the `finished` macro, I guess), and more importantly, not creating _Yet Another DSL for Properties(TM)_.

ORMs and libraries in that vein I think run into this problem the most (as bew's links show), as they generally want to hook into the properties of a type to define a bunch of logic, define extra methods based on those properties, and so on.

Before `JSON::Serializable`, having a type that was both `JSON` and `DB` mappable was always repetitive, having to define the same properties in a named tuple argument to each. I think that's a somewhat valid way of addressing this issue, but isn't a very pleasant experience, and has its own issues of defining properties each time one of these macros is called.

(I think) this was part of why `JSON::Serializable` was introduced, to clean up this duplication and make it more flexible as a whole (and I'm hoping `DB.mapping` will get a similar `DB::Serializable` in the near future!). But moreover, it works across both inheritance and composition of types, and, most importantly, doesn't enforce any kind of DSL on the types that use it. It becomes _purely additive_, which I think is a good property for modules to adhere to.

With that, and coming from the other discussion in this thread, I think there are two different ways of addressing this problem:

- Implement the change to `macro finished` to as proposed here, giving it access to the complete type information directly. This would be the most ideal, and could have a transitional implementation as a separate macro to avoid breaking existing code for now. In all of bew's links, only 1 actually defines a new instance variable property (via `getter`). While that may not be an exhaustive sample set, I think it shows a good enough trend. Further, I think this change would help push libraries to use annotations and other standard language features instead of writing their own "proprietary" DSLs.<sup>2</sup>

- Or, implement some kind of macro hook for when instance variables are defined, similar to `method_added`. I don't think this is really ideal, as it would still necessitate the "separate array of values", but wouldn't require other custom macros to build that array.

---- 
<sup>1</sup> For reference, I have actually found a way to accomplish this goal by defining the new type directly in the `included` macro, then having `finished` call the macro to define methods on that new type. It's not pretty, and I don't think it's a long-term solution, but it is a working compromise for now: https://github.com/faultyserver/change/blob/31290084ce67c8f4af24d0a57c8018635a2824ab/src/change/schema.cr#L1

<sup>2</sup> I don't doubt that DSLs would still exist. In fact I would still plan on making one available in the library I am writing, but they wouldn't be a necessity, and would truly just be syntactic sugar for boilerplate things like adding an annotation to property definitions, or defining multiple properties from a single line (e.g. a `belongs_to` macro in an ORM).

**Comment by asterite** [comment]
@faultyserver Do you really want to track all instance variables?

One way to solve this is by letting `Change` define a custom macro that defined a property and the related "changed" property.

What I mean is, what you want to do is already possible, just not with the syntax/API you want it. But defining a property with a related property is definitely possible. So I wouldn't change the language (I really wouldn't know how, anyhow) to allow defining instance variables in the `finished` macro.

**Comment by faultyserver** [comment]
> Do you really want to track all instance variables?

As of now, yes. I guess more concretely, I want to match what `JSON::Serializable` does by defaulting to every instance variable and then using annotations to opt-out.

> One way to solve this is by letting Change define a custom macro that defined a property and the related "changed" property.

This is what I meant by the "'proprietary' DSLs" I described above, and is really what I want to avoid. Philosophically, I don't want users to have to change how they define properties just for me to be able to use them, but as of now that's the way it goes (and I've [implemented it as such here](https://github.com/faultyserver/change/blob/31290084ce67c8f4af24d0a57c8018635a2824ab/src/change/schema.cr#L13-L33)).

My main issue with this style is that it isn't composable. For example, my library isn't meant to be a full-blown ORM, so I don't intend to define a `DB.mapping` in it. So, if a user wanted to use my library with an ORM (which is one of its goals), they're essentially stuck because they have to use my macros to define properties that I can read, but also use the ORM's macros to define properties for it to use, which gets very messy and potentially fails depending on how each library ends up defining the properties.

In that specific case, a `DB::Serializable` would essentially solve the issue, but the larger issue to me is general composition of libraries as a whole. Using the standard library's mechanisms directly and having libraries build off of that feels a lot better than having libraries wrap those mechanisms and be incompatible with each other by default.

> What I mean is, what you want to do is already possible, just not with the syntax/API you want it. But defining a property with a related property is definitely possible. So I wouldn't change the language (I really wouldn't know how, anyhow) to allow defining instance variables in the finished macro.

Sadly I'm inclined to agree. I don't think this is necessarily a pressing issue, and maybe there can be a "standardized" third party re-implementation of `property` that defines a hook registry for libraries to use or something like that. I'm less concerned with the "build a list constant of properties" than I am with the bespoke DSLs, so I'm not beat up about this feature not changing, but it does make things awkward to implement.

While trying to avoid this problem, I also tried using generics and accessing `T.instance_vars` outside of a method, but that didn't work either, as expected from this whole discussion. My takeaway is that it feels very strange to not have a way of getting at this information naturally from the language and having to build it up manually for every use case.

I think part of what put me down this rabbit hole was [reading the docs for `finished`](https://crystal-lang.org/reference/syntax_and_semantics/macros/hooks.html):

> `finished` is called once a type has been completely defined - this includes extensions on that class. Consider the following program:

The wording, to me, makes it sound like the information is available directly in the macro, and there's no mention of this restriction. (The example uses `@type.methods`, which _is_ available at that time).

I might try to draft up a docs PR that makes it more clear to hopefully avoid this confusion for others in the future.

**Comment by Blacksmoke16** [comment]
> So, if a user wanted to use my library with an ORM (which is one of its goals), they're essentially stuck because they have to use my macros to define properties that I can read, but also use the ORM's macros to define properties for it to use, which gets very messy and potentially fails depending on how each library ends up defining the properties.

Annotations + properties can help.  For example, Granite ORM's DSL for defining columns is simply a wrapper to defining properties with an annotation.  This allows other libraries, to simply apply their own annotations to the columns/properties for their implementation.

For example:

```cr
@[CRS::ExclusionPolicy(:all)]
class Character < Granite::Base
  connection pg
  table "characters"

  column id : Int32, primary: true, auto: false

  @[CRS::Expose]
  @[Assert::NotBlank]
  column name : String

  @[CRS::Expose]
  column corporation_id : Int32

  @[CRS::Expose]
  column alliance_id : Int32?

  @[CRS::Expose]
  @[Assert::GreaterThanOrEqual(value: 0.0)]
  column balance : Float64 = 0.0, converter: Granite::Converters::PgNumeric

  @[CRS::Expose]
  column created_at : Time?

  @[CRS::Expose]
  column updated_at : Time?

  column owner_hash : String
  column access_token : String
  column refresh_token : String
  column expires_at : Time
end
```

However, as you mentioned, not being able to access ivars outside of a method can be an issue in some cases, see #7504.

**Comment by faultyserver** [comment]
That's a good point, and I think it's one of the powerful aspects of annotations. It definitely works for a lot of use cases that just need to define _methods_ based on properties.

But this line is what remains a concern for me:

> Granite ORM's DSL for defining columns is simply a wrapper to defining properties with an annotation.

Because of that, if a user wanted to use a library that needs access to those properties in a way that it can clone them onto a new object (e.g., my use case, or many of the examples bew linked), they simply don't work because they need to have their own macros to store the generated properties in an array. So, either a user has to define their properties twice (once with each DSL), or they basically can't use the libraries together (at least, I haven't found or seen a way of doing so).

I don't think DSLs like this are bad, and I think Granite has arguably the best implementation of this kind of DSL because it keeps things simple and is purely a wrapper and doesn't need to do any extra type generation. So, without changing anything about Granite's DSL, if the `finished` macro were to change, it would suddenly become composable with other libraries that want to generate derived types, which would be great!

But, in my limited knowledge of the problem from the compiler's perspective, I understand that this is not a path worth pursuing for now.

I'm thinking more about overwriting the `property` macro with some kind of registry and that there might be an entirely different approach to solving this problem. It just replaces it with a different problem of adding a common dependency and a non-native pattern, but at least it would be one that might be closer/more compatible with a potential change to `finished` in the future.

**Comment by Blacksmoke16** [comment]
> Because of that, if a user wanted to use a library that needs access to those properties in a way that it can clone them onto a new object (e.g., my use case, or many of the examples bew linked), they simply don't work because they need to have their own macros to store the generated properties in an array. So, either a user has to define their properties twice (once with each DSL), or they basically can't use the libraries together (at least, I haven't found or seen a way of doing so).

I think you might have misunderstood.  In my previous example, `column corporation_id : Int32` would be expanded to like:

```cr
@[Granite::Column(column_type: nil, converter: nil, auto: false, primary: false, nilable: false)]
@corporation_id : Int32? 

def corporation_id=(@corporation_id : Int32); end

def corporation_id : Int32
  raise NilAssertionError.new "Model#corporation_id cannot be nil" if @corporation_id.nil?
  @corporation_id.not_nil!
end
```

So in the end it's just another ivar.  There is nothing stopping the user from just defining a property and applying the annotation on their own without using the Granite macro DSL.

If another library wanted to do something else, it would just still work as if you just did like `property corporation_id : Int32` since we're only dealing with instance variables, no library specific implementations. 

I think it's important to realize the difference between like, not sure how to best word this, but like a library using a macro DSL to build out custom stuff versus powering a library based off metadata associated with an instance variable.

The latter is much more flexible as all libraries have access to the same set of ivars, with a library basing its implementation on if that ivar has an annotation in addition to what fields/values that annotation has.  

Another pattern you can do is like
```cr
macro finished
  {% begin %}
    {% services = ClassService.all_subclasses.select { |klass| klass.annotation(Register) } %}
    {% for service in services %}
      {% for service_ann in service.annotations(Athena::DI::Register) %}
        {% key = service_ann[:name] ? service_ann[:name] : service.name.split("::").last.underscore %}
        private getter {{key.id}} : {{service.id}}
      {% end %}
    {% end %}
  {% end %}
end
```

This is what I use for my DI container in Athena.  This is used outside of any method to define ivars within the container struct.

```cr
# Register some service
@[Register(name: "some_service")]
class SomeServiceClass
end

# Would define this in the container
private getter some_service : SomeServiceClass
```

You would ofc have to have more code in the initializer to actually set the values of each ivar.

**Comment by asterite** [comment]
So, in your example, how do you track whether a property has changed or not? I think one way to do that would be to override `property` (or `setter`) so that when you change a value it marks it as changed. Then you would need some kind of `commit` or `save` to mark that things are not changed anymore. But it means you need a **different** behavior for `property`. And it of course won't work if you just rely on instance variables which could be modified anywhere else.

So how would your code work seamlessly?

**Comment by Blacksmoke16** [comment]
I'm not saying that this is the most optimal solution, nor that there isn't room for improvement, but it works and allows for that seamless integration with other libs.

https://play.crystal-lang.org/#/r/7fzd

**Comment by faultyserver** [comment]
> So in the end it's just another ivar. There is nothing stopping the user from just defining a property and applying the annotation on their own without using the Granite macro DSL.

Yeah, and in Granite's case that works just fine, because Granite (seems to) work entirely within the containing type and doesn't need to store those defined properties for use in another type later on. This is a very nice, direct use case.

But:

> If another library wanted to do something else, it would just still work as if you just did like `property corporation_id : Int32` since we're only dealing with instance variables, no library specific implementations.

The issue here (as you address a bit in your next paragraph) is when a library requires a custom macro to store off those properties to "build out custom stuff" later. For example, this happens in my library [here](https://github.com/faultyserver/change/blob/31290084ce67c8f4af24d0a57c8018635a2824ab/src/change/schema.cr#L24-L33). Now, I _have_ to either use my DSL to define properties or duplicate property definitions, otherwise my library won't work because it has no access to the instance vars as defined by `property` outside of methods to be able to generate a derived type.

Hopefully I'm understanding your explanation of the different types of libraries here. I think this is a distinct use case from others that intend to modify the including class. I think this use case is arguably more of a fit for Generics, but they have similar issues, and I think changing how Generics work to have data layouts that are completely modified by the generic type parameters is much more complicated and unnecessary.

> So, in your example, how do you track whether a property has changed or not?

Not sure if this was directed for my example or Blacksmoke's, but I track this in the derived struct, not on the class itself. My library is essentially a direct port of Ecto Changesets, which act as a proxy for modifying and validating data structures.

When generating the derived type, my macro defines a [cloned prop _and_ a `_changed?` prop](https://github.com/faultyserver/change/blob/31290084ce67c8f4af24d0a57c8018635a2824ab/src/change/schema.cr#L49-L53) and changes are purely managed by methods on that derived type.

> And it of course won't work if you just rely on instance variables which could be modified anywhere else.

A primary aspect of the design I'm going after is that a Changeset is a distinct way of modifying an object, it doesn't have to care about tracking instance variables being modified on the underlying type, as those are assumed "out of scope" to the Changeset's pattern. In this way, even the use of the `property` macro is unnecessary for me, as long as the instance variable is defined at all, by any other system.

> https://play.crystal-lang.org/#/r/7fzd

This is a good example! It seems kind of similar to how [`Onyx::SQL` implements this](https://github.com/onyxframework/sql/blob/master/src/onyx-sql/model/changes.cr#L126-L130). But I don't think it fits my end goal ideally. A la the paragraphs above, the goal is a proxy structure that doesn't modify the including structure until explicitly "applied", so relying on the existing instance variables on the type itself isn't effective. That was how [Crecto](https://github.com/Crecto/crecto/tree/master/src/crecto) implemented changesets and I found that to be a heavy drawback in trying to have non-destructive modifications and validations (that would also be guaranteed thread-safe in future multi-threaded Crystal!)

That said, I think I have an idea of a different workaround based on Onyx's that I'm going to try out tonight, so thanks for the inspiration!

---

Side note: sorry for having very long posts, but I've found this to be a complicated issue that I've been working around for a very long time now. Having done Elixir work before, I started using Crecto more than 2 years ago because I find that pattern of data manipulation to be the most enjoyable, and I have been tinkering with its implementation of Changesets for almost that entire time because they haven't matched my expectations of how they should work. From that tinkering, I've gained a similar perspective to Vlad's comment in #7504:

> I've tried many approaches to implement the best possible API, and I always faced the need to know them variables. Please believe me on that. Current annotation approach is nearly perfect in the terms of codebase and API, and resolving the issue would make it even more ideal.

I know there are ways to implement _similar_ behavior that bypasses the need for generated types and this change entirely (such as the example code provided above), but they defeat my primary goal of not modifying/bloating the underlying type. I have working code that is not ideal, but suitable for now, and that is fine, but I keep coming back to this issue as stopping the code from being cleaner, simpler, and more effective.

**Comment by Blacksmoke16** [comment]
> But I don't think it fits my end goal ideally. A la the paragraphs above, the goal is a proxy structure that doesn't modify the including structure until explicitly "applied", so relying on the existing instance variables on the type itself isn't effective.

This works https://play.crystal-lang.org/#/r/7g0p

**Comment by faultyserver** [comment]
```
macro included
    @change_set : ChangeSet = ChangeSet.new

    def apply
    # ...
end

obj = User.new "Fred", 12
obj.apply
```

This is the pattern I'm trying to avoid/invert. This is defining new behavior on the including type. I've used this pattern before and am conciously trying to not define methods on the including type.

Yes, this may seem like an entirely arbitrary philosophy, and to an extent it is. But in short, I want the data type to be the data type, and the derived type to provide the functionality. I get that that's a fair bit different than the some of the core philosophy of Crystal and a lot of OO languages.

I have seen and written implementations that do this before, and am explicitly trying to use a different pattern. That's part of why I'm not adamant about needing this feature to build my library, cause I know a similar thing can be done in many existing ways, I'm just thinking about ideals in how I want to implement this now. The existing options are simply less appealing to me from a library design perspective at this point.

For reference, here is the usage pattern I have created: https://github.com/faultyserver/change/blob/master/example.cr

**Comment by jhass** [comment]
To me it feels like finished is the wrong solution to the right problem. Given the ability to reopen types, there actually is no point where a type definition is truly done. Most usecases for finished seem to deal with handling the instance variables of a type, so how about we make a macro hook that is called each time we discover a new instance variable? Or generalized each time it has one or more new instance variables, to allow the compiler to optimize (reduce) the number of calls to it later on. And then two more of those for methods and class variables I guess

**Comment by faultyserver** [comment]
>  Most usecases for finished seem to deal with handling the instance variables of a type

I agree, and think that's how most people arrive to using `finished` in the first place, because the docs currently say "invoked after instance variable types for all classes are known.", so with no extra context, it sounds like the only place its possible to use these.

> so how about we make a macro hook that is called each time we discover a new instance variable?

This would be really nice! There's already the `method_added` macro, so to an extent I think this makes the most sense from a consistency perspective.

However, I can't find it now, but I remember seeing somewhere that this wouldn't really be feasible because of how instance variables get typed. At least, the hook wouldn't be able to guarantee that each variable has a completed type at that point. Maybe I'm misunderstanding that though...

FWIW, I think it's fine to say the type information is only available based on what gets provided when the instance variable gets created. (e.g., only has type information if it is initialized as a `TypeDeclaration` or `Assign`). I can't think of any times I've actually used or even seen instance variables declared without type information, so realistically this is a non-issue for me.
