### ISSUE TITLE
Recursive Hash initialization

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6050]
Hola,

```crystal
alias MyHash = Hash(String, String | MyHash)
h = MyHash.new # Doesn't work
h = {} of String => String | MyHash # Works
```

:bug: ?

**Comment by asterite** [comment]
Recursive types are buggy, incomplete and can simply be done with a recursive struct. I said many times "let's remove them from the language", and I think that what will happen, eventually. So try not to use them. You probably don't need them.

**Comment by r00ster91** [comment]
Yes let's remove them!

**Comment by vladfaust** [comment]
@asterite could you please help me then? I cannot make it work:

```crystal
struct Param
  @value : String | Int32 | Float64 | Hash(String, Param) | Nil

  def initialize(@value)
  end

  def [](key : String)
    if @value.is_a?(Hash)
      @value[key]
    else
      raise Exception.new("Cannot call #[] on #{@value.class}")
    end
  end

  def []=(key : String, value)
    if @value.is_a?(Hash)
      @value[key] = value
    else
      raise Exception.new("Cannot call #[]= on #{@value.class}")
    end
  end
end

params = {} of String => Param
params["foo"] = "bar"
```

**Comment by asterite** [comment]
`Param.new("bar")`

But sorry, I have no time to do 1on1 support. Better ask in gitter this kind of things.

**Comment by vladfaust** [comment]
@asterite you paved me the way. Thanks then, hope this will be helpful to someone!

**Comment by Blacksmoke16** [comment]
While I tend to agree that structs are usually the way to go instead of a variable with a recursive type, there are some uses cases that the recursive type makes more sense.

For example, including user context in log messages.  Each log event could have its own hash of context, of any type, including a sub hash.  

`msg.extra["git"] = {"branch" => git_info[1]?, "commit" => git_info[2]?}` is a lot more straightforward than using structs from a UX point of view.
