### ISSUE TITLE
Type check in never-called methods

### ISSUE THREAD

**Issue by xnuk** [crystal-lang/crystal#6103]
Tested on: Crystal v0.24.2 / Arch Linux x64

```crystal
def profit
  i_am_integer = "actually not"
  i_am_array = i_am_integer - 100
  i_am_array.each do |value|
    p value
  end
end

# And never use `profit`
```

This code never get errors until `profit` is called, and also no warns about dead code. This is inconvenient; we can't gain type checker's benefit during implementing methods, until real use. Is there a proper option that makes the compiler to check types in dead methods? If so, why isn't it default?

**Comment by asterite** [comment]
Duplicate: https://github.com/crystal-lang/crystal/issues/4402#issuecomment-328354503

This is not going to change unless we decide to force types on all methods (which, of course, is never going to happen).

**Comment by xnuk** [comment]
Why does Crystal need to force types while it's static typed language? Type inference works well, so we don't need to write down types of every single methods, so I don't think it's a problem.

**Comment by bew** [comment]
Because the compiler has no way to know the method's arguments types until the method is called.

For example:
```cr
def add(a, b)
  a + b
end
```
This method works when a and b are of type `String`, but not when a is `nil` and b is something else. Should the compiler gives you a compile error?

**Comment by asterite** [comment]
It really doesn't matter. If it's type-checked, you can't know if it works. That's semantic. So write tests that exercise your methods. That way you'll get type-check plus semantic-check.

Why it needs to force types? Because if you don't force types, you can't type-check a method when you don't know the types. It could be done if the method has no arguments, but that would just be inconsistent with everything else.

**Comment by xnuk** [comment]
Suppose:
```crystal
def sum(a : Int32, b : String) : Nil
  a + b
end
```

This forces type, and compiler says okay. But it's dead method, and also types doesn't make sense.

Compiler didn't notice these problems until I run with dummy arguments:
```crystal
sum(0, "")
```

I think type checking is the compiler's job, not test cases' job. At least compiler should give dead code warning.

**Comment by RX14** [comment]
@xnuk the problem is that it's impossible to typecheck methods which aren't fully typed. And type restrictions in crystal are just that: restrictions not *specifications*. If you restrict an argument type to `Int`, it could be any integer type. Which do you pick to type the method with?

Regarding test cases, you can use `typeof(sum(1, ""))` to check for type errors without actually executing code. There's really no other way to do it because of how the type inference algorithm work. It's the price you pay for crystal's extreme expressiveness compared to all other statically typed languages.
