### ISSUE TITLE
add dependencies zlib1g-dev libssl1.0-dev for Ubuntu

### ISSUE THREAD

**Issue by BenDietze** [crystal-lang/crystal#6140]
Hey guys,

while testing Crystal on _WSL_ and _Ubuntu 18.04_ (clean installs) i have to install **zlib1g-dev**  and **libssl1.0-dev** too to compile src correctly - maybe usefull to put this into your _gitbook_ for installation on Ubuntu and Windows bash (or correct my deps to better).

https://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html
https://crystal-lang.org/docs/installation/on_bash_on_ubuntu_on_windows.html

**Comment by bcardiff** [comment]
Hi @BenDietze , depending on the libraries of the stdlib you use you might need even more packages.

The issue happens every now and then, specially on new environment where developers jump to install crystal before other common packages and libs 🎉 

PR are welcome in https://github.com/crystal-lang/crystal-book , maybe a section inside *Using the compiler* that can point some of the common libraries like zlib and libssl. But note that those instruction might vary for each platform as it is stated in https://github.com/crystal-lang/crystal/wiki/All-required-libraries that is linked in https://crystal-lang.org/docs/installation/from_source_repository.html .

I think the right place in there and not when installing the compiler since.

**Comment by BenDietze** [comment]
Hi @bcardiff , thank you very much - i did not know this site in your wiki, but now i am am happy (it's perfect!) 👍 i am on the Crystal road since a week or some days, so i can't help today, but some month later it maybe possible for me to contribute such way
