### ISSUE TITLE
Inconsistency in type inference

### ISSUE THREAD

**Issue by v-q** [crystal-lang/crystal#6153]
```crystal
x = "0"
y = "0"

if x.is_a?(String) # => true
  x = x.to_i{0}
  p typeof(x) # => Int32
end

p typeof(x) # => Int32
```

```crystal
x = "0"
y = "0"

if y.is_a?(String) # => true
  x = x.to_i{0}
  p typeof(x) # => Int32
end

p typeof(x) # => (Int32 | String)
```

Why is the second not `String`?

**Comment by asterite** [comment]
In the first example, the `else` branch doesn't have a type (NoReturn) for x (because it can only be a string), and the `then` branch has a type of `Int32`, so the type is `Int32`.

In the second example, the condition is not on `x`, so the compiler can't (won't) deduce anything about it.

But as a general advise, don't rely on these type flows for anything. You then rely on a user having to figure out how the compiler works.

**Comment by v-q** [comment]
Thanks, I see. Would it at all be possible to change `x`'s type according to a condition not on`x`?

**Comment by asterite** [comment]
No

**Comment by v-q** [comment]
I thought, perhaps, there could be some other way of doing it if written differently, but I see. Thanks for the insight.

**Comment by RX14** [comment]
@v-q this is just an edge case, where `y.is_a?(String)` is always `true`. This type inference would be correct if `y.is_a? String` wasn't always true. And given that `if true` [doesn't restrict the type](https://carc.in/#/r/47my) either, this shouldn't be expected. And I think we discussed inferring `if true` before, and decided against it.

Either way, it's unlikely to come up in real code.
