### ISSUE TITLE
Instantiating an array of arrays (of integers) crashes the compiler

### ISSUE THREAD

**Issue by alexbrahastoll** [crystal-lang/crystal#6172]
Hi there,

First of all, keep up the good work with the Crystal language! I have just started to experiment with the language (coming from a Ruby background) and found it really easy to install and start using Crystal's compiler and tools =)

I was trying to implement a Crystal version of the famous Knight's tour problem and it seems I have found a bug related to an array of arrays (i.e. a matrix).

Bellow follows a very short snippet that causes the compiler to crash:

```crystal
class Board
  property squares
  getter rows, columns

  def initialize(@rows = 5)
    @columns = rows
    @squares = Array.new(rows) { Array.new(columns) { 0 } }
  end
end

board = Board.new
```
When attempting to compile the code above, the compiler crashes with the following error:

```
cast from Nil to Crystal::GenericInstanceType+ failed, at /private/tmp/crystal-lang-20180310-76015-tfxflp/crystal-0.24.2/src/compiler/crystal/types.cr:1428:20:1428
Crystal::TypeParameter#solve<Crystal::NonGenericClassType>:Crystal::ASTNode+
Crystal::GenericInstanceType+@Crystal::GenericInstanceType#replace_type_parameters<Crystal::NonGenericClassType>:Crystal::Type+
Crystal::TypeDeclarationProcessor#process_owner_guessed_instance_var_declaration<Crystal::Type+, String, Crystal::TypeDeclarationProcessor::InstanceVarTypeInfo>:(Crystal::MetaTypeVar | Crystal::TypeDeclarationProcessor::Error | Nil)
Crystal::TypeDeclarationProcessor#process_instance_vars_declarations:Nil
Crystal::Program#top_level_semantic<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor)
Crystal::Program#semantic<Crystal::ASTNode+, Bool>:Crystal::ASTNode+
Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
Crystal::Command#run_command<Bool>:Nil
Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil)
main
```

I am using macOS High Sierra (10.13.3 (17D47)), Crystal 0.24.2 (2018-03-10) and LLVM 5.0.1.

This same snippet also causes a crash when run in play.crystal-lang.org (https://play.crystal-lang.org/#/r/49ia) - which I assume runs in some flavor of Linux - so it does not seem to be macOS specific.

I imagine my implementation attempt may contain errors. If so, I would also appreciate if someone could indicate the correct way of creating an array of arrays (of integers) in Crystal (I searched online and was not able to find much; I have found the solution that is being used in the snippet above, but it is obviously not working).

I have searched open issues and was not able to find a report similar to this one. I apologize if this is something that is already being tackled.

Cheers.

**Comment by Vici37** [comment]
I was able to get your snippet to compile successfully by replacing the relevant line with:
`@squares = Array(Array(Int32)).new(rows) { Array(Int32).new(@columns) { 0 } }`

I used `@columns` instead of `columns` and declared what types the Arrays were. Generally, generics need to include this when being defined or the compiler will throw an error (or crash, in this case).

Good find!

**Comment by straight-shoota** [comment]
@Vici32 No, the generic arguments should not be neccessary, as this compiles quite fine without any instance vars involved:
```cr
rows = columns = 5
Array.new(rows) { Array.new(columns) { 0 } }
```

And that's not even the real issue here. It seems that the compiler fails at determining the type of `@squares` through inference from the assignment `@squares = Array.new(rows) { Array.new(columns) { 0 } }`.
If you assign the type manually (`property squares : Array(Array(Int32))`) it works. Specififying the generic arguments in the expression just indirectly helps the compiler to infer the correct ivar type.

Now, this should obviously not produce a compiler error but either work as expected or produce a semantic error with appropriate error message. I suppose this can be fixed and should work.

**Comment by alexbrahastoll** [comment]
Thanks @Vici37 and @straight-shoota for the detailed explanations and workarounds. The suggestions you have made worked fine!

Cheers.
