### ISSUE TITLE
wrong result adding two Time ?

### ISSUE THREAD

**Issue by ilmanzo** [crystal-lang/crystal#6173]
I got this strange behavior while playing with exercism.io "gigasecond" exercise, here
http://exercism.io/exercises/crystal/gigasecond/readme

when the timespan added is smaller, the bug is not present. Maybe something related to timezone handling ?

```
$ crystal --version
Using compiled compiler at `.build/crystal'
Crystal 0.24.2+396 [7e8b219aa] (2018-06-09)

LLVM: 3.8.1
Default target: x86_64-pc-linux-gnu

$ cat addtime_spec.cr 
require "spec"

describe "bug?" do
  it "adds 1E9 seconds" do
    result = Time.new(2011, 4, 25, 0, 0, 0)+(1E9).seconds
    result.should eq Time.new(2043, 1, 1, 1, 46, 40)
  end
end

$ crystal spec addtime_spec.cr 
Using compiled compiler at `.build/crystal'
F

Failures:

  1) bug? adds 1E9 seconds
     Failure/Error: result.should eq Time.new(2043, 1, 1, 1, 46, 40)

       Expected: 2043-01-01 01:46:40.0 +01:00 Local
            got: 2043-01-01 00:46:40.0 +01:00 Local

     # addtime_spec.cr:6

Finished in 492 microseconds
1 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec addtime_spec.cr:4 # bug? adds 1E9 seconds

```
for reference, a python version of the same operation...

```
import datetime

def add_gigasecond(dt):
    """Calculate the date that someone will celebrate their 1Gsanniversary."""
    return dt + datetime.timedelta(seconds=10**9)

t0=datetime.datetime(2011, 4, 25)
t1=datetime.datetime(2043, 1, 1, 1, 46, 40)
t2=add_gigasecond(t0)
print(t1==t2)

```

**Comment by straight-shoota** [comment]
This is expected behaviour. `Time#add`  adds *exactly* the specified amount of seconds to the instance. You will however notice that, in your time zone, the number of seconds between 2011-4-25 00:00:00 and 2043-1-1 01:46:40 is actually different from what you expect. Check `Time.new(2011, 4, 25, 0, 0, 0).zone` and `Time.new(2043, 1, 1, 1, 46, 40).zone`, the difference of the offsets will probably explain the discrepancy of one hour.

A more thorough explanation can be found in the API docs: https://crystal-lang.org/api/master/Time.html

`Time.new` creates a time instance in the local time zone (`Time::Location.local`) which often observes daylight savings time. If you don't care about the local time zone (which you usually don't), you should use `Time.utc` instead of `Time.new`.

```cr
require "spec"

describe "no bug" do
  it "adds 1E9 seconds" do
    result = Time.utc(2011, 4, 25, 0, 0, 0)+(1E9).seconds
    result.should eq Time.utc(2043, 1, 1, 1, 46, 40)
  end
end
```

**Comment by ilmanzo** [comment]
sounds fair, thanks for explanation!
