### ISSUE TITLE
Defining to_s doesn't override puts's value

### ISSUE THREAD

**Issue by sancarn** [crystal-lang/crystal#6185]
Example:

```
class Test
  def to_s
    "hello world"
  end
end

puts Test.new
```
[Crystal Play](https://play.crystal-lang.org/#/r/4a1p)

Expected return value:

```
hello world
```

Actual return value:

```
#<Test:0x55840c0e6fe0>
```

Interestingly redefining inspect does override p's value:

```
class Test
  def inspect
    "hello world"
  end
end

p Test.new
```

[Crystal Play](https://play.crystal-lang.org/#/r/4a1q)

Also tested redefining `as_s`, but no difference. 

Snooped around in the source code to see if I could determine what is causing the issue but for all I can tell [`Kernel#puts`](https://github.com/crystal-lang/crystal/blob/4f9ed8d03208dd0db33993c5a6fa6753bc1cf91e/src/kernel.cr#L81) calls [`IO#puts`](https://github.com/crystal-lang/crystal/blob/4f9ed8d03208dd0db33993c5a6fa6753bc1cf91e/src/io.cr#L234) which calls [`IO#<<`](https://github.com/crystal-lang/crystal/blob/4f9ed8d03208dd0db33993c5a6fa6753bc1cf91e/src/io.cr#L191) which calls **`to_s`**. So it actually looks correct... So I'm not sure why this discrepancy occurs...

Note: that `to_s` is callable. I.E. `puts Test.new.to_s` will return `hello world` as expected.

**Comment by hugoabonizio** [comment]
[IO#<<](https://github.com/crystal-lang/crystal/blob/4f9ed8d03208dd0db33993c5a6fa6753bc1cf91e/src/io.cr#L191) actually calls `#to_s(io)`

```crystal
class Test
  def to_s(io)
    io << "hello world"
  end
end

puts Test.new
```

https://play.crystal-lang.org/#/r/4a1w

**Comment by sancarn** [comment]
Huh... So it does. I guess the question therefore is, should it?

E.G. in Ruby at least

```
class Test
  def to_s
       "hello world"
  end
end
```

Will do what I initially expected.

I know crystal isn't ruby but still... was quite confusing.

**Comment by straight-shoota** [comment]
You should almost always override `to_s(io : IO)`, not `to_s()`. This is explicitly stated in the [API docs](https://crystal-lang.org/api/latest/Object.html#to_s-instance-method).

The difference certainly doesn't matter for such a simple example, but when serializing a complex object to a string, it can have a huge impact. If you're sending the output to an IO (terminal, socket, file, etc.) you don't need to allocate the entire representation as string in heap memory. Instead `to_s(io : IO)` writes to the IO directly. In order to do that, every object needs a custom implementation of this method instead of `to_s()`.

That's a deliberate design choice in Crystal to make string serialization IO-focused, and I think this is a really good feature 👍

**Comment by jhass** [comment]
:point_up_2: should answer the question, closing.

**Comment by sancarn** [comment]
@straight-shoota Interesting. In that case is there anything to watch out for while overriding `to_s`?

**Comment by sancarn** [comment]
@jhass Ah okay! That makes sense 👍

**Comment by ajmihunt** [comment]
Wouldn't it then make sense to have the default `to_s(io : IO)` method defined as this?

`def to_s(io : IO)
  io << to_s
  end`

**Comment by straight-shoota** [comment]
No. It's the other way around. `#to_s(io)` is the more versatile implementation because it uses a streaming interface. `#to_s()` is a more specialized variant built upon that.
