### ISSUE TITLE
Crystal run/eval: pass the file name and the following arguments to the program

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#6291]
## Description

In most interpreters, the file name and the following arguments are passed to the program.
For example in `python`:
```python
#!/usr/bin/python -OO
import sys
print(sys.argv)
```
```sh
$ 2 ./myapp.py arg1 arg2 # or python -OO myapp.py arg1 arg2
$ ['myapp', 'arg1', 'arg2']
```
or in `shell`:
```sh
#!/bin/sh -eu
echo $@
```
```sh
$ ./myapp.sh arg1 arg2 # or sh -eu myapp.sh arg1 arg2
$ arg1 arg2
```

## Purpose

This will allow us to execute directly Crystal code like a script without the `build` and `run` steps.
Useful for testing and executing non-performance related tasks which the code changes often.

```crystal
#!/usr/bin/crystal run
puts ARGV
```
```sh
$ ./myapp.cr arg1 arg2 # or crystal run myapp.cr arg1 arg2
$ ["./myapp.cr", "arg1", "arg2"]
```

This feature can also be added to the `crystal eval` command:
```sh
$ crystal eval "puts ARGV" arg1 arg2
$ ["arg1", "arg2"]
```

The current behavior of `crystal run` it to take all non-option arguments as files, like `crystal build` does.
If this behavior for `crystal run` is really wanted to be kept, an option indicating that all following parameters will be passed as arguments, in addition to the files, can be created.

**Comment by asterite** [comment]
https://github.com/crystal-lang/crystal/issues/546

**Comment by j8r** [comment]
Thanks @asterite , this issue is thus a semi duplicate, my mistake. However I find a bit confusing to have `crystal` and  `crystal run` for build & run.
Also we can't use the flags that are in `crystal run` like `--verbose` or `--debug`, that can be useful.
IMO it will be clearer to merge this to `crystal run`, and eventually add an option like `-f` as used in `awk`.

**Comment by asterite** [comment]
But crystal is not a scripting language. I have a few programs written in crystal that I use in my machine. I compile them in release and copy them to /usr/local/bin. No need to recompile each time, and it's super fast.

**Comment by j8r** [comment]
Agree but when developing a CLI program, it's very handy. I still find having both `crystal FILE` and `crystal run FILE` confusing.
You said that Crystal is a compiled language - it feels weird that an argument right after `crystal` is taken by default as a file and *interpret* it.

**Comment by asterite** [comment]
It's just that by default the first argument is considered to be the filename if it's not one of the commands (and it's usually never the case because crystal filenames usually end with `.cr`). So it's just a nice convenient thing to do. And it's not that Crystal interprets your program, it compiles it and runs it.

And then, when you develop, you can do:

```
crystal file.cr -- arg1 arg2
```

you probably don't need to type that all the type, pressing up a few times in your shell will bring it up.

Once you are done with your program, you compile it in release mode and move it to `/usr/local/bin`

All I'm saying is that with the above workflow I don't see the need to treat crystal as an interpreted language. In fact, I wouldn't want to make any changes to the language to suggest that's the case. Putting a crystal file in `/usr/local/bin` and have it be compiled every time you want to execute it is a waste of energy.

**Comment by Willamin** [comment]
An interesting solution to the problem of "don't compile every time" could be to have `crystal run` cache the compiled binary somewhere like `~/.cache/crystal/run/`. I've written a rudimentary tool that accomplishes this, using a digest of the script's contents as a lookup for the cached binary. It still lacks some features that would be necessary if it was in the core Crystal command, but in practice it works well.

**Comment by j8r** [comment]
Fixed with https://github.com/crystal-lang/crystal/pull/9171
