### ISSUE TITLE
Remove time related aliases in Int: year, month, day, second, millisecond, nanosecond

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#6294]
There are aliases related to time - the singular and the plural variant of `Int#year`, `Int#month`, `Int#week`, `Int#day`,  `Int#minute`, `Int#second`, `Int#millisecond` and `Int#nanosecond`.

Note that `Int#microseconds` is only in plural

Related code: https://github.com/crystal-lang/crystal/blob/master/src/time/span.cr

Reference PR: https://github.com/crystal-lang/crystal/pull/6273

**Comment by asterite** [comment]
Note that I wanted to remove them but nobody liked that. So the direction should be the other one: we should add the singular names back (remove the `:nodoc:` from them, and add `millisecond`).

**Comment by Sija** [comment]
Submitted as #6297.

**Comment by ysbaddaden** [comment]
I'm neutral here, either solution is fine.

**Comment by straight-shoota** [comment]
> Note that I wanted to remove them but nobody liked that.

There are 4 :+1: on #6273 but only 1 :-1:. Besides, only one other core member expressed an opinion - and that was neither in favor nor against it. So it's certainly not true that there was a strong opinion for keeping these aliases. In fact, it was only a single voice critizising the PR.

So please, let's have an open and friendly discussion about this topic.

I personally don't care much, and I'm fine with either solution. Maybe tending a bit towards removing the aliases, because they actually don't add much convenience.

**Comment by RX14** [comment]
I'd prefer to keep them.

**Comment by Sija** [comment]
This can be closed since #6297 has been merged.

**Comment by bcardiff** [comment]
Thanks @Sija
