### ISSUE TITLE
Macro to add new binary / unary operator ?

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#6334]
Maybe a macro to add new binary / unary operator is an interesting idea?

Limit the symbol of operator only be single Unicode character, such as ∪, ∩, △.

This feature is compatible with the exisiting syntax, although the process of macro is later then AST parse so some dirty patch may be necessary to inform AST parser (like a pre-processor).

But the benefit is fancy:

``` crystal
class Math::Set
    operator def ∪(b)
    end
end
class Math::Symbolic::Function
    operator def self.∇(func)
        # gradient of a function
    end
end
a, b = Math::Set{1,2}, Math::Set{2,4}
f = Math::Symbolic::Function.new "x+x^2+y", {:x, :y}
# Currently, can only:
c = a.∪ b
g = Math::Symbolic::Function.∇ f
# With macro support:
c = a ∪ b
g = ∇f
# How fancy it is!
```

More flexible syntax and plenty of sugar, more easy for DSL and especially a way to an academic (scientific) programming language.

For future, one could use [digraph](http://vimcdoc.sourceforge.net/doc/digraph.html)(for Vim), [Icicles](https://www.emacswiki.org/emacs/Icicles)(for Emacs), to input the special Unicode character.

**Comment by straight-shoota** [comment]
Unary operator is simple:

```cr
def ∇(func)
  # ...
end

∇ f
```

The whitespace is required, because `∇f` would just be a single identificator. There's no way to turn that into `∇(f)` without losing full-unicode support for names.

Binary operators is more complicated and would require a change to the language. `a ∪ b` is parsed as `a(∪(b))` and fails because `a` is not a method. But theoretically, the compiler could try to rewrite this to `∪(a, b)` when `a` is not callable or doesn't receive any arguments. I'm not sure what else this might impact, though. And it's probably going to be difficult to properly handle cases where `a` is callable with optional arguments because you'd expect matching types etc.

All in all, I think it's unlikely that this can be implemented in a sane way. It would probably be nice, but honestly, just using prefix operators isn't that much of a downside. In math, it's used for functions anyway.

**Comment by bcardiff** [comment]
Knowing if a operator can be used in a prefix or infix way is coded in the compiler itself. As @straight-shoota show the expressions are parsed as call unless their are known operators.

The user is not allowed to define their operators. Only to define the meaning of the allowed ones.

I understand it why it could be nice and look good in certain use cases, but I wouldn't consider it in the mid term future.

**Comment by xqyww123** [comment]
Hey, I believe the work isn't too hard and trying to make some code. So, let's firstly talk about whether the feature is acceptable?

**Comment by bcardiff** [comment]
That would require a first pass to find the declared operators or force operators definition to come before any usage (which will end up in some edge cases).

Above that, operators might need to deal with precedence and types as you point out. But different libraries could decide to use them different.

This differences could come from different libraries. Due to the nature of how code is included/require, without module isolation on usage, this has no nice resolution.

The differences could also come from different types. And the parser wont know which rule to apply since it does not know the typing. So the operators should be either global which leads to the already mentioned conflict. Or the operators needs to be defined in a lexical scope, meaning that on every file the user want to use them, those declaration would need to be explicitly there.

You state that you only care about unicode chars, that might seems to reduce the conflict. But what if those names are wanted to be used as variables or function names: if `⊗`is a function `⊗ b` is fine and is `⊗(b)`, but if someone declare it as an operator, then is translated to `b.⊗`. So it's no longer possible to be certain how the code will be interpreted by the parser.

I only know Haskell as a language to allow a great freedom regarding operators, but for that to work other aspects of the language need to be aligned.

**Comment by xqyww123** [comment]
It's does a hard problem, as @bcardiff said. And after two weeks thinking, I find no good solution, so may temporary close the issue.
