### ISSUE TITLE
Crypto::Bcrypt::Password shadowing `==` operator

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#6339]
`Crypto::Bcrypt::Password#==` throws compilation error if equality is made with anything else than a String.
 
https://github.com/crystal-lang/crystal/blob/3c3d3e2b830e81de0aa39b7af0cd6f82f759c410/src/crypto/bcrypt/password.cr#L61

Shouldn't be instead `def ==(password : String)` ?

Note 1: Not sure of the security implication of the change, e.g. being able to forge an equality check, so I didn't do any PR

**Comment by anykeyh** [comment]
Also, a bit off-topic, but it takes around 1 sec (without --release flags) to compute BCrypt on my Macbook core i7 with default parameters. 

The number of turns by default sounds a bit conservative in my opinion, would definitely protect from brute force, but open your app to DDoS 😄

```crystal
time ruby -e 'require "bcrypt"; 10.times { BCrypt::Password.create("Hello") }'
time crystal eval 'require "crypto/bcrypt/password" 10.times { BCrypt::Password.create("Hello") }'
````

**Comment by straight-shoota** [comment]
Yes, `Bcrypt::Password#==` needs a type restriction to `String` in order to avoid shadowing the general `Reference#==(other)`.

About the performance issue: Crystal's Bcrypt implementation is written in pure Crystal. It's not totally optimized and - as declared in the [API docs](https://crystal-lang.org/api/0.25.1/Crypto/Bcrypt.html) - expected to be (currently) about 50% slower than mature C implementations (which are probably used by your Ruby example). This will certainly improve in the future.

Also note that you didn't configure any cost value, so the examples will use whichever default cost each implementation assigns. But unless using equal cost parameter, a performance comparison between different algorithms is total nonsense.
