### ISSUE TITLE
URI.parse parses strings that aren't URIs

### ISSUE THREAD

**Issue by HCLarsen** [crystal-lang/crystal#6437]
I just discovered this by complete fluke. I accidentally passed a string containing a number into the URI.parse method, and it didn't raise an error. 

My code was equivalent to:

`URI.parse("45.5")`

What returned was:

`@uri=#<URI:0x10eb4b7e0 @scheme=nil, @host=nil, @port=nil, @path="45.5", @query=nil, @user=nil, @password=nil, @fragment=nil, @opaque=nil>`

It doesn't make sense to successfully turn any string into a URI, so it seems like an error to me.

**Comment by asterite** [comment]
It's a valid URI. Both Ruby and Go parse it like that. It's just the path component (no scheme, host, etc.).

**Comment by HCLarsen** [comment]
According to the official spec for URIs, the scheme is required. If other languages are wrong, it doesn't automatically mean that Crystal should be as well.

https://tools.ietf.org/html/rfc3986#section-3

**Comment by straight-shoota** [comment]
This parser expects a URI reference, which is either an absolute URI including a scheme, or a relative URI (see [section 4.1](https://tools.ietf.org/html/rfc3986#section-4.2) of the same document).
You can verify whether a URI is absolute by testing if `#scheme` is non-nil. #6311 adds a predicate `#absolute?` for this.
Maybe there could be a parse method that only accepts absolute URIs and raises otherwise... But that's actually not that common and easy to implement yourself.

**Comment by HCLarsen** [comment]
I'm honestly surprised. I would have thought that parsing only absolute URIs would be the more common situation. But if you see this way as better, then I'll close the issue.

**Comment by straight-shoota** [comment]
The certainly depends on the problem domain.

In hypertext applications (which is probably the most important use cases of URI) it is pretty common to use relative URIs for internal links.

**Comment by HCLarsen** [comment]
I've only ever used external links in my programs. That's probably why I never thought of this.
