### ISSUE TITLE
Process.find_executable does not search in absolute nor relative paths

### ISSUE THREAD

**Issue by NIFR91** [crystal-lang/crystal#6506]
Hi, 

Is the expected behavior  that the function Process.find_executable does not find a program in the relative path?

From the documentation : 
> Searches an executable, checking for an absolute path, a path relative to pwd or absolute path, then eventually searching in directories declared in path.

## Example 

Working directory 
```text
.
├── program-a
├── program-a.cr
└── program-b.cr
``` 

where

```crystal 
# program-a
puts "Hello World"
```

and 

```crystal
# program-b
pp! Process.find_executable("program-a")
```

Running `program-b` yields `nil`, but given the description I expected  it to find the executable in the relative path. 

Note: Adding  `program-a` or the current directory  to `$PATH` gives the expected result. 

The other two cases are: 

```crystal 
Process.find_executable "/program-a"  #=> "/program-a"
```

and  

```crystal
Process.find_executable "dummy-dir/program-a" #=> "/current-path/dummy-dir/program-a"
```
in both examples the path is joined to the name and returned , but the file does not exist, I expected the output to be  `nil`.   The same output is given even if the current directory or `program-a` are 
present int `$PATH`

## Crystal 
```
Crystal 0.25.1 [b782738ff] (2018-06-27)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
## OS 
```
Linux azuna 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
```

**Comment by z64** [comment]
It will search a relative path if you give it one: `Process.find_executable("./program_a")`

It works the same as the shell:

```
➜  program-a
zsh: command not found: program-a
➜  ./program-a 
hello world
➜  mkdir foo
➜  cp program-a foo 
➜  foo/program-a 
hello world

**Comment by ysbaddaden** [comment]
1. You must specify `.` somewhere in your `PATH` environment variable for it to be searched, otherwise it won't.

2. The point of `find_executable` is to search an executable in PATH. You should check beforehand if your executable name is absolute then call `find_executable` to search for it if needed.

**Comment by straight-shoota** [comment]
This method simply resolves a program name by these rules:

1. If `name` is absolute, it is returned directly.
2. If `name` is a relative path consisting of at least two components (i.e. it includes a directory separator), it will be expanded in `Dir.current`.
3. Otherwise it searches in `PATH` if it can find a file matching this name.

No 3. is the only place where it checks if the file exists. This is the case only if the program name is only a basename with no hierarchical component.

As @z64 already pointed out, this is the same as a shell works.

So if you want to find the program in the current directory, you have to prefix the name with `./`. If you want to find the program and it *might* be in the current directory (but not reliably, it could be somewhere else in `PATH`), you have to add cwd (`.`) to the `PATH`.

No 1. and 2. (absolute and relative paths) specify an exact location of the program. There is only one possible result and such it is returned. Arguably it could ensure the file exists in this case too and return `nil` otherwise.
But then, knowing of the existence doesn't tell if the file is actually executable. And this would definitely be too much complexity for this method as it cannot trivially be determined, considering different user's access rights.

**Comment by NIFR91** [comment]
@straight-shoota  @ysbaddaden @z64 

Thank you for the detailed explanation of the function, I see the current implementation is the intended behavior. 

But the way I understand the documentation and name of the function it implies some check for the existence of the file. I support the idea of keeping the shell like notation but I think  to be consistent it should check the existence of the file and returning `nil` if it doesn't. 

#### Example 

Lets supposed I expect the executable in the current directory or in  `$PATH`

##### Working Tree 
```
.
├── foo
│   └── program-a
├── program-a.cr
└── program-b.cr
```

##### PATH
```
PATH=$PATH:/current-dir/foo/
```

##### Program-b

```crystal
puts 
puts "Current behaviour"
executable = (Process.find_executable("./program-a") || 
              Process.find_executable("program-a"))
if executable 
  Process.run(executable,
    error: Process::Redirect::Inherit, 
    output: Process::Redirect::Inherit)
end 

puts 
puts "Proposed behaviour"
executable = (find_executable("./program-a") || 
              find_executable("program-a"))
if executable 
  Process.run(executable,
    error: Process::Redirect::Inherit, 
    output: Process::Redirect::Inherit)
end 
```

##### Output 

```
Current behaviour
execvp: No such file or directory (Errno)
  from /usr/share/crystal/src/process.cr:392:7 in 'exec_internal'
  from /usr/share/crystal/src/process.cr:245:9 in 'initialize'
  from /usr/share/crystal/src/process.cr:207:3 in 'new'
  from /usr/share/crystal/src/process.cr:153:14 in 'run:error:output'
  from program-b.cr:29:3 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:104:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:93:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:133:3 in 'main'
  from __libc_start_main
  from _start
  from ???

Proposed behaviour
Hello World
```

I like the idea of executing the program only if it exists where i expected to be wihout 
manually checking it. But if you think it up to the user to check the existence I'll close the Issue.

**Comment by ysbaddaden** [comment]
The fact that the binary would exist when searching it in PATH is a side effect. You may check manually whether a path is absolute and check whether it exists then call find_executable for other cases, to avoid a double file exists check.
