### ISSUE TITLE
Unable to directly set array of subclass when declared as array of super

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/crystal#6507]
The following code:

```crystal
class Foo
end

class Bar < Foo
end

class Test
  @arr : Array(Foo)
  def initialize
    @arr = [Bar.new]
  end
end
  
t = Test.new
```

produces the following error:

`instance variable '@arr' of Test must be Array(Foo), not Array(Bar)`

I tried to find a similar issue or documentation but failed at both. Is this expected / desired behavior? My little bit of searching around seemed to imply that this shouldn't throw an error.

For example, if I change the `= [Bar.new]` to `<< Bar.new` there's no issue. Like so:

```crystal
class Foo
end

class Bar < Foo
end

class Test
  @arr = Array(Foo).new
  def initialize
    @arr << Bar.new
  end
end
  
t = Test.new
```

**Comment by straight-shoota** [comment]
This is expected. `Array(Foo)` and `Array(Bar)` are different types. They can't be interchangeable because they behave differently. Reading from `Array(Bar)` is the same as from `Array(Foo)`, it will always return a `Foo` (because `Bar` inherits from that). But writing to `Array(Bar)` it only accepts `Bar`, not any `Foo`.

See #3803 for more details and a discussion about alternatives.

Given that this example is about an array literal, it might be considered to apply an automatic cast to `Array(Foo)` in that case. But I don't think that would be a good idea. Just add `of Foo` after the literal and you're good to go.

**Comment by straight-shoota** [comment]
Yeah, that'd be great. 

I think it would better fit into the *Inheritance* section, as it is not specific to arrays. Maybe a reference from the array docs would be fine.

**Comment by KCErb** [comment]
I'll go ahead and close this in favor of the PR over on the crystal-book repo. Thanks again :)
