### ISSUE TITLE
method naming conventions

### ISSUE THREAD

**Issue by Vikaton** [crystal-lang/crystal#651]
I have seen a few methods in Crystal that are borrowed from Ruby, but some of the method names are unnecessarily short/unreadable

So far I have seen only 2, `String.tr()` and `Int32.chr`

For those 2, .tr can be .replace or something a bit more recognizable and .chr should be .char, so it can be much more readable.

This is just a suggestion, and have only found 2 methods so far in the course of writing my code.

**Comment by jhass** [comment]
I think `tr` is actually a well known name used across many languages, most prominently it's present in the Gnu coreutils.

**Comment by Vikaton** [comment]
method names can stay as they are if you see that they have good reason for their shotnames. if what you said is true than sure. Though I don't see why .char is .chr.

**Comment by waterlink** [comment]
Both methods (`tr` and `chr`) are available in Ruby ;)

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-05-11 1:53 GMT+03:00 Unnamed <notifications@github.com>:

**Comment by Vikaton** [comment]
Yes I understand that, but I'm doing this in Crystal's perspective.

These are just slight method naming conventions that can make Crystal better in my opinion for those who don't code in Ruby :)

In a situation like .chr, I would rather have it readable then making it as short as possible

**Comment by asterite** [comment]
I think at this point I'd like to preverse as much compatibility with Ruby as possible. In fact, maybe using `includes?` instead of `include?` was a mistake (we still have time to change this). If someone knows Ruby and comes to Crystal, they already know most of the names. If not, they don't know any name so learning "tr" vs. "replace" or "chr" vs. "char", or "includes?" vs. "include?" is the same for them. So preserving Ruby names should be something to think about.

On the other hand, I never really liked `attr_accessor`, `attr_reader` and `attr_writer`. In every other language they are called property, getter and setter.

@Vikaton Would you also change `puts` and `gets` to more readable, but probably longer, names?

**Comment by asterite** [comment]
There's also the thing that `if "foo".includes?("o")` reads like English, but `if "foo".include?("o")` reads like Tarzan. On the other hand `array.includes?` reads well too, but the variable is probably named `elements` or `children` so `elements.includes?` reads wrong. And having aliases for these is not a good thing...

But then, I'm not sure a lot of Ruby code can be ported to Crystal, most of the time you end up writing lots of code yourself, and once your mind knows you are programming in this language you don't make those spelling mistakes.

There's also `readline`, which should probably be `read_line`... So many names!

**Comment by Vikaton** [comment]
@asterite there is not need for the `puts` and `gets` switch because we have the other ways of printing, though maybe not in the same implementation.

getter and setter are fine, but it's really up to the community and what they think.

**Comment by waterlink** [comment]
How about `#chr` => `#to_char` ?

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-05-11 2:41 GMT+03:00 Unnamed <notifications@github.com>:

**Comment by Vikaton** [comment]
@waterlink That sounds good, anything to make it more readable than .chr. and this goes for any other method name.

**Comment by waterlink** [comment]
And `#tr` is more like not a `#replace`, but a `translate`

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-05-11 3:44 GMT+03:00 Unnamed <notifications@github.com>:

**Comment by asterite** [comment]
`man tr`

**Comment by Vikaton** [comment]
What's that?

**Comment by kirbyfan64** [comment]
@Vikaton `tr` is a UNIX command that replaces single characters.

**Comment by ysbaddaden** [comment]
@asterite going back and forth from Crystal to Ruby I always mistype `includes?` vs `include?` for the wrong language. Same for the `responds_to?` vs `respond_to?`. It would be nice to harmonize.

In Ruby I feel like there is a difference between wrapped C functions vs Ruby methods: the former retains the original names, whereas the Ruby methods are more explicit, or happen to alias the wrapped C functions.

**Comment by Vikaton** [comment]
I was wondering what `man tr` meant

**Comment by strcmp** [comment]
I think he just meant read the manual page for that command.
You can do it online too: http://linux.die.net/man/1/tr

**Comment by kirbyfan64** [comment]
@Vikaton Typing that in a UNIX shell gives you the manual page for `tr`. @asterite was using it to say to read the manual page. They have them online, too, like @strcmp; there's another one [here](http://unixhelp.ed.ac.uk/CGI/man-cgi?tr+1).

**Comment by waterlink** [comment]
`man` is the *nix command for reading manuals for other *nix commands.
Command `man tr` will show such manual for builtin `tr` *nix command (which
effectively does, what `String#tr` does, but more powerful of course).

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-05-12 22:25 GMT+03:00 strcmp <notifications@github.com>:

**Comment by jhass** [comment]
`man man`

**Comment by asterite** [comment]
I was actually surprised to find that `tr` was a unix command, that's why I put `man tr` here. I guess that's where Ruby took the name from...

**Comment by asterite** [comment]
@jhass gotta love recursion :-P

**Comment by Vikaton** [comment]
Oh, Thanks

**Comment by Vikaton** [comment]
What do you think of changing `chr` to `char`

**Comment by dziulius** [comment]
Why can't there be both? There is detect and find, collect and map. So if you made aliases for tr and chr, everyone would be happy.

**Comment by Vikaton** [comment]
That sounds like a good idea

**Comment by YaroslavShapoval** [comment]
I don't think that aliases are the best part of Ruby. Like [Erik Michaels-Ober said](http://rubyc.eu/posts/24), language can be better if syntax will be more consistent. I think some aliases can be confusing, especially for beginners.

At the same time, I think that methods should have clear and short names.
Both words - 'replace' and 'char' aren't so long, but with those names, methods look more understandable, what cannot be said about the 'tr' and 'chr'.

However, I think that some aliases is better to save or add, but only those that will not able be confusing to developers.  For example, 'include?' and 'uncludes?', 'responds_to?' and 'respond_to?'. The presence of the two options will only help.

**Comment by Vikaton** [comment]
+1 ^

**Comment by asterite** [comment]
@YaroslavShapoval +1

I don't like aliases either. Yes, it seems nice at first that you can choose "map" or "collect", whichever you prefer. But say you prefer "map" and work in a team and someone else prefers "collect". Then the project starts having these two names all over and there's no consistency. And then you find a piece of code with "detect" and wonder "what's that?".

In the end, you have to learn **all** variants of the API, regardless of what you prefer. And it's better if you have to keep less things in your mind.

As for `tr` and `chr`, I don't know. Instead of `chr` it should be something like `to_char` or `to_c`, but the later means "to Complex" in Ruby (not that it's really important). But what about "puts"? That's cryptic too. Or "gets". Should we rename those?

I don't think these names matter much, they are so frequently used that you learn them quickly.

**Comment by YaroslavShapoval** [comment]
I think that methods like 'puts' and 'gets' meet not simply often, they start meeting from the first steps of learning language, from the first program: "puts 'Hello, world!'".

Moreover, I think that a change of 'puts' on something else can confuse those developers who will come from Ruby. After all, the Crystal's description has the saying: "Have the same syntax as Ruby, or at least as similar as possible." And if even "puts 'Hello, world!'" won't be executed, it can frighten off developers.

In view of the above, I think that making changes in the syntax need to be cautious, and it would be nice if all the changes have been listed anywhere.

**Comment by PragTob** [comment]
As far as I can tell crystal made some good choices :) I like `includes?` and `responds_to?` for instance :)

I also think that the flurry of aliases in Ruby isn't always helping - e.g. I'm happy just having `map`/`find` instead of `collect`/`detect` :)

**Comment by ozra** [comment]
Abbreviations and shortened names are great for things that are used all the time. I know `tr` from Linux and Perl, but how often is it used, and how many others do _not_ get the historic connection? "translate" would be better in that case.

After some time now with crystal I must say I'm starting to dislike the `is_a?` methods (ending with question mark). It would be way more logical extending the `if` expression with the _ternary_ syntax mixed in (as an optional then/else delimiter syntax): `foo = if bar.is_a(Baz) ? 1 : 0`. That would make ternary op more clear (possibly helping with the nil/? issue, if that would become interesting again), give `if` an alternative, logical, way of making one-statement blocks and get the question mark in a better place. 

But, yes, I know, Crystal has luggage to drag; Ruby. That's good and bad. I wish crystal could stick with _the good parts_ of the Ruby _syntax_, and re-invent on all the rest. But in any event, I'm happy that Crystal exists because it rocks, so I'll just swallow these small flies.

**Comment by PragTob** [comment]
Hey @ozra - at least for me so far crystal sticks to the good parts of Ruby :)

The `?` mark for query methods that return booleans are rather a convention other than the ones in the language. If you REALLY want `is_a` to you can probably do:

```
class Object
  alias_method :is_a?, :is_a # not sure what the order of arguments in crystal is :)
end
```

**Comment by ozra** [comment]
@PragTob - thanks for the tip! I will stick to the way of the Crystal community consensus for most everything anyway, even though I might _wish_ and _hope_ for something different in some regards, _the pro of easier sharing takes precedence_ :), and I do realize Ruby is lapidary engraved in the Crystal movement. Though I do use dashes in all identifiers ;-)

**Comment by freecellf** [comment]
+1 from a non-rubyist

**Comment by sergey-kucher** [comment]
+1 from rubyist
- for
  > Abbreviations and shortened names are great for things that are used all the time

  So `#chr` better to be `#to_char`, `#tr` -> `#translate` (or something else)

- for **not** having aliases like `#map`/`#collect`, `#find`/`#detect`
- for having aliases like `#include?`/`#includes?`, `#respond_to?`/`#responds_to?`

**Comment by asterite** [comment]
This issue is very general, so I'll close this. Please open individual issue for method renames that you'd like to happen.
