### ISSUE TITLE
Weird error related to nested static arrays

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6540]
```crystal
xs = uninitialized StaticArray(StaticArray(Int32, 2), 2)
xs[0] = uninitialized StaticArray(Int32, 2)
```

> Error in line 2: undefined method 'uninitialized'

**Comment by straight-shoota** [comment]
`uninitialized` only works in a declaration directly assigning a local variable.

Your second line is completely useless, though, even if it worked. `x[0]` is already implicitly typed as `StaticArray(Int32, 2)` there is no point to declaring it separately.

Judging from that usage I wonder if you completely understand the concept of `uninitialized` and if not, you should better stay away from it. It is a pretty unsafe and low-level feature of the language and certainly not intended for everyday work. I'd guess it's pretty likely that you shouldn't use it (unless you're working with C bindings) - otherwise you should know *how* to use it.
