### ISSUE TITLE
Array#sort requires < and <= methods, not <=>

### ISSUE THREAD

**Issue by ghost** [crystal-lang/crystal#6608]
According to the docs for [Array#sort](https://crystal-lang.org/api/0.26.0/Array.html#sort%3AArray%28T%29-instance-method), it:

> Returns a new array with all elements sorted based on the return value of their comparison method #<=>

However, `Array#sort` only uses the `#<` and `#<=` methods; it does not use the `#<=>` method.

## With <=>

```crystal
class Foo
  property :number

  def initialize(@number : Int32)
  end

  def <=>(other : Foo)
    self.number <=> other.number
  end
end

arr = [Foo.new(10), Foo.new(20), Foo.new(5), Foo.new(15)]
arr.sort!
pp arr.map(&.number)
```

Compiling yields:

>in /usr/share/crystal/src/array.cr:1872: undefined method '<' for Foo
>
>      c -= 1 if a[c] < a[c - 1]
>                     ^

## With < and <=

```crystal
class Foo
  property :number

  def initialize(@number : Int32)
  end
  
  def <(other : Foo) 
    self.number < other.number
  end

  def <=(other : Foo)
    self.number <= other.number
  end
end

arr = [Foo.new(10), Foo.new(20), Foo.new(5), Foo.new(15)]
arr.sort!
pp arr.map(&.number)
```

Running this code yields:

> [5, 10, 15, 20]

## System Information

Operating System
> Ubuntu 18.04.1 LTS

crystal -v
> Crystal 0.26.0 [eeb53c506] (2018-08-09)
> 
> LLVM: 4.0.0
> Default target: x86_64-unknown-linux-gnu

**Comment by asterite** [comment]
I have a branch will all of these changes.

The only problem is that `Array#sort(&block)` becomes about 3 times slower because it must now account for the block returning `nil` (the non-block version performance remains the same). I don't know if this is acceptable. 

Maybe we can just change `Array` sorting methods to use `<=>`, but forget about the possibility of it returning `nil`... though of course you won't be able to `sort` something that is partial comparable, like `Location` in the compiler.

I usually prefer a language that behaves correctly even if that means sacrificing a bit of performance (Ruby <3). Our `sort` is pretty fast, so loosing a bit of that performance might not be that bad). Sorting numbers where one of the values is `NaN` should probably raise, in the same way that overflow should raise instead of silently behaving incorrectly.

Thoughts?

**Comment by asterite** [comment]
Actually, I have an idea to make it faster when nil can't be returned. I'll try it later.

**Comment by asterite** [comment]
Cool, I managed to fix the performance problem. Well... for floats it'll be slower because of the `NaN` check, but for ints and generally things where comparison of `<=>` doesn't return `nil` it performs the same. I'll send a PR soon.

**Comment by rdp** [comment]
Nice.  I'm a little late to the party but... could `Float#<=>` throw an ArgumentError for NaN (itself)?  Is the nil useful somewhere else I'm not aware of?

**Comment by rdp** [comment]
Oh wait I get it it's so that `NaN <=> NaN` can still return that they're "equal" (0 in this case).  That's OK.  Another option might be the java route where NaN gets sorted "as the highest number" (after positive infinity LOL): https://discuss.python.org/t/nan-breaks-min-max-and-sorting-functions-a-solution/2868/19 FWIW :)

**Comment by asterite** [comment]
It's not because `NaN <=> NaN` returns 0, it actually returns `nil` in both Ruby and Crystal. NaN is simply not comparable and not equal to anything else.

The reason `nil` is returned is so that `<=>` is only operator used for comparison, and it provides for partial and complete orders.
