### ISSUE TITLE
Initializing variable as  typeof at runtime

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#6670]
I want to be able at runtime to initialize some variables types as same as  ``input``value to method, where ``input`` is an integer that can be ``Int32|64, UInt32|64, or BigInt``

Ex
```
def methodx (end_num)
   k = 0.as(typeof(end_num))
   ...
end
```
But I get this error

```
in primesutilstesty1a.cr:257: can't cast Int32 to Int64

          k = 0.as(typeof(end_num))
```
According to docs -- https://crystal-lang.org/docs/syntax_and_semantics/typeof.html -- shouldn't this work?

**Comment by straight-shoota** [comment]
`typeof` works as inspected, but `as` doesn't change the inherent datatype, it just tries to treat the value as that type but the compiler complains if this is not possible. You can't treat an `Int32` as an `Int64` because they're completely different types with different memory layout.  See https://crystal-lang.org/docs/syntax_and_semantics/as.html

For your use case, you probably need to convert the value from one type to the other.  If this is just about converting number types, you use the regular contstructors: `typeof(end_num).new(0)`. Every number type even has a `.zero` method, so your example could just be `typeof(end_num).zero`.

All this obviously doesn't work if `end_num` is a union type.

**Comment by asterite** [comment]
If it's a union you can do `end_enum.class.zero`

**Comment by jzakiya** [comment]
Yes, this works: ``k = typeof(end_num).zero``

Thanks :-)

May I recommend including this use of ``typeof`` in the documentation for that section, as it would have instructed me on the proper way to use it initially.

**Comment by asterite** [comment]
@jzakiya It's probably a good idea. Please send a PR to https://github.com/crystal-lang/crystal-book . Thanks!
