### ISSUE TITLE
Time stringification issues

### ISSUE THREAD

**Issue by TPei** [crystal-lang/crystal#6708]
When stringifying a `Time` and then reparsing it, I expect to get an identical `Time` object, however there are some differences:

```
time = Time.utc_now
time_string = time.to_s("%FT%X%z")
reparsed_time = Time.parse_utc(time_string, "%FT%X%z")

puts time.to_s
puts time_string
puts reparsed_time.to_s

2018-09-12 00:52:39 UTC
2018-09-12T00:52:39+0000
2018-09-12 00:52:39 +00:00
```

The issue seems to be that the time zone differs slightly:
```
puts time.zone => Time::Location::Zone(UTC +00:00 (0s) STD)
puts reparsed_time.zone =>Time::Location::Zone(+00:00 (0s) STD)
```

That's weird because both
https://github.com/crystal-lang/crystal/blob/master/src/time.cr#L1002
and 
https://github.com/crystal-lang/crystal/blob/master/src/time.cr#L352
set `Location::UTC` as time zone.

https://play.crystal-lang.org/#/r/4y4e

¯\\_(ツ)_/¯

All the best,
Thomas

**Comment by straight-shoota** [comment]
From [Time#parse_utc](https://crystal-lang.org/api/master/Time.html#parse_utc%28time%3AString%2Cpattern%3AString%29%3ATime-class-method):

> Time::Location::UTC will only be used as #location if the formatted time does not contain any time zone information. The return value can't be assumed to be a UTC time (this can be achieved by calling #to_utc).

Your formatted time string contains a numerical zone offset, so that will be used to create a fixed zone location with that offset. `UTC` would only be used if the string does not contain any time zone information.
In order to ensure the Time instance is in UTC, you need to call `#to_utc` or leave out the time zone information (`%z`).

I understand that this might be surprising and you would expect the method `parse_utc` to always return `UTC`. Even more because the offset is actually 00:00 and equal to UTC.

The method could theoretically always call `#to_utc` to enforce the location but that would make it behave differently than the other parse methods which is also unexpected.
Maybe a small improvement could be to replace a `00:00` offset with UTC. This might even be generally a good idea when parsing a fixed offset.

**Comment by straight-shoota** [comment]
Btw. your time instances will also differ by nanoseconds, because `Tike.utc_now` has nanosecond precision but they are not included in the string format.
