### ISSUE TITLE
Vagrantfile

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#6722]
The Vagrantfile is a mess. I tried to use it to test the sockets specs on different systems, but there are a lot of issues:

* The latest LTS Ubuntu Bionic is missing.
* FreeBSD 11 is missing (#4802) and the provisioning for FreeBSD is error-prone. There is a year-old stale PR #4803 with details.
* Ubuntu Xenial uses an outdated, custom build LLVM-3.5 even if already comes with 3.8.
* Ubuntu uses the setup script to install crystal, Debian doesn't. For no apparent reason.
* There are issues with integrating the crystal source code which should ideally be shared folder, not a copy. See https://github.com/crystal-lang/crystal/pull/4803#discussion_r131628383 for details.
* OpenBSD is entirely missing. Would be great to add it, considering it's a tier 2 platform.
* Alpine Linux with musl would also be great to add.
* The selection of Linux distributions is a bit strange. Debian and Ubuntu are both present but they are actually very similar. Relevant differences are mostly regarding available packages and versions. Other distributions such as CentOS, Arch, Gentoo are entirely missing. I'm not saying they should all be added, it just strikes me that there are 10 different Debian/Ubuntu releases (and not even including the latest LTS) and no other distributions.

I'm just wondering about whether the vagrant file is entirely supported, then these issues need to be addressed to be useful in any way. Or maybe it should just be removed and developers use their own VM specs (or separately maintained Vagrantfile). WDYT?

**Comment by bcardiff** [comment]
I personally don't use the Vagrant file as is.

I think they should match the per-distro instructions to get a development environment for the latest version of the compiler.

The vagrant file has evolved from been the way to test the initial ruby written compiler, to cross compile, and has ~~survived~~ aged with the changes in infrastructure.

I would not jump to add every single distro latest version, but rather to have the supported ones by the official packages. Maybe we can have a `Vagrantfile.community` where non official ones can tracked.

The matrix for supporting different llvm version is still relevant (yet not enforced fully by the CI)

I see no problem with using local files directly instead of cloning the git repo as it is today. Users will need to clear binaries when jumping between machines. I don't recall if there was a specific reason to do the clone, but it comes from the [very first comit](https://github.com/crystal-lang/crystal/commit/3b6e748fda32bf3cbcc1c8491c6c03d59b1fc337) of the file.

**Comment by straight-shoota** [comment]
Closing, Vagrantfile is not used anymore #10033
