### ISSUE TITLE
Can we provision a Discourse instance for better forums and conversations?

### ISSUE THREAD

**Issue by sergiotapia** [crystal-lang/crystal#6749]
This isn't really a bug, just a general quality-of-life improvement for the ecosystem as a whole.

Some negatives from Google Groups:

- You need a Google account. Some people don't want to create a Google account. In my case I'm banned from some Google services because I uploaded some old cartoons to youtube. Not old enough and I was banned from their platform and that limits my other usage on the entire Google ecosystem.
- Hard to find notifications in fluent convos.
- No way to see trending topics or a weekly recap of interesting things.

Some positives of Discourse:

- Already proven for open source languages, like Elixir. https://elixirforum.com/
- Modern UI, younger people will feel at home.
- Notifications in a familiar UX.
- Trending topics by day, week, month.
- Tagging by topics.
- and more

---

What do you guys think?

**Comment by luislavena** [comment]
Chipping in some thoughts: from my perspective is not about the possibility, but the long term maintainability of the decisions made.

While there are folks sponsoring development of the language, there are not dedicated resources to perform system administration or infrastructure work, which will be necessary to deploy and maintain a Discourse installation.

Using your example, maintenance of Elixir forums is made possible by their sponsors, and they clearly advertise the platform for their visibility:

https://sponsors.elixirforum.com/info/

That is why also Discourse sells up hosting plans on their own:

https://payments.discourse.org/pricing

There is one example of Community-based install ($100) and then hosting fees ($5/month) in of self-hosted, but still there is no maintenance included.

To give another example: RubyGems service (https://rubygems.org) is divided in two: Ruby Central pays for the hosting bills (excluding the gem download which is sponsored by Fastly) and Ruby Together pays developers working on infrastructure maintenance (not to mention the application code maintenance, but that is separate).

I personally like the proposal, but the decision needs to be made with a long term and sustainable plan in mind before committing, specially since there maintenance hours associated with this.

Cheers.

**Comment by Sija** [comment]
@straight-shoota why? that's an issue - regarding community, not technical one but still. I'm sure that many people active here are not subscribed to mailinglist (and probably vice-versa), so perhaps this could be cross-posted to increase visibility.

**Comment by sergiotapia** [comment]
@straight-shoota I didn't want the conversation to get lost in the spam.

![image](https://user-images.githubusercontent.com/686715/45846946-4bd51580-bcf7-11e8-8ebf-3cb01e636d8c.png)

**Comment by girng** [comment]
i saw @RX14 tease us with the new forum on gitter. am excited

**Comment by sergiotapia** [comment]
That's great news @RX14

**Comment by RX14** [comment]
Just launched! https://forum.crystal-lang.org/

**Comment by sergiotapia** [comment]
Hell to the yes!
