### ISSUE TITLE
Type Invariance

### ISSUE THREAD

**Issue by ttowncompiled** [crystal-lang/crystal#6792]
Would it be possible for Crystal to enforce the Liskov Substitution principle by making sub-types which override their super-type Invariant to their super-type? This wouldn't apply to overloads or abstract methods. This would only apply to subtypes which override a defined field or a defined method.

The Liskov Substitution Principle is extremely important for software development. Especially in large projects. I believe that this would make Crystal the ideal OOP language.

I can see this being implemented in a number of ways:

1. Disallow overrides of non-abstract methods and overrides of defined fields. This would require that developers have to explicitly define the Composition of the two types without using the sub-types relationship.

2. Allow overrides, but break the sub-type relationship. Rather, duplicate the super-type and override its methods. The duplicate and the original super-type should be Invariant.

I recognize that this feature would be difficult to implement, but it would be an extremely useful feature to have. Additionally, by implementing the second solution, you would also be solving the second problem of Composition: namely that Composed types have to wrap re-used methods. With this solution, the duplicate type will duplicate methods and fields so the developer only has to write the overriden methods when using Composition.

There's probably another better solution, but these were two naive solutions that came to mind.

WDYT?

**Comment by jwoertink** [comment]
Wouldn't this just be a design pattern that the individual programmers would follow? I never follow LSP, so if crystal enforced it, this would make using crystal a lot harder for me. Any framework that currently violates the pattern would possibly need re-architecting. That's a big "if" because I don't know if any of them do or not; however, if they do, then that throws a huge wrench in to the progress of crystal.

**Comment by LesterCano** [comment]
Hello,

I modified some instances of the `firstNonWhite` variable, as it could possible have a racist undertone. "First non white person of whom?"

Also changed it to be more expressive for what that variable is actually doing (and less oppressive).

Since @mverzilli thinks it's okay to close my PR without any justification. You will get spammed. Enjoy!

**Comment by straight-shoota** [comment]
Enforcing this for all Crystal users doesn't seem like something that would be appreciated in the community.
The design pattern can be used without compiler support. It should even be possible to support some kind of enforcement using the macro language in user code (maybe a shard idea?). 
I don't think there is anything actionable here.
