### ISSUE TITLE
Compiler spec failing on travis-ci because of insufficient memory

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#6961]
I noticed a lot of CI builds failing on travis-ci because they can't allocate enough memory at some point.
 
* https://travis-ci.org/crystal-lang/crystal/jobs/443615214
* https://travis-ci.org/crystal-lang/crystal/jobs/442935761
* https://travis-ci.org/crystal-lang/crystal/jobs/441646668
* https://travis-ci.org/crystal-lang/crystal/jobs/443615214

The failure is always `fork: Cannot allocate memory (Errno)` in spec `Semantic: macro allows declaring class with macro expression` (https://github.com/crystal-lang/crystal/blob/master/spec/compiler/semantic/macro_spec.cr#L569).

This really doesn't seem to make any sense. It doesn't always happen, but it comes up from time to time. 

According to [travis docs](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) the machines running with Ubuntu Trusty on GCE have 7.5 GB of memory available. That should be plenty for compiling the std and compiler specs - even in one go.

**Comment by asterite** [comment]
I think it's the only spec that compiles a program that executes a macro that ends up invoking a shell command. I don't know if that requires more memory for some reason or what...

Also, I think right now we are calling `make crystal std_spec compiler_spec docs`, and for example `make std_spec` will execute `crystal spec/compiler_spec.cr` which will compile that and start executing the specs while still having all the memory occupied because of the compile process. So maybe we should split that into `crystal build spec/compiler_spec.cr && ./compiler_spec`.

**Comment by jhass** [comment]
Maybe we somehow blow up memory sharing? That is after a fork the OS lets the child use the parents memory until it tries to write to it, at that point its copied. if we have a 2GB compiler process forking three times that's easily 6GB, if we fail to free unneeded memory after fork.

**Comment by bcardiff** [comment]
@asterite the Makefile performs build and run in a different stages already `$(O)/std_spec` vs `std_spec: $(O)/std_spec` targets

**Comment by straight-shoota** [comment]
Even in one step, it shouldn't fill 7,5 GB.

**Comment by straight-shoota** [comment]
This happens on circle-ci as well which should have 8 GB RAM: https://circleci.com/gh/crystal-lang/crystal/16121

**Comment by sdogruyol** [comment]
Can we close this now that #6968 #7263 merged?

**Comment by straight-shoota** [comment]
#6968 is probably completely unrelated. And #7263 only disables the very frequently failing 32-bit builds on travis.

This issue is about OOM failures in 64-bit builds on both travis and circle.

**Comment by straight-shoota** [comment]
OOM failures keep coming even after #6962: https://circleci.com/gh/crystal-lang/crystal/20381

**Comment by straight-shoota** [comment]
Resolved by #10078

**Comment by bo-tato** [comment]
(commenting on closed issue just cause I ran into a similar problem and found this searching) I ran out of memory running the compiler tests (I have 8GB) and I think the issue was as jhass said, that the compiler process forks and using a bunch of memory for each process. The memory usage of crystal would go up to about 4GB, then the compiler would fork and it'd be fine for a minute or so, and then I imagine as jhass says the child uses the parents' memory until it writes to it and then it's copied. A bit after forking it would start swapping like crazy and hang. Then I ran make with `threads=2` and I guess then it uses threads rather than forking, and the memory usage stayed around 4GB and worked fine.
