### ISSUE TITLE
Frustrating Time::Span initializers

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7143]
I've noticed that `Time::Span` has following initializers:

```crystal
def self.new(days : Int, hours : Int, minutes : Int, seconds : Int, nanoseconds : Int = 0)
def self.new(hours : Int, minutes : Int, seconds : Int)
def self.new(*, seconds : Int, nanoseconds : Int)
def self.new(*, nanoseconds : Int)
```

First of all, `milliseconds` and `microseconds` arguments are missing. Secondly, there is only a `nanoseconds` argument which has default value.

Wouldn't it be better to have a single initializer with all default values?

```crystal
def initialize(*, days : Int = 0, hours : Int = 0, minutes : Int = 0, seconds :  Int = 0, milliseconds : Int = 0, microseconds : Int = 0, nanoseconds : Int = 0)
```

**Comment by straight-shoota** [comment]
The initializer doesn't need individual fields for milli-, nano- and microseconds because they're simple decimal unit prefixes. The relations between days, hours, minutes, seconds are more complicated and they are the common units used for calendrical representation of a time duration. Theoretically, `nanoseconds` could be expressed as a fraction of `seconds`, but that's not practical (because you can't use `Int`).

If adding any additional constructors, it should be alternatives for `milliseconds`/`microseconds` which delegate to the appropriate `nanosecond` value:
```cr
def self.new(days : Int, hours : Int, minutes : Int, seconds : Int, *, milliseconds : Int)
def self.new(days : Int, hours : Int, minutes : Int, seconds : Int, *, microseconds : Int)
```
But I don't see a strong use case for this. We generally don't provide such overloads just for different prefixes.

**Comment by straight-shoota** [comment]
Closing. The lack of activity suggests the current state is fine.
