### ISSUE TITLE
`to_s` vs `inspect` when printing arrays

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/crystal#7258]
It [looks like](https://github.com/crystal-lang/crystal/blob/c9d1eef8fde5c7a03a029d64c8483ed7b4f2fe86/src/array.cr#L1679) Crystal calls `inspect` and not `to_s` when printing an array. This isn't Ruby behavior (I believe) and caught me off guard so I just want to check that this is expected behavior in Crystal. If so I can head over to the docs and try to add something helpful. Otherwise ... I can put together a PR calling `to_s` instead?

Example:
```crystal
class A
  def initialize(@a="foo")
  end
  def to_s(io)
    io << "<#{@a}>"
  end

  # uncomment this to make `puts` work in an array too  
  # def inspect(io)
  #   to_s(io)
  # end
end

a = A.new
b = A.new("bar")
puts a # => <foo>
puts b # => <bar>
puts [a, b] # => [#<A:0x10cf57ca0 @a="foo">, #<A:0x10cf57920 @a="bar">]
```

**Comment by asterite** [comment]
> This isn't Ruby behavior (I believe)

It is :-)

**Comment by asterite** [comment]
However, `puts` in Ruby has a special meaning for arrays: it will print each item one by one using `to_s`. Because this is a special behavior and we don't like those things in Crystal, `puts` just calls `to_s` on the given argument(s), and `Array#to_s` calls `inspect` on each element, and this is exactly like Ruby.

**Comment by KCErb** [comment]
Thanks for the quick answer :)

But I'm still a little confused. You said that in ruby it calls `to_s` on each item in the array and in Crystal it calls `inspect` on each item. I see how from a Crystal perspective Ruby got the wires crossed and you're uncrossing them, but doesn't that mean the behavior is different between the two languages?

At any rate, I'm happy to close this, thanks for a very nice explanation @asterite, you've made it clear why the Crystal way uses `inspect` when `puts`ing an array of objects.

**Comment by asterite** [comment]
@KCErb What I meant is this:

```crystal
puts ["foo", "bar"]
```

behaves differently in Ruby and Crystal. In Ruby no method is invoked on Array, there's a hardcoded, special logic that says "if `puts` receives an array, then we print each element invoking `to_s` on it, and then print a newline". If it's any other type then `to_s` is invoked on it.

Crystal **doesn't** use `inspect` when doing `puts array`. It invokes `to_s` on the Array. It does this regardless of the type being passed. Then, `Array#to_s` is implementing by invoking `inspect` on each of the elements.

The best way to try this out is to avoid doing `puts array`. Try this:

```ruby
class A
  def initialize(a = "foo")
    @a = a
  end

  def to_s
    "<#{@a}>"
  end
end

a = A.new
b = A.new("bar")
puts a.to_s
puts b.to_s
puts [a, b].to_s
```

Run the above code with Ruby and Crystal, you'll get a similar output: `to_s` isn't used when invoking `to_s` on Array, `inspect` is used. The reason is that if `to_s` is used and the array contains strings, doing:

```crystal
puts ["hello, world", "foo", "bar"].to_s
```

would print this:

```
[hello, world, foo, bar]
```

and like that it's not clear how many elements are there in the array.
