### ISSUE TITLE
Class: redefining the `name` property affects the behavior of `to_s`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7292]
```Crystal
abstract class Command
  class_getter name : String = ""
end

class CreateUserCommand < Command
end


pp {{Command.subclasses}} # =. []
```

However removing the `class_getter name : String = ""` causes it to work fine.

https://play.crystal-lang.org/#/r/5ypk/edit

**Comment by asterite** [comment]
It's not that it's empty, if you invoke `size` on it you'll see the number 1. It's just that you are defining the name to be empty, and for some reason it doesn't show up as `""` but as an empty value. And that's because `Class#inspect(io)` just delegates to `to_s(io)`, which is the class name, and that's empty. Maybe it's fine.

**Comment by Blacksmoke16** [comment]
Ohhhhh.  TIL that `name` class var is actually something used internally?

**Comment by asterite** [comment]
It's a method that gives you the name of the class, and it's used in the string representation. With that class getter you was overwriting it :-)

**Comment by straight-shoota** [comment]
@asterite Is that really expected behaviour that user code can override class names?

**Comment by asterite** [comment]
@straight-shoota You can do it in Ruby :-)

That said, I just tried it in Ruby and if you override the `name` method it doesn't change the behavior of `to_s`, so we should probably fix that.
