### ISSUE TITLE
signal traps and unhandled SIGCHLD

### ISSUE THREAD

**Issue by stronny** [crystal-lang/crystal#7336]
```
#!/usr/bin/env crystal
child = Process.new "sleep", ["60"]
spawn { p child.wait }
Signal::INT.trap { exit 0 }
at_exit {
  child.kill
p :before
  sleep 1
p :after
}

sleep 10
raise "boom"
```

If left to run (as expected):
```
$ ./test.rb
:before
#<Process::Status:0x7fd86638cfd0 @exit_status=15>
:after
Unhandled exception: boom (Exception)
```

With `^C` pressed:
```
$ ./test.rb
^C:before
:after
```

As far as I was able to gather this happens because trap handlers are run signal-free, however it's not obvious that a call to `exit` will pull at_exit to its context.

If this is not a bug, please tell me a way to make sure the subprocess is reliably killed and reaped before the master dies. I've spent half a day to figure this all out and I'm all out of ideas short of taking back SIGCHLD from the event loop if it's even possible and safe.

**Comment by ysbaddaden** [comment]
Kill & wait for the subprocess in the signal trap?

**Comment by stronny** [comment]
That wouldn't work. `child.wait` inside the trap handler would block forever, because SIGCHLD would only be handled after the signal trap handler returns. I've tested this.

**Comment by RX14** [comment]
I think this should be a `spawn process(...)` here: https://github.com/crystal-lang/crystal/blob/34619bfa7225a7bd16a2592d40e910da6802296c/src/signal.cr#L202

Otherwise you can easily block the signal handling loop with user-code, and I don't think that's a good semantic.

**Comment by stronny** [comment]
I was able to raise inside the trap and get out this way, however my
overall questions would be these two:

* does it make sense that at_exit behaves differently depending on whether
you exit from a trap or not?
* wouldn't it be a better way to do away with traps completely and instead
provide a top level channel SIGNALS for the program to read?

While we're at it, is there a way to kill a Fiber or interrupt a "blocking"
call like #wait or sleep? I would like to stop all my fibers before
terminating, but I have no idea how to do this other than just let them
finish and return. I can't seem to find anything like Thread.join, did I
miss it?

**Comment by RX14** [comment]
@stronny the current easiest workaround is just to do this:

```cr
#!/usr/bin/env crystal
child = Process.new "sleep", ["60"]
spawn { p child.wait }
Signal::INT.trap { spawn { exit 0 } }
at_exit {
  child.kill
p :before
  sleep 1
p :after
}

sleep 10
raise "boom"
```

**Comment by asterite** [comment]
I think @RX14 's [solution](https://github.com/crystal-lang/crystal/issues/7336#issuecomment-457871817) is valid, though I'm not super familiar with the signal handling code.

**Comment by asterite** [comment]
I also wrote this code in Ruby and it behaves as @stronny (and probably anyone) would expect:

```ruby
child = Process.spawn("sleep 6")
Thread.new { Process.wait(child); puts "done" }
trap(:INT) { exit 0 }
at_exit {
  Process.kill(9, child)
  p :before
  sleep 1
  p :after
}

sleep 3
raise "boom"
```

**Comment by stronny** [comment]
The second point here is the magic around `at_exit`: it behaves differently depending on where the `exit` happens, is this intentional?

**Comment by ysbaddaden** [comment]
@RX14 you're right, we must spawn a fiber to invoke the signal handler, so a blocking call inside a signal handler (SIGINT => `exit`) won't block other signals from being processed (SIGCHLD => ...pending...).

**Comment by asterite** [comment]
@stronny How it behaves differently?

**Comment by ysbaddaden** [comment]
@stronny the reason is that `exit` is a blocking call. Calling exit inside the trap handler will block the handling of further signals, so the SIGCHLD is received, pushed to the signal pipe, but the child handler is never called.

Calling exit outside of the trap handler, or inside a spawn will block that fiber, and won't block the signal handler loop, so the SIGCHLD can be handled.

**Comment by stronny** [comment]
There is a bit of complexity here. So IIUC, calling `exit` will block the fiber it's called from, will run `at_exit` "inside" that fiber, all the while other fibers will continue running?

**Comment by asterite** [comment]
@stronny The problem is this:
- the handling of signals in Crystal is handled by a loop in a single fiber (do we have a signal? -> handle signal (*))
- when you press ctrl+C the `SIGINT` handler is invoked (mentioned in the previous step)
- the handler calls `exit`, which ends up calling `at_exit` (all of these are successive calls, happen in the same fiber, but clarifying this wasn't needed in my opinion)
- the `at_exit` handler kills a process and that triggers `SIGCHLD`. However, and this is the problem, the signal handler is already busy handling that previous `SIGINT`, it can't handle any more signals. And this is because the handling of the signal (what I marked with (*) above) is done in the same fiber as the signal handling loop fiber. That's why SIGCHLD never triggers and `child.wait` never finishes

The solution is to spawn a new fiber to invoke the signal handler to prevent it from handling other signals concurrently.

Makes sense?

**Comment by asterite** [comment]
> That's why SIGCHLD never triggers and `child.wait` never finishes

This point I actually don't understand very well (because I'm not very familiar with the signal handling code, not even with signals themselves) but I think that's the problem.

**Comment by stronny** [comment]
When I was reading the source I left with the impression that the handlers reset all C traps to IGNORE so that the handlers run with no other signals interrupting them, am I correct here? Isn't this a part of the problem?

**Comment by ysbaddaden** [comment]
It's confusing but SIGCHLD is *never* ignored. `Signal::CHLD.reset` actually sets the default crystal handler that will report completions to `Process` and will call the user handler set with `Signal::CHLD.trap` if present.

**Comment by ysbaddaden** [comment]
@asterite we delay the handling of signals to the event loop because:

1. a signal delivery can interrupt a running signal handler, so we must only use signal-safe reentrant C calls within a signal handler (otherwise it can segfault), and there aren't many of them (see `signal(7)`), so running arbitrary crystal code inside the signal handler is unsafe;
2. a signal delivery interrupts the current thread, thus blocks the Crystal event loop and scheduler, so doing the bare minimum avoids blocking the thread for too long.

To solve that:

- the *C signal handler* is always the same: it merely writes the signal (e.g. LibC::SIGINT) to an IO pipe and returns; this is expected to be signal safe;
- the *Crystal signal handler* is also always the same: it's a loop inside a fiber that reads the signal (Int32) from the IO pipe and invokes the actual handlers, that can run whatever since we're in Crystal land.

Back to this issue:
- I overlooked that a *blocking* call inside a signal handler would block that signal handler, thus block the signal handler loop, thus prevent further signal handlers to be called.. oops;
- calling the signal handler inside a fiber will make a blocking call block that fiber, not the signal handler loop, which can now invoke other handlers, thus fixing the issue.

**Comment by asterite** [comment]
@ysbaddaden Thanks for the thorough explanation! What do you think about putting all that information right in the code? If you are busy I can do it (I'll just copy what you wrote here somewhere near the signal handling code).

> I overlooked that a _blocking_ call inside a signal handler would block that signal handler, thus block the signal handler loop, thus prevent further signal handlers to be called.. oops

We all make mistakes, this is just another bug. And it's one that's hard to spot right away :-)

**Comment by ysbaddaden** [comment]
The most information should be in signal.cr already, but maybe it's scattered in the file, and not as thorough. I let you look and improve it :)

**Comment by stronny** [comment]
Let me ask a final question: what are your thoughts on doing away with callbacks and handling signals with either a Channel exposed directly to the user code or with SignalException, ruby-style?

**Comment by ysbaddaden** [comment]
I'm not sure what you mean.

I think the current solution is correct as per crystal runtime design. It hides the underlying complexity and dangerousness, it exposes a simple interface to the developer (run a callback block inside a fiber), and avoids blocking the event loop for too long —coukd eventually be improved by having a dedicated thread to

**Comment by asterite** [comment]
In Go you pass a channel where you receive a signal or multiple signals. But I don't know what's the advantage of that compared to a callback.

**Comment by stronny** [comment]
What I try to improve is mental model of signal handling. Suppose my program has a main loop that reads from a channel or selects a number of channels and manages its work by sending data to "worker" channels. A quite common design for a daemon I imagine. Now I want to handle signals. Naturally I would like to either add another channel to my select block or rescue and handle an exception inside the loop. Callbacks do not fit nicely here, I would have to send my signals to my channel manually, so the whole thing becomes a bit redundant:

- C-trap a signal
- send it to a pipe
- get it from a pipe, spawn a fiber, call a Proc
- Proc sends the signal to a channel

Having said that, I don't have a strong position one way or the other here, I was just wondering did you consider other signal handling approaches than the traditional callbacks.

**Comment by ysbaddaden** [comment]
I'm afraid passing a channel to send the signal to, instead of a callback would be exactly the same, since the channel can block (unbuffered or the buffer is full), so it's still C callback -> IO pipe -> signal loop -> fiber -> channel send, with yet another level with the channel.

We must still create the channel manually, but maybe `Signal::INT.notify(channel)` that would do `Signal::Int.trap { |sig| channel.send(sig) }` is interesting. I'd keep the simpler trap callback, thought.
