### ISSUE TITLE
Named fibers seem subtly broken

### ISSUE THREAD

**Issue by stronny** [crystal-lang/crystal#7365]
#1284

```
spawn               do p :hi end
spawn "hey"         do p :hey end
spawn name: "hello" do p :hello end
sleep 1
```

```
$ ./test.cr
:hi
:hello
```

This was a real WTF moment for me. Do I understand correctly that any positional arguments to `spawn` will silently prevent it from running? Why?

:thinking: is it because of `spawn` macro?

**Comment by straight-shoota** [comment]
> Where is my block now? Did macro just eat it with no warnings?

Yes. A macro can be called with a block but doesn't need to do anything with it. That's necessary because macro blocks need to be optional.

Regarding the initial example, `name` can't be used as a positional argument to `spawn`, it needs to be a named argument for both the [macro](https://crystal-lang.org/api/0.27.1/toplevel.html#spawn%28call%2C%2A%2Cname%3Dnil%29-macro) and the [method](https://crystal-lang.org/api/0.27.1/toplevel.html#spawn%28%2A%2Cname%3AString%3F%3Dnil%2C%26block%29-class-method).

**Comment by stronny** [comment]
Does it ever make sense to call spawn macro with a block? Why not at least issue a warning?

Do you understand how confusing it is to debug the code that was not compiled at all?

**Comment by asterite** [comment]
I think we can give a compile error if an expression and a block are passed. Let me fix that...

**Comment by stronny** [comment]
Thank you! As a more general approach is it possible to notify a user about unused code in the program? If I understand correctly at the moment if a method is never called it just gets skipped, what are your thoughts on a new optional mode that will report all unused methods, block, procs, maybe even variables?
