### ISSUE TITLE
Formatter: case style indention for property definitions

### ISSUE THREAD

**Issue by jrester** [crystal-lang/crystal#7433]
Could the formatter indent properties like it's done with `case` blocks?
So this
```crystal
class Foo
   property foo_bar_foo : FooBarType = FooBarType.new
   property foo : Foo = Foo.new
   property bar_foo_bar_foo : BarFooBarFooType? =  nil
end
```
becomes this
```crystal
class Foo
   property foo_bar_foo        : FooBarType            = FooBarType.new
   property foo                : Foo                   = Foo.new
   property bar_foo_bar_foo    : BarFooBarFooType?     = nil
end
```

The last one is much more readable and you can easily see what's going on.

**Comment by Sija** [comment]
That would be a real nightmare for diffing...

**Comment by asterite** [comment]
@jrester This is an interesting idea. However, `property` is not a keyword in the language, it's just a macro call. If we want to align these we'll also have to align `getter`, `setter`, and whatever name you'd also like to align in case it looks like a keyword (or as DSL). This makes it practically impossible for the formatter to know when things should or shouldn't be aligned.

Additionally, I'm not convinced about the formatter currently aligning things: it can make some lines too wide, and it can produce unwanted diff. So in my mind the direction should be removing automatic alignment instead of adding more of it.

I'm also closing because it only had 5 negative votes.
