### ISSUE TITLE
Macro definitions in modules do not work like method definitions in modules

### ISSUE THREAD

**Issue by toddsundsted** [crystal-lang/crystal#7541]
Macro definitions in modules do not work like method definitions in modules when imported/extended into classes.

Method definitions work as expected:
```
module Foo
  def foo
  end
end

class Bar
  include Foo
end

Bar.foo # => undefined method 'foo' for Bar.class

class Baz
  extend Foo
end

Baz.foo # this is ok
```

However, macro definitions work exactly the opposite:
```
module Foo
  macro foo
  end
end

class Bar
  include Foo
end

Bar.foo # this is ok!

class Baz
  extend Foo
end

Baz.foo # undefined method 'foo' for Bar.class
```

**Comment by straight-shoota** [comment]
Macro methods are defined on the type scope, instance methods are on the instance scope. So macro methods are more similar to class methods `def self.foo ...`.
It wouldn't make any sense if macro methods behaved like instance methods because they have no connection at all to instances of the defining type.

**Comment by ysbaddaden** [comment]
This is a question for the [forum](https://forum.crystal-lang.org), thanks :)

**Comment by toddsundsted** [comment]
thanks for the super-fast replies!

i didn't see this behavior documented anywhere, and i didn't find it enshrined in tests, so i thought it might be a bug. it's not really class-like, but if it's as designed/as implemented, i'm fine.
