### ISSUE TITLE
Is Hash ordered based on when the entry was inserted?

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#7593]
Hi, everybody.

  I just want to make sure whether `Hash#keys` or `Hash#each` returns entries in order based on when they were inserted. I found it's mentioned in [`Hash#key_index`](https://crystal-lang.org/api/0.27.2/Hash.html#key_index(key)) in document,  and it looks like it's ordered viewing the code of `key_index`. But nothing mentioned in any other place about this, and the document of [`Set` ](https://crystal-lang.org/api/0.27.2/Set.html) say `Set` based on `Hash` is unordered.

**Comment by xqyww123** [comment]
And more is it safe to insert new entry into Hash during the iteration of it, and will the new inserted entry be visited in the iteration?

**Comment by straight-shoota** [comment]
1. Key-value pairs in a Hash are sorted by insertion order.
2. A Set by definition has no order. In practice, the items will be sorted by insertion order because of the implementation. But it's not guaranteed. If we change the implementation, this might not longer be true. Sets should always be considered unordered.
3. It should be safe to add elements to any stdlib collection while enumerating it and newly added items should be enumerated as well.

We should use this issue to improve the documentation.

**Comment by asterite** [comment]
For 2, a Set has an order. _In theory_ it doesn't have one, but in practice it does. Same with `Hash`: in theory a mapping of keys from values isn't ordered, but in practice it is. And for example Ruby guarantees this (because they guarantee this through the implementation, and they won't suddenly change the implementation to unordered). We should do the same (guarantee that `Set` will stay ordered).

**Comment by straight-shoota** [comment]
@asterite I can't find such a guarantee for `Set` in Ruby. The [API docs](https://docs.ruby-lang.org/en/2.6.0/Set.html) explicitly state that it's an unordered collection and that the order of elements returned by `#to_a` is uncertain.

**Comment by asterite** [comment]
@straight-shoota Oh, I guess it's ordered then because it's built on top of `Hash`. Nevermind.

**Comment by ysbaddaden** [comment]
BTW: Hash wasn't ordered in Ruby 1.8.
