### ISSUE TITLE
Initialize detecting raise values

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#7710]
I am not sure if this is intended but if I have properties that are conditionally set I want to raise if none of the inputs into the initializer is correct.  example: https://play.crystal-lang.org/#/r/6s5b

I dont think the compiler knows that I just want it to raise and the properties shouldn't matter in that case.  This could be complicated if there is a rescue and the varible is accessed.  I just wanted to get peoples thoughts.

**Comment by oprypin** [comment]
First of all `bar = ...` here just sets a local variable so that's a no-op

**Comment by oprypin** [comment]
And if you change it to `@bar = ...` everything just works

**Comment by jhass** [comment]
The compiler is not tracking instance variable assignments inside methods called from an initializer. For now this is an intentional limitation to keep the compiler more performant and simple.

As already said, you're just assigning local variables here, not even touching the instance variables. Adding `self.` in front of your assignments would reference the setters defined by the `property` macro, but given those are just normal methods, the above limitation applies. As also already said you can fix your example but just assigning the instance variables directly: https://play.crystal-lang.org/#/r/6s7f
