### ISSUE TITLE
crystal:nightly docker image is broken

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7713]
Running `crystal` in the current (2019-04-24) `crystal:nightly` and `crystal:nightly-build` docker images  fail with the following error message:
```
/usr/bin/crystal: 105: exec: /usr/bin/../lib/crystal/bin/crystal: not found
```

Examples:
* https://circleci.com/gh/straight-shoota/crinja/356
* https://circleci.com/gh/crystal-lang/crystal/22171

The previous nightly images (2019-04-23) worked fine.

**Comment by bcardiff** [comment]
Duplicate of https://github.com/crystal-lang/distribution-scripts/issues/33 .

The `/usr/bin/../lib/crystal/bin/crystal: not found` error is probably because some dependencies are not met, due to not been statically linked.

I wasn't able to repro consistently. Not sure if there is a difference in the docker images used during the build some nights.

**Comment by straight-shoota** [comment]
I noticed this has happened before: Nightly builds for crinja failed on [2019-04-18](https://circleci.com/gh/straight-shoota/crinja/350) and [2019-04-19](https://circleci.com/gh/straight-shoota/crinja/351) for the same reason. But it worked on [2019-04-17](https://circleci.com/gh/straight-shoota/crinja/349) and [2019-04-20](https://circleci.com/gh/straight-shoota/crinja/352).

**Comment by drhuffman12** [comment]
This happened for me tonight. FYI, as a work-around, those who don't *need* `nightly` (like me) might consider using `latest` instead.
