### ISSUE TITLE
Cannot autocast `Int::Unsigned`

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7752]
https://carc.in/#/r/6vdy:

```crystal
def foo(x : Int::Unsigned)
  puts x
end

foo(1)
```

```
Error in line 5: ambiguous call, implicit cast of 1 matches all of UInt128, UInt16, UInt32, UInt64, UInt8
```

It didn't work one day before, looks like it hasn't been fixed yet :thinking: 

BTW, I'm still voting for replacing `Int::Unsigned` with simple `UInt` like this, it's more intuitive IMO:

```crystal
def foo(x : UInt)
  puts x
end
```

The changes to the language are minimal, just add an alias or replace:

```crystal
alias UInt = Int::Unsigned
```

**Comment by oprypin** [comment]
The error totally makes sense though. An integer literal has affinity with Int32 but all the unsigned types are equally distant from it. And a method has to be instantiated with some concrete type!

**Comment by vladfaust** [comment]
Should make _unsigned_ integer literal affine with _UInt32_ then?

**Comment by oprypin** [comment]
Also FYI, the more common approach lately seems to be to allow any integer type and then check that it's in range at runtime. My thinking behind this is that just because Unsigned happens to match your logic's valid range (0 to infinity) doesn't mean you should rely on it. Because what if it another instance the range was 1 to infinity? Then it's not enough anyway.

**Comment by vladfaust** [comment]
I'd like to reduce runtime errors as much as possible. If I have strict case of from 0 to infinity, that's perfect use for `UInt`. If I have 1 or 2 to infinity then, well, I'd still like to use `UInt` as restriction to raise in compilation time if there is a theoretical possibility for the argument to be negative.

**Comment by asterite** [comment]
But which unsigned integer it should cast to?

This is not a bug, it works as expected.

**Comment by vladfaust** [comment]
@asterite why not `UInt32`?

**Comment by asterite** [comment]
Why would UInt32 be chosen over the other types? It seems like a random rule.

**Comment by vladfaust** [comment]
Why would Int32 be chosen over the other types?

**Comment by asterite** [comment]
> If I have strict case of from 0 to infinity, that's perfect use for UInt

No. It's a bit hard to explain why on cellphone, but if you search this topic in the internet you will find many answers.

**Comment by vladfaust** [comment]
Okay, I'm a bit too pushy. I don't know about those internals you're talking about. I'm assuming from a regular language point of view. The current behavior is not intuitive, that's what I want to say.

**Comment by Sija** [comment]
@vladfaust I disagree. It's pretty obvious you can't autocast a value when there are multiple matching types.

**Comment by RX14** [comment]
`1` is an `Int32`, so using an `Int` type restriction passes without any autocasting.

When you restrict to `Int::Unsigned`, the type restriction does not match so autocasting is invoked - and this is ambiguous so it fails. This is not a bug.

**Comment by straight-shoota** [comment]
I'm not sure about dismissing this.

Yes, the call is ambiguous regarding the target type of the method call. But the compiler can resolve that and just pick one. As long as it fits the origin type, this should be totally fine. Since all types are accepted, the implementation shouldn't care about which one is chosen.
I don't see a reason why the developer should be bothered to type the literal (or cast the value since #11431).

> Why would UInt32 be chosen over the other types? It seems like a random rule.

Because it's the biggest type. It subsumes all other alternative types. Picking the largest type seems like a valid default choice to me.
This argument won't work when signed and unsigned integer types are mixed, though.

> It's pretty obvious you can't autocast a value when there are multiple matching types.

That's not obvious. The compiler could just make a choice. Any choice is fine as long as it's deterministic and documented. I think that's at least as reasonable as refusing to do anything.
