### ISSUE TITLE
Multiplying a decimal and hexidecimal number gives incorrect result

### ISSUE THREAD

**Issue by watzon** [crystal-lang/crystal#7782]
When running the following, very simple equation Crystal gives an incorrect result of `0`

```crystal
1 * 0x10000000000
``` 

However when running the equation in reverse the correct answer of `1099511627776` is returned

```crystal
0x10000000000 * 1
```

This definitely looks like a parser error to me, as in the first example the `Int32` on the left is being multiplied by the `0` instead of the decimal representation of the full hex.

**Comment by bew** [comment]
Note: https://carc.in/#/r/6x5g
```cr
p! 1 * 0x10000000000 # => 0
p! 0x10000000000 * 1 # => 1099511627776
puts
p! 1_i64 * 0x10000000000 # => 1099511627776
p! 0x10000000000 * 1_i64 # => 1099511627776
```

**Comment by ysbaddaden** [comment]
Nope, it's an overflow:
```
> 0x10000000000
 => 1099511627776
> 1099511627776.to_i32
 => 0
```

Use `-Dpreview_overflow` when compiling and this will raise `Arithmetic overflow (OverflowError)`. You must cast the first argument to Int64 or reverse arguments so the first argument of the integer multiplication is an Int64, because the first argument's type dictates the result type of the operation (1 is Int32, so the result is always an Int32).

**Comment by watzon** [comment]
@ysbaddaden ok that makes sense
