### ISSUE TITLE
Same error shown for two different macro method calls

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7825]
```cr
CONSTANT = "hello".delete('l')

{% CONSTANT.split('e') %}
```
```
Error in line 3: expanding macro

in line 3: undefined macro method 'Call#split'

in line 1: undefined macro method 'Call#split'
```
I called the undefined macro method `delete`, not `split` in line 1.

**Comment by jhass** [comment]
This seems fine, constant value expression are not run in macro land.

**Comment by asterite** [comment]
Yes, the macro is operating on the AST node behind `"hello".delete('l')`, which is a `Call`.

**Comment by bew** [comment]
I would expect that to work though: https://carc.in/#/r/6zyj
```cr
CONSTANT = {{ "hello".delete('l') }}

{% p CONSTANT.split('e') %}
```

**Comment by Sija** [comment]
@bew you've forgot about sth, see https://carc.in/#/r/6zyn

**Comment by bew** [comment]
Lol yeah ok, there's no `StringLiteral#delete`, but https://carc.in/#/r/6zyp should work imo:
```cr
CONSTANT = {{ "hello" }}

{% p CONSTANT.split('e') %}
```

**Comment by Sija** [comment]
@bew no, it shouldn't, since you're missing `{% begin %} ... {% end %}`.

**Comment by bew** [comment]
Well @Sija adding macro' begin/end doesn't work either since you can't reference `CONSTANT` from the macro being evaluated.. To make that work you need to escape like: https://carc.in/#/r/6zyt

I would expect that using `CONSTANT` in a macro would execute the macro expression, like they are executed when passed as macro arguments: `some_macro({{ "foo" }})`.
And to get the current behavior you'd need to escape the macro `C = \{{ "foo" }}`..

I can open another issue to properly discuss that if needed?

**Comment by Sija** [comment]
@bew That's correct but you still need to wrap it into `{% begin %} ... {% end %}`.
