### ISSUE TITLE
Compiler Bug when class constant is Regex that references class member of same name

### ISSUE THREAD

**Issue by jfharrigan** [crystal-lang/crystal#7865]
The compiler reports a compiler bug for the following code:
```
class Pattern
  @@A = "asdf"
  A = /#{@@A}/
end
puts Pattern::A
```

I can only trigger this bug if the constant and member have the same name.

> crystal build test.cr
```
Module validation failed: Function return type does not match operand type of return inst!
  ret %String** @"Pattern::A", !dbg !74
 %Regex** (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```

> crystal -v
```
Crystal 0.29.0 [fbfe8b62f] (2019-06-05)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by straight-shoota** [comment]
`@@A` should not be a valid name for a class variable.

**Comment by HertzDevil** [comment]
[The internal error went away since 1.8](https://godbolt.org/z/eehq4Pezd) due to changes to regex creation, but now running the program crashes because both constants and class variables are initialized or read using the same LLVM functions (`~Pattern::A:init` in this case). This is the code that lexes instance or class variables (and globals too, which are still allowed in libs):

https://github.com/crystal-lang/crystal/blob/c97c20e36167b0c9689995b9e020a0105a2d0ec8/src/compiler/crystal/syntax/lexer.cr#L2669-L2679
