### ISSUE TITLE
Ruby to Crystal transformation tool?

### ISSUE THREAD

**Issue by catastrop** [crystal-lang/crystal#7882]

**Comment by wontruefree** [comment]
I am not sure to what level this is possible and what the benefit would be.

Because ruby is so dynamic there are some structures and patterns that I do not think could be migrated to Crystal.  Also,  I don't know if this tool existed I don't know what the value would be.  For example if you could migrate the rails project to crystal would that be better then just making a web application framework in Crystal.

I guess the best place to start is what project do you want to migrate to Crystal?

**Comment by j8r** [comment]
There is [ruby2crystal](https://github.com/faustinoaq/ruby2crystal) from @faustinoaq. I haven't tested it.

This issue isn't related to the Crystal programming language itself, but an external tool. A better place would be https://github.com/crystal-community/crystal-libraries-needed

**Comment by ysbaddaden** [comment]
Please use https://forum.crystal-lang.org for asking questions.
