### ISSUE TITLE
Cannot pass hash directly to a method without parentheses

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7923]
```cr
def do_work(hash : Hash(String, String)); end

do_work {"foo" => "bar"}
```

`Syntax error in eval:3: unexpected token: =>`

Assigning the hash to a variable first or adding parentheses to the method invocation works.

**Comment by j8r** [comment]
I guess that's because parentheses are also used for blocks.

**Comment by jhass** [comment]
Yes, this a limitation in the grammar.

**Comment by oprypin** [comment]
To expand on why this is unsolvable, otherwise the compiler will need to special-case this with 3-level deep lookahead. Which is usually seen as a very bad thing (sorry for not expanding on that one).

`do_work {` could be both
`do_work {"foo"` could be both
`do_work {"foo" =` could be both
`do_work {"foo" =>` ok right, now I can go back and actually parse this as `Hash`

**Comment by asterite** [comment]
Duplicate of #6224, #2746, #4826, #1051
