### ISSUE TITLE
Ambiguity with `self[n]` within tuples

### ISSUE THREAD

**Issue by waj** [crystal-lang/crystal#801]
The result might look unexpected:
```crystal
struct Tuple
  def self.foo
    self[0]
  end

  def self.bar
    Array(self[0])
  end
end

tuple_class = {1}.class
tuple_class.foo # => Int32
tuple_class.bar # => Array(StaticArray({Int32}, 0))
```

For consistency I think `self[0]` should always be a StaticArray and macro methods should be used to get into the type parameters of the tuple class.

**Comment by waj** [comment]
Also, this crashes the compiler, but I think it's related:
```crystal
Array({1}.class[0])
```
```
cast to Crystal::Type failed
*Exception#initialize<Exception, String, Nil>:Array(String) +21 [4316284741]
*Exception::new<String>:Exception +106 [4316284682]
*raise<String>:NoReturn +6 [4316120614]
*Crystal::TupleType#instantiate<Crystal::TupleType, Array((Crystal::Type+ | Crystal::ASTNode+))>:Crystal::GenericClassInstanceType+ +529 [4325914817]
...
```

**Comment by asterite** [comment]
This ambiguity exists between code and the type grammar. For example `{Int32, Int32}` means a tuple with two `Int32` types in regular code, but means `Tuple(Int32, Int32)` in the type grammar. The same applies to `self[X]`. So this is not a valid issue. We *could* remove all shorter syntax, but then we'd have to write `Pointer(Pointer(Void))` instead of `Void**`, or `Array(NamedTuple(x: Int32, y: Char))` instead of `Array({x: Int32, y: Float64})`. I prefer to keep the short syntax :-)

The last snippet gives this compile time error in 0.17.4:

```crystal
Error in ./foo.cr:1: argument to Tuple must be a type, not 1

Array({1}.class[0])
      ^
```
