### ISSUE TITLE
Infinite recursion when sending Iterator to channel

### ISSUE THREAD

**Issue by KimBurgess** [crystal-lang/crystal#8150]
Attempting to send an `Iterator` to a channel appears to result in infinite recursion in the compiler.

As a [reduced example](https://play.crystal-lang.org/#/r/7hyl):
```crystal
channel = Channel(Iterator(String)).new

spawn do
  channel.send ["foo", "bar", "baz"].each
end

channel.receive.each &->puts(String)
```

This behaviour was evident across all currently released versions of the compiler (from 0.30 back).

Looking through similar issues, this may be related to #7044.

**Comment by asterite** [comment]
Yes, there's no way right now to have a variable of type Iterator. So I think we can close this as a duplicate.

**Comment by bew** [comment]
@asterite why is that?

**Comment by asterite** [comment]
Note that this doesn't happen anymore in `master`. Might be related to the `Channel` refactor and that now `Channel` is just a single type, not an abstract type.

The reduced example for `Iterator` is this:

```crystal
iter = ([] of Int32).each.as(Iterator(Int32))
iter.map { |s| s }
```

Here the compiler will type `iter` as `Iterator(Int32)` which means: any type that inherits `Iterator(Int32)`.

Unlike other languages (Java, C++, Go), Crystal doesn't use virtual inheritance. When you have a type that means "that type or any of its subtypes" the compiler will compute all of its subtypes before hand. In Java, C++, Go, etc., there's a virtual table that is consulted at runtime to check what is the final method that needs to be called. This is impossible to do in Crystal because we don't require that all methods are typed.

So how does the above causes an infinite compilation?

`iter.map` will instantiate `Iterator::Map(T)` where `T` is the wrapped iterator.

So we have `([] of Int32).each` which is `Indexable::ItemIterator(Array(Int32), Int32)`, but for brevity let's call it `ArrayIterator`.

Then `iter.map` will produce `Iterator::Map(ArrayIterator)`. Because `Iterator::Map` is itself an `Iterator` the compiler notices that a new subtype of `Iterator` was created so the type of `iter` now takes that into account. Now it's possible that `map` is called on this new iterator type. Doing so generates this type: `Iterator::Map(Iterator::Map(ArrayIterator))`. But wait, this new type also includes `Iterator` so the compiler notices a new subtype. But `map` can be called on this subtype. And so on...

If I modify the compiler to print whenever a generic instantiation happens, I see this:

```
Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Iterator::Map(Indexable::ItemIterator(Array(Int32), Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32), Int32, Int32)
...
```

With the current approach (no virtual tables) this is kind of impossible to solve.

That's why a part of my wants a Crystal where you are forced to type every type of every method argument, and every return type. It will make things so much clearer, it will improve compile times and it will make it possible to compile these things. And there will be no edge cases. On the other hand I know this will basically destroy the essence of Crystal.

**Comment by RX14** [comment]
It would probably be possible to detect this case and fail to compile nicely, then in the future this could possibly be solved with vtables.
