### ISSUE TITLE
BUG: trying to downcast (Slice(UInt8) | Nil) <- Slice(UInt8) (Exception)

### ISSUE THREAD

**Issue by rmarronnier** [crystal-lang/crystal#8163]
This code : 
```crystal
require "json"

module Data
  DATA_DIR = "#{__DIR__}/"
end

class Lemmatizer
  include Data
  @lookup : Hash(String, String) = Hash(String, String).from_json({{ read_file("#{DATA_DIR.id}lemma_lookup.json") }})

  def lemmatize(token)
    @lookup[token]
  end
end

pp Lemmatizer.new.lemmatize("zoomed")
```
gives : 

```bash
BUG: trying to downcast (Slice(UInt8) | Nil) <- Slice(UInt8) (Exception)
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
While, this code: 
```crystal
require "json"

DATA_DIR = "#{__DIR__}/"

lookup = Hash(String, String).from_json({{ read_file("#{DATA_DIR.id}lemma_lookup.json") }})

pp lookup["zoomed"]  # "zoom"
```
works.

Note : the json file is irrelevant but I can point you to it or make a repo out of my code if you need.

Also, this code : 
```crystal
require "json"

module Data
  @@lemmatizer_lookup : Hash(String, String) = {"zoomed" => "zoom"}
end

class Lemmatizer
  include Data
  @lookup : Hash(String, String) = @@lemmatizer_lookup

  def lemmatize(token)
    [@lookup[token]]
  end
end

pp Lemmatizer.new.lemmatize("zoomed")
```

gives a runtime error : 

```bash
Invalid memory access (signal 11) at address 0x4
[0x559eb33dc856] *CallStack::print_backtrace:Int32 +118
[0x559eb33cf210] __crystal_sigfault_handler +192
[0x7fe41a311890] ???
[0x559eb34202e0] ???
[0x559eb3420288] *Hash(String, String) +24
[0x559eb34200c0] *Hash(String, String) +48
[0x559eb3420621] *Lemmatizer#lemmatize<String>:Array(String) +97
[0x559eb33c1461] __crystal_main +1489
[0x559eb3426fd6] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +6
[0x559eb3426f39] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +41
[0x559eb33cc5d6] main +6
[0x7fe4198c2b97] __libc_start_main +231
[0x559eb33c0daa] _start +42
[0x0] ???
```

**Comment by rmarronnier** [comment]
I forgot : 
```bash
Crystal 0.30.1 [5e6a1b672] (2019-08-12)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by asterite** [comment]
Reduced a bit:

```crystal
require "json"

class Lemmatizer
  getter lookup = JSON.parse("foo")
end

Lemmatizer.new.lookup
```

Can probably be reduced further.

As a workaround, initializing `@lookup` inside `initialize` works fine.

**Comment by rmarronnier** [comment]
Thanks @asterite for the workaround

**Comment by kinxer** [comment]
Context from #8343 to help with diagnosing this issue:

This issue occurs in Crystal 0.27.1 to 0.31.1.

This issue occurs in the following case (minimized from here and #8343):
```
require "json"

class A
  @a = JSON.parse("a")
end

A.new
```

Stack Trace (provided by @Blacksmoke16):
```
BUG: trying to downcast (Slice(UInt8) | Nil) <- Slice(UInt8) (Exception)
  from Crystal::CodeGenVisitor#downcast_distinct<LLVM::Value, Crystal::Type+, Crystal::Type+>:NoReturn
  from Crystal::CodeGenVisitor#downcast<LLVM::Value, Crystal::Type+, Crystal::Type+, Bool>:LLVM::Value
  from Crystal::CodeGenVisitor#visit<Crystal::Var+>:(LLVM::Value | Nil)
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#codegen_cond<Crystal::ASTNode+>:LLVM::Value
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  ...
```

**Comment by asterite** [comment]
Reduced a bit more, but I still don't know the cause:

```crystal
def foo : Int32
  io = uninitialized IO
  io.read_char
  1
end

class Foo
  @x : Int32 = foo
end
```

**Comment by rmarronnier** [comment]
I tried going into the rabbit hole and what I found was : 
`IO#read_char` and `IO#peek` were the only two methods of the IO abstract class to produce this bug.
Here is the #peek definition : 
```crystal
  def peek : Bytes?
    nil
  end
```
So I could make this code even simpler : 

```crystal
def foo : Nil
  io = uninitialized IO
  io.peek
end

class Foo
  @x : Nil = foo
end
```

And also, this (expectedly ?) compiles but crashes at runtime : 

```crystal
def foo : Nil
  io = uninitialized IO
  io.peek
end

foo
```

I'm stuck for now.

**Comment by HertzDevil** [comment]
There is a method call loop involved in https://github.com/crystal-lang/crystal/issues/8163#issuecomment-547603343:

* `IO::Buffered#read`
* `Crystal::System::FileDescriptor#unbuffered_read`
* `IO::Evented#evented_read`
* `IO::Evented#wait_readable`
* `Crystal::Scheduler.reschedule`
* `Crystal::Scheduler#reschedule`
* `Fiber#resume`
* `Crystal::Scheduler.resume`
* `Crystal::Scheduler#resume`
* `Crystal::Scheduler#validate_resumable`
* `Crystal::Scheduler#fatal_resume_error`
* `caller`
* `Exception::CallStack#printable_backtrace`
* `Exception::CallStack#decode_backtrace`
* `Exception::CallStack.decode_line_number`
* `Exception::CallStack.load_debug_info`
* `Exception::CallStack.load_debug_info_impl`

From here, the definition diverges between platforms. On Darwin it is:

* `Exception::CallStack.read_dwarf_sections`
* `Exception::CallStack.locate_dsym_bundle`
* `Crystal::MachO.open`
* `Crystal::MachO#initialize`
* `IO::FileDescriptor#read_bytes`

On Linux:

* `Exception::CallStack.read_dwarf_sections`
* `Crystal::ELF.open`
* `Crystal::ELF#initialize`
* `Crystal::ELF#read_magic`
* `IO::FileDescriptor#read`

On Windows, `Exception::CallStack.load_debug_info_impl` calls only Win32 API functions.

On Darwin and Linux the global type inference algorithm probably broke somewhere. While I don't have a minimal reproduction outside this hierarchy yet, the same bug indeed does not occur on Windows because there is no loop there.

It probably makes sense that `Crystal::MachO` and `Crystal::ELF` should use a lower abstraction than `IO::FileDescriptor`.
