### ISSUE TITLE
Rationale of ECR?

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#8311]
Since we can import Crystal code with `{{ read_file "./file.cr" }}`, there are no examples in the [API docs](https://crystal-lang.org/api/master/ECR.html) that expose a true advantage over regular macros.

`ECR.def_to_s "greeter.ecr"` would be in macros:
```cr
def to_s(io)
  ({{ read_file "./greeter" }}).to_s io
end
```
If this is considered too verbose, it can also eventually become a dedicated macro.

Another question is why having only compile time templating and none for runtime?
This templatings can be delegated to external libraries.

**Comment by asterite** [comment]
The first example already shows something you can't do with `read_file`:

```
Greetings, <%= @name %>!
```

**Comment by j8r** [comment]
You can @asterite:
```cr
"Greetings, #{@name}!"
```

**Comment by asterite** [comment]
How would that print the value of an instance variable `@name` in the context where the file was read?

**Comment by j8r** [comment]
It can be achieved with a regular macro method.

**Comment by j8r** [comment]
What I want also to point out is that ECR is mostly used via Kilt in Kemal: 
https://github.com/search?l=Crystal&p=1&q=ECR&type=Code

What is the motive under supporting only this compile time template? And why no runtime one?

**Comment by bcardiff** [comment]
A template like .ecr is aimed to express content first rather than code. So the interpolation is for code instead of string literals for content.

Embedding a crystal file would not allow the processing of the .ecr language to happen.

Having .ecr checked in compile time is the deal-breaking with other templates that work only on runtime and hence will not allow the same semantics when doing method dispatch.

**Comment by j8r** [comment]
Thanks, I better understand the rationale.
I guess it was developed in the first place mainly for the `crystal docs` tool?

**Comment by bcardiff** [comment]
And for crystal init and inspired in how asp.net precompiled pages work 🙊
