### ISSUE TITLE
Incorrect String#gsub behavior

### ISSUE THREAD

**Issue by igor-alexandrov** [crystal-lang/crystal#8459]
I need to escape all whitespace chars with '\'.

```
"two words".gsub(/\s+/, "\ ")
```

Expected result: ```"two\ words"```.
Actual result: ```"two words"```.

Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx

**Comment by straight-shoota** [comment]
`gsub` behaves totally correct.

Did you look at the string replacement? It is actually `two words`.
In string literals the backslash character denotes an escape sequence and by default escapes the next character as itself (unless it is one of the special escape sequences). See https://crystal-lang.org/reference/syntax_and_semantics/literals/string.html for details.

In order to write a literal backslash, you can use the backslash escape `\\`: `"two\\ words`.
Alternatively, there is also a non-interpolation string literal: `%q[two\ words]`.

**Comment by igor-alexandrov** [comment]
Got it!

**Comment by RX14** [comment]
Should we just make invalid escapes be syntax errors, so they're reserved for additional escapes possibly in the future. Otherwise it's always a breaking change to add an escape, and these kinds of errors can pop up.

**Comment by straight-shoota** [comment]
I suppose that behaviour is simply a Ruby legacy. It's a valid option, though. I don't think there are many escape sequences that could possibly be added, so the breaking changes should not be a huge issue.

The possible alternatives for unrecognized escape sequences are:
* Ignore the backslash (current behaviour)
* Treat the backslash as literal backslash (Python)
* Syntax error (C)

**Comment by asterite** [comment]
I think syntax error is good.

**Comment by igor-alexandrov** [comment]
Should we reopen it?

**Comment by straight-shoota** [comment]
No, better make it a new issue.

**Comment by asterite** [comment]
I think it should be a different issue, unrelated to gsub.
