### ISSUE TITLE
Exact behavior of Proc#hash

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#8517]
Hello,

Could you please clarify the following results when using Proc#hash, and comment on what practical effect it has on comparing Procs based on their hash?

Code:

```crystal
p ->(){1}.hash
p ->(){1}.hash
p "--"
3.times do p ->(){1}.hash end
p "--"
(0..2).each do p ->(){1}.hash end
p "--"
p ->(){1}.hash
p ->(){1}.hash
```

Results:

```
14671911895494160835
11396167350379433108
--
16107691497591169285
16107691497591169285
16107691497591169285
--
15655413899114458185
15655413899114458185
14308562490901528988
--
5358833060979187041
2962368102080395622
```

Code on play:
https://play.crystal-lang.org/#/r/82hc

**Comment by asterite** [comment]
`Proc#hash` is a hash produced by the combination of the Proc's memory address plus any closured data. In your example there's no closured data so it's just the memory address.

Then each time you write `->{}` it's a different Proc instance. Inside a block, because blocks are inlined, each `yield` invocation will produce a different `->{}` (maybe the compiler could improve this by reusing previous instantiations of the block). In the case of `(0..2).each` there are two `yield` expressions inside it: one for the general loop and one more if the range is not exclusive. That's why we see one different `hash` at the bottom.

This could be improved (what I said above).

Maybe this question is more suited for the forums? Is there a problem this behavior is giving you?

**Comment by docelic** [comment]
Most probably forum would have been better. Thanks for the answer and pointer.

**Comment by straight-shoota** [comment]
Addendum: If you replace all calls to `#hash` with `#pointer` (https://play.crystal-lang.org/#/r/82i8), you can see the function pointer directly.

The practical effect of comparing procs by their hash is the same as with any other value. Hashing speeds up comparison and indexing of values, for examples in the implementation of `Hash` etc.
