### ISSUE TITLE
Compiler crash with to_unsafe and C type

### ISSUE THREAD

**Issue by keidax** [crystal-lang/crystal#8544]
Reproduction:
https://gist.github.com/keidax/890f0a7195f64950effb3a302e879996

On macOS, I get this output:
```
$ crystal foo_object.cr
Module validation failed: Incorrect number of arguments passed to called function!
  call void @"*Pointer(Void)@Object::to_s<String::Builder>:Nil"(i32 %obj, %"String::Builder"* %self), !dbg !183
 (Exception)
  from Crystal::CodeGenVisitor#finish:Nil
  from Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)
  from Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
  from Crystal::Command#run_command<Bool>:Nil
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from __crystal_main
  from main
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

This is on macOS Mojave 10.14.6
Output of `crystal -v`:
```
Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```

**Comment by HertzDevil** [comment]
This breaks `make spec`, because the standard library spec does this:

https://github.com/crystal-lang/crystal/blob/5b8cb313a84d28fb4a3489fe005fa48cee30c457/spec/std/xml/reader_spec.cr#L549-L554

where `LibXML::XMLTextReader` is defined as:

https://github.com/crystal-lang/crystal/blob/5b8cb313a84d28fb4a3489fe005fa48cee30c457/src/xml/libxml2.cr#L82

The actual conflict occurs within `Spec::BeAExpectation#failure_message`. Reduced:

```crystal
lib LibFoo
  type Foo = Pointer(Void)
end

class Class
  def foo(x)
    x
  end
end

x = 1
LibFoo::Foo.foo(x)
Pointer(Void).foo(x)
```

But note that the linked spec should fail; `LibAsdf::VoidPtr` and `Pointer(Void)` are sibling types, so neither is a subtype of the other. (To make it pass, use `alias` instead of `type`.)
