### ISSUE TITLE
PKG_CONFIG_PATH should be automatically set to /usr/local/opt/openssl/lib/pkgconfig for macOS

### ISSUE THREAD

**Issue by ndbroadbent** [crystal-lang/crystal#8548]
Hello,

I ran into this openssl issue, and found that a lot people have had the same issue on Mac. It's even [listed as one of the setup steps for the Lucky web framework](https://luckyframework.org/guides/getting-started/installing):

> If you get an error like this: Package libssl/libcrypto was not found in the pkg-config search path then be sure to run the last step listed above so that Crystal knows where OpenSSL is located.

This happened for me on a fresh install of macOS, with the latest versions of packages installed from homebrew. So I don't think it is appropriate to include this as a manual step, since it seems fairly easy to automate this for everyone on Mac:

* If `PKG_CONFIG_PATH` is already defined, then do nothing
* If the OS is macOS, and a file exists at `/usr/local/opt/openssl/lib/pkgconfig/libssl.pc`, then set `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig`.

Would this cause any problems for other people on older versions of macOS, or with a different path to openssl?

**Comment by wontruefree** [comment]
This would cause a problem for people not using brew like CI.  but I think in general that might be easier for Devs trying to learn Crystal.

**Comment by jhass** [comment]
If we do magic here I would argue for checking the existence of `brew`, if it's not there, suggest to install it. If it's there, check if `pkg-config` and `openssl` is installed, if not then suggest to do it (or provide it another way by setting PKG_CONFIG_PATH explicitly). If it's there, do some magic based on `brew --prefix openssl`

**Comment by bcardiff** [comment]
To fix this, the current idea is to add a wrapper script in the brew package that will set the PKG_CONFIG_PATH accordingly.

This is similar to #8046 where it should handled by the distribution rather than the std-lib itself.

We can discuss how the brew wrapper script should work as in how to allow the user tweaks the path. 

If the wrapper script always append the openssl path, there is no way to remove it.

If the wrapper script only sets it if non previously set I bet it will become somehow useless because there are many use cases that push users to have already a PKG_CONFIG_PATH set.

**Comment by ndbroadbent** [comment]
Hi @bcardiff, sorry I actually ran into this issue when I cloned the crystal repo, compiled the source code, and then ran the test suite. But the brew wrapper script also sounds like it would be a good solution for Crystal end-users who install it from homebrew.

`PKG_CONFIG_PATH` is currently being set in the CircleCI config for the CI jobs on MacOS. But it would be nice if it could be moved into the Makefile. like this: https://github.com/DocSpring/crystal/commit/d96d4c231d02ec514b631b6f04ea63d505cd6152

Then any Mac users can just clone the repo, install packages with brew, and run `make` without any additional steps.

**Comment by ndbroadbent** [comment]
@wontruefree CI is actually using homebrew to install the packages for the macOS builds, so that's why I thought it would be nice to also automate this config for developers on mac.

@jhass  I think my only concern is that the brew CLI is really slow, and running `brew --prefix openssl` takes about 1.5 seconds on my machine. ([Also they're not interested in rewriting it in Crystal!](https://github.com/Homebrew/brew/issues/3901)) But that would be really nice to add some more magic and tell people how to install homebrew and the required packages. (Or even automate it!)

**Comment by ndbroadbent** [comment]
Argh sorry, I put it in the wrong place. I only need `PKG_CONFIG_PATH` while running `make spec`, and not during compilation. I think I would need to move it into `./bin/crystal`: https://github.com/DocSpring/crystal/commit/8288a13cd6ae1aa54fdde3468eb015e7e3592dd9

**Comment by rdp** [comment]
See also https://github.com/crystal-lang/crystal-book/pull/312#issuecomment-554498573 but glad it's an issue too :)

**Comment by bcardiff** [comment]
I think that unless you are compiling crystal itself the wrapper script in brew should handle the `make spec` or `make std_spec`.

When building the compiler the `bin/crystal` will use `.build/crystal` binary and library path need to be set in order to avoid assuming too much. For example the location of the embedded libraries like the gc might need to be specified.

**Comment by RX14** [comment]
Putting this in a brew script is correct, but unfortunately putting it in the crystal repo itself is using heuristics to try and patch a broken build environment, and isn't something we can accept.

**Comment by ndbroadbent** [comment]
I've [opened an issue on Homebrew/homebrew-core to address the brew package issue](https://github.com/Homebrew/homebrew-core/issues/47515), since crystal should really work by default for all Mac users without any extra required steps.

@RX14 Haha that's a fair point about macOS being a terrible OS for development, but I did just pick up a new MacBook yesterday 🤣
It's also extremely popular for Ruby / Rails developers, and it has a huge market share for Bay Area startups. I know Crystal is a distinct and unique language, but I think it's still a great idea to market it as "compiled Ruby with static types", and so it makes a lot of sense to treat macOS as one of the core platforms for Crystal developers.

In fact, it's very easy to get crystal to work out of the box on a Mac, it just needs a single line of code to set the `PKG_CONFIG_PATH`. It's the only thing I needed to get every running, compile the crystal compiler, and run the Crystal test suite. It doesn't seem like a huge deal to just add a few lines of code somewhere so that Mac users feel welcome and can get up and running without any trouble-shooting steps.

**Comment by RX14** [comment]
Of course we'll support and prioritise macos, more than half of the core team are probably using it as their development environment. In fact, I've been pushing for someone to fix the homebrew package [since this issue first appeared](https://github.com/crystal-lang/crystal-book/pull/312#issuecomment-450770179). I can't do it, since I can't test it, since I don't have a macbook!

But still, if *installed packages* are not in the pkg-config search patch out of the box, then that's by definition a broken build environment. And it needs a workaround (brew wrapper script) to fix it.

Sorry for my 2m rant :)

**Comment by Sija** [comment]
> Sorry for my 2am rant :)

2am?! 🙀 Which timezone r u in?

**Comment by RX14** [comment]
europe still exists as far as I know

**Comment by rdp** [comment]
Mentioned as fixed in 0.32.1 https://forum.crystal-lang.org/t/crystal-0-32-1-has-been-released/1503
