### ISSUE TITLE
Single quote warning failling for a string

### ISSUE THREAD

**Issue by jekroll** [crystal-lang/crystal#8555]
We all know that single quotes are wrong for Strings and that Crystal shows a warning for that kind of mistake.

Example of a warning:
    puts '---'
    Error: unterminated char literal, use double quotes for strings

However, I found an exception:
    puts '-'   #<--------- No warnings here and 'puts' works!!

Other example:
    [ "-", "abc", "def" ].select { |item|  item != '-' }
          Output:   ["-", "abc", "def"]   #string "-" is not removed and no warnings are shown

Any ideas?

**Comment by asterite** [comment]
Hi!

Single quotes are used for Char literals.

https://crystal-lang.org/reference/syntax_and_semantics/literals/char.html

**Comment by jekroll** [comment]
What about a warning to avoid comparing Char to String? Or better, make them comparable?

It seems too easy to make a mistake and not perceive it, as shown in the example:
[ "-", "abc", "def" ].select { |item| item != '-' }

**Comment by asterite** [comment]
A Char and a String are different types and they are not comparable. I think it would be confusing if `"a" == 'a'`.

It's a bit hard to make some types not be comparable between each other. It can break really bad because we have union types in the language, meaning that you could have something be a `String | Int32 | Char` and it should be comparable to any of those types.

Also, this was discussed in the past many times already and the conclusion is that we can't do anything about this unless we radically change the language.

**Comment by ysbaddaden** [comment]
And we don't want to radically change the language. Single quotes are Char. Double quotes are String.

Note: I'm always using double quotes in every languages nowadays. It's a good habit.
