### ISSUE TITLE
Time.now daylight savings time

### ISSUE THREAD

**Issue by benoist** [crystal-lang/crystal#858]
Hi,

I've noticed Time.now does not include daylight savings time.

Time.now yield
2015-06-25 08:41:40 +0100

Where Time.now in ruby for instance yields
2015-06-25 08:41:47 +0200

**Comment by asterite** [comment]
Right. For that we would need to parse and understand the timezones in the machine. That's a huge task right now so it'll have to wait. But if anyone wants to tackle it, our idea was to base it on C#'s classes, and also have a TimeWithOffset (maybe with a different name) type.

**Comment by jhass** [comment]
See https://github.com/manastech/crystal/pull/1521#issuecomment-141590795

**Comment by marceloboeira** [comment]
@asterite @jhass whats the status on that? I would like to give it a shot

**Comment by jhass** [comment]
141fe7029056f3e96eef6a2f71d690b8059e162f might've fixed or improved this, can somebody verify?

**Comment by benoist** [comment]
On OSx I get this
```
$ bin/crystal eval puts Time.now
Using compiled compiler at .build/crystal
2016-06-16 16:56:11 +0100
$ irb
2.3.0 :001 > Time.now
 => 2016-06-16 17:56:48 +0200
```

**Comment by marceloboeira** [comment]
OSX
```
icr(0.13.0) > Time.now
 => 2016-03-17 14:05:55 -0300
```

**Comment by asterite** [comment]
@benoist what's your time zone? Locally I get good results, but probably because of my time zone.

**Comment by benoist** [comment]
My normal time zone is Amsterdam (+0100), but to check I forwarded my clock to when daylight savings time is active. It should say +0200 in that period, but with latest crystal build it says +0100.

**Comment by ysbaddaden** [comment]
We just switched to DST in France, and thus I have the problem first hand.

There is no easy way to get the actual DST offset in POSIX just like we can get the timezone offset, since the `daylight` variable is merely a flag stating whether the current timezone may have DST in the past, present or future —the `timezone` variable that we currently use is the timezone offset only.

A solution could be to rely on `time.h` and more specifically use the `tm` struct and `tzset`, `mktime`, `gmtime` and `localtime` functions, and let libc handle the DST offset by itself (eg. set `tm_isdst` to -1 when populating the `tm` struct manually). The offset would be available as `tm_gmtoff`, which is non POSIX but seems to be available in most libc. It would require a refactor of the Time struct thought, since it currently doesn't use these functions.

The hard way would be to identify the timezone files (thanks to `tzname`) and load/parse/apply the rules ourselves, which is a lot of hard work... but could eventually lead to a TimeWithZone (or TimeWithOffset).

**Comment by ysbaddaden** [comment]
I experimented with the easy solution, and I can reliably handle the timezone+DST offset in a basic Time struct. It relies on the POSIX calls from my previous comment + a non POSIX but widely available `timegm` call (to transform a `tm` struct expressed as UTC to UNIX time, when `mktime` expresses the struct as local time). It works on Linux/glibc at least, I must still check on OSX and Linux/musl.

We can also manipulate the `TZ` environment variable (eg: `ENV["TZ"] = ":America/Buenos_Aires"`) then call `tzset` before calling `localtime` to translate a given time into another timezone. That would require a lock, since it's obviously not thread safe, and it may have bad performance too, but this is possible.

**Comment by asterite** [comment]
@ysbaddaden I'd say, let's do what is more simple right now, even if it's a bit slower. The most important bit here is to have specs that we can later use when we optimize this. For example, honoring `ENV["TZ"]` is a must so we can test the different time zones.

I tried to parse timezone files a long time ago but it was tedious, and we didn't have IO::ByteFormat back then. I guess eventually one of us, or someone else, will do this and we can do it the correct way. But in the meantime it's better to have something that works well :-)

**Comment by straight-shoota** [comment]
Could this issue be closed in favour of #4556?

**Comment by benoist** [comment]
I think it can as Time.now currently returns +0200 on my machine.

**Comment by straight-shoota** [comment]
Yes, `Time` has some time zone handling, but it is very limited. If that's already sufficient for your use case, that's great 👍
