### ISSUE TITLE
An option to make type inference a little dumber

### ISSUE THREAD

**Issue by kirbyfan64** [crystal-lang/crystal#861]
This is a little gripe I've had for a bit now.

Basically, I define a function. And use it. Everyone's happy.

But, then, I call it with the wrong arguments. Crystal makes the function argument a union type, and this accident may not show up for a bit.

It has also frequently happened that I accidentally forget a return somewhere, causing Crystal to change the return type to `XXX|Nil`.

All in all, it's a little confusing. I end up adding type annotations to various arguments (which oddly sometimes don't throw an error when called with the wrong types) and mentally tracing returns to figure out where a nil sneaked in.

My idea is some optional qualifier on function arguments (`strict`?) and return types that would cause Crystal to *not* automatically union-ize stuff.

**Comment by Exilor** [comment]
Just in case you missed it, you can specify the type of the return value of a method definition since 0.7.0. The compiler will tell you if the return value would be an unintended union.

**Comment by kirbyfan64** [comment]
@Exilor It didn't seem to always work, though. Sometimes, the result of a function call was the inferred type, not the type I gave.

**Comment by asterite** [comment]
One thing that we did consider, but never implemented, is that whenever you have:

```crystal
def foo(x, y, z)
end
```

neither x, y or z can accept nil. To accept nil you'd have to make the argument name have a question mark:

```crystal
def foo(x, y?, z) # y can be nil
end
```

That's because nil is the one that usually accidentally escapes.

@kirbyfan64 If you find a case where the return type restriction doesn't work, please report it.

When I get a type error like that (incorrectly changing the type of an instance variable, for example), I look at the stack trace and check which is the first method that incorrectly got that type. From there it's usually easy to understand why that happens, more if it was a recent change and you know what code you touched.

But it's true, this is the are that will need to improve the most to make it easier to work with the language, so ideas are welcome :-)

**Comment by ozra** [comment]
@asterite: Having to explicitly allow nil's with `id?` looks very good to me. On a side note: what notation is available to restrict/allow mutation of variables and arguments?

@kirbyfan64: It's a good idea you have: being able to restrict, not to a specific type, but to say "infer it, but only to _one_ type, if it's a union: it is not what I intended"

**Comment by stugol** [comment]
+1 for explicit nillable with ```?```. Swift does that.

**Comment by asterite** [comment]
I'm closing this as this is too general. Please reopen if there's a specific way we can improve the type inference algorithm (soon the errors will be more clear when instance, class and global variable will have to have a more obvious type specified, somehow).
