### ISSUE TITLE
Standardize `tls` arguments in HTTP objects

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#8663]
The `tls` argument has different values and typing depending on the methods in [HTTP::Client](https://crystal-lang.org/api/master/HTTP/Client.html) and [HTTP::WebSocket](https://crystal-lang.org/api/master/HTTP/WebSocket.html), among others:
- `tls = nil`
- `tls = false`
- `tls : Bool | OpenSSL::SSL::Context::Client = false`

The two first arguments don't make it obvious that we can pass a `OpenSSL::SSL::Context::Client` object; this can be the source of https://github.com/crystal-lang/crystal/issues/6395.
I saw that the `tls` argument was supported as back as `2016` when it was changed from the `ssl` name.

This different arguments versions can be standardized into a single one `tls` argument with the same default value and typing everywhere.
The options are:
- `tls : OpenSSL::SSL::Context::Client | Bool = false`
- `tls : OpenSSL::SSL::Context::Client | Bool | Nil = nil`
- `tls : OpenSSL::SSL::Context::Client | Bool | Nil = false`

Personally I prefer the first one, because the union is smaller.

**Comment by bcardiff** [comment]
The issue is that `OpenSSL::SSL::Context::Client` is not always available. `-Dwithout_openssl`

There is one idea to refactor how the sockets are wrapped with openssl that could us to get rid of the `-Dwithout_openssl` flag.

Decoupling the wrapper type `OpenSSL::SSL::Context::Client` in a generic argument.

```
class HTTP::Client < HTTP::BaseClient(OpenSSL::SSL::Context::Client)
end

class HTTP::BaseClient(SocketWrapper)
   # current code of HTTP::Client
end
```

The compiler, that compiles the http server and websocket for the playground uses the `Dwithout_openssl`. But other applications that might need to speak http through file socket might also find this useful IIRC.

**Comment by j8r** [comment]
Ok for the server, but not sure to fully understand the implications: there is already ` HTTP::Client#new(host : String, port = nil, tls : Bool | OpenSSL::SSL::Context::Client = false)` - and no issues so far on the client side?

**Comment by bcardiff** [comment]
It is fenced https://github.com/crystal-lang/crystal/blob/8f01a647044ef827939305fe11818d74745451ae/src/http/client.cr#L127-L155

**Comment by straight-shoota** [comment]
When we want to have `true` value meaning "I wan't TLS but just use the default", `false` obviously means "no TLS". Then `nil` doesn't make sense because it's equivalent to either of them. So I think the argument should not be nilable.

@bcardiff Using generics seems way to much overkill for this. Generics are for runtime differentiation, but whether we compile with openssl or not is entirely decided at compile time. Simply guarding OpenSSL type with a macro conditional should be enough.

The argument should everywhere be `tls : OpenSSL::SSL::Context::Client | Bool = false` by default and `tls : Bool = false` with `-Dwithout_openssl`.

**Comment by j8r** [comment]
We could do a trick like:
```cr
{% if flag?(:without_openssl) %} 
alias TLS = OpenSSL::SSL::Context::Client | Bool
{% else %}
alias TLS = Bool
{% end %}
```
And then having `tls : TLS = false`.

**Comment by j8r** [comment]
We could do a trick like:
```cr
{% if flag?(:without_openssl) %} 
alias TLS = OpenSSL::SSL::Context::Client | Bool
{% else %}
alias TLS = Bool
{% end %}
```
And then having `tls : TLS = false`.

**Comment by j8r** [comment]
We could do a trick like:
```cr
{% if flag?(:without_openssl) %} 
alias TLS = Bool
{% else %}
alias TLS = OpenSSL::SSL::Context::Client | Bool
{% end %}
```
And then having `tls : TLS = false`.

**Comment by bcardiff** [comment]
@straight-shoota I find that generics can be used to encode strategies without runtime penalties. It's a way to get program specializations. In this case, it also serves for getting rid of a dependency.

Very old example: https://github.com/bcardiff/crystal-experiment-program-specialization

**Comment by j8r** [comment]
Side design question: why having all this get, post, etc class method in `HTTP::Client`?
It generates lots of methods in the class, and they feels duplicated to their instance methods equivalent.
It doesn't also encourage to create one `HTTP::Client` instance, and then call methods.

**Comment by straight-shoota** [comment]
@j8r They are convenience methods when you simply need a one-off HTTP request.

**Comment by j8r** [comment]
I don't see how they are much more convenient @straight-shoota :
```cr
HTTP::Client.get("http://example.com")
HTTP::Client.new("http://example.com").get
```
Not worth to "pollute" the API IMHO with loads of methods.

It makes also the TLS argument typing harder compared to be only in the constructor.

**Comment by straight-shoota** [comment]
It doesn't work like this. `.new` receives the address and `#get` the resource. The relevant work happens in [`.exec`](https://github.com/crystal-lang/crystal/blob/41bd18fbea4aec50aad33aa3beb7a0bf30544186/src/http/client.cr#L851) which extracts address and requested resource from the URL and creates an appropriate client instance.

```cr
HTTP::Client.get("http://example.com/foo")
HTTP::Client.new("example.com").get("/foo")
```

**Comment by j8r** [comment]
Not a big deal for me, but I understand it's quite use-friendly.
I will propose a PR to see how to fix this issue.

**Comment by j8r** [comment]
I have a question about the private `HTTP::Client.tls_flag` class method: if there is `tls : OpenSSL::SSL::Context::Client | Bool = false` by default, this means raising if the URI is `https://example.com`?
I see 2 solutions:
- `tls : OpenSSL::SSL::Context::Client | Bool | Nil = nil`, which handle setting explicitly tls, giving a OpenSSL context, or letting Crystal deal with tls if necessary (nil).
- `tls : OpenSSL::SSL::Context::Client | Nil = nil`, which kind of break the `tls` toggle.

I prefer the first one, even if it increase the union and is a bit more complicated to deal with.

**Comment by j8r** [comment]
To sumup, 4 possibilities:
- I want to set my own `OpenSSL::SSL::Context::Client`
- I want TLS (`true`)
- I do no want TLS (`false`)
- I don't mind, deal with TLS if required (`nil`)

**Comment by straight-shoota** [comment]
I actually wouldn't worry about this individual detail because it needs to be assessed in context of an eventual redesign of HTTP::Client (see #6011). That might lead to changes to the API related to `tls` argument, anyway. So it doesn't make sense to change anything about it right now, when we need to look at the bigger picture.
The status quo needs improvement, but it's not an immediate necessity to do something about it.
