### ISSUE TITLE
Character added to string and read back doesn't match

### ISSUE THREAD

**Issue by kalafut** [crystal-lang/crystal#8680]
For a range of code points (55296 to 57343), if you add the character to a string and then read it back out, you always get 65533. The code below tests every code point and outputs mismatching ones:

https://play.crystal-lang.org/#/r/8dlf

```
(0..Char::MAX_CODEPOINT).each do |i|
  charToStringToChar(i)
end

def charToStringToChar(i)
  s = "" + i.chr
  ord = s[0].ord
  match = i == ord

  if !match
    puts "Error! Wrote: #{i}, Read: #{ord}"
  end
end
```

---
Crystal 0.32.1 (2019-12-18)
LLVM: 9.0.0
Default target: x86_64-apple-macosx

**Comment by straight-shoota** [comment]
This actually expected behaviour.

Crystal's `String` type is based on UTF-8 encoding. The codepoints U+D800 to U+DFFF (55296 to 57343) are invalid values in Unicode. `String` has some support for accepting invalid characters, so it doesn't immediately explode when it is fed arbitrary bytes. Appending a `Char` representing an invalid codepoint to a `String` is fine. But when you specifically ask for the first character, `String#[]` tries to read the UTF-8 character at position 0 and since it's an invalid value, replaces it with the unicode replacement character U+FFDD (65533).

**Comment by kalafut** [comment]
Ah, good to know!  I ran into it porting some code that’s basically using the code points as indexes into another structure (their actuals values in Unicode is irrelevant). I can easily enough exclude use of this range though. 

Thanks.

**Comment by straight-shoota** [comment]
For this use case, you could also consider using `Slice`.
