### ISSUE TITLE
Missing (deprecated) definition for Time::Span 

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#8825]
In [crystal/crystal-mysql](https://github.com/crystal-lang/crystal-mysql/blob/4c4737c22f69df7ab68e14a442b282f70430c281/src/mysql/types.cr#L225) the following construct is used

```cr
::Time::Span.new(0, time.hour, time.minute, time.second, nanoseconds: time.nanosecond)
```

Although it will be removed due to #8257, in master is totally gone already.

I think we should add that overload in case others uses them. I will update crystal-mysql for 0.34, but with the current situation I can't publish a patch release that will work with 0.33 and 0.34 (unless `{% if compare_version ...`). But the whole point of deprecated message is to allow the current shard version to compile on the new std-lib with warnings.

**Comment by straight-shoota** [comment]
This call works on both 0.33.0 and 0.34.0 if the nanoseconds are passed as positional argument instead of named argument.

And I don't think there could be any way to define method overloads that would accept such legacy call signatures without compromising deprecation messages. Maybe if we would introduce deprecation in multiple steps, but that seems way to complicated.
