### ISSUE TITLE
Add top-level has_constant? macro method (or expose Program type)

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#8914]
In #1585 `has_constant?` was added and allows you to check if a constant is defined within a type. But I think there is no hay to check if a top-level constant exists.

Adding a top-level macro method to check if the constant is defined in the internal `Program` type that holds the top level could look like:

```crystal
{{ has_constant?(:MyShard) }}
```

Or if we expose the top level as an alias we could directly use.

```crystal
{{ Program.has_constant?(:MyShard) }}
```

It can be useful to check if a shard is required or not. And to use feature checks instead of comparing versions.

**Comment by Blacksmoke16** [comment]
I think the latter would be better, as this is also an issue with like "getting methods on the top level", etc.

**Comment by asterite** [comment]
Actually, you can do this right now :-D

```crystal
{% puts @type.has_constant?(:Int32) %}
{% puts @type.has_constant?(:Int256) %}
```

https://play.crystal-lang.org/#/r/8qfs

`@type` at the top-level refers to the program.

That said, it's true that there's no way to explicitly refer to the top level...

But maybe we can do `@type.top_level` to access the top level from any type? That way we don't need to replicate all of the methods on `TypeNode` on the top level.

**Comment by Blacksmoke16** [comment]
Ahhh yes, the issue was more so having access to top level constants/methods when the macro itself is _NOT_ in the top level as well.

**Comment by asterite** [comment]
Then I still think it makes sense to expose the top level as `@type.top_level`. `Program` _could_ work but it can be quite confusing if there's an actual type called `Program`.

**Comment by jhass** [comment]
How about another "macro instance var" like `@toplevel`? having it as a method on `@type` somehow irks me since it's not really a property of a type node. And indeed `Program` isn't very explicit about what it is either.

**Comment by asterite** [comment]
Yeah, another macro instance var sounds good too.

**Comment by straight-shoota** [comment]
`@program`?

**Comment by RX14** [comment]
Why `Program`? Seems strange to tie the name to a badly named god object in the compiler. Top-level is what we call it everywhere else.

**Comment by bcardiff** [comment]
Program is probably a leak from the compiler internals. `@top_level` sounds about right.

**Comment by bcardiff** [comment]
The main benefit of `@top_level` vs `::has_constant?` is that this will allow other methods defined in `TypeNode` to be applied to the top level.

**Comment by RX14** [comment]
@bcardiff `::` should refer to the top-level type, and it should be a `TypeNode`. Just like `String.has_constant?` works right now, but with `::` referring to the top level.

**Comment by bcardiff** [comment]
I don't follow @RX14. If `::` is a value, then the syntax should be `::.has_constant?`. If `::` works in the same way as in the non-macro land, then is not a value; but a syntax that affect the constant resolution.

**Comment by RX14** [comment]
I'm just saying make `::foo` access `foo` on the top-level type node, just like `String.foo` would.

**Comment by asterite** [comment]
I initially thought it could be a good idea. However, if you do this at the top level:

```crystal
{% has_constant? :Foo %}
{% ::has_constant? :Foo %}
```

my initial thought would be that they are equivalent, since we are already at the top-level. So making `::` mean "but call it on the top level" is a bit confusing.

I think introducing a `@top_level` macro instance var is clearer.

**Comment by RX14** [comment]
@asterite why wouldn't they be equivalent? At the top level those should be equivalent.

**Comment by asterite** [comment]
But that means that in the compiler we'll have to do this:
- check if the method is a macro method for `Crystal::Macros`. Like `debug`, `puts`, etc.
- otherwise, check if the method is a macro method for the program TypeNode

I think it's a bit confusing. Specially if later on there's a TypeNode method that has the same name as ones in the top-level right now.

**Comment by Blacksmoke16** [comment]
FWIW I just noticed in the book that `The Program` is what is used to describe the "top level".  It never actually mentions "top level".  In that case it makes sense to have `@program`, or update the docs to use different language if we want to keep the "program" internal.

Ref: https://crystal-lang.org/reference/syntax_and_semantics/the_program.html

**Comment by straight-shoota** [comment]
I'd say they are different aspects. Still related but distinct. `top level scope` is where every code lives that is not in a deeper name space. But the program is the code that executes. That's about how I would put it. But it's hard to distinguish, especially since the term `program` has several connotations.

That page in the book needs some love, though. I was actually preparing to write a page on that and didn't even notice there is already one in the *Types and Methods* section.

**Comment by beta-ziliani** [comment]
We needed to get this fixed, so I create the PR using the `@top_level` name, which seems to be acceptable to most of us. I think we can then move on to improve and expand the documentation accordingly.
