### ISSUE TITLE
Not unified parsing of ambiguous suffixes `+` and `-`

### ISSUE THREAD

**Issue by max-codeware** [crystal-lang/crystal#9193]
As asked by @asterite I report here what I wrote in PR #9191.
Supposing to have this code:
``` crystal
def m(x)
  x
end

m = 10

puts(m -2) #=> 8
``` 
Crystal interprets the ambiguous suffix as `m.-(2)` giving the precedence to `m` as variable.

But if we wrote the same code in this way
``` crystal
def m(x)
  x
end

m = 10
b = 2

puts(m -b) #=> -2
```
what saw previously is no longer valid, and `m` is interpreted as a call.
IMO both the syntaxes should produce the same result like in Ruby, as I don't see why `-b` should be treated differently than `-2`. 

The same thing is valid for ambiguous `+`

**Comment by straight-shoota** [comment]
Both cases should behave the same way. But there is also good reason to reverse the semantics:
When the operator is surrounded by zero whitespace (`m-b`) or has whitespace on either side (`m - b`), it should clearly be interpreted as `m.-(b)`. But in case there is only whitespace before it, it seems like indicating a stronger relation to the argument, which would mean `m(-b)`.

However, even as this seems to make sense, it's probably not worth having a different behaviour for such an edge case. It's fine to force using parenthesis in order to indicate a method call.
