### ISSUE TITLE
HTTP::StaticFileHandler doesn't work well with HTTP::CompressHandler

### ISSUE THREAD

**Issue by digitalcora** [crystal-lang/crystal#9196]
`HTTP::StaticFileHandler` [includes a line](https://github.com/crystal-lang/crystal/blob/4401e90f001c975838b6708cc70868f18824d1e5/src/http/server/handlers/static_file_handler.cr#L79) that sets the `Content-Length` of the response to the size of the file being served. If `HTTP::CompressHandler` is also used, this length ends up being incorrect — usually it is larger than the actual size of the response, after compression. One consequence is that if the file is loaded in a web browser, the "loading" indicator will keep going forever, as the browser thinks there is more data to come (and the connection has not been closed, due to keep-alive).

Example code:

```crystal
require "http/server"

server = HTTP::Server.new([
  HTTP::CompressHandler.new,
  HTTP::StaticFileHandler.new(__DIR__),
])
server.bind_tcp("127.0.0.1", 8080)
server.listen
```

Put this in the same directory as a file of non-trivial size (like a screenshot image), then in a web browser, go to `localhost:8080/name_of_file`. When I tested this with a PNG file in Firefox, the image displayed, but the loading indicator kept going indefinitely. When I tested with Edge the image was not displayed at all, and the request was stuck on "pending" in the dev tools.

This can be worked around by ordering the `StaticFileHandler` ahead of the `CompressHandler`, but in that case the static file responses will not be compressed.

* Crystal: **0.34.0**
* LLVM: **8.0.0**
* Target: **x86_64-unknown-linux-gnu**

**Comment by straight-shoota** [comment]
This is only an issue with `CompressHandler`. Doesn't matter whether you use it with `StaticFileHandler`, could just be any handler that sets `Content-Length` header.

The implementation of `CompressHandler` is very simple and it can't fully work like that. There are other problems to. For example, it should not compress when the body is empty or a downstream handler sets `Cache-Control: no-transform` header.

Fixing all this means to act when the downstream handler starts writing the body but after headers have been set. Maybe a callback on `Server::Response` needs to be added for that?

**Comment by RX14** [comment]
@digitalcora Thanks for the report and finding the root cause!

@straight-shoota I don't think a new callback is needed, it's possible to do with a custom IO wrapper which would set headers right before anything is written to the `HTTP::Server::Response::Output`.

**Comment by waj** [comment]
@RX14 yes, that would be clever. I just wonder how are all the wrappers affecting the performance. Because there's already two defined in `HTTP::Server::Response` around the socket (add one if it's SSL) and the `CompressHandler` adds another one. This new wrapper would be just forwarding all calls except for the first one were it would check the headers? Maybe it's not a bad idea to add another callback to let the handlers check the headers one more time before writing.

Also, keep in mind that if `Content-Length` is not set, it's not possible to use `Range` headers later to resume downloads. Not that it's currently supported, but to keep that in mind for the future 😄 

Of course this is a bug and must be fixed, but current implementation of `CompressHandler` and `StaticFileHandler` are still quite naive and waiting for so much love.

**Comment by RX14** [comment]
All this can be refactored for performance later. I'd stick with the easiest solution, whatever that ends up being. Introducing new public API for callbacks would require more design thought, so if I were to implement it I'd go for another wrapper, but that's just me.

**Comment by waj** [comment]
@RX14 Sure! big 👍 from me. It's just some thoughts came to my mind when I read about this issue and I wanted to share related concerns.

**Comment by straight-shoota** [comment]
Such a callback doesn't need to be public API. It could just be internal and tailored for this exact use case. Implementation wise this might even be easier than another wrapper because you don't need to care about wrapping semantics.
