### ISSUE TITLE
Error: undefined method 'anchor_link' for Crystal::Doc:Module

### ISSUE THREAD

**Issue by 007lva** [crystal-lang/crystal#9260]
Hi, I've found this problem when tried to give support to Crystal 0.34.0 in [autolink.cr](https://github.com/crystal-community/autolink.cr).

This code:

```crystal
require "compiler/crystal/tools/doc/markdown"

text = "## This is title \n This is a [link](http://crystal-lang.org)"

puts Crystal::Doc::Markdown.to_html(text)
```

On 0.31.1:

https://play.crystal-lang.org/#/r/91am
> :ok_hand: 

Since 0.32.0:

https://play.crystal-lang.org/#/r/91an
> In /usr/lib/crystal/compiler/crystal/tools/doc/markdown/html_renderer.cr:35:25
>
> 35 | @io << Crystal::Doc.anchor_link(anchor)
>                          ^----------
>Error: undefined method 'anchor_link' for Crystal::Doc:Module

**Comment by straight-shoota** [comment]
`Crystal::Doc::Markdown` is an undocumented feature and only intended for internal use with the doc generator. You can technically use it if you want (since it's included in the compiler code available with the stdlib distribution), but it's not advised to do so. The API is private so it changes without warning. The implementation is also pretty flawed, that's why it was removed from stdlib.

Please use a publicly available and properly working Markdown implementation like https://github.com/icyleaf/markd instead.

**Comment by straight-shoota** [comment]
From what I see you're only using it in a spec to generate HTML from markdown source:

https://github.com/crystal-community/autolink.cr/blob/c27212593ce5d7869ed46d656ebbfeff3b7853f2/spec/autolink_spec.cr#L115

The spec works the same if you just provide the rendered HTML directly, instead of the Markdown source.

**Comment by 007lva** [comment]
I understand, thanks!
