### ISSUE TITLE
Cookies.add_request_headers Breaks Cookies

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#9306]
Simple example where original cookie `base64==` becomes `base64%3D%3D` after setting cookies to the new header.

```crystal
require "http"

cookie = "bar=base64=="
headers = HTTP::Headers.new
headers["Cookie"] = cookie
cookies = HTTP::Cookies.from_headers(headers)
new_headers = HTTP::Headers.new
cookies.add_request_headers(new_headers)
new_headers
```

**Comment by bararchy** [comment]
I can be fixed by using 
```crystal
class HTTP::Cookie
  def to_cookie_header(io)
    io << "#{@name}=#{@value}"
  end
end
```

Instead of the original version that encodes the name and value for URI based encoding

**Comment by jhass** [comment]
The original implementation does this already: https://github.com/crystal-lang/crystal/commit/e13fe256276c120c6c8805ef08b3804802e4678a#diff-c1c6aa063298b6e5bf89f770fbd00454R45

@netfeed do you remember the rationale?

Relevant RFC portions from https://tools.ietf.org/html/rfc6265#section-4.1

> ```
> cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
> cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
>                      ; US-ASCII characters excluding CTLs,
>                       ; whitespace DQUOTE, comma, semicolon,
>                      ; and backslash
> ```

> To maximize compatibility with user agents, servers that wish to
   store arbitrary data in a cookie-value SHOULD encode that data, for
   example, using Base64

It's said that there seems to be no effort to standardize cross implementation compatibility for this :/

**Comment by netfeed** [comment]
No sorry. Wrote that way too long ago.

**Comment by KimBurgess** [comment]
Just saw this exact issue in the wild.

As above, the spec itself only calls out a specific subset of disallowed characters. Although URL encoding of these values is common practice, it is not universal or specified.

The current implementation always [URL decodes when reading from headers](https://github.com/crystal-lang/crystal/blob/4401e90f001c975838b6708cc70868f18824d1e5/src/http/cookie.cr#L109), and then [re-encodes when writing](https://github.com/crystal-lang/crystal/blob/4401e90f001c975838b6708cc70868f18824d1e5/src/http/cookie.cr#L58-L62). In cases where a server has not used URL encoding a round trip does not correctly reflect the originally set value.

Perhaps a sensible default here could be to keep the current behaviour as standard, but introduce a parameter to `HTTP::Cookies.from_header` and `HTTP::Cookies#add_request_headers` and underlying methods to support disabling this. Let me know if this is of interest and I'll send through a PR.

**Comment by bararchy** [comment]
Why do we even handling encode\decode? maybe just send/receive as is, and let the client user decide is encoding is needed?

**Comment by KimBurgess** [comment]
IMHO, that's the correct approach.

The issue to resolve then becomes what happens when attempting to serialize a cookie that contains illegal characters, or perhaps more accurately, when instantiating `HTTP::Cookie`?
1. raise and `IO::Error` (on serialization), or `ArgumentError` (on instantiation)
2. encode the value (if so, what encoding?)

There also appears to be some related discussion to this in #8020.

**Comment by straight-shoota** [comment]
When looking at other implementations, I found Go is less strict on cookie values. 

It does *not* implicitly encode or decode any characters.
When writing it warns and drops invalid characters, when reading it errors on invalid characters.

The only "extra" thing is that commas and spaces are allowed and values including them are automatically wrapped in quotes. See https://golang.org/src/net/http/cookie.go#L357 (see also discussion in https://github.com/golang/go/issues/7243).

#10442 removed automatic encoding/decoding of the cookie name for security reasons. But I think we should also remove that for cookie values and instead make appropriate encoding/decoding values with invalid characters a responsibility of the user. Perhaps we can add a convenient method for that.

**Comment by security-curious** [comment]
Just my two cents on it since I was involved in #10442. Take or leave what you wish.

Automatic encoding seems good and is what the RFC suggests but since there is no standardization on the encoding used (Rack uses URL encoding, the spec suggests base64, Flask and Go do limited quoting) I think whatever is picked is bound to be incompatible with something else.

I like the idea of not forcing encoding as it allows the developer to choose whatever if most compatible with other systems they are using. Convenience methods for the common needs can be layered on top. I really like the way Go throws an error if you use an invalid character. That can help prevent against things like [header splitting](https://owasp.org/www-community/attacks/HTTP_Response_Splitting). If someone is using a convenience method they shouldn't ever hit the error but anyone setting raw cookie values could introduce a security issue.

I would suggest the name also have error handling for any invalid characters. I had just removing the encoding since it can cause a problem that the user can trigger and the developer cannot really fix. But the error handling will prevent a developer from unintentionally introducing a security issue.

As for how to layer the encoding on top it would be sort of annoying to constantly have to specify what encoding to use. I wonder if we could let the user specify the encoder/decoder via configuration similar to [sessions in rack)[https://github.com/rack/rack/blob/master/lib/rack/session/cookie.rb#L50).

Maybe provide:

* URL encoded - Compat with the Ruby world which would be relevant to many Crystal developers
* Base64 encoding - For compat with systems following the spec suggestion
* Limited quoting - Compat with system like Go and Flask

Finally a user could provide their own decoder/encoder for anything else. Is this over-engineering the problem? Outside the scope of Crystal and should be in a web framework (so Crystal just provides the error checking and passes everything else raw)?

**Comment by straight-shoota** [comment]
Thanks for your assessment, it's very welcome 👍 

I think offering different options for encoding is overkill. Crystal like Ruby has a focus on convention over configuration. There's no clear benefit for having multiple strategies. You only really need a single one in most use cases.

If we don't do any encoding and add the suggested validity checks, that works as a solid base.

On top of that we could provide a convenience layer using some kind of quoting/encoding, but one strategy should be fine. If you need something else for interoparability with other systems, the base feature should allow that.

The quoting approach sounds really nice to me. It passes the data through as raw unless it contains specific characters (comma or space) that would technically be considered invalid with the RFC anyways.
That means it acts completely transparent if you pass only valid data. So it's super easy to just use an encoding on top. There's no need to selectively choose a "raw" vs. a "safe" method because the same method unambiguously acts as both.
It's not 100% RFC compatible, but it looks like it really works in practice. It seeems this approach is also taken by Java ([SO](https://stackoverflow.com/questions/572482/why-do-cookie-values-with-whitespace-arrive-at-the-client-side-with-quotes)).
