### ISSUE TITLE
Sematic difference from Ruby : Syntax Suggestion

### ISSUE THREAD

**Issue by rebelwarrior** [crystal-lang/crystal#9336]
Going through the API I found these:

```crystal
Array#[]? #=> may return nil
Array#[]  #=> fails if out of bounds
```
In Ruby the `?` is a sign that a method returns a boolean. Contrast this with these methods from Rails:

```ruby
Model#save   #=> returns false if not saved due to validations.
Model#save!  #=> fails loudly if not saved due to validations.
```

Semantically it makes more sense for these to be the methods in Crystal:

```crystal
Array#[]   #=> may return nil
Array#[]!  #=> fails if out of bounds
```
This will keep it in line with the "meaning", the semantics of the Ruby API without changing any functionality. As Crystal is before v1 this would be the perfect time to do this breaking change.

**Comment by bcardiff** [comment]
@rebelwarrior that won't play nice with other parts of the std-lib design. It will force `[]!` to be more common than `[]`.

A related discussion can be found at #1034 to get into details of it.

I'm confident you won't find the current behavior disturbing at all. In Crystal `Nil` has a special treatment.

**Comment by asterite** [comment]
Hi and welcome!

This has been discussed to death in the past: https://github.com/crystal-lang/crystal/issues/1034

This is never going to change. Changing it will mean breaking **all** code out there. It would be really bad to do so right before 1.0.

@Blacksmoke16 and everyone: can we please stop using 👎 without giving a reason? Imagine you enter a forum or discussion, take the time to ask something, and immediately get a 👎 . How would you feel?

**Comment by RX14** [comment]
The TL;DR is that a `?` suffix in crystal has *dual* meaning: it may mean that it returns nil (typically with a raising method without `?`), or it may mean that it's a query method and returns a boolean (the same as ruby).

We find that in practice this is fairly unambiguous and works well.

**Comment by rebelwarrior** [comment]
The more differences there are with the say expectations set by Ruby the harder it is to port code and then more effort you have to put into watching the gotchas of the Crystal language like include? vs includes? 
While this is fine the cost should not be tossed away because it would cause a breaking change. In a pre-v1 is the time to massively change the language to experiment to try new things and see how they work.

This would not be a terribly difficult thing to change either. First you'd alias `[]!` to `[]` so people can change the code leisurely then warn of the change to `[]` and deprecation of `[]?` Then complete the swap. It takes a few versions but the first is not a breaking change as it adds an alias. 

The reason I'm proposing this is not cause I have a hard time learning a new API or that `[]?` is difficult. Not at all. It just that it introduces two unexpected changes:
1.  doesn't return a boolean
2 . doesn't follow the behavior of `[]` which return `nil` in Ruby. 

I'd feel remiss if I didn't at least state my case. It's inevitable that crystal will differ from Ruby syntax as they are different languages but they more they can follow the same "language expectations" the more synergy you get between them. The includes? include? change makes semantic sense. So it's a pain but a pain with a purpose. 

This change just introduces a new semantic rule `?` can return `nil` or the normal value in addition to being a sign the method returns a boolean, while the `!` is already established as a **fail** rather than return `nil` symbol, at least, in Rails. 
 
Thanks to all who explained your perspectives so kindly especially RX14 & asterite

**Comment by straight-shoota** [comment]
> This change just introduces a new semantic rule ? can return nil or the normal value in addition to being

This semantic rule is considered idiomatic in Crystal and used in many places, not just for Hash/Array accessors. Since Crystal has static type checking and special `Nil` type handling, it's necessary to be more specific with these things than Ruby. So there are essentially two alternative sets of methods:

1. `foo?` is nilable and `foo` is non-nilable (raises)
2. `foo` is nilable and `foo!` is non-nilable (raises)

Both are actually used in Crystal and it depends on the specific use case. No. 1 is used if the typical use case of the method expects it to usually work and return a value, and if not raise a meaningful error message. No. 2 is used if the method's success is optional and not having an actual return value in expectd to be normal behaviour.
In both cases there's always a different method (with `!` or `?`) suffix that provides the alternate behaviour if necessary. But the suffix-free method is always used as the default behaviour and varies between nilable and raising depending on the use case.

For hash/array accessors, you would usually expect to get a value and not have to deal with nilable return types. That's why the main method without suffix raises if the key is not found.

A related reason is the special meaning of `Nil` to designate a missing key doesn't work if the collection may contain `Nil` values. When calling `hash["foo"]` on a `Hash(String, String?)` returns `nil`, there's no way to know whether `nil` is the actual value for `"foo"` or it indicates that key doesn't exist. Such an ambiguity should be avoided in the default accessor, hence it raises in the latter case. You can use `[]?` to get a nilable return value, but this might not make sense when the values are nilable (in that case you need to use `#fetch(key, &)` which yields on missing key).
