### ISSUE TITLE
Error when extracting free variable from a union of generic types

### ISSUE THREAD

**Issue by KimBurgess** [crystal-lang/crystal#9498]
The compiler does not appear to play nicely when working with a union of similar types and attempting to extract the type they are generic over.

For example, passing a `Foo(A) | Foo(B)` to a method that accepts a `Foo(T)` will fail.
```crystal
a = [:foo, :bar, :baz].as(Array(Symbol) | Array(Int32))

def test(x : Enumerable(T)) forall T
  p! T
end

test a
```
```
Error: no overload matches 'test' with type (Array(Int32) | Array(Symbol))
```
https://play.crystal-lang.org/#/r/9aei

In an attempt to workaround this, the following compiles, but emits an incorrect type for T
```crystal
a = [:foo, :bar, :baz].as(Array(Symbol) | Array(Int32))

def example(x : Enumerable(T) | Enumerable) forall T
  p! T
end

example a
```
```
T # => Int32
```
https://play.crystal-lang.org/#/r/9afp

**Comment by straight-shoota** [comment]
It seems the problem here is that the compiler doesn't recognize it would need to apply multiple dispatch over the generic type union.

The workaround is actually expected, though. In a union, types are ordered alphabetically, so the normalized form of your type union is `Array(Int32) | Array(String)`. That's what the compiler matches against `Enumerable(T) | Enumerable`, so `T` is assigned `Int32`.

However, a union like `Enumerable(T) | Enumerable` doesn't really make sense. This should probably be folded to `Enumerable(T)` or `Enumerable`, probably depending on whether `T` is a free variable or a generic argument type.

**Comment by HankAnderson** [comment]
Exact duplicate of #8973

**Comment by KimBurgess** [comment]
Closing in favor of issue linked above.
