### ISSUE TITLE
Gitflow with patch branch

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#9504]
This is a followup from this comment https://github.com/crystal-lang/crystal/pull/9496#issuecomment-646002366

I am use to the gitflow model which there is an explanation [here](https://datasift.github.io/gitflow/IntroducingGitFlow.html).  I think we should adopt something like that here.  When a fix is needed for a point release we should cut a branch from master and apply a patch and then release it.  This means we can have PRs like https://github.com/crystal-lang/crystal/pull/9496 and not have to close them due to master being used to create hotfix releases.

**Comment by jhass** [comment]
I don't think we need to go full git-flow, also see  the note added to the original proposal of it at: https://nvie.com/posts/a-successful-git-branching-model/

But yeah, latest with 1.0 we'll need release branches  and a cherry-picking workflow anyhow, might as well start now.

**Comment by bcardiff** [comment]
On some releases we did that. In this case, the CI was unable to move to 1.0.0-dev and was also waiting for a fix that is included in 0.35.1. So as a way to keep the focus until 0.35.1 is released I chose to use master as that.

With 1.0 approaching we are going to revisit how to organize the PRs to be able to land in different maintained versions.

---

Since this is more a discussion I'm going to close the issue.
