### ISSUE TITLE
BigDecimal E notation (scientific) string parser bugs, (& proposed fixes)

### ISSUE THREAD

**Issue by stevegeek** [crystal-lang/crystal#9547]
Hi all, and thanks for all the amazing work on Crystal! This is my first foray into crystal so let me know if there is anything wrong/mis-understood.

I noticed `BigDecimal#initialize` parses E notation numbers from strings incorrectly in some cases. I believe the issues could be boiled down to the following types of problem:

- `e1` : raises `Invalid BigInt: e1 (ArgumentError)`
- `1e-` :  raises `Invalid UInt64:`
- `1e.` :  raises `Index out of bounds (IndexError)`

ie errors in parsing logic and some leaking of underlying implementation detail (more examples can be seen in the specs in the branch compares below). 

Fixes available in #9577

**Comment by asterite** [comment]
@stevegeek Thank you for the bug report!

I suggest cleaning up the text in the issue to just mention the parsing bug, then creating separate issues for each of the things that you'd like to discuss. Otherwise it will be a mess of discussion, trying to tackle many things at once. For example the output of `BigDecimal#to_s` has nothing to do with the bug reported here. Improving the parsing using a grammar is also good, but in #9552 I could fix it without doing any of that so I would extract that as a "feature" or RFC.

Thank you!

**Comment by asterite** [comment]
Same goes for whether to use a specialized exception or not. In my opinion it should just be `ArgumentError`.

**Comment by stevegeek** [comment]
@asterite Ok, will do! The proposed fixes from https://github.com/crystal-lang/crystal/compare/master...stevegeek:fix_e_notation_big_decimal do tackle the changes without any immediate big changes, I will have a look at #9552 and compare! The RFC idea sounds good too, will create tickets accordingly soon

**Comment by asterite** [comment]
@stevegeek Oh, sorry, I missed those changes. Next time I recommend directly sending a PR with them, it's much easier to track, review, etc.

**Comment by stevegeek** [comment]
hey, just wanted to say I haven't abandoned this, will get on and sort out as soon as I can!
