### ISSUE TITLE
WebSocket connection not cleanly closed

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#9563]
When I close a WebSocket connection from Crystal, I got in both Firefox and Chrom(ium):
`close { target: WebSocket, isTrusted: true, wasClean: false, code: 1006, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }`

I was wondering why the property `wasClean` of `close` is `false`.

JavaScript code to reproduce:
```js
const socket = new WebSocket('ws://localhost:8080');
WebSocket.binaryType = "arraybuffer"

socket.onclose = event => {
  console.log('Connection closed ', event.reason);
  console.log(event);
};
```

As far as I understand of closing a WebSocket connection works:
- A closing frame is sent (opcode 0x08) (good)
- The frame may contain a body that indicates the reason for closing (good)
- If either side of a connection receives a close frame, **it must send a close frame in response** (not sure Crystal does that properly?)
- No more data should be sent over the connection
- Once the close frame has been received by both parties, the TCP connection is torn down

**Comment by j8r** [comment]
Additional note, it only happens when `HTTP::Server#close` is called. Can be related with `RequestProcessor`.

**Comment by waj** [comment]
`HTTP::Server#close` doesn't call `close` on each individual websocket. If the server process exits after that, then you'll see those unclean close on the client side. The same happens if you suddenly kill the server.

Actually even with non-websocket connections, all it does is not pay attention to the keep alive and close the connection once the request is completed. But it doesn't wait for each request to be gracefully completed and I'm not sure it should. In any case you can store a list of all the current websockets and call to `close` on all of the before exiting the process.

**Comment by j8r** [comment]
Thanks @waj , yes I was thinking doing that - no much other choice.

I was expecting `HTTP::Server` closing gracefully the connections, because [it is specified in the API doc of the method](https://crystal-lang.org/api/0.35.1/HTTP/Server.html#close-instance-method):
> def close
>
> Gracefully terminates the server. It will process currently accepted requests, but it won't accept new connections.

**Comment by waj** [comment]
Hmm.... good point. That should probably say something like "it let the current requests to be processed" but is not that it blocks until all the requests are done. Either that or make it really blocking, but I'm afraid that could add an extra overhead on every request that is barely needed.

**Comment by straight-shoota** [comment]
Related: #5957
