### ISSUE TITLE
BUG: Array index assignments at the end of array with range operator doesn't raise an error.

### ISSUE THREAD

**Issue by Geo-7** [crystal-lang/crystal#9574]
Hi,
```
a = [] of Int32
a[0]=1000
a[1]=5
a[2]=12
```
doesn't compile with Error:
Unhandled exception: Index out of bounds (IndexError) 

But it doesn't raise an error with range operator:
```
a = [] of Int32
a[0..]=1000
a[1..]=5
a[2..]=12
```

Crystal 0.35.0 [3c48f311f] (2020-06-09)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

For reference: This came up in https://forum.crystal-lang.org/t/why-do-we-need-a-range-operator-for-array-index-assignments/2304

**Comment by HertzDevil** [comment]
Those ranges refer to the empty subrange of elements at the end of the array, so every call replaces the empty subrange with the given value. The same also happens for start indices that are within range, effectively behaving like `#insert`:

```crystal
x = [0, 1, 4, 9, 16, 25]
x[3...3] = 36
x # => [0, 1, 4, 36, 9, 16, 25]
```

Thus one could reason that `x[6..] = 36` should behave like `x.insert(6, 36)`, which is indeed the case.

[This is by design](https://forum.crystal-lang.org/t/why-do-we-need-a-range-operator-for-array-index-assignments/2304/16). All range-like methods in the Crystal's standard library should handle empty ranges at the end like this.
