### ISSUE TITLE
Scope of variables in case statements are not local!

### ISSUE THREAD

**Issue by u89012** [crystal-lang/crystal#9588]
This caught me by surprise and I'm sure I won't be the only one. Any reason why the variable bar isn't scoped local here? 

```
foo = 1

case foo
when 1
  bar : Int32
  bar = 1
  # baz(bar) #do something...
when 2
  bar : Float32 # fails here with "Error: variable 'bar' already declared"
  bar = 1.1
  # baz(bar) #do something...
else
end
```

**Comment by jhass** [comment]
Because control flow statements don't make a new scope in Crystal. This  is inherited  from Ruby.

I'm  afraid it's an too inherent property of the language to change now.

**Comment by u89012** [comment]
Makes sense. But I think this makes writing any reasonable real world usage within these statements a real pain -- the case block has bitten me twice already and it makes me nervous as I'm porting a large application over! Now, I don't know the complexity involved but it'd be really great if this could be addressed before hitting 1.0 and things freeze over for the long term.

**Comment by jhass** [comment]
I think it actually would break too much  existing code that relies on this in  a subtle way.

IME if this bites you, chances are high that your methods are too long anyhow and would benefit from extracting smaller methods describing each action, or even service classes (or structs Crystal).

**Comment by u89012** [comment]
I'm sure it will break a lot of code that relies on this odd behavior but I beg to disagree about the size of the code that makes this issue surface. For example:

```

server = HTTP::Server.new do |c|
  case c.request.path
  when "/signin"
    # email : String?
    # password : String?
    if false
      email : String = c.request.query_params["email"]
      password = c.request.query_params["password"]
      foo : Int32 = 1
      find_user(email, password)
    end
  when "/signup"
    # foo = 1.1
    email = "foo"
    new_user(email, password)
  else
  end
end
```

The following immediately stands out:

1. Email variable is visible to "/signup" despite being declared inside an if. So now, not only do I have to be careful about not declaring it at top level, it looks like I have to worry about not reusing the name at all (if and when the type changes in the following branches).
2. If I comment out the assignment ```email = "foo"``` in the "/signup" branch, I get this error -- ```Error: read before assignment to local variable 'email'``` which means there's a clear distinction between the different branches when it comes to assignment and uninitialized vars but yet somehow it looks like it's ok to take in variables declared above not meant for this branch.
3. I thought ```if false``` would be optimized away to a noop but isn't (may be the release mode does it, but I haven't checked) which would mean email, password and foo shouldn't be visible further down the line at all. Or do they?

I love Crystal and I'm willing to definitely work around these rough edges but I'm sure you'll agree these gotchas are annoying and could/would trip up people coming from other languages easily not to mention they become edge cases that one will have to accumulate and have to remember to avoid in the future. I'd rather Crystal be as gotcha free as possible. I'd love to hear more thoughts about this.

**Comment by jhass** [comment]
It seems a little artificial, I wanted to give a variant of how I would write this, but then got confused as to what each action does, where does `email` and `password` come from in the`signup` branch? Where and for what are the return values of `new_user` and `find_user` used?

> the size of the code

Yes sorry, that was bit misleading. I meant "too long" not only on a LOC perspective, but more importantly also from a SRP perspective. In your example we can identify four responsibilities:

* Starting an HTTP server
* Recognizing a request path
* Extracting query parameters based on the request path
* Dispatching to other methods based on the request path with the extracted data

I think it's easy to argue it's doing "too much".

Declaring local variables is not idiomatic Crystal. Period. I'm not sure why this syntax was even added, I've never used it and never have seen it used in the standard library.

Variable name reuse is not an issue if all the branches do is delegating to a method that has the responsibility of extracting the context specific query parameters and then delegates to the next method with the next responsibility.

Regarding 2., Ruby would give you `nil`'s here, yeah. I guess this is a trade-off Crystal makes in order to reduce nilability a bit.  Anyways relying on variables declared in another branch of a condition seems weird and probably an artifact from what I already tackle in my first and second point.

Regarding 3.: Crystal does essentially no optimization at parse stage and little to none during semantic phase. However local variable declaration already happens at parse stage. The vast majority of optimization happens by LLVM on LLVM IR, so quite some abstraction levels away from any Crystal code. Thus unfortunately there's little to reason about changed behavior through optimization on the Crystal code/syntax level. However it would be terrible if semantic analysis is affected by release optimizations anyhow, I'm not sure why you would expect that.

**Comment by asterite** [comment]
@u89012 In Crystal's style it's very, very, **very** uncommon to explicitly type local variables. The syntax is just there so you can do `property x : Int32` which is a declaration of a local variable. It works inside methods as regular local variables because... it makes sense for that to work. But in general, I'd say 99.9999% of the cases nobody programs like that (in Crystal!).

If you remove those type restrictions, the code will work fine. Inside each `when` the variable will have the type that was assigned in that branch, and it will only merge all those types outside of the case. Then you don't need to be careful about not reusing names, because the types are actually scoped.

Try removing those type annotations and you'll see how easy it is.

By the way, Ruby works exactly the same and there are thousands if not millions of programs (mostly websites) out there, including Shopify, Basecamp, etc. You can do solid things with Ruby, so even though this might look like a big issue, it really isn't (or people workaround it really well).

**Comment by u89012** [comment]
@jhass I snipped the code in the signup branch to highlight the fact that Crystal complains about uninitialized variables well. Email and password would be fetched from posted data of course again the signup branch (which brings me to point that the HTTP module doesn't seem to have an easy way to access posted data and requires a Params.parse on body thus having me resort to using query_params to demonstrate, but that's another issue altogether).

I love having to not declare the types. I included them here to signal my intentions to you gentlemen for this post. 

I totally understand what you mean by the single responsibility of a piece of code but that topic is entirely subjective and I don't want to venture there -- I want to play with ideas before committing to refactoring to extract individual functions. 

About the optimization being far from the parsing -- if the left hand doesn't know what the right is doing, then we certainly are in for surprises -- I'd like to know that the intent specified in the source is translated with as few surprises as possible. 

Anyway, it looks to me that certain ideas which are fine in Ruby are not a great fit when it comes to modern strongly typed language such as Crystal. My two cents.

@asterite I agree with you and I love having to not declare the types, only included to show what I was trying to do. The basis for this post, the variable name showing up in branches further down still is what I intended to primarily highlight.

**Comment by asterite** [comment]
When I implemented `x : Int32` I decided that `Int32` will be the type for the entire method. Maybe it shouldn't be that way. But if not, it would be a bit confusing:

```crystal
x : Int32 = 0
x = "hello" # Now this is valid!
```

It's a bit confusing, essentially making the type annotation useless.

> the variable name showing up in branches further down

If you don't use type annotations, and given that Crystal will check that you use types correctly, I don't think it's an issue that variables appear later on. For example if you overwrite them outside of the `case` statement then their type will be that new type, not the old one.

**Comment by u89012** [comment]
@jhass @asterite Ah! I see what you mean by types being merged. Thank you for all the explanation and your time. Guess I get to unlearn something today -- declaring local variables! Keep up the good work guys!

**Comment by u89012** [comment]
Oh a little note in the documentation would help the others in my opinion. How to word this I'm not sure! I'll post something here if it comes to me.

**Comment by asterite** [comment]
@u89012 Thank you for the patience and calm discussion! 🙏
