### ISSUE TITLE
BigDecimal to_s bug

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#9715]
The code of handling negative value  in BigDecimal to_s is slight wrong
it will make
puts BigDecimal.new(-1234,4) => -.1234
Since -.1234 is invalid crystal code, so I assume it's wrong

The code is:
```
  if @scale >= s.size && @value >= 0
      io << "0."
      (@scale - s.size).times do
        io << '0'
      end
      io << s
  elsif @scale >= s.size && @value < 0
      io << "-0.0"
      (@scale - s.size).times do
        io << '0'
      end
      io << s[1..-1]
    else
      offset = s.size - @scale
      io << s[0...offset] << '.' << s[offset..-1]
  end
```

Which should be 
```
    if @scale >= s.size && @value >= 0
      io << "0."
      (@scale - s.size).times do
        io << '0'
      end
      io << s
    elsif @scale >= (s.size-1) && @value < 0
      io << "-0."
      (@scale - s.size).times do
        io << '0'
      end
      io << s[1..-1]
    else
      offset = s.size - @scale
      io << s[0...offset] << '.' << s[offset..-1]
    end
```

**Comment by dukeraphaelng** [comment]
Hi all.

I agree with @femto 's statements here. In this comment, I would like to further elaborate on this issue.

In the following code snippet of all floating-point like number structs (i.e. `Float32`, `Float64`, `BigFloat`, `BigDecimal`), `0.23`, `"0.23"`, `".23"`, `-0.23`, `"-0.23"`, `-".23"` are in turn `.to_s`, and whilst all structs return results in the format of either `"0.23"` or `"-0.23"`, only `BigDecimal` in the example of `"-0.23"`, `-".23"` returns `"-.23"`. This should be corrected so that numeric values conform to the same format.

`
require "big"

# Float32

(0.23).to_f32.to_s # # "0.23"
("0.23").to_f32.to_s # # "0.23"
(".23").to_f32.to_s # # "0.23"

(-0.23).to_f32.to_s  # # "-0.23"
("-0.23").to_f32.to_s # # "-0.23"
("-.23").to_f32.to_s # # "-0.23"

#Float64

(0.23).to_f64.to_s # # "0.23"
("0.23").to_f64.to_s # # "0.23"
(".23").to_f64.to_s # # "0.23"

(-0.23).to_f64.to_s  # # "-0.23"
("-0.23").to_f64.to_s # # "-0.23"
("-.23").to_f64.to_s # # "-0.23"


#BigFloat

(0.23).to_big_f.to_s # # "0.230000000000000009992"
("0.23").to_big_f.to_s # # "0.23"
(".23").to_big_f.to_s # # "0.23"

(-0.23).to_big_f.to_s # # "-0.230000000000000009992"
("-0.23").to_big_f.to_s # # "-0.23"
("-.23").to_big_f.to_s # # "-0.23"

#BigDecimal

(0.23).to_big_d.to_s # # "0.23"
("0.23").to_big_d.to_s # # "0.23"
(".23").to_big_d.to_s # # "0.23"

(-0.23).to_big_d.to_s  # # "-.23"
("-0.23").to_big_d.to_s # # "-.23"
("-.23").to_big_d.to_s # # "-.23"`

Taking a closer look at the source code for `BigDecimal`

`
def to_s(io : IO) : Nil
    factor_powers_of_ten

    s = @value.to_s
    if @scale == 0
      io << s
      return
    end

    if @scale >= s.size && @value >= 0
      io << "0."
      (@scale - s.size).times do
        io << '0'
      end
      io << s
    elsif @scale >= s.size && @value < 0
      io << "-0.0"
      (@scale - s.size).times do
        io << '0'
      end
      io << s[1..-1]
    else
      offset = s.size - @scale
      io << s[0...offset] << '.' << s[offset..-1]
    end
  end
`

One can see that this issue is caused by the final `else` clause in this `if..else` block. Specifically, `io << s[0..offset]` does not add a 0 digit before the `.` if the `@value` is below 0. This can be fixed easily by adding an extra condition before `else` as follows:

`
    elsif (offset = s.size - @scale) == 1 && @value < 0
      io << "-0." << s[offset..-1]
`

If the Crystal maintainers are in agreement that this is an issue worth addressing, and this solution is preferable, please reply and I'd be happy to make a PR for this issue, as I have already had this pass specs.
