### ISSUE TITLE
BigDecimal <=> bug

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#9718]
puts 1<=>BigDecimal.new("-0.2") #=>2
puts BigDecimal.new("-0.2")<=>1 #=>-2

the result is weird, should be -1,1,0 like ruby

**Comment by asterite** [comment]
Hi! Check the docs on our Comparable: https://github.com/crystal-lang/crystal/blob/master/src/comparable.cr

The result is positive, negative or zero. The number doesn't matter because you use those numbers compared with zero. I don't think it matters that we don't return exactly the same values as Ruby.

Put another way: how does this affect you?
