### ISSUE TITLE
Naked macro cause previous code doesn't compile: Error: unexpected token

### ISSUE THREAD

**Issue by arloan** [crystal-lang/crystal#9798]
main.cr:
```crystal
A = {a: 1, b: 2, c: 3}

v = {
  {% for n, v in A %}
  {{n}}: {{v}},
  {% end %}
}
puts v
```

compile result:
```
In main.cr:1:9

 1 | A = {a: 1, b: 2, c: 3}
             ^
Error: unexpected token: 1
exit status 1
```

Crystal version:
```
 crystal -v
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by asterite** [comment]
The reason is that when you do `{{n}}` the location of that node is preserved, so the error points to the `a` or `1` that you had in the node you copy information from.

Maybe this wasn't a good change after all.

In any case, macro expressions need to be valid **complete** expressions. In your case you need to write this:

```crystal
A = {a: 1, b: 2, c: 3}

v =
  {% begin %}
  {
    {% for n, v in A %}
    {{n}}: {{v}},
    {% end %}
  }
  {% end %}

puts v
```

**Comment by arloan** [comment]
@asterite 
Thank u so much.
I guess putting the original macro lines into a macro method makes those things becoming **complete** expressions so they compile, am I right?

```crystal
A = {a: 1, b: 2, c: 3}

macro make_tuple
  {
    {% for n, v in A %}
    {{n}}: {{v}},
    {% end %}
  }
end

puts make_tuple
```
