### ISSUE TITLE
Inconsistent #[]? behaviour with null pointers

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#9870]
Tested on d44530d88. Some containers always return `nil` instead of `Pointer(T).null` when `#[]?` is called, even if the index is within bounds:

```crystal
nullptr = Pointer(Void).null

arr = [nullptr]
arr[0]  # => Pointer(Void).null
arr[0]? # => nil

hsh = {0 => nullptr}
hsh[0]  # => Pointer(Void).null
hsh[0]? # => nil

tup = {nullptr}
tup[0]  # => Pointer(Void).null
tup[0]? # => Pointer(Void).null
```

This affects all `Indexable` containers except `Tuple`, and `Hash`. It is most likely due to their implementations of `#fetch`, which backs `#[]?`. Reduced example:

```crystal
class MyContainer
  def check_index_out_of_bounds(&)
    yield if false
  end

  def fetch(index)
    check_index_out_of_bounds { return nil }
    Pointer(Void).new(index)
  end
end

p MyContainer.new.fetch(0) # => nil
p MyContainer.new.fetch(1) # => Pointer(Void)@0x1
p typeof(MyContainer.new.fetch(0)) # => (Pointer(Void) | Nil)
```

Here the first line should also return `Pointer(Void).null` instead of `nil`.

**Comment by asterite** [comment]
The issue is broader:

```crystal
z = true ? Pointer(Int32).null : nil
p typeof(z) # => (Pointer(Int32) | Nil)
p z.class # => Nil
p z # => nil
```

It seems that when a null pointer is combined with `Nil`, the result is `nil` and the type information is lost.

**Comment by asterite** [comment]
I think the issue is that we represent the type `Pointer(T) | Nil` as just a pointer. `nil` or null pointer then have the same representation.

This was done so that for a C call you could allow a function to receive `Pointer(T) | Nil` and pass `nil` if you need to, instead of `Pointer(T).null`. That way you kind of have type-safe pointers also, where you either use a pointer that is not null, or `nil`.

Before changing this, what's your use case? Maybe instead we can document it as a punt.
