### ISSUE TITLE
`crystal docs` fails if I reference a lib constant from a doc comment

### ISSUE THREAD

**Issue by ashtneoi** [crystal-lang/crystal#9928]
## Details

I seem to have found a way to crash `crystal docs`, using Crystal 0.35.1:

```none
[nix-shell:~/repro]$ cat xyz.cr
lib LibFoo
  BAR = 0
end

# `LibFoo::BAR`
def qua
end

[nix-shell:~/repro]$ crystal docs xyz.cr --project-name=jkl
Unhandled type in `kind`: LibFoo (Exception)
  from ../../../build/source/src/compiler/crystal/tools/doc/type.cr:311:0 in 'kind'
  from ../../../build/source/src/compiler/crystal/tools/doc/type.cr:134:5 in 'path_to'
  from ../../../build/source/src/compiler/crystal/tools/doc/type.cr:366:10 in 'path_to'
  from ../../../build/source/src/compiler/crystal/tools/doc/markdown/doc_renderer.cr:171:5 in 'process_line'
  from ../../../build/source/src/compiler/crystal/tools/doc/markdown/parser.cr:130:5 in 'process_paragraph'
  from ../../../build/source/src/compiler/crystal/tools/doc/markdown/parser.cr:14:11 in 'doc'
  from ../../../build/source/src/compiler/crystal/tools/doc/templates.cr:10:25 in 'to_s'
  from ../../../build/source/src/string.cr:4789:5 in 'generate_types_docs'
  from ../../../build/source/src/file.cr:132:5 in 'docs'
  from ../../../build/source/src/compiler/crystal/command.cr:89:7 in 'run'
  from ../../../build/source/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from ../../../build/source/src/crystal/main.cr:105:5 in 'main'
  from __libc_start_main
  from ../sysdeps/x86_64/start.S:122:0 in '_start'
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

If I replace `` `LibFoo::BAR` `` with `asdf`, the docs build properly.

## Environment

I installed Crystal using Nix (nixpkgs commit [cb0908a8](https://github.com/NixOS/nixpkgs/tree/cb0908a810631510674e8bfd8fd40d226c824b96/pkgs/development/compilers/crystal)).

```none
[nix-shell:~/repro]$ crystal --version
Crystal 0.35.1 (2020-11-17)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu

[nix-shell:~/repro]$ which crystal
/nix/store/m0bsb3xqy73v0cmpm9zmv77vxl9dxmxg-crystal-0.35.1/bin/crystal

[nix-shell:~/repro]$ uname -rvmpio
3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 unknown unknown GNU/Linux
```

**Comment by straight-shoota** [comment]
The reason is probably that lib types themselves are not included in the API docs and thus there's no handler for referencing them.
But it should obviously be possible to name it. It just shouldn't be linked.

**Comment by straight-shoota** [comment]
My initial assumption was wrong. The culprit is actually that the docs generator does not consider nested types of types that are excluded from documentation to be also excluded. So this is not a specific bug to lib, but most other cases don't raise an exception later on.

Another example:
```cr
# :nodoc:
module Foo
  module Bar; end
end

# `Foo::Bar`
def foo
end
```
`Foo::Bar` renders as `<a href="Foo/Bar.html">Foo::Bar</a>` despite `Foo::Bar` not existing the documentation (because `Foo` is `:nodoc:`).

So the doc generator's `must_include?` needs to take the namespace into account and recognize that a feature in an excluded namespace cannot be included.

That's probably not that hard to implement, but it's gonna require some effort to get it right (needs lots of testing to be reliable). When we get rid of the immediate error breaking the docs genrator (fixed in #9931), it's also not super urgent. So I'd prefer to tackle the larger problem with an inevitable doc generator overhaul (sometime after 1.0). I'll create a new issue to track that.

**Comment by Blacksmoke16** [comment]
@straight-shoota Isn't that https://github.com/crystal-lang/crystal/pull/9819?

**Comment by straight-shoota** [comment]
Whoops, totally right. I even reviewed that. But it's still missing in master. And no specs ;)
