### ISSUE TITLE
[RFC] Make File.size return Int64

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#9969]
It currently returns `UInt64`. If you do something like `File.size(filename) - 100` it can underflow, which is really annoying.

In general we shouldn't be returning unsigned types in public APIs. Ever. Unsigned types are bad, bad, bad.

**Comment by wontruefree** [comment]
Why are unsigned types so bad?

**Comment by mattrberry** [comment]
I'm just curious: what is the concern with returning unsigned types? I'm all for the consistency of making it a signed type, but what's the concern with unsigned?

**Comment by j8r** [comment]
For reference Rust uses u64 and Go int64.

On one hand `Int64` is more practical for common operations (like @asterite's example), but on the other hand, `#to_i` is not very a big deal, and will likely be needed anyway, because `UInt64` is much less common than `Int32`. It also makes sense to return an unsigned integer because a file's size can't be negative.

**Comment by straight-shoota** [comment]
Unsigend types can lead to nasty overflow errors when you use them for regular math without paying attention to the definition range. `File.size` can easily be used in a computation that includes subtraction and may lead to negative values. It's hard to remember that you need to keep an eye up for this, because humans are used to working with negative numbers quite fine. So it's better to avoid that pitfall by returning Int64 and you have to worry about one gotcha less.
The only downside is that it can't express file sizes above `Int64::MAX`, but that should have no practical impact. When you're working with file sizes in the exabytes, you'll likely need a bigger data type anyway and UInt64 only doubles the size.

**Comment by konovod** [comment]
> #to_i

How would it help? Converting to `Int32` will break applications with files > 2GB, so shouldn't be considered a good practice. Using `to_i64` makes returning `UInt64` useless - why couldn't library do it for a user.
Correct way of working with unsigned numbers is to carefully construct all expressions with them, to be sure that they won't underflow. This could be useful for a system programming language, but I think signed integers are just plainly better in this case.

**Comment by straight-shoota** [comment]
It's `#to_i64` of course.

**Comment by asterite** [comment]
@mattrberry Can you spot the bug in this code without running it?

```crystal
# Read the last 10K bytes of README.md
filename = "README.md"
size = File.size(filename)
File.open(filename) do |file|
  file.pos = {size - 10_000, 0}.max
  file.gets_to_end
end
```

**Comment by mattrberry** [comment]
> @mattrberry Can you spot the bug in this code without running it?
> 
> 
> 
> ```crystal
> 
> # Read the last 10K bytes of README.md
> 
> filename = "README.md"
> 
> size = File.size(filename)
> 
> File.open(filename) do |file|
> 
>   file.pos = {size - 10_000, 0}.max
> 
>   file.gets_to_end
> 
> end
> 
> ```

Ah, I see the problem there. I personally would have done something like the following, just because I would assume that File.size would be unsigned.
```crystal
file.pos = size >= 10000 ? size - 10000 : 0
```
Looking at your example though, it makes it clear to me why Int64 would be preferred here. Both your example and mine work with signed ints, but only mine works with unsigned ints. Making it return a signed int allows for more ways to work with the number without introducing bugs the programmer might not have expected.
Thanks for the example!

_Hopefully the formatting looks fine, I'm trying out the github mobile app :p_

**Comment by asterite** [comment]
Cool!

That was actually the code that motivated me to propose changing it to a signed value. There are ways to make it work with unsigned, like what you wrote, but if you forget about it then in some cases the code will work, and in some cases you'll find out it doesn't, at runtime. It's not that bad because you get an underflow exception. In other languages, for example C, the value would just wrap and you'll get a silent bug.

**Comment by asterite** [comment]
Also note that unsigned values do have use cases. I think in emulators they might be used a lot, but operations on them are well defined by the machine, I guess. Using unsigned values as checksums is also probably fine. But as soon as there's a chance to use the value with some math operations then there's a chance things will be a bit unexpected or not intuitive.
